### ISSUE TITLE
v2ray is auto-enabled after reboot

### ISSUE THREAD

**Issue by zerobikappa** [v2rayA/v2rayA#100]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2raya 1.0.1-1
2. 你通过什么方式安装v2rayA
yay (from aur repo of archlinux)

3. 你所使用的操作系统
archlinux

### 描述问题：

I disabled `v2ray` and `v2raya` services due to I want to manually start `v2ray` and `v2raya` services every time only when I need to run it. However, if I reboot the computer with `v2raya` running, the `v2ray` service would always be set to enabled after reboot. What's more, the `v2ray` service is running but the service itself seems still not valid until I start `v2raya` manually. I cannot confirm if it was caused by some setting of `v2ray`/`v2raya` or it was simply a bug.
我想在有需要的时候才启动`v2ray`和`v2raya`，所以我取消了这两个服务的开机自启。但我发现如果我在`v2raya`运行的时候直接重启电脑，开机后`v2ray`总会变回自动启动。并且，此时`v2ray`虽然看起来已经启动了，但却无法正常使用这个服务，除非我手动开启`v2raya`服务。我不确定这是不是我`v2ray`/`v2raya`的一些设置引起的，还是说单纯只是bug。

**Comment by mzz2017** [comment]
这确实是算软件的“bug”，目前v2raya将自动启动v2ray，但由于透明代理依赖于v2raya，v2raya关闭情况下透明代理将无法工作，但v2ray开放的端口是正常工作的（20170-20172），除非你使用ssr这样的依赖于v2raya的协议。

**Comment by zerobikappa** [comment]
> 这确实是算软件的“bug”，目前v2raya将自动启动v2ray，但由于透明代理依赖于v2raya，v2raya关闭情况下透明代理将无法工作，但v2ray开放的端口是正常工作的（20170-20172），除非你使用ssr这样的依赖于v2raya的协议。

Exactly...I am using SSR...

**Comment by zerobikappa** [comment]
我看到`v2raya`的服务脚本里的依赖项只包含了`network.target`：
[Unit]
Description=v2rayA Service
Documentation=https://github.com/mzz2017/v2rayA/wiki
After=network.target
Wants=network.target

你们是用其他方式启动`v2ray`的吗，如果是这样的话，在服务脚本中添加依赖项启动`v2ray`服务，代替原来的启动方式，能不能解决这个问题？

**Comment by mzz2017** [comment]
> 我看到`v2raya`的服务脚本里的依赖项只包含了`network.target`：
> 
> [Unit]
> 
> Description=v2rayA Service
> 
> Documentation=https://github.com/mzz2017/v2rayA/wiki
> 
> After=network.target
> 
> Wants=network.target
> 
> 
> 
> 你们是用其他方式启动`v2ray`的吗，如果是这样的话，在服务脚本中添加依赖项启动`v2ray`服务，代替原来的启动方式，能不能解决这个问题？

v2raya会自动enable v2ray。你也可以使用docker版本，去掉restart=always，通过docker start/stop来控制

**Comment by mzz2017** [comment]
我将关闭该issue，因为它已被解决于新发布的[v1.1.1](https://github.com/v2rayA/v2rayA/releases/tag/v1.1.1)
