### ISSUE TITLE
ubuntu server 2204 不能启动服务

### ISSUE THREAD

**Issue by marklitle** [v2rayA/v2rayA#1000]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
2.0.5
2. What approach of installation do you install V2rayA?
apt install v2raya
3. What is your operating system?
ubuntu server 2204.2

### Description

web界面可以打开
重置密码，导入订阅这些都没问题
ping节点没问题
启动服务的时候报错

### Logs：

2023/07/25 22:30:02.541  [A] [main.go:26]  V2Ray binary is /usr/local/bin/v2ray
2023/07/25 22:30:02.541  [A] [main.go:26]  V2Ray asset directory is /run/user/0/v2raya
2023/07/25 22:30:02.541  [A] [main.go:26]  v2rayA working directory is /
2023/07/25 22:30:02.541  [A] [main.go:26]  v2rayA configuration directory is /etc/v2raya
2023/07/25 22:30:02.541  [A] [main.go:26]  Golang: go1.20.2
2023/07/25 22:30:02.541  [A] [main.go:26]  OS: linux
2023/07/25 22:30:02.541  [A] [main.go:26]  Arch: amd64
2023/07/25 22:30:02.541  [A] [main.go:26]  Lite: false
2023/07/25 22:30:02.541  [A] [main.go:26]  Version: 2.0.5
2023/07/25 22:30:02.541  [A] [main.go:26]  Starting...
2023/07/25 22:30:02.541  [I] [main.go:27]  the core was not running the last time v2rayA exited
2023/07/25 22:30:02.545  [A] [index.go:116]  v2rayA is listening at http://127.0.0.1:2017
2023/07/25 22:30:02.545  [A] [index.go:116]  v2rayA is listening at http://192.168.32.9:2017
2023/07/25 22:30:02.545  [A] [index.go:116]  v2rayA is listening at http://[::1]:2017

2023/07/25 22:30:06.582  [I] [io.go:429]  V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
2023/07/25 22:30:06.582  [I] [io.go:429]  A unified platform for anti-censorship.
2023/07/25 22:30:06.692  [I] [io.go:429]  Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: private > proto: cannot parse invalid wire-format data
2023/07/25 22:30:06.706  [W] [asm_amd64.s:1598]  v2ray-core: exit status 1
2023/07/25 22:30:06.807  [E] [connection.go:88]  failed to start v2ray-core: unexpected exiting: check the log for more information

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```
 You can also paste the log that comes from web administration page

```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by mzz2017** [comment]
@marklitle 这应该是你的 geoip.dat 文件损坏了吧，删了重新去网上下一下。看文件路径: find /usr/ -name geoip.dat

**Comment by marklitle** [comment]
> find /usr/ -name geoip.dat
按你的做法，还是不行
root@lfclimber:/usr/local/share/v2ray# find /usr/ -name geoip.dat
/usr/local/share/v2ray/geoip.dat
root@lfclimber:/usr/local/share/v2ray# pwd
/usr/local/share/v2ray
root@lfclimber:/usr/local/share/v2ray# ls -al
total 21624
drwxr-xr-x 2 root root     4096 Jul 25 22:48 .
drwxr-xr-x 5 root root     4096 Jul 25 22:13 ..
-rw-r--r-- 1 root root 10267806 Jul 20 08:47 geoip.dat
-rw-r--r-- 1 root root 10267806 Jul 25 22:22 geoip.datbak
-rw-r--r-- 1 root root  1593799 Jul 25 22:22 geosite.dat
root@lfclimber:/usr/local/share/v2ray#

**Comment by marklitle** [comment]
> @marklitle v2fly太新了？降级试试？
降到了5.4,还不行

2023/07/25 12:56:24.452 [A] [main.go:26] OS: linux
2023/07/25 12:56:24.452 [A] [main.go:26] Arch: amd64
2023/07/25 12:56:24.452 [A] [main.go:26] Lite: false
2023/07/25 21:11:21.593 [I] [main.go:27] the core was not running the last time v2rayA exited
2023/07/25 21:11:21.604 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2023/07/25 21:11:21.604 [A] [index.go:116] v2rayA is listening at http://192.168.32.9:2017
2023/07/25 21:11:21.604 [A] [index.go:116] v2rayA is listening at http://[::1]:2017
2023/07/25 21:11:21.604 [A] [index.go:116] v2rayA is listening at http://[fe80::8aae:ddff:fe0b:c0d0]:2017
2023/07/25 21:11:22.489 [I] [asm_amd64.s:1598] [AutoUpdate] Subscriptions: Complete updating subscription -- ID: 0，Address: https://jmssub.net/members/getsub.php?service=807298&id=a1f3a186-bd07-47a2-8fd9-25c74a8ca82a&usedomains=1
2023/07/25 21:11:36.058 [I] [io.go:429] V2Ray 5.4.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.1 linux/amd64)
2023/07/25 21:11:36.058 [I] [io.go:429] A unified platform for anti-censorship.
2023/07/25 21:11:36.171 [I] [io.go:429] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: private > proto: cannot parse invalid wire-format data
2023/07/25 21:11:36.664 [W] [asm_amd64.s:1598] v2ray-core: exit status 1
2023/07/25 21:11:36.664 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information
2023/07/25 21:14:12.717 [A] [main.go:26] V2Ray binary is /usr/local/bin/v2ray
2023/07/25 21:14:12.717 [A] [main.go:26] V2Ray asset directory is /run/user/0/v2raya
2023/07/25 21:14:12.717 [A] [main.go:26] v2rayA working directory is /
2023/07/25 21:14:12.717 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2023/07/25 21:14:12.717 [A] [main.go:26] Golang: go1.20.2
2023/07/25 21:14:12.717 [A] [main.go:26] OS: linux
2023/07/25 21:14:12.717 [A] [main.go:26] Arch: amd64
2023/07/25 21:14:12.717 [A] [main.go:26] Lite: false
2023/07/25 21:52:07.191 [A] [main.go:26] OS: linux
2023/07/25 21:52:07.191 [A] [main.go:26] Arch: amd64
2023/07/25 21:52:07.191 [A] [main.go:26] Lite: false
2023/07/25 21:52:07.191 [A] [main.go:26] Version: 2.0.5
2023/07/25 21:52:07.191 [A] [main.go:26] Starting...
2023/07/25 21:52:07.191 [I] [main.go:27] the core was not running the last time v2rayA exited
2023/07/25 21:52:07.195 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2023/07/25 21:52:07.195 [A] [index.go:116] v2rayA is listening at http://192.168.32.9:2017
2023/07/25 21:52:07.195 [A] [index.go:116] v2rayA is listening at http://[::1]:2017
2023/07/25 21:52:07.195 [A] [index.go:116] v2rayA is listening at http://[fe80::8aae:ddff:fe0b:c0d0]:2017
2023/07/25 21:52:08.056 [I] [asm_amd64.s:1598] [AutoUpdate] Subscriptions: Complete updating subscription -- ID: 0，Address: https://jmssub.net/members/getsub.php?service=807298&id=a1f3a186-bd07-47a2-8fd9-25c74a8ca82a&usedomains=1
2023/07/25 21:52:17.557 [I] [io.go:429] V2Ray 5.6.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
2023/07/25 21:52:17.557 [I] [io.go:429] A unified platform for anti-censorship.
2023/07/25 21:52:17.675 [I] [io.go:429] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: private > proto: cannot parse invalid wire-format data
2023/07/25 21:52:17.679 [W] [asm_amd64.s:1598] v2ray-core: exit status 1
2023/07/25 21:52:17.679 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information
2023/07/25 21:53:45.542 [A] [main.go:26] V2Ray binary is /usr/local/bin/v2ray
2023/07/25 21:53:45.542 [A] [main.go:26] V2Ray asset directory is /run/user/0/v2raya
2023/07/25 21:53:45.542 [A] [main.go:26] v2rayA working directory is /
2023/07/25 21:53:45.542 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2023/07/25 21:53:45.542 [A] [main.go:26] Golang: go1.20.2
2023/07/25 21:53:45.542 [A] [main.go:26] OS: linux
2023/07/25 21:53:45.542 [A] [main.go:26] Arch: amd64
2023/07/25 21:53:45.542 [A] [main.go:26] Lite: false
2023/07/25 21:53:45.542 [A] [main.go:26] Version: 2.0.5
2023/07/25 21:53:45.542 [A] [main.go:26] Starting...
2023/07/25 21:53:45.542 [I] [main.go:27] the core was not running the last time v2rayA exited
2023/07/25 21:53:45.545 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2023/07/25 21:53:45.545 [A] [index.go:116] v2rayA is listening at http://192.168.32.9:2017
2023/07/25 21:53:45.545 [A] [index.go:116] v2rayA is listening at http://[::1]:2017
2023/07/25 21:53:45.545 [A] [index.go:116] v2rayA is listening at http://[fe80::8aae:ddff:fe0b:c0d0]:2017
2023/07/25 21:53:46.461 [I] [asm_amd64.s:1598] [AutoUpdate] Subscriptions: Complete updating subscription -- ID: 0，Address: https://jmssub.net/members/getsub.php?service=807298&id=a1f3a186-bd07-47a2-8fd9-25c74a8ca82a&usedomains=1
2023/07/25 21:54:46.076 [A] [main.go:26] V2Ray binary is /usr/local/bin/v2ray
2023/07/25 21:54:46.076 [A] [main.go:26] V2Ray asset directory is /run/user/0/v2raya
2023/07/25 21:54:46.076 [A] [main.go:26] v2rayA working directory is /
2023/07/25 21:54:46.076 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2023/07/25 21:54:46.076 [A] [main.go:26] Golang: go1.20.2
2023/07/25 21:54:46.076 [A] [main.go:26] OS: linux
2023/07/25 21:54:46.076 [A] [main.go:26] Arch: amd64
2023/07/25 21:54:46.076 [A] [main.go:26] Lite: false
2023/07/25 21:54:46.076 [A] [main.go:26] Version: 2.0.5
2023/07/25 21:54:46.076 [A] [main.go:26] Starting...
2023/07/25 21:54:46.076 [I] [main.go:27] the core was not running the last time v2rayA exited
2023/07/25 21:54:46.080 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2023/07/25 21:54:46.080 [A] [index.go:116] v2rayA is listening at http://192.168.32.9:2017
2023/07/25 21:54:46.080 [A] [index.go:116] v2rayA is listening at http://[::1]:2017
2023/07/25 21:54:46.080 [A] [index.go:116] v2rayA is listening at http://[fe80::8aae:ddff:fe0b:c0d0]:2017
2023/07/25 21:54:47.008 [I] [asm_amd64.s:1598] [AutoUpdate] Subscriptions: Complete updating subscription -- ID: 0，Address: https://jmssub.net/members/getsub.php?service=807298&id=a1f3a186-bd07-47a2-8fd9-25c74a8ca82a&usedomains=1
2023/07/25 21:54:54.533 [E] [account.go:79] length of password should be between 6 and 32
2023/07/25 21:55:13.285 [I] [io.go:429] V2Ray 5.6.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
2023/07/25 21:55:13.287 [I] [io.go:429] A unified platform for anti-censorship.
2023/07/25 21:55:13.390 [I] [io.go:429] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: private > proto: cannot parse invalid wire-format data
2023/07/25 21:55:13.416 [W] [asm_amd64.s:1598] v2ray-core: exit status 1
2023/07/25 21:55:13.517 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information
2023/07/25 22:20:13.022 [I] [io.go:429] V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
2023/07/25 22:20:13.022 [I] [io.go:429] A unified platform for anti-censorship.
2023/07/25 22:20:13.129 [I] [io.go:429] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: private > proto: cannot parse invalid wire-format data
2023/07/25 22:20:13.155 [W] [asm_amd64.s:1598] v2ray-core: exit status 1
2023/07/25 22:20:13.256 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information
2023/07/25 22:26:08.907 [I] [io.go:429] V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
2023/07/25 22:26:08.907 [I] [io.go:429] A unified platform for anti-censorship.
2023/07/25 22:26:09.023 [I] [io.go:429] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: private > proto: cannot parse invalid wire-format data
2023/07/25 22:26:09.026 [W] [asm_amd64.s:1598] v2ray-core: exit status 1
2023/07/25 22:26:09.120 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information
2023/07/25 22:26:11.243 [I] [io.go:429] V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
2023/07/25 22:26:11.243 [I] [io.go:429] A unified platform for anti-censorship.
2023/07/25 22:30:02.541 [A] [main.go:26] v2rayA working directory is /
2023/07/25 22:30:02.541 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2023/07/25 22:30:02.541 [A] [main.go:26] Golang: go1.20.2
2023/07/25 22:30:02.541 [A] [main.go:26] OS: linux
2023/07/25 22:30:02.541 [A] [main.go:26] Arch: amd64
2023/07/25 22:30:02.541 [A] [main.go:26] Lite: false
2023/07/25 22:30:02.541 [A] [main.go:26] Version: 2.0.5
2023/07/25 22:30:02.541 [A] [main.go:26] Starting...
2023/07/25 22:30:02.541 [I] [main.go:27] the core was not running the last time v2rayA exited
2023/07/25 22:30:02.545 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2023/07/25 22:30:02.545 [A] [index.go:116] v2rayA is listening at http://192.168.32.9:2017
2023/07/25 22:30:02.545 [A] [index.go:116] v2rayA is listening at http://[::1]:2017
2023/07/25 22:30:02.545 [A] [index.go:116] v2rayA is listening at http://[fe80::8aae:ddff:fe0b:c0d0]:2017
2023/07/25 22:30:03.454 [I] [asm_amd64.s:1598] [AutoUpdate] Subscriptions: Complete updating subscription -- ID: 0，Address: https://jmssub.net/members/getsub.php?service=807298&id=a1f3a186-bd07-47a2-8fd9-25c74a8ca82a&usedomains=1
2023/07/25 22:30:06.582 [I] [io.go:429] V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
2023/07/25 22:30:06.582 [I] [io.go:429] A unified platform for anti-censorship.
2023/07/25 22:30:06.692 [I] [io.go:429] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: private > proto: cannot parse invalid wire-format data
2023/07/25 22:30:06.706 [W] [asm_amd64.s:1598] v2ray-core: exit status 1
2023/07/25 22:30:06.807 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information
2023/07/25 22:41:38.713 [A] [main.go:26] V2Ray binary is /usr/local/bin/v2ray
2023/07/25 22:41:38.714 [A] [main.go:26] V2Ray asset directory is /run/user/0/v2raya
2023/07/25 22:41:38.714 [A] [main.go:26] v2rayA working directory is /
2023/07/25 22:41:38.715 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2023/07/25 22:41:38.715 [A] [main.go:26] Golang: go1.20.2
2023/07/25 22:41:38.715 [A] [main.go:26] OS: linux
2023/07/25 22:41:38.715 [A] [main.go:26] Arch: amd64
2023/07/25 22:44:08.146 [I] [io.go:429] A unified platform for anti-censorship.
2023/07/25 22:44:08.262 [I] [io.go:429] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: private > proto: cannot parse invalid wire-format data
2023/07/25 22:44:08.723 [W] [asm_amd64.s:1598] v2ray-core: exit status 1
2023/07/25 22:44:08.824 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information
2023/07/25 22:44:36.138 [I] [io.go:429] V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
2023/07/25 22:44:36.138 [I] [io.go:429] A unified platform for anti-censorship.
2023/07/25 22:44:36.244 [I] [io.go:429] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: private > proto: cannot parse invalid wire-format data
2023/07/25 22:44:36.266 [W] [asm_amd64.s:1598] v2ray-core: exit status 1
2023/07/25 22:44:36.367 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information
2023/07/25 22:45:22.653 [I] [io.go:429] V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
2023/07/25 22:45:22.653 [I] [io.go:429] A unified platform for anti-censorship.
2023/07/25 22:45:22.760 [I] [io.go:429] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: private > proto: cannot parse invalid wire-format data
2023/07/25 22:45:22.767 [W] [asm_amd64.s:1598] v2ray-core: exit status 1
2023/07/25 22:45:22.767 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information
2023/07/25 22:50:43.162 [I] [io.go:429] V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
2023/07/25 22:50:43.162 [I] [io.go:429] A unified platform for anti-censorship.
2023/07/25 22:50:43.277 [I] [io.go:429] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: private > proto: cannot parse invalid wire-format data
2023/07/25 22:50:43.285 [W] [asm_amd64.s:1598] v2ray-core: exit status 1
2023/07/25 22:50:43.298 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information
2023/07/25 22:54:11.619 [A] [main.go:26] V2Ray binary is /usr/local/bin/v2ray
2023/07/25 22:54:11.619 [A] [main.go:26] V2Ray asset directory is /run/user/0/v2raya
2023/07/25 22:54:11.619 [A] [main.go:26] v2rayA working directory is /
2023/07/25 22:54:11.619 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2023/07/25 22:54:11.619 [A] [main.go:26] Golang: go1.20.2
2023/07/25 22:54:11.619 [A] [main.go:26] OS: linux
2023/07/25 22:54:11.619 [A] [main.go:26] Arch: amd64
2023/07/25 22:54:11.619 [A] [main.go:26] Lite: false
2023/07/25 22:54:11.619 [A] [main.go:26] Version: 2.0.5
2023/07/25 22:54:11.619 [A] [main.go:26] Starting...
2023/07/25 22:54:11.619 [I] [main.go:27] the core was not running the last time v2rayA exited
2023/07/25 22:54:11.623 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2023/07/25 22:54:11.623 [A] [index.go:116] v2rayA is listening at http://192.168.32.9:2017
2023/07/25 22:54:11.623 [A] [index.go:116] v2rayA is listening at http://[::1]:2017
2023/07/25 22:54:11.623 [A] [index.go:116] v2rayA is listening at http://[fe80::8aae:ddff:fe0b:c0d0]:2017
2023/07/25 22:54:12.372 [I] [asm_amd64.s:1598] [AutoUpdate] Subscriptions: Complete updating subscription -- ID: 0，Address: https://jmssub.net/members/getsub.php?service=807298&id=a1f3a186-bd07-47a2-8fd9-25c74a8ca82a&usedomains=1
2023/07/25 22:54:17.448 [I] [io.go:429] V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
2023/07/25 22:54:17.448 [I] [io.go:429] A unified platform for anti-censorship.
2023/07/25 22:54:17.555 [I] [io.go:429] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: private > proto: cannot parse invalid wire-format data
2023/07/25 22:54:17.586 [W] [asm_amd64.s:1598] v2ray-core: exit status 1
2023/07/25 22:54:17.586 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information
2023/07/25 22:59:56.031 [A] [main.go:26] V2Ray binary is /usr/local/bin/v2ray
2023/07/25 22:59:56.031 [A] [main.go:26] V2Ray asset directory is /run/user/0/v2raya
2023/07/25 22:59:56.031 [A] [main.go:26] v2rayA working directory is /
2023/07/25 22:59:56.031 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2023/07/25 22:59:56.031 [A] [main.go:26] Golang: go1.20.2
2023/07/25 22:59:56.031 [A] [main.go:26] OS: linux
2023/07/25 22:59:56.031 [A] [main.go:26] Arch: amd64
2023/07/25 22:59:56.031 [A] [main.go:26] Lite: false
2023/07/25 22:59:56.031 [A] [main.go:26] Version: 2.0.5
2023/07/25 22:59:56.031 [A] [main.go:26] Starting...
2023/07/25 22:59:56.031 [I] [main.go:27] the core was not running the last time v2rayA exited
2023/07/25 22:59:56.035 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2023/07/25 22:59:56.035 [A] [index.go:116] v2rayA is listening at http://192.168.32.9:2017
2023/07/25 22:59:56.035 [A] [index.go:116] v2rayA is listening at http://[::1]:2017
2023/07/25 22:59:56.035 [A] [index.go:116] v2rayA is listening at http://[fe80::8aae:ddff:fe0b:c0d0]:2017
2023/07/25 22:59:56.763 [I] [asm_amd64.s:1598] [AutoUpdate] Subscriptions: Complete updating subscription -- ID: 0，Address: https://jmssub.net/members/getsub.php?service=807298&id=a1f3a186-bd07-47a2-8fd9-25c74a8ca82a&usedomains=1
2023/07/25 23:00:04.124 [I] [io.go:429] V2Ray 5.4.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.1 linux/amd64)
2023/07/25 23:00:04.124 [I] [io.go:429] A unified platform for anti-censorship.
2023/07/25 23:00:04.345 [I] [io.go:429] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: hk > proto: cannot parse invalid wire-format data
2023/07/25 23:00:04.348 [W] [asm_amd64.s:1598] v2ray-core: exit status 1
2023/07/25 23:00:04.433 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information


诡异的是，我在ubuntu 2204 Desktop上就是好的，
但是2204 server 就不行

**Comment by marklitle** [comment]
v2raya 调用v2ray core的命令是什么，我单独调一下

**Comment by marklitle** [comment]
对比desktop的日志
server不能accept udp

**Comment by mzz2017** [comment]
@marklitle v2ray run -c /etc/v2raya/config.json

**Comment by marklitle** [comment]
root@lfclimber:/home/lf# v2ray run -c /etc/v2raya/config.json
V2Ray 5.4.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.1 linux/amd64)
A unified platform for anti-censorship.
Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to load geoip: hk > proto: cannot parse invalid wire-format data

**Comment by MarksonHon** [comment]
`geoip:hk`
中间不能有空格
自己写规则的时候检查一下
