### ISSUE TITLE
更新gfwlist报错

### ISSUE THREAD

**Issue by blueskink** [v2rayA/v2rayA#101]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.0.1

2. 你通过什么方式安装v2rayA
docker

3. 你所使用的操作系统
nas

### 复现问题的步骤

更新gfwlist报错
 github.com/mzz2017/v2rayA/core/v2ray/asset/gfwlist: failed to get latest version of GFWList > Get "https://api.github.com/repos/mzz2017/dist-v2ray-rules-dat/tags": dial tcp 13.250.168.23:443: connect: connection refused

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

**Comment by mzz2017** [comment]
先连接节点，打开透明代理，保存后，重新获取

**Comment by mzz2017** [comment]
或者设置里有更新订阅通过代理
