### ISSUE TITLE
About Farsi language flag

### ISSUE THREAD

**Issue by neilbowman666** [v2rayA/v2rayA#1010]
What country / region should it be?

This flag is not owned or recognized by UN members and should not be used to identify languages.

![Open source software, politically neutral, please correct this flag](https://raw.githubusercontent.com/v2rayA/v2rayA/5ab2defdf8303d7dc9a6624f0400c6d2bf9d6aa1/gui/src/assets/img/flags/flag_fa.svg)

https://github.com/v2rayA/v2rayA/commit/5ab2defdf8303d7dc9a6624f0400c6d2bf9d6aa1

**Comment by mzz2017** [comment]
@neilbowman666 Could you plz give a PR? Thanks!

**Comment by neilbowman666** [comment]
> @neilbowman666 Could you plz give a PR? Thanks!

https://github.com/v2rayA/v2rayA/pull/1011
