### ISSUE TITLE
v2rayA service can't start in OpenWRT

### ISSUE THREAD

**Issue by joebnb** [v2rayA/v2rayA#1016]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?

v2raya | 2.0.5-1 (latest from openwrt offcial)

2. What approach of installation do you install V2rayA?

i'm using v2rayA via a openwrt system under PVE system

4. What is your operating system?

OpenWrt 22.03.5 r20134-5f15225c1e / LuCI openwrt-22.03 branch git-23.093.57104-ce20b4a

### Description

in openwrt the v2rayA can't start service using /etc/init.d/v2raya enable and start

### Steps to reproduce
type below code in terminal no error show up.
```
/etc/init.d/v2raya enable 
/etc/init.d/v2raya start
```
when using stats to check status
```
/etc/init.d/v2raya status
```
the output is:active with no instances.

and check the destnation in 2017 port,will show `ERR_CONNECTION_REFUSED`  (service not start).

if run
```
v2raya &
```
in terminal when service will work well.

it's seems init.d/v2raya not compatiable with newly openwrt system

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

it's seems only init.d not working,v2raya config is not related

![image](https://github.com/v2rayA/v2rayA/assets/1646883/8ebbe4ae-c884-47a1-b0ae-2131b78e9a5b)

![image](https://github.com/v2rayA/v2rayA/assets/1646883/31c2323c-414e-4908-9a3b-4052d2caa151)

**Comment by 1715173329** [comment]
https://v2raya.org/en/docs/prologue/installation/openwrt/#enable-and-start-the-service

So the documentation is even more useless than toilet paper as at least you will see the latter by chance.
How many times we need to repeat that OpenWrt uses UCI to manage services.

**Comment by lhzcm** [comment]
I have also encountered the problem you described, I found a strange code in the /etc/init.d/v2raya file, I don't know what it does, but I commented it out and the problem was solved. The picture below is the strange code marked in red. If you also have such code in your file, comment it out and try to run it again.
<img width="489" alt="c72d94c76838f6249c73b21724f54a5" src="https://github.com/v2rayA/v2rayA/assets/31691621/faf2d030-4285-44d9-a364-4015b299ead4">

**Comment by joebnb** [comment]
> I have also encountered the problem you described, I found a strange code in the /etc/init.d/v2raya file, I don't know what it does, but I commented it out and the problem was solved. The picture below is the strange code marked in red. If you also have such code in your file, comment it out and try to run it again. <img alt="c72d94c76838f6249c73b21724f54a5" width="489" src="https://user-images.githubusercontent.com/31691621/260049587-faf2d030-4285-44d9-a364-4015b299ead4.png">

solved,thanks a lot
