### ISSUE TITLE
2.1.1版本无法进入GUI界面

### ISSUE THREAD

**Issue by Minsdata** [v2rayA/v2rayA#1017]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
2.1.1
2. What approach of installation do you install V2rayA?
docker
3. What is your operating system?
debian 12

### Description

2.1.1版本无法进入GUI界面
浏览器显示:
ERR_CONNECTION_REFUSED
容器日志显示:
/go/pkg/mod/go4.org/unsafe/assume-no-moving-gc@v0.0.0-20230204201903-c31fa085b70e/untested.go:25 +0x1da panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.21 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH="go1.21" set. Notably, if go1.21 adds a moving garbage collector, this program is unsafe to use

**Comment by mzz2017** [comment]
Thanks. I'll fix it urgently.

**Comment by mzz2017** [comment]
https://github.com/v2rayA/v2rayA/releases/tag/v2.1.2
