### ISSUE TITLE
最新版本无法启动，会报这个错误

### ISSUE THREAD

**Issue by Seifon** [v2rayA/v2rayA#1018]
goroutine 1 [running]:
go4.org/unsafe/assume-no-moving-gc.init.0()
	/go/pkg/mod/go4.org/unsafe/assume-no-moving-gc@v0.0.0-20230204201903-c31fa085b70e/untested.go:25 +0x1a0
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.21 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH="go1.21" set. Notably, if go1.21 adds a moving garbage collector, this program is unsafe to use.

**Comment by mzz2017** [comment]
https://github.com/v2rayA/v2rayA/releases/tag/v2.1.2 刚修
