### ISSUE TITLE
文件错误

### ISSUE THREAD

**Issue by Yofo-me** [v2rayA/v2rayA#103]
` ubuntu 20LTS`安装时报错，提示文件大小不对

![image](https://user-images.githubusercontent.com/55388087/96204301-8a9d2e80-0f96-11eb-8ba9-368c7bd307ce.png)

**Comment by 763ce67512c8** [comment]
我也遇到了相同的问题，目前手动下载Release中的deb文件手动安装解决。

**Comment by mzz2017** [comment]
谢谢你们的反馈，目前ci正在重新打包

**Comment by mzz2017** [comment]
目前问题已修复
