### ISSUE TITLE
无法使用一个ssr订阅的节点

### ISSUE THREAD

**Issue by Karmylr** [v2rayA/v2rayA#1030]
使用其他节点能正常科学上网。但是使用这个ssr机场的订阅不行。已经用别的软件测试过节点的连通性了。订阅链接在telegram私信我(`@biliconter`)

**Comment by Karmylr** [comment]
降级到v2rayA 2.0.5就正常了

**Comment by YingchangLiu** [comment]
同样的问题

**Comment by van2m** [comment]
我也是一个样的情况，按楼上的用2.1.0就没问题了。。折腾了一晚上，也是够够的。

**Comment by van2m** [comment]
我也是一个样的情况，按楼上的用2.1.0就没问题了。。折腾了一晚上，也是够够的。

**Comment by Caesar6666666** [comment]
具体是什么情况，我也有同样问题，ssr节点不能http测速

**Comment by Karmylr** [comment]
> 具体是什么情况，我也有同样问题，ssr节点不能http测速

升级。已经修复了
