### ISSUE TITLE
国外VPS   v2rayA中转socks5，安全吗？

### ISSUE THREAD

**Issue by zxymdaddy** [v2rayA/v2rayA#1037]
国外VPS搭建节点，国内服务器v2rayA中转sock5，手机用小火箭直接代理socks5代理地址。这样安全吗？

**Comment by BakaJzon** [comment]
服务器是在局域网吗？公网肯定不安全。参考[这个链接](https://en.wikipedia.org/wiki/SOCKS#Security)
即使是局域网也不能确保安全，因为可能有**某些软件**扫端口之类的。
_话说 v2raya 依赖于 v2ray,国内厂商不会封号吗？_

还有这不是 issue 板块的功能，非技术问题请去 Discussion 或 TG 群询问 :smile:
Have a nice day~
