### ISSUE TITLE
Fails to start on Docker

### ISSUE THREAD

**Issue by matanceros** [v2rayA/v2rayA#1039]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
2.2.0

2. What approach of installation do you install V2rayA?
docker pull v2raya:latest

3. What is your operating system?
Unraid/docker

### Description
v2raya fails to start after upgrading to 2.2.0.
Have tried rebuilding dockerimg but no effect

### Logs：

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa4cd44]

goroutine 1 [running]:
github.com/v2rayA/v2rayA/core/serverObj.(*V2Ray).Configuration(_, {{_, _}, {_, _}, {_, _}, _})
        /build/service/core/serverObj/v2ray.go:388 +0x1384
github.com/v2rayA/v2rayA/core/v2ray.(*Template).resolveOutbounds(0xc000246500, 0xc000581ea0)
        /build/service/core/v2ray/v2rayTmpl.go:1312 +0x59e
github.com/v2rayA/v2rayA/core/v2ray.NewTemplate({0xc0001da5a0?, 0x7, 0x7}, 0x0)
        /build/service/core/v2ray/v2rayTmpl.go:1535 +0x3f2
github.com/v2rayA/v2rayA/core/v2ray.NewTemplateFromConnectedServers(0xc0000c8600?)
        /build/service/core/v2ray/process.go:323 +0xe5
github.com/v2rayA/v2rayA/core/v2ray.UpdateV2RayConfig()
        /build/service/core/v2ray/process.go:331 +0x19
main.run()
        /build/service/pre.go:328 +0x10d
main.main()
        /build/service/main.go:30 +0x8a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa4cd44]

goroutine 1 [running]:
github.com/v2rayA/v2rayA/core/serverObj.(*V2Ray).Configuration(_, {{_, _}, {_, _}, {_, _}, _})
        /build/service/core/serverObj/v2ray.go:388 +0x1384
github.com/v2rayA/v2rayA/core/v2ray.(*Template).resolveOutbounds(0xc00044e8c0, 0xc000586550)
        /build/service/core/v2ray/v2rayTmpl.go:1312 +0x59e
github.com/v2rayA/v2rayA/core/v2ray.NewTemplate({0xc000264c60?, 0x7, 0x7}, 0x0)
        /build/service/core/v2ray/v2rayTmpl.go:1535 +0x3f2
github.com/v2rayA/v2rayA/core/v2ray.NewTemplateFromConnectedServers(0xc00064e600?)
        /build/service/core/v2ray/process.go:323 +0xe5
github.com/v2rayA/v2rayA/core/v2ray.UpdateV2RayConfig()
        /build/service/core/v2ray/process.go:331 +0x19
main.run()
        /build/service/pre.go:328 +0x10d
main.main()
        /build/service/main.go:30 +0x8a
2023/08/20 08:59:11.763 [A] [main.go:29]  V2Ray binary is /usr/bin/v2ray
2023/08/20 08:59:11.763 [A] [main.go:29]  V2Ray asset directory is /run/user/0/v2raya
2023/08/20 08:59:11.763 [A] [main.go:29]  v2rayA working directory is /root
2023/08/20 08:59:11.763 [A] [main.go:29]  v2rayA configuration directory is /etc/v2raya
2023/08/20 08:59:11.764 [A] [main.go:29]  Golang: go1.21.0
2023/08/20 08:59:11.764 [A] [main.go:29]  OS: linux
2023/08/20 08:59:11.764 [A] [main.go:29]  Arch: amd64
2023/08/20 08:59:11.764 [A] [main.go:29]  Lite: false
2023/08/20 08:59:11.764 [A] [main.go:29]  Version: 2.2.0
2023/08/20 08:59:11.764 [A] [main.go:29]  Starting...
2023/08/20 08:59:22.647 [A] [main.go:29]  V2Ray binary is /usr/bin/v2ray
2023/08/20 08:59:22.647 [A] [main.go:29]  V2Ray asset directory is /run/user/0/v2raya
2023/08/20 08:59:22.647 [A] [main.go:29]  v2rayA working directory is /root
2023/08/20 08:59:22.647 [A] [main.go:29]  v2rayA configuration directory is /etc/v2raya
2023/08/20 08:59:22.647 [A] [main.go:29]  Golang: go1.21.0
2023/08/20 08:59:22.647 [A] [main.go:29]  OS: linux
2023/08/20 08:59:22.647 [A] [main.go:29]  Arch: amd64
2023/08/20 08:59:22.647 [A] [main.go:29]  Lite: false
2023/08/20 08:59:22.647 [A] [main.go:29]  Version: 2.2.0
2023/08/20 08:59:22.647 [A] [main.go:29]  Starting...

**Comment by mzz2017** [comment]
What's your previous version?

**Comment by matanceros** [comment]
1.5.5 or 1.5.1, can’t remember. Pulled original image for Alibaba’s CR, then updated through official repo.

**Comment by matanceros** [comment]
Issue has been fixed with new update, thanks @mzz2017
