### ISSUE TITLE
vless|Reality目前无法连接

### ISSUE THREAD

**Issue by wudongdefeng** [v2rayA/v2rayA#1048]
### 您想提出的功能特性是否和现有问题相关？

vless|Reality目前无法连接

### 功能特性内容
能够支持这个协议吗

**Comment by MarksonHon** [comment]
2.2.1版本已经支持

**Comment by wudongdefeng** [comment]
我使用别的客户端可以连接，但是2.2.1版本不行

**Comment by mzz2017** [comment]
@wudongdefeng 你要安装最新版 xray-core

**Comment by wudongdefeng** [comment]
> @wudongdefeng 你要安装最新版 xray-core

我装的docker版。也需要装xray-core吗

**Comment by mzz2017** [comment]
@wudongdefeng 对

**Comment by wudongdefeng** [comment]
> @wudongdefeng 对

docker版是进容器更新吗
下面命令对吗
bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install

**Comment by mzz2017** [comment]
@wudongdefeng 能把 xray 装上就行，我不知道用什么命令

**Comment by wudongdefeng** [comment]
> > @wudongdefeng 对
> 
> docker版是进容器更新吗 下面命令对吗 bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install

按照这个安装了，还是不行啊，是否还需要配置下

**Comment by wudongdefeng** [comment]
> @wudongdefeng 能把 xray 装上就行，我不知道用什么命令

xray.service - Xray Service                             Loaded: loaded (/etc/systemd/system/xray.servic>    Drop-In: /etc/systemd/system/xray.service.d                   └─10-donot_touch_single_conf.conf            Active: active (running) since Sat 2023-08-26 0>       Docs: https://github.com/xtls                    Main PID: 733249 (xray)                                 Tasks: 9 (limit: 4458)                              Memory: 3.6M                                            CPU: 708ms                                        CGroup: /system.slice/xray.service                           └─733249 /usr/local/bin/xray run -confi>                                                     Notice: journal has been rotated since unit was star>
启动了，还是提示vless(tcp+reality)时延NOT STABLE

**Comment by mzz2017** [comment]
@wudongdefeng 不在这看，看日志里

**Comment by MarksonHon** [comment]
你可以选择不使用 Docker 版本，转而使用第三方脚本安装：

```sh
sudo bash -c "$(curl -sL -H "Cache-Control: no-cache" https://github.com/MarksonHon/v2raya-fhs-installer/raw/main/v2raya-fhs-installer.sh)" @ --with-xray
```

**Comment by wudongdefeng** [comment]
> 你可以选择不使用 Docker 版本，转而使用第三方脚本安装：
> 
> ```shell
> sudo bash -c "$(curl -sL -H "Cache-Control: no-cache" https://github.com/MarksonHon/v2raya-fhs-installer/raw/main/v2raya-fhs-installer.sh)" @ --with-xray
> ```

这个命令可以了，但是只能选择一个节点，以前可以多选节点的

**Comment by MarksonHon** [comment]
> > 你可以选择不使用 Docker 版本，转而使用第三方脚本安装：
> > ```shell
> > sudo bash -c "$(curl -sL -H "Cache-Control: no-cache" https://github.com/MarksonHon/v2raya-fhs-installer/raw/main/v2raya-fhs-installer.sh)" @ --with-xray
> > ```
> 
> 这个命令可以了，但是只能选择一个节点，以前可以多选节点的，版本是最新的

多节点需要 v2ray，支持VLESS全套协议与多节点选择，你只能同时拥有一个

**Comment by wudongdefeng** [comment]
> > 你可以选择不使用 Docker 版本，转而使用第三方脚本安装：
> > ```shell
> > sudo bash -c "$(curl -sL -H "Cache-Control: no-cache" https://github.com/MarksonHon/v2raya-fhs-installer/raw/main/v2raya-fhs-installer.sh)" @ --with-xray
> > ```
> 
> 这个命令可以了，但是只能选择一个节点，以前可以多选节点的，版本是最新的

那果断放弃vless，负载均衡不可少
