### ISSUE TITLE
节点设置 AlterID 不能为 0，导致无法连接

### ISSUE THREAD

**Issue by hackxiu** [v2rayA/v2rayA#105]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
Version: 1.0.3
2. 你通过什么方式安装v2rayA
https://hub.docker.com/r/mzz2017/v2raya
3. 你所使用的操作系统
群晖NAS，运行环境 docker

### 描述问题

在配置  v2ray 节点的时候，在web 管理界面上增加节点
AlterID 输入 0 。保存后 ，会导致无法连接到 v2ray 节点，
此 AlterID 对应 应该是 v2ray 服务端的 alterId 也是 0 ，
这样配置会导致无法连接，但是设置 1 以上 包含 1，就可以正常
连接，

### 复现问题的步骤

在保存 alterId 的时候，允许设置为0 应该默认设置也是 0 
才对。

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### 截图

![偷揉图床 API](https://i.ibb.co/NW7zPQF/20201019013912.png)

**Comment by mzz2017** [comment]
AlterID=0的释义在最新版的v2ray-core中已改变，参阅https://www.v2fly.org/config/protocols/vmess.html

无法连接的原因应该是服务端未开启aead

**Comment by hackxiu** [comment]
> AlterID=0的释义在最新版的v2ray-core中已改变，参阅https://www.v2fly.org/config/protocols/vmess.html
> 
> 无法连接的原因应该是服务端未开启aead

。。。谢谢，我知道了  我可能是很久没更新 v2ray 了，所以
落伍了，蛤蛤 多谢。提示
