### ISSUE TITLE
如何备份订阅?

### ISSUE THREAD

**Issue by finalcreator** [v2rayA/v2rayA#1051]
### 版本、安装方式、系统

最新 docker 版本

### 描述问题：

因为订阅比较多, 需要备份一下, 今天升级docker 镜像, 订阅都丢失了

**Comment by mzz2017** [comment]
@finalcreator 备份你的 docker 镜像，或者备份里面的 /etc/v2raya/ 目录

**Comment by finalcreator** [comment]
多选 server 的时候能有个批量分享链接的功能吗
