### ISSUE TITLE
ubuntu22软件源安装的v2raya无法通过apt软件源更新

### ISSUE THREAD

**Issue by woshiniba-debug** [v2rayA/v2rayA#1052]
### 版本、安装方式、系统

1. ubuntu
2. apt软件源

3.ubuntu22 

### 描述问题：

无法通过软件源更新，现在版本是2.13

### v2rayA运行日志（Optional）：

![image](https://github.com/v2rayA/v2rayA/assets/72678270/31383da4-d2f5-4a4e-86f9-67820b6317b5)

**Comment by woshiniba-debug** [comment]
这里写着我是2.2.1，但是我打开网页实际上是2.13
![image](https://github.com/v2rayA/v2rayA/assets/72678270/2e7869c4-d4c3-4d59-88b1-b3872c90d2e2)

**Comment by mzz2017** [comment]
@woshiniba-debug 重启

**Comment by woshiniba-debug** [comment]
请问重启的指令是什么？

**Comment by woshiniba-debug** [comment]
我不是docker，是直接装Ubuntu里的
