### ISSUE TITLE
Access raw.githubusercontent.com 

### ISSUE THREAD

**Issue by glepnir** [v2rayA/v2rayA#1053]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

Latest version

2. 你通过什么方式安装v2rayA      

AUR

3. 你所使用的操作系统

Arch Linux

### 描述问题

can not access `raw.githubusercontent.com` 

### 复现问题的步骤

I have tried config `domain(regexp: \.github.*\.com$) -> proxy` this in routingA mode but not works . thanks 

### v2rayA/v2ray运行日志：

Maybe no need log ?

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by cubercsl** [comment]
请解决 DNS 污染

**Comment by glepnir** [comment]
thanks quick reply . I tried doh mode also not work ? sry I don't install any chinese input method.

**Comment by mzz2017** [comment]
@glepnir 设置里面打开dns防污染
