### ISSUE TITLE
请问如何改密码

### ISSUE THREAD

**Issue by Jushb** [v2rayA/v2rayA#1054]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2.2.1
2. 你通过什么方式安装v2rayA
docker
3. 你所使用的操作系统
unraid

### 描述问题：
请问已经开始使用了之后，如何修改密码？

请问已经开始使用了之后，如何修改密码？

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by cubercsl** [comment]
#110
