### ISSUE TITLE
提示'v2ray'将对你的电脑造成伤害

### ISSUE THREAD

**Issue by caicaicaicai2222** [v2rayA/v2rayA#1057]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2023-5-10
2. 你通过什么方式安装v2rayA
homebrew
3. 你所使用的操作系统
macOS

### 描述问题：

系统一直提示提示：'v2ray'将对你的电脑造成伤害。你应该将它移到废纸篓
点击取消后很快重复弹出提示

### v2rayA设置以及相关截图

<img width="318" alt="截屏2023-08-30 16 39 13" src="https://github.com/v2rayA/v2rayA/assets/98260972/8fe9ea52-6e2b-45df-8321-7d8a22c3b450">

**Comment by MarksonHon** [comment]
v2ray怎么安装的

**Comment by caicaicaicai2222** [comment]
使用homebrew安装的
brew tap v2raya/v2raya
brew install v22raya/v2raya/v2raya

几个月前安装的，一直正常使用，最近突然就出现了这个问题

**Comment by MarksonHon** [comment]
把v2ray、v2raya卸掉再重装
