### ISSUE TITLE
cannot start V2Ray without server connected

### ISSUE THREAD

**Issue by xiguafz** [v2rayA/v2rayA#106]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
https://registry.hub.docker.com/r/mzz2017/v2raya/  latest

2. 你通过什么方式安装v2rayA
群辉 docker 

3. 你所使用的操作系统
群辉 

### 描述问题：

v2ray-core状态：尚未运行

启动会出现报错 cannot start V2Ray without server connected

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya_backend
 ```
```shell
# 此处贴入运行日志


v2ctl> Read config:  /usr/local/share/v2ray/config.json                         
2020/10/20 02:29:16 [Warning] v2ray.com/core: V2Ray 4.31.0 started              
2020/10/20 02:29:17 transparent.go:43: github.com/v2rayA/v2rayA/common/cmds: ipt
ables-legacy -t nat -N V2RAY iptables v1.8.3 (legacy): can't initialize iptables
 table `nat': Permission denied (you must be root)                              
Perhaps iptables or your kernel needs to be upgraded.                           
 > exit status 3                                                                
2020/10/20 02:29:17 connect.go:65: Connect: done                                
2020/10/20 02:29:17 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/
v2ray: github.com/v2rayA/v2rayA/core/v2ray: not support transparent proxy:  > gi
thub.com/v2rayA/v2rayA/common/cmds: iptables-legacy -t nat -N V2RAY iptables v1.
8.3 (legacy): can't initialize iptables table `nat': Permission denied (you must
 be root)                                                                       
Perhaps iptables or your kernel needs to be upgraded.                           
 > exit status 3                                                                
2020/10/20 02:31:07 [Warning] cannot start V2Ray without server connected       
                                                                                
                                                                                
2020/10/20 02:31:56 [Warning] cannot start V2Ray without server connected       

```

**Comment by xiguafz** [comment]
全局透明 能运行 而且能连接了。

但是只要开启 就会报错

github.com/v2rayA/v2rayA/core/v2ray: github.com/v2rayA/v2rayA/core/v2ray: not support transparent proxy: > github.com/v2rayA/v2rayA/common/cmds: iptables-legacy -t nat -N V2RAY iptables v1.8.3 (legacy): can't initialize iptables table `nat': Permission denied (you must be root) Perhaps iptables or your kernel needs to be upgraded. > exit status 3

**Comment by mzz2017** [comment]
透明代理需要iptables的支持，一些低版本的操作系统并不满足要求

**Comment by xiguafz** [comment]
> 透明代理需要iptables的支持，一些低版本的操作系统并不满足要求

iptables？这个是所在服务环境的要求吗。不应该跟我群辉的iptables有关吧。而是docker的环境吧

**Comment by xiguafz** [comment]
对了，忘了问，如果全局透明关闭的情况下。是否有代理的。

**Comment by mzz2017** [comment]
> > 透明代理需要iptables的支持，一些低版本的操作系统并不满足要求
> 
> 
> 
> iptables？这个是所在服务环境的要求吗。不应该跟我群辉的iptables有关吧。而是docker的环境吧

docker和寄主环境是共享内核的

**Comment by mzz2017** [comment]
> 对了，忘了问，如果全局透明关闭的情况下。是否有代理的。

端口开放的

**Comment by xiguafz** [comment]
> > 对了，忘了问，如果全局透明关闭的情况下。是否有代理的。
> 
> 端口开放的

那透明关闭。。流量是怎么走 pac还是全局

**Comment by mzz2017** [comment]
看一下各个端口的介绍

**Comment by xiguafz** [comment]
还有配置文件参数 config 怎么好像不行
我挂载了一个/config路径  然后环境变量config=/config 是我设置错了吗

**Comment by mzz2017** [comment]
没有config环境变量
使用 V2RAYA_CONFIG

**Comment by xiguafz** [comment]
> 没有config环境变量
> 使用 V2RAYA_CONFIG

![image](https://user-images.githubusercontent.com/62539036/96547273-66b35300-12de-11eb-9ec0-af0a807ca21e.png)

也不行啊。。目录里面没东西
