### ISSUE TITLE
Hello! Request to add load balancing mechanism

### ISSUE THREAD

**Issue by zhouxinghong** [v2rayA/v2rayA#1067]
### Is the feature related with existing problem?

Hello! Since multiple nodes can be selected, how to perform load balancing? In most cases, the validity period of a node is only tens of minutes or even a few hours. . .

### Content of the feature

Hello! Since multiple nodes can be selected, how to perform load balancing? In most cases, the validity period of a node is only tens of minutes or even a few hours. . .

**Comment by mzz2017** [comment]
@zhouxinghong This is v2ray-core only feature.

**Comment by zhouxinghong** [comment]
@mzz2017 Is this function available in this tool?

**Comment by mzz2017** [comment]
@zhouxinghong What do you mean

**Comment by zhouxinghong** [comment]
How to achieve node load balancing in this tool?

**Comment by wanlce** [comment]
Load balancing depends on the core, currently this is v2ray-core unique features, use v2ray-core can be used!

**Comment by zhouxinghong** [comment]
Does v2ray-core have a similar GUI client?

**Comment by wanlce** [comment]
> Does v2ray-core have a similar GUI client?

v2raya is a web GUI client that requires a core to run properly, either xray-core or v2ray-core , and the load balancing feature is owned by v2ray-core.
When both xray-core and v2ray-core are present, the current version uses xray-core first, so if you have them both installed, just uninstall xray-core.

**Comment by zhouxinghong** [comment]
![image](https://github.com/v2rayA/v2rayA/assets/54253524/d4e4d67e-18c3-411a-a00f-377a6b3116ea)

**Comment by zhouxinghong** [comment]
Please tell me how to uninstall xray-core.

**Comment by zhouxinghong** [comment]
Recently, many service nodes have lost connection within a few minutes. It is very important to add a service load balancing mechanism! I hope the team can take this requirement into consideration!

**Comment by mzz2017** [comment]
@zhouxinghong Please open an issue to xray-core instead.
