### ISSUE TITLE
apt update error，出现签名错误

### ISSUE THREAD

**Issue by digitama6512** [v2rayA/v2rayA#1070]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.2.2
2. 你通过什么方式安装v2rayA
v2raya文档，通过软件源安装
3. 你所使用的操作系统
debian testing
Linux debian 6.4.0-3-amd64  SMP PREEMPT_DYNAMIC Debian 6.4.11-1 (2023-08-17) x86_64 GNU/Linux

### 描述问题：

今天运行apt update时出现错误，如下所示：
>W: GPG error: https://hubmirror.v2raya.org/v2rayA/v2raya-apt/raw/master v2raya InRelease: The following signatures were invalid: BADSIG 354E516D494EF95F mzz2017 (apt) <mzz@tuta.io>
>E: The repository 'https://apt.v2raya.org v2raya InRelease' is not signed.
>N: Updating from such a repository can't be done securely, and is therefore disabled by default.
>N: See apt-secure(8) manpage for repository creation and user configuration details.

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![image](https://github.com/v2rayA/v2rayA/assets/58547984/ec043736-5bd2-476b-969b-c7560bf166d3)
![image](https://github.com/v2rayA/v2rayA/assets/58547984/eeb65023-45b1-4c34-8a73-f2afad7c9def)
![image](https://github.com/v2rayA/v2rayA/assets/58547984/4025e567-c004-4706-8c76-4fcc2c3f27b1)

**Comment by mzz2017** [comment]
@digitama6512 少执行了个命令吧，看文档

**Comment by digitama6512** [comment]
> @digitama6512 少执行了个命令吧，看文档

一个月前安装的，今天突然报错了，那我重新安装试试

**Comment by digitama6512** [comment]
> > @digitama6512 少执行了个命令吧，看文档
> 
> 一个月前安装的，今天突然报错了，那我重新安装试试

还是不行

**Comment by digitama6512** [comment]
> > @digitama6512 少执行了个命令吧，看文档
> 
> 一个月前安装的，今天突然报错了，那我重新安装试试

@mzz2017 还是报这个错

**Comment by mzz2017** [comment]
@digitama6512 1. cat /etc/apt/keyrings/v2raya.asc
2. cat /etc/apt/sources.list.d/v2raya.list

**Comment by digitama6512** [comment]
> @digitama6512 1. cat /etc/apt/keyrings/v2raya.asc 2. cat /etc/apt/sources.list.d/v2raya.list

@mzz2017 
![c9773df0e370952ca6a4c15b87b56fab](https://github.com/v2rayA/v2rayA/assets/58547984/c1cd1b1c-fa98-44f2-843a-11eab5de941d)

**Comment by mzz2017** [comment]
好吧.. 我修一下

**Comment by digitama6512** [comment]
> 好吧.. 我修一下

辛苦了

**Comment by digitama6512** [comment]
> 好吧.. 我修一下

**Comment by mzz2017** [comment]
@digitama6512 再试一下

**Comment by digitama6512** [comment]
> @digitama6512 再试一下

@mzz2017 我这儿还是不行。我这个是个例吗？

**Comment by digitama6512** [comment]
@mzz2017 是否需要翻墙？

**Comment by mzz2017** [comment]
@digitama6512 重新按那个文档导入一下

**Comment by mzz2017** [comment]
但是不应该吧.. 等等看别人有没有相关报告好了

**Comment by digitama6512** [comment]
> @digitama6512 重新按那个文档导入一下

@mzz2017 我这里还是不行

**Comment by swhoro** [comment]
同不行，出现签名错误
以前装的时候没有使用签名，是正常的，但是今天在新电脑上装时出错的
是不是签名格式不正确？不太懂apt签名机制，但是k8s docker它们的签名都是gpg格式的：
![图片](https://github.com/v2rayA/v2rayA/assets/34229589/d8c50cae-5ca7-415c-b43c-644a944c2091)

**Comment by mzz2017** [comment]
@swhoro wget -qO - https://apt.v2raya.org/key/public-key.asc | sudo tee /etc/apt/trusted.gpg.d/v2raya.asc

echo "deb https://apt.v2raya.org/ v2raya main" | sudo tee /etc/apt/sources.list.d/v2raya.list

apt update

试试这个

**Comment by mzz2017** [comment]
@digitama6512 是反向代理的问题，应该已经解决了

**Comment by swhoro** [comment]
> @swhoro wget -qO - https://apt.v2raya.org/key/public-key.asc | sudo tee /etc/apt/trusted.gpg.d/v2raya.asc
> 
> echo "deb https://apt.v2raya.org/ v2raya main" | sudo tee /etc/apt/sources.list.d/v2raya.list
> 
> apt update
> 
> 试试这个

可以了，谢谢

**Comment by digitama6512** [comment]
> @digitama6512 是反向代理的问题，应该已经解决了

已经问题已解决
