### ISSUE TITLE
apt安装导入公钥失败

### ISSUE THREAD

**Issue by Ah-lam** [v2rayA/v2rayA#1072]
### 描述问题：

尝试使用apt安装v2rayA（参考安装文档：https://github.com/v2rayA/v2rayA/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95/18d233c7541bf061e8f33fa8d8f1fca327fffbc6#user-content-debian-%E7%B3%BB%E5%88%97%E5%AE%89%E8%A3%85），
执行下面指令尝试添加公钥：
wget -qO - https://apt.v2raya.mzz.pub/key/public-key.asc | sudo apt-key add -

报错：
gpg: no valid OpenPGP data found.

百度说：是因为无法翻墙导致的。于是不会解决了，正是需要翻墙要装v2rayA，但是要装v2rayA首先需要可以翻墙。

**Comment by cubercsl** [comment]
@Ah-lam https://v2raya.org/docs/prologue/installation/debian/#%E6%96%B9%E6%B3%95%E4%B8%80%E9%80%9A%E8%BF%87%E8%BD%AF%E4%BB%B6%E6%BA%90%E5%AE%89%E8%A3%85

**Comment by cubercsl** [comment]
@mzz2017 wiki 内容似乎过时了

**Comment by mzz2017** [comment]
@cubercsl 居然还有 wiki，我去给删掉

**Comment by Ah-lam** [comment]
@cubercsl 感谢~
参考（https://v2raya.org/docs/prologue/installation/debian/#%E6%96%B9%E6%B3%95%E4%B8%80%E9%80%9A%E8%BF%87%E8%BD%AF%E4%BB%B6%E6%BA%90%E5%AE%89%E8%A3%85）

还是有问题：
执行下面指令尝试添加公钥：
sudo wget -qO - https://apt.v2raya.org/key/public-key.asc | sudo tee /etc/apt/keyrings/v2raya.asc
执行没有报错。 

接着执行：
echo "deb [signed-by=/etc/apt/keyrings/v2raya.asc] https://apt.v2raya.org/ v2raya main" | sudo tee /etc/apt/sources.list.d/v2raya.list
sudo apt update

报错：
W: GPG error: https://apt.v2raya.org v2raya InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 354E516D494EF95F
E: The repository 'https://apt.v2raya.org v2raya InRelease' is not signed.


尝试修复方案：
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 354E516D494EF95F

报错：
gpg: keyserver receive failed: No data

求教如何解决？非常感谢~

**Comment by cubercsl** [comment]
@Ah-lam https://apt.v2raya.org/key/public-key.asc 应该有内容

**Comment by MarksonHon** [comment]
> @cubercsl 感谢~ 参考（[https://v2raya.org/docs/prologue/installation/debian/#%E6%96%B9%E6%B3%95%E4%B8%80%E9%80%9A%E8%BF%87%E8%BD%AF%E4%BB%B6%E6%BA%90%E5%AE%89%E8%A3%85）](https://v2raya.org/docs/prologue/installation/debian/#%E6%96%B9%E6%B3%95%E4%B8%80%E9%80%9A%E8%BF%87%E8%BD%AF%E4%BB%B6%E6%BA%90%E5%AE%89%E8%A3%85%EF%BC%89)
> 
> 还是有问题： 执行下面指令尝试添加公钥： sudo wget -qO - https://apt.v2raya.org/key/public-key.asc | sudo tee /etc/apt/keyrings/v2raya.asc 执行没有报错。
> 
> 接着执行： echo "deb [signed-by=/etc/apt/keyrings/v2raya.asc] https://apt.v2raya.org/ v2raya main" | sudo tee /etc/apt/sources.list.d/v2raya.list sudo apt update
> 
> 报错： W: GPG error: https://apt.v2raya.org v2raya InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 354E516D494EF95F E: The repository 'https://apt.v2raya.org v2raya InRelease' is not signed.
> 
> 尝试修复方案： sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 354E516D494EF95F
> 
> 报错： gpg: keyserver receive failed: No data
> 
> 求教如何解决？非常感谢~

执行第一条命令的时候，屏幕上有没有输出类似的内容？

![图片](https://github.com/v2rayA/v2rayA/assets/50002150/81632bc7-93ee-4ba8-97ea-ffd6c63003a2)

**Comment by Ah-lam** [comment]
感谢 @cubercsl @MarksonHon 两位老师~~~

执行sudo wget -qO - https://apt.v2raya.org/key/public-key.asc | sudo tee /etc/apt/keyrings/v2raya.asc 不知道为什么公钥没有拉下来就直接返回了

手动下载public-key.asc后拷贝至/etc/apt/keyrings/v2raya.asc，之后都很顺利。

**Comment by 6ang996** [comment]
wget -qO - https://apt.v2raya.org/key/public-key.asc | sudo tee /etc/apt/keyrings/v2raya.asc
tee: /etc/apt/keyrings/v2raya.asc: No such file or directory
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGFCxwUBEACa8jVA5S5u89JKaEzsm6WdIrCmoaHUgrsBqTP/Zx3by4OIzlWR

有些系统没有keyrings目录，需要手动提前创建下
sudo mkdir -p /etc/apt/keyrings/
wget -qO - https://apt.v2raya.org/key/public-key.asc | sudo tee /etc/apt/keyrings/v2raya.asc
