### ISSUE TITLE
Windows下的权限检查与配置文件目录被写死的问题

### ISSUE THREAD

**Issue by zanjie1999** [v2rayA/v2rayA#1078]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.2.3
2. 你通过什么方式安装v2rayA
exe直接运行（非安装）
3. 你所使用的操作系统
Windows x64

### 描述问题

![bd96c4d9ea1ebac08632fb3320dbb27b](https://github.com/v2rayA/v2rayA/assets/16502567/aea638fc-54fe-4af1-83e8-3c9db57d7f0a)
不要写死路径，Windows没有`/etc`，于是就暴毙，会一直提示geoip错误让去检查，
可以判断系统为Windows时放到当前目录下

### 复现问题的步骤

在当前目录打开管理员cmd，并运行`文件名 --passcheckroot`，因为Windows没有root用户所以得绕过检查

### 日志
因为删了换Docker部署了，日志没拷贝出来，并且问题非常明显，这就麻烦你自己跑下试试吧

**Comment by mzz2017** [comment]
@zanjie1999 不会给选项吗，哪里写死了？

**Comment by mzz2017** [comment]
@zanjie1999 windows要用--lite
