### ISSUE TITLE
invalid config: not support "redirect" mode of transparent proxy: ExecCommands: iptables -w 2 -t nat -N TP_OUT iptables v1.8.7 

### ISSUE THREAD

**Issue by glenlau228** [v2rayA/v2rayA#1085]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2rayA Version: 2.2.4

2. 你通过什么方式安装v2rayA
通过 v2rayA 自建软件源安装

3. 你所使用的操作系统
OpenWrt 22.03.5 r20134-5f15225c1e

### 描述问题：

invalid config: not support "redirect" mode of transparent proxy: ExecCommands: iptables -w 2 -t nat -N TP_OUT iptables v1.8.7 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?) Perhaps iptables or your kernel needs to be upgraded. : exit status 3

只要打开透明代理就会这样，这是什么原因，配置问题吗？请指教

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志

2023/09/14 11:22:39.535 [I] [process.go:101] low memory: 329MiB, set V2RAY_CONF_GEOLOADER=memconservative
2023/09/14 11:22:39.650 [I] [io.go:429] Xray 1.8.4 (Xray, Penetrates Everything.) OpenWrt (go1.20.7 linux/arm)
2023/09/14 11:22:39.650 [I] [io.go:429] A unified platform for anti-censorship.
2023/09/14 11:22:39.651 [I] [io.go:429] [Info] infra/conf/serial: Reading config: /etc/v2raya/config.json
2023/09/14 11:22:40.106 [W] [transparent.go:52] writeTransparentProxyRules: not support "redirect" mode of transparent proxy: ExecCommands: iptables -w 2 -t nat -N TP_OUT iptables v1.8.7 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/09/14 11:22:40.605 [E] [setting.go:51] invalid config: not support "redirect" mode of transparent proxy: ExecCommands: iptables -w 2 -t nat -N TP_OUT iptables v1.8.7 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3

```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
@glenlau228 是否开启特殊模式？如果开了就关掉

**Comment by glenlau228** [comment]
![image](https://github.com/v2rayA/v2rayA/assets/80826314/48968852-bd80-480a-9554-39ea5e2a83a0)

没有打开其它的，都是默认的配置

**Comment by glenlau228** [comment]
![image](https://github.com/v2rayA/v2rayA/assets/80826314/1d90cb39-bd8c-47ab-b6c6-e873a5d9f854)

**Comment by MarksonHon** [comment]
https://github.com/v2rayA/v2rayA-openwrt

照着补全内核模块然后重启系统

**Comment by glenlau228** [comment]
是再安装下  opkg install v2ray-core  对吗？

**Comment by glenlau228** [comment]
opkg install iptables-mod-conntrack-extra \

opkg install iptables-mod-extra \
opkg install iptables-mod-filter \
opkg install iptables-mod-tproxy \
opkg install kmod-ipt-nat6

我安装了这个之后就没的提示错误了，Google 已经正常，请教怎么样添加自定义的网站走代理

**Comment by MarksonHon** [comment]
v2raya.org

**Comment by glenlau228** [comment]
非常感谢问题已经解决
