### ISSUE TITLE
访问github出现一些问题

### ISSUE THREAD

**Issue by g1fts** [v2rayA/v2rayA#1094]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.2.4
![image](https://github.com/v2rayA/v2rayA/assets/20061353/777b83e6-1e8f-42b6-89fe-d895b26bc65d)

2. 你通过什么方式安装v2rayA
archlinuxcn源
3. 你所使用的操作系统
archlinux

### 描述问题：

1. github 经常显示不出来图片，有些可以有些不可以。比如：https://github.com/oldj/SwitchHosts
![image](https://github.com/v2rayA/v2rayA/assets/20061353/9e50af24-edf0-4292-92af-d1ff3667b66d)

2. 在终端里经常碰到github资源访问不到的问题。我这里是konsole安装软件需要从github拉资源时会出现错误
![image](https://github.com/v2rayA/v2rayA/assets/20061353/a9acc36f-767a-4f76-bdeb-4d3943142a2a)

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志

2023/09/21 17:44:02.593 [I] [io.go:432] [240e:3b3:38f1:cde0:a59:c39e:db9d:f9e]:60152 accepted tcp:[2a01:4f9:c010:50::1]:443 [『新加坡 新加坡2（V2推荐）』]
2023/09/21 17:44:19.592 [I] [io.go:432] 192.168.1.6:53094 accepted tcp:20.205.243.166:443 [『新加坡 新加坡2（V2推荐）』]
2023/09/21 17:44:21.878 [I] [io.go:432] 192.168.1.6:60884 accepted tcp:185.199.111.133:443 [『新加坡 新加坡2（V2推荐）』]
2023/09/21 17:44:25.425 [I] [io.go:432] [240e:3b3:38f1:cde0:a59:c39e:db9d:f9e]:57376 accepted tcp:[2404:6800:4008:c00::6c]:993 [『新加坡 新加坡2（V2推荐）』]
2023/09/21 17:44:25.741 [I] [io.go:432] [240e:3b3:38f1:cde0:a59:c39e:db9d:f9e]:36588 accepted tcp:[240e:ff:f100:8019::6a]:993 [direct]
2023/09/21 17:44:55.981 [I] [io.go:432] 192.168.1.6:42520 accepted tcp:20.205.243.166:443 [『新加坡 新加坡2（V2推荐）』]
2023/09/21 17:45:12.187 [I] [io.go:432] [240e:3b3:38f1:cde0:a59:c39e:db9d:f9e]:35712 accepted tcp:[2404:6800:4008:c02::bc]:5228 [『新加坡 新加坡2（V2推荐）』]



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![image](https://github.com/v2rayA/v2rayA/assets/20061353/73c8bd6f-d671-4371-9fe9-bbf09ac6e5bc)
![image](https://github.com/v2rayA/v2rayA/assets/20061353/cab01f21-52e4-49fa-a9bb-189f19d37af7)

**Comment by MarksonHon** [comment]
感觉你DNS污染没解决，可以设置下防止DNS污染
