### ISSUE TITLE
如何重置密码跟用户名

### ISSUE THREAD

**Issue by Yofo-me** [v2rayA/v2rayA#110]
如何重置密码跟用户名

**Comment by updater1234** [comment]
sudo v2raya --reset-password

**Comment by Yofo-me** [comment]
> sudo v2raya --reset-password

But my username is error.so how can I reset them?

**Comment by mzz2017** [comment]
> > sudo v2raya --reset-password
> 
> But my username is error.so how can I reset them?

`--reset-password` will reset both username and password.

**Comment by sometimestios** [comment]
What‘re the default username and password?

**Comment by mzz2017** [comment]
maybe some trouble happens

if there is no unique information saved in v2rayA, you can delete the database file under the directory /etc/v2raya and reboot.

**Comment by mzz2017** [comment]
> What‘re the default username and password?

Hello, you should reboot v2rayA and it works.
