### ISSUE TITLE
arm64架构系统无法通过软件源安装

### ISSUE THREAD

**Issue by iori-ichinose** [v2rayA/v2rayA#111]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
版本 1.1.1

2. 你通过什么方式安装v2rayA
软件源

3. 你所使用的操作系统
Debian arm64

### 描述问题：

安装时更新软件源出现以下错误提示，进而无法下载v2raya

![image](https://user-images.githubusercontent.com/58081463/97241460-21d27380-182c-11eb-8b9a-1dc3cc38cd5a.png)

**Comment by mzz2017** [comment]
感谢你的反馈，该问题将在下次发布时被修复

**Comment by mzz2017** [comment]
已尝试在v1.1.2中修复

**Comment by iori-ichinose** [comment]
嗯，看起来再1.1.2版本这个问题已经解决了
