### ISSUE TITLE
无法连接到127.0.0.1：2017 服务器

### ISSUE THREAD

**Issue by cwc2023** [v2rayA/v2rayA#1113]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

2. 你通过什么方式安装v2rayA

3. 你所使用的操作系统

### 描述问题：

连接失败，无法连接到服务器

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![img_v2_78b7b2a0-bf92-4f44-896b-854c5e04c7ix](https://github.com/v2rayA/v2rayA/assets/136964016/b940c275-ea92-4cd7-9d68-58e6f6f85ecb)

**Comment by MarksonHon** [comment]
v2raya.org 看文档

**Comment by beat4ocean** [comment]
没关防火墙
