### ISSUE TITLE
RoutingA的配置dialog在小米平板5上显示不全，导致无法保存

### ISSUE THREAD

**Issue by gyf9835** [v2rayA/v2rayA#1117]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.2.4
2. 你通过什么方式安装v2rayA
alpine手动安装
3. 你所使用的操作系统
alpine
android Chrome 117.0.5938.156

### 描述问题

点击RoutingA右边的配置按钮之后，弹出的dialog全屏都是输入框，看不到保存按钮，不论横竖屏都看不到

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![Screenshot_2023-10-17-20-42-28-060_com.android.chrome.jpg](https://github.com/v2rayA/v2rayA/assets/24644280/d7381c58-3472-44a1-8add-f95de2e6d34c)

![Screenshot_2023-10-17-20-42-32-484_com.android.chrome.jpg](https://github.com/v2rayA/v2rayA/assets/24644280/8c8268a1-557f-4a10-b89b-df55990fe59a)

**Comment by MarksonHon** [comment]
Thanks for your work!
