### ISSUE TITLE
无法连接到代理服务器

### ISSUE THREAD

**Issue by liujinhan2** [v2rayA/v2rayA#113]
1.1.2下可以正常运行V2rayA,但不能在另一台电脑上连接
代理机:Linux raspberrypi 5.4.72-v8+ #1356 SMP PREEMPT Thu Oct 22 13:58:52 BST 2020 aarch64 GNU/Linux
客户机:Linux kevin-81qm 5.9.1-1-MANJARO #1 SMP PREEMPT Sat Oct 17 11:44:44 UTC 2020 x86_64 GNU/Linux

代理机运行日志：

> 2020/10/31 02:05:53 handle.go:202: dnsPoison[eth0]: 192.168.0.208:54426 <- 192.168.0.101:53 (incoming.telemetry.mozilla.org. => [A:0.0.0.0])
> 2020/10/31 02:05:53 handle.go:207: dnsPoison[eth0]: [propose] incoming.telemetry.mozilla.org. proof: incoming.telemetry.mozilla.org.[A:0.0.0.0]
> 2020/10/31 02:05:53 handle.go:211: dnsPoison[eth0]: {add blocklist} incoming.telemetry.mozilla.org.
> 2020/10/31 02:05:53 handle.go:197: dnsPoison[eth0]: 192.168.0.208:54426 -> 192.168.0.101:53 incoming.telemetry.mozilla.org. poisoned as 240.0.0.1
> 2020/10/31 02:05:53 handle.go:197: dnsPoison[eth0]: 192.168.0.208:38871 -> 192.168.0.101:53 incoming.telemetry.mozilla.org. poisoned as 240.0.0.1
> 2020/10/31 02:05:53 handle.go:197: dnsPoison[eth0]: 192.168.0.208:38228 -> 192.168.0.101:53 incoming.telemetry.mozilla.org. poisoned as 240.0.0.1
> 2020/10/31 02:05:53 handle.go:197: dnsPoison[eth0]: 192.168.0.208:34771 -> 192.168.0.101:53 incoming.telemetry.mozilla.org. poisoned as 240.0.0.1
> 2020/10/31 02:05:53 handle.go:197: dnsPoison[eth0]: 192.168.0.208:53603 -> 192.168.0.101:53 incoming.telemetry.mozilla.org. poisoned as 240.0.0.1
> 2020/10/31 02:05:53 handle.go:197: dnsPoison[eth0]: 192.168.0.208:47175 -> 192.168.0.101:53 incoming.telemetry.mozilla.org. poisoned as 240.0.0.1
> 2020/10/31 02:05:53 handle.go:197: dnsPoison[eth0]: 192.168.0.208:38706 -> 192.168.0.101:53 incoming.telemetry.mozilla.org. poisoned as 240.0.0.1
> 2020/10/31 02:08:22 handle.go:202: dnsPoison[eth0]: 192.168.0.208:34606 <- 192.168.0.101:53 (www.google-analytics.com. => [A:0.0.0.0])
> 2020/10/31 02:08:22 handle.go:207: dnsPoison[eth0]: [propose] www.google-analytics.com. proof: www.google-analytics.com.[A:0.0.0.0]
> 2020/10/31 02:08:22 handle.go:211: dnsPoison[eth0]: {add blocklist} www.google-analytics.com.
> 2020/10/31 02:08:28 handle.go:202: dnsPoison[eth0]: 192.168.0.228:1164 <- 192.168.0.101:53 (tools.3g.qq.com. => [A:0.0.0.0])
> 2020/10/31 02:08:28 handle.go:207: dnsPoison[eth0]: [propose] tools.3g.qq.com. proof: tools.3g.qq.com.[A:0.0.0.0]
> 2020/10/31 02:08:28 handle.go:211: dnsPoison[eth0]: {add blocklist} tools.3g.qq.com.
>

**Comment by liujinhan2** [comment]
附图：
![image](https://user-images.githubusercontent.com/52961817/97741858-61e07180-1b1e-11eb-9d50-1609d4d51b2a.png)
![image](https://user-images.githubusercontent.com/52961817/97741889-702e8d80-1b1e-11eb-896d-45730c9eacc2.png)

**Comment by mzz2017** [comment]
不对劲啊，你这怎么全都被污染了

关掉增强模式

开启DOH看看

ssh进去这个树莓派能正常访问外网吗

**Comment by liujinhan2** [comment]
已解决，树莓派PiHole问题
