### ISSUE TITLE
使用docker镜像mzz2017/v2raya:latest，节点被泄漏，连续三天，当天换次日封，流量也被用完了，开发者解释一下？

### ISSUE THREAD

**Issue by yjw8336** [v2rayA/v2rayA#1140]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

2. 你通过什么方式安装v2rayA

3. 你所使用的操作系统

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```
 或者粘贴来自 Web 页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@yjw8336 我可没那么无聊，我有正经工作，开源只是我的兴趣，拜托

**Comment by MarksonHon** [comment]
@yjw8336 一点日志与截图都没有，你去庙里求告太上老君或者观音菩萨吧

**Comment by yjw8336** [comment]
西游记看多了？回去写作业吧小屁孩

**Comment by MarksonHon** [comment]
@yjw8336 https://t.me/v2raya_zh

欢迎进群找我们当众对线，不怕你不来，就怕你进不来哦！
