### ISSUE TITLE
To:MarksonHon

### ISSUE THREAD

**Issue by yjw8336** [v2rayA/v2rayA#1141]
这MarksonHon是什么东西？怎么v2rayA门口拴了一条疯狗吗？还对线，开源项目那么多，有空理你啊？
![1698815878710](https://github.com/v2rayA/v2rayA/assets/38392415/d96b01ff-c18c-4df3-a0ed-3afdbbc39837)

**Comment by yjw8336** [comment]
顺便说一句，电报群链接不要随便甩，垃圾

**Comment by bradfordzhang** [comment]
您的日志呢

**Comment by MarksonHon** [comment]
@yjw8336 公开群的链接都能搜索到的，放出来又何妨？我们的文档里面都写了的。还有，你无凭无据指责开发者盗取流量，那我们不得找你好好聊聊

**Comment by MarksonHon** [comment]
既然说不出来，那我替你说吧。
🔮1：你把v2rayA错误地用在了服务端，然后开启了端口分享，于是世界人民都可以用你的流量了
🔮2：你是用做了客户端，但是你用了端口分享，然后你的WAN口被别人偷了
再见吧，京爷
