### ISSUE TITLE
DNS解析不到apt.v2raya.org

### ISSUE THREAD

**Issue by ghost** [v2rayA/v2rayA#1153]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

latest

2. 你通过什么方式安装v2rayA

apt

3. 你所使用的操作系统

ubuntu

### 描述问题：

```
Err:9 https://apt.v2raya.org v2raya InRelease                                                                        
  Could not handshake: The TLS connection was non-properly terminated. [IP: 127.0.0.1 20172]
Fetched 353 kB in 14s (26.0 kB/s)   
```

```
 nslookup apt.v2raya.org 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

** server can't find apt.v2raya.org: NXDOMAIN
```

**Comment by Kagurazaka-yuqian** [comment]
通过查询dns历史记录发现
apt.v2raya.org cname mirrors.v2raya.org 最后更新11.04
mirrors.v2raya.org A 2.59.182.6 最后更新11.05
对应ip地址机器: Debian-5+deb11u2

所以这是为什么把解析记录删除了呢？

**Comment by du-xinyi** [comment]
> https://github.com/v2rayA/v2rayA/releases/tag/v2.2.4.1
> 
> > 使用 GitHub 的 url 而不是 v2raya.org v2rayA 自己的服务器已因缺钱而关闭

应该怎么替换，我将`echo "deb [signed-by=/etc/apt/keyrings/v2raya.asc] https://apt.v2raya.org/ v2raya main" | sudo tee /etc/apt/sources.list.d/v2raya.list`修改为`echo "deb [signed-by=/etc/apt/keyrings/v2raya.asc] https://github.com/v2rayA/v2raya-apt/ v2raya main" | sudo tee /etc/apt/sources.list.d/v2raya.list`报E: The repository 'https://github.com/v2rayA/v2raya-apt v2raya Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.的错误，就算把链接直接指定到`https://github.com/v2rayA/v2raya-apt/tree/master/dists/v2raya`还是同样的问题
