### ISSUE TITLE
[Feature] Is there (or considering) the feature of switching the proxy with one click?

### ISSUE THREAD

**Issue by SoTosorrow** [v2rayA/v2rayA#1155]
### 功能特性内容

Is there a more convenient way to turn on/off the proxy? 
Even outside the browser, For example, consider having a toolbar for shortcutso that you don’t need to do all operations in the browser. This can also quickly determine the status of v2raya

**Comment by SoTosorrow** [comment]
Maybe A simple client can be implemented that is only responsible for sending several settings api
like request "http://localhost:2017/api/setting"

**Comment by Gaojianli** [comment]
Press F12 and turn on/off the proxy, you can get what you want in the devtools.

**Comment by SoTosorrow** [comment]
> Press F12 and turn on/off the proxy, you can get what you want in the devtools.

I do not understand what you mean? What I am referring to is whether to consider adding a one-click run/stop proxy outside the browser so that there is no need to open the browser.
A complex method can be used to make a toolbar. In simple terms, it is two run/stop scripts to send requests.
