### ISSUE TITLE
v2raya局域网代理请求增加设置用户名和密码 怕别人薅羊毛 具体见后面图片，非常需要谢谢

### ISSUE THREAD

**Issue by chenxudong2020** [v2rayA/v2rayA#1159]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
最新docker拉取的lastet
2. 你通过什么方式安装v2rayA
docker
3. 你所使用的操作系统
群晖DS920+ 7.2

### 描述问题：

v2raya局域网代理能否支持http代理设置用户名和密码
v2raya局域网代理能否支持https代理 可以设置用户名和密码 怕别人薅羊毛

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by seltzer9055** [comment]
https://v2raya.org/docs/advanced-application/intranet-transmission/

**Comment by chenxudong2020** [comment]
> https://v2raya.org/docs/advanced-application/intranet-transmission/

这个我看了我的意思没界面上提供用户名和密码 配置的选项

**Comment by Gaojianli** [comment]
https代理需要证书，你可以自己设置一个反向代理

**Comment by du8028934** [comment]
这讨论的不应该是设置密码的问题么
inbound: httpauthin = http(address: 0.0.0.0, port: 1081, user: user1, pass: user1pass, user:user2, pass:user2pass)
inbound: socksauthin = socks(address: 0.0.0.0, port: 1082, udp:true, user: 123, pass: 123)
inbound: sockslocalin = socks(address: 127.0.0.1, udp:true, port: 1080)

我把这个插入到配置里，我发现账号密码设置的啥都起不到作用。输入错误也能链接。

**Comment by ncnnnnn** [comment]
试了半天，太绕了。。。

最后土办法上了。
先WIN下用v2rayn配置好局域网共享设置用户名和密码，
把config.json复制到linux，直接
v2ray run -c config.json

结束

**Comment by chenxudong2020** [comment]
![image](https://github.com/v2rayA/v2rayA/assets/61214170/7f6e1712-6e7a-4ca2-ba5f-976ccda7adc6)
