### ISSUE TITLE
docker部署后，按照官方教程进行配置后，发现经常显示是正在运行，但是无代理。有时经过多次断开重连刷新界面会成功

### ISSUE THREAD

**Issue by lh-kyf** [v2rayA/v2rayA#1164]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
最新的
2. What approach of installation do you install V2rayA?
docker
3. What is your operating system?
ubuntu

### Description

![image](https://github.com/v2rayA/v2rayA/assets/116720655/b7aef8c5-6f8e-4713-a0c0-a1aa5e4e958f)

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```
 You can also paste the log that comes from web administration page

```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by lh-kyf** [comment]
![image](https://github.com/v2rayA/v2rayA/assets/116720655/520c4213-6902-4c4e-8be4-3eda7c53334e)

**Comment by madwood123** [comment]
同样问题，连接节点后过一会就会显示timeout

**Comment by lh-kyf** [comment]
重装后已解决该问题
