### ISSUE TITLE
Can help to publish 2.2.4.1 version in synology docker (current is 2.2.4)?

### ISSUE THREAD

**Issue by tokyoqiang** [v2rayA/v2rayA#1165]
### Version, approach of installation, operating system
sysnology dsm7.2
1. What version of v2rayA are you using?
2.2.4
2. What approach of installation do you install V2rayA?
docker
3. What is your operating system?
dsm7.2

### Description

the latest version is 2.2.4 in which exits GFW list issue, as we know this is fixed in 2.2.4.1 version here, can help to publish 2.2.4.1 version in docker? Thanks!

![Snipaste_2023-11-10_22-27-49](https://github.com/v2rayA/v2rayA/assets/99979431/722aa002-90d7-4d75-9409-c02b75726a41)

**Comment by yyyfffccc** [comment]
+1

**Comment by Victor2333** [comment]
@mzz2017 https://github.com/v2rayA/v2rayA/actions/runs/6764494537/job/18563292110
v2.2.4.1 docker build failed during build frontend ui.

**Comment by MarksonHon** [comment]
@Victor2333 Can you give a help to fix the CI?

**Comment by Victor2333** [comment]
@MarksonHon 
Can't do it now.
Commit some code. Try to build.
https://github.com/Victor2333/v2rayA/actions/runs/6835178674
But failed to build.
https://github.com/docker/setup-qemu-action/issues/110
Will try later.

**Comment by MarksonHon** [comment]
version 2.2.4.3 has fixed building Docker images, however, thanks for your work, this issue will be closed now

**Comment by tokyoqiang** [comment]
@Victor2333 @MarksonHon 感谢Marksonhon 和 [Victor2333],GFW List问题已修复，但新问题出现：以前能多选节点，使用无法使用负载均衡，但现在只能单选，忘修复，感谢！

**Comment by tokyoqiang** [comment]
从xray 切换为v2ray，解决了问题，现一切正常，感谢大佬们！
