### ISSUE TITLE
Auto Change Server in Subscription every 5,10,15,30,60, custom, random_variable(5-15)

### ISSUE THREAD

**Issue by rony432** [v2rayA/v2rayA#1167]
### Is the feature related with existing problem?

No

### Content of the feature

automatically change connected proxy server from subscription list in defined times or manual input for range.
it is a fantastic option to have.

**Comment by MarksonHon** [comment]
@rony432 So where are your fantastic code and pull-request?🧐

**Comment by rony432** [comment]
it is a feature request my dude, i use it this every day, it would be awesome feature to have.
