### ISSUE TITLE
自己下载的GFWlist.txt 需要放在哪个目录下,才能被v2rayA 找到？

### ISSUE THREAD

**Issue by rollto** [v2rayA/v2rayA#1172]
### 版本、安装方式、系统     Linux Debian 12

1. 你在使用什么版本的v2rayA      2.2.4

2. 你通过什么方式安装v2rayA

3. 你所使用的操作系统   Debian 12

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
2.2.4.3 已经修复下载问题，建议更新。同时，v2ray/xray只支持dat格式的文件，不能直接引用txt文本

**Comment by reserveword** [comment]
> 2.2.4.3 已经修复下载问题，建议更新。同时，v2ray/xray只支持dat格式的文件，不能直接引用txt文本

希望及早更新openwrt软件包
