### ISSUE TITLE
V2.2.4.3 Docker Image不支持负载均衡

### ISSUE THREAD

**Issue by jasonjinchen** [v2rayA/v2rayA#1173]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2.2.4.3(latest)

2. 你通过什么方式安装v2rayA
Docker

3. 你所使用的操作系统
Linux (x86 CentOS) - Docker

### 描述问题

docker pull mzz2017/v2raya:latest
docker pull mzz2017/v2raya:v2.2.4.3

Container起来后，无法启用负载均衡，每个outbound只能选择一个固定的代理出口

如果已经选择了多个节点，则报错：failed to start v2ray-core: cannot select multiple servers: v2fly/v2ray-core only feature

### 复现问题的步骤

v2.2.4.3，v2.2.4.2均如此，必现，2.2.4正常

**Comment by MarksonHon** [comment]
@jasonjinchen https://t.me/v2raya_notification/94

**Comment by MarksonHon** [comment]
文档已经更新：
https://v2raya.org/docs/prologue/installation/docker/#%E8%BF%90%E8%A1%8C

**Comment by fashamu** [comment]
解决了吗，我发现也是这样，但是我换到2.2.4同样不能多选，是设置问题吗

**Comment by fashamu** [comment]
解决了，新增一个出站就可以了

**Comment by Victor2333** [comment]
> 解决了，新增一个出站就可以了

docker默认用的xray 不支持轮询 改docker启动参数 用v2ray就可以一个outbound多选了

**Comment by Tough-JK** [comment]
因为新版本默认用xray，要指定使用v2ray就可以了！

**Comment by 654850695** [comment]
# run v2raya
docker run -d \
  --restart=always \
  --privileged \
  --network=host \
  --name v2raya \
  -e V2RAYA_LOG_FILE=/tmp/v2raya.log \
  -e V2RAYA_V2RAY_BIN=/usr/local/bin/v2ray \
  -e V2RAYA_NFTABLES_SUPPORT=off \
  -v /lib/modules:/lib/modules:ro \
  -v /etc/resolv.conf:/etc/resolv.conf \
  -v /etc/v2raya:/etc/v2raya \
  mzz2017/v2raya

**Comment by fashamu** [comment]
好的谢谢
________________________________
发件人: 654850695 ***@***.***>
发送时间: 2023年12月10日 22:08
收件人: v2rayA/v2rayA ***@***.***>
抄送: fashamu ***@***.***>; Comment ***@***.***>
主题: Re: [v2rayA/v2rayA] V2.2.4.3 Docker Image不支持负载均衡 (Issue #1173)


run v2raya

docker run -d
--restart=always
--privileged
--network=host
--name v2raya
-e V2RAYA_LOG_FILE=/tmp/v2raya.log
-e V2RAYA_V2RAY_BIN=/usr/local/bin/v2ray
-e V2RAYA_NFTABLES_SUPPORT=off
-v /lib/modules:/lib/modules:ro
-v /etc/resolv.conf:/etc/resolv.conf
-v /etc/v2raya:/etc/v2raya
mzz2017/v2raya

―
