### ISSUE TITLE
GFWList更新问题

### ISSUE THREAD

**Issue by xiaozixun** [v2rayA/v2rayA#1177]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2.2.4.3

2. 你通过什么方式安装v2rayA
releases下载安装

3. 你所使用的操作系统
Windows 11 22H2 

### 描述问题

自从服务器关闭以来每次更新GFWList都无法成功

### 复现问题的步骤
1.打开设置
2.点击更新
3.等待一段时候后报错（关于“解析订阅链接/更新时优先使用”这里我把三个都试了试，日志如下）

 v2rayA/v2ray运行日志：

2023/11/16 12:32:31.960 [I] [gfwlist.go:112] Downloading https://github.com/v2rayA/dist-v2ray-rules-dat/raw/202311142209/geosite.dat to C:\Program Files\v2rayA\data\LoyalsoldierSite.dat.new
2023/11/16 12:32:39.469 [I] [io.go:432] 127.0.0.1:60469 accepted //incoming.telemetry.mozilla.org:443 [『中国 - 香港 - Akari Networks(3)』]
2023/11/16 12:32:53.039 [W] [gfwlist.go:155] UpdateLocalGFWList: Get "https://github.com/v2rayA/dist-v2ray-rules-dat/raw/202311142209/geosite.dat": dial tcp 20.205.243.166:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2023/11/16 12:32:53.039 [E] [gfwlist.go:12] Get "https://github.com/v2rayA/dist-v2ray-rules-dat/raw/202311142209/geosite.dat": dial tcp 20.205.243.166:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.（这是跟随规则端口下的日志）

Get "https://raw.githubusercontent.com/v2rayA/dist-v2ray-rules-dat/202311142209/geosite.dat": dial tcp: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found.（这是直连和不分流模式下的日志）

v2rayA设置以及相关截图
![Screenshot 2023-11-16 at 12-36-43 v2rayA](https://github.com/v2rayA/v2rayA/assets/22409452/ede5f1de-f3c8-4a9d-be7f-270d1c9e8391)

**Comment by xiaozixun** [comment]
![Screenshot 2023-11-16 at 12-36-43 v2rayA](https://github.com/v2rayA/v2rayA/assets/22409452/27f06b8e-f8fd-461b-a457-715fb9c57022)


能看到图吗

**Comment by kierdwyn** [comment]
碰到了同样的问题, 从“最新：2023-11-15” 那个链接里点进去，可以手动下载GFW.txt，但问题是不知道该放到哪里……
![image](https://github.com/v2rayA/v2rayA/assets/1897210/06b00941-5641-464d-85cd-b345991fa0b9)

**Comment by xiaozixun** [comment]
> 碰到了同样的问题, 从“最新：2023-11-15” 那个链接里点进去，可以手动下载GFW.txt，但问题是不知道该放到哪里…… ![image](https://user-images.githubusercontent.com/1897210/284008979-06b00941-5641-464d-85cd-b345991fa0b9.png)

\v2rayA\data\下

**Comment by 1sandy** [comment]
我这儿发生了类似的问题。我看了下弹出的出错提示，大致上的意思好像是说，在GFWlist的下载地址找到了文件，但没有需要下载的指定格式（大概是DAT），所以，下载不成功。这直接导致了服务启动不了。

于此同时，我chrome上的SwitchyOmega，是能通过https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt这个地址正常下载GFWlist的。这应该是与v2rayA用的同一个地址，但是TXT格式。

我的想法是：
1、v2rayA能不能在发行时就包括一个GFWlist文件？以避免第一次设置运行时，由于下载GFWlist失败导致的服务启动不了。
2、提供个一设置选择，可以自定义GFWlist的下载地址。
3、如果以上都不可行的话，至少在WEB UI上提供一个提示，说明在GFWlist应该被放在什么位置。如果安装版，与手动解压版需要的位置不同，请明确指出。

非常感谢。

**Comment by xiaozixun** [comment]
https://github.com/v2rayA/v2rayA/issues/1222#issuecomment-1859632495
