### ISSUE TITLE
Ubuntu Docker 部署 V2rayA 提示 缺少内核模块

### ISSUE THREAD

**Issue by misty-windy** [v2rayA/v2rayA#1178]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
latest

2. What approach of installation do you install V2rayA?
docker

4. What is your operating system?
Ubuntu Server 20.04 LTS 64bit

### Description

在Ubuntu上通过docker部署 v2rayA，访问Web GUI 界面时，提示：“检测到v2ray-core可能未正确安装，请检查”
查看镜像的Dockerfile 有安装内核的步骤，不知道为什么还是提示缺少

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

![v2rayA](https://github.com/v2rayA/v2rayA/assets/40721604/985c083d-d289-4958-a4c1-6edc3335ab82)

**Comment by MarksonHon** [comment]
https://v2raya.org/docs/prologue/installation/docker/
以及，你用的版本有够老

**Comment by zhangjun** [comment]
I encountered the same problem.  Modifying the Docker start command as following can fix it.

Replace 
```shell
-e V2RAYA_V2RAY_BIN=/usr/local/bin/v2ray \
```
with 
```shell
-e V2RAYA_V2RAY_BIN=/usr/bin/v2ray \
```
