### ISSUE TITLE
点击 “load core”无法启动

### ISSUE THREAD

**Issue by Jiqinglin** [v2rayA/v2rayA#1179]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
版本：Version 1.5.1 (1278)

2. 你通过什么方式安装v2rayA
安装方式：浏览器下载

4. 你所使用的操作系统
Macos m1 
13.2.1

### 描述问题：

打开软件，点击“load core”无法启动，没有任何反应
<img width="318" alt="image" src="https://github.com/v2rayA/v2rayA/assets/35061127/faaaeba7-6207-422b-a3df-f68067e173f3">

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志
<img width="544" alt="image" src="https://github.com/v2rayA/v2rayA/assets/35061127/46e06651-4ea6-44f9-91f2-428fd0741857">
<img width="536" alt="image" src="https://github.com/v2rayA/v2rayA/assets/35061127/ad5676b8-1727-451b-8cdb-51f12712aeb8">

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
你发错地方了
