### ISSUE TITLE
无法连接Vmess服务器 （Nginx + SSL + WS配置）

### ISSUE THREAD

**Issue by latorc** [v2rayA/v2rayA#118]
**Issue1**
无法连接这样配置的Vmess服务器：
![v2ray](https://user-images.githubusercontent.com/65785354/98252943-748ef680-1fb5-11eb-9600-7c14ea66fdc7.png)

服务器本身可以连接。该服务器同一个v2ray实例下，另一端口开了SS协议，可以连接：
![ss](https://user-images.githubusercontent.com/65785354/98253376-e9fac700-1fb5-11eb-9450-5b646097f44e.png)

请帮忙看看是不是该配置的vmess连接有问题？

**Issue2**
顺便问一下v2ray log所在位置。我用docker部署，想把log目录映射出来查看一下。
如果在Web GUI上能增加查看log功能也不错。

谢谢帮助 in advance

**Comment by mzz2017** [comment]
试试AllowInsecure？

log的话默认是关闭的，手动修改/etc/v2ray/config.json添加log然后重启v2ray（不要改动v2raya否则配置会重新刷新）

或者源码运行，自动debug模式就会有log了

**Comment by latorc** [comment]
> 试试AllowInsecure？
> 
> log的话默认是关闭的，手动修改/etc/v2ray/config.json添加log然后重启v2ray（不要改动v2raya否则配置会重新刷新）
> 
> 或者源码运行，自动debug模式就会有log了

AllowInsecure以后可以连接了，谢谢！不过该网址的ssl证书是ok的，照理来说应该没问题。

**Comment by mzz2017** [comment]
check证书的有效性是v2ray-core做的，可以用chrome访问检查，以及检查域名。
另外，如果连接的是中转节点，也会产生该问题。

**Comment by latorc** [comment]
多谢解答：）这个工具放在NAS上很好用~支持~
