### ISSUE TITLE
能否增加一个outbound的服务器列表轮询功能，不要选择最佳连接的，而且循环列表

### ISSUE THREAD

**Issue by 851459955** [v2rayA/v2rayA#1183]
### 您想提出的功能特性是否和现有问题相关？

现在是选择最佳网络速度的, 但是我有多个服务器，我想每个请求都均分到各个服务器，以保证每台的使用率都差不多

### 功能特性内容

可以在选择的服务器中，均衡负载的，将每个请求都每个服务器

**Comment by Victor2333** [comment]
内核用v2ray xray只支持选择一个节点 v2ray支持选多个节点

**Comment by 851459955** [comment]
> 内核用v2ray xray只支持选择一个节点 v2ray支持选多个节点
多个节点咋玩

**Comment by 851459955** [comment]
> 内核用v2ray xray只支持选择一个节点 v2ray支持选多个节点

多个节点咋弄，不是很懂呀

**Comment by Victor2333** [comment]
> > 内核用v2ray xray只支持选择一个节点 v2ray支持选多个节点
> 
> 多个节点咋弄，不是很懂呀
https://v2raya.org/docs/manual/use-other-core/

**Comment by 851459955** [comment]
> > > 内核用v2ray xray只支持选择一个节点 v2ray支持选多个节点
> > 
> > 
> > 多个节点咋弄，不是很懂呀
> 
> https://v2raya.org/docs/manual/use-other-core/
> 
> https://v2raya.org/docs/manual/variable-argument/

好的我试试，感谢您的回复
