### ISSUE TITLE
如何通过nginx给v2raya的http proxy设置帐号和密码

### ISSUE THREAD

**Issue by c4ys** [v2rayA/v2rayA#119]
想将v2raya部署到线上服务器，然后通过nginx加一层用户名和密码设置，便于在公司和家里都能通过v2raya访问外网，而不用安装多个v2ray，不知道应该如何设置。

或者可以直接给v2raya的http proxy设置密码和用户？

**Comment by mzz2017** [comment]
将http/socks端口暴露在公网中是及其不安全和不推荐的，相当于明文传输数据。
如果你执意如此，可以研究一下wiki里的routingA。

**Comment by libli** [comment]
我在routingA里面新增加的inhound http proxy，给了账号密码，用了一个新的port。但下面写的路由规则在这个新的port上不生效，为什么？
