### ISSUE TITLE
订阅应该可以解析任意uri

### ISSUE THREAD

**Issue by eexpress** [v2rayA/v2rayA#1192]
### 您想提出的功能特性是否和现有问题相关？

订阅导入只能是一个base64的文件？

### 功能特性内容

v2rayNG吃各种内容，包括一个网页。反正就是正则提取下特征链接而已。

**Comment by easterNday** [comment]
我的v2rayNG似乎也只能导入base64文件？

**Comment by eexpress** [comment]
> 我的v2rayNG似乎也只能导入base64文件？

一些网页文本发布一堆 vmess://xxxx trojan://xxxx的行。NG都一堆导入。比如 https://github.com/aiboboxx/v2rayfree/。才测试了。

**Comment by MarksonHon** [comment]
目前没计划
