### ISSUE TITLE
installation fails on arch 

### ISSUE THREAD

**Issue by Mahgozar** [v2rayA/v2rayA#1196]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?

2. What approach of installation do you install V2rayA?
yay -S v2raya
3. What is your operating system?
arch linux

### Description

during installation it exits with the following error code

### Logs：
error @achrinza/event-pubsub@5.0.9: The engine "node" is incompatible with this module. Expected version "13 || 14 || 16 || 17 || 18 || 19 || 20". Got "21.2.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: v2raya-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
v2raya - exit status 4
 
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```
 You can also paste the log that comes from web administration page

```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by MarksonHon** [comment]
@Mahgozar use v2raya-bin instead

**Comment by Mahgozar** [comment]
it worked thank you
