### ISSUE TITLE
透明代理中DNS污染问题

### ISSUE THREAD

**Issue by koalang** [v2rayA/v2rayA#1198]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.2.4.3

3. 你通过什么方式安装v2rayA
手动安装

5. 你所使用的操作系统
Ubuntu 22.04 LTS

### 描述问题：

在一台linux主机上v2rayA部署当旁路由，使用透明代理，DNS防污染关闭，由在本机的AdguardHome接管，
AdguardHome配置了两个上游DNS，分别是腾讯和阿里的DOH

访问被污染的网站，如https://teddysun.com/
由于是使用国内的DNS, 所以返回的DNS也是污染的
解析到twitter去了，但是局域网内的设备可以正常访问，这是为什么？

### v2rayA运行日志（Optional）：

routingA配置如下：
```
default: proxy
# write your own rules below
domain(domain:mail.qq.com)->direct

#dns
domain(domain:doh.pub)->direct
domain(domain:dns.alidns.com)->direct


domain(geosite:google-scholar)->proxy
domain(geosite:category-scholar-!cn, geosite:category-scholar-cn)->direct
domain(geosite:geolocation-!cn, geosite:google)->proxy
domain(geosite:cn)->direct
ip(geoip:hk,geoip:mo)->proxy
ip(geoip:private, geoip:cn)->direct
```

### v2rayA设置以及相关截图

v2rayA的配置
![chrome_sOh5eaw4Cl.png](https://66img.cc/images/2023/11/28/chrome_sOh5eaw4Cl.png)

adguardHome DNS配置
![chrome_ChEMcn9Pd8.png](https://66img.cc/images/2023/11/28/chrome_ChEMcn9Pd8.png)

**Comment by Victor2333** [comment]
问题没有描述清楚
1.dns没被污染的设备网关配置的是旁路由吗？
2.dns被污染的设备dns配的是内网地址还是外网地址

只要在解析dns的环节 都有可能发生dns污染
解决dns污染的本质是解析dns的udp或者https请求走proxy

eg.
访问 https://teddysun.com/
host -> dns(teddysun) -> adguard -> **_dns(doh.pub) -> default dns provider_** -> return ip(doh.pub) to adguard -> dns query to ip(doh.pub) with (teddysun) -> **_doh.pub dns request to high level dns provider_** -> ip(teddysun) -> adguard -> host

加粗斜线的部分都是会被dns污染的
但是如果你用的是http proxy或者sock proxy那么dns查询也会走proxy 所以不会污染

如果走的是透明代理 你需要配置网关到透明代理 还需要配置 透明代理的网关劫持dns请求 让dns请求走代理 就解决了dns污染的问题

但是如果你配置的网关是内网地址，dns也是内网地址就会有问题 dns请求就会直接走内网广播 不经过你的旁路由网关 也就不会做dns劫持这件事

你需要debug到底哪条链路的dns没有走代理而导致发生的污染

可以用dig命令
eg.
dig google.com @1.1.1.1

**Comment by koalang** [comment]
@Victor2333  感谢回复

> 1.dns没被污染的设备网关配置的是旁路由吗？
> 2.dns被污染的设备dns配的是内网地址还是外网地址

我是在旁路由上使用dig或者curl测试的，旁路由网关配置的的是主路由，虽然dns污染了，但是可以正常访问，局域网内其他设备配置了网关指向旁路由，现象跟在旁路由上测试的一样。

会不会跟开了域名嗅探有关系，虽然本地被污染了，但在远程机器上嗅探还原了

**Comment by Victor2333** [comment]
> @Victor2333 感谢回复
> 
> > 1.dns没被污染的设备网关配置的是旁路由吗？
> > 2.dns被污染的设备dns配的是内网地址还是外网地址
> 
> 我是在旁路由上使用dig或者curl测试的，旁路由网关配置的的是主路由，虽然dns污染了，但是可以正常访问，局域网内其他设备配置了网关指向旁路由，现象跟在旁路由上测试的一样。
> 
> 会不会跟开了域名嗅探有关系，虽然本地被污染了，但在远程机器上嗅探还原了
> 
> ```
> root@koalaserver:~# dig google.com @1.0.0.1
> ; <<>> DiG 9.18.12-0ubuntu0.22.04.3-Ubuntu <<>> google.com @1.0.0.1
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54153
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;google.com.                    IN      A
> ;; ANSWER SECTION:
> google.com.             245     IN      A       142.250.66.46
> ;; Query time: 7 msec
> ;; SERVER: 1.0.0.1#53(1.0.0.1) (UDP)
> ;; WHEN: Tue Dec 05 15:58:36 CST 2023
> ;; MSG SIZE  rcvd: 55
> ```

其他设备的dns配的是adguard？adguard是内网地址？

**Comment by koalang** [comment]
@Victor2333 
> 其他设备的dns配的是adguard？adguard是内网地址？

是的，其他设备我手动改网关和dns，dns改成旁路由所在的ip，因为adh部署在旁路由上

**Comment by Victor2333** [comment]
> @Victor2333
> 
> > 其他设备的dns配的是adguard？adguard是内网地址？
> 
> 是的，其他设备我手动改网关和dns，dns改成旁路由所在的ip，因为adh部署在旁路由上 是内网ip

你这种情况把adguard和旁路由放在一起情况就比较复杂也很难调试了，
有额外的防火墙配置劫持dns查询吗？

要弄清楚dns请求到底去哪了

1.dns请求被旁路由劫持了
2.dns去了adguard adguard请求上游dns被旁路由劫持

如果2种情况都没有发生 那么就是会被dns污染的 因为dns请求没走代理

**Comment by Victor2333** [comment]
我之前碰到过一个类似的情况
我的本地环境是
网关和dns是分开的
dns配了内网地址 没有走网关 所以没有dns劫持 也就被污染了
但是dns配外网地址
dns请求就会走网关 被劫持了 也就不会被污染了

**Comment by koalang** [comment]
就只有adguardhome了 没有其他劫持dns了，从在dig上看 是被adh接管了，局域网其他设备上网，dns查询记录也可以在adh的日志中可以查询到，ip是被污染的，但是可以正常访问，我后来怀疑就是域名嗅探的功劳了

**Comment by Victor2333** [comment]
> @Victor2333 就只有adguardhome了 没有其他劫持dns了，从在dig上看 是被adh接管了，局域网其他设备上网，dns查询记录也可以在adh的日志中可以查询到，ip是被污染的，但是可以正常访问，我后来怀疑就是域名嗅探的功劳了

我再理解下，
你的问题是局域网内 使用adguard的设备没有问题是吗？
但是旁路由自己有问题是吗？

**Comment by koalang** [comment]
> > @Victor2333 就只有adguardhome了 没有其他劫持dns了，从在dig上看 是被adh接管了，局域网其他设备上网，dns查询记录也可以在adh的日志中可以查询到，ip是被污染的，但是可以正常访问，我后来怀疑就是域名嗅探的功劳了
> 
> 我再理解下， 你的问题是局域网内 使用adguard的设备没有问题是吗？ 但是旁路由自己有问题是吗？

都没有问题，我的疑问是，为啥拿到的ip是污染的，但最后可以正常访问。
我现在的网络拓扑是
光猫拨号，LAN接到主路由WAN，主路由LAN接Linux小主机，小主机上安装v2rayA 开启透明代理，同时安装adguard。主路由dns首选指向了小主机的IP，方便其他设备dns去广告。需要特殊用途的设备，我会手动改网关到小主机上。

**Comment by Victor2333** [comment]
应该是adguard某种程度上不是可以防污染吧
<img width="662" alt="image" src="https://github.com/v2rayA/v2rayA/assets/20839187/23c36eeb-c98b-4340-9350-071821f8c762">

**Comment by koalang** [comment]
> 应该是adguard某种程度上是可以防污染吧 <img alt="image" width="662" src="https://private-user-images.githubusercontent.com/20839187/287972461-23c36eeb-c98b-4340-9350-071821f8c762.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjUxNjcsIm5iZiI6MTcwMTc2NDg2NywicGF0aCI6Ii8yMDgzOTE4Ny8yODc5NzI0NjEtMjNjMzZlZWItYzk4Yi00MzQwLTkzNTAtMDcxODIxZjhjNzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA4Mjc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YmE3NmQxNjUxMGI4NzU3OTNiZjBkY2I3MGZhYzU1MWY1M2IwZDdiNDU1M2E2ZTY5NGRhM2RhYjUxMzEwNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LiI9b0gluswrP3OPPWJwxVGGT8rcBxoAx0Og22kpLEo"> 只是解析出来的ip不是基于你的ip解析的

adh本身没有域名分流的功能，而且我上游都是国内的DNS，必然是污染的ip，ip归属地我都查过，都是分配的twitter之类的ip，ecs透传ip的话解决不了污染的问题，顶多是cdn访问差点而已。

**Comment by Victor2333** [comment]
能dig下看看走adguard的话 解析google.com返回的是google的ip吗？

**Comment by Victor2333** [comment]
那这不是adguard dns没被污染？

**Comment by koalang** [comment]
> 那这不是adguard dns没被污染？

dig google返回googole，其他小众的就不行了，返回是污染的IP，比如

```
root@koalaserver:~/blrec# dig teddysun.com

; <<>> DiG 9.18.12-0ubuntu0.22.04.3-Ubuntu <<>> teddysun.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30582
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;teddysun.com.                  IN      A

;; ANSWER SECTION:
teddysun.com.           60      IN      A       199.96.62.41

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1) (UDP)
;; WHEN: Tue Dec 05 22:47:51 CST 2023
;; MSG SIZE  rcvd: 57
```

国内的公共DNS是不会提供防污染的，尤其是这种网站，DoH/DoT也不例外，我adh上游都是国内的DNS

**Comment by Victor2333** [comment]
了解了
要解决这种情况就比较麻烦了
核心思路就是adguard在解析域名的时候 发现是gfwlist里block的域名 就要走代理去解析

v2ray不提供一种直接提供dns服务 而且v2raya和最新的v2ray对应的dns配置格式还不兼容
v2raya的透明代理是通过防火墙(iptables)打mark然后给到v2ray特定端口 实现的代理
对dns劫持也是，通过ip包target的端口是不是53判断要不要打mark

clash是支持监听53端口 实现了一个dns服务
之前我是把自己的dns上游配在了clash上 根据domain在不在gfwl block list里来决定要不要用clash的dns 后来clash repo没了 才换到的v2ray
这套逻辑就一直也没实现
