### ISSUE TITLE
RoutingA 生成的规则会自动填入inboundTag，是否可以修改或去掉

### ISSUE THREAD

**Issue by MutipleA** [v2rayA/v2rayA#1200]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
V2Ray 5.12.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.21.4 linux/amd64)
2. 你通过什么方式安装v2rayA
手动安装
3. 你所使用的操作系统
ubuntu 22.04
### 描述问题：

![image](https://github.com/v2rayA/v2rayA/assets/32366084/26aa7ce5-4686-45b8-bfa2-66f940196288)
![image](https://github.com/v2rayA/v2rayA/assets/32366084/09a14c68-2f8b-4f24-95f4-08805a7186b7)
![image](https://github.com/v2rayA/v2rayA/assets/32366084/1fe8b25a-28b7-4ab0-9164-67f299312445)

我注意到config.json已经被更改了，但是新增了inboundTag字段，我想知道这个inboundTag是否可以更改或者直接去掉？
手动更改并重新拉起core当然可以应对此问题，但是我想直到RoutingA 本身是否可以做这件事

**Comment by Victor2333** [comment]
可以通过配置多规则文件 通过规则覆盖的方式实现

**Comment by MutipleA** [comment]
> 可以通过配置多规则文件 通过规则覆盖的方式实现
哦哦，  麻烦再问一下，  你指的是v2ray的多规则文件 还是下面这种方式？ 
https://v2raya.org/docs/advanced-application/custom-extra-config/

**Comment by Victor2333** [comment]
> > 可以通过配置多规则文件 通过规则覆盖的方式实现
> > 哦哦，  麻烦再问一下，  你指的是v2ray的多规则文件 还是下面这种方式？
> > https://v2raya.org/docs/advanced-application/custom-extra-config/

我指的是 https://v2raya.org/docs/manual/variable-argument/
<img width="526" alt="image" src="https://github.com/v2rayA/v2rayA/assets/20839187/bb6b871c-eeb5-4649-b574-12ef6ce19f33">
这个功能 覆盖规则要看v2ray的文档

**Comment by Victor2333** [comment]
你可以配置一个目录 这个目录的配置会根据v2ray或者xray的多文件覆盖规则覆盖已有的配置
https://www.v2fly.org/config/multiple_config.html#%E8%A7%84%E5%88%99%E8%AF%B4%E6%98%8E

**Comment by Victor2333** [comment]
> > 可以通过配置多规则文件 通过规则覆盖的方式实现
> > 哦哦，  麻烦再问一下，  你指的是v2ray的多规则文件 还是下面这种方式？
> > https://v2raya.org/docs/advanced-application/custom-extra-config/

这种方式看起来应该也可以 但是我不大喜欢这种代码加hook 所以我没尝试过

**Comment by MutipleA** [comment]
好的， 感谢，解决了

**Comment by MutipleA** [comment]
已解决，关闭
