### ISSUE TITLE
检测后批量删除及导出功能

### ISSUE THREAD

**Issue by buvta** [v2rayA/v2rayA#121]
现在可以批量检测节点，但不能保存检测结果，所以我想能不能加个批量删除功能，利用排序加上多选将检测后的某些节点删除掉

如果可以的话麻烦再加上导出功能，现在有些订阅更新后新节点反而不如以前，有些订阅可能失效一更新数据全部丢失——或者做成“撤销更新”

**Comment by mzz2017** [comment]
我很理解使用公共节点的用户，他们需要频繁更新订阅并选择较好的节点，所以负载均衡和节点质量检测是他们的主要需求。但这些需求与v2ryaA的主要特点并不完全重合。

我在之前考虑过专门为这部分用户设计一种类似clash的隧道，支持基于节点质量检测的自动负载均衡，以及基于节点质量检测的订阅的自动更新与节点保留，但因为种种原因，包括了我们认为anti-censor是需要有一定代价的，developer不应该过分降低门槛，这个设计被搁浅了。

无论如何，批量导出的功能在我看来是一个与上述考虑的使用场景并不完全一致的特性，我会在将来将其引入v2rayA，谢谢。

**Comment by buvta** [comment]
多谢回复，也可以不用导出，可以将每个订阅单独保存为一个文件，更新时先将旧文件加拓展名.bak，需要撤销时直接将.bak文件恢复

**Comment by mzz2017** [comment]
目前v2raya的数据全部保存于/etc/v2raya/0.dat，你可以通过cron的方式，将时间作为文件名对其进行备份，并通过覆盖0.dat进行还原。

**Comment by mzz2017** [comment]
该 issue 由于长期没有回复而将被关闭。
