### ISSUE TITLE
能否根据域名选择节点代理

### ISSUE THREAD

**Issue by hb-0** [v2rayA/v2rayA#1210]
### 您想提出的功能特性是否和现有问题相关？

现在两个节点，分别位于韩国和新加坡。在访问一些18禁网站时，不知是否韩国有政策，韩国的节点无法显示图片。

### 功能特性内容

能否配置实现特定网站走特定节点？

**Comment by mzz2017** [comment]
@hb-0 看文档

**Comment by hb-0** [comment]
> @hb-0 看文档

看了文档，似乎只有这个可能有用，多节点分流：https://v2raya.org/docs/advanced-application/multiple-outbound-routing/
但怎么关联某一个节点，比Disney组如何对应某一个节点，文档并没有写清楚啊。
