### ISSUE TITLE
2.2.4.3无法进行局域网代理了?

### ISSUE THREAD

**Issue by King-OOA** [v2rayA/v2rayA#1215]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2. 2.4.3

3. 你通过什么方式安装v2rayA
ubuntu添加软件源

4. 你所使用的操作系统
ubuntu 22.04

### 描述问题：

![图片](https://github.com/v2rayA/v2rayA/assets/20796065/c9f95474-3658-46ea-90b9-164db97a670f)

设置里面找不到"局域网共享"这个选项了,无法为其他局域网机器代理

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
使用端口分享
