### ISSUE TITLE
提议增加一个流量统计的功能

### ISSUE THREAD

**Issue by jim-sang** [v2rayA/v2rayA#1217]
### 功能特性内容

可以在主页方便的观察当前订阅下所使用的流量统计，以便于管理预算，希望大神能采纳，谢谢。

**Comment by dingpamaoo** [comment]
另外希望增加每条连接的带宽监控信息，这对于客户端没有带宽统计的上传下载（例如油管web端上传视频）很重要，带宽使用率上不去的时候需要切换线路

**Comment by GuoYuefei** [comment]
建议针对docker应用的，每天少近10g的流量，都不知道哪个gou应用在乱用代理
