### ISSUE TITLE
多文件配置 confdir

### ISSUE THREAD

**Issue by lekai63** [v2rayA/v2rayA#122]
### 您想提出的功能特性是否和现有问题相关？

目前v2raya通过routingA、或者自定义config.json形式确实可以完成一些自定义的事情。
但是如果希望完成更复杂的需求，比如：
1、同时用作server端，多开一个ss协议的inbound  用以接收一个额外的公网入站连接
2、对于流媒体分流至一个专门的节点

### 功能特性内容

v2ray core 支持 --confdir 参数，方便多文件配置。v2raya是否也能同步跟进。
看代码应该是这个文件 v2rayA/service/core/v2ray/status.go 的RestartV2rayService()函数在调用os.StartProcess时修改下参数。
不知道是否会影响其他方面

**Comment by lekai63** [comment]
补充说明：
期待的实现是：
v2raya通过webui实现了一个config.json , 用户的其他自定义需求可以自建custom.json
两个json放到$CONF目录，v2raya启动/重启时，使用 --confdir $CONF 参数来使相关配置生效

**Comment by mzz2017** [comment]
很棒的提议，我希望能够尽快将其引入v2rayA。近期我的时间不是很多，在我有空闲时将进行相关的实现。

**Comment by mzz2017** [comment]
https://github.com/v2rayA/v2rayA/releases/tag/v1.2.1
