### ISSUE TITLE
"The requested name is valid, but no data of the requested type was found." when I want to update GFWList

### ISSUE THREAD

**Issue by zlgxzswjy** [v2rayA/v2rayA#1222]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
  2.2.4.6

2. What approach of installation do you install V2rayA?

[installer_windows_inno_x64_2.2.4.6.exe](https://github.com/v2rayA/v2rayA/releases/download/v2.2.4.6/installer_windows_inno_x64_2.2.4.6.exe)  

3. What is your operating system?

windows 11

### Description

I noticed that my GFWLIST was still stuck at 2023-11-01, so I clicked the update button next to it, but the following prompt appeared：
Get "https://raw.githubusercontent.com/v2rayA/dist-v2ray-rules-dat/202312122209/geosite.dat": dial tcp: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found.

I think that means network  is good, but parsing data files is just a problem.
### Steps to reproduce

Setting -> GFWList's right -> update
### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```

 You can also paste the log that comes from web administration page

```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by ilxqx** [comment]
直接手动下载，然后放到(Windows)：
`cd %LOCALAPPDATA%`
dir 查看一下是否存在 v2ray 目录，不存在新建一个
然后将下载好的`geoip.dat/geosite.dat`扔到v2ray目录里面
重启即可

**Comment by MarksonHon** [comment]
> 直接手动下载，然后放到(Windows)： `cd %LOCALAPPDATA%` dir 查看一下是否存在 v2ray 目录，不存在新建一个 然后将下载好的`geoip.dat/geosite.dat`扔到v2ray目录里面 重启即可

你这是在误导人啊

**Comment by MarksonHon** [comment]
https://t.me/v2raya_zh/143067

**Comment by ilxqx** [comment]
@MarksonHon 没有误导你，我就是这么干的，只是我的是Mac，存放的路径跟你不一样，根据xdb标准，你的应该是在app_data目录，或者你直接定义环境变量`V2RAY_LOCATION_ASSET`，内容就是你存放那一堆 .dat 文件的目录也是可以识别的，你自己试试

**Comment by ilxqx** [comment]
V2RAY_LOCATION_ASSET 环境变量对所有操作系统通用

**Comment by sycki** [comment]
> @MarksonHon 没有误导你，我就是这么干的，只是我的是Mac，存放的路径跟你不一样，根据xdb标准，你的应该是在app_data目录，或者你直接定义环境变量`V2RAY_LOCATION_ASSET`，内容就是你存放那一堆 .dat 文件的目录也是可以识别的，你自己试试

What others are reporting is a bug, what are you talking about?
