### ISSUE TITLE
Why v2raya would like to access files?! on removable volume!!!?

### ISSUE THREAD

**Issue by m-alikhani** [v2rayA/v2rayA#1228]
<img width="298" alt="Screen Shot 1402-09-28 at 18 36 56" src="https://github.com/v2rayA/v2rayA/assets/8352475/7fe3559d-4a7a-4223-858c-fe384ff68028">

Why?

**Comment by m-alikhani** [comment]
And Contact and Photos and ...

**Comment by MarksonHon** [comment]
It's an unknown macOS problem while v2rayA running with Launchd. Someone has reported before you, however, it is currently difficult for us to fully reproduce it. Restarting v2rayA service might be helpful.
