### ISSUE TITLE
kali linux里面v2raya点击start报错

### ISSUE THREAD

**Issue by Seant1125** [v2rayA/v2rayA#1235]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
    Version: 2.2.4.6

2. 你通过什么方式安装v2rayA
    按照v2raya.org文档说明提示，添加公钥，添加软件源，更新软件源，
    sudo apt install v2raya v2ray

5. 你所使用的操作系统
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2023.4"
VERSION="2023.4"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian

### 描述问题：

安装完成以后，客户端正常打开，正常创建用户名和密码，导入节点，点击start，报错，详见如下：

2023/12/22 17:02:11.519 [I] [io.go:432] V2Ray 5.12.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.21.4 linux/amd64)
2023/12/22 17:02:11.519 [I] [io.go:432] A unified platform for anti-censorship.
2023/12/22 17:02:11.908 [I] [io.go:432] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: geosite:google > infra/conf/rule: failed to load geosite: google > infra/conf/geodata/standard: list not found in geosite.dat: google
2023/12/22 17:02:11.911 [W] [asm_amd64.s:1650] v2ray-core: exit status 1
2023/12/22 17:02:11.995 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志
2023/12/22 17:02:11.519 [I] [io.go:432] V2Ray 5.12.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.21.4 linux/amd64)
2023/12/22 17:02:11.519 [I] [io.go:432] A unified platform for anti-censorship.
2023/12/22 17:02:11.908 [I] [io.go:432] Failed to start: main/commands: failed to load config: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: geosite:google > infra/conf/rule: failed to load geosite: google > infra/conf/geodata/standard: list not found in geosite.dat: google
2023/12/22 17:02:11.911 [W] [asm_amd64.s:1650] v2ray-core: exit status 1
2023/12/22 17:02:11.995 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information


```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![Screenshot_2023-12-22_18-27-26](https://github.com/v2rayA/v2rayA/assets/30857447/4111841e-48a2-4a56-8aff-4e816fffb16b)

**Comment by mzz2017** [comment]
@Seant1125 卸载了重新装

**Comment by mzz2017** [comment]
@Seant1125 你的 v2ray-core 有问题

**Comment by Seant1125** [comment]
卸载过，重新安装一遍，还是一样。甚至重新下载geoip.dat, geosite.dat，替换以后，还是报一样的错。

**Comment by mzz2017** [comment]
@Seant1125 sudo find /usr -name geosite.dat -exec rm {} \;

**Comment by mzz2017** [comment]
@Seant1125 然后再重新装

**Comment by Seant1125** [comment]
搞定了，系统里面还有其他v2ray版本，删除干净以后，重新安装以后，就正常了，感谢！
