### ISSUE TITLE
日志时区貌似不对，如何设置？

### ISSUE THREAD

**Issue by YahuiAn** [v2rayA/v2rayA#124]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.1.2
2. What approach of installation do you install V2rayA?
docker
3. What is your operating system?
ubuntu 20.04

### Description
日志的时区貌似不对，如何设置？

### Logs：
![image](https://user-images.githubusercontent.com/39142491/100756627-5edfe600-3428-11eb-8711-6e182863100a.png)

**Comment by mzz2017** [comment]
这个不影响使用。

**Comment by YahuiAn** [comment]
好的～
