### ISSUE TITLE
Is it possible to remove a subscription

### ISSUE THREAD

**Issue by guoapeng** [v2rayA/v2rayA#1241]
### 您想提出的功能特性是否和现有问题相关？

首先感谢v2raya team的努力，以至于我们不被封锁在高墙之内！

当前在使用v2raya的过程中也遇到一些问题。

在v2raya web界面， 只有导入和创建节点功能。但是在导入订阅后没有办法删除订阅，比如我有一个订阅已经过期了，订阅下的servers都因为过期不可用了，但是我想删除整个订阅，似乎系统不提供这样的功能。

比如截图中APIV2.LIPULAI.COM这个订阅已经与昨天过期了，我想把它删除掉，但是不知道怎么删除。
![image](https://github.com/v2rayA/v2rayA/assets/5491418/73583b86-3d42-4859-89af-defbedab4703)

### 功能特性内容

所以我的建议是添加一个订阅管理的界面，用于创建，管理和删除订阅。类似与设置节目，放置一个一级菜单，一个单独的节目用于管理订阅。

**Comment by mzz2017** [comment]
最左边那个 subscription 点开

**Comment by guoapeng** [comment]
> 最左边那个 subscription 点开

oh, got it. 点开里面有两个subscription, 删除想要删除的subscription就可以， 谢谢@mzz2017

**Comment by guoapeng** [comment]
closed the issue since there is remove subscription there. just not that intuitive.
