### ISSUE TITLE
Snap version doesn't work

### ISSUE THREAD

**Issue by mirhmousavi** [v2rayA/v2rayA#1242]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
2.2.4.6

2. What approach of installation do you install V2rayA?
snap

3. What is your operating system?
Ubuntu 22.04

### Description

I'm having a hard time figuring out how packet forwarding works in the snap version. I installed v2ray through apt and a new set of rules was added to nftable it's working fine however when I install it through snap nothing is added to nftable and my machine just doesn't receive any packets. so I just can't browse the internet

When I get a url it just hangs. after debugging with Wireshark and netstat I figured that when a request is sent a connection is established and then the same request is fired from 127.0.0.1:52345 to that URL

### Steps to reproduce

- snap install v2raya
- Apply the following configs
Transparent Proxy/System Proxy  -> On: Do not split traffic
Transparent Proxy/System Proxy Implementation  -> redirect

### Logs：

```bash
> curl http://82.118.230.121:8000 -v
*   Trying 82.118.230.121:8000...
* Connected to 82.118.230.121 (82.118.230.121) port 8000 (#0)
> GET / HTTP/1.1
> Host: 82.118.230.121:8000
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

```bash
# netstat entries
tcp        0      0 192.168.1.120:38810     82.118.230.121:8000     ESTABLISHED 15031/curl          
tcp6       0      0 127.0.0.1:52345         192.168.1.120:38810     ESTABLISHED 14460/v2ray 
```

**Comment by MarksonHon** [comment]
Please report snap unique problems in:
https://github.com/v2rayA/v2raya-snap
