### ISSUE TITLE
可以ping通，但是使用http访问不成功

### ISSUE THREAD

**Issue by bajiuqier** [v2rayA/v2rayA#1260]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.2.4.6
2. 你通过什么方式安装v2rayA
apt
3. 你所使用的操作系统
debian12

### 描述问题：

在连接我家的wifi的时候，可以ping通各个节点，但是http访问不成功，（已经确认节点是没有问题的。）而且也访问不了任何页面，国内的页面也访问不了。

令我惊奇的是，我连接手机wifi热点的时候，http是可以访问成功的，访问网页也没有任何问题。

**Comment by andyanghe** [comment]
解决了，跟换了谷歌DNS。

**Comment by andyanghe** [comment]
解决了，更换了谷歌的DNS.

**Comment by zll600** [comment]
@bajiuqier Could you help close this issue?
