### ISSUE TITLE
无法更新geodate.dat 提示拒绝连接

### ISSUE THREAD

**Issue by aw59** [v2rayA/v2rayA#1261]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
2.2.4.6-1
2. What approach of installation do you install V2rayA?
archlinux yay
3. What is your operating system?
archlinux

### Description

在webui更新gfwlist, 提示“Get "https://raw.githubusercontent.com/v2rayA/dist-v2ray-rules-dat/202401092209/geosite.dat": dial tcp 0.0.0.0:443: connect: connection refused”

手动下载移动到/usr/share/v2ray目录后重启v2raya服务，没有识别更新

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.
![image](https://github.com/v2rayA/v2rayA/assets/70953327/a0b602dc-4325-44d6-a1b2-8b0cad7b5217)

![image](https://github.com/v2rayA/v2rayA/assets/70953327/92ee74c6-d739-4a07-ad01-9e71ce0d2c06)

**Comment by MarksonHon** [comment]
@aw59 DNS污染而已 先开透明代理再更新
