### ISSUE TITLE
proxychains4里无法使用V2rayA

### ISSUE THREAD

**Issue by munmigenui** [v2rayA/v2rayA#1266]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
    V2rayA Version 2.2.4.6

2. 你通过什么方式安装v2rayA
apt 安装

3. 你所使用的操作系统
Kali 2023.4

### 描述问题：

我想要通过proxychains4工具来在终端里使用代理，我没有修改v2rayA里默认的Socks5和Http端口。我在proxychains4.conf配置文件里添加了:
```
socks5 127.0.0.1 20170
http 127.0.0.1 20171
```
当我想要`proxychains curl google.com`测试看时，命令行得到的结果是
```
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] Strict chain  ...  127.0.0.1:20170  ...  127.0.0.1:20171  ...  google.com:80 <--socket error or timeout!
curl: (7) Failed to connect to google.com port 80 after 0 ms: Couldn't connect to server
```
请问下我是在配置方面出了问题吗？或是哪里出了问题？

### v2rayA运行日志（Optional）：
`2024/01/18 19:50:03.542 [I] [io.go:432] tcp:127.0.0.1:52136 accepted tcp:127.0.0.1:20171 [proxy]`

**Comment by weierbao** [comment]
是的，我遇到和你一样的问题，但是无法被解决，甚至我把本地127的IP替换成了192本机IP

**Comment by munmigenui** [comment]
> 是的，我遇到和你一样的问题，但是无法被解决，甚至我把本地127的IP替换成了192本机IP

配置文件里只需要指定一个代理，删除掉`socks5 127.0.0.1 20170` 与`http 127.0.0.1 20171`其中的一个就可以了

**Comment by weierbao** [comment]
为什么不用socks5来使用他的代理，而是用http，我尝试socks5有时候能够成功使用代理，有时候会使用不了，这是怎么回事？

**Comment by weierbao** [comment]
用了你的方式确实没有问题了
