### ISSUE TITLE
如何修改订阅地址？

### ISSUE THREAD

**Issue by cliuyang** [v2rayA/v2rayA#127]
emm，我觉得应该是有这个功能的，但是找了半天没找到。

目前好像只支持对订阅的别名进行修改，不能修改订阅的地址，也不能删除不再使用的订阅，使用起来会有一丢丢在意。

**Comment by mzz2017** [comment]
点击左边的多选符号，会有按钮

**Comment by cliuyang** [comment]
啊啊，我看到了，之前没看见实在是抱歉
