### ISSUE TITLE
我只是想让局域网内的一台centos7上github而已，真是太难了！！！请大佬指导~~~感谢~~

### ISSUE THREAD

**Issue by mugua-8210** [v2rayA/v2rayA#1270]
### 版本、安装方式、系统

1. v2rayA-1.5.5

2. docker-v2rayA

3. centos7

### 描述问题

我用docker安装的v2raya,运行正常，导入的定于，然后选择其中一个启动，没有报错，也能正常运行。
我的问题是，我这台centos是在局域网内的服务器，可以访问国内网站，我安装这个v2raya，是为了让这个centos访问github。
如果，我设置右上角的设置，我就无法启动，什么也不改的话，可以启动！

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```
 或者粘贴来自 Web 页面的日志

```shell
# 此处贴入运行日志

[root@bogon ~]# journalctl -u v2raya | tail -n 50
-- No entries --


```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

无图

**Comment by GXJ6** [comment]
插眼，我是可以运行，但是没法访问github

**Comment by mugua-8210** [comment]
> 插眼，我是可以运行，但是没法访问github

我显示也是可以运行，但是依然无法访问，不知道哪错了~~~

**Comment by mugua-8210** [comment]
我通过v2rayN,实现了~~~
