### ISSUE TITLE
V2tayA无法完成卸载

### ISSUE THREAD

**Issue by CLT2011** [v2rayA/v2rayA#1285]
### 版本、安装方式、系统

1.2.2.46

2.系统内置

3. Ubuntu 20.04.6 NTSC HISTB240120

### 描述问题：

无法使用APT卸载

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

# 此处贴入运行日志

```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。
<!-- 如果条件允许请附图 -->

![Uploading Screenshot_20240201_085108_com.microsoft.emmx.jpg…]()

**Comment by CLT2011** [comment]
> ### 版本、安装方式、系统
> 1.2.2.46
> 
> 2.系统内置
> 
> 3. Ubuntu 20.04.6 HISTB240120
> 
> ### 描述问题：
> 无法使用APT卸载
> 
> ### v2rayA运行日志（Optional）：
> ```shell
> # daemon mode
> journalctl -u v2raya | tail -n 50
> sudo tail -n 50 /var/log/v2raya/v2raya.log
> 
> # docker mode
> docker logs v2raya
> ```
> 
> 或者粘贴来自 Web 管理页面的日志
> 
> # 此处贴入运行日志
> ```
> 
> ### v2rayA设置以及相关截图
> 贴入v2rayA设置，以及问题相关的截图。
> 
> 
> ![Uploading Screenshot_20240201_085108_com.microsoft.emmx.jpg…]()
> ```

**Comment by CLT2011** [comment]
系统版本为:Ubuntu 20.04.6 HISTB240120

**Comment by MarksonHon** [comment]
无任何有效信息，issue关闭
