### ISSUE TITLE
docker 启动方式的脚本给错了 

### ISSUE THREAD

**Issue by codingChang** [v2rayA/v2rayA#1289]
### Version, approach of installation, operating system

应该这样
文档中写的：/usr/local/bin/v2ray
改为： /usr/bin/v2ray \

 docker run -d \
  --restart=always \
  --privileged \
  --network=host \
  --name v2raya \
  -e V2RAYA_LOG_FILE=/tmp/v2raya.log \
  -e V2RAYA_V2RAY_BIN=/usr/bin/v2ray \
  -e V2RAYA_NFTABLES_SUPPORT=off \
  -e IPTABLES_MODE=legacy \
  -v /lib/modules:/lib/modules:ro \
  -v /etc/resolv.conf:/etc/resolv.conf \
  -v /etc/v2raya:/etc/v2raya \
  mzz2017/v2raya

**Comment by MarksonHon** [comment]
@codingChang 你要不要考虑重新组织下语言？
https://github.com/v2rayA/v2rayA/issues/1289
