### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by zz5678** [v2rayA/v2rayA#130]
1，可以自行换 core，比如最近很热闹的 xray，其实 qv2ray 就好用在可以自己手动选择 v2ray或者xray 的core，很灵活
2，在设置里加上 per-page 可自定制，有几个超过100节点的，分页实在是太麻烦了
3，每个订阅前加上序号，目前只是用服务器名字做 tab name，有时候实在是。。。。太尴尬，比如十几个都放在github的订阅，显示的都是 RAW.GITHUBUSERCONTENT.COM 看的头昏
4，或者把订阅做到侧边栏 frame 位置，避免点错不同订阅站点，或者找不到对应订阅，整个软件的界面也会更工整，目前的顶部 tab 分页模式 UI 操作有点太可怕
5，更新预警确认，点了订阅更新之后，会弹对话框提示，比如订阅链接内更新删除了50个节点，是否要确定更新到目前的订阅数据库？一旦操作失误，或者原来有些好用的，正在用的节点被误操作删除了，想要找回刚刚的数据就麻烦了

另外 wiki 里提示用户，把浏览器里的 allow Insecure content 点允许，否则，自建的服务器在 https:// 下打不开 demo 页面

**Comment by mzz2017** [comment]
The first problem has been solved in master branch code.
The third problem could be solved by rename the subscription manually.
The unnumbered problem is not what v2rayA should consider.
Thanks for your issue.
