### ISSUE TITLE
openwrt 软件包依赖配置

### ISSUE THREAD

**Issue by reserveword** [v2rayA/v2rayA#1303]
希望v2rayA在openwrt上的软件包能添加两个依赖项：`iptbles-mod-filter`和`iptbles-mod-nat-extra`，没有这两个软件包会导致v2rayA无法正常开始服务。

特别是`iptbles-mod-filter`这个依赖项，不查找资料很难发现这个依赖项提供了`iptables -m string`所需的依赖。

**Comment by MarksonHon** [comment]
https://github.com/v2rayA/v2raya-openwrt
