### ISSUE TITLE
VOIP Calls not working Like Whatsapp, Viber, Botim.

### ISSUE THREAD

**Issue by devalt90** [v2rayA/v2rayA#1305]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?

**v2raya armhf V 2.0.1 since there's no longer support to armhf 32bit**

3. What approach of installation do you install V2rayA?

**same as in Introduction site**

4. What is your operating system?

**Raspberry Pi OS**

### Description

**VOIP Calls not working Like Whatsapp, Viber, Botim.**

**Using V2ray Vmess and server was tested with v2ray android app and worked perfectly with voip calls.**

### Steps to reproduce

**VOIP Calls not working Like Whatsapp, Viber, Botim.**

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
  
 # docker mode
 docker logs v2raya
 ```

 You can also paste the log that comes from web administration page

```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by esaaprillia** [comment]
set tproxy
