### ISSUE TITLE
deb方式安装怎么卸载

### ISSUE THREAD

**Issue by lwgpshit** [v2rayA/v2rayA#131]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?

2. What approach of installation do you install V2rayA?

3. What is your operating system?
SMP Debian 4.19.160-2  x86_64 GNU/Linux

### Description
apt-get remove后访问127.0.0.1:2017仍然有界面???

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# Paste running logs here



```

**Comment by mzz2017** [comment]
浏览器缓存问题。
