### ISSUE TITLE
v2raya局域网代理请求增加设置用户名和密码设置

### ISSUE THREAD

**Issue by chenxudong2020** [v2rayA/v2rayA#1315]
### 您想提出的功能特性是否和现有问题相关？

在nas上，局域网代理了，映射到了外网 不安全，请求增加代理用户名和密码设置 谢谢

### 功能特性内容

![image](https://github.com/v2rayA/v2rayA/assets/61214170/80d328cc-0938-4988-918f-335bbc3c5a46)

**Comment by MarksonHon** [comment]
https://v2raya.org/docs/manual/routinga/#%E7%A4%BA%E4%BE%8B
