### ISSUE TITLE
建议将v2ray一并打包进程序

### ISSUE THREAD

**Issue by woodlyer** [v2rayA/v2rayA#1324]
### Is the feature related with existing problem?

文档中没有提到需要单独下载 v2ray 或 xray，但v2rayA运行需要这个。
没有就运行不了。
见：  https://github.com/v2rayA/v2rayA/issues/870#issuecomment-1817549897
还不如直接就打包v2ray，就不需要用户再自己下载v2ray。

要么是我的安装方法不合适，但我想有其他人也遇到同样的问题。
基本上就应该是需要用户下载v2ray.
但这个文档里面好像没有提到。
### Content of the feature

1.要么在文档里面写清楚要下载v2ray
2.要么直接把v2ray或xray打包进程序，免去用户下载

**Comment by cubercsl** [comment]
文档中已经写明
https://v2raya.org/docs/prologue/installation/debian/

**Comment by MarksonHon** [comment]
“好像没提到”，建议去看眼科医生
