### ISSUE TITLE
Add SNI Settings

### ISSUE THREAD

**Issue by ragasubekti** [v2rayA/v2rayA#133]
### Content of the feature

Add SNI Setting so we can spoof the source of the traffic

**Comment by mzz2017** [comment]
Sorry, I can not get your spark.

Could you please describe more details?

**Comment by ragasubekti** [comment]
Ah okay, so it's simply to spoof Header, in vmess I can set something like

``` 
"tlsSettings": {
    "allowInsecure": true,
    "serverName": "www.baidu.com"
},
```

I don't know if this possible, but in qv2ray and v2rayN already has this feature, 

![image](https://user-images.githubusercontent.com/20393246/103899022-5b770300-5128-11eb-8cff-0584b3884aff.png)

**Comment by mzz2017** [comment]
Hello, when you choose `TLS=tls`, the `host` field is exactly what you need, maybe.

Can it resolve your question?

**Comment by mzz2017** [comment]
Assume it is solved.
