### ISSUE TITLE
在hyper-v虚拟机中，访问京东网站时，CPU会突然占用100%。

### ISSUE THREAD

**Issue by iesv** [v2rayA/v2rayA#1332]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
2.2.5.1
2. What approach of installation do you install V2rayA?
deb
3. What is your operating system?
debian12

### Description

在hyper-v虚拟机中，访问京东网站时，CPU会突然占用100%。

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

![image](https://github.com/v2rayA/v2rayA/assets/16969250/64eaa127-ca0d-428c-bed4-4da4cbfeea77)
![image](https://github.com/v2rayA/v2rayA/assets/16969250/69dac6c0-3177-4648-9ef0-333241ee5ce3)

**Comment by Gaojianli** [comment]
占用CPU的是V2ray，也许你应该直接反馈给[v2ray-core](https://github.com/v2fly/v2ray-core/issues)
