### ISSUE TITLE
http interface 'api/version' return cannot find v2ray executable binary

### ISSUE THREAD

**Issue by jacknate** [v2rayA/v2rayA#134]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
latest
2. What approach of installation do you install V2rayA?
docker,  build from src code
3. What is your operating system?
mac 

### Description

in method "where.go#getV2rayBinPath()"
if call getV2rayServiceFilePath() return error, then program will return err ,but as expected, it should continue to find from env
 
![image](https://user-images.githubusercontent.com/9838652/103890036-5adb6e00-5122-11eb-8381-1baa51af2c4e.png)

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# Paste running logs here
![image](https://user-images.githubusercontent.com/9838652/103890408-fbca2900-5122-11eb-9234-8c8725c78396.png)



```

**Comment by mzz2017** [comment]
Thanks for your work, I'll fix it in the latest code.

**Comment by mzz2017** [comment]
> Thanks for your work!
> I'll fix it in the latest code.

Sorry, because I found that the code has been fixed.

Can you try the code in the branch `master`? Or just waiting for the new release recently.

**Comment by jacknate** [comment]
> > Thanks for your work!
> > I'll fix it in the latest code.
> 
> Sorry, because I found that the code has been fixed.
> 
> Can you try the code in the branch `master`? Or just waiting for the new release recently.

https://github.com/v2rayA/v2rayA/blob/master/service/core/v2ray/where/where.go#L103
In my view, code has not been fixed

btw, i can not build source code in mac，the error is as follows， if it is caused by my environment, please ignore it

```
# github.com/v2rayA/v2rayA/extra/proxy
extra/proxy/direct.go:83:63: undefined: syscall.SO_MARK
# github.com/v2rayA/v2rayA/core/dnsPoison
core/dnsPoison/dialer.go:47:63: undefined: syscall.SO_MARK
core/dnsPoison/dialer.go:52:46: undefined: syscall.SOL_IP
core/dnsPoison/dialer.go:52:62: undefined: syscall.IP_TRANSPARENT
core/dnsPoison/dnsPoison.go:47:12: undefined: pcapgo.NewEthernetHandle
core/dnsPoison/handle.go:22:2: undefined: pcapgo.EthernetHandle
core/dnsPoison/handle.go:27:54: undefined: pcapgo.EthernetHandle
```

because i want to remove the authentication (auth had already been done in nginx), so i would change the source code and rebuild docker image

**Comment by mzz2017** [comment]
Sorry, my fault. I'll fix it and re-release one.
