### ISSUE TITLE
如何让日志显示域名呀

### ISSUE THREAD

**Issue by cocdkl** [v2rayA/v2rayA#1340]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.2.4.6
2. 你通过什么方式安装v2rayA
手动安装
3. 你所使用的操作系统
openwrt

### 描述问题：

如何让日志显示域名呀

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by cubercsl** [comment]
#565

**Comment by cocdkl** [comment]
我看到那个提问了，问题是我开启系统代理告知不支持，有具体的处理方式吗

**Comment by cocdkl** [comment]
> #565
我看到那个提问了，问题是我开启系统代理告知不支持，有具体的处理方式吗
