### ISSUE TITLE
geoip.dat not found in kali linux 6.6.9

### ISSUE THREAD

**Issue by 2077DevWave** [v2rayA/v2rayA#1342]
### Version, approach of installation, operating system

1. What version of v2rayA are you using? snap V2raya version

2. What approach of installation do you install V2rayA? [installer_debian_x64_2.2.5.1.deb](https://github.com/v2rayA/v2rayA/releases/download/v2.2.5.1/installer_debian_x64_2.2.5.1.deb)

3. What is your operating system? Kali GNU/Linux Rolling  , kernel Linux 6.6.9-amd64 , Gnome 45.3

### Description
When I try to install the program using the .deb file (with apt or dpkg). It does not install correctly and gives an error geoip.dat file not found or not installed correctly. But when I install it with Snap, it works properly and there is no problem. I think there is a problem with .deb packages and it is not installed correctly in Kali Linux version 6.6.9.

### Logs：

 ```bash
 # with apt
sudo apt install ./installer_debian_x64_2.2.5.1.deb
 
 # with dpkg
 sudo dpkg -i ./installer_debian_x64_2.2.5.1.deb
 ```

**Comment by MarksonHon** [comment]
go to v2raya.org to read docs
