### ISSUE TITLE
联想个人云X1

### ISSUE THREAD

**Issue by strong-hub** [v2rayA/v2rayA#1345]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
mzz2017/v2raya:latest

2. 你通过什么方式安装v2rayA
docker

3. 你所使用的操作系统
linux 联想定制系统

### 描述问题

无法启动

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```
 或者粘贴来自 Web 页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![微信截图_20240319002025](https://github.com/v2rayA/v2rayA/assets/9864787/4503ede6-cb0e-41d6-9cd9-edce58276d91)

**Comment by iopq** [comment]
You must run it as root to be able to configure the ip tables
