### ISSUE TITLE
socks5和http代理默认监听全部网卡

### ISSUE THREAD

**Issue by HSwift** [v2rayA/v2rayA#135]
### 您想提出的功能特性是否和现有问题相关？

发现v2rayA配置的v2ray-core默认监听全部网卡[::]，这导致可以接收来自局域网的链接，可能存在一定的安全问题

### 功能特性内容

可否自行设置要监听的网卡地址，比如127.0.0.1

**Comment by mzz2017** [comment]
I think maybe the firewall is the better choice

**Comment by HSwift** [comment]
Thanks for your reply. I solved it by adding routingA rules and closing the default ports.
