### ISSUE TITLE
在nas（威联通）中用Docker 安装了v2fly-core,但是v2rayA早不到

### ISSUE THREAD

**Issue by ygfq** [v2rayA/v2rayA#136]
始终提示v2ray-core 尚未运行

**Comment by mzz2017** [comment]
什么操作引起的提示？

**Comment by ygfq** [comment]
> 什么操作引起的提示？

比较尴尬的是，我确实不知道是什么引起的。我甚至怀疑是我的操作错误。
由于使用的是威联通的nas，虽然在进程中能够看见v2ray，但是不支持systemctl status v2ray和service v2ray status两个命令。
在使用 https://hub.docker.com/r/v2fly/v2fly-core中推荐的命令docker pull v2fly/v2fly-core   拉取后，在威联通的containerstation中创建了v2ray-core.随后创建了v2raya.  进入页面就提示 v2ray-core 尚未运行

**Comment by mzz2017** [comment]
尚未运行是正常的，不需要管这个提示。v2raya不需要v2fly镜像，docker镜像的参数请按照v2raya的wiki

**Comment by ygfq** [comment]
安装没有问题了但是运行自接报错2021/01/25 13:48:50 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: github.com/v2rayA/v2rayA/core/v2ray: not sup
port transparent proxy:  > github.com/v2rayA/v2rayA/common/cmds: iptables-legacy -t nat -A V2RAY -p tcp -m multiport --sports 1:102
3,2017,5080,6363,20170:20172,62449 -j RETURN iptables v1.8.3 (legacy): Couldn't load match `multiport':No such file or directory   
                                                                                                                                   
Try `iptables -h' or 'iptables --help' for more information.                                                                       
 > exit status 2

**Comment by ygfq** [comment]
就是在想要在威联通自带的浏览器里面实现科学上网。这个真头痛

**Comment by mzz2017** [comment]
这是威联通的iptables组件不全，建议使用switchyomega或者尝试其他透明代理方案。

**Comment by ygfq** [comment]
另外，如果关闭全局透明代理，v2ray监听的是ipv6. 如何改为监听ip4的地址啊

**Comment by ygfq** [comment]
不是很明白大佬的意思。现在的情况是连接不了 节点啊。

**Comment by mzz2017** [comment]
会同时监听ipv4和ipv6

**Comment by ygfq** [comment]
> 会同时监听ipv4和ipv6

这个真的没有，查看 配置里面，是lison“：”：：“，查看监听端口也是 ipv6，没有监听ipv4

**Comment by mzz2017** [comment]
可以通过环境变量`V2RAYA_ADDRESS`修改监听地址

**Comment by ygfq** [comment]
> 可以通过环境变量`V2RAYA_ADDRESS`修改监听地址，其他环境变量见[wiki](https://github.com/v2rayA/v2rayA/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)。
> 另外，端口的地址在设置中修改。
不好意思，是我描述错误，不是说的   监听地址 (默认 ":::2017")这个，
而是 代理端口。代理端口只监听了ipv6

**Comment by mzz2017** [comment]
> 另外，端口的地址在设置中修改。

**Comment by ygfq** [comment]
感谢大佬指点，由于威联通nas自身限制，最终采用 qnapclub中的v2ray。自编config.json.
