### ISSUE TITLE
无法解析一些订阅节点

### ISSUE THREAD

**Issue by LittleControl** [v2rayA/v2rayA#138]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.2.1-3
2. 你通过什么方式安装v2rayA
yay(pacman)
3. 你所使用的操作系统
archlinux 5.10.11-arch1-1

### 描述问题：

一些订阅无法获取到节点,看日志说是不支持的格式,但是我手动编辑解码后是vmess,应该是支持的

### v2rayA运行日志（Optional）：

Jan 28 15:30:02 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 28 15:30:02 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 28 15:30:02 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 28 15:30:02 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 28 15:30:02 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 28 15:30:02 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 28 15:30:02 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 28 15:30:02 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 28 15:30:02 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 28 15:30:03 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
-- Boot 9a26623d485a48efa3633e4dc7e2f8fc --
Jan 29 09:04:24 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:04:24 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:04:24 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:04:24 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:04:24 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:04:24 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:04:24 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:04:24 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:04:25 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:04:25 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:04:25 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:04:25 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:04:26 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
-- Boot 4e450f04f3204481a9e724f7a40f4fb3 --
Jan 29 09:23:43 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:23:43 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:23:43 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:23:43 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:23:43 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:23:43 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:23:43 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:23:43 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:23:44 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:23:44 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:23:44 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:23:44 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:23:45 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:30:58 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:30:59 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:30:59 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:30:59 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:30:59 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:30:59 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:39:42 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:39:42 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:39:42 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:39:42 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:39:42 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:39:42 littlecontrol systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     <div id="cf-bubbles"> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <div id="cf-bubbles">
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:       <div class="bubbles"></div> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <div class="bubbles"></div>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:       <div class="bubbles"></div> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <div class="bubbles"></div>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:       <div class="bubbles"></div> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <div class="bubbles"></div>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     </div> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: </div>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     <h1><span data-translate="checking_browser">Checking your browser before accessing</span> mojie.me.</h1> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <h1><span data-translate="checking_browser">Checking your browser before accessing</span> mojie.me.</h1>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none"> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:       <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     </div> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: </div>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:   </div> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: </div>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:    <a href="https://madbbs.org/feminine.php?issue=0"></a> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <a href="https://madbbs.org/feminine.php?issue=0"></a>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:   <form class="challenge-form" id="challenge-form" action="/api/v1/client/subscribe?token=535e8149b60b35797d8e1c9a136e1f2c&amp;__cf_chl_jschl_tk__=3233db2d709c7808f62806b89a2d9f49d913ebd9-1611884387-0-Ab1bhC-5kIHw35NdgQReaOyU9PXV3agaI3JKhH85F6OelBGxAk-rl0JxVSOZEZYJlCB39H6oOVPZ40jwsfUBEDjUQ66DPUj_G9a0ta8XIfwSNNgN80KCU-KMByLldwUDrYID0vYYOIlX3krXSb7M99MTTNTdG-fthhbNRuSYjudzf_1q-PPGK9Q_nOSCmaMN-Vz5NeqPYz52QR-K_1Phf7mnB_W1rLQx9khiY5aRGdYHK7l3h0hkkQYMqlSrMfEHdoJi5wWQxEqCe0rAISYo8f77H_cMCWdhrraJVD0U3Yb3UasZrk3eKwhYjx2U_gCXtrcuPNyiAfz9WtwPCIRygOQNL7_T8JiwMpN6Bc4JhFNLw3KeVnD9teSs57tJIJWcx48vgQFCXgLqRCcsjVVxhUA" method="POST" enctype="application/x-www-form-urlencoded"> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <form class="challenge-form" id="challenge-form" action="/api/v1/client/subscribe?token=535e8149b60b35797d8e1c9a136e1f2c&amp;__cf_chl_jschl_tk__=3233db2d709c7808f62806b89a2d9f49d913ebd9-1611884387-0-Ab1bhC-5kIHw35NdgQReaOyU9PXV3agaI3JKhH85F6OelBGxAk-rl0JxVSOZEZYJlCB39H6oOVPZ40jwsfUBEDjUQ66DPUj_G9a0ta8XIfwSNNgN80KCU-KMByLldwUDrYID0vYYOIlX3krXSb7M99MTTNTdG-fthhbNRuSYjudzf_1q-PPGK9Q_nOSCmaMN-Vz5NeqPYz52QR-K_1Phf7mnB_W1rLQx9khiY5aRGdYHK7l3h0hkkQYMqlSrMfEHdoJi5wWQxEqCe0rAISYo8f77H_cMCWdhrraJVD0U3Yb3UasZrk3eKwhYjx2U_gCXtrcuPNyiAfz9WtwPCIRygOQNL7_T8JiwMpN6Bc4JhFNLw3KeVnD9teSs57tJIJWcx48vgQFCXgLqRCcsjVVxhUA" method="POST" enctype="application/x-www-form-urlencoded">
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     <input type="hidden" name="r" value="0ac87aae45857869070305dc8de74d1bd349d194-1611884387-0-Ac1dV+gKkaVMMykNRxbZYmkUTLvB0JZvGgQDw1AFoA+WSfqkAiiLXu2AhhkbFb8Vbkt1c5SRKmKCKXuOfabJXGe3ZIn6/xe98xZk0kQcPNwEoLeoOByPTeTIImuTgJ73SOhewQl10Zq+z4BPgPdf0pnbskGR+Gqkah8FpnZzWjDWGvlzRB5kG/3MCjWGlQFJkiw+eed7Ez7sGtKTwxu/3ctU/TW56WQxZUqCDD3Tj449nLbtI8aORb8vB/l70lB6usXyUi3jHLU8pS2nLWtojcUa6uIkXiS4DYkXVAfH6DhGNgDo8OkmLTw3Xfh4ZHQn2wJvpwaPs1owlj/M87tWHzImsltAnXMY3bkfr1fSW+pxkuv7OJ0feP5svUn1osplkmKqTfhRZ5lg5h62HWHqwFvKPtAHhtBtCpAAFPpNmn4jfGJlBnMQZUQJ1kUkSv04METAZtDAOD/3ifLYURqREt3Br2boCGI/o21JcEeD7wqWL2i1BKbFniC473yVkig5dacUNJt9LDAkrMy+yCKjf+Syb459CO5s8NUazeLgLVU3FPvQLOaaa4HppWA4jv5CFYno/RvmrBANLhv1KaFveRyVdaQfqz5uBBnXfcc3WMv5Ru40ZqXTkDYyLsjiUp2V7gLz7ioboNwc6MYlYB29T87HS3cn8wl1aA4S1Fv6AgP91gGRkPPwc1yIpRnIqnqmWXdjO70m+5jpIO3GA6R1vdSj+3unml4QI5YmP2YBojXb0Otih+tNoVmKJiJqsTkeu6sXB4WlGDxVdUa88xWqOHQz81r7ZcownbIMaBj69v8qXoy6+4JunIvQXwQkmR2cQxCGcFsE1lSkm0NPrh7FonvGknbtaYivLEzEawYrXGjU0ALJnc1o4xLUiYzukHBGjINNJxqzX6GxpEo5rlnPPSAAnR2Bvwph6nW/dBcfRtHnFRiL0YrCcR6/ND1Rgqkn6nStMGoSUSEr93QEQm2uy9RK+wALoQ9yfYHvBXNcdJ9zq0wJPGo7AxRkAZEmhJhib0bWhyUObGQx1TSzXgsqcHzWSfdtCV6btTTZ7NQHa08JIzBDRiriXc7Bo/XHeLpqEHLTg86Qp+aVMYbN2A90dgYuedY2g8i6v9DVFvuhfj+1+LsPfPsg64oO/QNkkGWkYQeMmEi1T5+JxmDlMJq7TQC/3gTafzOe273B4wwmDofohrQc2mstQ2vmBGuukefg3/a7rpYHm6UWibv6tFfVmhIDViZsOIMeAwJ2O3hG9vA/JNWmDJkHEf2MYMtLGc3GFaLqOKKy9gdCiq3ME0fQm8j1id88W2b1eEi9KAEWCgtxZwyvrzmv/AiX7kNCg2/5B21dLdmzNSI+dRBIlaWRkNaC/TOA5qgDmZOaw2HBYzNptl3DSxdfg+L34h71uuAwHxbK2T1uw3kdLS44Vp/zbZTbQql5cyZDAG1td4DI4cTHnsWxjU77Qiomrnd1KoFJjU6CZ9/PrMUptHxLNyvxIxsq080KpHeItsNRrZs/hgYg2YrQ+NGcKnIbmzYTZ2FKEpZLYFmz82CcaYFCnPEUE9H8/vbl88ZBOAZfeNGkHENDISfnI2fCj7ECbH7/lsHLxA=="/> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <input type="hidden" name="r" value="0ac87aae45857869070305dc8de74d1bd349d194-1611884387-0-Ac1dV+gKkaVMMykNRxbZYmkUTLvB0JZvGgQDw1AFoA+WSfqkAiiLXu2AhhkbFb8Vbkt1c5SRKmKCKXuOfabJXGe3ZIn6/xe98xZk0kQcPNwEoLeoOByPTeTIImuTgJ73SOhewQl10Zq+z4BPgPdf0pnbskGR+Gqkah8FpnZzWjDWGvlzRB5kG/3MCjWGlQFJkiw+eed7Ez7sGtKTwxu/3ctU/TW56WQxZUqCDD3Tj449nLbtI8aORb8vB/l70lB6usXyUi3jHLU8pS2nLWtojcUa6uIkXiS4DYkXVAfH6DhGNgDo8OkmLTw3Xfh4ZHQn2wJvpwaPs1owlj/M87tWHzImsltAnXMY3bkfr1fSW+pxkuv7OJ0feP5svUn1osplkmKqTfhRZ5lg5h62HWHqwFvKPtAHhtBtCpAAFPpNmn4jfGJlBnMQZUQJ1kUkSv04METAZtDAOD/3ifLYURqREt3Br2boCGI/o21JcEeD7wqWL2i1BKbFniC473yVkig5dacUNJt9LDAkrMy+yCKjf+Syb459CO5s8NUazeLgLVU3FPvQLOaaa4HppWA4jv5CFYno/RvmrBANLhv1KaFveRyVdaQfqz5uBBnXfcc3WMv5Ru40ZqXTkDYyLsjiUp2V7gLz7ioboNwc6MYlYB29T87HS3cn8wl1aA4S1Fv6AgP91gGRkPPwc1yIpRnIqnqmWXdjO70m+5jpIO3GA6R1vdSj+3unml4QI5YmP2YBojXb0Otih+tNoVmKJiJqsTkeu6sXB4WlGDxVdUa88xWqOHQz81r7ZcownbIMaBj69v8qXoy6+4JunIvQXwQkmR2cQxCGcFsE1lSkm0NPrh7FonvGknbtaYivLEzEawYrXGjU0ALJnc1o4xLUiYzukHBGjINNJxqzX6GxpEo5rlnPPSAAnR2Bvwph6nW/dBcfRtHnFRiL0YrCcR6/ND1Rgqkn6nStMGoSUSEr93QEQm2uy9RK+wALoQ9yfYHvBXNcdJ9zq0wJPGo7AxRkAZEmhJhib0bWhyUObGQx1TSzXgsqcHzWSfdtCV6btTTZ7NQHa08JIzBDRiriXc7Bo/XHeLpqEHLTg86Qp+aVMYbN2A90dgYuedY2g8i6v9DVFvuhfj+1+LsPfPsg64oO/QNkkGWkYQeMmEi1T5+JxmDlMJq7TQC/3gTafzOe273B4wwmDofohrQc2mstQ2vmBGuukefg3/a7rpYHm6UWibv6tFfVmhIDViZsOIMeAwJ2O3hG9vA/JNWmDJkHEf2MYMtLGc3GFaLqOKKy9gdCiq3ME0fQm8j1id88W2b1eEi9KAEWCgtxZwyvrzmv/AiX7kNCg2/5B21dLdmzNSI+dRBIlaWRkNaC/TOA5qgDmZOaw2HBYzNptl3DSxdfg+L34h71uuAwHxbK2T1uw3kdLS44Vp/zbZTbQql5cyZDAG1td4DI4cTHnsWxjU77Qiomrnd1KoFJjU6CZ9/PrMUptHxLNyvxIxsq080KpHeItsNRrZs/hgYg2YrQ+NGcKnIbmzYTZ2FKEpZLYFmz82CcaYFCnPEUE9H8/vbl88ZBOAZfeNGkHENDISfnI2fCj7ECbH7/lsHLxA=="/>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     <input type="hidden" value="fbe6ea59d403a073df9ad61d7bd09fc0" id="jschl-vc" name="jschl_vc"/> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <input type="hidden" value="fbe6ea59d403a073df9ad61d7bd09fc0" id="jschl-vc" name="jschl_vc"/>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:      github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: 
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     <input type="hidden" name="pass" value="1611884391.007-IGlgp4ddrd"/> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <input type="hidden" name="pass" value="1611884391.007-IGlgp4ddrd"/>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     <input type="hidden" id="jschl-answer" name="jschl_answer"/> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <input type="hidden" id="jschl-answer" name="jschl_answer"/>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:   </form> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: </form>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     <script type="text/javascript"> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <script type="text/javascript">
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:       //<![CDATA[ github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: //<![CDATA[
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:       (function(){ github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: (function(){
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           var a = document.getElementById('cf-content'); github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: var a = document.getElementById('cf-content');
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           a.style.display = 'block'; github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: a.style.display = 'block';
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent); github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           var trkjs = isIE ? new Image() : document.createElement('img'); github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: var trkjs = isIE ? new Image() : document.createElement('img');
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=618f3dcacccfd9c0"); github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=618f3dcacccfd9c0");
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           trkjs.id = "trk_jschal_js"; github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: trkjs.id = "trk_jschal_js";
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           trkjs.setAttribute("alt", ""); github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: trkjs.setAttribute("alt", "");
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           document.body.appendChild(trkjs); github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: document.body.appendChild(trkjs);
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           var cpo=document.createElement('script'); github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: var cpo=document.createElement('script');
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           cpo.type='text/javascript'; github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: cpo.type='text/javascript';
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           cpo.src="/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1"; github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: cpo.src="/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1";
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           document.getElementsByTagName('head')[0].appendChild(cpo); github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: document.getElementsByTagName('head')[0].appendChild(cpo);
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:         }()); github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: }());
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:       //]]> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: //]]>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     </script> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: </script>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:   <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=618f3dcacccfd9c0')"> </div> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=618f3dcacccfd9c0')"> </div>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90: </div> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: </div>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           <div class="attribution"> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <div class="attribution">
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:             DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:             <br /> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <br />
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:             <span class="ray_id">Ray ID: <code>618f3dcacccfd9c0</code></span> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: <span class="ray_id">Ray ID: <code>618f3dcacccfd9c0</code></span>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:           </div> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: </div>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:       </td> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: </td>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:     </tr> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: </tr>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90:   </table> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: </table>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90: </body> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: </body>
Jan 29 09:39:46 littlecontrol v2raya[360]: 2021/01/29 09:39:46 subscription.go:90: </html> github.com/v2rayA/v2rayA/service: not supported protocol. we only support ss, ssr and vmess now: </html>

**Comment by LittleControl** [comment]
之前记得还好的,这几天就这样了,不知道是机场的原因还是v2raya的原因

**Comment by mzz2017** [comment]
你的订阅链接开了cloudflare

**Comment by LittleControl** [comment]
> 你的订阅链接开了cloudflare五秒盾？

我也清楚,看日志是加了CF的DDos,但那个可能是用v2raya一直点击更新触发的,平时应该是没有的

**Comment by mzz2017** [comment]
看日志没有被解析的应该是个空节点。你有发现什么节点漏了吗

**Comment by LittleControl** [comment]
我明白了,因为我设置的是启动v2raya是自动更新订阅,然后解析订阅规则设置的是跟随全局透明代理  
然后这样子可能就会通过代理来获取订阅,从而出发CF的一些机制  
我现在用本地网络更新订阅就没有问题了  
原来如此,是我的错,太大意了  
主要是偷懒了,对于分流规则只简单设置了绕过中国大陆QAQ  
我的错,抱歉!

**Comment by LittleControl** [comment]
> 看日志没有被解析的应该是个空节点。你有发现什么节点漏了吗。
> 
> 其他的信息，看不到具体情况了。

感谢感谢,经过你提醒,我想明白了,感谢
