### ISSUE TITLE
apt安装添加源时NO_PUBKEY问题

### ISSUE THREAD

**Issue by Passacagliaaaaa** [v2rayA/v2rayA#1384]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.2.5
2. 你通过什么方式安装v2rayA
apt
3. 你所使用的操作系统
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

### 描述问题：

在添加源时,使用命令如下：
wget -qO - https://apt.v2raya.org/key/public-key.asc | sudo tee /etc/apt/keyrings/v2raya.asc
echo "deb [signed-by=/etc/apt/keyrings/v2raya.asc] https://apt.v2raya.org/ v2raya main" | sudo tee /etc/apt/sources.list.d/v2raya.list
sudo apt update
报错如下：
![image](https://github.com/v2rayA/v2rayA/assets/99469808/795922eb-2172-436c-839e-2ffbee4ed71e)

但是.asc和.list应该是成功写入了
![image](https://github.com/v2rayA/v2rayA/assets/99469808/935a0fff-60c4-4e15-8f77-0c60073738d5)

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by cubercsl** [comment]
Ubuntu 16.04 is end of life.
