### ISSUE TITLE
 Could not process rule: No such file or directory chain tp_pre、tp_out

### ISSUE THREAD

**Issue by mayl0415** [v2rayA/v2rayA#1387]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2ray version v5.15.3 installed successfully!
v2rayA version v2.2.5.1 installed successfully!

2. 你通过什么方式安装v2rayA
sudo sh -c "$(wget -qO- https://github.com/v2rayA/v2rayA-installer/raw/main/installer.sh)" @ --with-v2ray

4. 你所使用的操作系统
linux

### 描述问题
设置代理为大陆白名单后报错
failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: nft -f /usr/local/etc/v2raya/v2raya.nft /usr/local/etc/v2raya/v2raya.nft:62:11-16: Error: Could not process rule: No such file or directory chain tp_pre { ^^^^^^ /usr/local/etc/v2raya/v2raya.nft:67:11-16: Error: Could not process rule: No such file or directory chain tp_out { ^^^^^^ /usr/local/etc/v2raya/v2raya.nft:59:9-43: Error: Could not process rule: No such file or directory meta l4proto tcp redirect to :52345 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ /usr/local/etc/v2raya/v2raya.nft:62:11-16: Error: Could not process rule: No such file or directory chain tp_pre { ^^^^^^ /usr/local/etc/v2raya/v2raya.nft:67:11-16: Error: Could not process rule: No such file or directory chain tp_out { ^^^^^^ : exit status 1

### 复现问题的步骤
设置启用大陆白名单模式，然后运行节点，报错

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```
 或者粘贴来自 Web 页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
@mayl0415 提供系统的详细版本与内核版本、nftables版本

**Comment by mayl0415** [comment]
> @mayl0415 提供系统的详细版本与内核版本、nftables版本


[root@iZ2zehv8dwkdvggyua79p2Z myl]# uname -a
Linux iZ2zehv8dwkdvggyua79p2Z 4.19.0-91.82.141.6.uelc20.aarch64 #1 SMP Thu May 25 11:37:10 CST 2023 aarch64 aarch64 aarch64 GNU/Linux
[root@iZ2zehv8dwkdvggyua79p2Z myl]# nft --version
nftables v0.9.6 (Capital Idea #2)

**Comment by MarksonHon** [comment]
@mayl0415 https://wiki.nftables.org/wiki-nftables/index.php/List_of_updates_in_the_nft_command_line_tool

你的nft比较老 参照文档或v2rayA自带的帮助信息关掉nftables支持看下把

**Comment by mayl0415** [comment]
> @mayl0415 https://wiki.nftables.org/wiki-nftables/index.php/List_of_updates_in_the_nft_command_line_tool
> 
> 你的nft比较老 参照文档或v2rayA自带的帮助信息关掉nftables支持看下把

好的，感谢，我试试

**Comment by mayl0415** [comment]
> @mayl0415 https://wiki.nftables.org/wiki-nftables/index.php/List_of_updates_in_the_nft_command_line_tool
> 
> 你的nft比较老 参照文档或v2rayA自带的帮助信息关掉nftables支持看下把

你好，v2rayA没看到怎么关闭nftables哎，可以提供帮助吗

**Comment by mayl0415** [comment]
v2raya --help|grep nft
看到了，打扰了，我试试

**Comment by mayl0415** [comment]
> v2raya --help|grep nft 看到了，打扰了，我试试

[root@iZ2zehv8dwkdvggyua79p2Z myl]# v2raya -c --nftables-support off
不过好像不支持

**Comment by mayl0415** [comment]
> > > v2raya --help|grep nft 看到了，打扰了，我试试
> > 
> > 
> > [root@iZ2zehv8dwkdvggyua79p2Z myl]# v2raya -c --nftables-support off 不过好像不支持
> 
> [root@iZ2zehv8dwkdvggyua79p2Z myl]# v2raya --nftables-support "off" 2024/04/25 20:46:32.403 [A] [main.go:29] V2Ray binary is /usr/local/bin/v2ray 2024/04/25 20:46:32.403 [A] [main.go:29] V2Ray asset directory is /run/user/0/v2raya 2024/04/25 20:46:32.403 [A] [main.go:29] v2rayA working directory is /myl 2024/04/25 20:46:32.403 [A] [main.go:29] v2rayA configuration directory is /etc/v2raya 2024/04/25 20:46:32.403 [A] [main.go:29] Golang: go1.22.0 2024/04/25 20:46:32.403 [A] [main.go:29] OS: linux 2024/04/25 20:46:32.403 [A] [main.go:29] Arch: arm64 2024/04/25 20:46:32.403 [A] [main.go:29] Lite: false 2024/04/25 20:46:32.403 [A] [main.go:29] Version: 2.2.5.1 2024/04/25 20:46:32.403 [A] [main.go:29] Starting... 2024/04/25 20:46:32.403 [I] [main.go:30] the core was not running the last time v2rayA exited 2024/04/25 20:46:32.409 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017 2024/04/25 20:46:32.409 [A] [index.go:116] v2rayA is listening at http://172.18.24.48:2017 2024/04/25 20:46:32.409 [A] [index.go:116] v2rayA is listening at http://[::1]:2017 2024/04/25 20:46:32.409 [A] [index.go:116] v2rayA is listening at http://[fe80::216:3eff:fe12:8a01]:2017

我在 /etc/systemd/system/v2raya.service中添加了启动参数
ExecStart=/usr/local/bin/v2raya --nftables-support "off"

然后
systemctl daemon-reload
systemctl restart v2raya.service

这个问题解决了
