### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by HaoHaovo** [v2rayA/v2rayA#1391]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.2.5.1
2. 你通过什么方式安装v2rayA
yay
3. 你所使用的操作系统
archlinux

### 描述问题：

显示这个问题 无法启动
failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: iptables -w 2 -t nat -N TP_OUT iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?) Perhaps iptables or your kernel needs to be upgraded. : exit status 3

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

报错这个：
failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: iptables -w 2 -t nat -N TP_OUT iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?) Perhaps iptables or your kernel needs to be upgraded. : exit status 3

**Comment by cubercsl** [comment]
@HaoHaovo 重启
