### ISSUE TITLE
操作面板中仍有部分资源使用绝对路径

### ISSUE THREAD

**Issue by 763ce67512c8** [v2rayA/v2rayA#145]
### 您想提出的功能特性是否和现有问题相关？

#108

目前经过测试，仍有部分资源引用使用绝对路径，主要为脚本`chunk-vendors.2c5ef482.js`引用的资源：
如：

+ /img/flags/flag_zh.svg

+ /img/flags/flag_en.svg

+ /api/version

+ /api/touch

希望可以改为相对引用方便反向代理。

**Comment by mzz2017** [comment]
似乎一切资源正常，是否影响使用？

**Comment by 763ce67512c8** [comment]
如果不进行特殊配置，会导致只能加载UI界面无法操作，目前我是使用了307跳转将请求重定向解决该问题的，配置较为繁琐。

**Comment by mzz2017** [comment]
该 issue 由于 **should be solved** 而将被关闭。

**Comment by WeiqiChenCN** [comment]
```
 location /v2raya/ {
                proxy_pass http://localhost:2017/;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_redirect http://$host:2017/ /v2raya/;
        }
```
![Screenshot 2021-12-24 031052](https://user-images.githubusercontent.com/6562920/147282935-c0168ecd-9dfd-4bec-8ff0-c3189a05af3e.png)

好像没办法。
