### ISSUE TITLE
开启增强模式导致死机

### ISSUE THREAD

**Issue by 2014CAIS01** [v2rayA/v2rayA#146]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
v2raya 1.2.2-1

2. What approach of installation do you install V2rayA?
archlinuxcn/v2raya

3. What is your operating system?
Arch Linux x86_64

### Description

使用 5.11.1-zen1 和 5.11.1-arch1 内核时开启增强模式会导致电脑死机，如果设置了 `systemd` 服务在开机自动启动则会导致无法进入系统。只能通过断网的方式防止 v2raya 自动连接。

### Steps to reproduce

使用 5.11.1-zen1 和 5.11.1-arch1 内核时开启增强模式

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```

非连接性问题，死机前可能相关的最后几行日志。
重启后的日志中没有 v2raya 的
```shell
# Paste running logs here
Feb 25 23:48:13 archlinux audit[171037]: NETFILTER_CFG table=nat family=2 entries=29 op=xt_replace pid=171037 comm="iptables"
Feb 25 23:48:13 archlinux kernel: audit: type=1325 audit(1614268093.141:1145): table=nat family=2 entries=29 op=xt_replace pid=171037 comm="iptables"
Feb 25 23:48:13 archlinux kernel: audit: type=1300 audit(1614268093.141:1145): arch=c000003e syscall=54 success=yes exit=0 a0=4 a1=0 a2=40 a3=5570fac44080 items=0 ppid=372 pid=171037 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iptables" exe="/usr/bin/xtables-legacy-multi" key=(null)
```

**Comment by keter42** [comment]
应该是iptables或内核的bug？
![PXL_20210303_002149197](https://user-images.githubusercontent.com/69804308/110195551-ef3f2400-7e78-11eb-9f9b-3e85cb4d6bb0.jpg)
（不知道怎么记录kernel panic，只好拍照了）

**Comment by 2014CAIS01** [comment]
`linux 5.11.7-zen1-1` 开启增强模式已能正常运行，无法复现，看起来似乎修好了。
