### ISSUE TITLE
检测到v2ray-core可能未正确安装

### ISSUE THREAD

**Issue by mason478** [v2rayA/v2rayA#148]
### 版本、安装方式、系统

1. version：debian_amd64_v1.2.2.deb

2.通过.deb安装包安装（sudo dpkg -i）

3. OS: Ubuntu 19

### 描述问题：

v2rayA的web页面显示：“检测到v2ray-core可能未正确安装”

这是v2ray_core没有安装，所以我应该把v2ray_core安装到哪里？或者如何配置，能使v2rayA找到v2ray_core？
v2ray_core是直接运行的二进制包

```

**Comment by mzz2017** [comment]
https://github.com/v2rayA/v2rayA/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95#%E9%80%9A%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by mzz2017** [comment]
Assume it is solved.

**Comment by lifenglsf** [comment]
升级到最新版出现这个错误提示了,不升级可以正常运行.v2ray没有移动位置

**Comment by mzz2017** [comment]
> 升级到最新版出现这个错误提示了,不升级可以正常运行.v2ray没有移动位置

请将 v2ray v2ctl 放到 /usr/bin 目录中再试

**Comment by lifenglsf** [comment]
可以了,比较奇怪的是我环境变量指定了v2ray_bin的地址
```
echo $V2RAYA_V2RAY_BIN
/usr/bin/v2ray/v2ray
```

**Comment by mzz2017** [comment]
@lifenglsf 或许systemd没读到?

**Comment by lifenglsf** [comment]
这个不太清楚,先用着,有时间再研究吧

**Comment by PumpkinXD** [comment]
kubuntu
同样是报错v2ray-core可能未正确安装
然而我是用脚本安的。。。
甚至用snap版的又试验了一下
还是不行

**Comment by mzz2017** [comment]
@PumpkinXD 你装了v2ray-core了吗

**Comment by esdream** [comment]
> kubuntu 同样是报错v2ray-core可能未正确安装 然而我是用脚本安的。。。 甚至用snap版的又试验了一下 还是不行

我这边用的1.5.5版本，安装v2ray后，你需要开启v2ray服务，才能正常使用v2rayA：
```
systemctl start v2ray
```

**Comment by MarksonHon** [comment]
@esdream v2rayA 已经不依赖 v2ray 的 systemd 服务了
