### ISSUE TITLE
新功能

### ISSUE THREAD

**Issue by Lovekeying** [v2rayA/v2rayA#151]
### 功能特性内容

希望能够加入对网关透明代理的支持

**Comment by mzz2017** [comment]
描述清楚一点

**Comment by Lovekeying** [comment]
希望未来连接到这台作为有着v2raya的网关能够代理来自连接网关设备的流量

**Comment by MarksonHon** [comment]
v2rayA 早就可以用于网关透明代理了，原理详见：
<https://guide.v2fly.org/app/tproxy.html>
