### ISSUE TITLE
能否增加一个选项提供单一的透明代理端口而无需配置ipset规则，iptables规则由用户自定义

### ISSUE THREAD

**Issue by hehh2001** [v2rayA/v2rayA#152]
我的环境是自建了dnsmasq+chinadns-ng  已经做了域名分流策略，只需要在原有v2ray客户端配置的基础上，加上一个 dokodemo-door 入站协议即可，即不配置任何分流或路由规则。透明代理选项中能再加一项由用户自定义的iptables规则透明代理端口那样配置的灵活性更好。

**Comment by mzz2017** [comment]
@hehh2001 见--v2ray-confdir参数

**Comment by hehh2001** [comment]
@ mzz2017    感谢大佬，本人水平有限，能否多给点提示，我找不到任何v2raya的配置文件，你是说我可以把自定义v2ray的json配置文 件放在/etc/v2raya目录下吗？然后v2raya它会优先于我这个自定义的配置？

**Comment by mzz2017** [comment]
@hehh2001 你在启动v2raya的时候追加--v2ray-conf参数，详见v2raya --help

**Comment by hehh2001** [comment]
@ mzz2017 大佬 ，学生愚笨，试了一下，还是不行，追加--v2ray-confdir参数后，v2raya还是会加你载预制的透明代理规则，我自定义的入站方式和我的iptables不起作用，不明白问题出在哪？

**Comment by mzz2017** [comment]
@hehh2001 你不需要开v2raya的透明代理。然后自己定义一个dokodemo-door。你可以对比/etc/v2raya/config.json配置来确定是否达到自己的目的

**Comment by hehh2001** [comment]
@ mzz2017大佬,还有个问题，我是在内网一台机器上布署的，目前功能正常，分流体验非常好，内网有bt软件，怎样设置才能使bt流量绕过代理。

**Comment by mzz2017** [comment]
@hehh2001 做过努力了，bt流量目前无法精准识别

**Comment by hehh2001** [comment]
@ mzz2017大佬    感谢大佬做出如此优秀的软件，挂在旁路由上体验非常棒！

**Comment by mzz2017** [comment]
谢谢
