### ISSUE TITLE
apt remove v2raya 后，是否会还原至安装配置之前的状态？（例如是否会清除 iptables）

### ISSUE THREAD

**Issue by Warkeeper** [v2rayA/v2rayA#153]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
latest
2. 你通过什么方式安装v2rayA
apt install
3. 你所使用的操作系统
ubuntu 18

### 描述问题：
我在一台具有公网访问权限的机器 A 上安装了一些需要翻墙才能安装的软件环境，所以安装了 v2raya 并配了全局透明代理，然后这个机器打包成镜像放到一个没有互联网环境的机器 B 里跑。

由于 v2raya 不允许出现在机器 B 里，因此需要 apt remove 掉它。

请问这样移除 v2raya 后，iptables 之类的东西会还原吗？我还需要做什么操作吗？

**Comment by mzz2017** [comment]
@Warkeeper 一般而言绝大多数配置会恢复，不放心重启即可

**Comment by Warkeeper** [comment]
感谢回复，在 apt remove 后我发现 iptables 里 mangle 表被清空了，是否意味着这台机器已经关闭了透明代理？
（补充一下，由于内网的某些政策，无法通过 2017 端口访问 http 关闭透明代理）

**Comment by mzz2017** [comment]
@Warkeeper 是的 透明代理依赖于iptables规则

**Comment by mzz2017** [comment]
Assume it is solved.
