### ISSUE TITLE
按非host方式启动docker容器，无法访问网络

### ISSUE THREAD

**Issue by LainNetWork** [v2rayA/v2rayA#156]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
v2raya版本：1.2.1
2. What approach of installation do you install V2rayA?
Docker
3. What is your operating system?
Ubuntu Server 20.04 LTS 64bit

### Description

你好，我依照文档在使用如下方式启动v2raya后，docker容器中无法访问外网，在容器内执行ping命令亦无法解析到域名，导致无法更新订阅以及正常代理。
```
docker run -d \
	-p 2017:2017 \
	-p 20170-20172:20170-20172 \
	--restart=always \
	--name v2raya \
	-v /etc/resolv.conf:/etc/resolv.conf \
	-v /etc/v2raya:/etc/v2raya \
	mzz2017/v2raya
```
但按照docker安装文档的第一种方式，使用host模式是可以正常上网的。
其实我是想把v2raya通过我自建的docker bridge网络，开放给我容器里其他项目使用的，但是第二种方式现在不加上自己的网络配置也无法正常使用，不知道这种场景您有没有什么更好的方法？

![image](https://user-images.githubusercontent.com/20994069/113495125-b8b10380-9521-11eb-84b2-2e7f5314b5b9.png)

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya

 ```
![image](https://user-images.githubusercontent.com/20994069/113495146-eac26580-9521-11eb-966d-cafa36b649c1.png)

```shell
# Paste running logs here



```

**Comment by mzz2017** [comment]
```shell
$ docker run -d \
        -p 2017:2017 \
        -p 20170-20172:20170-20172 \
        --restart=always \
        --name v2raya \
        -v /etc/resolv.conf:/etc/resolv.conf \
        -v /etc/v2raya:/etc/v2raya \
        mzz2017/v2raya
6711c7a04f52fe86c15889a33d78d0a24e04c1b989b87d2c14bb2bba15cfb539
$ docker exec -it 6711 sh
/ # ping baidu.com
PING baidu.com (39.156.69.79): 56 data bytes
64 bytes from 39.156.69.79: seq=0 ttl=45 time=43.825 ms
64 bytes from 39.156.69.79: seq=1 ttl=45 time=43.531 ms
64 bytes from 39.156.69.79: seq=2 ttl=45 time=43.606 ms
^C
--- baidu.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 43.531/43.654/43.825 ms
/ # 

```
无法复现，版本是1.2.2，docker pull mzz2017/v2raya获取最新版本试试？

**Comment by mzz2017** [comment]
想到了一个可能存在的问题，尝试不挂载/etc/resolv.conf？

**Comment by LainNetWork** [comment]
> 想到了一个可能存在的问题，尝试不挂载/etc/resolv.conf
> 
> 问题原因：
> 不打开透明代理的情况下v2raya不会修改resolv.conf
> 由于resolv.conf可能由systemd-resolved管理，这种情况下挂载后的文件在容器中可能是无效的

感谢，去掉之后确实可以了

**Comment by liaozd** [comment]
我有类似的状况，但去掉挂载/etc/resolv.conf也不行

**Comment by 4Aiur** [comment]
> 我有类似的状况，但去掉挂载/etc/resolv.conf也不行

我也是host模式启动,一切正常代理,但是非host模式就不行,
后来我把设置里的"端口分享"勾上就行了, 
可能非host模式下容器IP和宿主机IP不一致,监听的127.0.0.1:20170就不生效了
