### ISSUE TITLE
希望增加封锁icmp流量的功能

### ISSUE THREAD

**Issue by Smith1970** [v2rayA/v2rayA#160]
### 您想提出的功能特性是否和现有问题相关？

v2raya 开启全局透明代理后部分网站仍然可以通过 Ping 的方式探测到访问者的真实 ip地址

![image](https://user-images.githubusercontent.com/17473921/114291312-ef34d400-9a75-11eb-95f6-ea4d9263697d.png)
访问<https://whatleaks.com/>的截图

---
v2raya 开启全局透明代理时分别执行 `ping whatleaks.com` 和 `ping www.google.com`

```
ping whatleaks.com
PING whatleaks.com (109.236.87.80) 56(84) 比特的数据。
64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=1 ttl=112 时间=269 毫秒
64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=2 ttl=112 时间=264 毫秒
64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=3 ttl=112 时间=265 毫秒
64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=4 ttl=112 时间=275 毫秒
^C
--- whatleaks.com ping 统计 ---
已发送 4 个包， 已接收 4 个包, 0% packet loss, time 3002ms
```

```
ping www.google.com
PING www.google.com (157.240.17.36) 56(84) 比特的数据。
^C
--- www.google.com ping 统计 ---
已发送 11 个包， 已接收 0 个包, 100% packet loss, time 10125ms
```

### 功能特性内容

希望 v2raya 增加一个在全局透明代理时封锁icmp流量的按钮

**Comment by Smith1970** [comment]
补充

v2raya 开启全局透明代理时分别执行 `ping whatleaks.com` 和 `ping www.google.com`
```
ping whatleaks.com
PING whatleaks.com (109.236.87.80) 56(84) 比特的数据。
64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=1 ttl=112 时间=269 毫秒
64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=2 ttl=112 时间=264 毫秒
64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=3 ttl=112 时间=265 毫秒
64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=4 ttl=112 时间=275 毫秒
^C
--- whatleaks.com ping 统计 ---
已发送 4 个包， 已接收 4 个包, 0% packet loss, time 3002ms
rtt min/avg/max/mdev = 263.680/268.157/275.011/4.453 ms
```

```
ping www.google.com
PING www.google.com (157.240.17.36) 56(84) 比特的数据。
^C
--- www.google.com ping 统计 ---
已发送 11 个包， 已接收 0 个包, 100% packet loss, time 10125ms
```

**Comment by zhullyb** [comment]
@Smith1970 造成这样结果的原因估计是因为你开了分流吧

**Comment by Smith1970** [comment]
![圖片](https://user-images.githubusercontent.com/17473921/114292591-06c48a80-9a7f-11eb-98b8-21602336858b.png)
@zhullyb 我的设置是这样的，应该是没开分流吧

**Comment by zhullyb** [comment]
@Smith1970 这取决于你RoutingA到底是怎么配置的

**Comment by Smith1970** [comment]
![圖片](https://user-images.githubusercontent.com/17473921/114292849-10e78880-9a81-11eb-9e0b-52ab11f015ba.png)

@zhullyb 我的RoutingA是空的

**Comment by zhullyb** [comment]
@Smith1970 RoutingA为空时会自动使用默认分流规则，即大陆白名单

**Comment by Smith1970** [comment]
![圖片](https://user-images.githubusercontent.com/17473921/114293094-d5e65480-9a82-11eb-8d0d-65c0fdfff364.png)

@zhullyb 但是规则端口分流模式下拉菜单里面并没有“关闭分流”选项，因此求教怎样才能关闭分流呢

**Comment by zhullyb** [comment]
> ### 您想提出的功能特性是否和现有问题相关？
> 
> v2raya 开启全局透明代理后部分网站仍然可以通过 Ping 的方式探测到访问者的真实 ip地址
> 
> ![image](https://user-images.githubusercontent.com/17473921/114291312-ef34d400-9a75-11eb-95f6-ea4d9263697d.png)
> 访问https://whatleaks.com/的截图
> 
> v2raya 开启全局透明代理时分别执行 `ping whatleaks.com` 和 `ping www.google.com`
> 
> ```
> ping whatleaks.com
> PING whatleaks.com (109.236.87.80) 56(84) 比特的数据。
> 64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=1 ttl=112 时间=269 毫秒
> 64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=2 ttl=112 时间=264 毫秒
> 64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=3 ttl=112 时间=265 毫秒
> 64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=4 ttl=112 时间=275 毫秒
> ^C
> --- whatleaks.com ping 统计 ---
> 已发送 4 个包， 已接收 4 个包, 0% packet loss, time 3002ms
> ```
> 
> ```
> ping www.google.com
> PING www.google.com (157.240.17.36) 56(84) 比特的数据。
> ^C
> --- www.google.com ping 统计 ---
> 已发送 11 个包， 已接收 0 个包, 100% packet loss, time 10125ms
> ```
> 
> ### 功能特性内容
> 
> 希望 v2raya 增加一个在全局透明代理时封锁icmp流量的按钮

如果对这个检测结果不满意，我觉得你应该使用浏览器的隐私模式

**Comment by zhullyb** [comment]
> ![圖片](https://user-images.githubusercontent.com/17473921/114293094-d5e65480-9a82-11eb-8d0d-65c0fdfff364.png)
> 
> @zhullyb 但是规则端口分流模式下拉菜单里面并没有“关闭分流”选项，因此求教怎样才能关闭分流呢

![图片](https://user-images.githubusercontent.com/43305366/114293147-51b5c080-9ac6-11eb-8813-13d778460456.png)

**Comment by zhullyb** [comment]
> ### 您想提出的功能特性是否和现有问题相关？
> 
> v2raya 开启全局透明代理后部分网站仍然可以通过 Ping 的方式探测到访问者的真实 ip地址
> 
> ![image](https://user-images.githubusercontent.com/17473921/114291312-ef34d400-9a75-11eb-95f6-ea4d9263697d.png)
> 访问https://whatleaks.com/的截图
> 
> v2raya 开启全局透明代理时分别执行 `ping whatleaks.com` 和 `ping www.google.com`
> 
> ```
> ping whatleaks.com
> PING whatleaks.com (109.236.87.80) 56(84) 比特的数据。
> 64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=1 ttl=112 时间=269 毫秒
> 64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=2 ttl=112 时间=264 毫秒
> 64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=3 ttl=112 时间=265 毫秒
> 64 比特，来自 mail.vimezz.nl (109.236.87.80): icmp_seq=4 ttl=112 时间=275 毫秒
> ^C
> --- whatleaks.com ping 统计 ---
> 已发送 4 个包， 已接收 4 个包, 0% packet loss, time 3002ms
> ```
> 
> ```
> ping www.google.com
> PING www.google.com (157.240.17.36) 56(84) 比特的数据。
> ^C
> --- www.google.com ping 统计 ---
> 已发送 11 个包， 已接收 0 个包, 100% packet loss, time 10125ms
> ```
> 
> ### 功能特性内容
> 
> 希望 v2raya 增加一个在全局透明代理时封锁icmp流量的按钮

我去访问了那个站点，他检测到你用代理应该是从你的DNS记录判断出来的

**Comment by Smith1970** [comment]
> > ![圖片](https://user-images.githubusercontent.com/17473921/114293094-d5e65480-9a82-11eb-8d0d-65c0fdfff364.png)
> > @zhullyb 但是规则端口分流模式下拉菜单里面并没有“关闭分流”选项，因此求教怎样才能关闭分流呢
> 
> ![图片](https://user-images.githubusercontent.com/43305366/114293147-51b5c080-9ac6-11eb-8813-13d778460456.png)

有关这个我的配置也是“代理所有流量”，但是icmp流量并没有被代理封锁，连接v2raya全局透明代理时可以ping通未被墙的网站

**Comment by mzz2017** [comment]
> @Smith1970 RoutingA为空时会自动使用默认分流规则，即大陆白名单

应该会全走代理

**Comment by zhullyb** [comment]
@mzz2017 我试了一下，RoutingA全空时会自动填上RoutingA的默认配置啊

**Comment by mzz2017** [comment]
你可以禁用你代理服务器的ping响应来规避这个问题

或者你可以查找如何在本地通过iotables drop掉ping的流量

v2raya不对此负责，因为它**可能**会影响PC的正常功能

**Comment by Smith1970** [comment]
感谢回复，我已经通过 iptables drop 解决了问题
