### ISSUE TITLE
订阅链接提示i/o timeout

### ISSUE THREAD

**Issue by SaboZhang** [v2rayA/v2rayA#161]
### 版本、安装方式、系统

1. 最新版本的v2rayA

2. Docker

3. 群晖NAS

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya_backend
 ```
```shell
# 此处贴入运行日志

github.com/v2rayA/v2rayA/service: failed to resolve subscription address > Get "https://XXX.XXX.COM//link/l4hGC5iDzplwDjov?sub=3": dial tcp 198.18.0.4:443: i/o timeout

```

**Comment by mzz2017** [comment]
@SaboZhang 你在哪里开的fakedns？

**Comment by SaboZhang** [comment]
NAS的DNS吗，如果是的话 我换个网试试

**Comment by SaboZhang** [comment]
> @SaboZhang 你在哪里开的fakedns？
> dns缓存污染了，重启或者等十分钟。

NAS的DNS吗，如果是的话 我换个网试试

**Comment by SaboZhang** [comment]
> @SaboZhang 你在哪里开的fakedns？
> dns缓存污染了，重启或者等十分钟。

看着像是时间不同步的问题context deadline exceeded (Client.Timeout exceeded while awaiting headers) docker您有在镜像中添加时区的参数吗？
