### ISSUE TITLE
透明代理增强模式使用异常

### ISSUE THREAD

**Issue by BlademasterQAQ** [v2rayA/v2rayA#162]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.2.2
2. 你通过什么方式安装v2rayA
.deb
3. 你所使用的操作系统
Ubuntu

### 描述问题

为了让docker容器使用透明代理，开启了增强模式。开启后无法通过ipv6连接服务器，无法ping通阿里DNS，输出结果如下：
```
# ping 2400:3200::1
connect: Cannot assign requested address
```
关闭增强模式后依然ping不通，输出结果如下：
```
# ping 2400:3200::1
connect: Network is unreachable
```
需要重启电脑网络才恢复正常。

### 复现问题的步骤

如上

**Comment by mzz2017** [comment]
@BlademasterQAQ 1.2.2的增强模式不支持ipv6，1.3.0马上发布

**Comment by mzz2017** [comment]
@BlademasterQAQ 不过无论如何，你需要特殊设置才可以使得docker使用ipv6

**Comment by BlademasterQAQ** [comment]
> @BlademasterQAQ 不过无论如何，你需要特殊设置才可以使得docker使用ipv6
> 
> 见
> 
> https://www.linode.com/community/questions/20842/how-do-i-enable-ipv6-support-for-docker-containers#answer-75012

谢谢大佬指点，暂时用[https://github.com/v2rayA/v2rayA/issues/129](https://github.com/v2rayA/v2rayA/issues/129)的方法解决了。

**Comment by BlademasterQAQ** [comment]
> @BlademasterQAQ 不过无论如何，你需要特殊设置才可以使得docker使用ipv6
> 
> 见
> 
> https://www.linode.com/community/questions/20842/how-do-i-enable-ipv6-support-for-docker-containers#answer-75012

在Windows上使用Clash For Windows的透明代理可以让Docker内的容器也透明代理，它好像是通过tun实现的。
我不太清楚Linux上的透明代理是如何实现的，不过根据我搜索到的信息，好像让Docker容器透明代理在宿主机是Linux的情况下是比较麻烦的（例如：https://kebingzao.com/2019/02/22/docker-container-proxy ）。

大佬你说的对，不进行配置的话容器内确实是没有ipv6地址的。

**Comment by mzz2017** [comment]
@BlademasterQAQ 1.3.0更新了，支持ipv6

**Comment by BlademasterQAQ** [comment]
> @BlademasterQAQ 1.3.0更新了，支持ipv6

谢谢大佬😘
