### ISSUE TITLE
开启全局透明代理报错

### ISSUE THREAD

**Issue by allabandon** [v2rayA/v2rayA#168]
### 版本、安装方式、系统

1. Version: 1.3.1

2. 通过docker方式安装v2rayA

3. cen8.3

### 描述问题：

设置全局透明代理报错

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode

 
 # docker mode

 ```
```shell
# 此处贴入运行日志



github.com/v2rayA/v2rayA/core/v2ray: github.com/v2rayA/v2rayA/core/v2ray: not support transparent proxy: > github.com/v2rayA/v2rayA/common/cmds: iptables-legacy -w 2 -t nat -N V2RAY iptables v1.8.3 (legacy): can't initialize iptables table `nat': Permission denied (you must be root) Perhaps iptables or your kernel needs to be upgraded. > exit status 3


```

**Comment by mzz2017** [comment]
@allabandon 你的docker run命令参数是？

**Comment by allabandon** [comment]
不太明白你说的docker run命令参数是啥。我已导入订阅节点，是通过2017面板切换全局透明代理，然后顶部橙色字体报如上错误
我是通过docker的方式安装的，命令：
docker run -d \
	--restart=always \
	--privileged \
	--network=host \
	--name v2raya \
	-v /etc/resolv.conf:/etc/resolv.conf \
	-v /etc/v2raya:/etc/v2raya \
	mzz2017/v2raya

**Comment by mzz2017** [comment]
已在dockerhub重打包1.3.1，可重新docker pull再试

如果仍有问题，可尝试直接在宿主机安装v2raya

**Comment by allabandon** [comment]
已删除镜像容器重新pull，依旧无法开启透明代理，VPS上docker专门用来安装v2raya，无其他容器，系统cen8.3，除了docker，其他方法不会

**Comment by allabandon** [comment]
同docker安装步骤在谷歌云上功能正常，怀疑是现VPS有限制。已放弃使用全局代理，改用http代理20171端口

**Comment by mzz2017** [comment]
你在宿主机yum install iptables一下试试

**Comment by allabandon** [comment]
该依赖已安装[root@instance-bnffba ~]# yum install iptables
Last metadata expiration check: 0:56:55 ago on Tue 27 Apr 2021 06:30:04 PM CST.
Package iptables-1.8.4-15.el8_3.3.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by allabandon** [comment]
![image](https://user-images.githubusercontent.com/46588071/116234491-41246c00-a78f-11eb-92cb-b51a170238fc.png)

**Comment by mzz2017** [comment]
可以加个 `-v /lib/modules:/lib/modules` 看

**Comment by allabandon** [comment]
感谢，已成功启用全局透明代理。
