### ISSUE TITLE
希望可以  启动时自动连接上次的节点

### ISSUE THREAD

**Issue by Stars-fireworks** [v2rayA/v2rayA#172]
### 您想提出的功能特性是否和现有问题相关？

安装在N1旁路由上的，偶尔有重启的话，还得手动连节点，有亿点点强迫症。

复现：
reboot重启没问题。。。  断电重启才会 不连接节点

### 功能特性内容

V2启动时，自动连接上次的节点。

**Comment by Stars-fireworks** [comment]
抱歉

重启了一下  好像又可以了   之前是断了一会儿电  重启后没反应   可能是个例

**Comment by mzz2017** [comment]
断电会使得部分硬盘数据丢失，可能你的配置丢失了，这不是v2rayA的问题

**Comment by x1iu** [comment]
我也是最近一周出现这个问题，断电启动有概率（估计30%）不能自动重连

**Comment by mzz2017** [comment]
具体表现是什么，无法自动连接时日志里有什么错误内容

**Comment by x1iu** [comment]
具体表现就是未连接任何节点，需要手动连接才行。下次遇到我截一下日志。

**Comment by Stars-fireworks** [comment]
> 具体表现是什么，无法自动连接时日志里有什么错误内容

![image](https://user-images.githubusercontent.com/44934504/116980577-f9569500-acf8-11eb-95cd-f88c187b7e52.png)

**Comment by x1iu** [comment]
![IMG_0044](https://user-images.githubusercontent.com/44594408/117086545-5eed6480-ad7f-11eb-941b-2dfe8490c119.jpeg)
这是没有重连的日志

**Comment by x1iu** [comment]
下图是自动重连的日志
![图片](https://user-images.githubusercontent.com/44594408/117519559-a1f54500-afd6-11eb-8900-52c622d6c3fc.png)
下图是未能自动重连的日志
![图片](https://user-images.githubusercontent.com/44594408/117519576-b5081500-afd6-11eb-8106-c687ab76eaac.png)

**Comment by mzz2017** [comment]
只有断电开机会出现这种情况吗？

无法从日志里获得更多信息。

**Comment by x1iu** [comment]
我手动重启了5次容器，都可以自动连接。我平常使用是晚上11点关机，第二天早上6点开机，这样就有30%的概率不能自动连接。v2raya启动的时候，系统时间还没成功同步，还是晚上11点，这影响吗？

**Comment by mzz2017** [comment]
该 issue 由于无法稳定复现而将被关闭。
