### ISSUE TITLE
为啥不把Centos的安装方法写上去呢

### ISSUE THREAD

**Issue by MkMarko** [v2rayA/v2rayA#173]
为啥不把Centos的安装方法写上去呢？既然支持YUM 为啥只写Ubuntu的安装方法，而不加入RPM安装的方式呢

**Comment by mzz2017** [comment]
@MkMarko 我这里没有centos，可以麻烦提供一下步骤吗，我会将它写入wiki

**Comment by imapproxy** [comment]
如果有opensuse tumbleweed的安装方法，也请提供一下，谢谢。
Releases里的：v2raya_linux_amd64_v1.3.2在opensuse tumble weed里面无法启动；installer_redhat_amd64_v1.3.2.rpm在opensuse tumbleweed上安装报错

**Comment by mzz2017** [comment]
已经写上了
