### ISSUE TITLE
无法链接

### ISSUE THREAD

**Issue by sisyphus1212** [v2rayA/v2rayA#177]
May 09 12:55:50 sysiphus systemd[1]: Started v2rayA Service.
May 09 12:55:51 sysiphus v2raya[26259]: V2RayLocationAsset is .
May 09 12:55:51 sysiphus v2raya[26259]: V2Ray binary is
May 09 12:55:51 sysiphus v2raya[26259]: v2rayA working directory is /
May 09 12:55:51 sysiphus v2raya[26259]: Version: 1.3.2
May 09 12:55:51 sysiphus v2raya[26259]: Starting...
May 09 12:55:51 sysiphus v2raya[26259]: v2rayA is listening at http://127.0.0.1:2017
May 09 12:55:51 sysiphus v2raya[26259]: v2rayA is listening at http://10.250.0.2:2017
May 09 12:55:51 sysiphus v2raya[26259]: v2rayA is listening at http://192.168.4.231:2017
May 09 12:55:51 sysiphus v2raya[26259]: v2rayA is listening at http://172.17.0.1:2017
May 09 12:55:51 sysiphus v2raya[26259]: v2rayA is listening at http://192.168.122.1:2017
May 09 14:49:41 sysiphus v2raya[26259]: 2021/05/09 14:49:41 [Warning] github.com/v2rayA/v2rayA/server/service: length of password should be between 6 and 32
May 09 14:49:50 sysiphus v2raya[26259]: 2021/05/09 14:49:50 nutsdbOperator.go:47: github.com/v2rayA/v2rayA/db: [ERROR] func Exists returns a new error type > not found bucket:accounts,key:sysiphus
May 09 14:51:51 sysiphus v2raya[26259]: 2021/05/09 14:51:51 [Warning] not found
May 09 14:51:57 sysiphus v2raya[26259]: 2021/05/09 14:51:57 which.go:134: dial tcp 183.232.56.221:10252: i/o timeout
May 09 14:51:57 sysiphus v2raya[26259]: 2021/05/09 14:51:57 which.go:134: dial tcp 210.0.158.76:10601: i/o timeout
May 09 14:51:57 sysiphus v2raya[26259]: 2021/05/09 14:51:57 [Warning] github.com/v2rayA/v2rayA/server/service: not found
May 09 14:52:10 sysiphus v2raya[26259]: 2021/05/09 14:52:10 connect.go:66: Connect: begin
May 09 14:52:10 sysiphus v2raya[26259]: 2021/05/09 14:52:10 connect.go:93: Connect: done
May 09 14:52:10 sysiphus v2raya[26259]: 2021/05/09 14:52:10 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: not found > not found
May 09 14:52:15 sysiphus v2raya[26259]: 2021/05/09 14:52:15 connect.go:66: Connect: begin
May 09 14:52:16 sysiphus v2raya[26259]: 2021/05/09 14:52:16 connect.go:93: Connect: done
May 09 14:52:16 sysiphus v2raya[26259]: 2021/05/09 14:52:16 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: not found > not found
May 09 14:52:23 sysiphus v2raya[26259]: 2021/05/09 14:52:23 connect.go:66: Connect: begin
May 09 14:52:23 sysiphus v2raya[26259]: 2021/05/09 14:52:23 connect.go:93: Connect: done
May 09 14:52:23 sysiphus v2raya[26259]: 2021/05/09 14:52:23 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: not found > not found
May 09 14:52:51 sysiphus v2raya[26259]: down<geosite.dat> 3835545-4383483
May 09 14:52:51 sysiphus v2raya[26259]: down<geosite.dat> 1095870-1643804
May 09 14:52:51 sysiphus v2raya[26259]: down<geosite.dat> 2191740-2739674
May 09 14:52:51 sysiphus v2raya[26259]: down<geosite.dat> 2739675-3287609
May 09 14:52:51 sysiphus v2raya[26259]: down<geosite.dat> 547935-1095869
May 09 14:52:51 sysiphus v2raya[26259]: down<geosite.dat> 0-547934
May 09 14:52:51 sysiphus v2raya[26259]: down<geosite.dat> 1643805-2191739
May 09 14:52:51 sysiphus v2raya[26259]: down<geosite.dat> 3287610-3835544
May 09 14:52:55 sysiphus v2raya[26259]: down<geosite.dat.sha256sum> 63-77
May 09 14:52:55 sysiphus v2raya[26259]: down<geosite.dat.sha256sum> 27-35
May 09 14:52:55 sysiphus v2raya[26259]: down<geosite.dat.sha256sum> 45-53
May 09 14:52:55 sysiphus v2raya[26259]: down<geosite.dat.sha256sum> 18-26
May 09 14:52:55 sysiphus v2raya[26259]: down<geosite.dat.sha256sum> 9-17
May 09 14:52:55 sysiphus v2raya[26259]: down<geosite.dat.sha256sum> 54-62
May 09 14:52:55 sysiphus v2raya[26259]: down<geosite.dat.sha256sum> 36-44

 系统：Linux sysiphus 5.4.0-71-generic #79~18.04.1-Ubuntu SMP Thu Mar 25 05:45:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
啥问题

**Comment by cubercsl** [comment]
@sisyphus1212 which v2ray 的输出是什么

**Comment by sisyphus1212** [comment]
解决了，没有装v2ray-core
# download script
curl -O https://cdn.jsdelivr.net/gh/v2rayA/v2rayA@master/install/go.sh
# install v2ray-core from jsdelivr
sudo bash go.sh
