### ISSUE TITLE
VLESS 导入/导出 分享链接需要完善

### ISSUE THREAD

**Issue by cubercsl** [v2rayA/v2rayA#182]
### 功能特性内容

VLESS 协议分享格式。

目前导出的格式直接将 json base64 编码，并添加了 `vmess://` 前缀，经测试在 v2rayA 内部可以正常导入导出。

https://github.com/v2rayA/v2rayA/blob/6b27a5be8270c29b666f4a86419ad9c3d661a7e6/service/core/vmessInfo/vmessInfo.go#L40

暂时无法正确从外部导入以 `vless://` 为前缀的链接，会当作订阅地址解析，并报错：
```
github.com/v2rayA/v2rayA/server/service: failed to resolve subscription address > Get "http://vless//****": dial tcp: lookup vless: no such host
```

VLESS 分享链接参考 https://github.com/XTLS/Xray-core/issues/91 。

**Comment by mzz2017** [comment]
Thanks for your issue.
It has been integrated in [v1.3.3](https://github.com/v2rayA/v2rayA/releases/tag/v1.3.3)
