### ISSUE TITLE
开启全局透明代理后，cloudflared（argo tunnel）无法使用

### ISSUE THREAD

**Issue by zvzl** [v2rayA/v2rayA#188]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.3.2
2. What approach of installation do you install V2rayA?
docker
3. What is your operating system?
debian10

### Description

关闭全局透明代理，cloudflared可以正常工作
开启全局透明代理后就会报错
`2021-05-23T07:46:36Z ERR Unable to establish connection with Cloudflare edge error="TLS handshake with edge error: EOF" connIndex=0
`

我使用的routingA规则见下方，前两行规则来自于cloudflare的[文档](https://developers.cloudflare.com/cloudflare-one/faq/cloudflare-tunnels-faq/#what-are-the-ports-and-ips-used-by-cloudflared)，cloudflared要连接argotunnel.com域名的7844端口，还是https协议，貌似就是这里出错了。v2raya也有报错，我认为应该没关系，日志贴在后面了。参考[这个文档](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/trycloudflare)，可以快速复现问题。
```
default: proxy

domain(domain:argotunnel.com)->direct
ip(198.41.0.0/16) ->direct
ip(geoip:private, geoip:cn)->direct
domain(geosite:cn)->direct
```

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# Paste running logs here

2021/05/23 16:15:07 [Warning] [1618900066] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws:/xxxx.com:xxx/s/xxxx.com:xxxx):  > read tcp 192.168.3.x:43848->xxx.xxx.xxx.xxx:xx: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://xxx.com:xxx/s/xxxx:xx):  > dial tcp xxxxxx:xxx: operation was canceled transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://xxxx.com:xxx/s/xxxxx.com:xx):  > dial tcp: operation was canceled] > common/retry: all retry attempts failed


```

**Comment by mzz2017** [comment]
@zvzl 请问增强模式是否能解决问题。以及能否贴出v2rayA设置，谢谢。

**Comment by zvzl** [comment]
![图片](https://user-images.githubusercontent.com/84430227/119253686-fc9cbc80-bbe4-11eb-9e3c-302be42457f1.png)
增强模式需要开启dns，但是我本地已经有dns服务了，开启dns，docker可能会崩

**Comment by mzz2017** [comment]
@zvzl 当53端口不可用时也可以使用增强模式

**Comment by zvzl** [comment]
开启增强模式依然不行

**Comment by mzz2017** [comment]
@zvzl 好的，后面我会尝试复现，谢谢

**Comment by zvzl** [comment]
感谢

**Comment by lxxself** [comment]
> ### Version, approach of installation, operating system
> 1. What version of v2rayA are you using?
>    1.3.2
> 2. What approach of installation do you install V2rayA?
>    docker
> 3. What is your operating system?
>    debian10
> 
> ### Description
> 关闭全局透明代理，cloudflared可以正常工作 开启全局透明代理后就会报错 `2021-05-23T07:46:36Z ERR Unable to establish connection with Cloudflare edge error="TLS handshake with edge error: EOF" connIndex=0 `
> 
> 我使用的routingA规则见下方，前两行规则来自于cloudflare的[文档](https://developers.cloudflare.com/cloudflare-one/faq/cloudflare-tunnels-faq/#what-are-the-ports-and-ips-used-by-cloudflared)，cloudflared要连接argotunnel.com域名的7844端口，还是https协议，貌似就是这里出错了。v2raya也有报错，我认为应该没关系，日志贴在后面了。参考[这个文档](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/trycloudflare)，可以快速复现问题。
> 
> ```
> default: proxy
> 
> domain(domain:argotunnel.com)->direct
> ip(198.41.0.0/16) ->direct
> ip(geoip:private, geoip:cn)->direct
> domain(geosite:cn)->direct
> ```
> 
> ### Logs：
> ```shell
> # daemon mode
> journalctl -u v2raya | tail -n 50
> 
> # docker mode
> docker logs v2raya
> ```
> 
> ```shell
> # Paste running logs here
> 
> 2021/05/23 16:15:07 [Warning] [1618900066] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws:/xxxx.com:xxx/s/xxxx.com:xxxx):  > read tcp 192.168.3.x:43848->xxx.xxx.xxx.xxx:xx: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://xxx.com:xxx/s/xxxx:xx):  > dial tcp xxxxxx:xxx: operation was canceled transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://xxxx.com:xxx/s/xxxxx.com:xx):  > dial tcp: operation was canceled] > common/retry: all retry attempts failed
> ```

我也遇到了一模一样的问题，请问目前有解决方案么

**Comment by zvzl** [comment]
把cloudflared放在docker里，网络选择bridge

**Comment by lxxself** [comment]
> 把cloudflared放在docker里，网络选择bridge

那可能有一点不一样，我本就是把cloudflared放在docker里，网络bridge，然后全局透明代理。然后v2raya也是docker，所有的docker都是放NAS上。才报的这个错。

**Comment by zvzl** [comment]
> 把cloudflared放在docker里，网络选择bridge

我关闭了增强模式，版本是1.3.3，实测可以。你的nas系统是阉割版本的linux吗

**Comment by mzz2017** [comment]
> > 把cloudflared放在docker里，网络选择bridge
> 
> 
> 
> 那可能有一点不一样，我本就是把cloudflared放在docker里，网络bridge，然后全局透明代理。然后v2raya也是docker，所有的docker都是放NAS上。才报的这个错。

设置里选tproxy模式，以绕过docker

**Comment by anhilo** [comment]
手动写了个代码测试了下。发现是v2ray的sniffer 模块的一个问题，不知道如何去修复。我是将DNS嗅探关闭就可以使用了。
`tlsConfig := &tls.Config{InsecureSkipVerify: true,ServerName: "www.qq.com"}
	conn, err := tls.Dial("tcp", "198.41.200.193:7844", tlsConfig)
	if err != nil {
		log.Println(err)
		panic(err.Error())
		fmt.Println(err)
		return
	}

	tlsEdgeConn := tls.Client(conn, tlsConfig)
	fmt.Println("ccc")

	if err = tlsEdgeConn.Handshake(); err != nil {
		//fmt.Println(err.Error())
		fmt.Println("222")
		//return nil, newDialError(err, "TLS handshake with edge error")
	}else {
		fmt.Println("ok11")
	}`
上述代码经过透明代理后，会去连接www.qq.com的7788端口。
推测产生这个问题的原因是v2ray 会去劫持tls请求，获取tls中的域名后，将目的地址更改为v2ray解析的域名，但由于 h2.cftunnel.com 这个解析为空，导致v2ray连接空地址 连接失败。
`2021/11/26 01:39:45 [Info] [1459510126] proxy/dokodemo: received request for 10.0.4.15:45376
2021/11/26 01:39:45 [Info] [1459510126] app/dispatcher: sniffed domain: h2.cftunnel.com
2021/11/26 01:39:45 [Debug] app/dns: domain h2.cftunnel.com will use DNS in order: [UDP:223.6.6.6:53 UDP:119.29.29.29:53 TCP//208.67.220.220:5353 TCP//119.29.29.29:53]
2021/11/26 01:39:45 [Info] app/dns: UDP:223.6.6.6:53 cache HIT h2.cftunnel.com -> [] > empty response
2021/11/26 01:39:45 [Info] app/dns: failed to lookup ip for domain h2.cftunnel.com at server UDP:223.6.6.6:53 > empty response                                                                                                    2021/11/26 01:39:45 [Info] features/routing/dns: resolve ip for h2.cftunnel.com > empty response                                                                                                                                  2021/11/26 01:39:45 [Debug] app/dns: domain h2.cftunnel.com will use DNS in order: [UDP:223.6.6.6:53 UDP:119.29.29.29:53 TCP//208.67.220.220:5353 TCP//119.29.29.29:53]                                                           2021/11/26 01:39:45 [Info] app/dns: UDP:223.6.6.6:53 cache HIT h2.cftunnel.com -> [] > empty response                                                                                                                             2021/11/26 01:39:45 [Info] app/dns: failed to lookup ip for domain h2.cftunnel.com at server UDP:223.6.6.6:53 > empty response                                                                                                    2021/11/26 01:39:45 [Info] features/routing/dns: resolve ip for h2.cftunnel.com > empty response`

并且我发现一个V2RAYA的小bug，好像并不能关闭DNS拦截。sniffing 一直为TRUE。。手动改了。

**Comment by mzz2017** [comment]
@anhilo 透明代理不嗅探的话只能根据ip分流

**Comment by mzz2017** [comment]
为了**解决 sniffing 所引发的问题**，我决定更改 v2rayA 中 fakedns 的行为来解决相关问题。

测试版本已打包于 https://github.com/v2rayA/v2rayA/actions/runs/1510550893 ，请在 Github 登录后下载对应 CPU 架构文件替换你的当前 v2rayA 二进制文件。

在使用该测试版本情况下：

1. 将 DNS 防污染设为“关闭”以外的任意一项，以开启 FakeDNS 的选项。
2. 在特殊模式中选择 FakeDNS。

而后查看问题是否解决。

该版本的行为如下：
1. 对所有域名启用 FakeDNS。
2. 不使用 tls/http 嗅探（关键）。

FakeDNS 可能引发的问题：
1. 污染 dns 映射关系。如 ssh 的 known_hosts。
2. 污染 dns 缓存。在切换节点、保存设置、关闭 v2rayA 等情况下可能会导致部分网站暂时无法访问，待缓存刷新后生效。
3. 极少数会验证 IP 的应用会出现不可用的情况。

望周知。

**Comment by ixinshang** [comment]
遇到类似的情况，只不过我的V2部署在padavan的路由器中
还没想到啥办法。。。

**Comment by johnrosen1** [comment]
@mzz2017 经过测试，发现是V2raya的DNS配置有问题，无法解析srv record，把    `"address": "2.0.1.7"` 改成 `"address": "1.1.1.1"` 就可以正常连接了 , 望周知。

**Comment by mzz2017** [comment]
@johnrosen1 嗯。。很有可能，因为 v2ray-core 仅支持 A/AAAA 的解析。

**Comment by mzz2017** [comment]
@johnrosen1 可将相关 issue 发至 v2ray-core

**Comment by mzz2017** [comment]
@johnrosen1 请问 2.0.1.7 具体在哪里？

**Comment by johnrosen1** [comment]
“在处理 DNS 查询时，此出站协议会将 IP 查询（即 A 和 AAAA）转发给内置的 [DNS 服务器](https://www.v2fly.org/config/dns.html)。其它类型的查询流量将被转发至它们原本的目标地址。”

所以那个address其实是拿来转发非 a/aaaa 解析的对吧？那么是不是不应该设置为一个空地址？

**Comment by johnrosen1** [comment]
@mzz2017 inbounds设置里面

**Comment by johnrosen1** [comment]
{
      "port": 53,
      "protocol": "dokodemo-door",
      "listen": "0.0.0.0",
      "sniffing": {
        "enabled": false,
        "metadataOnly": false
      },
      "settings": {
        "network": "udp",
        "address": "2.0.1.7",
        "port": 53
      },
      "streamSettings": null,
      "tag": "dns-in"
    },

**Comment by johnrosen1** [comment]
这里的2.0.1.7

**Comment by mzz2017** [comment]
@johnrosen1 好的，感谢排查，我会跟进

**Comment by johnrosen1** [comment]
🆗

**Comment by johnrosen1** [comment]
@mzz2017 所以这个issue名字是不是应该改成 “非a/aaaa DNS记录无法解析” ？ 这样应该更好。

顺便，这个是SRV的debug方法，`dig +short _origintunneld._tcp.argotunnel.com. SRV`

**Comment by mzz2017** [comment]
@johnrosen1 好的，可以的。谢谢。

**Comment by mzz2017** [comment]
已修复于 1.5.8

**Comment by weasam** [comment]
老毛子路由器Padavan 的V2ray/xray 未能解决

**Comment by weasam** [comment]
我不使用 V2Ray 的内置 DNS 服务就解决了
 搭建Web环境 > V2ray > V2Ray 链接生成 V2Ray 配置 > 使用 V2Ray 的内置 DNS 服务？> 不使用

**Comment by lijunle** [comment]
仍然遇到一样的问题，把防止DNS污染改为DoH可以解决。本来是快速仅防止劫持。

![image](https://github.com/v2rayA/v2rayA/assets/1296500/8243b83f-9b5d-44d8-b9f9-b04693773120)
