### ISSUE TITLE
“仅防止DNS劫持”模式下，第一个DNS地址，填写国内DOH域名失败

### ISSUE THREAD

**Issue by imapproxy** [v2rayA/v2rayA#191]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2rayA---------V1.3.3
v2ray-core----V4.37.3-1.1

2. 你通过什么方式安装v2rayA
sudo rpm -i ./installer_redhat_amd64_v1.3.3.rpm

3. 你所使用的操作系统
openSUSE Tumbleweed 20210522
KDE Plasma 5.21.5, kernel 5.12.4-1-default

### 描述问题

“仅防止DNS劫持”模式下，在第一个DNS地址处，尝试分别填写：
https://doh.pub/dns-query，https://doh.360.cn/dns-query， https://i.233py.com/dns-query，https://dns.alidns.com/dns-query
全都提示bad format of doh server。

去掉https://，同样提示bad format of doh server；

去掉https:// 和 dns-query，可以保存“仅防止DNS劫持”下的DNS列表，但“防止DNS污染”下切换为DOH模式，点击保存并应用却无法正常启动v2rayA

### 复现问题的步骤

按描述操作即可复现。

**Comment by mzz2017** [comment]
@imapproxy 那要选择DoH才可以，不要选择仅防止dns劫持

**Comment by imapproxy** [comment]
> @imapproxy 那要选择DoH才可以，不要选择仅防止dns劫持

那如何实现：*国内IP或GFW以外域名采用国内的DOH，国外IP或GFW域名采用国外的DOH？*

“DOH”模式下的DNS列表，应该是作为解析国外地址的DNS服务器存在的吧。
个人理解，国内的DOH是存在DNS污染的，不能写在“DOH”模式下的DNS列表中。

按照界面上的说明：“仅防止DNS劫持”模式下DNS列表的第一个，将作为“DOH”模式下解析国内地址的DNS服务器。
所以出现把国内DOH写在“仅防止DNS劫持”模式下DNS列表的第一个的举动。

![仅防止DNS劫持的DNS列表](https://user-images.githubusercontent.com/40516405/119671049-02f09a00-be6c-11eb-9b1f-e20eb7072aaf.png)

**Comment by mzz2017** [comment]
@imapproxy 暂时不支持这种方式，谢谢你的提出，下个版本考虑支持

**Comment by mzz2017** [comment]
已支持。见 https://github.com/v2rayA/v2rayA/releases/tag/v1.4.0
