### ISSUE TITLE
为通用安装方式提供包含 Web GUI 的安装包

### ISSUE THREAD

**Issue by CodeingBoy** [v2rayA/v2rayA#193]
https://github.com/v2rayA/v2rayA/wiki/Usage#universal-approach 中仅提到了下载二进制文件，但是没有提到和提供编译好的 Web GUI 文件，需要使用者自行编译上传。建议能够提供一个包含二进制文件以及 Web GUI 的安装包

**Comment by mzz2017** [comment]
@CodeingBoy 安装包可以在releases中找到。如果使用二进制文件，也可以配合demo站 http://v.mzz.pub 使用

**Comment by CodeingBoy** [comment]
> @CodeingBoy 安装包可以在releases中找到。如果使用二进制文件，也可以配合demo站 http://v.mzz.pub 使用

最新的 v1.3.3 release 中仅提供了二进制文件，没有适用于 universal 的安装包

**Comment by mzz2017** [comment]
@CodeingBoy 不存在universal的安装包
