### ISSUE TITLE
我在旧版本中1.2.2 中启动 可以正常访问通20170/20172端口 但是新版本 1.3.3 访问不通了

### ISSUE THREAD

**Issue by hao276843248** [v2rayA/v2rayA#196]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.2.2 和 1.3.3
2. 你通过什么方式安装v2rayA
新版本 通过软件源安装
3. 你所使用的操作系统
Ubuntu

### 描述问题：

我看端口 和服务绑定 ip 发现 新版本 绑定   127.0.0.1:20170/20172
旧版本绑定    :::20170/20172 
不知道是不是这个原因我访问不了新版本地址了

### v2rayA运行日志（Optional）：
旧版本
![image](https://user-images.githubusercontent.com/25560026/121303996-5532c000-c92e-11eb-93d6-5202283eb84c.png)
新版本
![image](https://user-images.githubusercontent.com/25560026/121304165-94611100-c92e-11eb-80f2-809a228e2094.png)

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya_backend
 ```
```shell
# 此处贴入运行日志



```

**Comment by mzz2017** [comment]
@hao276843248 新版本需要在设置中开启局域网共享

**Comment by hao276843248** [comment]
好了 感谢！！
