### ISSUE TITLE
failed to connected > github.com/v2rayA/v2rayA/core/v2ray

### ISSUE THREAD

**Issue by skull591** [v2rayA/v2rayA#199]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.3.3

2. 你通过什么方式安装v2rayA

sudo apt install v2raya

3. 你所使用的操作系统
Ubuntu 20.04.2 LTS

### 描述问题：

When trying to connect, failed with a message:
failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
-- Logs begin at Mon 2021-03-08 10:32:55 CST, end at Tue 2021-06-22 16:24:09 CST. --
6月 22 15:10:55 threedean-office v2ray[14738]: A unified platform for anti-censorship.
6月 22 15:10:55 threedean-office v2ray[14738]: 2021/06/22 15:10:55 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
6月 22 15:10:55 threedean-office v2ray[14738]: 2021/06/22 15:10:55 [Warning] github.com/v2fly/v2ray-core/v4: V2Ray 4.35.1 started
6月 22 15:19:20 threedean-office systemd[1]: Stopping V2Ray Service...
6月 22 15:19:20 threedean-office systemd[1]: v2ray.service: Succeeded.
6月 22 15:19:20 threedean-office systemd[1]: Stopped V2Ray Service.
6月 22 15:19:20 threedean-office systemd[1]: Started V2Ray Service.
6月 22 15:19:20 threedean-office v2ray[16359]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
6月 22 15:19:20 threedean-office v2ray[16359]: A unified platform for anti-censorship.
6月 22 15:19:20 threedean-office v2ray[16359]: 2021/06/22 15:19:20 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
6月 22 15:19:20 threedean-office v2ray[16359]: main: failed to read config files: [/usr/local/etc/v2ray/config.json] > github.com/v2fly/v2ray-core/v4/infra/conf: invalid field rule > github.com/v2fly/v2ray-core/v4/infra/conf: failed to parse domain rule: ext:LoyalsoldierSite.dat:geolocation-!cn > github.com/v2fly/v2ray-core/v4/infra/conf: failed to load external geosite: geolocation-!cn from LoyalsoldierSite.dat > proto: invalid field number
6月 22 15:19:20 threedean-office systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
6月 22 15:19:20 threedean-office systemd[1]: v2ray.service: Failed with result 'exit-code'.
6月 22 15:20:15 threedean-office systemd[1]: Started V2Ray Service.
6月 22 15:20:15 threedean-office v2ray[16397]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
6月 22 15:20:15 threedean-office v2ray[16397]: A unified platform for anti-censorship.
6月 22 15:20:15 threedean-office v2ray[16397]: 2021/06/22 15:20:15 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
6月 22 15:20:15 threedean-office v2ray[16397]: main: failed to read config files: [/usr/local/etc/v2ray/config.json] > github.com/v2fly/v2ray-core/v4/infra/conf: invalid field rule > github.com/v2fly/v2ray-core/v4/infra/conf: failed to parse domain rule: ext:LoyalsoldierSite.dat:geolocation-cn > github.com/v2fly/v2ray-core/v4/infra/conf: failed to load external geosite: geolocation-cn from LoyalsoldierSite.dat > proto: invalid field number
6月 22 15:20:15 threedean-office systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
6月 22 15:20:15 threedean-office systemd[1]: v2ray.service: Failed with result 'exit-code'.
6月 22 15:30:59 threedean-office systemd[1]: Started V2Ray Service.
6月 22 15:30:59 threedean-office v2ray[18017]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
6月 22 15:30:59 threedean-office v2ray[18017]: A unified platform for anti-censorship.
6月 22 15:30:59 threedean-office v2ray[18017]: 2021/06/22 15:30:59 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
6月 22 15:30:59 threedean-office v2ray[18017]: main: failed to read config files: [/usr/local/etc/v2ray/config.json] > github.com/v2fly/v2ray-core/v4/infra/conf: invalid field rule > github.com/v2fly/v2ray-core/v4/infra/conf: failed to parse domain rule: ext:LoyalsoldierSite.dat:geolocation-!cn > github.com/v2fly/v2ray-core/v4/infra/conf: failed to load external geosite: geolocation-!cn from LoyalsoldierSite.dat > proto: invalid field number
6月 22 15:30:59 threedean-office systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
6月 22 15:30:59 threedean-office systemd[1]: v2ray.service: Failed with result 'exit-code'.
6月 22 15:37:02 threedean-office systemd[1]: Started V2Ray Service.
6月 22 15:37:02 threedean-office v2ray[19004]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
6月 22 15:37:02 threedean-office v2ray[19004]: A unified platform for anti-censorship.
6月 22 15:37:02 threedean-office v2ray[19004]: 2021/06/22 15:37:02 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
6月 22 15:37:02 threedean-office v2ray[19004]: main: failed to read config files: [/usr/local/etc/v2ray/config.json] > github.com/v2fly/v2ray-core/v4/infra/conf: invalid field rule > github.com/v2fly/v2ray-core/v4/infra/conf: failed to parse domain rule: ext:LoyalsoldierSite.dat:geolocation-!cn > github.com/v2fly/v2ray-core/v4/infra/conf: failed to load external geosite: geolocation-!cn from LoyalsoldierSite.dat > github.com/v2fly/v2ray-core/v4/infra/conf: failed to open file: LoyalsoldierSite.dat > open /usr/local/bin/LoyalsoldierSite.dat: no such file or directory
6月 22 15:37:02 threedean-office systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
6月 22 15:37:02 threedean-office systemd[1]: v2ray.service: Failed with result 'exit-code'.
6月 22 16:02:34 threedean-office systemd[1]: Started V2Ray Service.
6月 22 16:02:34 threedean-office v2ray[22839]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
6月 22 16:02:34 threedean-office v2ray[22839]: A unified platform for anti-censorship.
6月 22 16:02:34 threedean-office v2ray[22839]: 2021/06/22 16:02:34 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
6月 22 16:02:34 threedean-office v2ray[22839]: 2021/06/22 16:02:34 [Warning] github.com/v2fly/v2ray-core/v4: V2Ray 4.35.1 started
6月 22 16:03:06 threedean-office systemd[1]: Stopping V2Ray Service...
6月 22 16:03:06 threedean-office systemd[1]: v2ray.service: Succeeded.
6月 22 16:03:06 threedean-office systemd[1]: Stopped V2Ray Service.
6月 22 16:04:57 threedean-office systemd[1]: Started V2Ray Service.
6月 22 16:04:57 threedean-office v2ray[23636]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
6月 22 16:04:57 threedean-office v2ray[23636]: A unified platform for anti-censorship.
6月 22 16:04:57 threedean-office v2ray[23636]: 2021/06/22 16:04:57 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
6月 22 16:04:57 threedean-office v2ray[23636]: 2021/06/22 16:04:57 [Warning] github.com/v2fly/v2ray-core/v4: V2Ray 4.35.1 started
6月 22 16:14:55 threedean-office systemd[1]: Stopping V2Ray Service...
6月 22 16:14:55 threedean-office systemd[1]: v2ray.service: Succeeded.
6月 22 16:14:55 threedean-office systemd[1]: Stopped V2Ray Service.

 # docker mode
 docker logs v2raya_backend
 ```
```shell
# 此处贴入运行日志
-- Logs begin at Mon 2021-03-08 10:32:55 CST, end at Tue 2021-06-22 16:20:25 CST. --
6月 22 16:04:03 threedean-office v2raya[23129]: Starting...
6月 22 16:04:03 threedean-office v2raya[23129]: v2rayA is listening at http://127.0.0.1:2017
6月 22 16:04:03 threedean-office v2raya[23129]: v2rayA is listening at http://114.212.82.22:2017
6月 22 16:04:03 threedean-office v2raya[23129]: v2rayA is listening at http://[::1]:2017
6月 22 16:04:03 threedean-office v2raya[23129]: v2rayA is listening at http://[2001:250:5002:8100::1:a3b0]:2017
6月 22 16:04:03 threedean-office v2raya[23129]: v2rayA is listening at http://[fe80::5b61:b8c3:cfbb:4cbc]:2017
6月 22 16:04:04 threedean-office v2raya[23129]: 2021/06/22 16:04:04 pre.go:288: Failed to update PAC file: github.com/v2rayA/v2rayA/core/v2ray/asset/gfwlist: latest version is 2021-06-16. GFWList is up to date
6月 22 16:04:23 threedean-office v2raya[23129]: 2021/06/22 16:04:23 connect.go:67: Connect: begin
6月 22 16:04:23 threedean-office v2raya[23129]: 2021/06/22 16:04:23 status.go:47: /usr/local/bin/v2ray --config=/etc/v2raya/config.json
6月 22 16:04:23 threedean-office v2raya[23611]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
6月 22 16:04:23 threedean-office v2raya[23611]: A unified platform for anti-censorship.
6月 22 16:04:23 threedean-office v2raya[23611]: 2021/06/22 16:04:23 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /etc/v2raya/config.json
6月 22 16:04:38 threedean-office v2raya[23129]: 2021/06/22 16:04:38 connect.go:101: Connect: done
6月 22 16:04:38 threedean-office v2raya[23129]: 2021/06/22 16:04:38 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information
6月 22 16:05:19 threedean-office v2raya[23129]: 2021/06/22 16:05:19 connect.go:67: Connect: begin
6月 22 16:05:19 threedean-office v2raya[23129]: 2021/06/22 16:05:19 status.go:47: /usr/local/bin/v2ray --config=/etc/v2raya/config.json
6月 22 16:05:19 threedean-office v2raya[23757]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
6月 22 16:05:19 threedean-office v2raya[23757]: A unified platform for anti-censorship.
6月 22 16:05:19 threedean-office v2raya[23757]: 2021/06/22 16:05:19 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /etc/v2raya/config.json
6月 22 16:05:34 threedean-office v2raya[23129]: 2021/06/22 16:05:34 connect.go:101: Connect: done
6月 22 16:05:34 threedean-office v2raya[23129]: 2021/06/22 16:05:34 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information
6月 22 16:08:15 threedean-office v2raya[23129]: 2021/06/22 16:08:15 [Warning] github.com/v2rayA/v2rayA/core/v2ray/asset/gfwlist: latest version is 2021-06-16. GFWList is up to date
6月 22 16:08:24 threedean-office v2raya[23129]: 2021/06/22 16:08:24 connect.go:67: Connect: begin
6月 22 16:08:24 threedean-office v2raya[23129]: 2021/06/22 16:08:24 status.go:47: /usr/local/bin/v2ray --config=/etc/v2raya/config.json
6月 22 16:08:24 threedean-office v2raya[24067]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
6月 22 16:08:24 threedean-office v2raya[24067]: A unified platform for anti-censorship.
6月 22 16:08:24 threedean-office v2raya[24067]: 2021/06/22 16:08:24 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /etc/v2raya/config.json
6月 22 16:08:39 threedean-office v2raya[23129]: 2021/06/22 16:08:39 connect.go:101: Connect: done
6月 22 16:08:39 threedean-office v2raya[23129]: 2021/06/22 16:08:39 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information
6月 22 16:09:37 threedean-office v2raya[23129]: 2021/06/22 16:09:37 connect.go:67: Connect: begin
6月 22 16:09:37 threedean-office v2raya[23129]: 2021/06/22 16:09:37 status.go:47: /usr/local/bin/v2ray --config=/etc/v2raya/config.json
6月 22 16:09:37 threedean-office v2raya[24245]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
6月 22 16:09:37 threedean-office v2raya[24245]: A unified platform for anti-censorship.
6月 22 16:09:37 threedean-office v2raya[24245]: 2021/06/22 16:09:37 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /etc/v2raya/config.json
6月 22 16:09:52 threedean-office v2raya[23129]: 2021/06/22 16:09:52 connect.go:101: Connect: done
6月 22 16:09:52 threedean-office v2raya[23129]: 2021/06/22 16:09:52 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information
6月 22 16:16:14 threedean-office v2raya[23129]: 2021/06/22 16:16:14 connect.go:67: Connect: begin
6月 22 16:16:14 threedean-office v2raya[23129]: 2021/06/22 16:16:14 status.go:47: /usr/local/bin/v2ray --config=/etc/v2raya/config.json
6月 22 16:16:14 threedean-office v2raya[25712]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
6月 22 16:16:14 threedean-office v2raya[25712]: A unified platform for anti-censorship.
6月 22 16:16:14 threedean-office v2raya[25712]: 2021/06/22 16:16:14 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /etc/v2raya/config.json
6月 22 16:16:29 threedean-office v2raya[23129]: 2021/06/22 16:16:29 connect.go:101: Connect: done
6月 22 16:16:29 threedean-office v2raya[23129]: 2021/06/22 16:16:29 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information
6月 22 16:17:19 threedean-office v2raya[23129]: 2021/06/22 16:17:19 connect.go:67: Connect: begin
6月 22 16:17:20 threedean-office v2raya[23129]: 2021/06/22 16:17:20 status.go:47: /usr/local/bin/v2ray --config=/etc/v2raya/config.json
6月 22 16:17:20 threedean-office v2raya[25880]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
6月 22 16:17:20 threedean-office v2raya[25880]: A unified platform for anti-censorship.
6月 22 16:17:20 threedean-office v2raya[25880]: 2021/06/22 16:17:20 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /etc/v2raya/config.json
6月 22 16:17:35 threedean-office v2raya[23129]: 2021/06/22 16:17:35 connect.go:101: Connect: done
6月 22 16:17:35 threedean-office v2raya[23129]: 2021/06/22 16:17:35 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information


```

**Comment by mzz2017** [comment]
infra/conf: failed to parse domain rule: ext:LoyalsoldierSite.dat:geolocation-!cn > github.com/v2fly/v2ray-core/v4/infra/conf: failed to load external geosite: geolocation-!cn from LoyalsoldierSite.dat > github.com/v2fly/v2ray-core/v4/infra/conf: failed to open file: LoyalsoldierSite.dat > open /usr/local/bin/LoyalsoldierSite.dat: no such file or d



先在设置里更新gfwlist

**Comment by shaodan** [comment]
@skull591 
我今天也遇到这个报错，后来发现是忘了第一步[安装v2ray-core](https://github.com/v2rayA/v2rayA/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95#user-content-%E5%AE%89%E8%A3%85-v2ray-%E5%86%85%E6%A0%B8--xray-%E5%86%85%E6%A0%B8)

**Comment by adaaaaaa** [comment]
> ```shell
> journalctl -u v2ray | tail -n 50
> ```

这个我导不出什么日志哦。。。日志到底去哪里看？😭

**Comment by mzz2017** [comment]
@adaaaaaa journalctl -u v2raya

**Comment by adaaaaaa** [comment]
[captain@captain-notebook ~]$ journalctl -u v2raya | tail -n 50
-- Boot 3ce7f4c8290b4aa29a84c4372decf69d --
7月 15 15:59:31 captain-notebook systemd[1]: Started v2rayA Service.
7月 15 15:59:32 captain-notebook v2raya[436]: V2RayLocationAsset is /usr/share/v2ray
7月 15 15:59:32 captain-notebook v2raya[436]: V2Ray binary is /usr/bin/v2ray
7月 15 15:59:32 captain-notebook v2raya[436]: v2rayA working directory is /
7月 15 15:59:32 captain-notebook v2raya[436]: Version: 1.3.3
7月 15 15:59:32 captain-notebook v2raya[436]: Starting...
7月 15 15:59:32 captain-notebook v2raya[436]: v2rayA is listening at http://127.0.0.1:2017
7月 15 15:59:32 captain-notebook v2raya[436]: v2rayA is listening at http://[::1]:2017
7月 15 15:59:47 captain-notebook v2raya[436]: 2021/07/15 15:59:47 pre.go:288: Failed to update PAC file: github.com/v2rayA/v2rayA/core/v2ray/asset/gfwlist: latest version is 2021-07-14. GFWList is up to date
7月 15 15:59:59 captain-notebook v2raya[436]: 2021/07/15 15:59:59 connect.go:67: Connect: begin
7月 15 15:59:59 captain-notebook v2raya[436]: 2021/07/15 15:59:59 status.go:47: /usr/bin/v2ray --config=/etc/v2raya/config.json
7月 15 15:59:59 captain-notebook v2raya[2010]: V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 linux/amd64)
7月 15 15:59:59 captain-notebook v2raya[2010]: A unified platform for anti-censorship.
7月 15 15:59:59 captain-notebook v2raya[2010]: 2021/07/15 15:59:59 [Info] main/jsonem: Reading config: /etc/v2raya/config.json
7月 15 15:59:59 captain-notebook v2raya[2010]: main: failed to read config files: [/etc/v2raya/config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: ext:LoyalsoldierSite.dat:geolocation-!cn > infra/conf: failed to load external geosite: geolocation-!cn from LoyalsoldierSite.dat > proto: cannot parse invalid wire-format data
7月 15 15:59:57 captain-notebook v2raya[436]: 2021/07/15 15:59:57 connect.go:101: Connect: done
7月 15 15:59:57 captain-notebook v2raya[436]: 2021/07/15 15:59:57 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information
7月 15 16:03:58 captain-notebook v2raya[436]: 2021/07/15 16:03:58 connect.go:67: Connect: begin
7月 15 16:03:59 captain-notebook v2raya[436]: 2021/07/15 16:03:59 status.go:47: /usr/bin/v2ray --config=/etc/v2raya/config.json
7月 15 16:03:59 captain-notebook v2raya[2890]: V2Ray 4.40.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.5 linux/amd64)
7月 15 16:03:59 captain-notebook v2raya[2890]: A unified platform for anti-censorship.
7月 15 16:03:59 captain-notebook v2raya[2890]: 2021/07/15 16:03:59 [Info] main/jsonem: Reading config: /etc/v2raya/config.json
7月 15 16:03:59 captain-notebook v2raya[2890]: main: failed to read config files: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: ext:LoyalsoldierSite.dat:geolocation-!cn > infra/conf/rule: failed to load external geosite: geolocation-!cn from LoyalsoldierSite.dat > proto: cannot parse invalid wire-format data
7月 15 16:04:14 captain-notebook v2raya[436]: 2021/07/15 16:04:14 connect.go:101: Connect: done
7月 15 16:04:14 captain-notebook v2raya[436]: 2021/07/15 16:04:14 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information
7月 15 16:58:33 captain-notebook v2raya[436]: 2021/07/15 16:58:33 connect.go:67: Connect: begin
7月 15 16:58:33 captain-notebook v2raya[436]: 2021/07/15 16:58:33 status.go:47: /usr/bin/v2ray --config=/etc/v2raya/config.json
7月 15 16:58:33 captain-notebook v2raya[7494]: V2Ray 4.40.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.5 linux/amd64)
7月 15 16:58:33 captain-notebook v2raya[7494]: A unified platform for anti-censorship.
7月 15 16:58:33 captain-notebook v2raya[7494]: 2021/07/15 16:58:33 [Info] main/jsonem: Reading config: /etc/v2raya/config.json
7月 15 16:58:33 captain-notebook v2raya[7494]: main: failed to read config files: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: ext:LoyalsoldierSite.dat:geolocation-!cn > infra/conf/rule: failed to load external geosite: geolocation-!cn from LoyalsoldierSite.dat > proto: cannot parse invalid wire-format data
7月 15 16:58:48 captain-notebook v2raya[436]: 2021/07/15 16:58:48 connect.go:101: Connect: done
7月 15 16:58:48 captain-notebook v2raya[436]: 2021/07/15 16:58:48 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information
7月 15 17:04:26 captain-notebook v2raya[436]: 2021/07/15 17:04:26 connect.go:67: Connect: begin
7月 15 17:04:27 captain-notebook v2raya[436]: 2021/07/15 17:04:27 status.go:47: /usr/bin/v2ray --config=/etc/v2raya/config.json
7月 15 17:04:27 captain-notebook v2raya[9502]: V2Ray 4.40.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.5 linux/amd64)
7月 15 17:04:27 captain-notebook v2raya[9502]: A unified platform for anti-censorship.
7月 15 17:04:27 captain-notebook v2raya[9502]: 2021/07/15 17:04:27 [Info] main/jsonem: Reading config: /etc/v2raya/config.json
7月 15 17:04:27 captain-notebook v2raya[9502]: main: failed to read config files: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: ext:LoyalsoldierSite.dat:geolocation-!cn > infra/conf/rule: failed to load external geosite: geolocation-!cn from LoyalsoldierSite.dat > proto: cannot parse invalid wire-format data
7月 15 17:04:42 captain-notebook v2raya[436]: 2021/07/15 17:04:42 connect.go:101: Connect: done
7月 15 17:04:42 captain-notebook v2raya[436]: 2021/07/15 17:04:42 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information
7月 15 17:13:35 captain-notebook v2raya[436]: 2021/07/15 17:13:35 connect.go:67: Connect: begin
7月 15 17:13:35 captain-notebook v2raya[436]: 2021/07/15 17:13:35 status.go:47: /usr/bin/v2ray --config=/etc/v2raya/config.json
7月 15 17:13:35 captain-notebook v2raya[12050]: V2Ray 4.40.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.5 linux/amd64)
7月 15 17:13:35 captain-notebook v2raya[12050]: A unified platform for anti-censorship.
7月 15 17:13:35 captain-notebook v2raya[12050]: 2021/07/15 17:13:35 [Info] main/jsonem: Reading config: /etc/v2raya/config.json
7月 15 17:13:35 captain-notebook v2raya[12050]: main: failed to read config files: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: ext:LoyalsoldierSite.dat:geolocation-!cn > infra/conf/rule: failed to load external geosite: geolocation-!cn from LoyalsoldierSite.dat > proto: cannot parse invalid wire-format data
7月 15 17:13:50 captain-notebook v2raya[436]: 2021/07/15 17:13:50 connect.go:101: Connect: done
7月 15 17:13:50 captain-notebook v2raya[436]: 2021/07/15 17:13:50 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information

大佬，帮我看看？@mzz2017

**Comment by mzz2017** [comment]
@adaaaaaa 设置里把gfwlist更新一下

**Comment by adaaaaaa** [comment]
7月 16 08:04:10 captain-notebook v2raya[436]: 2021/07/16 08:04:10 connect.go:67: Connect: begin
7月 16 08:04:15 captain-notebook v2raya[436]: 2021/07/16 08:04:15 status.go:47: /usr/bin/v2ray --config=/etc/v2raya/config.json
7月 16 08:04:15 captain-notebook v2raya[115994]: V2Ray 4.40.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.5 linux/amd64)
7月 16 08:04:15 captain-notebook v2raya[115994]: A unified platform for anti-censorship.
7月 16 08:04:15 captain-notebook v2raya[115994]: 2021/07/16 08:04:15 [Info] main/jsonem: Reading config: /etc/v2raya/config.json
7月 16 08:04:15 captain-notebook v2raya[115994]: main: failed to read config files: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: ext:LoyalsoldierSite.dat:geolocation-!cn > infra/conf/rule: failed to load external geosite: geolocation-!cn from LoyalsoldierSite.dat > proto: cannot parse invalid wire-format data
7月 16 08:04:30 captain-notebook v2raya[436]: 2021/07/16 08:04:30 connect.go:101: Connect: done
7月 16 08:04:30 captain-notebook v2raya[436]: 2021/07/16 08:04:30 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information
7月 16 08:31:18 captain-notebook v2raya[436]: 2021/07/16 08:31:18 write tcp 127.0.0.1:2017->127.0.0.1:58298: write: broken pipe
7月 16 08:31:18 captain-notebook v2raya[436]: POST /api/import HTTP/1.1
7月 16 08:31:18 captain-notebook v2raya[436]: Host: 127.0.0.1:2017
7月 16 08:31:18 captain-notebook v2raya[436]: Accept: application/json, text/plain, */*
7月 16 08:31:18 captain-notebook v2raya[436]: Accept-Encoding: gzip, deflate
7月 16 08:31:18 captain-notebook v2raya[436]: Accept-Language: zh-CN
7月 16 08:31:18 captain-notebook v2raya[436]: Authorization: *
7月 16 08:31:18 captain-notebook v2raya[436]: Connection: keep-alive
7月 16 08:31:18 captain-notebook v2raya[436]: Content-Length: 55
7月 16 08:31:18 captain-notebook v2raya[436]: Content-Type: application/json;charset=utf-8
7月 16 08:31:18 captain-notebook v2raya[436]: Origin: http://127.0.0.1:2017
7月 16 08:31:18 captain-notebook v2raya[436]: Referer: http://127.0.0.1:2017/
7月 16 08:31:18 captain-notebook v2raya[436]: Sec-Fetch-Dest: empty
7月 16 08:31:18 captain-notebook v2raya[436]: Sec-Fetch-Mode: cors
7月 16 08:31:18 captain-notebook v2raya[436]: Sec-Fetch-Site: same-origin
7月 16 08:31:18 captain-notebook v2raya[436]: User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
7月 16 08:31:18 captain-notebook v2raya[436]: 
7月 16 08:31:18 captain-notebook v2raya[436]: 
7月 16 08:31:42 captain-notebook v2raya[436]: 2021/07/16 08:31:42 connect.go:67: Connect: begin
7月 16 08:31:45 captain-notebook v2raya[436]: 2021/07/16 08:31:45 status.go:47: /usr/bin/v2ray --config=/etc/v2raya/config.json
7月 16 08:31:45 captain-notebook v2raya[122785]: V2Ray 4.40.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.5 linux/amd64)
7月 16 08:31:45 captain-notebook v2raya[122785]: A unified platform for anti-censorship.
7月 16 08:31:45 captain-notebook v2raya[122785]: 2021/07/16 08:31:45 [Info] main/jsonem: Reading config: /etc/v2raya/config.json
7月 16 08:31:45 captain-notebook v2raya[122785]: main: failed to read config files: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: ext:LoyalsoldierSite.dat:geolocation-!cn > infra/conf/rule: failed to load external geosite: geolocation-!cn from LoyalsoldierSite.dat > proto: cannot parse invalid wire-format data
7月 16 08:32:00 captain-notebook v2raya[436]: 2021/07/16 08:32:00 connect.go:101: Connect: done
7月 16 08:32:00 captain-notebook v2raya[436]: 2021/07/16 08:32:00 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for mor

本地的已经比最新的还新了。。。现在显示本地是7月15的。。。@mzz2017

**Comment by mzz2017** [comment]
@adaaaaaa 把所有gfwlist换成绕过大陆

**Comment by adaaaaaa** [comment]
为什么选了大陆白名单瞬间就OK了？
以前一直都是用gfwlist模式的啊。。。@mzz2017

**Comment by mzz2017** [comment]
@adaaaaaa 你gfwlist是不是开了自动更新，给更炸了

**Comment by adaaaaaa** [comment]
卧槽。。。还有这种操作？？
现在那个gfwlist比较靠谱？功能又多的。。。🤪@mzz2017

**Comment by MarksonHon** [comment]
@adaaaaaa 一个列表而已，哪来的功能多啊，去看看v2ray的wiki吧

**Comment by mzz2017** [comment]
已修复。见 https://github.com/v2rayA/v2rayA/releases/tag/v1.4.0

**Comment by adaaaaaa** [comment]
么么哒。。。😘@mzz2017
