### ISSUE TITLE
在使用docker下，配置了开启局域网代理后，并未监听20171等端口

### ISSUE THREAD

**Issue by hbqclh** [v2rayA/v2rayA#200]
用的是最新版,网络用的是host模式，配置检查并应用后，未发现有监听20171等等端口，只有2017端口常在。

**Comment by mzz2017** [comment]
@hbqclh 尝试 https://cloud.tencent.com/developer/article/1767246

**Comment by mzz2017** [comment]
@hbqclh 另外，需要连接节点才会监听20170等端口，开启局域网代理只是会让监听127.0.0.1改为0.0.0.0，还有就是是否在设置中使用了自定义端口，或将其修改为了0

**Comment by hbqclh** [comment]
转发我都开了。网关指过来也不能上网。其它设置我都按默认的设置了。需要连接节点是什么意思呢？要怎么连？谢谢！
![image](https://user-images.githubusercontent.com/12690057/123407234-50ccff00-d5de-11eb-83bf-333f7a1cab4c.png)

**Comment by mzz2017** [comment]
@hbqclh 字面意思，创建/导入之后点连接

**Comment by hbqclh** [comment]
果然有了，非常感谢。一直没注意到这个按钮的作用。
