### ISSUE TITLE
vless+tcp无法使用host且连接 

### ISSUE THREAD

**Issue by iwrwr** [v2rayA/v2rayA#201]
在v2rayA中选择 vless+tcp
填入http伪装保存后  并不能保存上host
查看只显示不伪装
经测试在线也无法连接.

运用客户端配置导入也不行
如导入vless://blue@192.168.0.3:80?security=none&encryption=none&host=baidu.com&headerType=http&type=tcp#%E6%9C%AC%E5%9C%B0
导入后再分享直接变成vless://blue@192.168.0.3:80?security=none&type=tcp#%E6%9C%AC%E5%9C%B0
而host直接就消失了

**Comment by iwrwr** [comment]
同时希望能够选择性适配不检测可用性直接连接的功能
有时候直接报错无法而连上

**Comment by iwrwr** [comment]
连接报错信息
7月 01 02:51:31 dwight v2raya[387]: 2021/07/01 02:51:31 connect.go:67: Connect: begin
7月 01 02:51:32 dwight v2raya[387]: 2021/07/01 02:51:32 status.go:47: /usr/local/bin/v2ray --config=/etc/v2raya/config.json
7月 01 02:51:32 dwight v2raya[387]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
7月 01 02:51:32 dwight v2raya[387]: A unified platform for anti-censorship.
7月 01 02:51:32 dwight v2raya[387]: 2021/07/01 02:51:32 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /etc/v2raya/config.json
7月 01 02:51:34 dwight v2raya[387]: main: failed to create server > github.com/v2fly/v2ray-core/v4/proxy/vless/outbound: failed to parse server spec > github.com/v2fly/v2ray-core/v4/proxy/vless: failed to parse ID > invalid UUID: none.blue
7月 01 02:51:47 dwight v2raya[387]: 2021/07/01 02:51:47 connect.go:101: Connect: done
7月 01 02:51:47 dwight v2raya[387]: 2021/07/01 02:51:47 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information

**Comment by mzz2017** [comment]
确实有这个问题，近期修复一下

**Comment by mzz2017** [comment]
@iwrwr 已提交commit，如在archlinux使用，尝试v2raya-git可体验unstable版本

**Comment by mzz2017** [comment]
已修复。见 https://github.com/v2rayA/v2rayA/releases/tag/v1.4.0
