### ISSUE TITLE
Wrong username or password

### ISSUE THREAD

**Issue by thegxi** [v2rayA/v2rayA#202]
### Version, approach of installation, operating system

docker install v2raya 

access 127.0.0.1:2017 tip wrong username or password

**Comment by mzz2017** [comment]
@TheGXi https://github.com/v2rayA/v2rayA/wiki/常见问题

**Comment by TheGXi** [comment]
I dont't have account

**Comment by TheGXi** [comment]
I don't have a account

**Comment by mzz2017** [comment]
@TheGXi The first time you open the website, it ask you to set up an account. And if you forget your account or password, refer to the link mentioned above.
