### ISSUE TITLE
关于支持ss-tproxy

### ISSUE THREAD

**Issue by qiujiangkun** [v2rayA/v2rayA#203]
### 您想提出的功能特性是否和现有问题相关？
目前v2raya和ss-tproxy兼容性不好，经常会出现奇怪的问题，大概和iptables有关系

https://github.com/zfl9/ss-tproxy/issues/192
https://github.com/zfl9/ss-tproxy/issues/185

### 功能特性内容
希望能够修复这些问题

**Comment by MarksonHon** [comment]
@qiujiangkun v2rayA 与 ss-tproxy 都是透明代理的软件欸，它们之间哪有兼容性啊，根本没法兼容好吧~~~

**Comment by qiujiangkun** [comment]
我比较喜欢v2rayA的图形界面，linux下好用的图形界面不多。如果v2rayA只开放端口，不尝试做透明代理，应该就兼容了

**Comment by cubercsl** [comment]
@qiujiangkun 那你关闭v2raya的全局透明代理功能就行了吧

**Comment by qiujiangkun** [comment]
> 那你关闭v2raya的全局透明代理功能就行了吧

遇到了一个奇怪的DNS问题，不知道是v2raya还是ss-tproxy的问题。
```
tail /var/log/dns2tcp.log 
2021-07-08 08:40:08 INF: [main] tcp remote addr: 8.8.8.8#53
2021-07-08 08:40:13 ERR: [tcp_recvmsg_cb] recv from 8.8.8.8#53: (2) No such file or directory
```
ss-tproxy试图走DNS over tcp，用ss lib-redir是可以的，但v2raya不行
只用v2raya也是可以的，curl -X socks5h://127.0.0.1:xxxx www.google.com也是可以的

**Comment by MarksonHon** [comment]
@qiujiangkun 你非要把两个透明代理软件一起用，，那就只能你自己搞定防火墙规则了~而且，不开启透明代理的情况下，v2rayA只有两个http入站，压根没法做透明代理或tun2socks

**Comment by qiujiangkun** [comment]
> 而且，不开启透明代理的情况下，v2rayA只有两个http入站，压根没法做透明代理或tun2socks

我经过测试还有一个socks5端口，curl直接指定socks5端口是可以的。难道这个socks5端口不支持ss-tproxy的流量？

**Comment by MarksonHon** [comment]
@qiujiangkun https://github.com/v2rayA/v2rayA/wiki/RoutingA

**Comment by qiujiangkun** [comment]
我的理解是
ss-tproxy处理了分流规则，然后将需要代理的流量转发到socks5上，socks5的规则设置为全部代理。v2raya默认的规则是全部代理吗？

**Comment by qiujiangkun** [comment]
我知道原因了，我需要一个支持透明代理的端口（在我另外的机器上是32345），而不是socks5端口。不知道v2raya能不能开放这样一个端口，但是不修改iptables

> # 另外，请确认6666端口是否是v2raya客户端提供的本地透明代理端口（一定要是透明代理端口）
> # 这个端口不能是socks5端口，socks5端口是无法透明代理的，需要配合ipt2socks/redsocks2进行转换
> proxy_tcpport='6666'    # ss/ssr/v2ray 等本机进程的 TCP 监听端口，该端口支持透明代理
> proxy_udpport='6666'    # ss/ssr/v2ray 等本机进程的 UDP 监听端口，该端口支持透明代理

**Comment by mzz2017** [comment]
@qiujiangkun 详见v2raya --v2ray-confdir参数或V2RAYA_V2RAY_CONFDIR环境变量

**Comment by mzz2017** [comment]
该 issue 由于没有长期回复将被关闭。
