### ISSUE TITLE
订阅链接中，用chacha20-ietf-poly1305的SS无法正确识别

### ISSUE THREAD

**Issue by pikakolendo02** [v2rayA/v2rayA#205]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
  1.3.3
2. What approach of installation do you install V2rayA?
  archlinuxcn
3. What is your operating system?
  arch linux

### Description

导入某个含不同加密方式的SS、SSR的订阅链接时，用chacha20-ietf-poly1305的SS在列表中“协议”显示为“SSR()”。
点击“连接”，无法连接，提示
```
failed to connect > github.com/v2rayA/v2rayA/core/v2ray: unsupported shadowsocks encryption method: chacha20-ietf-poly1305
```
用aes-128-cfb的SS识别为“SSR(origin)”，不过不影响使用。
手动导入该服务器的ss://地址，识别正常。

### Steps to reproduce

SUBSCRIPTION中导入某服务商提供的订阅链接；
显示协议不正确，点击“连接”出错。

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 ```
https://pastebin.ubuntu.com/p/Dy7YXhfbgf/

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

![图片](https://user-images.githubusercontent.com/15796641/125111774-e3aa8500-e118-11eb-891b-4aa901550b5b.png)
![图片](https://user-images.githubusercontent.com/15796641/125113033-a941e780-e11a-11eb-9b63-8574304505e1.png)
![图片](https://user-images.githubusercontent.com/15796641/125113199-ead29280-e11a-11eb-9171-3993afa72806.png)

**Comment by mzz2017** [comment]
@pikakolendo02 目前不支持aead加密的ssr

**Comment by mzz2017** [comment]
@pikakolendo02 我看了一下日志，你可能把clash订阅导入进来了，这是不支持的，你应该导入类似v2rayN的订阅

**Comment by pikakolendo02** [comment]
> @pikakolendo02 我看了一下日志，你可能把clash订阅导入进来了，这是不支持的，你应该导入类似v2rayN的订阅

这个服务商提供两个订阅，一个地址包含了ss和ssr，另一个是clash。导入clash订阅是顺便尝试的，并没有识别……

**Comment by mzz2017** [comment]
@pikakolendo02 ssr不支持aead的加密

**Comment by pikakolendo02** [comment]
> @pikakolendo02 ssr不支持aead的加密

我的意思是，用aead的那几个节点不是ssr，而是ss，但从订阅链接导入时认成了ssr
看了一下似乎是订阅链接问题，该订阅链接解密后确实全部是ssr://开头（尽管有些实际上应该是ss）
