### ISSUE TITLE
HTTPS代理

### ISSUE THREAD

**Issue by updater1234** [v2rayA/v2rayA#207]
### 您想提出的功能特性是否和现有问题相关？

既然v2ray支持HTTP代理，为什么V2RayA的Protocol里没有呢？希望后期可以将这个功能添加上，而且我感觉这也不难实现。

**Comment by MarksonHon** [comment]
@updater1234 如果你想要本地建立一个HTTPS代理服务器，那么我建议你搭配Nginx使用。

**Comment by mzz2017** [comment]
@updater1234 见wiki中的RoutingA一节，可以设置outbound出站

**Comment by mzz2017** [comment]
@updater1234 另外v2rayA也支持整合v2ray的配置，使用v2raya --v2ray-confdir

**Comment by updater1234** [comment]
OK
