### ISSUE TITLE
加密方式，协议不全

### ISSUE THREAD

**Issue by mengminggo** [v2rayA/v2rayA#21]
添加ssr配置时，协议，加密方式，混淆不全，

**Comment by mzz2017** [comment]
V2RayA基于v2ray-core，功能正在逐渐迭代。
V2RayA对ssr的支持依赖于[mzz2017/shadowsocksR](https://github.com/mzz2017/shadowsocksR)，欢迎感兴趣的人在上述项目中贡献PR。

**Comment by suhuaixing** [comment]
yeah..espescially aes-gcm family and chacha20-ietf-poly1305. But it doesn't matter.
V2RayA is so impressive that I wanna use it then I change my server to v2ray+ws+tls. Nice work! the best I can find, Web UI is much better than native ui or electron(too huge,core is only 10+M, GUI is 60M+? serious?). Maybe some Mac's native gui app can compete with this, but I use Linux, thanks!

**Comment by updater1234** [comment]
V2RayA既然是基于v2ray的，那怎么不支持AEAD呢?

**Comment by mzz2017** [comment]
> V2RayA既然是基于v2ray的，那怎么不支持AEAD呢?

你是说vmess/vless的aead还是ss的？

**Comment by updater1234** [comment]
> > V2RayA既然是基于v2ray的，那怎么不支持AEAD呢?
> 
> 你是说vmess/vless的aead还是ss的？

不管是vmess/vless还是ss，v2ray都支持

**Comment by mzz2017** [comment]
ss的aead问题以及simpleobfs在todolist，vmess和vless的aead通过aid设0来实现，客户端不关心。

**Comment by mzz2017** [comment]
[v1.1.0](https://github.com/v2rayA/v2rayA/releases/tag/v1.1.0)释出
+ 支持v2ray的xtls
+ 支持shadowsocks的simpleobfs混淆
+ 支持shadowsocks的AEAD加密方法
