### ISSUE TITLE
华芸nas运行报错

### ISSUE THREAD

**Issue by cgangit** [v2rayA/v2rayA#210]
github.com/v2rayA/v2rayA/core/v2ray: github.com/v2rayA/v2rayA/core/v2ray: not support transparent proxy:  > github.com/v2rayA/v2rayA/common/cmds: iptables-legacy -w 2 -t nat -A V2RAY -m mark --mark 0xff -j RETURN iptables v1.8.6 (legacy): Couldn't load match `mark':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
 > exit status 2

**Comment by mzz2017** [comment]
@cgangit nas跑不了透明代理的话，就在nas的系统设置里找找有没有系统代理可以用

**Comment by cgangit** [comment]
> @cgangit nas跑不了透明代理的话，就在nas的系统设置里找找有没有系统代理可以用

似乎没有，只能考虑虚拟机方案了
