### ISSUE TITLE
vless+tcp连接失败

### ISSUE THREAD

**Issue by iwrwr** [v2rayA/v2rayA#211]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
14.1
2. 你通过什么方式安装v2rayA
脚本
3. 你所使用的操作系统
debian10 最新

### 描述问题

在之前  vless+tcp协议 host问题修复了
**但是连接还是存在问题**  我在手机端测试连接成功
是在v2rayA上就会报错
failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start normally, check the log for more information

### 复现问题的步骤

在v2ray网页上导入
vless://none.blue@43.132.179.254:233?security=none&encryption=none&host=baidu.com&headerType=http&type=tcp#%E8%85%BE%E8%AE%AF
(目前有效  可以测试使用)

日志:
7月 21 16:19:53 dwight v2raya[5989]: 2021/07/21 16:19:53 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does 
7月 21 16:20:28 dwight v2raya[5989]: 2021/07/21 16:20:28 connect.go:51: Connect: begin
7月 21 16:20:29 dwight v2raya[5989]: 2021/07/21 16:20:29 status.go:47: /usr/local/bin/v2ray --config=/etc/v2raya/config.json
7月 21 16:20:30 dwight v2raya[5989]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64)
7月 21 16:20:30 dwight v2raya[5989]: A unified platform for anti-censorship.
7月 21 16:20:30 dwight v2raya[5989]: 2021/07/21 16:20:30 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /etc/v2raya/conf
7月 21 16:20:34 dwight v2raya[5989]: main: failed to create server > github.com/v2fly/v2ray-core/v4/proxy/vless/outbound: failed to parse se
7月 21 16:20:45 dwight v2raya[5989]: 2021/07/21 16:20:45 connect.go:85: Connect: done
7月 21 16:20:45 dwight v2raya[5989]: 2021/07/21 16:20:45 connection.go:21: github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does not start no
7月 21 16:20:45 dwight v2raya[5989]: 2021/07/21 16:20:45 [Warning] failed to connect > github.com/v2rayA/v2rayA/core/v2ray: v2ray-core does 
lines 1-20/20 (END)

**Comment by iwrwr** [comment]
另外建议新增一个强制连接不需要验证的功能

**Comment by mzz2017** [comment]
@iwrwr 你的密码是none.blue？

**Comment by mzz2017** [comment]
@iwrwr https://github.com/XTLS/Xray-core/issues/158，将该密码转换成对应的uuid，即可连接。下个版本我会进行自动转换。

**Comment by mzz2017** [comment]
v1.4.2已支持
