### ISSUE TITLE
无法启用透明代理

### ISSUE THREAD

**Issue by 1092888175** [v2rayA/v2rayA#212]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA 1.4.1

2. 你通过什么方式安装v2rayA archlinuxAUR

3. 你所使用的操作系统 archlinux

### 描述问题：

		
failed to connect > github.com/v2rayA/v2rayA/core/v2ray: not support "tproxy" mode of transparent proxy: github.com/v2rayA/v2rayA/common/cmds: iptables -w 2 -t mangle -N TP_OUT iptables v1.8.7 (legacy): can't initialize iptables table `mangle': Table does not exist (do you need to insmod?) Perhaps iptables or your kernel needs to be upgraded. > exit status 3
 使用redirect模式显示几乎一样的提示

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya_backend
 ```
```shell
# 此处贴入运行日志

-- Journal begins at Thu 2021-07-15 09:31:47 CST, ends at Sun 2021-07-25 15:10:07 CST. --
-- No entries --

```

**Comment by mzz2017** [comment]
@1092888175 重装iptables然后重启
