### ISSUE TITLE
Gui 中 SSR 的 Server Name 显示没有被解码

### ISSUE THREAD

**Issue by Liquid-Aristocracy** [v2rayA/v2rayA#213]
### 您想提出的功能特性是否和现有问题相关？

我使用的 ssr 节点名称在 gui 显示中没有被正确解码，显示的是 base64 编码后的节点名称，不方便选择节点。

### 功能特性内容

ssr 节点名称能够正确显示。

**Comment by mzz2017** [comment]
@Liquid-Aristocracy 给个例子

**Comment by Liquid-Aristocracy** [comment]
测试了一下没法复现，应该是特定节点的问题了
