### ISSUE TITLE
希望在ui中添加显示在当前路由规则下哪些域名是走的代理或者是直连(日志形式也可以)

### ISSUE THREAD

**Issue by dorthl** [v2rayA/v2rayA#214]
### 您想提出的功能特性是否和现有问题相关？

日常开发使用 有时会还原很多依赖 有些依赖访问过于缓慢 
```
021/07/30 16:22:47 [Info] [2407422447] proxy/http: request to Method [CONNECT] Host [github.com:443] with URL [//github.com:443]
2021/07/30 16:22:47 [Info] [2407422447] app/dispatcher: sniffed domain: github.com
2021/07/30 16:22:47 [Info] [2407422447] app/dispatcher: taking detour [proxy] for [tcp:github.com:443]
2021/07/30 16:22:47 [Info] [2407422447] common/mux: dispatching request to tcp:github.com:443
2021/07/30 16:22:47 172.16.2.1:53780 accepted //github.com:443 [proxy]
```
docker 环境 现在我只能使用 V2RAYA_VERBOSE 环境变量打印日志 但是它会把 v2rayA 混合打印 日志过多非常不方便
### 功能特性内容

希望的样子是 提供一种方法日志 只打印
2021/07/30 16:22:47 172.16.2.1:53780 accepted //github.com:443 [proxy] 这一行
更好的实现是 能在ui中体现 提供一个统计 能有访问的延迟情况就是最好的了

**Comment by mzz2017** [comment]
@dorthl 已记录，下个版本将支持

**Comment by mzz2017** [comment]
v1.4.2已支持

**Comment by dorthl** [comment]
@mzz2017  非常感谢 现在默认日志有打印路由信息了  但是我对ui中出现的多出站口很疑惑 不明白他的用处 以及在 feat: multiple outbounds, keep latency results, routing log 提交中所提到的 keep latency results 未发现显示的位置 
非常感谢解决了这个问题 如果 multiple outbounds, keep latency results 当前实现是预期的话 我会关掉这个 Issues

**Comment by mzz2017** [comment]
多出站是说可以连接多个节点，通过配合RoutingA，可以实现访问不同的站点走不同的服务器。

保存HTTP时延结果，当你HTTP测试完毕后，刷新页面或重启均不会使得结果丢失。

**Comment by dorthl** [comment]
@mzz2017 
了解了 如果能在每个出站中显示每个域名的统计时延就更好了 也能更好的配合 RoutingA 进行独立设置 包括 direct

非常感谢

**Comment by mzz2017** [comment]
@dorthl 不好意思，你可以详细讲述一下吗

**Comment by dorthl** [comment]
我不清楚v2ray-core是否支持这样的监控   其实我最开始提的功能实现就是这个想法
比如我在 RoutingA 中设置了 domain(domain:github.com)->proxy 
在日志中会出现 2021/08/03 13:46:51 192.168.3.251:50235 accepted //github.com:443 [proxy] 这一条
但是在实际访问中 github.com 可能即使是代理也访问不到 或者非常慢 如果是在浏览器中 使用 我的确可以直观的看到  github.com这个页面有没有加载出来以及速度
但是当我在使用git 在.gitconfig 配置代理时 当提交代码日志中也会出现
2021/08/03 13:46:51 192.168.3.251:50235 accepted //github.com:443 [proxy] 这一条
有些情况下是 提交非常非常慢 有时候是代理的问题 有时候又是因为vscode的问题
更多的是其他情况 如在使用npm .gradle composer 等甚至在shell环境中 鉴于...网络复杂的情况
所以我需求是能在v2rayA 的日志 或者界面或者等地方 能够了解到 我的访问是否是成功的 以及延迟情况 direct 或者 proxy 现在如果是多出口的话 在当前所用的出口 也就是 //github.com:443 [proxy]  是否连接成功 连接的时延情况 这样子

**Comment by mzz2017** [comment]
@dorthl 这个细粒度且定制化的日志的确非常有用，但目前这一块的日志完全依赖于core，v2rayA这边做不了太多工作

**Comment by dorthl** [comment]
@mzz2017 了解了 现在的实现已经非常好了  非常感谢
