### ISSUE TITLE
无法通过 Ubuntu apt 更新

### ISSUE THREAD

**Issue by tigerruanyifan** [v2rayA/v2rayA#216]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.4.1

2. 你通过什么方式安装v2rayA
ubuntu apt 源

3. 你所使用的操作系统
ubuntu 20.04

### 描述问题：

无法连接到 ubuntu 源, 运行 `sudo apt update` 时会出现 `Could not handshake: The TLS connection was non-properly terminated.`
之后也会说 `Error: The repository 'https://apt.v2raya.mzz.pub v2raya Release' does not have a Release file.`

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya_backend
 ```
```shell
# 此处贴入运行日志



```

**Comment by mzz2017** [comment]
@tigerruanyifan caddy OOM了，已恢复，谢谢

**Comment by YahuiAn** [comment]
记录一下我遇到的 apt 问题：

```shell
Err:6 https://raw.fastgit.org/v2rayA/v2raya-apt/master v2raya InRelease                                        
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F4FEBCD04F64D328
```
如果出现上面的错误，重新[添加一下公钥](https://github.com/v2rayA/v2rayA/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95#%E6%B7%BB%E5%8A%A0%E5%85%AC%E9%92%A5)就可以
