### ISSUE TITLE
注意，v1.4.2有GUI的不兼容更新

### ISSUE THREAD

**Issue by mzz2017** [v2rayA/v2rayA#217]
注意v1.4.2有GUI的不兼容更新，如果GUI和后端的版本不一致，如GUI为1.4.2，而后端为1.4.1，则有可能出现当前连接节点不显示选中的问题。

**Comment by CliffHan** [comment]
今天刚升到1.4.2，发现20170-20172的端口监听没了，跟这个Bug是同样原因吗？

**Comment by mzz2017** [comment]
@CliffHan 无法复现，请检查日志

**Comment by CliffHan** [comment]
@mzz2017 感谢提醒，刚看了看service启动log

Aug 07 09:36:26 cliff-830-g6 v2raya[148487]: 2021/08/07 09:36:26 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /etc/v2raya/config.json
Aug 07 09:36:26 cliff-830-g6 v2raya[148487]: main: failed to read config files: [/etc/v2raya/config.json] > github.com/v2fly/v2ray-core/v4/infra/conf: invalid field rule > github.com/v2fly/v2ray-core/v4/infra/conf: invalid IP: doh.pub > github.com/v2fly/v2ray-core/v4/infra/conf: unsupported address for router: doh.pub

看起来是配置中doh的问题？不太了解这种问题怎么处理，能给点建议吗？直接把doh.pub改IP？

**Comment by CliffHan** [comment]
config.json似乎是生成的
下面看起来应该是相关的一段：

{"type":"field","outboundTag":"direct","inboundTag":["dns"],"ip":["doh.pub"]}

**Comment by mzz2017** [comment]
@CliffHan 这个问题在1.4.3修复了

**Comment by CliffHan** [comment]
> @CliffHan 这个问题在1.4.3修复了

Thanks, 已更新，确认修复了

**Comment by ZGeek** [comment]
> 
> 
> 注意v1.4.2有GUI的不兼容更新，如果GUI和后端的版本不一致，如GUI为1.4.2，而后端为1.4.1，则有可能出现当前连接节点不显示选中的问题。

请问怎么更新GUI版本 我这边删除了重装都不行

**Comment by mzz2017** [comment]
@ZGeek 一般是随着版本一起更新，除非使用二进制版本或者demo站

**Comment by ZGeek** [comment]
> 
> 
> @ZGeek 一般是随着版本一起更新，除非使用二进制版本或者demo站

你好 我这边解决了 是因为我使用了nginx 需要清空nginx缓存才可以 清空nginx缓存的方式为 网站域名/purge

**Comment by mzz2017** [comment]
@ZGeek 尝试强制刷新网页

**Comment by mzz2017** [comment]
@ZGeek 👍

**Comment by xuxuMaster** [comment]
> > @ZGeek 一般是随着版本一起更新，除非使用二进制版本或者demo站
> 
> 你好 我这边解决了 是因为我使用了nginx 需要清空nginx缓存才可以 清空nginx缓存的方式为 网站域名/purge

您好，可以学习一下您的nginx配置吗
