### ISSUE TITLE
降低分发成本增加易用性, 将 web gui 直接嵌入到可执行文件中

### ISSUE THREAD

**Issue by feitian124** [v2rayA/v2rayA#222]
go 1.16 有一个新特性 `embed`, 可以将 web 应用直接嵌入到 go 执行文件中,
大大降低分发和使用成本, 现在 `https://v.mzz.pub/` 等2个域名也偶尔被墙了

我已经做过研究, vue, react 均成功, 可参见 https://github.com/feitian124/go-starter
如果需要, 我可以提一个 pr, 谢谢.

**Comment by cubercsl** [comment]
It has been implemented in https://github.com/v2rayA/v2rayA/commit/3ee9e1563c3fc72242a3cfa5124d850682e1e3da .

**Comment by feitian124** [comment]
好的, 谢谢.

**Comment by feitian124** [comment]
网络问题和 #221 重复了, 关闭这个
