### ISSUE TITLE
v2raya 1.4.3-1 无法使用ssr节点

### ISSUE THREAD

**Issue by Disen-Shaw** [v2rayA/v2rayA#223]
### 版本、安装方式、系统
我使用的操作系统： Arch Linux x86_64 
安装方式：下载archlinuxcn的软件源
当前使用版本为1.4.1-1(已回滚)，出现问题的版本为1.4.3-1

1. 你在使用什么版本的v2rayA
当前使用版本为1.4.1-1(已回滚)

2. 你通过什么方式安装v2rayA
网上查询

3. 你所使用的操作系统
Arch Linux x86_64

### 描述问题
在执行更新命令后的一段时间里还可以联网使用(这段时间我没有浏览外网，所以不知道是否可以浏览外网)，之后突然关机重启，之后我所有的节点都显示为异常NOSTATE，非网络节点的问题，相同节点的其他设备可以使用并浏览外网。在执行回滚操作后问题解除。

### 复现问题的步骤
更新之后出现的问题

###############################################################

Aug 10 05:27:35 archlinux v2raya[4931]: 2021/08/10 05:27:35 10.17.37.6:44656 accepted tcp:34.211.187.119:443 [proxy]
Aug 10 05:27:41 archlinux v2raya[4931]: 2021/08/10 05:27:41 10.17.37.6:48202 accepted tcp:117.167.125.216:443 [direct]
Aug 10 05:27:41 archlinux v2raya[4931]: 2021/08/10 05:27:41 10.17.37.6:32882 accepted tcp:202.141.176.110:443 [direct]
Aug 10 05:28:57 archlinux v2raya[4931]: 2021/08/10 05:28:57 10.17.37.6:46228 accepted tcp:117.167.125.215:443 [direct]
Aug 10 05:28:57 archlinux v2raya[4931]: 2021/08/10 05:28:57 10.17.37.6:32886 accepted tcp:202.141.176.110:443 [direct]
Aug 10 05:29:20 archlinux v2raya[4931]: 2021/08/10 05:29:20 10.17.37.6:55008 accepted tcp:49.12.124.107:443 [proxy]
Aug 10 05:29:52 archlinux v2raya[463]: Quitting...
Aug 10 05:29:52 archlinux systemd[1]: Stopping v2rayA Service...
Aug 10 05:29:52 archlinux systemd[1]: v2raya.service: Deactivated successfully.
Aug 10 05:29:52 archlinux systemd[1]: Stopped v2rayA Service.
Aug 10 05:29:52 archlinux systemd[1]: v2raya.service: Consumed 2min 21.644s CPU time.
-- Boot ee4b5839b7564b409622499947b06705 --
Aug 10 05:30:07 archlinux systemd[1]: Started v2rayA Service.
Aug 10 05:30:07 archlinux v2raya[460]: 2021/08/10 05:30:07 pre.go:256: [info] waiting for network connected
Aug 10 05:30:12 archlinux v2raya[460]: 2021/08/10 05:30:12 pre.go:256: [info] waiting for network connected
Aug 10 05:30:17 archlinux v2raya[460]: 2021/08/10 05:30:17 pre.go:259: [info] network is connected
Aug 10 05:30:17 archlinux v2raya[460]: V2RayLocationAsset is /usr/share/v2ray
Aug 10 05:30:17 archlinux v2raya[460]: V2Ray binary is /usr/bin/v2ray
Aug 10 05:30:17 archlinux v2raya[460]: v2rayA working directory is /
Aug 10 05:30:17 archlinux v2raya[460]: Version: 1.4.1
Aug 10 05:30:17 archlinux v2raya[460]: Starting...
Aug 10 05:30:17 archlinux v2raya[460]: 2021/08/10 05:30:17 connect.go:51: Connect: begin
Aug 10 05:30:18 archlinux v2raya[460]: 2021/08/10 05:30:18 status.go:47: /usr/bin/v2ray --config=/etc/v2raya/config.json
Aug 10 05:30:18 archlinux v2raya[1208]: V2Ray 4.40.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.5 linux/amd64)
Aug 10 05:30:18 archlinux v2raya[1208]: A unified platform for anti-censorship.
Aug 10 05:30:18 archlinux v2raya[1208]: 2021/08/10 05:30:18 [Info] main/jsonem: Reading config: /etc/v2raya/config.json
Aug 10 05:30:18 archlinux v2raya[1208]: 2021/08/10 05:30:18 [Warning] V2Ray 4.40.1 started
Aug 10 05:30:19 archlinux v2raya[460]: 2021/08/10 05:30:19 pre.go:277: Failed to update PAC file: github.com/v2rayA/v2rayA/core/v2ray/asset/gfwlist: latest version is 2021-08-04. GFWList is up to date
Aug 10 05:30:19 archlinux v2raya[460]: 2021/08/10 05:30:19 connect.go:90: Connect: done
Aug 10 05:30:19 archlinux v2raya[460]: v2rayA is listening at http://127.0.0.1:2017
Aug 10 05:30:19 archlinux v2raya[460]: v2rayA is listening at http://10.17.37.6:2017
Aug 10 05:30:19 archlinux v2raya[460]: v2rayA is listening at http://[::1]:2017
Aug 10 05:30:19 archlinux v2raya[460]: v2rayA is listening at http://[fe80::576d:6206:df4c:1ab6]:2017
Aug 10 05:30:35 archlinux v2raya[460]: 2021/08/10 05:30:35 connect.go:51: Connect: begin
Aug 10 05:30:35 archlinux v2raya[460]: 2021/08/10 05:30:35 status.go:47: /usr/bin/v2ray --config=/etc/v2raya/config.json
Aug 10 05:30:35 archlinux v2raya[1448]: V2Ray 4.40.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.5 linux/amd64)
Aug 10 05:30:35 archlinux v2raya[1448]: A unified platform for anti-censorship.
Aug 10 05:30:35 archlinux v2raya[1448]: 2021/08/10 05:30:35 [Info] main/jsonem: Reading config: /etc/v2raya/config.json
Aug 10 05:30:35 archlinux v2raya[1448]: 2021/08/10 05:30:35 [Warning] V2Ray 4.40.1 started
Aug 10 05:30:37 archlinux v2raya[460]: 2021/08/10 05:30:37 connect.go:90: Connect: done
Aug 10 05:30:38 archlinux v2raya[460]: 2021/08/10 05:30:38 status.go:47: /usr/bin/v2ray --config=/etc/v2raya/config.json
Aug 10 05:30:38 archlinux v2raya[1552]: V2Ray 4.40.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.5 linux/amd64)
Aug 10 05:30:38 archlinux v2raya[1552]: A unified platform for anti-censorship.
Aug 10 05:30:38 archlinux v2raya[1552]: 2021/08/10 05:30:38 [Info] main/jsonem: Reading config: /etc/v2raya/config.json
Aug 10 05:30:39 archlinux v2raya[1552]: 2021/08/10 05:30:39 [Warning] V2Ray 4.40.1 started
Aug 10 05:30:40 archlinux v2raya[460]: 2021/08/10 05:30:40 status.go:47: /usr/bin/v2ray --config=/etc/v2raya/config.json
Aug 10 05:30:40 archlinux v2raya[1607]: V2Ray 4.40.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.5 linux/amd64)
Aug 10 05:30:40 archlinux v2raya[1607]: A unified platform for anti-censorship.
Aug 10 05:30:40 archlinux v2raya[1607]: 2021/08/10 05:30:40 [Info] main/jsonem: Reading config: /etc/v2raya/config.json
Aug 10 05:30:40 archlinux v2raya[1607]: 2021/08/10 05:30:40 [Warning] V2Ray 4.40.1 started

############################################################### 

### v2rayA设置以及相关截图
就是显示节点异常，并且无法连接外网，没有其他的问题，因此没留截图。

**Comment by mzz2017** [comment]
这是一个已知问题，请先退回1.4.1

**Comment by mzz2017** [comment]
使用v1.4.4

**Comment by Disen-Shaw** [comment]
好的，感谢您的回复！
