### ISSUE TITLE
[BUG] 1.4.4 订阅显示更新成功 列表为空 数目为0

### ISSUE THREAD

**Issue by 0x012FA733** [v2rayA/v2rayA#231]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA: 1.4.4

2. 你通过什么方式安装v2rayA: AUR

3. 你所使用的操作系统: Manjaro (Arch Linux)

### 描述问题：

由 1.4.3 更新到 1.4.4 以后，订阅列表突然被清空，更新订阅列表显示成功，但列表依旧为空，节点数目为0
同样的订阅链接在 v2rayNG 上面可以成功添加和更新订阅列表
回退到 1.4.3 以后依旧无法订阅，怀疑是 GUI 出了点问题？

**Comment by MarksonHon** [comment]
@0x012FA733 <https://t.me/v2raya_cn> 进群聊

**Comment by mzz2017** [comment]
截图看看

**Comment by 0x012FA733** [comment]
![image](https://user-images.githubusercontent.com/49284128/130768760-e9b479c1-e71a-494e-8bad-738bf731b8d5.png)

**Comment by mzz2017** [comment]
@0x012FA733 看看日志

**Comment by 0x012FA733** [comment]
我应该怎样找到 GUI 的日志文件呢？

**Comment by mzz2017** [comment]
@0x012FA733 journalctl -u v2raya | tail -n 30

**Comment by 0x012FA733** [comment]
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:       <div class="cf-section cf-wrapper"> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <div class="cf-section cf-wrapper">
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:         <div class="cf-columns two"> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <div class="cf-columns two">
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:           <div class="cf-column"> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <div class="cf-column">
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:             <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:             <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:           </div> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: </div>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:           <div class="cf-column"> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <div class="cf-column">
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:             <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:             <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:             <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:           </div> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: </div>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:         </div> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: </div>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:       </div> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: </div>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:       <a href="https://tempestsw.com/nightingalesguilt.php?asp=86"></a> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <a href="https://tempestsw.com/nightingalesguilt.php?asp=86"></a>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:       <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300"> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:   <p class="text-13"> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <p class="text-13">
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:     <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">6843ebca797327d2</strong></span> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">6843ebca797327d2</strong></span>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:     <span class="cf-footer-separator sm:hidden">&bull;</span> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <span class="cf-footer-separator sm:hidden">&bull;</span>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:     <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 223.74.78.86</span> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 223.74.78.86</span>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:     <span class="cf-footer-separator sm:hidden">&bull;</span> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <span class="cf-footer-separator sm:hidden">&bull;</span>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:     <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:   </p> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: </p>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91: </div> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: </div>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:     </div> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: </div>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:   </div> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: </div>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:   <script type="text/javascript"> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: <script type="text/javascript">
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91:   window._cf_translation = {}; github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: window._cf_translation = {};
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91: </script> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: </script>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91: </body> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: </body>
Aug 25 17:51:18 H v2raya[48184]: 2021/08/25 17:51:18 subscription.go:91: </html> github.com/v2rayA/v2rayA/server/service: not supported protocol. we only support ss, ssr and vmess now: </html>

**Comment by mzz2017** [comment]
这不是就清楚了，你走代理拉订阅结果订阅放在cf上开了防ddos模式

**Comment by 0x012FA733** [comment]
换个节点就好了 😞 打扰了
