### ISSUE TITLE
透明代理实现方式设置为tproxy时，出方向端口白名单设置无效

### ISSUE THREAD

**Issue by junmoxiao** [v2rayA/v2rayA#238]
rt，保存并应用后/etc/v2raya/config.json里面并没有保存设置。  

另外我配置这个主要是由于开启了透明代理后，无法连接ssh，  
会提示 kex_exchange_identification: Connection closed by remote host    

在mac上用clashx时开启增强模式也有这个问题，但是配置忽略列表~/.config/clash/proxyIgnoreList.plist ，  把ssh服务器地址加到忽略列表就可以了。v2raya怎么配置呢？

**Comment by ajian2002** [comment]
git clone ssh链接时也会遇到这个问题,设置22端口直连之后,国内访问速度很慢,v2raya有没有解决办法
