### ISSUE TITLE
v2ray vless 下的 gRPC 协议中的 alterID 不是必填项

### ISSUE THREAD

**Issue by orangejx** [v2rayA/v2rayA#242]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
`1.5.1`
2. What approach of installation do you install V2rayA?
`docker`
3. What is your operating system?
`linux`

### Description

v2ray vless 下的 `gRPC` 协议中的 `alterID` 不是必填项, 刚刚手动填进去的时候发现是必填项, 审查元素把必填项的的标记去掉, 还是会填入一个默认值`1`. 期待老板们在下个 版本中修复

**Comment by mzz2017** [comment]
@orangejx 好的谢谢

**Comment by mzz2017** [comment]
我检查了一下vless下不会显示alterid，请问你是怎么看到的呢
