### ISSUE TITLE
v2fly balance strategy 支持 leastPing, random ,  v2rayA 有对应的配置吗 ? 

### ISSUE THREAD

**Issue by daodaovps** [v2rayA/v2rayA#243]
v2fly balance strategy 支持 leastPing, random ,  v2rayA 有对应的配置吗 ?

**Comment by mzz2017** [comment]
@daodaovps 目前只支持leastping

**Comment by BladPit** [comment]
@mzz2017 
大佬，我是docker安装的，观察了一下v2rayA的config.json文件，似乎在未启动v2rayA服务时，配置文件的内容有很多数字（疑似端口）填充的部分，如rule，tag之类。但一旦启动了服务，又会每次按照软件配置的规则重新修改config.json内容，使其能对应上配置。
请问这么设置的目的是什么呢？似乎直接保存之前生效的配置就可以了

**Comment by mzz2017** [comment]
@BladPit 第一个是http测时延的配置

**Comment by wind315** [comment]
> 
我也需要具体配置方式，自己测试了一下，如果按如下配置就能访问
{
    ...
    "balancers":[{
                "tag":"balancer",
                "selector":["agent"],
        	"strategy":{
	            "type":"leastPing"
	        }
    ...
    "observatory":{
	    "subjectSelector":["agent"],
	    "probeInterval":"10m"
    }
}
同样的，只修改一个地方如下：
{
    ...
    "balancers":[{
                "tag":"balancer",
                "selector":["agent"],
        	"strategy":{
	            "type":"leastPing"
	        }
    ...
    "observatory":{
	    "subjectSelector":["agent"],
            "probeURL":"www.google.com", //增加检测的地址
	    "probeInterval":"10m"
    }
}
只是增加了一个检测的地址就一直在direct不进行其他agent的代理访问，不知何故？
