### ISSUE TITLE
安装v2raya后，xDroid不能联网了

### ISSUE THREAD

**Issue by mwmb2** [v2rayA/v2rayA#253]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.2
2. 你通过什么方式安装v2rayA
github下载deb包，手动安装
3. 你所使用的操作系统
Ubuntu 21.04

### 描述问题：

系统中安装有xDroid（虚拟安卓系统，可以运行apk）。以前用qv2ray的时候，qv2ray不会影响到xDroid（xDroid里的程序可以访问一般的网站，但是Google啥的访问不了）。

卸载qv2ray，安装v2raya后，xDroid也受到了影响，所有程序都不能联网。

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志
-- Journal begins at Fri 2021-07-02 12:31:49 CST, ends at Mon 2021-09-13 13:53:30 CST. --
Sep 10 13:38:33 XXX systemd[1]: /etc/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Sep 10 13:38:33 XXX systemd[1]: /etc/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
Sep 10 13:38:33 XXX systemd[1]: /etc/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!

```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@mwmb2 用法是什么

**Comment by mwmb2** [comment]
![screen](https://user-images.githubusercontent.com/58910046/133033548-5861f2cf-e97d-4d38-9184-d55d460e920a.jpg)

是指配置截图吗？

**Comment by Eleanoa** [comment]
xdroid建立了一个虚拟网络，打开局域网共享可能可以解决
