### ISSUE TITLE
Kali Linux无法连接v2rayA

### ISSUE THREAD

**Issue by pure69per** [v2rayA/v2rayA#258]
1. 你在使用什么版本的v2rayA
最新版

2. 你通过什么方式安装v2rayA  使用debian系列的apt安装

3. 你所使用的操作系统  Kali Linux

### 描述问题

打开代理后无法正常连接国际互联网，curl google.com无法成功

日志

2021/09/17 11:01:02.914 [A] [main.go:24]  network is connected
2021/09/17 11:01:02.927 [A] [main.go:26]  V2RayLocationAsset is /usr/local/share/v2ray
2021/09/17 11:01:02.927 [A] [main.go:26]  V2Ray binary is /usr/local/bin/v2ray
2021/09/17 11:01:02.927 [A] [main.go:26]  v2rayA working directory is /home/zenyanle
2021/09/17 11:01:02.927 [A] [main.go:26]  v2rayA configuration directory is /home/zenyanle/.config/v2raya
2021/09/17 11:01:02.927 [A] [main.go:26]  OS: linux
2021/09/17 11:01:02.927 [A] [main.go:26]  Arch: amd64
2021/09/17 11:01:02.927 [A] [main.go:26]  Lite: true
2021/09/17 11:01:02.927 [A] [main.go:26]  Version: 1.5.3
2021/09/17 11:01:02.927 [A] [main.go:26]  Starting...
2021/09/17 11:01:02.928 [A] [index.go:131]  v2rayA is listening at http://127.0.0.1:2017
2021/09/17 11:01:02.928 [A] [index.go:131]  v2rayA is listening at http://192.168.0.103:2017
2021/09/17 11:01:02.929 [A] [index.go:131]  v2rayA is listening at http://[::1]:2017
2021/09/17 11:01:02.929 [A] [index.go:131]  v2rayA is listening at http://[fe80::20c:29ff:fe53:1762]:2017
2021/09/17 11:01:02.929 [E] [main.go:27]  run: listen tcp 0.0.0.0:2017: bind: address already in use

![image](https://user-images.githubusercontent.com/86388549/133717944-bb61f0aa-d31c-45a0-ae93-34adf660fb88.png)

每个代理方式均已尝试

**Comment by cubercsl** [comment]
@pure69per 2017端口被占用了

**Comment by mzz2017** [comment]
@pure69per https://v2raya.org/docs/prologue/quick-start/

**Comment by pure69per** [comment]
> @pure69per 2017端口被占用了

可是我可以正常访问localhost:2017

**Comment by pure69per** [comment]
> @pure69per https://v2raya.org/docs/prologue/quick-start/

没有仔细阅读文档，很抱歉打扰你们
