### ISSUE TITLE
请问docker下的geosite.dat等资源文件的路径在哪里

### ISSUE THREAD

**Issue by BladPit** [v2rayA/v2rayA#263]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.3
2. 你通过什么方式安装v2rayA
docker
3. 你所使用的操作系统
unraid 6.8.2版本

### 描述问题：

使用上目前没有什么问题，但有个疑惑，就是类似geosite.dat之类的预定义域名文件，到底是保存在哪里的。
我在/etc/v2raya 映射的持久化路径中没有看到这些资源文件，只有config.json 和一个 0.dat的文件（8MB大小）。
然后在容器里面find也没有找到geosite.dat或者geoip.dat，而目前看routingA的默认配置和举例里面，是明确引用了这2个预设文件的，而且经测试也是生效的，万一后面需要用到自定义的预设文件，比如 引导里面提到的 LoyalsoldierSite.dat，我该怎么放置这些文件？

**Comment by mzz2017** [comment]
@BladPit 见v2raya启动时的输出，例如：
2021/09/19 23:57:46.687 [A] [main.go:26]  V2RayLocationAsset is /usr/share/v2ray

**Comment by BladPit** [comment]
> @BladPit 见v2raya启动时的输出，例如：
> 2021/09/19 23:57:46.687 [A] [main.go:26] V2RayLocationAsset is /usr/share/v2ray

`021/09/20 00:43:10.838 [1;36m[A][0m [main.go:24] network is connected
2021/09/20 00:43:10.970 [1;36m[A][0m [main.go:26] V2RayLocationAsset is /usr/local/share/v2ray
2021/09/20 00:43:10.970 [1;36m[A][0m [main.go:26] V2Ray binary is /usr/bin/v2ray
2021/09/20 00:43:10.970 [1;36m[A][0m [main.go:26] v2rayA working directory is /root
2021/09/20 00:43:10.970 [1;36m[A][0m [main.go:26] v2rayA configuration directory is /etc/v2raya
2021/09/20 00:43:10.970 [1;36m[A][0m [main.go:26] OS: linux
2021/09/20 00:43:10.970 [1;36m[A][0m [main.go:26] Arch: amd64
2021/09/20 00:43:10.970 [1;36m[A][0m [main.go:26] Lite: false
2021/09/20 00:43:10.970 [1;36m[A][0m [main.go:26] Version: 1.5.3
`
哈哈哈，真是劳模啊，回复这么快。
感谢大佬回复，不好意思没仔细看启动日志，但既然有确实的路径，不知道为什么在容器内搜索不到。
因为unraid系统给docker分配的是img格式的虚拟磁盘，因此容器内的文件管理非常麻烦（不是很懂技术，所以搞不定），不知道这个/usr/local/share/v2ray的路径，我是否也可以直接通过path的参数映射为持久化的宿主机目录？这样方便自定义dat文件

另外顺便问下，设置里面的【更新GFWlist】，也是更新的这个资源路径下的geosite.dat文件吗，我如果映射后不影响这个自动更新的功能吧

**Comment by mzz2017** [comment]
@BladPit 可以的，是的。

**Comment by BladPit** [comment]
了解，非常感谢~

**Comment by BladPit** [comment]
不好意思，映射路径后发现了新的问题。
根据启动日志，把对应的资源路径映射到宿主机了，但发生了诡异的事情：
容器重新启动后，启动日志里发现资源文件路径发生变化了，自动换到了config的路径下面，导致我映射的路径并没有意义（虽然这样也可以在config映射路径里面进行管理了，但还是有点怪）

下面是映射资源路径前后2次启动日志关于V2RayLocationAsset 的内容（反复试过2次，都是这样，不是随机出现的）：

`2021/09/20 01:29:51.347  [main.go:26] V2RayLocationAsset is /usr/local/share/v2ray`

`2021/09/20 01:34:06.576  [main.go:26] V2RayLocationAsset is /etc/v2raya`

映射路径这一次的docker命令：
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='v2raya' --net='host' --privileged=true -e TZ="Asia/Shanghai" -e HOST_OS="Unraid" -v '/mnt/user/appdata/v2raya':'/etc/v2raya':'rw' -v '/mnt/user/appdata/v2raya/Asset':'/usr/local/share/v2ray':'rw' 'mzz2017/v2raya'`

**Comment by mzz2017** [comment]
```go
				if _, err := os.Stat(path.Join(c, "geoip.dat")); os.IsNotExist(err) {
					continue
				}
```

**Comment by BladPit** [comment]
抱歉，我不是开发人员，您发的这段代码不太能理解，是什么意思呢，是解释上面我这个问题的吗？

**Comment by mzz2017** [comment]
@BladPit 不包含geoip.dat的目录会被视为无效目录而略过

**Comment by BladPit** [comment]
了解了，多谢。
那么是不是判定为无效目录后，就会自动将资源目录切换为etc/v2raya(的映射目录)了，而不是用默认的/usr/local/share/v2ray

**Comment by mzz2017** [comment]
@BladPit 对啊，所以你就在宿主的对应目录先放好.dat文件

**Comment by BladPit** [comment]
了解。感谢解答。
不过提个建议，既然在资源目录上做了判定，为何逻辑不直接处理为【缺失geoip.dat则复制一份放在该目录下】，这样似乎更合理一些。毕竟目前的处理方式，虽然自动切换资源目录为配置目录etc/v2raya，但也同时自动复制（或者是下载？）了一份geoip.dat/geosite.dat文件

顺便问下，这个0.dat是什么文件呢，也是预定义域名吗，我看有8MB也挺大的，是对geo的补充吗

**Comment by mzz2017** [comment]
@BladPit 0.dat是v2raya的数据库，里面有你的全部服务器信息以及配置等。v2raya会检查所有备选的asset路径，包括v2ray/xray所默认支持的路径，所以并不是说v2rayA随便指定一个就可以的。
