### ISSUE TITLE
检测到v2ray-core可能未正确安装，请检查

### ISSUE THREAD

**Issue by Legend997** [v2rayA/v2rayA#265]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.3

2. 你通过什么方式安装v2rayA
dpkg

3. 你所使用的操作系统
kali linux

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by cubercsl** [comment]
@Legend997 not a bug, please check your log and v2ray install.

**Comment by Legend997** [comment]
> @Legend997 not a bug, please check your log and v2ray install.

where can I see my logs, terminal? but my terminal not log this error.

**Comment by Legend997** [comment]
sorry, I can see my logs, but my logs dont have this error, the web just tell me that not found v2ray-core

**Comment by Legend997** [comment]
我是菜逼
