### ISSUE TITLE
centos 8成功安装v2raya也能正常运行，但是设置中的“开启局域网共享”功能关闭后，导致系统本地的Nginx发布的web服务443等端口，宿主机无法访问。在未安装v2raya前是能够访问的。

### ISSUE THREAD

**Issue by l1TTss** [v2rayA/v2rayA#266]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.5.3版本
2. What approach of installation do you install V2rayA?
通过sh脚本安装xray，通过rpm安装v2raya。
3. What is your operating system?
centos 8

### Description

虚拟机centos 8中我装了Nginx跑了个web网站，通过443端口和9090端发布。在未安装v2raya前，我的宿主机能访问虚拟机发布的wab网站。但在安装v2raya后，只要设置不开启局域网共享，我发布的443端口和9090端口的web网站，我的宿主机就无法访问我发布的网站。在v2raya的设置中，选中”开启局域网共享“，我发布的443端口和9090端口的web网站，才能被我的宿主机访问。
不知道v2raya设置中”开启局域网共享“开启和关闭这个动作，对Linux系统做了那些变动。比如是针对防火墙进行了设置，还是Linux系统底层的listen监听IP做了更改，导致全局变动了。我的理解是，你们的”开启局域网共享“只对v2raya相关端口进行操作，而不应该影响Linux系统全局的监听啥的。

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# Paste running logs here
#  journalctl -u v2raya | tail -n 50
9月 22 13:34:21 xmirror v2raya[74497]: [A] [main.go:26]  Lite: false
9月 22 13:34:21 xmirror v2raya[74497]: [A] [main.go:26]  Version: 1.5.3
9月 22 13:34:21 xmirror v2raya[74497]: [A] [main.go:26]  Starting...
9月 22 13:34:21 xmirror v2raya[74497]: [I] [io.go:425]  Xray 1.4.3 (Xray, Penetrates Everything.) 7246001 (go1.17.1 linux/amd64)
9月 22 13:34:21 xmirror v2raya[74497]: [I] [io.go:425]  A unified platform for anti-censorship.
9月 22 13:34:21 xmirror v2raya[74497]: [I] [io.go:425]  [Info] infra/conf/serial: Reading config: /etc/v2raya/config.json
9月 22 13:34:22 xmirror v2raya[74497]: [I] [io.go:425]  127.0.0.1:60136 accepted tcp:127.0.0.1:0 [api-in_ipv4 -> api-out]
9月 22 13:34:22 xmirror v2raya[74497]: [A] [index.go:131]  v2rayA is listening at http://127.0.0.1:2017
9月 22 13:34:22 xmirror v2raya[74497]: [A] [index.go:131]  v2rayA is listening at http://192.168.217.131:2017
9月 22 13:34:22 xmirror v2raya[74497]: [A] [index.go:131]  v2rayA is listening at http://172.17.0.1:2017
9月 22 13:34:22 xmirror v2raya[74497]: [A] [index.go:131]  v2rayA is listening at http://[::1]:2017
9月 22 13:34:22 xmirror v2raya[74497]: [A] [index.go:131]  v2rayA is listening at http://[fe80::20c:29ff:febb:77c1]:2017
9月 22 13:34:22 xmirror v2raya[74497]: [A] [index.go:131]  v2rayA is listening at http://[fc00:92f1:2da0:ce73::1]:2017
9月 22 13:34:22 xmirror v2raya[74497]: [A] [index.go:131]  v2rayA is listening at http://[fe80::42:c0ff:fea7:162f]:2017
9月 22 13:34:22 xmirror v2raya[74497]: [A] [index.go:131]  v2rayA is listening at http://[fe80::1]:2017
9月 22 13:34:22 xmirror v2raya[74497]: [A] [index.go:131]  v2rayA is listening at http://[fe80::80ca:7ff:fee2:8d5a]:2017
9月 22 13:34:22 xmirror v2raya[74497]: [A] [index.go:131]  v2rayA is listening at http://[fe80::187d:d1ff:fe3c:1a52]:2017
9月 22 13:34:52 xmirror v2raya[74497]: [I] [io.go:425]  Xray 1.4.3 (Xray, Penetrates Everything.) 7246001 (go1.17.1 linux/amd64)
9月 22 13:34:52 xmirror v2raya[74497]: [I] [io.go:425]  A unified platform for anti-censorship.
9月 22 13:34:52 xmirror v2raya[74497]: [I] [io.go:425]  [Info] infra/conf/serial: Reading config: /etc/v2raya/config.json
9月 22 13:34:52 xmirror v2raya[74497]: [I] [io.go:425]  127.0.0.1:48890 accepted tcp:127.0.0.1:0 [api-in -> api-out]
9月 22 13:35:02 xmirror systemd[1]: Stopping v2rayA Service...
9月 22 13:35:02 xmirror v2raya[74497]: Quitting...
9月 22 13:35:06 xmirror systemd[1]: v2raya.service: Succeeded.
9月 22 13:35:06 xmirror systemd[1]: Stopped v2rayA Service.
9月 22 13:35:41 xmirror systemd[1]: Started v2rayA Service.
9月 22 13:35:41 xmirror v2raya[75546]: [A] [main.go:24]  network is connected
9月 22 13:35:41 xmirror v2raya[75546]: [A] [main.go:26]  V2RayLocationAsset is /usr/local/share/xray
9月 22 13:35:41 xmirror v2raya[75546]: [A] [main.go:26]  V2Ray binary is /usr/local/bin/xray
9月 22 13:35:41 xmirror v2raya[75546]: [A] [main.go:26]  v2rayA working directory is /
9月 22 13:35:41 xmirror v2raya[75546]: [A] [main.go:26]  v2rayA configuration directory is /etc/v2raya
9月 22 13:35:41 xmirror v2raya[75546]: [A] [main.go:26]  OS: linux
9月 22 13:35:41 xmirror v2raya[75546]: [A] [main.go:26]  Arch: amd64
9月 22 13:35:41 xmirror v2raya[75546]: [A] [main.go:26]  Lite: false
9月 22 13:35:41 xmirror v2raya[75546]: [A] [main.go:26]  Version: 1.5.3
9月 22 13:35:41 xmirror v2raya[75546]: [A] [main.go:26]  Starting...
9月 22 13:35:41 xmirror v2raya[75546]: [I] [io.go:425]  Xray 1.4.3 (Xray, Penetrates Everything.) 7246001 (go1.17.1 linux/amd64)
9月 22 13:35:41 xmirror v2raya[75546]: [I] [io.go:425]  A unified platform for anti-censorship.
9月 22 13:35:41 xmirror v2raya[75546]: [I] [io.go:425]  [Info] infra/conf/serial: Reading config: /etc/v2raya/config.json
9月 22 13:35:42 xmirror v2raya[75546]: [I] [io.go:425]  127.0.0.1:53916 accepted tcp:127.0.0.1:0 [api-in -> api-out]
9月 22 13:35:42 xmirror v2raya[75546]: [A] [index.go:131]  v2rayA is listening at http://127.0.0.1:2017
9月 22 13:35:42 xmirror v2raya[75546]: [A] [index.go:131]  v2rayA is listening at http://192.168.217.131:2017
9月 22 13:35:42 xmirror v2raya[75546]: [A] [index.go:131]  v2rayA is listening at http://172.17.0.1:2017
9月 22 13:35:42 xmirror v2raya[75546]: [A] [index.go:131]  v2rayA is listening at http://[::1]:2017
9月 22 13:35:42 xmirror v2raya[75546]: [A] [index.go:131]  v2rayA is listening at http://[fe80::20c:29ff:febb:77c1]:2017
9月 22 13:35:42 xmirror v2raya[75546]: [A] [index.go:131]  v2rayA is listening at http://[fc00:92f1:2da0:ce73::1]:2017
9月 22 13:35:42 xmirror v2raya[75546]: [A] [index.go:131]  v2rayA is listening at http://[fe80::42:c0ff:fea7:162f]:2017
9月 22 13:35:42 xmirror v2raya[75546]: [A] [index.go:131]  v2rayA is listening at http://[fe80::1]:2017
9月 22 13:35:42 xmirror v2raya[75546]: [A] [index.go:131]  v2rayA is listening at http://[fe80::80ca:7ff:fee2:8d5a]:2017
9月 22 13:35:42 xmirror v2raya[75546]: [A] [index.go:131]  v2rayA is listening at http://[fe80::187d:d1ff:fe3c:1a52]:2017


```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

<img width="948" alt="搜狗截图20210922133627" src="https://user-images.githubusercontent.com/60909700/134290052-383a8216-7642-431b-9ab6-32cf46a9a181.png">

**Comment by mzz2017** [comment]
还会开关ipforward

**Comment by l1TTss** [comment]
> 还会开关ipforward

这是因为v2raya设置“开启局域网共享”，操作了Linux系统底层的ipforward的开关的，导致非v2raya相关应用也无法访问了，能否升级v2raya只设置其v2raya相关服务端口是否开启局域网共享，而不影响系统其他服务的网络端口通信情况的。

**Comment by mzz2017** [comment]
@l1TTss 可以

**Comment by l1TTss** [comment]
> 还会开关ipforward

您好，大佬，请问v2raya怎么操作更改了Linux系统的ipforward影响了系统本地其他服务的网络端口网络可达的问题？还请明示，谢谢。还有我发现，好奇怪的是关闭了”开启局域网共享“，宿主机那端能够访问到v2raya的2017端口后台登入端，但是，我无法访问本地系统中我的Nginx发布的443和9090端口的服务。还请大佬们优化升级，开启局域网共享，这个功能只针对v2raya相关的服务和端口，不干扰系统中其他的服务的端口网络功能。用着v2raya导致用户本地的应用服务出问题，体验就可能不太好了。谢谢。

**Comment by mzz2017** [comment]
@l1TTss 虚拟机的网络如果用的nat模式等方式，关了ipforward会有影响。其他方面我不能直接解答你，需要在特定环境自己研究一下。

**Comment by l1TTss** [comment]
> @l1TTss 虚拟机的网络如果用的nat模式等方式，关了ipforward会有影响。其他方面我不能直接解答你，需要在特定环境自己研究一下。

好的，谢谢。
确实是简单粗暴，一棍子打死😂
[root@local ~]# cat /proc/sys/net/ipv4/ip_forward
1
[root@local ~]# cat /proc/sys/net/ipv4/ip_forward
0

**Comment by l1TTss** [comment]
> @l1TTss 虚拟机的网络如果用的nat模式等方式，关了ipforward会有影响。其他方面我不能直接解答你，需要在特定环境自己研究一下。

嗯嗯，虚拟机中装了v2raya，虚拟机中装了其他docker发布应用，然后配置关闭”开启局域网共享“所有docker中的应用都瘫痪。😢

**Comment by l1TTss** [comment]
> @l1TTss 虚拟机的网络如果用的nat模式等方式，关了ipforward会有影响。其他方面我不能直接解答你，需要在特定环境自己研究一下。

大佬，我有个建议可以参考Qv2ray的入站设置的方法实现，控制v2raya自己的监听地址，如监听0.0.0.0就相当于“开启局域网共享”，监听127.0.0.1就相当于关闭“开启局域网共享”，不过docker部署的话，可能监听0.0.0.0就相当于“开启局域网共享”，监听宿主机IP和127.0.0.1相当于关闭“开启局域网共享”。点击“开启局域网共享”按钮，v2raya是自动内部设置监听的IP地址切换，不用像Qv2raya那样用户自己去填写，127.0.0.1还是0.0.0.0的。这些监听的设置只针对v2raya这个应用生效，不是Linux系统全局生效。

![image](https://user-images.githubusercontent.com/60909700/134443481-a01860bd-536b-4496-937a-378d147dea60.png)

**Comment by MarksonHon** [comment]
@l1TTss WHAT ARE YOU TALKING ABOUT？AND WHAT'S QV2RAYA？

**Comment by l1TTss** [comment]
> @l1TTss 虚拟机的网络如果用的nat模式等方式，关了ipforward会有影响。其他方面我不能直接解答你，需要在特定环境自己研究一下。

大佬好，我有个建议可以参考Qv2ray的入站设置的方法实现，控制v2raya自己的监听地址，如监听0.0.0.0就相当于“开启局域网共享”，监听127.0.0.1就相当于关闭“开启局域网共享”，不过docker部署的话，可能监听0.0.0.0就相当于“开启局域网共享”，监听宿主机IP和127.0.0.1相当于关闭“开启局域网共享”。点击“开启局域网共享”按钮，v2raya是自动内部设置监听的IP地址切换，不用像Qv2ray那样用户自己去填写，127.0.0.1还是0.0.0.0的。这些监听的设置只针对v2raya这个应用生效，不是Linux系统全局生效。

![image](https://user-images.githubusercontent.com/60909700/134456290-dc7da2a1-8964-4e5b-8407-27a7d5eebd1c.png)

**Comment by l1TTss** [comment]
> @l1TTss WHAT ARE YOU TALKING ABOUT？AND WHAT'S QV2RAYA？

太多v2ray的项目了，很容易搞混，我打错名字了，Qv2raya应该是v2raya的，懂的都懂。

There are too many v2ray projects, it is easy to confuse, I mistyped the name, Qv2raya should be v2raya, understand everything.

**Comment by mzz2017** [comment]
This feature has been added.

You can replace your binary with the newer one from [Github Actions Artifact](https://github.com/v2rayA/v2rayA/actions/runs/1270390730), or just waiting for the next release.

Thanks.

**Comment by l1TTss** [comment]
> This feature has been added.
> 
> You can replace your binary with the newer one from [Github Actions Artifact](https://github.com/v2rayA/v2rayA/actions/runs/1270390730), or just wait for the next release.
> 
> Thanks.

Thank you for your hard work, I am waiting for you to release the new version of v2raya.

**Comment by l1TTss** [comment]
> This feature has been added.
> 
> You can replace your binary with the newer one from [Github Actions Artifact](https://github.com/v2rayA/v2rayA/actions/runs/1270390730), or just wait for the next release.
> 
> Thanks.

大佬，你好，能否告知，新版本中实现开启局域网共享和关闭开启局域网共享的功能的方法，是否是像Qv2ray那样监听IP的方法？是否像以前v2raya那样全局影响Linux网络功能导致影响本地系统其他应用的可用性？谢谢。

**Comment by cubercsl** [comment]
@l1TTss 分为两个功能："开启IP转发" 和 "开启端口分享"，端口分享与 Qv2ray 的 0.0.0.0 HTTP 入站功能类似。

**Comment by l1TTss** [comment]
> @l1TTss 分为两个功能："开启IP转发" 和 "开启端口分享"，端口分享与 Qv2ray 的 0.0.0.0 HTTP 入站功能类似。

好的，谢谢。

**Comment by mzz2017** [comment]
该 issue 将会关闭，因为该问题已在 v1.5.4 中修复。
