### ISSUE TITLE
导入shadowsocks节点失败，因密码含有非base64字符

### ISSUE THREAD

**Issue by t2015q** [v2rayA/v2rayA#273]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
Version: 1.5.3

2. 你通过什么方式安装v2rayA
 手动安装 deb 包

3. 你所使用的操作系统
Ubuntu 18.04

### 描述问题

shadowsocks密码设置成随机数，含有base64以外字符，比如“dX_0>:o-]:PMX_,U}v”。
当我手动导入节点时，出现 “illegal base64 data at input”，后面发现是密码的问题。
不知该问题能否解决？

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![无法导入base64格式的密码](https://user-images.githubusercontent.com/30385071/135705421-9e2ed703-3593-4d58-914d-368e0d987f33.png)

**Comment by mzz2017** [comment]
已修复于 https://github.com/v2rayA/v2rayA/commit/f088fc7319e3fba804eafd625be5c995864b8aef
使用 [Github Actions](https://github.com/v2rayA/v2rayA/actions/runs/1297651072) 中的二进制替换你的 v2raya

**Comment by malikshi** [comment]
> 已修复于 [f088fc7](https://github.com/v2rayA/v2rayA/commit/f088fc7319e3fba804eafd625be5c995864b8aef) 使用 [Github Actions](https://github.com/v2rayA/v2rayA/actions/runs/1297651072) 中的二进制替换你的 v2raya

For trojan too please?

**Comment by mzz2017** [comment]
@malikshi What is the problem of trojan?

**Comment by malikshi** [comment]
@mzz2017 I thought it have the same problem with the password with `:`, just tested it, and no error.

**Comment by t2015q** [comment]
替换了f088fc7中二进制文件后， v2raya可以正常记录shadwsocks的非base64字符。

不过还有一个问题：由于我订阅链接的内容含有base64编码过的shdowsocks链接，
更新订阅时，无法将shadowsocks节点更新进去，只能手动用shdowsocks链接导入。

不知程序是否不支持base64编码过的shadowsock，还是由于之前的原因程序无法支持非base64字符订阅转码？

**Comment by mzz2017** [comment]
@t2015q 我不太清楚你的订阅具体格式，怎么复现

**Comment by t2015q** [comment]
@mzz2017  感谢大佬热心帮助，我有点懒，不打算复现了，得花时间在别事情上。程序极大方便了在ubuntu翻墙的使用，我非常满意了，谢谢你们的辛苦付出，至于最后提到是不是问题，我还是放弃关心了，不好意思。

**Comment by mzz2017** [comment]
@t2015q 好的谢谢

**Comment by mzz2017** [comment]
@t2015q 请保留这个issue，等待其他人复现
