### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by chenmoaaaa** [v2rayA/v2rayA#274]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v1.5.4
2. 你通过什么方式安装v2rayA
windows手动下载安装包
3. 你所使用的操作系统
windows

### 描述问题：

第一次运行后，再次运行报错，删除v2rayA.exe和v2ray核心无效。
C:\Users\dragon>D:\v2rayA\v2raya.exe --lite --v2ray-bin 'D:\v2ray\v2ray.exe'
2021/10/07 16:37:49.896 [A] [main.go:25]  network is connected
2021/10/07 16:37:49 db.buildIndexes error: when build listIdx LRem err: index out of range

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![image](https://user-images.githubusercontent.com/33976355/136350631-184a3fd0-768e-4b37-8dd2-957b8cdf4768.png)

**Comment by mzz2017** [comment]
@chenmoaaaa 使用-c重新指定一个位置
