### ISSUE TITLE
Arch Linux 透明代理 受限的连接

### ISSUE THREAD

**Issue by KiteAB** [v2rayA/v2rayA#282]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

```bash
$ v2raya --version
1.5.4
```

2. 你通过什么方式安装v2rayA

ArchLinuxCN 源内的 v2rayA 稳定包 (与 AUR 同步)

3. 你所使用的操作系统

Arch Linux (5.10.73-1-lts, linux-lts)

### 描述问题：

我使用 KDE 作为我的桌面环境

当我开启透明代理后, KDE 提示我受限的连接 (指无法上网的网络)

但是实际上是可以正常上网的

(所以问题只是说这个黄叹号看着有点难受而已)

**Comment by mzz2017** [comment]
@KiteAB #184

**Comment by penewzh** [comment]
不知道你的正常了吗，我把特殊模式的fakedns关了之后就没有黄色感叹号了，也能ping通了
