### ISSUE TITLE
开启透明代理后，手机google play商店可以浏览，但无法下载

### ISSUE THREAD

**Issue by Ling128** [v2rayA/v2rayA#285]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.54
2. 你通过什么方式安装v2rayA
apt
3. 你所使用的操作系统
Linux raspberrypi 5.10.63-v7l+ 2021 armv7l GNU/Linux

### 描述问题：
在树莓派搭建v2raya开启透明代理，浏览网页正常
手机上google play可以搜索、浏览应用，但无法下载应用
在手机上用v2rayNG时，goolge play商店能正常下载应用

**Comment by erge6521** [comment]
应该是手机的问题，国产手机的话把谷歌商店所有数据清一遍从新登陆就能解决了，这是通病，不是哪个客户端的问题。如果用的原生带谷歌套间的手机基本不会出现这个问题（目前我没有发现这个问题）

**Comment by medivh-jay** [comment]
> 应该是手机的问题，国产手机的话把谷歌商店所有数据清一遍从新登陆就能解决了，这是通病，不是哪个客户端的问题。如果用的原生带谷歌套间的手机基本不会出现这个问题（目前我没有发现这个问题）

我也有这个问题，跟手机没关系，我用手机直接使用v2rayNg是可以直接下载的，但是使用WireGuard连到服务器使用服务器v2raya透明代理就不行了，即使改成tproxy也不行

**Comment by mzz2017** [comment]
为了**解决 sniffing 所引发的问题**，我决定更改 v2rayA 中 fakedns 的行为来解决相关问题。

测试版本已打包于 https://github.com/v2rayA/v2rayA/actions/runs/1510550893 ，请在 Github 登录后下载对应 CPU 架构文件替换你的当前 v2rayA 二进制文件。

在使用该测试版本情况下：

1. 将 DNS 防污染设为“关闭”以外的任意一项，以开启 FakeDNS 的选项。
2. 在特殊模式中选择 FakeDNS。

而后查看问题是否解决。

该版本的行为如下：
1. 对所有域名启用 FakeDNS。
2. 不使用 tls/http 嗅探（关键）。

FakeDNS 可能引发的问题：
1. 污染 dns 映射关系。如 ssh 的 known_hosts。
2. 污染 dns 缓存。在切换节点、保存设置、关闭 v2rayA 等情况下可能会导致部分网站暂时无法访问，待缓存刷新后生效。
3. 极少数会验证 IP 的应用会出现不可用的情况。

望周知。

**Comment by medivh-jay** [comment]
![Uploading SmartSelect_20211127-215439_Chrome.jpg…]()

好像还是没有起到作用

**Comment by medivh-jay** [comment]
![SmartSelect_20211127-215439_Chrome](https://user-images.githubusercontent.com/23169872/143684414-6d00bdea-6955-4a4c-bbca-f7948b18e161.jpg)

**Comment by mzz2017** [comment]
@medivh-jay 看一下 v2rayA 中的日志输出，是否有 198.18.0.xx 的字样

**Comment by medivh-jay** [comment]
![Screenshot_20211127-220545_Termux](https://user-images.githubusercontent.com/23169872/143684816-8b5e6251-2bf9-4bb2-8e55-6b2e2e64bfc3.png)

**Comment by medivh-jay** [comment]
有

**Comment by mzz2017** [comment]
@medivh-jay 好吧。或许不是 sniffing 的问题。

**Comment by medivh-jay** [comment]
在v2ray的sniff功能里边，对于非标准
http和https数据v2ray会无法正确sniff，会跟这个有关吗

**Comment by mzz2017** [comment]
@medivh-jay 需要验证到底是哪里的问题，才有办法解决

**Comment by medivh-jay** [comment]
@mzz2017 https://toutyrater.github.io/app/tproxy.html 这篇文章是否会有点帮助

**Comment by mzz2017** [comment]
@medivh-jay 这是基础教程

**Comment by smartcatboy** [comment]
有部分节点是不支持谷歌商店下载的，建议更换原生ip节点进行测试，排除ip因素

**Comment by medivh-jay** [comment]
好像跟v2raya无关，是规则使用大陆白名单模式会导致services.googleapis.cn等谷歌相关服务被DNS解析到国内IP，导致卡住，国内大部分DNS提供商和国外部分DNS提供商都会解析到大陆，ADGuardDNS会解析到国外IP，但因为域名好像不止一个，尝试在本地DNS重写到国外没能解决问题，尝试使用GFWList规则好像就能解决问题，但是不知道GFWList规则是否够全，因为单纯使用GFWList害怕国外什么网站突然无法打开而忘记了v2raya的设置又要找很久问题，这个问题貌似主要出现在国行安卓手机并且自带Google服务的版本，比如我这个三星S21+

**Comment by mzz2017** [comment]
@medivh-jay 可以使用RoutingA，将对应IP走代理

**Comment by medivh-jay** [comment]
@mzz2017 但是透明代理走不了这个，不过这个issue确实跟v2raya无关
