### ISSUE TITLE
连不上远程v2ray服务

### ISSUE THREAD

**Issue by gouez** [v2rayA/v2rayA#292]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v1.5.4
2. 你通过什么方式安装v2rayA

3. 你所使用的操作系统
深度操作系统

### 描述问题：

连接远程v2ray服务，提示"failed to connect: failed to connect: not found". 在mac下使用clashx客户端能正常使用

### v2rayA运行日志（Optional）：
2021/10/30 11:53:37.052 [W] [context.go:165]  PostConnection: failed to connect: not found
2021/10/30 11:53:37.052 [E] [connection.go:36]  failed to connect: failed to connect: not found
2021/10/30 11:54:59.533 [W] [context.go:165]  PostConnection: failed to connect: not found
2021/10/30 11:54:59.533 [E] [connection.go:36]  failed to connect: failed to connect: not found
2021/10/30 11:55:01.529 [W] [context.go:165]  PostConnection: failed to connect: not found
2021/10/30 11:55:01.529 [E] [connection.go:36]  failed to connect: failed to connect: not found
2021/10/30 11:55:08.753 [W] [context.go:165]  PostConnection: failed to connect: not found
2021/10/30 11:55:08.753 [E] [connection.go:36]  failed to connect: failed to connect: not found
2021/10/30 11:55:09.549 [W] [context.go:165]  PostConnection: failed to connect: not found
2021/10/30 11:55:09.549 [E] [connection.go:36]  failed to connect: failed to connect: not found
2021/10/30 11:57:30.063 [W] [context.go:165]  PostConnection: failed to connect: not found
2021/10/30 11:57:30.063 [E] [connection.go:36]  failed to connect: failed to connect: not found
2021/10/30 12:02:20.035 [W] [context.go:165]  PostConnection: failed to connect: not found
2021/10/30 12:02:20.035 [E] [connection.go:36]  failed to connect: failed to connect: not found
2021/10/30 12:03:21.579 [E] [import.go:22]  not found
2021/10/30 12:04:39.318 [W] [context.go:165]  PostConnection: failed to connect: not found
2021/10/30 12:04:39.319 [E] [connection.go:36]  failed to connect: failed to connect: not found
2021/10/30 13:00:29.216 [W] [context.go:165]  PostConnection: failed to connect: not found
2021/10/30 13:00:29.216 [E] [connection.go:36]  failed to connect: failed to connect: not found
2021/10/30 13:03:43.990 [W] [context.go:165]  PostConnection: failed to connect: not found
2021/10/30 13:03:43.990 [E] [connection.go:36]  failed to connect: failed to connect: not found
2021/10/30 13:03:47.909 [W] [context.go:165]  PostConnection: failed to connect: not found
2021/10/30 13:03:47.909 [E] [connection.go:36]  failed to connect: failed to connect: not found
2021/10/30 13:04:07.778 [W] [context.go:165]  PostConnection: failed to connect: not found

**Comment by mzz2017** [comment]
@gouez 你v2ray-core装了吗

**Comment by gouez** [comment]
> @gouez 你v2ray-core装了吗

本地也需要装v2ray-core吗？

**Comment by mzz2017** [comment]
@gouez v2raya.org   v2raya依赖于v2ray-core

**Comment by gouez** [comment]
可以了，感谢。@mzz2017
