### ISSUE TITLE
Which release binary  version should i download,while i want to install it to my raspberry model 3B+?

### ISSUE THREAD

**Issue by JerryLiew** [v2rayA/v2rayA#295]
the platform is arm32-v7a, but I can't find the corresponding binary on the release page. thanks a lot.

**Comment by mzz2017** [comment]
@JerryLiew https://v2raya.org

**Comment by mzz2017** [comment]
@JerryLiew If you just want the binary. Use arm one.

**Comment by JerryLiew** [comment]
thanks. the "armhf" version works well on my pi
