### ISSUE TITLE
VLESS-GRPC端口(带分流规则)用不了

### ISSUE THREAD

**Issue by zzy-ac** [v2rayA/v2rayA#296]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.4
2. 你通过什么方式安装v2rayA
添加官网给的源
3. 你所使用的操作系统
debian

### 描述问题

设置VLESS-GRPC端口时报错：VLESS-GPRC inbound depends on TLS cert, close the inbound or add cert by comand line argument --vless-grpc-inbound-cert-key or environment variable V2RAYA_VLESS_GRPC_INBOUND_CERT_KEY
完全不知道该怎么做

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by cubercsl** [comment]
@zzy-ac https://v2raya.org/docs/manual/variable-argument/

**Comment by mzz2017** [comment]
学习一下linux知识

**Comment by zzy-ac** [comment]
> 学习一下linux知识

您这话说的跟扯淡一样，我已经王service添加了你们标注的环境变量，也尝试了在启动参数后面添加报错中给出的所谓参数，结果依然没有改变，你们的文档也是语焉不详，希望可以得到一个比较清晰一点的说明

**Comment by mzz2017** [comment]
@zzy-ac 马上feat_v5要去掉了，你可以先不用这个功能

**Comment by mzz2017** [comment]
@zzy-ac 我没时间也没义务写，开源靠爱心，你有空写可以来写

**Comment by zzy-ac** [comment]
> @zzy-ac 马上feat_v5要去掉了，你可以先不用这个功能

嗯好

**Comment by KevinZonda** [comment]
> > 学习一下linux知识
> 
> 您这话说的跟扯淡一样，我已经王service添加了你们标注的环境变量，也尝试了在启动参数后面添加报错中给出的所谓参数，结果依然没有改变，你们的文档也是语焉不详，希望可以得到一个比较清晰一点的说明

Contribution is welcomed.  
PR is welcomed.  
Bullshit is not.
