### ISSUE TITLE
如何让v2rayA使用第三方的geoip.dat和geosite.dat

### ISSUE THREAD

**Issue by nukemiko** [v2rayA/v2rayA#298]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?

1.5.4

2. What approach of installation do you install V2rayA?

设置 -> 规则端口分流规则设置为RoutingA -> 配置

3. What is your operating system?

Arch Linux

**Comment by cubercsl** [comment]
@nukemiko domain(ext:"somefuckingfile.dat:somefuckingdomain")

**Comment by mzz2017** [comment]
@nukemiko v2rayA 启动时会输出 v2rayAsset 地址，将dat文件放进去后按 @cubercsl 的方法使用。另可参考 https://v2fly.org
