### ISSUE TITLE
v2rayA 提供的镜像脚本安装 V2Ray 时，Bash 无任何反应

### ISSUE THREAD

**Issue by Google-Skillshop** [v2rayA/v2rayA#300]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
最新版本
2. 你通过什么方式安装v2rayA
方法一：通过软件源安装
3. 你所使用的操作系统
Ubuntu Mate in VMware

### 描述问题：
安装 V2Ray 内核，通过 v2rayA 提供的镜像脚本，回车后没有任何反应。
现象：
1. 光标不闪烁
2. 等待5分钟没有任何反应
3. 网络正常

已经尝试的解决方案：
1. 先下载 sh
2. chmod 777 给权限
3. 本地运行，仍然没有任何反应

请大佬指点，多谢多谢。

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by KevinZonda** [comment]
我的天！这个问题太玄学了！

**Comment by Google-Skillshop** [comment]
Ubuntu Mint 下的三个系统都试了一遍，都不行。
1. 系统版本 20.2 LTS
2. 之前都可以的，今天新安装系统突然产生了这个问题
3. VMware的设置没有变
4. 今天安装的系统和之前的系统一样

准备下载个 xubuntu 试试

**Comment by KevinZonda** [comment]
真的牛逼

**Comment by mzz2017** [comment]
@Google-Skillshop 你看一下官方脚本是否可行

**Comment by MarksonHon** [comment]
@Google-Skillshop 我看不下去了，老铁啊，Ubuntu、Xubuntu、Kubuntu、Lubuntu、Ubuntu Kylin 与 Kubuntu 的底层是一样一样的，你怎么迁移都不一定管用。

**Comment by MarksonHon** [comment]
@Google-Skillshop https://t.me/v2raya_cn 进群聊吧

**Comment by Google-Skillshop** [comment]
😭😭😭
