### ISSUE TITLE
failed to start v2ray-core

### ISSUE THREAD

**Issue by chenxiex** [v2rayA/v2rayA#305]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2raya 1.5.4
2. 你通过什么方式安装v2rayA
软件源安装
v2ray-core使用的是
`curl -Ls https://mirrors.v2raya.org/go.sh | sudo bash`
3. 你所使用的操作系统
linux mint 20.2

### 描述问题：

可以正常打开v2raya网页，但是点击启动时提示：“failed to start v2ray-core: LocateServerRaw: ID or Sub exceed range”

**Comment by mzz2017** [comment]
@chenxiex duplicate with #184

**Comment by Jackfu915** [comment]
help me with this 
我是win11 1.5.8.1 之前用的好好的 
提几个在出现该问题前的情况
下载了cloudflare 但没有连接过
更新了下win系统
