### ISSUE TITLE
ubuntu20.04  docker安装不能出国留学

### ISSUE THREAD

**Issue by erge6521** [v2rayA/v2rayA#307]
版本：目前最新版
操作系统：ubuntu20.04
安装方式：官方docker镜像
出现的问题：不能出国。希望官方出一个实用教程。我docker安装完后是否需要配置ubuntu系统代理改为127.0.0.1：2017（改过但是并没有什么用），浏览器代理改为127.0.0.1：2017，并没有什么用。代理在windows上可用

**Comment by mzz2017** [comment]
@erge6521 2017是不对的，用20170（socks5），20171（http），20172（http带分流）

**Comment by mzz2017** [comment]
@erge6521 另外教程在 https://v2raya.org

**Comment by erge6521** [comment]
请问我配置完是否需要配置系统代理或者浏览器代理，还有一点就是如果我使用wifi连接网络是否只能配置浏览器代理才能留学

**Comment by erge6521** [comment]
> @erge6521 另外教程在 https://v2raya.org

请问我配置完是否需要配置系统代理或者浏览器代理，还有一点就是如果我使用wifi连接网络是否只能配置浏览器代理才能留学

**Comment by mzz2017** [comment]
@erge6521 上面不是写清楚了，配了透明代理就不用配浏览器代理系统代理，这是三个不同的方法

**Comment by erge6521** [comment]
> @erge6521 上面不是写清楚了，配了透明代理就不用配浏览器代理系统代理，这是三个不同的方法
好的，感谢您的回复
