### ISSUE TITLE
v2raya正常启动，系统也能登录，无法代理

### ISSUE THREAD

**Issue by Mcdull0921** [v2rayA/v2rayA#308]
选择某个`server`之后点击启动，提示这个`failed to start v2ray-core: failed: no server is selected. please select at least one server`错误。
不知道是否和端口有关，
在服务器上能查询到2017端口开放，其他端口20170，20171，20172均未启动。

**Comment by cubercsl** [comment]
@Mcdull0921 请 “选择”

**Comment by Mcdull0921** [comment]
> @Mcdull0921 请 “选择”，不是点复选框。

刚刚发现这个问题，好的，可以了，感谢回复！
