### ISSUE TITLE
vless(tcp+tls)代理失败

### ISSUE THREAD

**Issue by Mcdull0921** [v2rayA/v2rayA#309]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.4

2. 你通过什么方式安装v2rayA
apt

3. 你所使用的操作系统
树莓派armv7l

### 描述问题：

配置了server链接，但代理不生效，使用ping显示时延260ms，使用http显示`NOT STABLE`，但是该server链接使用`v2rayN`可以正常代理，是因为不兼容的原因吗？
本地使用`wget -e "https_proxy=127.0.0.1:20171" https://www.google.com`也无法成功
协议为`vless(tcp+tls)`

### v2rayA设置以及相关截图
![](https://user-images.githubusercontent.com/14017075/142032217-1b142aaa-1735-44c8-a52c-8bd845820ce3.jpg)
![](https://user-images.githubusercontent.com/14017075/142032256-a7582972-d9db-4d3e-bf11-0f04ca37fa1e.jpg)
![](https://user-images.githubusercontent.com/14017075/142032272-579c6e23-fa69-4083-991b-8c288f1c9ada.jpg)

2个结果，一个是通过本地v2raya代理，一个是通过v2rayn客户端代理：
![](https://user-images.githubusercontent.com/14017075/142032906-58719fd2-e963-41e8-b300-b767244e47e5.jpg)

**Comment by cubercsl** [comment]
@Mcdull0921 请补充 v2rayA 界面的配置和详细日志。

**Comment by Mcdull0921** [comment]
> @Mcdull0921 请补充 v2rayA 界面的配置和详细日志。
已补充配置截图

**Comment by MarksonHon** [comment]
@Mcdull0921 你的节点配置压根没放出来啊，这咋看问题在哪

**Comment by Mcdull0921** [comment]
> @Mcdull0921 你的节点配置压根没放出来啊，这咋看问题在哪

节点信息涉及隐私哇
* Protocol:VLESS
* Port:443
* Network:TCP
* TLS:tls
* Type:不伪装

目前能确定同样的节点信息在v2rayn下可以正常使用，在v2raya下，对于http和https请求，分别出现如下错误：
![](https://user-images.githubusercontent.com/14017075/142095199-c3471ca1-bf85-40a5-ae27-1a6b09f77554.jpg)

**Comment by mzz2017** [comment]
@Mcdull0921 麻烦贴一下服务端的日志

**Comment by Mcdull0921** [comment]
> @Mcdull0921 麻烦贴一下服务端的日志
![](https://user-images.githubusercontent.com/14017075/142125305-2a1b3e10-36e5-4d18-8503-e550eedb28b9.png)
我在网上找了个免费的vmess节点，可以成功，怀疑和我的vps不兼容，我搭的是vless

**Comment by mzz2017** [comment]
@Mcdull0921 可以尝试更换core为xray再试试

**Comment by Mcdull0921** [comment]
@mzz2017 请问怎么更换v2ray内核为xray？

**Comment by cubercsl** [comment]
@Mcdull0921 https://v2raya.org/docs/manual/use-other-core/ Please RTFM

**Comment by Mcdull0921** [comment]
@mzz2017 @cubercsl 
切换内核xray也不行，我把vps设置成xray站点再用xray内核也不行，不管设置什么都是`NOT STABLE`
![1](https://user-images.githubusercontent.com/14017075/142158129-2b60ca13-aeb6-4748-93cf-b718ca66d056.jpg)

![2](https://user-images.githubusercontent.com/14017075/142158133-07156f2d-047b-4413-a7aa-b3d89252b600.jpg)

**Comment by Mcdull0921** [comment]
有找到这个错误，不知是否有关，我的证书是用`Let's Encrypt`颁发的
![](https://user-images.githubusercontent.com/14017075/142176682-5ea1e3db-253b-4339-8d9d-02e25f87b3e7.jpg)

**Comment by mzz2017** [comment]
@Mcdull0921 或许和之前的根证书过期事件有关

**Comment by Mcdull0921** [comment]
@mzz2017 同样的链接，`v2rayn`可以，`v2raya`不行，2者都是使用`v2ray`内核，唯一区别是前者使用版本是`4.36`后者使用的是`4.43`，验证过我的证书还在有效期内，目前我已经无解了。

**Comment by mzz2017** [comment]
@Mcdull0921 问题在根证书，不是你的证书。另外，你可以看一下v2rayn的json配置。

**Comment by Mcdull0921** [comment]
@mzz2017 确实是根证书问题，已解决，感谢大佬！

**Comment by ftmis** [comment]
我也遇到这个问题了，请问具体的解决方法？

**Comment by cubercsl** [comment]
@ftmis 根证书过期了，升级 ca-certificates

**Comment by ftmis** [comment]
> @ftmis 根证书过期了，升级 ca-certificates

要怎么升级呢？我网上搜了几个方法都不行。

**Comment by Carnia** [comment]
还是碰到同样的问题了，macOS和 window下的docker都不行，mac的日志暂时没在手边，window下的日志如下：
![1](https://user-images.githubusercontent.com/22728375/189306566-b034172b-9e0e-4881-b155-4a800c159ba5.png)

问题是我有3个服务端，测试用到了grpc、vless+tls、vmess，在v2rayN下3个服务端的所有配置都正常使用。
一旦切换到v2raya，其中2个服务端的配置全部不行，1个服务端的配置全部可以。这3个服务端都是一样部署的ubuntu18，Https证书都是有效状态。

根证书升级是要如何升级？我自己尝试apt-get install ca-certificates --reinstall之后，测试结果也没有发生变化。

**Comment by mzz2017** [comment]
@Carnia v2raya 运行在 docker 中的？是什么 OS？

**Comment by Carnia** [comment]
> @Carniav2raya 运行在 docker 中的？是什么 OS？

找到原因了，我在服务端指定https证书的时候用的是域名证书而不是全链路证书（fullchain.cer），使用全链路证书之后就没问题了。
