### ISSUE TITLE
[BUG] lintian v2raya_0.6.5.1_amd64.deb 检查，报错信息比较多

### ISSUE THREAD

**Issue by atzlinux** [v2rayA/v2rayA#31]
**描述问题**

lintian v2raya_0.6.5.1_amd64.deb 

E: v2raya: unstripped-binary-or-object usr/bin/v2raya
W: v2raya: hardening-no-relro usr/bin/v2raya
W: v2raya: hardening-no-pie usr/bin/v2raya
W: v2raya: missing-depends-line
W: v2raya: syntax-error-in-debian-changelog line 5 "badly formatted trailer line"
W: v2raya: syntax-error-in-debian-changelog line 5 "found eof where expected more change data or trailer"
E: v2raya: no-copyright-file
E: v2raya: extended-description-is-empty
E: v2raya: maintainer-name-missing <travis@travis-job-5a110948-5ecc-4ea2-9f20-ca326f2a75f3>
E: v2raya: maintainer-address-malformed <travis@travis-job-5a110948-5ecc-4ea2-9f20-ca326f2a75f3>
W: v2raya: unknown-section default
W: v2raya: priority-extra-is-replaced-by-priority-optional
W: v2raya: non-standard-file-perm etc/systemd/system/v2raya.service 0664 != 0644
W: v2raya: non-standard-executable-perm usr/bin/v2raya 0775 != 0755
W: v2raya: package-contains-timestamped-gzip usr/share/doc/v2raya/changelog.gz
W: v2raya: binary-without-manpage usr/bin/v2raya
W: v2raya: possible-bashism-in-maintainer-script postinst:8 'echo -e'
W: v2raya: possible-bashism-in-maintainer-script postinst:9 'echo -e'
W: v2raya: possible-bashism-in-maintainer-script postinst:10 'echo -e'
W: v2raya: possible-bashism-in-maintainer-script ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: v2raya: maintainer-script-ignores-errors postinst
W: v2raya: maintainer-script-ignores-errors postrm
W: v2raya: maintainer-script-ignores-errors prerm
E: v2raya: systemd-service-file-outside-lib etc/systemd/system/v2raya.service
W: v2raya: maintainer-script-calls-systemctl postinst:7
W: v2raya: maintainer-script-calls-systemctl postinst:22
W: v2raya: maintainer-script-calls-systemctl postinst:23
W: v2raya: maintainer-script-calls-systemctl ... use --no-tag-display-limit to see all (or pipe to a file/program)

**预期结果**
希望制作的 deb 包，能够符合 Debian 的打包规范，lintian 质量检查，尽量少报错。

具体可以看下：

https://www.atzlinux.com/devel.htm

**Comment by mzz2017** [comment]
尝试了一下修复lintian的报错，很难搞定，我对打包这方面不是很在行，希望有经验的人可以提PR

**Comment by mzz2017** [comment]
I closed the issue due to no response for a long time. Feel free to reopen it if there is some progress. Thank you!
