### ISSUE TITLE
可以加个插件商店

### ISSUE THREAD

**Issue by Potterli20** [v2rayA/v2rayA#310]
### 您想提出的功能特性是否和现有问题相关？
现在有个bug就是挂着v2raya终端，直接关机，第二次开机就进不去。系统是fedora 35

### 功能特性内容
功能：就是插件中心，如gost 之类的。应该还可以加个流量监控之类？

**Comment by mzz2017** [comment]
@Potterli20 #267

**Comment by Potterli20** [comment]
> @Potterli20 #267

这个bug问题我已经知道

**Comment by MarksonHon** [comment]
@Potterli20 挂着 v2raya 终端是啥意思？直接就在终端里面运行 v2raya 而不用服务么？

**Comment by Potterli20** [comment]
> @Potterli20 挂着 v2raya 终端是啥意思？直接就在终端里面运行 v2raya 而不用服务么？

sudo v2raya
![2021-11-19 02-52-43 的屏幕截图](https://user-images.githubusercontent.com/28734349/142551243-a1bc5a83-d2e6-48d4-bfc5-316bade523ef.png)

**Comment by MarksonHon** [comment]
@Potterli20 建议用 systemd 服务管理 v2raya：
sudo systemctl start v2raya

**Comment by cubercsl** [comment]
@Potterli20 RTFM https://v2raya.org/docs/prologue/installation/redhat/

**Comment by Potterli20** [comment]
> @Potterli20 建议用 systemd 服务管理 v2raya： sudo systemctl start v2raya

我用sudo v2ray够用了

**Comment by Potterli20** [comment]
> @Potterli20 RTFM https://v2raya.org/docs/prologue/installation/redhat/

我早知道

**Comment by mzz2017** [comment]
@Potterli20 v5 版本会换数据库，或许问题会得到一定改善

**Comment by Potterli20** [comment]
> @Potterli20 v5 版本会换数据库，或许问题会得到一定改善

加个流量监控和插件中心，如gost 之类的？

**Comment by mzz2017** [comment]
@Potterli20 目前还不考虑 gost 等插件。流量监控欢迎 PR。

**Comment by Potterli20** [comment]
> @Potterli20 v5 版本会换数据库，或许问题会得到一定改善

现在restart v2raya 节点有重复
![火狐截图_2021-11-19T02-05-25 864Z](https://user-images.githubusercontent.com/28734349/142552401-9b48c9cf-fe35-40ec-b66b-731d03c8acc0.png)

**Comment by mzz2017** [comment]
@Potterli20 嗯，可能是数据库问题

**Comment by mzz2017** [comment]
使用v1.5.5以更换数据库
