### ISSUE TITLE
如何兼容ss节点

### ISSUE THREAD

**Issue by 13528943945** [v2rayA/v2rayA#312]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA   1.5.4
2. 你通过什么方式安装v2rayA    编译
3. 你所使用的操作系统         openwrt

### 描述问题：
只安装了xray-core及v2raya，能顺利使用v2ray及ssr节点，但使用ss节点时报错。是需要安装xray-plugin这个包吗?

**Comment by cubercsl** [comment]
@13528943945 报的错呢

**Comment by 13528943945** [comment]
failed to connect: failed to connect unsupported shadowsocks encryption method:chacha20-ietf

**Comment by mzz2017** [comment]
@13528943945 流加密已被淘汰。如想强行使用，改为 ssr，选用origin/plain即可兼容该ss节点。

**Comment by 13528943945** [comment]
> @13528943945 流加密已被淘汰。如想强行使用，改为 ssr，选用origin/plain即可兼容该ss节点。
web界面显示ss节点的协议为SS(chacha20-ietf+simple-obfs)

另外，解析ssr节点不出中文，显示6aaZ5riv5Lio5LiT57q/5LioSEdD5LioU1NS

**Comment by mzz2017** [comment]
@13528943945 你机场的问题

**Comment by mzz2017** [comment]
@13528943945 ssr无法使用simpleobfs

**Comment by 13528943945** [comment]
> @13528943945 你机场的问题

用passwall能正确显示中文节点名称

**Comment by mzz2017** [comment]
@13528943945 v2rayA 对老旧协议支持有限，抱歉

**Comment by 13528943945** [comment]
> @13528943945 v2rayA 对老旧协议支持有限，抱歉

多谢解答！！！
