### ISSUE TITLE
Failed to enable tproxy/redirect on Fedora 35

### ISSUE THREAD

**Issue by star-39** [v2rayA/v2rayA#324]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?

1.5.4-1.5.5

2. What approach of installation do you install V2rayA?

Docker image.

3. What is your operating system?

Fedora 35.
Linux rhel-hs 5.15.6-200.fc35.x86_64 #1 SMP Wed Dec 1 13:41:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Description

When transparency mode is enabled, no matter which implementation is being selected, v2raya always return an error and fail to start.
```
failed to start v2ray-core: not support "tproxy" mode of transparent proxy: ExecCommands: ip6tables -w 2 -t mangle -N TP_OUT ip6tables v1.8.7 (legacy): can't initialize ip6tables table `mangle': Table does not exist (do you need to insmod?) Perhaps ip6tables or your kernel needs to be upgraded. : exit status 3
```

### Steps to reproduce

Described above.

### Logs：
 ```
2021/12/09 11:27:05.383 [I] [io.go:425]  V2Ray 4.42.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.1 linux/amd64)
2021/12/09 11:27:05.383 [I] [io.go:425]  A unified platform for anti-censorship.
2021/12/09 11:27:05.383 [I] [io.go:425]  [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2021/12/09 11:27:06.984 [I] [io.go:425]  127.0.0.1:55706 accepted tcp:127.0.0.1:0 [api-out]
2021/12/09 11:27:07.126 [W] [transparent.go:42]  WriteTransparentProxyRules: not support "tproxy" mode of transparent proxy: ExecCommands: ip6tables -w 2 -t mangle -N TP_OUT ip6tables v1.8.7 (legacy): can't initialize ip6tables table `mangle': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
: exit status 3
2021/12/09 11:27:07.369 [E] [connection.go:88]  failed to start v2ray-core: not support "tproxy" mode of transparent proxy: ExecCommands: ip6tables -w 2 -t mangle -N TP_OUT ip6tables v1.8.7 (legacy): can't initialize ip6tables table `mangle': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
: exit status 3

```

### Notes

v2raya runs fine if not using the container from Docker Hub. (using the RPM package provided in Release)

I guess this problem is related to iptables to nftables transition since I saw some notes on documentation site relating to Debian11. 

RHEL8 also runs the container normally, no problem occured.

**Comment by mzz2017** [comment]
Thanks for your issue.

We cannot reproduce it on Archlinux.

We will try it on fedora 35 later.

**Comment by mzz2017** [comment]
Do you have solved it or have any new progress?

We cannot reproduce it.

**Comment by star-39** [comment]
Sorry for delayed reply.

I think I'm missing some dependencies, I tried on Fedora Desktop version and it works fine.

I'll continue investigation, closing issue.
