### ISSUE TITLE
IPv6访问

### ISSUE THREAD

**Issue by Delayless** [v2rayA/v2rayA#325]
ArchLinux物理机安装的v2raya-1.5.5-1

打开v2raya后无法通过ipv6访问服务器，关闭v2raya后可正常访问。

我搜索v2raya的issue看到好像1.3版本就支持了ipv6，请问下需要进行些什么样的设置才能正常访问ipv6呢？

**Comment by mzz2017** [comment]
@Delayless 看看日志是不是走代理了

**Comment by Delayless** [comment]
> @Delayless 看看日志是不是走代理了

对的，应该是，`journalctl`查看v2ray日志
```
Dec 10 20:53:00 delayless v2raya[446]: [I] [io.go:425]  [240e:382:xxxx:xxxx:xxxx:ea10:b7e7:xxxx]:38450 accepted tcp:[240e:xxxx:xxxx:xxxx:86f:f8c8:xxxx]:443 [香港]
```
前者是我本机ipv6地址，后者是我服务器的ipv6地址。
请问下怎么解决呢？暂时也没有ipv6访问外网的需求。

**Comment by mzz2017** [comment]
@Delayless 如果不想这么做，也可以写RoutingA使这个ip直连

**Comment by MarksonHon** [comment]
@Delayless curl -v www.qq.com

在开启透明代理的情况下，看下有没有回落到IPv4进行连接
PS：顺带说下你用的啥透明代理模式

**Comment by Delayless** [comment]
> @Delayless v2raya提供一个参数，对ipv6的支持控制： --ipv6-support string Optional values: auto, on, off. Make sure your IPv6 network works fine before you turn it on. (default "auto")
> 
> 对应环境变量是V2RAYA_IPV6_SUPPORT

解决了，谢谢大佬。
BTW，这个问题是我节点的问题吧？


多说两句给后面的人参考
```bash
# 修改自启服务文件
vim /usr/lib/systemd/system/v2raya.service
# 添加参数 --ipv6-support=off
ExecStart=/usr/bin/v2raya --log-disable-timestamp --ipv6-support=off
# 重启服务
systemctl reenable v2raya
systemctl restart v2raya
```

**Comment by cubercsl** [comment]
@Delayless 不建议直接修改 `/usr/lib/systemd/` 下的参数，因为这个修改会在 v2rayA 更新时被覆盖安装。

建议的方式是 在 `/etc/systemd` 下新建一个 `v2raya.service` 文件来永久覆盖提供的配置。

可以参考：https://note.cubercsl.site/notes/616cdf04

**Comment by Delayless** [comment]
> curl -v [www.qq.com](http://www.qq.com)

```
*   Trying 2402:4e00:1020:1404:0:9227:71a3:83d2:80...
* Connected to www.qq.com (2402:4e00:1020:1404:0:9227:71a3:83d2) port 80 (#0)
> GET / HTTP/1.1
> Host: www.qq.com
> User-Agent: curl/7.80.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: AkamaiGHost
< Content-Length: 0
< Location: https://www.qq.com/
< Date: Fri, 10 Dec 2021 13:20:16 GMT
< Connection: keep-alive
<
* Connection #0 to host www.qq.com left intact
```
![image](https://user-images.githubusercontent.com/42591058/145579879-a97988ae-3063-4654-9527-8a2bbd7dc21b.png)
特意把配置改回去试的，兄台，怎么说？

**Comment by Delayless** [comment]
> @Delayless 不建议直接修改 `/usr/lib/systemd/` 下的参数，因为这个修改会在 v2rayA 更新时被覆盖安装。
> 
> 建议的方式是 在 `/etc/systemd` 下新建一个 `v2raya.service` 文件来永久覆盖提供的配置。
> 
> 可以参考：https://note.cubercsl.site/notes/616cdf04

多谢提醒，我去看下。谢谢

**Comment by Delayless** [comment]
> > @Delayless 不建议直接修改 `/usr/lib/systemd/` 下的参数，因为这个修改会在 v2rayA 更新时被覆盖安装。
> > 建议的方式是 在 `/etc/systemd` 下新建一个 `v2raya.service` 文件来永久覆盖提供的配置。
> > 可以参考：https://note.cubercsl.site/notes/616cdf04
> 
> 多谢提醒，我去看下。谢谢

`sudo systemctl edit v2raya.service`
在这一行`### Lines below this comment will be discarded`上方(第三行之后开始添加)如下配置：
```bash
[Service]
ExecStart=
ExecStart=/usr/bin/v2raya --log-disable-timestamp --ipv6-support=off
```
重启服务，即可永久生效
`systemctl restart v2raya.service`
