### ISSUE TITLE
如何使局域网别的主机访问 xxxx:2017端口进行登录设置 

### ISSUE THREAD

**Issue by ifnk** [v2rayA/v2rayA#326]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
$ v2raya --version
1.5.5

2. 你通过什么方式安装v2rayA
docker 和 centos  rpm 方式安装 

3. 你所使用的操作系统
OS: CentOS Linux release 7.7.1908 (Core) x86_64

### 描述问题：

我想在 centos 服务器上安装v2raya(没有界面)，通过局域网别的机器浏览器访问来登录配置,  一开始 用 docker 安装 v2raya  ，然后 启动 后 
$ curl 10.168.1.6:2017 (10.168.1.6是 安装v2ray 的 主机 ip)
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><link rel="icon" href="favicon.ico"><title>v2rayA</title><link href="css/app.dc796682.css" rel="preload" as="style"><link href="css/chunk-vendors.01c3f78a.css" rel="preload" as="style"><link href="js/app.c3cf58cb.js" rel="preload" as="script"><link href="js/chunk-vendors.7f573ede.js" rel="preload" as="script"><link href="css/chunk-vendors.01c3f78a.css" rel="stylesheet"><link href="css/app.dc796682.css" rel="stylesheet"></head><body><noscript><strong>We're sorry but v2rayA-GUI doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div><script src="js/chunk-vendors.7f573ede.js"></script><script src="js/app.c3cf58cb.js"></script></body></html>% 
但是我在局域网别的机器上面 curl 10.168.1.6:2017 就不行了 ，浏览器也登录不上
$ curl 10.168.1.6:2017
curl: (52) Empty reply from server
我以为是docker 网络 的问题 ，于是 我不用docker 使用 帮助文件 的 centos rpm 方式 安装 

结果是 一样的 

我应该怎么设置 v2raya ,才能 让 局域网其他 机器  通过 xxxx(运行v2raya的机器ip):2017 登录配置 v2raya 呢？ 

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by Apophis3158** [comment]
请问你curl localhost:2017后提示
**We're sorry but v2rayA-GUI doesn't work properly without JavaScript enabled. Please enable it to continue.**
的问题解决了吗？
如何解决？
