### ISSUE TITLE
群晖补足iptables模块之后还是无法透明代理

### ISSUE THREAD

**Issue by sjtuross** [v2rayA/v2rayA#330]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.5.5

2. What approach of installation do you install V2rayA?
```
docker run -d \
  --restart=always \
  --privileged \
  --network=host \
  --name v2raya-mzz2017 \
  -e V2RAYA_ADDRESS=0.0.0.0:2017 \
  -v /lib/modules:/lib/modules \
  -v /etc/resolv.conf:/etc/resolv.conf \
  -v /volume1/docker/v2raya-config:/etc/v2raya \
  mzz2017/v2raya
```
3. What is your operating system?
Linux 3.10.105 #25426 SMP Mon Dec 14 18:47:46 CST 2020 x86_64 GNU/Linux synology_broadwell_3617xs

### Description

补足并加载了以下iptables模块之后，v2rayA透明代理可以正常启动，但是代理流量貌似无法返回，直连流量正常返回。
```
insmod /lib/modules/nfnetlink.ko
insmod /lib/modules/ip_set.ko
insmod /lib/modules/ip_set_hash_ip.ko
insmod /lib/modules/xt_set.ko
insmod /lib/modules/ip_set_hash_net.ko
insmod /lib/modules/xt_mark.ko
insmod /lib/modules/xt_connmark.ko
insmod /lib/modules/nf_tproxy_core.ko
insmod /lib/modules/xt_TPROXY.ko
```
```
root@DSM3:~# lsmod | grep xt_TPROXY
xt_TPROXY               4440  0 
nf_tproxy_core          1004  1 xt_TPROXY
nf_defrag_ipv6         22249  2 xt_TPROXY,nf_conntrack_ipv6
nf_defrag_ipv4          1211  2 xt_TPROXY,nf_conntrack_ipv4
x_tables               16229  20 ip6table_filter,xt_iprange,xt_mark,xt_recent,ip_tables,xt_tcpudp,ipt_MASQUERADE,xt_limit,xt_state,xt_conntrack,xt_LOG,xt_nat,xt_set,xt_multiport,iptable_filter,xt_TPROXY,xt_connmark,xt_REDIRECT,ip6_tables,xt_addrtype
ipv6                  302657  220 sit,cnic,rodsp_ep,nf_defrag_ipv6,xt_TPROXY,nf_conntrack_ipv6
```
### Steps to reproduce

启动大陆白名单模式，在测试机上把群晖IP设成网关，然后访问ip111.cn测试结果如下
![image](https://user-images.githubusercontent.com/940110/146170994-793f0dfb-1df0-4d7c-9ea5-0465de403a71.png)

### Logs：

```
2021/12/15 10:27:12.106 [A] [main.go:25]  network is connected
2021/12/15 10:27:12.189 [A] [main.go:27]  V2RayLocationAsset is /usr/local/share/v2ray
2021/12/15 10:27:12.190 [A] [main.go:27]  V2Ray binary is /usr/bin/v2ray
2021/12/15 10:27:12.190 [A] [main.go:27]  v2rayA working directory is /root
2021/12/15 10:27:12.190 [A] [main.go:27]  v2rayA configuration directory is /etc/v2raya
2021/12/15 10:27:12.190 [A] [main.go:27]  Golang: go1.17.4
2021/12/15 10:27:12.190 [A] [main.go:27]  OS: linux
2021/12/15 10:27:12.190 [A] [main.go:27]  Arch: amd64
2021/12/15 10:27:12.191 [A] [main.go:27]  Lite: false
2021/12/15 10:27:12.191 [A] [main.go:27]  Version: 1.5.5
2021/12/15 10:27:12.191 [A] [main.go:27]  Starting...
2021/12/15 10:27:12.429 [I] [io.go:425]  V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)
2021/12/15 10:27:12.429 [I] [io.go:425]  A unified platform for anti-censorship.
2021/12/15 10:27:12.430 [I] [io.go:425]  [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2021/12/15 10:27:14.227 [I] [io.go:425]  127.0.0.1:60031 accepted tcp:127.0.0.1:0 [api-out]
2021/12/15 10:27:14.476 [A] [index.go:131]  v2rayA is listening at http://127.0.0.1:2017
2021/12/15 10:27:14.477 [A] [index.go:131]  v2rayA is listening at http://192.168.1.103:2017
2021/12/15 10:27:14.477 [A] [index.go:131]  v2rayA is listening at http://172.17.0.1:2017
2021/12/15 10:27:14.477 [A] [index.go:131]  v2rayA is listening at http://[::1]:2017
2021/12/15 10:27:14.478 [A] [index.go:131]  v2rayA is listening at http://[fe80::211:32ff:fe68:d636]:2017
2021/12/15 10:27:14.478 [A] [index.go:131]  v2rayA is listening at http://[fe80::42:58ff:fe9e:d0db]:2017
2021/12/15 10:27:14.479 [A] [index.go:131]  v2rayA is listening at http://[fe80::7487:82ff:fe00:c83a]:2017
2021/12/15 10:27:14.479 [A] [index.go:131]  v2rayA is listening at http://[fe80::cce0:95ff:fef9:238e]:2017
2021/12/15 10:27:14.479 [A] [index.go:131]  v2rayA is listening at http://[fe80::247f:88ff:fefc:e4a2]:2017
2021/12/15 10:27:14.480 [A] [index.go:131]  v2rayA is listening at http://[fe80::388d:f3ff:fec6:149e]:2017
2021/12/15 10:27:14.480 [A] [index.go:131]  v2rayA is listening at http://[fe80::a8bb:cdff:fe49:8e07]:2017
2021/12/15 10:27:14.480 [A] [index.go:131]  v2rayA is listening at http://[fe80::5ccc:23ff:fe4a:6cd8]:2017
2021/12/15 10:27:29.901 [I] [io.go:425]  192.168.1.101:52901 accepted tcp:31.13.82.52:443 [proxy]
2021/12/15 10:27:30.310 [I] [io.go:425]  192.168.1.101:52902 accepted tcp:31.13.82.52:443 [proxy]
2021/12/15 10:27:30.333 [I] [io.go:425]  192.168.1.101:52903 accepted tcp:31.13.82.52:443 [proxy]
2021/12/15 10:27:31.057 [I] [io.go:425]  192.168.1.101:52904 accepted tcp:121.41.110.161:80 [direct]
2021/12/15 10:27:31.160 [I] [io.go:425]  192.168.1.101:52906 accepted tcp:180.163.150.166:80 [proxy]
2021/12/15 10:27:31.165 [I] [io.go:425]  192.168.1.101:52907 accepted tcp:220.181.33.11:80 [direct]
2021/12/15 10:27:31.179 [I] [io.go:425]  192.168.1.101:52908 accepted tcp:23.80.5.90:80 [proxy]
2021/12/15 10:27:31.205 [I] [io.go:425]  192.168.1.101:52909 accepted tcp:115.126.100.160:80 [proxy]
2021/12/15 10:27:31.255 [I] [io.go:425]  192.168.1.101:52905 accepted tcp:121.41.110.161:80 [direct]
2021/12/15 10:27:31.989 [I] [io.go:425]  192.168.1.101:52910 accepted tcp:31.13.82.52:443 [proxy]
2021/12/15 10:27:32.383 [I] [io.go:425]  192.168.1.101:52913 accepted tcp:31.13.82.52:443 [proxy]
2021/12/15 10:27:32.383 [I] [io.go:425]  192.168.1.101:52914 accepted tcp:31.13.82.52:443 [proxy]
```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

![image](https://user-images.githubusercontent.com/940110/146169268-430e7364-dc27-4b0e-a1e2-cd521fe03976.png)

**Comment by sjtuross** [comment]
发现是节点的问题，换了节点后正常了，另外有2个问题：

当用作透明代理的时候，"开启端口分享"貌似也一定要打开，关闭后客户端就没网了，是这样吗？在透明代理的场景下，那些代理端口我并不想打开。

另外在启动的时候是否能尝试加载相关的iptables模块？现在我必须先手工加载，然后再启动容器。

···
insmod /lib/modules/nfnetlink.ko
insmod /lib/modules/ip_set.ko
insmod /lib/modules/ip_set_hash_ip.ko
insmod /lib/modules/xt_set.ko
insmod /lib/modules/ip_set_hash_net.ko
insmod /lib/modules/xt_mark.ko
insmod /lib/modules/xt_connmark.ko
insmod /lib/modules/nf_tproxy_core.ko
insmod /lib/modules/xt_TPROXY.ko
···

**Comment by mzz2017** [comment]
@sjtuross 你是怎么透明代理的，透明代理不需要这几个端口。你想想在哪用到这几个端口了？

**Comment by mzz2017** [comment]
@sjtuross 关于加载的问题，你可以写个脚本，在脚本的最后运行v2raya，然后挂载这个脚本，运行容器的时候以该脚本作为entrypoint或者cmd

**Comment by sjtuross** [comment]
我肯定没有用过代理端口，刚刚测试发现"开启端口分享"关闭后会导致客户端没网，旁路由模式

单独加载是可以，既然这些是v2raya的依赖，我想是不是写入dockerfile就更方便了

**Comment by MarksonHon** [comment]
@sjtuross 群晖这样的系统都是定制过的，手动加载内核模块不是正常的操作行为。内核模块在操作系统启动之时应该完成加载。v2rayA 只会基于 Ubuntu、Arch 这样的完整的系统进行适配

**Comment by sjtuross** [comment]
照 @mzz2017 的建议在配置目录里加了个bootstrap.sh脚本，作为entrypoint，重启机器后测试正常
```
#!/bin/sh
insmod /lib/modules/nfnetlink.ko &> /dev/null
insmod /lib/modules/ip_set.ko &> /dev/null
insmod /lib/modules/ip_set_hash_ip.ko &> /dev/null
insmod /lib/modules/xt_set.ko &> /dev/null
insmod /lib/modules/ip_set_hash_net.ko &> /dev/null
insmod /lib/modules/xt_mark.ko &> /dev/null
insmod /lib/modules/xt_connmark.ko &> /dev/null
insmod /lib/modules/nf_tproxy_core.ko &> /dev/null
insmod /lib/modules/xt_TPROXY.ko &> /dev/null
v2raya
```
```
docker run -d \
  --restart=always \
  --privileged \
  --network=host \
  --name v2raya-mzz2017 \
  -e V2RAYA_ADDRESS=0.0.0.0:2017 \
  -v /lib/modules:/lib/modules \
  -v /etc/resolv.conf:/etc/resolv.conf \
  -v /volume1/docker/v2raya-config:/etc/v2raya \
  --entrypoint /etc/v2raya/bootstrap.sh \
  mzz2017/v2raya
```

**Comment by sjtuross** [comment]
"开启端口分享"的问题我测试下来确实存在，浏览器的http请求错误为ERR_CONNECTION_REFUSED

关闭"开启端口分享"，用tcping测试，结果超时
```
C:\Tools>tcping.exe www.baidu.com 80
Probing 180.101.49.12:80/tcp - No response - time=2010.501ms
Probing 180.101.49.12:80/tcp - No response - time=2011.621ms
Probing 180.101.49.12:80/tcp - No response - time=2005.985ms
Probing 180.101.49.12:80/tcp - No response - time=2014.813ms
```
打开"开启端口分享"，用tcping测试，正常
```
C:\Tools>tcping.exe www.baidu.com 80
Probing 180.101.49.12:80/tcp - Port is open - time=0.562ms
Probing 180.101.49.12:80/tcp - Port is open - time=0.599ms
Probing 180.101.49.12:80/tcp - Port is open - time=0.553ms
Probing 180.101.49.12:80/tcp - Port is open - time=0.462ms

**Comment by mzz2017** [comment]
应该是不需要端口分享的，你打开端口分享在透明代理的服务器上例如： lsof -i:20170 （及20171等） ，看看是不是有连接

**Comment by sjtuross** [comment]
打开端口分享，一边播放YouTube视频，运行lsof，结果如下。端口分享关闭后客户机网络就不通了，运行lsof结果一样。v2rayA服务器本身一直都正常，可以正常代理，通过curl --ipv4 http://ifconfig.co确认

```
root@DSM3:~# lsof -i:20170
COMMAND   PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
v2ray   12490 root   11u  IPv6 1030887      0t0  TCP *:20170 (LISTEN)
v2ray   12490 root   12u  IPv6 1030888      0t0  UDP *:20170 
root@DSM3:~# lsof -i:20171
COMMAND   PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
v2ray   12490 root    3u  IPv6 1030879      0t0  TCP *:20171 (LISTEN)
root@DSM3:~# lsof -i:20172
COMMAND   PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
v2ray   12490 root    7u  IPv6 1030880      0t0  TCP *:20172 (LISTEN)
```

**Comment by mzz2017** [comment]
@sjtuross 可能是个别发行版体质问题吧.. 或许尽管开了network=host也依然没把127.0.0.1的端口开到宿主去，之类的问题

**Comment by mzz2017** [comment]
@sjtuross 你可以单独把这几个端口关了，在设置里

**Comment by sjtuross** [comment]
没事，我就是汇报一下，现在能用就行了

**Comment by houpi** [comment]
我威联通研究透明代理几年了都未果。

**Comment by sjtuross** [comment]
@mzz2017 今天在Ubuntu 18.04环境下试了下，一样的效果。透明代理，只要关了“端口分享”，客户机就没网了，REFUSED

另外如果我开DNS防污染，“端口分享”关闭的情况下，v2ray的dns服务是侦听127.2.0.17:53，至少说明客户端是无法访问这个DNS服务的

系统环境：Ubuntu 18.04.4 LTS, Docker 20.10.12

**Comment by mzz2017** [comment]
所以你的问题是dns服务无法被访问的问题，那么你需要更换redirect为tproxy。

**Comment by sjtuross** [comment]
dns只是我间接发现的，关闭“端口分享”，为何dns只侦听本机？

dns开不开，这个“端口分享”的问题一样存在于Ubuntu 18.04

**Comment by mzz2017** [comment]
@sjtuross 你看一下到底是dns问题还是哪里的问题，看日志，做分析

**Comment by sjtuross** [comment]
我只是想告诉你“端口分享”的问题我在Ubuntu上可以复现

我只要打开，透明代理使用是没有问题的

**Comment by mzz2017** [comment]
@sjtuross 我知道你复现了，我也知道我们的人没复现，所以问题在于你哪里配置错了，我们哪里配置对了

**Comment by mzz2017** [comment]
@sjtuross 你可以在客户机分别上ping 223.5.5.5，以及ping baidu.com来判断dns问题

**Comment by sjtuross** [comment]
只要端口分享不开，客户端网络是不通的，ping外网ip也是不通的，跟dns无关

**Comment by mzz2017** [comment]
@sjtuross 你说的状况和ip转发一样。那我建议你使用 curl 233.5.5.5 和 curl baidu.com 来测试

**Comment by sjtuross** [comment]
> "开启端口分享"的问题我测试下来确实存在，浏览器的http请求错误为ERR_CONNECTION_REFUSED
> 
> 关闭"开启端口分享"，用tcping测试，结果超时
> 
> ```
> C:\Tools>tcping.exe www.baidu.com 80
> Probing 180.101.49.12:80/tcp - No response - time=2010.501ms
> Probing 180.101.49.12:80/tcp - No response - time=2011.621ms
> Probing 180.101.49.12:80/tcp - No response - time=2005.985ms
> Probing 180.101.49.12:80/tcp - No response - time=2014.813ms
> ```
> 
> 打开"开启端口分享"，用tcping测试，正常
> 
> ```
> C:\Tools>tcping.exe www.baidu.com 80
> Probing 180.101.49.12:80/tcp - Port is open - time=0.562ms
> Probing 180.101.49.12:80/tcp - Port is open - time=0.599ms
> Probing 180.101.49.12:80/tcp - Port is open - time=0.553ms
> Probing 180.101.49.12:80/tcp - Port is open - time=0.462ms
> ```

我觉得上面这个已经说明问题了

**Comment by MarksonHon** [comment]
@mzz2017 普通的 DNS 能用 curl 的么？

**Comment by sjtuross** [comment]
就像你说的，关闭端口分享就像ip forward不起作用了

**Comment by mzz2017** [comment]
@sjtuross 那么你是怎么实现客户机代理的？

**Comment by sjtuross** [comment]
把网关设为v2raya所在服务器IP

**Comment by sjtuross** [comment]
会不会这个问题存在于debian系的linux，因为群晖和Ubuntu都属于这个系列，你们可能用的不是这个系列

**Comment by mzz2017** [comment]
@sjtuross 你的内网是ipv6地址吗

**Comment by sjtuross** [comment]
内网有私有ipv4以及公网ipv6，如下是客户端的。192.168.1.102是v2rayA所在服务器。

```
   IPv6 Address. . . . . . . . . . . : 240e:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX
   Link-local IPv6 Address . . . . . : fe80::755c:4a3a:7bb0:1c95%4
   IPv4 Address. . . . . . . . . . . : 192.168.1.99
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : fe80::1ae8:29ff:fe2d:4f91%4
                                       192.168.1.102
```

**Comment by mzz2017** [comment]
@sjtuross 我们已复现问题，并找到原因：
https://ipset.netfilter.org/iptables-extensions.man.html
根据文档， It redirects the packet to the machine itself by changing the destination IP to the primary address of the incoming interface.

**Comment by sjtuross** [comment]
今天用Ubuntu测试，发现一个奇怪的现象，浏览器没网的情况下，ping外网是通的，我把ipv6禁掉了

就是说icmp貌似没问题，但是tcp有问题

**Comment by sjtuross** [comment]
v2raya这个redirect透明代理只作用于tcp，可能是这个原因

**Comment by sjtuross** [comment]
前几天用群晖测试的时候，我用tcping不通，也是tcp，这就说得通了

**Comment by mzz2017** [comment]
https://github.com/v2rayA/v2rayA/actions/runs/1598154069

等待 actions 执行完毕后，使用这里的二进制文件替换 /usr/bin/v2raya 后应该可以解决问题。

**Comment by sjtuross** [comment]
另外dns侦听地址是不是也应该修一下？只要启用dns防污染，不管端口分享是否启用，dns都应该侦听::53而不是127.2.0.17:53

**Comment by mzz2017** [comment]
@sjtuross 这个wont fix，请开启端口分享后自行将其他端口改为127.0.0.1，见文档中的高级应用一章

**Comment by sjtuross** [comment]
最新的build试过了，确认 68c28fb85cf079a678ce5334a18b9d848faa9d06 解决了问题，关闭端口共享后，redirect模式透明代理正常

**Comment by sjtuross** [comment]
补充一下，再多加载一个iptable_mangle.ko内核模块，tproxy模式的透明代理也可以在群晖上正常启动了

insmod /lib/modules/iptable_mangle.ko &> /dev/null

**Comment by mzz2017** [comment]
@sjtuross 请问可否将你群辉开启透明代理的实践写入文档？如果你同意，提交 PR 或是我们帮你整理都可以。如有其他细节烦请告知。

**Comment by sjtuross** [comment]
@mzz2017 我可以发PR到[https://github.com/v2rayA/v2raya.github.io](https://github.com/v2rayA/v2raya.github.io)，但大量内容会是关于如何编译群晖的内核模块，对于普通用户来说是不是太复杂了？或者说偏离了v2rayA的主题？我可以分成两篇，一篇是关于编译群晖缺失的内核模块，一篇是关于如何安装使用，你觉得呢？

**Comment by houpi** [comment]
@sjtuross 我威联通用户也想知道如何开启透明代理。。。

**Comment by mzz2017** [comment]
@sjtuross 看起来是一个针对内核模块不全的发行版的通用方法，如果篇幅过长，也可以外链的形式，前提是外链长期可用

**Comment by Windman1320** [comment]
> 

你好，能否发布一个编译群晖内核模块的教程不，我使用docker的时候遇到了恶心的问题，十分感谢

**Comment by sjtuross** [comment]
教程已发布 - https://v2raya.org/docs/advanced-application/synology-transparent-proxy/

**Comment by Windman1320** [comment]
教程没有编译模块的部分欸，我后面整理一个吧

**Comment by cubercsl** [comment]
> 教程没有编译模块的部分欸，我后面整理一个吧

文档中有 GitHub 仓库的外链，其 readme 中包含了自编译的说明。

**Comment by Windman1320** [comment]
> 

好的，刚刚没看到，感谢提醒

**Comment by bsdcpp** [comment]
我试过其实只缺一个ipt_REJECT模块
`export CONFIG_IP_NF_IPTABLES=m
export CONFIG_IP_NF_FILTER=m
export CONFIG_IP_NF_TARGET_REJECT=m`
导入此模块即可开启Redir模式。

其他nf_tables模块是从linux 3.13开始才支持的，群晖好像内核更新比较慢，懒得折腾。
