### ISSUE TITLE
一些对使用有影响的自定义项的缺少

### ISSUE THREAD

**Issue by weiliang1503** [v2rayA/v2rayA#332]
### 您想提出的功能特性是否和现有问题相关？

1、现在的v2raya默认开启了嗅探导致tor无法用v2raya作为前置代理（"sniffing" :{"enabled" :true......）

2、似乎配置文件里写了一个腾讯的DNS（119.29.29.29）

### 功能特性内容

1、有能够关闭嗅探的设置项确保tor正常工作

2、能够自定义DNS服务器

**Comment by weiliang1503** [comment]
DNS的设置看到了，不好意思。但是tor还是没有找到办法

**Comment by mzz2017** [comment]
透明代理依赖嗅探进行域名分流。

一个妥协方案是打开fakedns，方法如下:

1. 将 DNS 防污染设为“关闭”以外的任意一项，以开启 FakeDNS 的选项。 
2. 在特殊模式中选择 FakeDNS。 

fakedns 将不依赖于嗅探进行域名分流。
