### ISSUE TITLE
运行后无法科学上网

### ISSUE THREAD

**Issue by mengchaoheng** [v2rayA/v2rayA#334]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.5
2. 你通过什么方式安装v2rayA
2.1
curl -Ls https://mirrors.v2raya.org/go.sh | sudo bash
2.2
sudo systemctl disable v2ray --now ### Xray 需要替换服务为 xray
2.3
通过软件源安装
添加公钥
wget -qO - https://apt.v2raya.mzz.pub/key/public-key.asc | sudo apt-key add -
添加 V2RayA 软件源
echo "deb https://apt.v2raya.mzz.pub/ v2raya main" | sudo tee /etc/apt/sources.list.d/v2raya.list
sudo apt update
安装 V2RayA
sudo apt install v2raya

2.4
sudo systemctl start v2raya.service

3. 你所使用的操作系统

Ubuntu18.04
### 描述问题

配置节点后无法联网。网络连接没问题，其他客户端也可以连同样的配置。
配置如下：
vless://17ec3102-1785-462a-b020-xxxxxxxxxxxx@xx.xx.xx.xx:443?flow=xtls-rprx-direct&encryption=none&security=xtls&sni=www.xxxxxx.top&type=tcp&headerType=none&host=www.xxxxxx.top#newip

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![Screenshot from 2021-12-20 17-54-38](https://user-images.githubusercontent.com/43166007/146748479-9bce69b4-0a1a-45e6-93e2-56f5b60ef811.png)
![Screenshot from 2021-12-20 17-54-41](https://user-images.githubusercontent.com/43166007/146748486-e6d8a1d5-2c02-4e15-821d-7e0112879cbc.png)
![Screenshot from 2021-12-20 17-54-33](https://user-images.githubusercontent.com/43166007/146748488-9557ec13-a51e-48ae-9a89-7e06dfa11a3b.png)

**Comment by cubercsl** [comment]
`flow=xtls-rprx-direct`

**Comment by mengchaoheng** [comment]
![Screenshot from 2021-12-20 17-59-22](https://user-images.githubusercontent.com/43166007/146749061-6261776b-61ed-4450-acbf-423ffd7ce9e9.png)


try but dont work

**Comment by mengchaoheng** [comment]
I dont know how to get log

**Comment by mengchaoheng** [comment]
> 
vless://4cda0b52-635b-4c46-be11-286ddbbc1e28@141.164.47.117:443?flow=xtls-rprx-direct&encryption=none&security=xtls&sni=www.mengchaoheng.com&type=tcp&headerType=none#mch

-------------------------------------------------------------
请问这个url怎么使用v2raya？我在qv2ray   v2rayN都可以使用。

**Comment by cubercsl** [comment]
@mengchaoheng 你 qv2ray 怎么用的 v2rayN 怎么用的 v2raya 也怎么用啊

**Comment by mengchaoheng** [comment]
> @mengchaoheng 你 qv2ray 怎么用的 v2rayN 怎么用的 v2raya 也怎么用啊 。xtls 怎么用 v2ray-core 来跑？

嗯嗯，我应该怎么用呢？小白没搞清楚。v2rayN确实是选xray-core。但我的服务器是参考：https://v2xtls.org/v2ray%e5%a4%9a%e5%90%88%e4%b8%80%e8%84%9a%e6%9c%ac%ef%bc%8c%e6%94%af%e6%8c%81vmesswebsockettlsnginx%e3%80%81vlesstcpxtls%e3%80%81vlesstcptls%e7%ad%89%e7%bb%84%e5%90%88/

搭建的。是只能使用xray了是吗？

**Comment by mzz2017** [comment]
卸掉v2ray，换xray

**Comment by mengchaoheng** [comment]
> 卸掉v2ray，换xray
在弄了，服务器端已经搞好。现在本地还是不行。我想重装v2raya。尴尬的地方在于，我不知道怎么在我的电脑上卸载v2ray。我按照https://v2raya.org/docs/prologue/installation/debian/ 里的官方脚本和硬件脚本都安装过。

**Comment by mzz2017** [comment]
https://hubmirror.v2raya.org/v2fly/fhs-install-v2ray#移除-v2ray

**Comment by mengchaoheng** [comment]
> [https://hubmirror.v2raya.org/v2fly/fhs-install-v2ray#移除-v2ray](https://hubmirror.v2raya.org/v2fly/fhs-install-v2ray#%E7%A7%BB%E9%99%A4-v2ray)
这个已经移除了，现在是我用：
==========================
v2rayA 提供的镜像脚本（推荐）
curl -Ls https://mirrors.v2raya.org/go.sh | sudo bash
安装后可以关掉服务，因为 v2rayA 不依赖于该 systemd 服务。

sudo systemctl disable v2ray --now ### Xray 需要替换服务为 xray
=====================
安装的要不要移除？怎么移除？

另外，我运行sudo systemctl disable xray --now
显示：
Failed to disable unit: Unit file xray.service does not exist.

**Comment by mzz2017** [comment]
你怎么又装一遍v2ray

**Comment by mengchaoheng** [comment]
> 你怎么又装一遍v2ray

非常不好意思，我懵了已经。在 https://v2raya.org/docs/prologue/installation/debian/ 中提到的两种方法我都运行过，官方脚本已经卸载，但“v2rayA 提供的镜像脚本”不知道怎么卸载。

**Comment by MarksonHon** [comment]
Xray并没有加速了下载速度的脚本
你需要使用官方脚本安装

**Comment by mengchaoheng** [comment]
> Xray并没有加速了下载速度的脚本 你需要使用官方脚本安装

使用官方脚本安装之后，我运行sudo systemctl disable xray --now
显示：
Failed to disable unit: Unit file xray.service does not exist.

**Comment by cubercsl** [comment]
@mengchaoheng v2rayA 只提供了 v2ray 安装的镜像脚本，就是上面提到的 fhs-install-v2ray

**Comment by mzz2017** [comment]
我将关闭该issue，因为它并不是v2rayA相关的问题
