### ISSUE TITLE
Show v2ray logs somewhere convenient

### ISSUE THREAD

**Issue by iopq** [v2rayA/v2rayA#335]
I was looking at the v2raya logs, but the error was in v2ray and it's very hard to see where those logs go, or if there are any

**Comment by mzz2017** [comment]
See the output of v2raya -h , there is an argument to control the log level.

**Comment by iopq** [comment]
I set it to trace, the log file didn't show the v2ray logs in it either. I can't see when I restart v2ray or have an error or anything

**Comment by mzz2017** [comment]
You should set the log file path first.

And make sure your v2ray has run or is running.

**Comment by iopq** [comment]
Oh, when I tried to run it from the CLI it was already running so I couldn't set the log level

But in the web interface I have no such option. When I stop the web interface, and run it from the CLI, it doesn't modify my web interface's log level or log file

**Comment by mzz2017** [comment]
Use `systemctl edit --full v2raya` to modify the ExecStart arguments.

**Comment by iopq** [comment]
Doesn't solve the issue of finding my logs

**Comment by mzz2017** [comment]
@iopq journalctl -fu v2raya

**Comment by Leathong** [comment]
@mzz2017 what is the log path on Windows?

**Comment by mzz2017** [comment]
@Leathong installation path
