### ISSUE TITLE
typo in EN translation

### ISSUE THREAD

**Issue by malikshi** [v2rayA/v2rayA#341]
https://github.com/v2rayA/v2rayA/blob/42d21f6b05141db02cdd1deabe11ad804012f088/gui/src/locales/en.js#L102

Upadate to Update

**Comment by malikshi** [comment]
could you check it?
https://github.com/malikshi/v2rayA/commit/8a34a703bda5dfbbc57fa36fdfc361865bcab12f

**Comment by mzz2017** [comment]
LGTM, please pull a request. Thanks.
