### ISSUE TITLE
https://mirrors.v2raya.org/go.sh 貌似离线

### ISSUE THREAD

**Issue by Mr54233** [v2rayA/v2rayA#343]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

2. 你通过什么方式安装v2rayA

3. 你所使用的操作系统

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@Mr54233 已恢复
