### ISSUE TITLE
添加GO BUILD TAGS支持条件编译

### ISSUE THREAD

**Issue by liuyujielol** [v2rayA/v2rayA#344]
### 您想提出的功能特性是否和现有问题相关？

希望可以在编译时通过指定编译选项，自定义构建的二进制支持那些协议

### 功能特性内容

添加GO BUILD TAGS支持条件编译，在编译时可以去掉部分不想要的协议支持，缩小二进制大小

**Comment by liuyujielol** [comment]
我自己试着写了一下https://github.com/liuyujielol/v2rayA/commit/ece33d77954bccf52d116cb95928955792544920

**Comment by mzz2017** [comment]
@liuyujielol 这样对体积大小有减少吗

**Comment by liuyujielol** [comment]
@mzz2017 大小减少了，不过说实话效果不太好，我只是单纯的改了main.go的import部分，go build -tags "full" 和 -tags "ssr socks socks5" 编译出来的二进制，后者(22950569 ~22.4M)比前者(23618737 ~23.0M)只小了差不多0.6M，可能需要对go部分的源码做更深层次的改动

**Comment by mzz2017** [comment]
@liuyujielol 是的，其实二进制大小问题主要是在其他部分体现。模块齐全是 v2rayA 的一个优点，我建议尽量不在这里动手。我会进一步调查。

**Comment by mzz2017** [comment]
如果在意二进制大小，可以用upx进行压缩

**Comment by liuyujielol** [comment]
not really a helpful suggestion. closing.
