### ISSUE TITLE
希望能够修改订阅节点的AllowInsecure选项

### ISSUE THREAD

**Issue by torgitor** [v2rayA/v2rayA#345]
### 您想提出的功能特性是否和现有问题相关？

V2raya的订阅节点仅能查看，不允许修改，而目前v2raya兼容的订阅格式不支持AllowInsecure选项。因某些原因部分节点需要AllowInsecure=true，在v2raya中无法处理。

### 功能特性内容

希望能够像v2rayN和v2rayNG、shadowrocket，允许使用者修改订阅节点的参数，如lowInsecure选项。

**Comment by cubercsl** [comment]
@torgitor cubercsl 🤔 | 今天 Canokeys 发售了吗, [2021-12-27 17:34]
为什么你的订阅节点要 AllowInsecure 但它自己不下发 AllowInsecure 呢？

**Comment by mzz2017** [comment]
@torgitor 点击节点旁边的分享，复制链接，再导入到SERVER，就可以修改了

**Comment by torgitor** [comment]
> 为什么你的订阅节点要 AllowInsecure 但它自己不下发 AllowInsecure 呢？

v2raya支持的分享链接看起来是[v2rayN的分享链接规范](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2))，它目前是不支持AllowInsecure 的，也行v2raya也支持具有更丰富的配置的分享格式？可否提供更详细的信息，万分感谢！

**Comment by torgitor** [comment]
> @torgitor 点击节点旁边的分享，复制链接，再导入到SERVER，就可以修改了

谢谢，这是个折衷的办法，也可以。

**Comment by mzz2017** [comment]
@torgitor Allow Insecure 应该只是一个用于 debug 的参数，不应该依赖使用

**Comment by cubercsl** [comment]
@torgitor 这个格式的规范是支持的 ，只要 base64 解码后的 json 对象里包含 AllowInsecure 的键值就行。

**Comment by torgitor** [comment]
> 

测试可行，v2raya和shadowrocket能识别这个键值。
