### ISSUE TITLE
add support for trojan grpc

### ISSUE THREAD

**Issue by malikshi** [v2rayA/v2rayA#347]
### Is the feature related with existing problem?

no.

### Content of the feature

As mentioned in telegram chat, trojan grpc quite popular since [mack-a/v2ray-agent](https://github.com/mack-a/v2ray-agent) have the combination trojan gRPC, vless gRPC. and following the client supported those combination like clash, passwall. I hope v2rayA considering to support it.

**Comment by aisivan36** [comment]
I am looking for support Trojan gRCP in future update, seems this was roughly asked 2 years ago.

**Comment by iopq** [comment]
> I am looking for support Trojan gRCP in future update, seems this was roughly asked 2 years ago.

Same, surprising omission and should be relatively easy to add

**Comment by mzz2017** [comment]
@iopq 是挺容易的，为什么没有人来加呢

**Comment by MarksonHon** [comment]
@iopq 是很容易，但是目前没有开发者用这样的节点，所以欢迎PR

**Comment by mzz2017** [comment]
https://github.com/v2rayA/v2rayA/actions/runs/7339466534

感谢 @iopq 的 PR，有人测试一下吗？
