### ISSUE TITLE
能否默认安装延迟来排序

### ISSUE THREAD

**Issue by jymr92** [v2rayA/v2rayA#348]
1. 现在默认是按照添加顺序排序，如何让系统默认使用延迟来排序？或者记住我的排序方式，先知啊每次都要手动点击按”时延”来排序
2. 如果一个订阅有100多个节点，测速很慢，测速结果要全部节点测完才能看到。建议改成5个节点一组来测速。

**Comment by mzz2017** [comment]
@jymr92 点击表头

**Comment by mzz2017** [comment]
@jymr92 没有默认的办法
