### ISSUE TITLE
透明代理开启失败 failed to start v2ray-core: ExecCommands: iptables -w 2 -A DROP_SPOOFING -p udp --sport 53 -m string --algo bm --hex-string "|00047f|" --from 60 --to 180 -j DROP iptables v1.8.7 (legacy): Couldn't load match `string':No such file or directory Try `iptables -h' or 'iptables --help' for more information. : exit status 2

### ISSUE THREAD

**Issue by ifnk** [v2rayA/v2rayA#349]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
$ v2raya --version
1.5.5
2. 你通过什么方式安装v2rayA
archlinux :  pacman -S v2raya 
3. 你所使用的操作系统
archlinux x64

### 描述问题：

根据文档 配置透明代理 
![image](https://user-images.githubusercontent.com/39295458/147737973-4e4c3d8f-9280-414d-bce6-f272084c73df.png)
然后点击就绪按钮 
报 
![image](https://user-images.githubusercontent.com/39295458/147738029-4ce7d305-ecb8-41de-a551-0eff53bc4da7.png)

但是 如果 关闭透明代理 就能正常启动 
如图 
![image](https://user-images.githubusercontent.com/39295458/147738146-32dacd28-324e-4128-8f11-235079dd2899.png)
 

### v2rayA运行日志（Optional）：
● v2raya.service - v2rayA Service
     Loaded: loaded (/usr/lib/systemd/system/v2raya.service; enabled; vendor preset: disabled)
     Active: active (running) since Thu 2021-12-30 16:14:12 CST; 1h 1min ago
       Docs: https://github.com/v2rayA/v2rayA/wiki
   Main PID: 728239 (v2raya)
      Tasks: 43 (limit: 17753)
     Memory: 84.8M
        CPU: 58.062s
     CGroup: /system.slice/v2raya.service
             ├─728239 /usr/bin/v2raya --log-disable-timestamp
             └─896760 /usr/bin/v2ray --config=/etc/v2raya/config.json

12月 30 17:13:36 ifnk v2raya[728239]: [W] [transparent.go:33]  WriteTransparentProxyRules: ExecCommands: iptables -w 2 -A DROP_SPOOFING -p udp --sport 53 -m string --algo bm --hex-string "|00047f|" --from 60 --t>
12月 30 17:13:36 ifnk v2raya[728239]: Try `iptables -h' or 'iptables --help' for more information.
12月 30 17:13:36 ifnk v2raya[728239]: : exit status 2
12月 30 17:13:37 ifnk v2raya[728239]: [E] [connection.go:88]  failed to start v2ray-core: ExecCommands: iptables -w 2 -A DROP_SPOOFING -p udp --sport 53 -m string --algo bm --hex-string "|00047f|" --from 60 --to>
12月 30 17:13:37 ifnk v2raya[728239]: Try `iptables -h' or 'iptables --help' for more information.
12月 30 17:13:37 ifnk v2raya[728239]: : exit status 2
12月 30 17:14:29 ifnk v2raya[728239]: [I] [io.go:425]  V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.5 linux/amd64)
12月 30 17:14:29 ifnk v2raya[728239]: [I] [io.go:425]  A unified platform for anti-censorship.
12月 30 17:14:29 ifnk v2raya[728239]: [I] [io.go:425]  [Info] main/jsonem: Reading config: /etc/v2raya/config.json
12月 30 17:14:30 ifnk v2raya[728239]: [I] [io.go:425]  127.0.0.1:54880 accepted tcp:127.0.0.1:0 [api-out]
 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50

11月 16 09:47:27 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
11月 16 09:54:31 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
11月 16 09:54:42 ifnk systemd[1]: Stopping V2Ray Service...
11月 16 09:54:42 ifnk systemd[1]: v2ray.service: Deactivated successfully.
11月 16 09:54:42 ifnk systemd[1]: Stopped V2Ray Service.
11月 16 09:54:42 ifnk systemd[1]: v2ray.service: Consumed 1.877s CPU time.
11月 16 09:54:42 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
11月 16 09:54:42 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
-- Boot c48da9c7393d42dcad8513ac1e7ed948 --
12月 03 17:01:16 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 08 10:08:47 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 08 10:08:48 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
-- Boot 4d006eedc4cc42c6a3d65bf546e38b48 --
12月 13 11:52:43 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 13 11:52:43 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 13 11:52:43 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 13 13:33:26 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 13 13:33:26 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 13 13:33:26 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 13 13:49:11 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 13 13:49:11 ifnk systemd[1]: Started V2Ray Service.
12月 13 13:49:11 ifnk v2ray[1400349]: V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.5 linux/amd64)
12月 13 13:49:11 ifnk v2ray[1400349]: A unified platform for anti-censorship.
12月 13 13:49:11 ifnk v2ray[1400349]: 2021/12/13 13:49:11 [Info] main/jsonem: Reading config: /etc/v2ray/config.json
12月 13 13:49:11 ifnk v2ray[1400349]: 2021/12/13 13:49:11 [Warning] V2Ray 4.44.0 started
12月 13 14:06:33 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 15 10:04:00 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 15 15:08:52 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 15 15:08:55 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 16 09:30:55 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 16 10:02:57 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 17 13:54:25 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 17 14:47:25 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 20 09:36:41 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 20 17:29:51 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 20 17:38:42 ifnk systemd[1]: Stopping V2Ray Service...
12月 20 17:38:42 ifnk systemd[1]: v2ray.service: Deactivated successfully.
12月 20 17:38:42 ifnk systemd[1]: Stopped V2Ray Service.
12月 20 17:38:42 ifnk systemd[1]: v2ray.service: Consumed 47.472s CPU time.
-- Boot 12d0cdeebeb3492296c5cbe7e5b1e344 --
12月 30 17:00:55 ifnk systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
12月 30 17:00:55 ifnk systemd[1]: Started V2Ray Service.
12月 30 17:00:55 ifnk v2ray[857410]: V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.5 linux/amd64)
12月 30 17:00:55 ifnk v2ray[857410]: A unified platform for anti-censorship.
12月 30 17:00:55 ifnk v2ray[857410]: 2021/12/30 17:00:55 [Info] main/jsonem: Reading config: /etc/v2ray/config.json
12月 30 17:00:55 ifnk v2ray[857410]: 2021/12/30 17:00:55 [Warning] V2Ray 4.44.0 started
12月 30 17:08:57 ifnk systemd[1]: Stopping V2Ray Service...
12月 30 17:08:57 ifnk systemd[1]: v2ray.service: Deactivated successfully.
12月 30 17:08:57 ifnk systemd[1]: Stopped V2Ray Service.
12月 30 17:08:57 ifnk systemd[1]: v2ray.service: Consumed 1.682s CPU time.

 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
重装iptables然后重启

**Comment by ifnk** [comment]
> 重装iptables然后重启

我重装 的 iptables ,然后  sudo systemctl restart iptables.service 

查看 iptables.service 的时候 发现是 exited 
● iptables.service - IPv4 Packet Filtering Framework
     Loaded: loaded (/usr/lib/systemd/system/iptables.service; disabled; vendor preset: disabled)
     Active: active (exited) since Thu 2021-12-30 18:02:49 CST; 1min 38s ago
    Process: 1036606 ExecStart=/usr/bin/iptables-restore /etc/iptables/iptables.rules (code=exited, status=0/SUCCESS)
   Main PID: 1036606 (code=exited, status=0/SUCCESS)
        CPU: 1ms

12月 30 18:02:49 ifnk systemd[1]: Stopping IPv4 Packet Filtering Framework...
12月 30 18:02:49 ifnk systemd[1]: iptables.service: Deactivated successfully.
12月 30 18:02:49 ifnk systemd[1]: Stopped IPv4 Packet Filtering Framework.
12月 30 18:02:49 ifnk systemd[1]: Starting IPv4 Packet Filtering Framework...
12月 30 18:02:49 ifnk systemd[1]: Finished IPv4 Packet Filtering Framework.

然后我在把 v2raya.service重启了 ，
开启透明代理 还是报 同样的错误 ，
我应该怎么弄呢？

**Comment by cubercsl** [comment]
@ifnk 重启电脑

**Comment by MarksonHon** [comment]
@ifnk 重启电脑试试看

**Comment by ifnk** [comment]
> @ifnk 重启电脑



> @ifnk 重启电脑试试看


谢谢 ，重启电脑就可以 啦 ……
