### ISSUE TITLE
如何手动设置某些网址/ip 连接方式走 代理/直连

### ISSUE THREAD

**Issue by ifnk** [v2rayA/v2rayA#350]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.5
2. 你通过什么方式安装v2rayA
archlinux pacman -S v2raya 
3. 你所使用的操作系统
archlinux x86

### 描述问题：

如题 ，在 qv2ray 下 有个路由 高级设置 ，可以 设置 某些网址或ip 强制走 proxy/直连 
![image](https://user-images.githubusercontent.com/39295458/147749775-c03e3777-9ea7-4df4-9dad-aa82bf55261f.png)

v2raya 是 在哪里设置的呢？ 

http://staticcdn.linebead.com/libs/cesium/Cesium.js

我现在这个 网址 直连是好的， 但是 用了 v2raya 的透明代理后 ，这个就没有办法访问了 ，导致我 react 项目 出错…… 
![image](https://user-images.githubusercontent.com/39295458/147749858-51153e21-830e-4df0-b837-a19a0c668cbe.png)

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by cubercsl** [comment]
首先请关掉你浏览器的代理插件 截图与http代理有关，而非透明代理。

关于分流：透明代理选择与规则端口相同，规则端口分流规则选 routingA

**Comment by ifnk** [comment]
> 首先请关掉你浏览器的代理插件 截图与http代理有关，而非透明代理。
> 
> 关于分流：透明代理选择与规则端口相同，规则端口分流规则选 routingA

可以 了 ，谢谢你 ！
