### ISSUE TITLE
请问怎么把配置迁移到别的电脑呢

### ISSUE THREAD

**Issue by ifnk** [v2rayA/v2rayA#351]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.5
2. 你通过什么方式安装v2rayA
pacman -S v2raya
3. 你所使用的操作系统
archlinux x64

### 描述问题：

如题 ，我在我自己的电脑（archlinux ）上面  安装 了 v2raya ,然后通过 localhost:2017 网址 配置 了 订阅地址 ，连接 ，透明代理等等 ，然后 我又在一台 centos 7 的服务器上面 安装 了 v2raya ,关键 他的  2017 端口是 不对外开放的 (就算开放了，估计也端口映射了) ，
所以我想 的是把我 本机 的 v2raya 的配置 (带订阅 和透明代理等 全部设置) scp 远程拷贝 到 centos 7 服务器上面 ，然后 直接 启动 v2raya.service 这样 可行么？ 
我在 /etc/v2raya 文件夹里面 找到了 这个 
root@ifnk /e/v2raya# ll
总用量 200K
-rw-r--r-- 1 root root 8.0M 11月 16 09:03 0.dat
-rw------- 1 root root 136K 12月 30 20:35 boltv4.db
-rw------- 1 root root 5.5K 12月 30 20:32 config.json

请问 这就是 v2raya 的 全部配置文件么? 
 

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by cubercsl** [comment]
@ifnk boltv4.db

使用疑问请尽量加群讨论，不要滥用 issue 区提问。

**Comment by ifnk** [comment]
> @ifnk boltv4.db
> 
> 使用疑问请尽量加群讨论，不要滥用 issue 区提问。

嗷嗷，好
