### ISSUE TITLE
[希望可以增加监控面板]

### ISSUE THREAD

**Issue by TcDhl** [v2rayA/v2rayA#352]
### Content of the feature

不管是启动了单条还是多条线路, 监控面板中能实时看到哪条线路正在被使用
类似v2rayN客户端的统计面板

**Comment by cubercsl** [comment]
@TcDhl 不用增加 已经有了

**Comment by TcDhl** [comment]
@cubercsl 
你图中是四条线路, v2rayA工作的时候, 是用其中的一条线路, 还是四条线路都会使用?

**Comment by mzz2017** [comment]
@TcDhl 金色代表当前连接，红色代表故障节点，蓝色代表正常节点

**Comment by cubercsl** [comment]
@TcDhl 这是我连接时选择了四条线路，会自动负载均衡选择最快的，其中蓝色的表示现在正在使用的，黄色表示存活的，红色（图中没有）表示离线的。

**Comment by TcDhl** [comment]
这个是 [新版本: 1.5.5] 才会这么显示的?
我1.5.4是这样的
![image](https://user-images.githubusercontent.com/58108675/147847378-d8805b87-2b61-4797-8025-82a5796c6dbd.png)

**Comment by mzz2017** [comment]
@TcDhl 你有三个策略: 1，等一会。2，刷新页面。3，重启电脑。

**Comment by TcDhl** [comment]
@cubercsl 
这两条线路我都是可以通过v2rayA,正常去翻墙, 只是没有像你这样颜色显示
我是通过Docker安装的, 有点尴尬不会升级(pull新的镜像后, 原先v2rayA容器里的配置不晓得怎么保存下来然后给新的使用...)

**Comment by mzz2017** [comment]
请问问题是否解决？

**Comment by TcDhl** [comment]
木有, 但不影响正常使用, 不管它了
