### ISSUE TITLE
希望可以增加uTLS设置

### ISSUE THREAD

**Issue by huangguiniab** [v2rayA/v2rayA#358]
### 您想提出的功能特性是否和现有问题相关？

可能是我使用的机房被盯上了。就算我不是做任何事情，如果不使用谷歌览器访问伪装网站的话，就会进入十分钟的路由黑洞，我自己开启了指纹伪装就可以完美使用

### 功能特性内容

如题，就是希望在设置里增加uTLS的指纹伪装设置

**Comment by mzz2017** [comment]
谢谢，v2rayA只会优先考虑v2ray-core的特性
