### ISSUE TITLE
内存爆炸 日志文件巨大

### ISSUE THREAD

**Issue by MavisTok** [v2rayA/v2rayA#359]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.55
2. 你通过什么方式安装v2rayA
使用 docker 命令部署
3. 你所使用的操作系统
centos7

### 描述问题

![image](https://user-images.githubusercontent.com/52002734/148262150-c48055b6-5bf9-4593-b277-65f1e3a6be5a.png)

日志现在都没刷完

**Comment by mzz2017** [comment]
@MavisTok 只贴日志无法诊断问题

**Comment by MavisTok** [comment]
![image](https://user-images.githubusercontent.com/52002734/148262940-0a13e85b-6840-46f5-bff8-96b52fc4843a.png)

-- Logs begin at Thu 2021-12-02 13:52:18 CST, end at Thu 2022-01-06 01:35:04 CST. --
-- No entries --

**Comment by cubercsl** [comment]
@MavisTok 请不要贴去年的日志来描述你现在的问题
