### ISSUE TITLE
提示 failed to start v2ray-core: unexpected exiting: check the log for more information

### ISSUE THREAD

**Issue by GEOHOTIOS** [v2rayA/v2rayA#360]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.5
2. 你通过什么方式安装v2rayA
sudo dnf copr enable zhullyb/v2rayA
sudo dnf install v2ray-core
sudo dnf install v2rayA
3. 你所使用的操作系统
CentOS 8

### 描述问题：

点击启动/api/v2ray爆错
{"code":"FAIL","data":null,"message":"failed to start v2ray-core: unexpected exiting: check the log for more information"}

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志
1月 07 21:14:03 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000134760 sp=0xc000134740 pc=0x55a3e216a136
1月 07 21:14:03 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.gcBgMarkWorker()
1月 07 21:14:03 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc0001347e0 sp=0xc000134760 pc=0x55a3e214e125
1月 07 21:14:03 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.goexit()
1月 07 21:14:03 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0001347e8 sp=0xc0001347e0 pc=0x55a3e2197a81
1月 07 21:14:03 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  created by runtime.gcBgMarkStartWorkers
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/mgc.go:1124 +0x25
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  goroutine 20 [GC worker (idle)]:
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.gopark(0x55a3e2e6ef50,
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  0xc000580000, 0x18, 0x14, 0x0)
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000134f60 sp=0xc000134f40 pc=0x55a3e216a136
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.gcBgMarkWorker()
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc000134fe0 sp=0xc000134f60 pc=0x55a3e214e125
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.goexit()
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000134fe8 sp=0xc000134fe0 pc=0x55a3e2197a81
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  created by runtime.gcBgMarkStartWorkers
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/mgc.go:1124 +0x25
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  goroutine 34 [GC worker (idle)]:
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.gopark(0x36b671eb95460e, 0xc00003d500, 0x18, 0x14, 0x0)
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000130760 sp=0xc000130740 pc=0x55a3e216a136
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.gcBgMarkWorker()
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc0001307e0 sp=0xc000130760 pc=0x55a3e214e125
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.goexit()
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0001307e8 sp=0xc0001307e0 pc=0x55a3e2197a81
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  created by runtime.gcBgMarkStartWorkers
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/mgc.go:1124 +0x25
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  goroutine 11 [GC worker (idle)]:
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.gopark(0x36b671df4f093c, 0xc000124080, 0x18, 0x14, 0x0)
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00005ef60 sp=0xc00005ef40 pc=0x55a3e216a136
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.gcBgMarkWorker()
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc00005efe0 sp=0xc00005ef60 pc=0x55a3e214e125
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.goexit()
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005efe8 sp=0xc00005efe0 pc=0x55a3e2197a81
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  created by runtime.gcBgMarkStartWorkers
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/mgc.go:1124 +0x25
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  goroutine 35 [GC worker (idle)]:
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.gopark(0x36b671ec7e1cca, 0xc0001240a0, 0x18, 0x14, 0x0)
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000130f60 sp=0xc000130f40 pc=0x55a3e216a136
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.gcBgMarkWorker()
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc000130fe0 sp=0xc000130f60 pc=0x55a3e214e125
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  runtime.goexit()
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000130fe8 sp=0xc000130fe0 pc=0x55a3e2197a81
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]  created by runtime.gcBgMarkStartWorkers
1月 07 21:14:04 localhost.localdomain v2raya[1277930]: [I] [io.go:425]          /usr/lib/golang/src/runtime/mgc.go:1124 +0x25
1月 07 21:14:06 localhost.localdomain v2raya[1277930]: [W] [asm_amd64.s:1581]  v2ray-core: signal: aborted (core dumped)
1月 07 21:14:06 localhost.localdomain v2raya[1277930]: [E] [connection.go:88]  failed to start v2ray-core: unexpected exiting: check the log for more information

```
```shell
# v2ray日志
1月 07 20:58:06 localhost.localdomain systemd[1]: Started V2Ray Service.
1月 07 20:58:06 localhost.localdomain v2ray[1248570]: V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.2 linux/amd64)
1月 07 20:58:06 localhost.localdomain v2ray[1248570]: A unified platform for anti-censorship.
1月 07 20:58:06 localhost.localdomain v2ray[1248570]: 2022/01/07 20:58:06 [Info] main/jsonem: Reading config: /etc/v2ray/config.json
1月 07 20:58:08 localhost.localdomain v2ray[1248570]: 2022/01/07 20:58:08 [Warning] V2Ray 4.44.0 started
1月 07 21:08:22 localhost.localdomain systemd[1]: Stopping V2Ray Service...
1月 07 21:08:22 localhost.localdomain systemd[1]: Stopped V2Ray Service.
1月 07 21:08:32 localhost.localdomain systemd[1]: Started V2Ray Service.
1月 07 21:08:32 localhost.localdomain v2ray[1275001]: V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.2 linux/amd64)
1月 07 21:08:32 localhost.localdomain v2ray[1275001]: A unified platform for anti-censorship.
1月 07 21:08:32 localhost.localdomain v2ray[1275001]: 2022/01/07 21:08:32 [Info] main/jsonem: Reading config: /etc/v2ray/config.json
1月 07 21:08:33 localhost.localdomain v2ray[1275001]: 2022/01/07 21:08:33 [Warning] V2Ray 4.44.0 started
```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

[](url)

**Comment by mzz2017** [comment]
运行 sudo v2ray -c /etc/v2raya/config.json 看看

**Comment by GEOHOTIOS** [comment]
运行结果
V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.2 linux/amd64)
A unified platform for anti-censorship.
2022/01/07 23:58:27 [Info] main/jsonem: Reading config: /etc/v2raya/config.json
panic: runtime error: index out of range [133] with length 127

goroutine 1 [running]:
panic({0x564c6e6929c0, 0xc0016eceb8})
        /usr/lib/golang/src/runtime/panic.go:1147 +0x3a8 fp=0xc00b0a4830 sp=0xc00b0a4770 pc=0x564c6d9e9208
runtime.goPanicIndex(0x85, 0x7f)
        /usr/lib/golang/src/runtime/panic.go:90 +0x75 fp=0xc00b0a4870 sp=0xc00b0a4830 pc=0x564c6d9e66b5
github.com/v2fly/v2ray-core/v4/common/strmatcher.(*ACAutomaton).Add(0xc0019d2e10, {0xc008f2c0e0, 0xc005b7eff0}, 0x1)
        /builddir/build/BUILD/v2ray-core-4.44.0/common/strmatcher/ac_automaton_matcher.go:138 +0x63e fp=0xc00b0a4f40 sp=0xc00b0a4870 pc=0x564c6deeb05e
github.com/v2fly/v2ray-core/v4/common/strmatcher.(*MphMatcherGroup).AddPattern(0xc005b72120, {0xc008f2c0e0, 0x1b}, 0x1)
        /builddir/build/BUILD/v2ray-core-4.44.0/common/strmatcher/mph_matcher.go:72 +0xa5 fp=0xc00b0a4fc0 sp=0xc00b0a4f40 pc=0x564c6deec5c5
github.com/v2fly/v2ray-core/v4/app/router.NewMphMatcherGroup({0xc000114ec0, 0x1, 0xc005b7e270})
        /builddir/build/BUILD/v2ray-core-4.44.0/app/router/condition.go:79 +0x13b fp=0xc00b0a5020 sp=0xc00b0a4fc0 pc=0x564c6df63bfb
github.com/v2fly/v2ray-core/v4/app/router.(*RoutingRule).BuildCondition(0xc0000ce840)
        /builddir/build/BUILD/v2ray-core-4.44.0/app/router/config.go:36 +0xfd fp=0xc00b0a5270 sp=0xc00b0a5020 pc=0x564c6df659fd
github.com/v2fly/v2ray-core/v4/app/router.(*Router).Init(0xc005b5c1c0, {0x564c6e71a180, 0xc005b7e000}, 0xc005b76420, {0x7f068c03e970, 0xc005b51780}, {0x7f0684e580d8, 0xc005b71770})
        /builddir/build/BUILD/v2ray-core-4.44.0/app/router/router.go:51 +0x448 fp=0xc00b0a5350 sp=0xc00b0a5270 pc=0x564c6df69a48
github.com/v2fly/v2ray-core/v4/app/router.init.1.func1.1({0x7f068c03e970, 0xc005b51780}, {0x7f0684e580d8, 0xc005b71770})
        /builddir/build/BUILD/v2ray-core-4.44.0/app/router/router.go:147 +0x6f fp=0xc00b0a53a0 sp=0xc00b0a5350 pc=0x564c6df6ab4f
runtime.call32(0xc005b7ee10, 0xc005b7e060, 0x0, 0x0, 0x0, 0x20, 0xc00b0a58e0)
        /usr/lib/golang/src/runtime/asm_amd64.s:626 +0x4b fp=0xc00b0a53d0 sp=0xc00b0a53a0 pc=0x564c6da17dab
runtime.reflectcall(0x564c6e6797e0, 0xc005b71770, 0x4, 0x6e1d4fad, 0x564c, 0x12, 0x564c6e62d600)
        <autogenerated>:1 +0x3c fp=0xc00b0a5410 sp=0xc00b0a53d0 pc=0x564c6da1c11c
reflect.Value.call({0x564c6e5a60c0, 0xc005b7e060, 0x30}, {0x564c6e1c8f64, 0x4}, {0xc005b7ede0, 0x2, 0x18})
        /usr/lib/golang/src/reflect/value.go:543 +0x814 fp=0xc00b0a5a00 sp=0xc00b0a5410 pc=0x564c6da794b4
reflect.Value.Call({0x564c6e5a60c0, 0xc005b7e060, 0x564c6e62d600}, {0xc005b7ede0, 0x2, 0x2})
        /usr/lib/golang/src/reflect/value.go:339 +0xc5 fp=0xc00b0a5a78 sp=0xc00b0a5a00 pc=0x564c6da78a65
github.com/v2fly/v2ray-core/v4.(*resolution).resolve(0xc00b0a5ca0, {0xc005b51100, 0x7, 0x8})
        /builddir/build/BUILD/v2ray-core-4.44.0/v2ray.go:75 +0x3d4 fp=0xc00b0a5c00 sp=0xc00b0a5a78 pc=0x564c6ddd8d34
github.com/v2fly/v2ray-core/v4.(*Instance).AddFeature(0xc005b716d0, {0x7f068c03e940, 0xc005b51780})
        /builddir/build/BUILD/v2ray-core-4.44.0/v2ray.go:306 +0x31e fp=0xc00b0a5cd8 sp=0xc00b0a5c00 pc=0x564c6ddda6fe
github.com/v2fly/v2ray-core/v4.initInstanceWithConfig(0xc0004e5560, 0xc005b716d0)
        /builddir/build/BUILD/v2ray-core-4.44.0/v2ray.go:202 +0x19c fp=0xc00b0a5de0 sp=0xc00b0a5cd8 pc=0x564c6ddd987c
github.com/v2fly/v2ray-core/v4.New(0x564c6e1c93b8)
        /builddir/build/BUILD/v2ray-core-4.44.0/v2ray.go:165 +0x77 fp=0xc00b0a5e18 sp=0xc00b0a5de0 pc=0x564c6ddd9697
main.startV2Ray()
        /builddir/build/BUILD/v2ray-core-4.44.0/main/main.go:114 +0x230 fp=0xc00b0a5ea8 sp=0xc00b0a5e18 pc=0x564c6e1c2e50
main.main()
        /builddir/build/BUILD/v2ray-core-4.44.0/main/main.go:138 +0x9f fp=0xc00b0a5f80 sp=0xc00b0a5ea8 pc=0x564c6e1c30bf
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:255 +0x227 fp=0xc00b0a5fe0 sp=0xc00b0a5f80 pc=0x564c6d9ebd67
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00b0a5fe8 sp=0xc00b0a5fe0 pc=0x564c6da19a81

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000068fb0 sp=0xc000068f90 pc=0x564c6d9ec136
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:372
runtime.forcegchelper()
        /usr/lib/golang/src/runtime/proc.go:306 +0xad fp=0xc000068fe0 sp=0xc000068fb0 pc=0x564c6d9ebfcd
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000068fe8 sp=0xc000068fe0 pc=0x564c6da19a81
created by runtime.init.8
        /usr/lib/golang/src/runtime/proc.go:294 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc0000697b0 sp=0xc000069790 pc=0x564c6d9ec136
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:372
runtime.bgsweep()
        /usr/lib/golang/src/runtime/mgcsweep.go:182 +0xd8 fp=0xc0000697e0 sp=0xc0000697b0 pc=0x564c6d9d7bf8
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000697e8 sp=0xc0000697e0 pc=0x564c6da19a81
created by runtime.gcenable
        /usr/lib/golang/src/runtime/mgc.go:181 +0x55

goroutine 4 [sleep]:
runtime.gopark(0xc000044050, 0xc2a92d4090, 0x0, 0x0, 0x564c6e6f0e88)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000069f30 sp=0xc000069f10 pc=0x564c6d9ec136
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:372
runtime.scavengeSleep(0x6eb9b35)
        /usr/lib/golang/src/runtime/mgcscavenge.go:241 +0x9f fp=0xc000069f80 sp=0xc000069f30 pc=0x564c6d9d5b9f
runtime.bgscavenge()
        /usr/lib/golang/src/runtime/mgcscavenge.go:366 +0x205 fp=0xc000069fe0 sp=0xc000069f80 pc=0x564c6d9d5de5
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000069fe8 sp=0xc000069fe0 pc=0x564c6da19a81
created by runtime.gcenable
        /usr/lib/golang/src/runtime/mgc.go:182 +0x65

goroutine 5 [finalizer wait]:
runtime.gopark(0x564c6ed65a20, 0xc000068770, 0xf1, 0x8e, 0x564c6ecf64e0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000068630 sp=0xc000068610 pc=0x564c6d9ec136
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:372
runtime.runfinq()
        /usr/lib/golang/src/runtime/mfinal.go:177 +0xb3 fp=0xc0000687e0 sp=0xc000068630 pc=0x564c6d9cd6d3
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000687e8 sp=0xc0000687e0 pc=0x564c6da19a81
created by runtime.createfing
        /usr/lib/golang/src/runtime/mfinal.go:157 +0x45

goroutine 6 [select]:
runtime.gopark(0xc000076f70, 0x3, 0xb8, 0x95, 0xc000076f12)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000076d78 sp=0xc000076d58 pc=0x564c6d9ec136
runtime.selectgo(0xc000076f70, 0xc000076f0c, 0x0, 0x0, 0x0, 0x1)
        /usr/lib/golang/src/runtime/select.go:327 +0x772 fp=0xc000076ec0 sp=0xc000076d78 pc=0x564c6d9fb512
github.com/v2fly/v2ray-core/v4/common/log.(*generalLogger).run(0xc000088080)
        /builddir/build/BUILD/v2ray-core-4.44.0/common/log/logger.go:54 +0x1f2 fp=0xc000076fc8 sp=0xc000076ec0 pc=0x564c6dbac092
github.com/v2fly/v2ray-core/v4/common/log.(*generalLogger).Handle·dwrap·6()
        /builddir/build/BUILD/v2ray-core-4.44.0/common/log/logger.go:77 +0x26 fp=0xc000076fe0 sp=0xc000076fc8 pc=0x564c6dbac406
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000076fe8 sp=0xc000076fe0 pc=0x564c6da19a81
created by github.com/v2fly/v2ray-core/v4/common/log.(*generalLogger).Handle
        /builddir/build/BUILD/v2ray-core-4.44.0/common/log/logger.go:77 +0xa6

goroutine 7 [GC worker (idle)]:
runtime.gopark(0xc2a1ebf7cb, 0xc00003f3c0, 0x18, 0x14, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00006af60 sp=0xc00006af40 pc=0x564c6d9ec136
runtime.gcBgMarkWorker()
        /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc00006afe0 sp=0xc00006af60 pc=0x564c6d9d0125
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00006afe8 sp=0xc00006afe0 pc=0x564c6da19a81
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1124 +0x25

goroutine 8 [GC worker (idle)]:
runtime.gopark(0xc2a1eec9a8, 0xc000124020, 0x18, 0x14, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00006b760 sp=0xc00006b740 pc=0x564c6d9ec136
runtime.gcBgMarkWorker()
        /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc00006b7e0 sp=0xc00006b760 pc=0x564c6d9d0125
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00006b7e8 sp=0xc00006b7e0 pc=0x564c6da19a81
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1124 +0x25

goroutine 18 [GC worker (idle)]:
runtime.gopark(0xc2a1ebccf5, 0xc000124040, 0x18, 0x14, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00006a760 sp=0xc00006a740 pc=0x564c6d9ec136
runtime.gcBgMarkWorker()
        /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc00006a7e0 sp=0xc00006a760 pc=0x564c6d9d0125
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00006a7e8 sp=0xc00006a7e0 pc=0x564c6da19a81
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1124 +0x25

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x564c6e6f0f50, 0xc000600000, 0x18, 0x14, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000064760 sp=0xc000064740 pc=0x564c6d9ec136
runtime.gcBgMarkWorker()
        /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc0000647e0 sp=0xc000064760 pc=0x564c6d9d0125
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000647e8 sp=0xc0000647e0 pc=0x564c6da19a81
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1124 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0xc2a1ebaf22, 0xc00003f3e0, 0x18, 0x14, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000608760 sp=0xc000608740 pc=0x564c6d9ec136
runtime.gcBgMarkWorker()
        /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc0006087e0 sp=0xc000608760 pc=0x564c6d9d0125
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0006087e8 sp=0xc0006087e0 pc=0x564c6da19a81
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1124 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x564c6e6f0f50, 0xc000124060, 0x18, 0x14, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000064f60 sp=0xc000064f40 pc=0x564c6d9ec136
runtime.gcBgMarkWorker()
        /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc000064fe0 sp=0xc000064f60 pc=0x564c6d9d0125
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000064fe8 sp=0xc000064fe0 pc=0x564c6da19a81
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1124 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x564c6e6f0f50, 0xc000600020, 0x18, 0x14, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000065760 sp=0xc000065740 pc=0x564c6d9ec136
runtime.gcBgMarkWorker()
        /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc0000657e0 sp=0xc000065760 pc=0x564c6d9d0125
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000657e8 sp=0xc0000657e0 pc=0x564c6da19a81
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1124 +0x25

goroutine 9 [GC worker (idle)]:
runtime.gopark(0xc2a1ebaf02, 0xc000600040, 0x18, 0x14, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00006bf60 sp=0xc00006bf40 pc=0x564c6d9ec136
runtime.gcBgMarkWorker()
        /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc00006bfe0 sp=0xc00006bf60 pc=0x564c6d9d0125
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00006bfe8 sp=0xc00006bfe0 pc=0x564c6da19a81
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1124 +0x25

goroutine 22 [GC worker (idle)]:
runtime.gopark(0xc2a1ebaf78, 0xc000600060, 0x18, 0x14, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000065f60 sp=0xc000065f40 pc=0x564c6d9ec136
runtime.gcBgMarkWorker()
        /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc000065fe0 sp=0xc000065f60 pc=0x564c6d9d0125
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000065fe8 sp=0xc000065fe0 pc=0x564c6da19a81
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1124 +0x25

goroutine 35 [GC worker (idle)]:
runtime.gopark(0xc264b13c6a, 0xc00003f400, 0x18, 0x14, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000608f60 sp=0xc000608f40 pc=0x564c6d9ec136
runtime.gcBgMarkWorker()
        /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc000608fe0 sp=0xc000608f60 pc=0x564c6d9d0125
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000608fe8 sp=0xc000608fe0 pc=0x564c6da19a81
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1124 +0x25

**Comment by mzz2017** [comment]
降级v2ray-core再试试

**Comment by mrcaidev** [comment]
你好！我也遇到了同样的提示，但日志提示的是 **53 端口已被占用**（见下）。和该 Issue 应该不是同一个问题，但如果之后有和我一样问题的人来这，我把我的解决方法贴一下：

    sudo systemctl stop systemd-resolved
    sudo systemctl disable systemd-resolved

我猜是因为 v2raya 的某项服务和系统自带的 `systemd-resolved` 服务在 53 端口上发生了冲突，所以我选择关掉了系统的服务。如果占用 53 端口的不是这个服务，可以用 `sudo lsof -i :53` 查看是什么占用了 53 端口。

日志：

```txt
2022/02/06 05:48:03.495 [I] [io.go:425]  V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)
2022/02/06 05:48:03.495 [I] [io.go:425]  A unified platform for anti-censorship.
2022/02/06 05:48:03.495 [I] [io.go:425]  [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/02/06 05:48:05.278 [I] [io.go:425]  Failed to start listen udp 0.0.0.0:53: bind: address already in use
2022/02/06 05:48:05.286 [W] [asm_amd64.s:1581]  v2ray-core: exit status 255
2022/02/06 05:48:05.483 [E] [connection.go:88]  failed to start v2ray-core: unexpected exiting: check the log for more information
```

**Comment by mzz2017** [comment]
@mrcaidev 在设置中关闭 DNS 防污染，或者透明代理切换至 tproxy

**Comment by MarksonHon** [comment]
现在 Fedora 源中的核心无故障了，这个issue先关闭。
