### ISSUE TITLE
Installing v2raya on mac os

### ISSUE THREAD

**Issue by Horuyuki** [v2rayA/v2rayA#365]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
latest

2. What approach of installation do you install V2rayA?
mac os with homebrew and creation of plist

3. What is your operating system?
Big Sur 11.6.1

### Description
1. `curl -L https://github.com/v2rayA/v2rayA/releases/download/v1.5.4/v2raya_darwin_x64_1.5.4 -o /usr/local/bin/v2raya`
2. `nano /usr/local/bin/v2raya.sh`
> #! /bin/zsh
PATH=$PATH:/usr/local/bin
/usr/local/bin/v2raya --lite

3. `brew install v2ray`
4. `chmod 755 /usr/local/bin/v2raya; chmod 755 /usr/local/bin/v2raya.sh`
5. `xattr -d -r com.apple.quarantine  /usr/local/bin/*`
6. `nano ~/Library/LaunchAgents/org.v2raya.v2raya.plist`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>KeepAlive</key>
        <true/>
        <key>Label</key>
        <string>org.v2raya.v2raya</string>
        <key>ProgramArguments</key>
        <array>
            <string>/usr/local/bin/v2raya.sh</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
    </dict>
</plist>
```

7. `launchctl load ~/Library/LaunchAgents/org.v2raya.v2raya.plist`
 error: `Load failed: 5: Input/output error`

**Comment by Horuyuki** [comment]
@mzz2017 如果需要的話，我也能說中文。

**Comment by MarksonHon** [comment]
手动运行：
`v2raya --lite` 
然后看下结果

**Comment by Horuyuki** [comment]
> 手动运行： `v2raya --lite` 然后看下结果

```
 v2raya --lite
2022/01/16 10:25:13.857 [A] [main.go:25]  network is connected
2022/01/16 10:25:13.860 [I] [pre.go:211]  init DB
2022/01/16 10:25:13.981 [A] [main.go:27]  V2RayLocationAsset is /usr/local/share/v2ray
2022/01/16 10:25:13.981 [A] [main.go:27]  V2Ray binary is /usr/local/bin/v2ray
2022/01/16 10:25:13.981 [A] [main.go:27]  v2rayA working directory is /Users/media
2022/01/16 10:25:13.981 [A] [main.go:27]  v2rayA configuration directory is /Users/media/.config/v2raya
2022/01/16 10:25:13.981 [A] [main.go:27]  Golang: go1.17.1
2022/01/16 10:25:13.981 [A] [main.go:27]  OS: darwin
2022/01/16 10:25:13.981 [A] [main.go:27]  Arch: amd64
2022/01/16 10:25:13.981 [A] [main.go:27]  Lite: true
2022/01/16 10:25:13.981 [A] [main.go:27]  Version: 1.5.4
2022/01/16 10:25:13.981 [A] [main.go:27]  Starting...
2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://127.0.0.1:2017
2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[::1]:2017
2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::1]:2017
2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::18c5:7769:e2d0:4a72]:2017
2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://192.168.1.130:2017
2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[2603:7000:d03d:f6d2:8d5:fadb:2b14:6ab0]:2017
2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[2603:7000:d03d:f6d2:99ea:c43c:c7c8:fc1a]:2017
2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::e842:49ff:feb7:9c6]:2017
2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::e842:49ff:feb7:9c6]:2017
2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::699d:80be:caa4:ca28]:2017
2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::94f3:b636:834:a54f]:2017
2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::b6ca:17d8:50d:ef50]:2017
2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::1fe9:12a3:8242:47fc]:2017
```

**Comment by MarksonHon** [comment]
> > 手动运行： `v2raya --lite` 然后看下结果
> 
> ```
>  v2raya --lite
> 2022/01/16 10:25:13.857 [A] [main.go:25]  network is connected
> 2022/01/16 10:25:13.860 [I] [pre.go:211]  init DB
> 2022/01/16 10:25:13.981 [A] [main.go:27]  V2RayLocationAsset is /usr/local/share/v2ray
> 2022/01/16 10:25:13.981 [A] [main.go:27]  V2Ray binary is /usr/local/bin/v2ray
> 2022/01/16 10:25:13.981 [A] [main.go:27]  v2rayA working directory is /Users/media
> 2022/01/16 10:25:13.981 [A] [main.go:27]  v2rayA configuration directory is /Users/media/.config/v2raya
> 2022/01/16 10:25:13.981 [A] [main.go:27]  Golang: go1.17.1
> 2022/01/16 10:25:13.981 [A] [main.go:27]  OS: darwin
> 2022/01/16 10:25:13.981 [A] [main.go:27]  Arch: amd64
> 2022/01/16 10:25:13.981 [A] [main.go:27]  Lite: true
> 2022/01/16 10:25:13.981 [A] [main.go:27]  Version: 1.5.4
> 2022/01/16 10:25:13.981 [A] [main.go:27]  Starting...
> 2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://127.0.0.1:2017
> 2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[::1]:2017
> 2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::1]:2017
> 2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::18c5:7769:e2d0:4a72]:2017
> 2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://192.168.1.130:2017
> 2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[2603:7000:d03d:f6d2:8d5:fadb:2b14:6ab0]:2017
> 2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[2603:7000:d03d:f6d2:99ea:c43c:c7c8:fc1a]:2017
> 2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::e842:49ff:feb7:9c6]:2017
> 2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::e842:49ff:feb7:9c6]:2017
> 2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::699d:80be:caa4:ca28]:2017
> 2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::94f3:b636:834:a54f]:2017
> 2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::b6ca:17d8:50d:ef50]:2017
> 2022/01/16 10:25:13.981 [A] [index.go:131]  v2rayA is listening at http://[fe80::1fe9:12a3:8242:47fc]:2017
> ```

看起来没啥问题，你再执行下 v2raya.sh 看下

**Comment by MarksonHon** [comment]
长时间未回应，先关闭。
可以加群聊：<https://t.me/v2raya_zh>
