### ISSUE TITLE
redirect模式设备自带doh进行dns解析显示timeout，tproxy模式一样无法连接，并影响局域网设备

### ISSUE THREAD

**Issue by GenerralLiu** [v2rayA/v2rayA#369]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.5
2. 你通过什么方式安装v2rayA
v2raya/openwrt下的源安装
3. 你所使用的操作系统
openwrt 21.02 statble
除了源安装需要的依赖，还安装了dnsmasq-full和ip-full

### 描述问题：

开启透明代理后,设置默认直连，只代理部分geo域名及ip，部分设备自带的doh进行dns解析会无法解析并不停增加连接。导致米家yeelight无法通过米家APP进行控制，home assistant不停进行解析。点击webui左上角关闭后正常。
如果用tproxy，不管是否设置dns防污染，都会无法连接，并影响局域网其他设备联网。
图片为无法连接时op实时信息里的连接信息。

复现流程：
1.开启redirect模式，关闭dns防污染
2.开启home-assistant/supervisor
3.op会增加进千个连接

![image](https://user-images.githubusercontent.com/97586725/149081680-bd6c7cac-c262-46ec-9e2a-9260129db4a1.png)
![image](https://user-images.githubusercontent.com/97586725/149081791-f3710d11-c70e-4a8b-92cc-a6964e5722de.png)

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
![image](https://user-images.githubusercontent.com/97586725/149081103-4aa7ca13-974b-4642-9d4f-ba0a9fef2510.png)

![image](https://user-images.githubusercontent.com/97586725/149081058-e78d494b-af3e-4be6-a64d-6e3ec94252b9.png)

贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@GenerralLiu https://v2raya.org/docs/advanced-application/advanced-dns/#%E4%BD%BF%E7%94%A8%E5%85%B6%E4%BB%96-dns-%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by GenerralLiu** [comment]
感谢大神百忙之中回复，我已经按照这个去操作了。所以改了redirect，并关闭了dns防污染。可是故障依旧。我还有什么可以做的吗？

>

**Comment by GenerralLiu** [comment]
> @GenerralLiu https://v2raya.org/docs/advanced-application/advanced-dns/#%E4%BD%BF%E7%94%A8%E5%85%B6%E4%BB%96-dns-%E5%AE%A2%E6%88%B7%E7%AB%AF

还是您的意思我应该在透明代理那一项选择其他选项，比如大陆白名单模式

**Comment by mzz2017** [comment]
@GenerralLiu 你关闭v2raya之后情况会恢复吗

**Comment by mzz2017** [comment]
@GenerralLiu 如果你选择redirect，且dns防污染选择关闭，很难说是v2rayA的问题

**Comment by mzz2017** [comment]
@mzz2017 为了避免复杂情况，建议：1，关闭所有占用 53 端口的服务，例如 dnsmasq。2，开启 DNS 防污染。

**Comment by GenerralLiu** [comment]
> @GenerralLiu 你关闭v2raya之后情况会恢复吗

关闭v2raya后会恢复，并且连接马上就都消失了。好的 我回去把53端口释放一下，然后用dns防污染试一下。是否还会这样。

**Comment by GenerralLiu** [comment]
大佬，我把dnsmasq放到了5353，开启了dns防污染高级模式，但是并没有程序监听53端口，是改完后要重启吗？目前局域网机器无法上网。
![image](https://user-images.githubusercontent.com/97586725/149115423-72f90e3e-e85a-40a0-815b-56540cb609f5.png)
![image](https://user-images.githubusercontent.com/97586725/149115592-c5252d0b-f2f7-4ff1-9d90-815c3c5f287a.png)

**Comment by mzz2017** [comment]
@GenerralLiu 你是用的 redirect 吗，服务启动了吗

**Comment by GenerralLiu** [comment]
我已经进行了service v2raya stop 及service v2raya start 操作

**Comment by GenerralLiu** [comment]
![image](https://user-images.githubusercontent.com/97586725/149117465-8ccc2e88-6d43-467d-b12a-9ada50c1f073.png)

**Comment by mzz2017** [comment]
@GenerralLiu 看看日志，没监听的话会有提示

**Comment by GenerralLiu** [comment]
![image](https://user-images.githubusercontent.com/97586725/149118680-dc9c8d84-08fa-4ae4-8246-2b67f21ccc33.png)
![image](https://user-images.githubusercontent.com/97586725/149118923-9f055adb-aee1-4c2f-9e88-43ab4534f5a5.png)
![image](https://user-images.githubusercontent.com/97586725/149118746-fad8d208-53a2-4297-ad33-753a42a8411e.png)
![image](https://user-images.githubusercontent.com/97586725/149118806-47c8117a-f404-41d5-998b-4af62ea2c2ce.png)
后面2个截图是我格式化了config截的

**Comment by GenerralLiu** [comment]
![image](https://user-images.githubusercontent.com/97586725/149119499-37754717-3089-4e7a-9215-f58c5e8df75c.png)
服务器也收到这条请求了

**Comment by mzz2017** [comment]
不是dnsout，看in，另外core启动的时候有提示

**Comment by GenerralLiu** [comment]
> 不是dnsout，看in，另外core启动的时候有提示
![image](https://user-images.githubusercontent.com/97586725/149122454-b33d7e5e-3952-408a-a8e3-851335ba9179.png)

这个吗 我的日志开的是info 需要改成debug吗？

**Comment by mzz2017** [comment]
@GenerralLiu 你看配置文件里有没有dns-in这个inbound

**Comment by GenerralLiu** [comment]
> @GenerralLiu 你看配置文件里有没有dns-in这个inbound

![image](https://user-images.githubusercontent.com/97586725/149122861-be5fa322-fc30-4ca0-9cfb-1a07299a682a.png)
就这一个

**Comment by mzz2017** [comment]
现在是没有回环了是吧，但是局域网没法上网

**Comment by GenerralLiu** [comment]
> 现在是没有回环了是吧，但是局域网没法上网

![image](https://user-images.githubusercontent.com/97586725/149124112-0e42ce9f-885c-40e9-8183-fecbce4881bd.png)
有。。这些还是。。。

**Comment by mzz2017** [comment]
这些看上去不是回环，因为时间间隔较长。你确定直连1.1.1.1:853没有问题吗？

**Comment by GenerralLiu** [comment]
> 这些看上去不是回环，因为时间间隔较长。你确定直连1.1.1.1:853没有问题吗？

不是，刚刚我拿灯试了一下，虽然设备网页打不开，灯断电后还是无法接入米家服务，webui左上角点关闭后，就瞬间连上了

**Comment by GenerralLiu** [comment]
> 这些看上去不是回环，因为时间间隔较长。你确定直连1.1.1.1:853没有问题吗？

又研究了一下 不知道是不是因为在v2ray中打了mark的缘故，又找到一个v2ray项目下的issues，也是说的这个，仔细一看，竟然是您提的。。。
https://github.com/v2ray/v2ray-core/issues/2160

**Comment by GenerralLiu** [comment]
不知道有没有办法让我把相关ip直接写在这试试
![image](https://user-images.githubusercontent.com/97586725/149194639-65b48b75-fd3a-40b4-8c95-95342ec95387.png)

**Comment by mzz2017** [comment]
@GenerralLiu 可能的原因有很多，tproxy不行redirect可以的话，很有可能是iptables的问题，看看 iptables -Lvn 排查一下问题

**Comment by mzz2017** [comment]
你确定是doh导致的无法操作米家吗

**Comment by GenerralLiu** [comment]
> 你确定是doh导致的无法操作米家吗

对不起，我不确定，我也只是根据他启动后一直连接这些地址来猜测。并且dhcp是可以看到他获取了地址，并且我用homeassistant也可以通过局域网控制。

**Comment by mzz2017** [comment]
尝试 redirect 模式
在启动正常后:

iptables -t nat -I V2RAY -p tcp --dport 853 -j RETURN

**Comment by GenerralLiu** [comment]
> 尝试 redirect 模式 在启动正常后:
> 
> iptables -t nat -I V2RAY -p tcp --dport 853 -j RETURN

谢谢大佬，问题解决，因为我看米家的灯的doh走的是443，home assistant doh走的是853，于是我运行了2条命令
iptables -t nat -I V2RAY -p tcp --dport 853 -j RETURN
iptables -t nat -I V2RAY -s 192.168.1.12 -j RETURN

经过关闭灯的电源，重启home assistant，发现故障都已解决。
我需要怎么做才能让这2条命令开机自启呢？

**Comment by GenerralLiu** [comment]
![image](https://user-images.githubusercontent.com/97586725/149198924-9e74d4c3-2743-4486-a195-e23026c13d40.png)

**Comment by mzz2017** [comment]
有一个做法比较hacky，将v2ray二进制换成一个shell脚本（wrapper），它先插入iptables指令，并以传入参数运行真正的v2ray。
例如

#!/bin/sh
iptables -t nat xxxxx
/usr/bin/real_v2ray $@

**Comment by GenerralLiu** [comment]
> 有一个做法比较hacky，将v2ray二进制换成一个shell脚本（wrapper），它先插入iptables指令，并以传入参数运行真正的v2ray。 例如
> 
> #!/bin/sh iptables -t nat xxxxx /usr/bin/real_v2ray $@

额。算了吧，我写一个开机延时脚本吧。希望大神有时间的话，在webui里加一个功能，可以填这些优先级最高的不代理的ip及端口啥的

**Comment by mzz2017** [comment]
@GenerralLiu 这样的话 v2raya 重连会刷新iptables 命令，你可以做成一个定时任务，当该行不存在时插入

**Comment by GenerralLiu** [comment]
好吧。。那我还是研究下您上面说的方案，多谢您了，早点休息

**Comment by GenerralLiu** [comment]
@mzz2017

**Comment by GenerralLiu** [comment]
已完美解决，感谢@mzz2017不厌其烦的帮助！
