### ISSUE TITLE
功能调整建议

### ISSUE THREAD

**Issue by poorboy** [v2rayA/v2rayA#375]
建议主界面上选择服务器后，把左边的浮动窗口里加一个取消选择，或者干脆把这个浮动窗口取消了，直接在主界面里增加一个固定的标签，这样好测试延迟 方便选择和取消，像订阅标签这样。，建议把所有的订阅里面的服务器也全部在增加一个标签 好批量测试延迟 增加服务器

**Comment by mzz2017** [comment]
谢谢你的建议，正在考虑。
