### ISSUE TITLE
如何让steam下载不走代理

### ISSUE THREAD

**Issue by Bob0111** [v2rayA/v2rayA#376]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA 1.5.5

2. 你通过什么方式安装v2rayA  apt包管理

3. 你所使用的操作系统  Debian

### 描述问题：

我就是想知道现在应该怎样才能让steam的社区和商店使用代理而下载不使用它（设置的是tproxy的透明代理）。

**Comment by mzz2017** [comment]
@Bob0111 在日志中找到对应的域名，然后在 RoutingA 中设置该域名直连。
提示：将“透明代理”选为“与规则端口所选模式一致”；将“规则端口的分流模式”选为“RoutingA”。
