### ISSUE TITLE
arch linux 的终端不能访问那些网站（已对终端设置代理）。烦请指导下，谢谢。

### ISSUE THREAD

**Issue by yummy527** [v2rayA/v2rayA#378]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.5-1
2. 你通过什么方式安装v2rayA
yay -S v2raya-bin
sudo systemctl enable --now v2raya
3. 你所使用的操作系统
Linux archlinux 5.16.1-arch1-1 

### 描述问题：

在终端中，export设置代理后，依然不能从某些网站下载资源、亦不能ping通某些网站。（在浏览器中，可以访问那些网站。）

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![Screenshot_20220118_202335](https://user-images.githubusercontent.com/9738778/149937448-10fd9fcd-a326-456d-81d0-2cf3df0833d7.png)
![Screenshot_20220118_202414](https://user-images.githubusercontent.com/9738778/149937458-fd998ff4-912d-4cb2-8bc6-1b0fa5891ecc.png)
![Screenshot_20220118_202559](https://user-images.githubusercontent.com/9738778/149937462-db97b1ef-08bf-4172-9d76-3b0b716e0a93.png)
![Screenshot_20220118_202726](https://user-images.githubusercontent.com/9738778/149937465-3b90ea8e-60e7-4210-93cf-0bc7bf16fd63.png)

**Comment by MarksonHon** [comment]
你别把https代理往socks端口上送啊，很多程序不支持的

**Comment by MarksonHon** [comment]
PS：开启透明代理来得更快

**Comment by mzz2017** [comment]
不要ping，不要ping，不要ping。谢谢。

**Comment by yummy527** [comment]
> PS：开启透明代理来得更快

好了。谢谢。
这是个乌龙，实际上终端是可以访问那些网站的。

**Comment by yummy527** [comment]
> 不要ping，不要ping，不要ping。谢谢。

我是外行。请问：在这种情况下，一般使用curl代替ping么？

**Comment by mzz2017** [comment]
@yummy527 对

**Comment by yummy527** [comment]
@mzz2017 了解了，非常感谢！
