### ISSUE TITLE
[Advice]开机自动启动代理

### ISSUE THREAD

**Issue by 123ABCDF11345** [v2rayA/v2rayA#381]
现在开机启动时代理没有运行，显示就绪，希望能增加开机自动激活代理的设置选项
（我试着看了看post的api，但是没太搞懂
```
{"POST":{"scheme":"http","host":"127.0.0.1:2017","filename":"/api/v2ray","remote":{"地址":"127.0.0.1:2017"}}}
```
带的请求头X-V2raya-Request-Id是怎么来的，所以实现不了自己写个脚本，如果可以也希望能给一个更加简明的API，直接传入这样的参数
{'user':'admin','pd':'this is password','action':'start v2ray'}
）
谢谢

**Comment by mzz2017** [comment]
@123ABCDF11345 没有运行看日志

**Comment by 123ABCDF11345** [comment]
谢谢，目前暂时无法复现，我怀疑是系统时间的问题，我会在稍后排查的，非常感谢你的提醒
