### ISSUE TITLE
更新gfwlist cdn.jsdelivr.net问题

### ISSUE THREAD

**Issue by FredyVia** [v2rayA/v2rayA#387]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
**1.5.5**
2. 你通过什么方式安装v2rayA
**apt**
3. 你所使用的操作系统
**ubuntu:20.04**

### 描述问题：

目前更新GFWList出现问题，查了下是这个下载geosite.dat处的cdn.jsdelivr.net的问题，有没有其他办法更新gfwlist

### v2rayA运行日志（Optional）：
```
Jan 23 23:39:30 littlebee v2raya[1576]: [W] [gfwlist.go:165]  UpdateLocalGFWList: Get "https://cdn.jsdelivr.net/gh/v2rayA/dist-v2ray-rules-dat@202201182216/geosite.dat": dial tcp 0.0.0.0:443: connect: connection refused
Jan 23 23:39:30 littlebee v2raya[1576]: [E] [gfwlist.go:12]  Get "https://cdn.jsdelivr.net/gh/v2rayA/dist-v2ray-rules-dat@202201182216/geosite.dat": dial tcp 0.0.0.0:443: connect: connection refused
```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![image](https://user-images.githubusercontent.com/43921304/150686702-61324d49-86bb-4c5f-9636-029acf2f68c7.png)

**Comment by cubercsl** [comment]
DNS 污染了

**Comment by mzz2017** [comment]
@FredyVia https://github.com/v2rayA/v2rayA/actions/runs/1736235280
该问题已在最新的 commit 中解决，使用这里的二进制文件替换你的 v2raya

**Comment by FredyVia** [comment]
多谢

**Comment by FredyVia** [comment]
我改的hosts也行了
