### ISSUE TITLE
请问一下win10平台下,软件的配置文件目录和缓存目录在哪?

### ISSUE THREAD

**Issue by KSroido** [v2rayA/v2rayA#389]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA 

2. 你通过什么方式安装v2rayA

3. 你所使用的操作系统

### 描述问题：

之前已经在Windows10下正常安装v2rayA了,目前需要干净卸载
想问一下相关组件和配置文件、临时文件等的存放目录在哪里(exe本体和winsw服务已经卸载了)
翻了一下文档暂时没找到具体路径
感谢解答

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@KSroido 程序启动的时候会打印出来

**Comment by KSroido** [comment]
resolved
