### ISSUE TITLE
在通过代理下载大文件一段时间后，会显示网络问题下载失败。

### ISSUE THREAD

**Issue by ltkal** [v2rayA/v2rayA#391]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.5
2. 你通过什么方式安装v2rayA
aur中的v2raya-git
3. 你所使用的操作系统
Arch Linux  5.16.2

### 描述问题：

在通过代理下载大文件一段时间后，会显示网络问题下载失败。

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![image](https://user-images.githubusercontent.com/87233994/151103009-e01ccb01-dc43-4b08-98a7-ce16d490421c.png)
![image](https://user-images.githubusercontent.com/87233994/151103045-428299ec-35da-47b7-929b-65c05289645b.png)
![image](https://user-images.githubusercontent.com/87233994/151103071-347caa1b-f776-460d-9280-5bc79718fb2f.png)

**Comment by mzz2017** [comment]
@ltkal 很抱歉，这通常不是 v2rayA 的问题，这通常与节点、本地网络等因素相关。我将关闭该问题，谢谢。
