### ISSUE TITLE
小白求指导。。好像无法使用vless+TCP+XTLS的节点

### ISSUE THREAD

**Issue by vztimeout** [v2rayA/v2rayA#392]
我在ubuntu上安装了V2RAYA后导入WINDOWS正常使用的两个节点，一个是vless+ws+tls,一个是vless+tcp+xtsl，然后ws+tls的节点可以正常使用，tcp+xtls的节点在V2RAYA节点列表里能ping，但是无法浏览网页。求解。。

**Comment by mzz2017** [comment]
与 https://github.com/v2rayA/v2rayA/issues/197 重复
