### ISSUE TITLE
代理实现方式只有 `system proxy`

### ISSUE THREAD

**Issue by mrcaidev** [v2rayA/v2rayA#398]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

    v1.5.6.2

2. 你通过什么方式安装v2rayA

    Windows 安装包一键安装 (installer_windows_x64_1.5.6.2.exe)

3. 你所使用的操作系统

    Windows 11 Beta (21H2)

### 描述问题：

面板设置中的“透明代理/系统代理实现方式”一栏只有 `system proxy` 选项，没有 `redirect`；导致启动时报错：failed to start v2ray-core: not support "system proxy" mode of transparent proxy: The parameter is incorrect.

### v2rayA运行日志（Optional）：

```shell
2022/02/02 11:06:55.703  [I] [io.go:425]  V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 windows/amd64)
2022/02/02 11:06:55.703  [I] [io.go:425]  A unified platform for anti-censorship.
2022/02/02 11:06:55.703  [I] [io.go:425]  [Info] main/jsonem: Reading config: C:\WINDOWS\system32\config\systemprofile\.config\v2raya/config.json
2022/02/02 11:06:57.713  [I] [io.go:425]  127.0.0.1:51235 accepted tcp:127.0.0.1:0 [api-out]
2022/02/02 11:06:57.888  [W] [transparent.go:54]  WriteTransparentProxyRules: not support "system proxy" mode of transparent proxy: The parameter is incorrect.
2022/02/02 11:06:58.224  [E] [connection.go:88]  failed to start v2ray-core: not support "system proxy" mode of transparent proxy: The parameter is incorrect.
```

### v2rayA设置以及相关截图

![image](https://user-images.githubusercontent.com/78269445/152086939-3f551796-4aa3-404f-9079-8567ac246231.png)

![image](https://user-images.githubusercontent.com/78269445/152087170-0cca7e53-75ff-4217-be06-654acdc95d8a.png)

**Comment by mzz2017** [comment]
@mrcaidev 调出admin权限的powershell执行 netsh winhttp import proxy source=ie 看看是不是不支持了

**Comment by mrcaidev** [comment]
> @mrcaidev 调出admin权限的powershell执行 netsh winhttp import proxy source=ie 看看是不是不支持了

    当前的 WinHTTP 代理服务器设置:
    
        直接访问(没有代理服务器)。

**Comment by mzz2017** [comment]
我也升级到了 Windows 11 Beta (21H2)，没有复现问题…… 很奇怪

**Comment by mzz2017** [comment]
在搜索时，我发现该问题可能和个体相关，见 https://www.maketecheasier.com/fix-the-parameter-is-incorrect-error-windows/

**Comment by yshenfab** [comment]
How did you solve it? The same issue happens with my Arch Linux. I installed through AUR (v2ray-git).
