### ISSUE TITLE
Timestamps can't be disabled in the log file

### ISSUE THREAD

**Issue by InvisibleRain** [v2rayA/v2rayA#401]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.5.6.2

2. What approach of installation do you install V2rayA?
.deb package from GitHub releases

3. What is your operating system?
Debian 11

### Description
`--log-disable-timestamp` is ignored when using along with `--log-file`

### Steps to reproduce
1. Run `v2raya --log-disable-timestamp --log-file /var/log/v2raya.log &`
2. Check the log file: `tail /var/log/v2raya.log`

However, if running without the `--log-file` flag, timestamps are disabled successfully in stdout:
1. Stop daemon `pkill v2raya`
2. `v2raya --log-disable-timestamp`

**Comment by mzz2017** [comment]
@InvisibleRain It is expected.

**Comment by cubercsl** [comment]
It is an expected feature.

When you use v2raya with systemd, the log is collected by systemd-journald with timestamp, so the log with timestamp is duplicate.

The option `--log-disable-timestamp` can be used in such situation.

**Comment by InvisibleRain** [comment]
>the log is collected by systemd-journald with timestamp, so the log with timestamp is duplicate

Ok, it makes sense now. Shall we make it explicit by adding description to `--help`?

**Comment by mzz2017** [comment]
@InvisibleRain Thanks. I'll write it to --help.
