### ISSUE TITLE
节点url太长导致订阅失效

### ISSUE THREAD

**Issue by FanLuoh** [v2rayA/v2rayA#405]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.6.2
2. 你通过什么方式安装v2rayA
https://github.com/v2raya/v2raya-openwrt
3. 你所使用的操作系统
openwrt

### 描述问题

订阅中单个节点url太长了会导致整个订阅出不了节点
没base64 encode前 单节点url长度超过262左右的字符长度（这个还蛮容易达到的 vmess ws tls ws host和sni都填 然后节点名稍微长一点点长度就达到），并且在节点别名中出现“_”“-”等字符时
节点url是从v2rayn提取的 然后base64 encode了一下作订阅使用 就会出现这种情况

### 复现问题的步骤

1.在订阅中添加如下节点url：
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogInRlc3RfdGVzdC10ZXN0X3Rlc3QiLA0KICAiYWRkIjogInRlc3QudGVzdC50ZXN0LnRlc3QiLA0KICAicG9ydCI6ICIxMjM0NSIsDQogICJpZCI6ICI5ZDA0MjEwZC05NWViLTQzNDUtYjM5MS1mY2VhODg4YTdlM2UiLA0KICAiYWlkIjogIjAiLA0KICAic2N5IjogImF1dG8iLA0KICAibmV0IjogIndzIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogInRlc3QudGVzdC50ZXN0LnRlc3QiLA0KICAicGF0aCI6ICIvdGVzdHRlc3R0ZXN0dGVzdCIsDQogICJ0bHMiOiAidGxzIiwNCiAgInNuaSI6ICJ0ZXN0LnRlc3QudGVzdC50ZXN0IiwNCiAgImFscG4iOiAiIg0KfQ==
#仅供test用
```
{
  "v": "2",
  "ps": "test_test-test_test",
  "add": "test.test.test.test",
  "port": "12345",
  "id": "9d04210d-95eb-4345-b391-fcea888a7e3e",
  "aid": "0",
  "scy": "auto",
  "net": "ws",
  "type": "none",
  "host": "test.test.test.test",
  "path": "/testtesttesttest",
  "tls": "tls",
  "sni": "test.test.test.test",
  "alpn": ""
}
```
2.把整个订阅url进行base64编码并制作订阅
3.在v2raya中添加订阅

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志

`2022/02/08 07:03:33.250  [W] [subscription.go:239]  resolveByLines: ResolveURL error: invalid URL:xxxxxxxxxxxx`
*若干行

```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by Gaojianli** [comment]
>vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogInRlc3RfdGVzdC10ZXN0X3Rlc3QiLA0KICAiYWRkIjogInRlc3QudGVzdC50ZXN0LnRlc3QiLA0KICAicG9ydCI6ICIxMjM0NSIsDQogICJpZCI6ICI5ZDA0MjEwZC05NWViLTQzNDUtYjM5MS1mY2VhODg4YTdlM2UiLA0KICAiYWlkIjogIjAiLA0KICAic2N5IjogImF1dG8iLA0KICAibmV0IjogIndzIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogInRlc3QudGVzdC50ZXN0LnRlc3QiLA0KICAicGF0aCI6ICIvdGVzdHRlc3R0ZXN0dGVzdCIsDQogICJ0bHMiOiAidGxzIiwNCiAgInNuaSI6ICJ0ZXN0LnRlc3QudGVzdC50ZXN0IiwNCiAgImFscG4iOiAiIg0KfQ==

使用你提供的URL无法复现：
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/19235246/152943101-caff76a7-a2b9-4223-97c3-bc7005df917f.png">

**Comment by FanLuoh** [comment]
> > vmess：// ew0KICAidiI6ICIyIiwNCiAgInBzIjogInRlc3RfdGVzdC10ZXN0X3Rlc3QiLA0KICAiYWRkIjogInRlc3QudGVzdC50ZXN0LnRlc3QiLA0KICAicG9ydCI6ICIxMjM0NSIsDQogICJpZCI6ICI5ZDA0MjEwZC05NWViLTQzNDUtYjM5MS1mY2VhODg4YTdlM2UiLA0KICAiYWlkIjogIjAiLA0KICAic2N5IjogImF1dG8iLA0KICAibmV0IjogIndzIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogInRlc3QudGVzdC50ZXN0LnRlc3QiLA0KICAicGF0aCI6ICIvdGVzdHRlc3R0ZXN0dGVzdCIsDQogICJ0bHMiOiAidGxzIiwNCiAgInNuaSI6ICJ0ZXN0LnRlc3QudGVzdC50ZXN0IiwNCiAgImFscG4iOiAiIg0KfQ ==
> 
> 使用你提供的 URL 无法复现： <img alt="图片" width="1344" src="https://user-images.githubusercontent.com/19235246/152943101-caff76a7-a2b9-4223-97c3-bc7005df917f.png">

直接添加节点是没问题的 但是当这个节点在订阅中是就会出现问题

**Comment by Gaojianli** [comment]
> > > vmess：// ew0KICAidiI6ICIyIiwNCiAgInBzIjogInRlc3RfdGVzdC10ZXN0X3Rlc3QiLA0KICAiYWRkIjogInRlc3QudGVzdC50ZXN0LnRlc3QiLA0KICAicG9ydCI6ICIxMjM0NSIsDQogICJpZCI6ICI5ZDA0MjEwZC05NWViLTQzNDUtYjM5MS1mY2VhODg4YTdlM2UiLA0KICAiYWlkIjogIjAiLA0KICAic2N5IjogImF1dG8iLA0KICAibmV0IjogIndzIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogInRlc3QudGVzdC50ZXN0LnRlc3QiLA0KICAicGF0aCI6ICIvdGVzdHRlc3R0ZXN0dGVzdCIsDQogICJ0bHMiOiAidGxzIiwNCiAgInNuaSI6ICJ0ZXN0LnRlc3QudGVzdC50ZXN0IiwNCiAgImFscG4iOiAiIg0KfQ ==
> > 
> > 
> > 使用你提供的 URL 无法复现： <img alt="图片" width="1344" src="https://user-images.githubusercontent.com/19235246/152943101-caff76a7-a2b9-4223-97c3-bc7005df917f.png">
> 
> 直接添加节点是没问题的 但是当这个节点在订阅中是就会出现问题

可否提供一个问题订阅返回值的样本

**Comment by FanLuoh** [comment]
> > > > vmess：// ew0KICAidiI6ICIyIiwNCiAgInBzIjogInRlc3RfdGVzdC10ZXN0X3Rlc3QiLA0KICAiYWRkIjogInRlc3QudGVzdC50ZXN0LnRlc3QiLA0KICAicG9ydCI6ICIxMjM0NSIsDQogICJpZCI6ICI5ZDA0MjEwZC05NWViLTQzNDUtYjM5MS1mY2VhODg4YTdlM2UiLA0KICAiYWlkIjogIjAiLA0KICAic2N5IjogImF1dG8iLA0KICAibmV0IjogIndzIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogInRlc3QudGVzdC50ZXN0LnRlc3QiLA0KICAicGF0aCI6ICIvdGVzdHRlc3R0ZXN0dGVzdCIsDQogICJ0bHMiOiAidGxzIiwNCiAgInNuaSI6ICJ0ZXN0LnRlc3QudGVzdC50ZXN0IiwNCiAgImFscG4iOiAiIg0KfQ ==
> > > 
> > > 
> > > 使用你提供的 URL 无法复现： <img alt="图片" width="1344" src="https://user-images.githubusercontent.com/19235246/152943101-caff76a7-a2b9-4223-97c3-bc7005df917f.png">
> > 
> > 
> > 直接添加节点是没问题的 但是当这个节点在订阅中是就会出现问题
> 
> 可否提供一个问题订阅返回值的样本

https://raw.githubusercontent.com/FanLuoh/test/main/1.txt

**Comment by cubercsl** [comment]
看起来是你的 base64 编码 每 76 个字符进行了换行造成的。

**Comment by FanLuoh** [comment]
> 看起来是你的 base64 编码 每 76 个字符进行了换行造成的。

用的win10自带的base64编码 
certutil -encode 1.txt 2.txt

别的节点也是多行输出的 v2raya里正常订阅

**Comment by cubercsl** [comment]
根据 [RFC2045](https://datatracker.ietf.org/doc/html/rfc2045#section-6.7):

> The Quoted-Printable encoding REQUIRES that encoded lines be no more than 76 characters long. If longer lines are to be encoded with the Quoted-Printable encoding, "soft" line breaks must be used.

代码中确实没有考虑 base64 编码结果中 76 个字符换行的情况。

**Comment by 2635064692** [comment]
确实，自定义添加的节点若存在于订阅链接的节点中，就会出现这个问题

**Comment by mzz2017** [comment]
已修复于 1.5.8
