### ISSUE TITLE
无法连接节点

### ISSUE THREAD

**Issue by roderickbao** [v2rayA/v2rayA#407]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v1.5.6.2
2. 你通过什么方式安装v2rayA
alpine/docker
3. 你所使用的操作系统
alpine/Ubuntu

### 描述问题：

在v2rayN上可以使用的配置，使用aphine及docker情况一样，订阅链接解析正常，ping服务器显示0ms，HTTP显示NOT STABLE,局域网代理不工作。

### v2rayA运行日志（Optional）：
2022/02/08 22:38:00.782 [A] [main.go:25]  network is connected
2022/02/08 22:38:01.354 [A] [main.go:27]  V2Ray binary is /usr/bin/v2ray
2022/02/08 22:38:01.355 [A] [main.go:27]  V2Ray asset directory is /run/user/0/v2raya
2022/02/08 22:38:01.355 [A] [main.go:27]  v2rayA working directory is /root
2022/02/08 22:38:01.355 [A] [main.go:27]  v2rayA configuration directory is /etc/v2raya
2022/02/08 22:38:01.355 [A] [main.go:27]  Golang: go1.17.6
2022/02/08 22:38:01.355 [A] [main.go:27]  OS: linux
2022/02/08 22:38:01.355 [A] [main.go:27]  Arch: amd64
2022/02/08 22:38:01.355 [A] [main.go:27]  Lite: false
2022/02/08 22:38:01.355 [A] [main.go:27]  Version: 1.5.6.2
2022/02/08 22:38:01.355 [A] [main.go:27]  Starting...
2022/02/08 22:38:03.473 [I] [io.go:425]  V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)
2022/02/08 22:38:03.473 [I] [io.go:425]  A unified platform for anti-censorship.
2022/02/08 22:38:03.474 [I] [io.go:425]  [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/02/08 22:38:04.832 [I] [asm_amd64.s:1581]  down<geosite.dat> 1167151-2334301

2022/02/08 22:38:04.832 [I] [asm_amd64.s:1581]  down<geosite.dat> 3501453-4668604

2022/02/08 22:38:04.832 [I] [asm_amd64.s:1581]  down<geosite.dat> 2334302-3501452

2022/02/08 22:38:04.833 [I] [asm_amd64.s:1581]  down<geosite.dat> 0-1167150

2022/02/08 22:38:04.881 [I] [asm_amd64.s:1581]  [AutoUpdate] Subscriptions: Complete updating subscription -- ID: 0，Address: https://xxx.cc?sub=111
2022/02/08 22:38:05.298 [I] [io.go:425]  127.0.0.1:44940 accepted tcp:127.0.0.1:0 [api-out]
2022/02/08 22:38:05.635 [I] [io.go:425]  127.0.0.1:44942 accepted tcp:127.0.0.1:0 [api-out]
2022/02/08 22:38:07.490 [I] [gfwlist.go:166]  download[1]: https://hubmirror.v2raya.org/v2rayA/dist-v2ray-rules-dat/raw/202202012210/geosite.dat -> SUCCESS

2022/02/08 22:38:09.687 [A] [index.go:117]  v2rayA is listening at http://127.0.0.1:2017
2022/02/08 22:38:09.687 [A] [index.go:117]  v2rayA is listening at http://192.168.1.99:2017
2022/02/08 22:38:09.687 [A] [index.go:117]  v2rayA is listening at http://192.168.10.99:2017
2022/02/08 22:38:09.687 [A] [index.go:117]  v2rayA is listening at http://192.168.11.99:2017
2022/02/08 22:38:09.687 [A] [index.go:117]  v2rayA is listening at http://10.0.3.1:2017
2022/02/08 22:38:09.687 [A] [index.go:117]  v2rayA is listening at http://172.17.0.1:2017
2022/02/08 22:38:09.687 [A] [index.go:117]  v2rayA is listening at http://172.21.0.1:2017
2022/02/08 22:38:09.687 [A] [index.go:117]  v2rayA is listening at http://172.30.32.1:2017
2022/02/08 22:38:09.687 [A] [index.go:117]  v2rayA is listening at http://172.18.0.1:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://172.19.0.1:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://172.22.0.1:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://172.20.0.1:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[::1]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::1425:d7ff:fe95:d17a]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::3029:58ff:fe36:5fa3]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::f8cc:5eff:fec1:6519]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::42:f4ff:fe5d:6f13]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::42:6aff:fe5e:8033]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::42:14ff:fe64:21aa]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::42:77ff:fe61:c5e7]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::42:2aff:fedd:b4d8]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::42:b2ff:fe48:6d3b]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::4806:e1ff:fe80:665]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::d81f:cdff:fedd:9f95]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::94ef:44ff:fe38:ed50]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::f05b:50ff:fe01:4697]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::e482:a4ff:fe06:2a5c]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::c802:c3ff:fe32:e21f]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::38b2:93ff:feed:4998]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::dce3:f7ff:fe1f:5e53]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::d826:dfff:feba:c3a6]:2017
2022/02/08 22:38:09.688 [A] [index.go:117]  v2rayA is listening at http://[fe80::bc57:dfff:fecf:1294]:2017
2022/02/08 22:38:10.621 [W] [asm_amd64.s:1581]  ObservatoryProducer: did not connect: context deadline exceeded
2022/02/08 22:38:10.671 [I] [io.go:425]  V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)
2022/02/08 22:38:10.671 [I] [io.go:425]  A unified platform for anti-censorship.
2022/02/08 22:38:10.671 [I] [io.go:425]  [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/02/08 22:38:11.280 [I] [io.go:425]  127.0.0.1:50066 accepted tcp:127.0.0.1:0 [api-out]
2022/02/08 22:38:11.622 [I] [io.go:425]  127.0.0.1:50068 accepted tcp:127.0.0.1:0 [api-out]
2022/02/08 22:38:14.559 [I] [asm_amd64.s:1581]  Complete updating PAC file. Localtime: 2022-02-02
2022/02/08 22:38:22.399 [I] [io.go:425]  192.168.11.99:41248 accepted udp:223.6.6.6:53 [dns-out]
2022/02/08 22:38:22.399 [I] [io.go:425]  192.168.11.99:36245 accepted udp:223.6.6.6:53 [dns-out]
2022/02/08 22:38:29.165 [W] [asm_amd64.s:1581]  ObservatoryProducer: did not connect: context deadline exceeded
2022/02/08 22:38:30.166 [W] [asm_amd64.s:1581]  ObservatoryProducer: did not connect: context deadline exceeded
2022/02/08 22:38:30.743 [I] [io.go:425]  V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)
2022/02/08 22:38:30.743 [I] [io.go:425]  A unified platform for anti-censorship.
2022/02/08 22:38:30.745 [I] [io.go:425]  [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/02/08 22:38:31.167 [W] [asm_amd64.s:1581]  ObservatoryProducer: did not connect: context deadline exceeded
2022/02/08 22:38:31.354 [I] [io.go:425]  127.0.0.1:59800 accepted tcp:127.0.0.1:0 [api-out]
2022/02/08 22:38:32.169 [I] [io.go:425]  127.0.0.1:59802 accepted tcp:127.0.0.1:0 [api-out]
2022/02/08 22:38:34.200 [I] [io.go:425]  tcp:127.0.0.1:46568 accepted tcp:gstatic.com:443 [outbound46397]
2022/02/08 22:38:34.200 [I] [io.go:425]  192.168.11.99:35610 accepted udp:223.6.6.6:53 [dns-out]
2022/02/08 22:38:34.201 [I] [io.go:425]  192.168.11.99:52288 accepted udp:223.6.6.6:53 [dns-out]
2022/02/08 22:38:37.928 [I] [io.go:425]  V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)
2022/02/08 22:38:37.928 [I] [io.go:425]  A unified platform for anti-censorship.
2022/02/08 22:38:37.929 [I] [io.go:425]  [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/02/08 22:38:38.215 [W] [asm_amd64.s:1581]  ObservatoryProducer: did not connect: context deadline exceeded
2022/02/08 22:38:38.527 [I] [io.go:425]  127.0.0.1:34270 accepted tcp:127.0.0.1:0 [api-out]
2022/02/08 22:38:39.217 [I] [io.go:425]  127.0.0.1:34272 accepted tcp:127.0.0.1:0 [api-out]
2022/02/08 22:38:51.215 [I] [io.go:425]  192.168.11.99:55816 accepted udp:223.6.6.6:53 [dns-out]

### v2rayA设置以及相关截图
![image](https://user-images.githubusercontent.com/5802783/153013676-f9dffad2-333b-4e46-8612-d9856ed01131.png)
![image](https://user-images.githubusercontent.com/5802783/153013986-005f5ccb-0bbc-4a9f-af4c-1db1a51580ae.png)
![image](https://user-images.githubusercontent.com/5802783/153014035-11ae961d-6493-4751-98bf-62fd8e997abb.png)

**Comment by mzz2017** [comment]
1.5.6 不支持 AlterID>0 的 VMess 节点。
