### ISSUE TITLE
设置了透明代理，局域网机器无法通过设置网关访问国外网站

### ISSUE THREAD

**Issue by Kaol-Fu** [v2rayA/v2rayA#408]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.5.6.2
2. What approach of installation do you install V2rayA?
Docker
3. What is your operating system?
Ubuntu 20.04.3 LTS

### Description
设置透明代理时，局域网的另一台机器设置v2rayA的地址为网关，可以访问国内的地址，但是无法访问国外的地址。在v2rayA上执行`http_proxy=localhost:20171 https_proxy=localhost:20171 curl -v google.com` 输出如下：

```bash
# http_proxy=localhost:20171 https_proxy=localhost:20171 curl -v google.com
* Uses proxy env variable http_proxy == 'localhost:20171'
*   Trying 127.0.0.1:20171...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 20171 (#0)
> GET http://google.com/ HTTP/1.1
> Host: google.com
> User-Agent: curl/7.68.0
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Content-Length: 219
< Cache-Control: public, max-age=2592000
< Connection: keep-alive
< Content-Type: text/html; charset=UTF-8
< Date: Tue, 08 Feb 2022 15:09:37 GMT
< Expires: Thu, 10 Mar 2022 15:09:37 GMT
< Keep-Alive: timeout=4
< Location: http://www.google.com/
< Proxy-Connection: keep-alive
< Server: gws
< X-Frame-Options: SAMEORIGIN
< X-Xss-Protection: 0
< 
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
* Connection #0 to host localhost left intact
```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.
![image](https://user-images.githubusercontent.com/18643104/153019112-6b7715ae-5306-47aa-9900-524be49bb027.png)
![image](https://user-images.githubusercontent.com/18643104/153019209-e02d3462-2c19-42ed-9644-6f66fd30b71f.png)

**Comment by mzz2017** [comment]
@Kaol-Fu 有没有另一台机器直接curl -v google.com的信息？

**Comment by Kaol-Fu** [comment]
额，其它的机器是windows的了。我从运行的日志上看，感觉像没有走代理一样全部都是direct的记录。
另外，我还发现了个问题，无论是docker安装的，还是apt直接安装的，只要运行了V2raya，其它容器就无法访问外网的443端口了，这是为什么？V2raya启动的时候还更改了iptables的规则么？

**Comment by mzz2017** [comment]
首先开启ip转发。https://v2raya.org/docs/advanced-application/specify-container-proxy/

其他机器不能上网，检查是否特定域名有dns污染。

**Comment by Kaol-Fu** [comment]
IP 转发开启了的，用 docker 版的局域网机器无法访问国外网站，直接安装的就没这个问题。感觉还是 docker image 中的某些设置出了问题。

另外，我确定容器无法访问外网 443 端口，不是 DNS 的问题，就是 V2raya 造成的，只要开了V2raya就不行，关了的话马上就好了。

**Comment by MarksonHon** [comment]
长时间未回复，issue关闭。
有需要可以进群： 
<https://t.me/v2raya_zh>
