### ISSUE TITLE
give the option to enable allowinsecure

### ISSUE THREAD

**Issue by iamtrazy** [v2rayA/v2rayA#410]
### Content of the feature

i know this is a stupid request because you are not supposed to enable allowinsecure in any way. but for my use case and there are many others who does this , allowing insecure SNIs is a must have feature . like in my country to bypass censorship we need to modify the SNI with something like facebook.com or twitter.com , cant do that without enabling allowinsecure . please give some way to enable that

**Comment by essoojay** [comment]
+1

V2raya is well thought out very well supported as well, but for some of us, we can afford to allowinsecure, this would be a welcomed option to have, Some proxies like Sagernet, V2rayNG, AnXray etc have it and with a cavaet. Please make this an option.

**Comment by essoojay** [comment]
Thanks for this, can you please check gRPC and tcp etc. (GUI options is fine, but seems option not applied,   Websocket works.

**Comment by malikshi** [comment]
#414 I tried to import an account Vless the prompt would show up whatever the Allowinsecure true or not? isn't only showing up when Allowinsecure true?

**Comment by malikshi** [comment]
@Gaojianli tyvm. it's fixed
