### ISSUE TITLE
这个是什么问题

### ISSUE THREAD

**Issue by Potterli20** [v2rayA/v2rayA#411]
root@nas:/usr/local/bin    /usr/local/bin/v2ray
A unified platform for anti-censorship.

Usage:

	v2ray <command> [arguments]

The commands are:

	run           run V2Ray with config
	api           call V2Ray API
	convert       convert config files
	test          test config files
	tls           TLS tools
	uuid          generate new UUID
	verify        verify if a binary is officially signed
	version       print V2Ray version

Use "v2ray help <command>" for more information about a command.

Additional help topics:

	config-merge  config merge logic
	format-loader config formats and loading

Use "v2ray help <topic>" for more information about that topic.

root@nas:/usr/local/bin    v2raya
2022/02/10 15:07:31.513 [A] [main.go:25]  network is connected
2022/02/10 15:07:31.758 [A] [main.go:27]  V2Ray binary is /usr/local/bin/v2ray
2022/02/10 15:07:31.758 [A] [main.go:27]  V2Ray asset directory is /run/user/1000/v2raya
2022/02/10 15:07:31.759 [A] [main.go:27]  v2rayA working directory is /usr/local/bin
2022/02/10 15:07:31.759 [A] [main.go:27]  v2rayA configuration directory is /etc/v2raya
2022/02/10 15:07:31.760 [A] [main.go:27]  Golang: go1.17.6
2022/02/10 15:07:31.760 [A] [main.go:27]  OS: linux
2022/02/10 15:07:31.760 [A] [main.go:27]  Arch: amd64
2022/02/10 15:07:31.761 [A] [main.go:27]  Lite: false
2022/02/10 15:07:31.761 [A] [main.go:27]  Version: 1.5.6.2
2022/02/10 15:07:31.762 [A] [main.go:27]  Starting...
2022/02/10 15:07:31.803 [A] [index.go:117]  v2rayA is listening at http://127.0.0.1:2017
2022/02/10 15:07:31.803 [A] [index.go:117]  v2rayA is listening at http://192.168.2.3:2017
2022/02/10 15:07:31.803 [A] [index.go:117]  v2rayA is listening at http://[::1]:2017
2022/02/10 15:07:31.803 [A] [index.go:117]  v2rayA is listening at http://[fe80::5054:ff:fe91:d2f2]:2017
2022/02/10 15:07:54.594 [E] [gfwlist.go:12]  latest version is 2022-02-09. GFWList is up to date
2022/02/10 15:08:07.183 [I] [io.go:425]  flag provided but not defined: -config
2022/02/10 15:08:07.183 [I] [io.go:425]  Usage of /usr/local/bin/v2ray:
2022/02/10 15:08:07.186 [W] [asm_amd64.s:1581]  v2ray-core: exit status 2
2022/02/10 15:08:07.335 [E] [connection.go:88]  failed to start v2ray-core: unexpected exiting: check the log for more information

**Comment by mzz2017** [comment]
@Potterli20 使用 4.40.0 而不是 v5

**Comment by Potterli20** [comment]
> @Potterli20 使用 4.40.0 而不是 v5

我是根着那个wiki 的debian来安装，他启动也是没有内核

**Comment by mzz2017** [comment]
@Potterli20 删掉 /usr/local/bin/v2ray 重新安装

**Comment by Potterli20** [comment]
> @Potterli20 删掉 /usr/local/bin/v2ray 重新安装
![2022-02-10 15-19-17 的屏幕截图](https://user-images.githubusercontent.com/28734349/153357186-d8999a36-ef64-4608-b902-7ad8957ef426.png)
![2022-02-10 15-20-03 的屏幕截图](https://user-images.githubusercontent.com/28734349/153357221-b09f65b1-ecb8-4253-a3b1-c222aa3b6731.png)

**Comment by mzz2017** [comment]
@Potterli20 重新安装 v2ray

**Comment by Potterli20** [comment]
> @Potterli20 重新安装 v2ray

https://v2raya.org/docs/prologue/installation/debian/ 这个？？

**Comment by MarksonHon** [comment]
长时间无回应，issue先关闭。有需要可以进群： 
<https://t.me/v2raya_zh>
