### ISSUE TITLE
Move logs to /var/log in accordance with FHS 3.0

### ISSUE THREAD

**Issue by InvisibleRain** [v2rayA/v2rayA#415]
### Move logs to /var/log in accordance with [FHS 3.0](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf)
[Currently](https://github.com/v2rayA/v2rayA/blob/5539609fc0b7e8dda8a0d5f2b77f856239012377/install/universal/v2raya.service), logs are being written to /tmp, which might be a concern for a number of reasons:
+ Logs might be deleted by the system on boot (Debian) or if the log file hasn't been modified for 10 days (Fedora).
+ Some users mount /tmp on RAM, and large log files can quickly exhaust partition's free space
+ Log rotation, though possible, might require some unorthodox solutions
+ Most distros won't accept a non-FHS compliant package to their official repos

This can be solved by running a shell script before the installation. The script should create the `/var/log/v2raya.log` file, set ownership to something like `root:v2raya` and permissions to `0664`. The non-root systemd unit should be modified as well, forcing usage of `v2raya` user

The script can be added to the packages via fpm's `--before-install` flag

**Comment by mzz2017** [comment]
It has been discussed by us. The biggest problem is as you said, v2raya@.service cannot rotate.

New user makes no sense, because we do not know which user will people use, and we could not limit user to use v2raya like v2raya@v2raya.service.

Maybe the only way is that we redesign the sercice like v2raya-user.sercive, and make a directory /var/log/v2raya/ and write logs into it to keep rotating.

More discussions is needed in this issue.

**Comment by InvisibleRain** [comment]
>the only way is that we redesign the sercice like v2raya-user.sercive with running user as v2raya, and make a directory /var/log/v2raya/, chown to v2raya and write logs into it to keep rotating.

That sounds like the best solution. 

It's even possible to have 3 systemd units if there's such need. One for root, second for the v2raya user, and third for an arbitrary user. The one for an arbitrary user should write logs to a corresponding user-specific log file (e.g. `/var/log/v2raya/v2raya-myuser.log`). This solution with 3 units, however, may be too loose, since it requires 777 permissions on the v2raya directory.

So, if this possible, I would deprecate `v2raya@.service` in favor of `v2raya-user.sercive`

**Comment by cubercsl** [comment]
Maybe we can create a user unit (e.g. `v2raya-lite.sercive`).

As it is mentioned in the man page ` systemd.unit (5) `:
```
       ┌──────────┬─────────────────────────────┬─────────────────────────────┐
       │"%L"      │ Log directory root          │ This is either /var/log     │
       │          │                             │ (for the system manager) or │
       │          │                             │ the path "$XDG_CONFIG_HOME" │
       │          │                             │ resolves to with /log       │
       │          │                             │ appended (for user          │
       │          │                             │ managers).                  │
       └──────────┴─────────────────────────────┴─────────────────────────────┘

```

And I think the definition of `%L` can be used for our log path in both system unit `v2ray.service` and user unit `v2raya-lite.service`.

**Comment by cubercsl** [comment]
If we deprecate `v2raya@.service`, we also should implement a post_upgrade hook to notify user migrating to a new one.

**Comment by InvisibleRain** [comment]
Just tested it on Ubuntu. It seems like the execution flag on `/usr/bin/v2raya` is missing, so the systemd unit fails with error 203.

Also, this is optional, but I think it would be nice to highlight the warning in post_upgrade in bold orange, so it'll look something like that: 
`echo -e "\e[01;38;5;208mWARN: v2raya@.service was deprecated; please use user service v2raya-lite.service instead.\e[0m"`

If not counting these minor issues, the new unit looks great!

**Comment by mzz2017** [comment]
I have no idea why the execution flag on `/usr/bin/v2raya` is missing. I did not change the `ExecStart`.

Could you please help us look into it?

**Comment by InvisibleRain** [comment]
Sorry, my bad. I just copy-pasted GitHub's workflow into a bash script in a wrong way.

Also, I think it may be a good idea to move the log file to a separate directory (So it will be `/var/log/v2raya/v2raya.log`). This will keep /var/log/ a little bit cleaner and will help with multiple log files (e.g. when log rotation happens)

**Comment by mzz2017** [comment]
@InvisibleRain good idea
