### ISSUE TITLE
支持自定义ping 或Http 测试的域名IP地址?

### ISSUE THREAD

**Issue by isfong** [v2rayA/v2rayA#418]
### 功能特性内容
***支持自定义ping 或Http 测试的域名IP地址?***

![Screen Shot 2022-02-16 at 21 43 25](https://user-images.githubusercontent.com/25047541/154278781-a9079127-376f-4b55-aad6-7aa906dd4237.png)

**Comment by MarksonHon** [comment]
这是一件使用操作系统自带的 `ping` 或者 `curl` 命令就能做到的事情，与 v2rayA 代理软件的定位不符合。
