### ISSUE TITLE
docker 安装怎么是个白色的啥也没有，demo站也是

### ISSUE THREAD

**Issue by xu1991** [v2rayA/v2rayA#420]
### 版本、安装方式、系统
![1645149924(1)](https://user-images.githubusercontent.com/7221999/154603813-ebab1bec-8dc4-4f90-ae06-8393c5239482.png)
![1645149939(1)](https://user-images.githubusercontent.com/7221999/154603838-9469d31e-c7f6-4a82-b053-2d279ce9279a.png)

1. 你在使用什么版本的v2rayA
1.installer_debian_armhf_1.5.6.2.deb
2. 你通过什么方式安装v2rayA
installer_debian_armhf_1.5.6.2.deb
3. 你所使用的操作系统
Ubuntu arm32 v7

### 描述问题

docker 安装怎么是个白色的啥也没有，demo站也是

### 复现问题的步骤

docker 安装怎么是个白色的啥也没有，demo站也是
### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
描述不全，无法排查
