### ISSUE TITLE
不支持 alterId>0 的 VMESS

### ISSUE THREAD

**Issue by YidaozhanYa** [v2rayA/v2rayA#423]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

1.5.6.2

2. 你通过什么方式安装v2rayA

操作系统的包管理器

3. 你所使用的操作系统

Arch Linux

### 描述问题

自从最近几个版本开始，v2rayA 开始不支持 alterId>0（比如4）的 VMESS 节点，连接后查看 /etc/v2raya/config.json ，user 数组中也没有 alterId 项。
此更改导致很多节点无法使用，因为很多节点的 alterId 都是 4，希望添加回对高 alterId 的支持。
如果是本项目不打算支持高 alterId，望给出原因，谢谢！

### 复现问题的步骤

连接一个节点

### v2rayA/v2ray运行日志：
```
2月 19 21:58:49 yidaozhan-PC v2raya[528]: [I] [io.go:425]  Xray 1.5.3 (Xray, Penetrates Everything.) Custom (go1.17.6 linux/amd64)
2月 19 21:58:49 yidaozhan-PC v2raya[528]: [I] [io.go:425]  A unified platform for anti-censorship.
2月 19 21:58:49 yidaozhan-PC v2raya[528]: [I] [io.go:425]  [Info] infra/conf/serial: Reading config: /etc/v2raya/config.json
2月 19 21:58:50 yidaozhan-PC v2raya[528]: [I] [io.go:425]  127.0.0.1:41364 accepted tcp:127.0.0.1:0 [api-out]
2月 19 21:59:46 yidaozhan-PC v2raya[528]: [I] [io.go:425]  192.168.51.6:34360 accepted tcp:20.205.243.166:443 [proxy]
2月 19 21:59:47 yidaozhan-PC v2raya[528]: [I] [io.go:425]  192.168.51.6:48666 accepted tcp:140.82.112.21:443 [proxy]
2月 19 21:59:47 yidaozhan-PC v2raya[528]: [I] [io.go:425]  192.168.51.6:36554 accepted tcp:172.217.163.42:443 [proxy]
2月 19 21:59:49 yidaozhan-PC v2raya[528]: [I] [io.go:425]  192.168.51.6:35020 accepted tcp:185.199.108.133:443 [proxy]
2月 19 22:00:30 yidaozhan-PC v2raya[528]: [I] [io.go:425]  192.168.51.6:52968 accepted tcp:124.95.173.179:443 [direct]
```

### v2rayA设置以及相关截图
![image](https://user-images.githubusercontent.com/73830635/154804000-855b4eaf-5b39-4159-87c4-66177771b39b.png)
![image](https://user-images.githubusercontent.com/73830635/154804005-9f3c013d-8c58-48f9-84b6-96fb62a08885.png)

**Comment by mzz2017** [comment]
@YidaozhanYa 是的，详见 v1.5.6 的 release 介绍。你也可以退回 v1.5.5。

**Comment by YidaozhanYa** [comment]
release 里只写了一句 `Removed AlterID for VMess.`，有点感兴趣为什么要删掉这个功能，是因为会导致 bug，还是会引起安全性问题呢？明明挺多节点都使用 AlterID 的

**Comment by mzz2017** [comment]
@YidaozhanYa 原因为落后的安全性，见 [v2fly docs](https://www.v2fly.org/config/protocols/vmess.html#vmess-md5-%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF-%E6%B7%98%E6%B1%B0%E6%9C%BA%E5%88%B6)

**Comment by imxys** [comment]
有一点点建议，如果能指明链接不上服务器的原因不是NOT STABLE或者TIMEOUT，而是说明不支持alterId>0就更好了，还好这边找了issue知道了原因
