### ISSUE TITLE
docker的latest标签pull下来是1.5.5版本，而不是最新的1.5.6.2

### ISSUE THREAD

**Issue by BladPit** [v2rayA/v2rayA#425]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
从1.5.2版本的docker升级到最新版本（webUI提示最新的是1.5.6.2）

2. 你通过什么方式安装v2rayA
docker

3. 你所使用的操作系统
unraid

### 描述问题：

通过系统自带的docker面板，使用latest标签pull下来的版本是1.5.5（webUI打开时提示的）
改为1.5.6.2标签后，pull下来的版本确实又是1.5.6.2
以上问题经过反复pull后确认，怀疑latest标签是不是设置有些错误

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![1](https://user-images.githubusercontent.com/90924194/155765041-c943b59c-12bf-48c1-b0d2-fa427cac3b0f.png)
![1-2](https://user-images.githubusercontent.com/90924194/155765300-b0f9e8c0-1e90-4494-b39a-d0232a50c202.png)

2022/02/26 02:00:50.444 [1;36m[A][0m [main.go:25] network is connected
2022/02/26 02:00:51.047 [1;36m[A][0m [main.go:27] V2RayLocationAsset is /usr/local/share/v2ray
2022/02/26 02:00:51.047 [1;36m[A][0m [main.go:27] V2Ray binary is /usr/bin/v2ray
2022/02/26 02:00:51.047 [1;36m[A][0m [main.go:27] v2rayA working directory is /root
2022/02/26 02:00:51.047 [1;36m[A][0m [main.go:27] v2rayA configuration directory is /etc/v2raya
2022/02/26 02:00:51.047 [1;36m[A][0m [main.go:27] Golang: go1.17.4
2022/02/26 02:00:51.047 [1;36m[A][0m [main.go:27] OS: linux
2022/02/26 02:00:51.047 [1;36m[A][0m [main.go:27] Arch: amd64
2022/02/26 02:00:51.047 [1;36m[A][0m [main.go:27] Lite: false
2022/02/26 02:00:51.047 [1;36m[A][0m [main.go:27] Version: 1.5.5

2022/02/26 02:00:51.047 [1;36m[A][0m [main.go:27] Starting...
2022/02/26 02:00:51.048 [1;36m[A][0m [index.go:131] v2rayA is listening at http://127.0.0.1:2017

**Comment by BladPit** [comment]
顺便问一下，订阅地址没有保存到/etc/v2raya配置目录吗，更新容器后，订阅地址就没有了，得重新创建

**Comment by cubercsl** [comment]
> 顺便问一下，订阅地址没有保存到/etc/v2raya配置目录吗，更新容器后，订阅地址就没有了，得重新创建

https://github.com/v2rayA/v2rayA/releases/tag/v1.5.6.2

v1.5.5 起数据库格式不兼容。

**Comment by cubercsl** [comment]
https://hub.docker.com/r/mzz2017/v2raya/tags

从这边看上对的

**Comment by BladPit** [comment]
> > 顺便问一下，订阅地址没有保存到/etc/v2raya配置目录吗，更新容器后，订阅地址就没有了，得重新创建
> 
> https://github.com/v2rayA/v2rayA/releases/tag/v1.5.6.2
> 
> v1.5.5 起数据库格式不兼容。

感谢回复，没注意看之前的release note。routingA策略丢失估计也是因为这个原因了~

**Comment by BladPit** [comment]
> https://hub.docker.com/r/mzz2017/v2raya/tags
> 
> 从这边看上对的

我也对比过tag，看起来确实latest和1.5.6.2是一样的，但不知道为什么pull下来就是不对

**Comment by mzz2017** [comment]
@BladPit Manjaro 测试 latest 是 1.5.6.2，请检查你的 docker pull 是否使用了镜像缓存

**Comment by BladPit** [comment]
> @BladPit Manjaro 测试 latest 是 1.5.6.2，请检查你的 docker pull 是否使用了镜像缓存

大佬们都是这么晚睡吗。。。。
镜像缓存我不是很懂，但是我用了1.5.6.2的tag pull下来1.5.6.2版本后，重新用latest又pull了一次，还是回到1.5.5了，不知道能不能排除镜像缓存的问题

**Comment by mzz2017** [comment]
@BladPit 你的操作系统可能对 docker 有自己的镜像缓存

**Comment by BladPit** [comment]
> @BladPit unraid 可能对 docker 有自己的镜像缓存

好的，那我再去研究一下unraid的镜像机制，看看是否缓存导致的问题，感谢回复

**Comment by mzz2017** [comment]
@BladPit 是的，我认为可能是 unraid 的上游并不直接使用 hub.docker.com，而是自己的镜像站，类似 daocloud 和 aliyun 提供的镜像站

**Comment by BladPit** [comment]
确认了，确实是阿里云的镜像太久没有更新了，版本一直停留在1.5.5
去掉镜像地址，从官方pull的latest确实是1.5.6.2
问题解决，关闭了
