### ISSUE TITLE
v2ray core下载后放哪个文件夹下面？

### ISSUE THREAD

**Issue by xiaokentrl** [v2rayA/v2rayA#428]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2rayA服务端正在运行，Version: 1.5.6.2

3. 你通过什么方式安装v2rayA

照着这里安装的
https://blog.51cto.com/feko/2747064 

4. 你所使用的操作系统

deepin20.4

### 描述问题：

failed to start v2ray-core: failed: no server is selected. please select at least one server

v2ray-core放在哪个目录呢？ 我安装后/etc/v2raya/里面只有两个配置文件
![Uploading image.png…]()

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50

Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- No entries --

 
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by cubercsl** [comment]
no server is selected. please select at least one server

你倒是选一个服务器再点连接啊
