### ISSUE TITLE
重密码后双击v2raya图标打开127.0.0.1:2017但不显示图形界面，直接输入0.0.0.0:2017可以显示

### ISSUE THREAD

**Issue by TannerTam** [v2rayA/v2rayA#432]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.6.2
2. 你通过什么方式安装v2rayA
通过软件源安装
3. 你所使用的操作系统
Ubuntu 18.04

### 描述问题：

重密码后双击v2raya图标打开127.0.0.1:2017但不显示图形界面，直接输入0.0.0.0:2017可以显示
在设置里修改端口无反应

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@TannerTam 1，重启 2，刷新

**Comment by TannerTam** [comment]
在快捷方式的页面刷新解决问题，谢谢大佬
