### ISSUE TITLE
以xray-core多路复用

### ISSUE THREAD

**Issue by Six-6Chen** [v2rayA/v2rayA#434]
在xray-core 上使用 多路复用时 无法正常工作
而单路 时一切正常

**Comment by MarksonHon** [comment]
@Six-6Chen 如果你的服务端是v2ray，那么你会遇到多路复用的兼容性问题。

**Comment by Six-6Chen** [comment]
我的 服务端是 Xray

**Comment by sommio** [comment]
xray-core [不支持基于观测的负载均衡](https://v2raya.org/docs/prologue/quick-start/#%E8%BF%9E%E6%8E%A5%E8%8A%82%E7%82%B9%E5%92%8C%E5%90%AF%E5%8A%A8%E6%9C%8D%E5%8A%A1)
