### ISSUE TITLE
无法访问远程局域网

### ISSUE THREAD

**Issue by ASSANDHOLE** [v2rayA/v2rayA#436]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.5.6.2 Latest release
2. What approach of installation do you install V2rayA?
apt 源
3. What is your operating system?
Ubuntu 20.04 LTS

### Description
我有一台机器在内网，我想访问内网网站（域名解析到内网）。用n2n vpn 接到了本机192.168.100.1上，可以ping通。该台机器上同样也安装了v2raya，设置了ip(geoip:private)->direct，有http分流端口10809。curl -x 可以访问内网网站。我用本机加了一个http出口，routingA配置了该网站走该出口（域名和局域网ip（nslookup）），不能进入，curl不加代理也不行。我以为是http的outbound有问题，加上了baidu和google hk到该节点，搜索ip出来的都是正确地地址（ip地区不同）。我使用的代理方式是tproxy，同时也测试过redirect，也不行。

### Logs：
都是 info，没有报错，没有相应内网ip地址出现。

### v2rayA setting and related screenshot
![image](https://user-images.githubusercontent.com/63102113/156500033-5bc375f0-90cf-4d52-92e0-0442669c99b9.png)

**Comment by mzz2017** [comment]
@ASSANDHOLE v2raya的透明代理默认是略过局域网的，也就是局域网部分不走代理

**Comment by ASSANDHOLE** [comment]
好的，我自己改一下试试

**Comment by mzz2017** [comment]
@ASSANDHOLE 你可以尝试对 iptables 规则进行修改

**Comment by ZRJ026** [comment]
我也遇到了同样的问题，想让目标地址是局域网的IP也走代理，请问您解决这个问题了吗

**Comment by ASSANDHOLE** [comment]
> 我也遇到了同样的问题，想让目标地址是局域网的IP也走代理，请问您解决这个问题了吗

我不太会iptables😵‍💫，我当时是设置了个[frp](https://github.com/fatedier/frp)内网穿透。不过现在有chatgpt，你愿意折腾可以试试问问它🤪
