### ISSUE TITLE
在 Windows 7/8.1 上更改状态后，需要手动刷新代理设置才可正常上网

### ISSUE THREAD

**Issue by People-11** [v2rayA/v2rayA#439]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.6.2
2. 你通过什么方式安装v2rayA
Windows 安装包
3. 你所使用的操作系统
Windows 7 旗舰版
Windows 8.1 专业版

### 描述问题：
在V2RayA控制网页上进行任何会影响连接状态（例如连接节点，断开连接，在连接状态时更改节点配置，在连接状态时更改V2RayA设置）的操作后无法正常上网 （如图一）。
除非打开 ”局域网设置“ 并点击确认关闭。（在Internet设置--连接--局域网设置中，如图二）
即使局域网设置内的代理设置已经与V2RayA内的设置相符，也依然需要打开该界面，无需做任何更改，再按确定关闭该几面，才可正常上网。

### v2rayA设置以及相关截图
![Snipaste_2022-03-06_02-01-43](https://user-images.githubusercontent.com/41558215/156895542-3a7919fc-0ef0-4888-b54c-c3e6cfd6aa8a.png)
![Snipaste_2022-03-06_01-58-55](https://user-images.githubusercontent.com/41558215/156895548-7984d38e-c3bc-4760-a45e-47abda8154bc.png)

**Comment by mzz2017** [comment]
确实遇到了需要等待几秒的问题。v2raya 会调用习题调用去刷新代理服务器的设置，但暂不清楚为什么需要等待。

在我不按步骤点击确定时，仍然可以等待几秒以解决问题。
