### ISSUE TITLE
v2raya 命令行代理配置和全局代理使能

### ISSUE THREAD

**Issue by jinguang-dong** [v2rayA/v2rayA#441]
### 您想提出的功能特性是否和现有问题相关？

1、通过 http://127.0.0.1:2017/ 导入订阅并完成全局代理配置，网页等基本访问正常，但是命令行终端无法访问
2、ubuntu 的命令行终端 terminal 里面如何配置才能使能代理？
是不是在.bashrc中设置http_proxy 和 https_proxy 为 http://127.0.0.1:2017？

**Comment by jinguang-dong** [comment]
端口配置问题,已解决
关闭此ISSUE,谢谢

**Comment by TRSWNCA** [comment]
您好，我也出现了这个问题:
```
$ echo $all_proxy
http://localhost:20171
```
v2ray中选择：
代理所有流量 开启IP转发
redirect
大陆白名单
关闭
关闭

浏览器中访问google正常，Ubuntu Terminal无法访问，请问是如何解决的呢？
