### ISSUE TITLE
如何为 v2raya 配置 V2RAY_VMESS_AEAD_FORCED=false 环境变量？

### ISSUE THREAD

**Issue by sommio** [v2rayA/v2rayA#443]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.6.2-1
2. 你通过什么方式安装v2rayA
pacman/[archlinuxcn](https://github.com/archlinuxcn/repo) 仓库
3. 你所使用的操作系统
Arch Linux

### 描述问题：

想配置 V2RAY_VMESS_AEAD_FORCED=false 环境变量以使用 MD5

### v2rayA设置以及相关截图

已修改下面的文件

```
# /etc/profile
export V2RAY_VMESS_AEAD_FORCED=false
```

```
#/usr/lib/systemd/system/v2raya.service
[Service]
Environment="V2RAY_VMESS_AEAD_FORCED=false"
```

但依旧无法使用 MD5 认证

**Comment by cubercsl** [comment]
你这个环境变量应该在服务端配置。v2rayA 在 1.5.6.2 会强制使用 AEAD，并忽略用户非 0 的 altid。

**Comment by mzz2017** [comment]
@sommio 1.5.6不支持，换1.5.5
