### ISSUE TITLE
多节点负载均衡时，socks入站流量出站时未走负载均衡器

### ISSUE THREAD

**Issue by bluaze** [v2rayA/v2rayA#447]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.6.2
2. 你通过什么方式安装v2rayA
apt
3. 你所使用的操作系统
ubuntu server 18.04

### 描述问题
当选择多个代理节点负载均衡时，v2raya生成的v2ray配置文件中没有任何socks入站的路由规则，这在单节点的情况下是合适的，没有路由规则的流量会从第一个出站走（即代理节点），但在多节点负载均衡的情况下，添加一条路由规则走负载均衡器"proxy"更合适

http端口（全局代理的那个）也存在类似问题

**Comment by mzz2017** [comment]
@bluaze 没错，已经获悉你的意思，下个版本进行修复

**Comment by mzz2017** [comment]
Fixed in v1.5.7

**Comment by bluaze** [comment]
v1.5.7添加的规则出站走"outboundTag": "proxy"
在负载均衡的情况下，添加的规则会不起作用，需要走balancerTag

**Comment by mzz2017** [comment]
@bluaze 奇怪，outboundTag 没有被转换为 balancerTag，我修复一下
