### ISSUE TITLE
在非透明代理模式下提供关闭嗅探的选项

### ISSUE THREAD

**Issue by ImBearChild** [v2rayA/v2rayA#448]
### 版本、安装方式、系统

1. 版本：v1.5.6.2
3. 安装方式：直接使用二进制文件
4. 操作系统：Linux 5.16.11

### 描述问题

Tor 无法在 V2Ray 内核启用嗅探 (`sniffing`) 功能的情况下正常连接到中继。而 V2RayA 在非透明代理模式下默认开启嗅探，即使将“防止DNS污染”设置为关闭也依然为所有入站开启嗅探，且不提供关闭选项。#332 中提及的“特殊选项”在非透明代理模式下不可见（不确定这个是Bug还是逻辑本来如此）。

对于不使用路由功能的HTTP/Socks5入站，因为所有的DNS解析都可以在远端进行，应该没必要开启嗅探功能吧？

### 复现问题的步骤

1. 使用 `v2raya --lite` 模式启动 v2raya
2. Tor 浏览器代理设置为 v2raya 的 socks5 或者 HTTP
3. 连接 Tor 网络

### v2rayA设置以及相关截图
找不到特殊选项设置：
![image](https://user-images.githubusercontent.com/29907700/158000949-2bee00cd-ea77-4416-bd40-b151bfa5e834.png)

**Comment by iopq** [comment]
Same issue, I want to turn off sniffing but it's turned on by default

**Comment by mzz2017** [comment]
Fixed in v1.5.7
