### ISSUE TITLE
无法导入订阅

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [v2rayA/v2rayA#449]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.6.2
2. 你通过什么方式安装v2rayA
apt
3. 你所使用的操作系统
ubuntu20.04

### 描述问题
无法导入订阅

### 复现问题的步骤
找一个以txt文件拓展结尾的订阅链接测试比如
https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0311.txt

### v2rayA/v2ray运行日志：

```shell
E] [import.go:22]  failed to resolve subscription address: Get "https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0311.txt": dial tcp 0.0.0.0:443: connect: connection refused
```

### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.6.2
2. 你通过什么方式安装v2rayA
apt
3. 你所使用的操作系统
ubuntu20.04

### 描述问题
无法导入订阅

### 复现问题的步骤
找一个以txt文件拓展结尾的订阅链接测试比如
https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0311.txt

### v2rayA/v2ray运行日志：

```shell
E] [import.go:22]  failed to resolve subscription address: Get "https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0311.txt": dial tcp 0.0.0.0:443: connect: connection refused
```

### v2rayA设置以及相关截图
![Screenshot from 2022-03-12 21-46-20](https://user-images.githubusercontent.com/57612792/158020549-5c227b3f-c7ce-44f9-bcb2-bbeb9e341440.png)
![image](https://user-images.githubusercontent.com/57612792/158020559-cc895d10-bcf3-4cf2-9883-d892a4e58672.png)

**Comment by cubercsl** [comment]
Your subscription link has DNS pollution, please use a proxy subscription. This is not a v2rayA issue, please ask your service provider to resolve it.
