### ISSUE TITLE
docker部署1.5.6.2 v2ray-core不启动也无对应log，原1.5.4正常(不是数据库格式问题）

### ISSUE THREAD

**Issue by chaihx0857** [v2rayA/v2rayA#453]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA - 1.5.6.2

3. 你通过什么方式安装v2rayA - docker
docker run -d \
  --restart=always \
  --privileged \
  --network=host \
  --name v2raya \
  -e V2RAYA_ADDRESS=0.0.0.0:2017 \
      -v /lib/modules:/lib/modules \
  -v /etc/resolv.conf:/etc/resolv.conf \
  -v /etc/v2raya:/etc/v2raya \
  mzz2017/v2raya

4. 你所使用的操作系统
群晖 DSM 7.0.1-42218 update 3

### 描述问题：

之前同一台群晖，部署v1.5.4一切正常，也没有按照教程补足群晖可能缺失的iptables
重新部署v1.5.6.2 （新建数据库），docker里 v2ray 没有启动，只有v2raya的进程，log找不到任何错误信息，log如下
尝试v1.5.6.1 同样v2ray不启动 
重新启动v1.5.4 就没有问题
主要是不知道怎么排查了。。
非常感谢~

### v2rayA运行日志（Optional）：

 # docker mode
 docker logs v2raya2022/03/16 07:54:50.606 [A] [main.go:25]  network is connected
2022/03/16 07:54:50.664 [I] [pre.go:222]  init DB
2022/03/16 07:54:50.914 [A] [main.go:27]  V2Ray binary is /usr/bin/v2ray
2022/03/16 07:54:50.914 [A] [main.go:27]  V2Ray asset directory is /run/user/0/v2raya
2022/03/16 07:54:50.914 [A] [main.go:27]  v2rayA working directory is /root
2022/03/16 07:54:50.914 [A] [main.go:27]  v2rayA configuration directory is /etc/v2raya
2022/03/16 07:54:50.914 [A] [main.go:27]  Golang: go1.17.6
2022/03/16 07:54:50.914 [A] [main.go:27]  OS: linux
2022/03/16 07:54:50.914 [A] [main.go:27]  Arch: amd64
2022/03/16 07:54:50.914 [A] [main.go:27]  Lite: false
2022/03/16 07:54:50.914 [A] [main.go:27]  Version: 1.5.6.2
2022/03/16 07:54:50.914 [A] [main.go:27]  Starting...
2022/03/16 07:54:50.948 [A] [index.go:117]  v2rayA is listening at http://127.0.0.1:2017
2022/03/16 07:54:50.948 [A] [index.go:117]  v2rayA is listening at http://192.168.1.10:2017
2022/03/16 07:54:50.948 [A] [index.go:117]  v2rayA is listening at http://169.254.82.229:2017
2022/03/16 07:54:50.949 [A] [index.go:117]  v2rayA is listening at http://169.254.158.103:2017
2022/03/16 07:54:50.949 [A] [index.go:117]  v2rayA is listening at http://169.254.96.84:2017
2022/03/16 07:54:50.949 [A] [index.go:117]  v2rayA is listening at http://192.168.1.11:2017
2022/03/16 07:54:50.949 [A] [index.go:117]  v2rayA is listening at http://172.17.0.1:2017
2022/03/16 07:54:50.949 [A] [index.go:117]  v2rayA is listening at http://[::1]:2017
2022/03/16 07:54:50.949 [A] [index.go:117]  v2rayA is listening at http://[fe80::211:32ff:fef2:dc5]:2017
2022/03/16 07:54:50.949 [A] [index.go:117]  v2rayA is listening at http://[fe80::42:b2ff:fe1c:423a]:2017
2022/03/16 07:54:50.949 [A] [index.go:117]  v2rayA is listening at http://[fe80::60ce:fcff:fe74:84db]:2017
2022/03/16 07:54:50.949 [A] [index.go:117]  v2rayA is listening at http://[fe80::5cf9:8dff:fe2c:4700]:2017
2022/03/16 07:54:50.949 [A] [index.go:117]  v2rayA is listening at http://[fe80::9813:1eff:feef:f4c4]:2017
2022/03/16 07:54:50.949 [A] [index.go:117]  v2rayA is listening at http://[fe80::58f2:2aff:fead:5230]:2017
2022/03/16 07:54:50.949 [A] [index.go:117]  v2rayA is listening at http://[fe80::a871:1aff:fe53:5433]:2017

**Comment by mzz2017** [comment]
@chaihx0857 什么意思，请表述你的操作过程以及出问题的步骤在哪里

**Comment by MarksonHon** [comment]
@chaihx0857 你看一下 是不是没有选择节点

**Comment by chaihx0857** [comment]
> @chaihx0857 什么意思，请表述你的操作过程以及出问题的步骤在哪里

首先感谢，v1.5.4我在群晖上部署，完美运行好几个月了（并没有意识到需要修正iptable缺失，可能群晖不同版本系统裁剪不同）
这次手动升级v1.5.6.2，完全重新部署，重新导入节点，怕有数据格式的问题。
但是发现docker里v2ray的进程完全没启动，log如上，也没有v2ray启动的相关信息，哪怕报错也好排查啊。
docker里ps也只有v2raya, 并没有v2ray的进程。docker里检查文件结构，相关文件都在。
为了排查，又重新部署v1.5.4，一切正常。log如下，
....
2022/03/15 07:47:11.397 [A] [main.go:27]  Version: 1.5.4
2022/03/15 07:47:11.397 [A] [main.go:27]  Starting...
2022/03/15 07:47:11.603 [I] [io.go:425]  V2Ray 4.42.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.1 linux/amd64)
2022/03/15 07:47:11.603 [I] [io.go:425]  A unified platform for anti-censorship.
2022/03/15 07:47:11.604 [I] [io.go:425]  [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/03/15 07:47:13.802 [I] [io.go:425]  127.0.0.1:40408 accepted tcp:127.0.0.1:0 [api-out]
2022/03/15 07:47:14.253 [A] [index.go:131]  v2rayA is listening at http://127.0.0.1:2017
....
感觉，在v1.5.6.2里，就没有启动v2ray-core，也不知道排查的方向。
为了测试，又从零部署了v1.5.6.1，现象同v1.5.6.2

太啰嗦了，就是发现v2ray没起来又不知道怎么查。。。只好这里求助，谢谢

**Comment by mzz2017** [comment]
@chaihx0857 你需要勾选节点之后，点左上角的就绪按钮进行启动

**Comment by chaihx0857** [comment]
> @chaihx0857 你看一下 是不是没有选择节点

谢谢兄弟 是我傻逼了
