### ISSUE TITLE
Linux 开启透明代理后再关闭透明代理会导致无法连接网络

### ISSUE THREAD

**Issue by icespite** [v2rayA/v2rayA#454]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.5.6.2
2. What approach of installation do you install V2rayA?
aur
3. What is your operating system?
manjaro

### Description

开启系统代理后再关闭系统代理会导致无法连接网络

### Steps to reproduce

1.开启系统代理，选择tproxy，保存并应用。
2.关闭系统代理，保存并应用。

### Logs：
[Log Link](https://pastebin.com/mv40yrGJ)  

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

![Screenshot_20220316_202708](https://user-images.githubusercontent.com/50160905/158590879-6ef023ba-b46f-4c63-8a2a-045e8d93c4c5.png)
![Screenshot_20220316_202819](https://user-images.githubusercontent.com/50160905/158590894-bd74cecb-51c6-4819-b569-34fc17e7a1f2.png)
![Screenshot_20220316_202847](https://user-images.githubusercontent.com/50160905/158590906-78500122-8341-4414-8643-70cbd23630fe.png)

**Comment by cubercsl** [comment]
@icespite #403

**Comment by icespite** [comment]
本身我并未开启iptables服务
