### ISSUE TITLE
希望能新增强制允许alertid的选项

### ISSUE THREAD

**Issue by torgitor** [v2rayA/v2rayA#455]
### 您想提出的功能特性是否和现有问题相关？
目前v2raya版本不支持alertid，即使订阅信息中有alertid，生成的config.json中也会丢弃。虽然是跟随core的特性，但目前很多机 场的订阅仍是要求alertid的，导致无法连接。

### 功能特性内容
强烈建议v2raya的配置中可以增加选项，允许使用alertid，可以在开启时给出安全警告，但最终选择权留给用户。

**Comment by cubercsl** [comment]
请使用旧版本 v2rayA

**Comment by MarksonHon** [comment]
@torgitor 建议用Clash，Clash目前还保留了这个选项

**Comment by torgitor** [comment]
已退回到1.5.5。Clash 也是要降版到0.19.4。唉。
