### ISSUE TITLE
在arm平台上运行代理时出错

### ISSUE THREAD

**Issue by hbqclh** [v2rayA/v2rayA#457]
### 版本、安装方式、系统
tx1的arm64  ubuntu16 

1. 你在使用什么版本的v2rayA
最新
2. 你通过什么方式安装v2rayA
docker
3. 你所使用的操作系统
arm ubuntu16

### 描述问题

2022/03/17 08:47:23.373 [W] [transparent.go:49]  WriteTransparentProxyRules: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -A V2RAY -p tcp -j REDIRECT --to-ports 32345 iptables v1.8.7 (legacy): unknown option "--to-ports"
Try `iptables -h' or 'iptables --help' for more information.
: exit status 2

2022/03/17 08:47:23.676 [E] [connection.go:88]  failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -A V2RAY -p tcp -j REDIRECT --to-ports 32345 iptables v1.8.7 (legacy): unknown option "--to-ports"
Try `iptables -h' or 'iptables --help' for more information.
: exit status 2

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@hbqclh sudo apt install -y iptables

**Comment by hbqclh** [comment]
> 

已经确定是最新版的iptables，且在容器外也可以使用这个命令。

**Comment by mzz2017** [comment]
@hbqclh 那就跑在宿主机吧

**Comment by hbqclh** [comment]
刚查了一下主机的 iptables v1.6.0
这个版本是不是太低了？

**Comment by MarksonHon** [comment]
@hbqclh 你宿主机操作系统内核太低，安装   
linux-generic-hwe 或 linux-generic-hwe-16.04 试下（系统太老 不知道 HWE 的包叫啥）

**Comment by hbqclh** [comment]
Linux tegra-ubuntu 4.4.38-tegra #1 SMP PREEMPT Thu Mar 1 20:44:58 PST 2018 aarch64 aarch64 aarch64 GNU/Linux
这是我的内核版本。安装了也不行。
![image](https://user-images.githubusercontent.com/12690057/158924654-8d937e2e-c206-433e-8084-cd40fe9982d3.png)
这个系统是nvidia官方定制的，估计精简了很多东西。升级内核可能得重刷系统才行，改天我再试下看看。

**Comment by hbqclh** [comment]
2022/03/29 12:13:48.025 [W] [subscription.go:239]  resolveByLines: ResolveURL error: invalid URL: </html>
2022/03/29 12:14:23.426 [E] [connection.go:88]  failed to start v2ray-core: failed: no server is selected. please select at least one server
2022/03/29 12:15:27.427 [I] [io.go:425]  V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/arm64)
2022/03/29 12:15:27.427 [I] [io.go:425]  A unified platform for anti-censorship.
2022/03/29 12:15:27.427 [I] [io.go:425]  [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/03/29 12:15:42.452 [E] [connection.go:88]  failed to start v2ray-core: timeout: check the log for more information
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7798b0]

goroutine 327 [running]:
github.com/v2rayA/v2rayA/core/v2ray.NewProcess.func2(0x400038af00, 0x40000a8c70, 0x4000852fa9)
        /build/service/core/v2ray/process.go:77 +0x70
created by github.com/v2rayA/v2rayA/core/v2ray.NewProcess
        /build/service/core/v2ray/process.go:74 +0x38c
2022/03/29 12:15:43.230 [A] [main.go:25]  network is connected
2022/03/29 12:15:43.257 [A] [main.go:27]  V2Ray binary is /usr/bin/v2ray
2022/03/29 12:15:43.257 [A] [main.go:27]  V2Ray asset directory is /run/user/0/v2raya
2022/03/29 12:15:43.258 [A] [main.go:27]  v2rayA working directory is /root
2022/03/29 12:15:43.258 [A] [main.go:27]  v2rayA configuration directory is /etc/v2raya
2022/03/29 12:15:43.258 [A] [main.go:27]  Golang: go1.17.6
2022/03/29 12:15:43.258 [A] [main.go:27]  OS: linux
2022/03/29 12:15:43.258 [A] [main.go:27]  Arch: arm64
2022/03/29 12:15:43.258 [A] [main.go:27]  Lite: false
2022/03/29 12:15:43.258 [A] [main.go:27]  Version: 1.5.6.2
2022/03/29 12:15:43.258 [A] [main.go:27]  Starting...
2022/03/29 12:15:43.280 [A] [index.go:117]  v2rayA is listening at http://127.0.0.1:2017
2022/03/29 12:15:43.280 [A] [index.go:117]  v2rayA is listening at http://192.168.102.156:2017

**Comment by mzz2017** [comment]
@hbqclh 我琢磨着节点有问题吧

**Comment by bruce2233** [comment]
解决了吗
