### ISSUE TITLE
请问一下如何进行无头配置?

### ISSUE THREAD

**Issue by KSroido** [v2rayA/v2rayA#461]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

2. 你通过什么方式安装v2rayA

3. 你所使用的操作系统

现在在debian10上面按照官方教程成功安装了v2raya,服务已经跑起来了,防火墙已关

但是无法访问2017端口,怀疑是软件逻辑只允许本机或局域网来源的流量(我这台是云主机)

所以想问一下云主机如何进行无头的v2raya初始化配置

感谢~

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by cubercsl** [comment]
@KSroido 开工单问你的云主机供应商
