### ISSUE TITLE
daemon.err v2raya

### ISSUE THREAD

**Issue by kilobyte15** [v2rayA/v2rayA#465]
![image](https://user-images.githubusercontent.com/30628155/160025704-052d70dc-1a87-44d4-a4b3-28ec3496783b.png)

how to resolve this? anyone please help I keep getting this error

I'm using a newifi 3 d2 router

**Comment by MarksonHon** [comment]
未按照模板发issue，这个issue会被关闭，有需要可以进群：
<https://t.me/v2raya_zh>
