### ISSUE TITLE
kvm虚拟机流量全被代理

### ISSUE THREAD

**Issue by hinyb** [v2rayA/v2rayA#474]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.6.2
2. 你通过什么方式安装v2rayA
yay -S v2rayA
3. 你所使用的操作系统
arch

### 描述问题：

用KVM开了个WIN10虚拟机，连接方式默认的nat，发现虚拟机的所有流量都被v2rayA代理了，RoutingA里面设置虚拟机IP直连还是走v2rayA。

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志
3月 08 19:48:55 myarch systemd[1]: /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![image](https://user-images.githubusercontent.com/40139991/161220710-f98a2e30-e483-44d6-8a7d-251c359d7019.png)
![image](https://user-images.githubusercontent.com/40139991/161220740-18f007a9-e4c5-499d-833a-8fac0b2f6f6a.png)
![image](https://user-images.githubusercontent.com/40139991/161220774-7b78d0c3-ba88-47e5-866e-0346847c3b17.png)

**Comment by mzz2017** [comment]
@hinyb source那条写最前面

**Comment by hinyb** [comment]
感谢大佬
