### ISSUE TITLE
deepin启动后一定概率不能自动连接

### ISSUE THREAD

**Issue by chenxiex** [v2rayA/v2rayA#477]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.6.2

2. 你通过什么方式安装v2rayA
v2raya软件源
3. 你所使用的操作系统
deepin20.5

### 描述问题：

deepin系统启动后有概率出现v2raya能正常启动但没有连接到代理。

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
不能连接的时候看v2raya日志。

**Comment by chenxiex** [comment]
> 不能连接的时候看v2raya日志。

使用
`journalctl -u v2ray | tail -n 50`
查看了日志。日志只有一句话：
`/etc/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!`
不断重复。

**Comment by mzz2017** [comment]
@chenxiex 看v2raya的不是v2ray

**Comment by chenxiex** [comment]
> @chenxiex 看v2raya的不是v2ray

找到原因了，是因为硬件时间不正确导致系统开机时时间不正确，无法启动v2ray连接。
