### ISSUE TITLE
Apple设备无法接收App推送通知

### ISSUE THREAD

**Issue by yunxi993** [v2rayA/v2rayA#479]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
 **`1.5.6.2`**

2. 你通过什么方式安装v2rayA
**`编译、ipk安装、脚本安装都试过`**

3. 你所使用的操作系统
**`ARM`**

### 描述问题：
**`使用RoutingA模式Apple设备无法接收到App通知推送
v2rayA日志可以看见Apple APNs的IP连接，不过在路由 实时连接里面 设备连接WIFI的几秒钟内可以看见 APNs的IP连接，几秒钟后连接貌似就被办掉了，没了.`**

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。
![屏幕截图 2022-04-03 203237](https://user-images.githubusercontent.com/59167936/161582467-2be420f7-ece1-41f8-b016-42022aa1807a.png)
![屏幕截图 2022-04-03 203300](https://user-images.githubusercontent.com/59167936/161582429-8ede8cd1-7408-42c5-8197-c862f6145ac3.png)

**Comment by mzz2017** [comment]
@yunxi993 情况很奇怪，有其他人遇到过吗？

**Comment by yunxi993** [comment]
> @yunxi993 情况很奇怪，有其他人遇到过吗？

目前不清楚其他人有没有相同的问题

passwall2与v2rayA的RoutingA规则模式相同，都是依赖Geo规则分流、问题也相同。

SSR、PASSWALL，这些不依赖Geo规则的就没问题.

在passwall2里面不使用 `流量嗅探 (V2ray/Xray)` 或者使用 `流量嗅探 (V2ray/Xray)` 的同时使用 `流量嗅探只供路由使用 (Xray)` 通知推送便是正常的。
![image](https://user-images.githubusercontent.com/59167936/161913245-eb292bf7-994d-4a2d-9935-601b533e07bf.png)

两者都是把流量全部交给*ray内核处理，在想是不是内核的原因.

**Comment by mzz2017** [comment]
@yunxi993 v2raya 关闭嗅探的方法是，打开dns防污染并且打开特殊模式中的fakedns

**Comment by yunxi993** [comment]
> @yunxi993 v2raya 关闭嗅探的方法是，打开dns防污染并且打开特殊模式中的fakedns

![image](https://user-images.githubusercontent.com/59167936/161929626-ea7d099f-5500-48fa-8073-9f0ec023debf.png)
上面的设置相同、只有开启 `fakedns` 通知才是正常、使用 `Super或 关闭` 都无法接收到推送.

**Comment by shuiguojiao** [comment]
ip(17.0.0.0/8)->direct
