### ISSUE TITLE
UDP 请求好像没有被完全转发

### ISSUE THREAD

**Issue by hellodword** [v2rayA/v2rayA#480]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

当前最新

```
$ v2raya --version
1.5.6.2
```

2. 你通过什么方式安装v2rayA

```ssh
curl -Ls https://mirrors.v2raya.org/go.sh | sudo bash
sudo systemctl disable v2ray --now
wget -qO - https://apt.v2raya.mzz.pub/key/public-key.asc | sudo tee /etc/apt/trusted.gpg.d/v2raya.asc
echo "deb https://apt.v2raya.mzz.pub/ v2raya main" | sudo tee /etc/apt/sources.list.d/v2raya.list
sudo apt update
sudo apt install v2raya
sudo systemctl start v2raya.service
```

3. 你所使用的操作系统

```
$ cat /etc/issue
Ubuntu 20.04.4 LTS
```

### 描述问题：

```sh
# 没问题，查询到的是配置的代理IP
curl ifconfig.me

# 查询到的是真实的IP
$ time -p dig TXT +short o-o.myaddr.l.google.com @ns2.google.com
< real ip >
real 1.25
user 0.00
sys 0.00
```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

所有配置如下
---   
图1 代理模式
---
![image](https://user-images.githubusercontent.com/46193371/161669133-4a6ce4d5-ee91-4fca-83e3-ceca213815ae.png)
---   
图2 DNS配置
---
![image](https://user-images.githubusercontent.com/46193371/161669156-da167e33-71ef-4b13-9509-4baecc4412f8.png)
---   
图3 唯一的outbound
---
![image](https://user-images.githubusercontent.com/46193371/161669184-0602df82-4775-4415-9030-4a7e3390dddd.png)
---
### 可能有用的信息

是新安装的操作系统，附上在此之前执行的操作

```sh
# 禁用ipv6
echo 'net.ipv6.conf.all.disable_ipv6=1' | sudo tee -a /etc/sysctl.conf
echo 'net.ipv6.conf.default.disable_ipv6=1' | sudo tee -a /etc/sysctl.conf
sudo sysctl -p

# 更换为 dnsmasq
sudo apt install dnsmasq
sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved
sudo systemctl mask systemd-resolved
cat /etc/resolv.conf 
sudo rm -f /etc/resolv.conf
sudo systemctl restart dnsmasq
```

```ini
# /etc/dnsmasq.conf
no-resolv
server=8.8.8.8#53

listen-address=127.0.0.1
port=53
```

**Comment by mzz2017** [comment]
@hellodword 根据文档 v2ray 只代理 A/AAAA 查询

**Comment by hellodword** [comment]
> @hellodword 根据文档 v2ray 只代理 A/AAAA 查询

根据 [v2fly guide](https://guide.v2fly.org/app/tproxy.html) 配置，是可以代理这类 udp 请求的，我会继续看看具体差异在哪里

**Comment by mzz2017** [comment]
@hellodword https://guide.v2fly.org/basics/dns.html#%E5%AF%B9%E5%A4%96%E5%BC%80%E6%94%BE-v2ray-%E7%9A%84-dns-%E6%9C%8D%E5%8A%A1

**Comment by hellodword** [comment]
> @hellodword https://guide.v2fly.org/basics/dns.html#%E5%AF%B9%E5%A4%96%E5%BC%80%E6%94%BE-v2ray-%E7%9A%84-dns-%E6%9C%8D%E5%8A%A1

抱歉，改了一下 title，应该更准确了些。我的理解是这个请求就算无法被 v2ray 当作 DNS 请求来“拦截”，也应该会被当作 UDP 流量来交由代理服务器来代理

**Comment by hellodword** [comment]
> @hellodword https://guide.v2fly.org/basics/dns.html#%E5%AF%B9%E5%A4%96%E5%BC%80%E6%94%BE-v2ray-%E7%9A%84-dns-%E6%9C%8D%E5%8A%A1

抱歉，改了一下 title，应该更准确了些。我的理解是这个请求就算无法被 v2ray 当作 DNS 请求来“拦截”，也应该会被当作 UDP 流量来交由代理服务器来代理

**Comment by mzz2017** [comment]
@hellodword 把防止dns关了，dns也会被视为udp正确分流
