### ISSUE TITLE
It seems the installation script doesn't work 

### ISSUE THREAD

**Issue by RedemptionC** [v2rayA/v2rayA#481]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
**I'm trying to install v2ray using the installation script [here](https://v2raya.org/en/docs/prologue/installation/debian/#:~:text=Mirror%20script%20provided%20by%20v2rayA%20(recommended)%23), but it failed due to network issue,which indicates this url may be not available inside the GFW**

3. What approach of installation do you install V2rayA?

4. What is your operating system?

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by mzz2017** [comment]
@RedemptionC No, it is okay with Shanghai Unicom.

**Comment by RedemptionC** [comment]
@mzz2017 When I executed it,it says 
"failed to connect to hubmirror.v2raya.org port 443: connection timed out"
"error: failed to get release list,please check your network"
what could I do ?
It does has network available now

**Comment by mzz2017** [comment]
@RedemptionC It's also fine on Guangzhou China Mobile. Maybe there is some problems between the mirror site and your local network.

**Comment by RedemptionC** [comment]
@mzz2017 
I don't know,but I tried the docker apporach,it did succeed in installation,but after it connect,I still can't access google,what should I do?

**Comment by mzz2017** [comment]
@RedemptionC Figure out which is broken: node, v2raya setting, connection, dns, ...

**Comment by RedemptionC** [comment]
@mzz2017  Got it,I forgot to do the initial setting in v2raya.
Thank you so much :)
