### ISSUE TITLE
“端口分享”功能的实际效果

### ISSUE THREAD

**Issue by windshadow233** [v2rayA/v2rayA#486]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
debian_amd64_1.5.6.2
2. 你通过什么方式安装v2rayA
/installer_debian_amd64_1.5.6.2.deb
3. 你所使用的操作系统
Ubuntu

### 描述问题
通过其他的issue，大概了解到“端口分享”实际上是“局域网可访问”。
我发现我一直没有开启端口分享功能，但仍可以正常作为透明代理被局域网设备使用。基于此，我未能感受到此功能带来的效果。

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
@windshadow233 <https://t.me/v2raya_zh>
欢迎加群

**Comment by mzz2017** [comment]
嗯，确实是个问题，我会考虑局域网共享关闭的情况下删掉prerouting的iptables语句
