### ISSUE TITLE
gfwlist问题(https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags)

### ISSUE THREAD

**Issue by Vlary** [v2rayA/v2rayA#488]
提示https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags拒绝访问，无法下载相关文件

**Comment by MarksonHon** [comment]
服务器有波动，可以再试试看
有需要可以进群：
<https://t.me/v2raya_zh>
