### ISSUE TITLE
trojan  server connect fail

### ISSUE THREAD

**Issue by leaguecn** [v2rayA/v2rayA#489]
why i cannot use trogan server?
when i started to click the trogan server, the bad thing showed up. Yep it didnot work with the "connection" function.
As you can see the logger information as following:

2022/04/13 19:08:41.021 [I] [io.go:425]  v2ctl> Read config:  /home/minipc/.config/v2raya/config.json
2022/04/13 19:08:41.124 [I] [io.go:425]  127.0.0.1:40684 accepted tcp:127.0.0.1:0 [api-out] 
2022/04/13 19:08:41.125 [W] [context.go:165]  PostConnection: failed to connect: not support Trojan: %!w(<nil>)
2022/04/13 19:08:41.125 [E] [connection.go:36]  failed to connect: failed to connect: not support Trojan: %!w(<nil>)
2022/04/13 19:08:45.517 [I] [io.go:425]  V2Ray 4.27.4 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.7 linux/amd64)
2022/04/13 19:08:45.517 [I] [io.go:425]  A unified platform for anti-censorship.
2022/04/13 19:08:45.611 [I] [io.go:425]  [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
2022/04/13 19:08:45.611 [I] [io.go:425]  v2ctl> Read config:  /home/minipc/.config/v2raya/config.json

Any guys had encountered the same problem?

**Comment by MarksonHon** [comment]
NOT A BUG
You use an outdated core
Read <v2raya.org/en> to install latest core
