### ISSUE TITLE
[bug] 导入ssr订阅地址出现错误

### ISSUE THREAD

**Issue by MrPeterJin** [v2rayA/v2rayA#49]
### 您想提出的feature是否和现有问题相关？

否

### Feature内容

希望客户端可以加入如SS客户端的导入订阅地址功能

**Comment by mzz2017** [comment]
你好，导入订阅地址是支持的，你在导入订阅时遇到了问题吗

**Comment by MrPeterJin** [comment]
![example](https://user-images.githubusercontent.com/51412849/75298789-6c02ef80-586e-11ea-9003-363c40e694e3.png)

对的，导入之后错误显示了

**Comment by mzz2017** [comment]
hello，你有golang环境吗，我这里没有可以复现的的订阅地址，这个问题需要你协助调试一下：
`/service/service/subscription`的第35行，\n改为\r尝试是否该订阅地址是否可以使用

或者如果有可以复现的订阅地址，可以发送至mzz@tuta.io

**Comment by MrPeterJin** [comment]
您好，这个 `/service/service/subscription` 地址指的v2raya根路径下吗？

**Comment by mzz2017** [comment]
是的。如果它仍然不奏效的话，可以试着修复它吗

**Comment by MrPeterJin** [comment]
emmm, 我是从aur源通过yay方式安装的，这个service的路径一般在哪里？

**Comment by mzz2017** [comment]
克隆仓库修改代码然后重新编译，这是代码中的。
如果不方便的话先留这个issue在这里吧，等待下一个有缘人。

**Comment by MrPeterJin** [comment]
好的，作者费心了

**Comment by mzz2017** [comment]
I closed the issue due to no response for a long time. Feel free to reopen it if there is some progress. Thank you!
