### ISSUE TITLE
v2ray连接后无法上网

### ISSUE THREAD

**Issue by sss20081** [v2rayA/v2rayA#492]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.6.2-1
2. 你通过什么方式安装v2rayA
通过pacman方式安装
3. 你所使用的操作系统
Arch linux

### 描述问题：

vraya连接后无法上网，也没有日志输出，ping节点无问题，http测试节点无法成功，显示not stable

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![Screenshot_20220416_220448](https://user-images.githubusercontent.com/62577592/163678044-ceb3b0cb-eb27-4fff-bf1b-e399beb1a490.png)
![Screenshot_20220416_220650](https://user-images.githubusercontent.com/62577592/163678053-06511f02-853c-4094-bbe1-55be90431707.png)
![Screenshot_20220416_220758](https://user-images.githubusercontent.com/62577592/163678080-db1af7b0-17f0-4087-aab7-4cad258d38db.png)
![Screenshot_20220416_220828](https://user-images.githubusercontent.com/62577592/163678103-8f1647fa-f1a4-4262-af44-5e0949fc7933.png)
![Screenshot_20220416_220836](https://user-images.githubusercontent.com/62577592/163678105-8d32fc43-29c4-456f-b15a-38df1db8f970.png)

**Comment by cubercsl** [comment]
`journalctl -u v2raya -n 50`

**Comment by sss20081** [comment]
`4月 16 22:07:50 Arch v2raya[28793]: [I] [io.go:425]  V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.>
4月 16 22:07:50 Arch v2raya[28793]: [I] [io.go:425]  A unified platform for anti-censorship.
4月 16 22:07:50 Arch v2raya[28793]: [I] [io.go:425]  [Info] main/jsonem: Reading config: /etc/v2raya/config.js>
4月 16 22:07:52 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:53580 accepted tcp:127.0.0.1:0 [api-out]
4月 16 22:07:52 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:42844 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:07:52 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:39248 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:07:52 Arch v2raya[28793]: [I] [io.go:425]  10.41.0.215:38258 accepted tcp:116.163.14.127:21154 [prox>
4月 16 22:07:52 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:48729 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:07:57 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:39983 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:07:57 Arch v2raya[28793]: [I] [io.go:425]  10.41.0.215:38260 accepted tcp:116.163.14.127:21154 [prox>
4月 16 22:07:57 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:33186 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:07:58 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:48833 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:07:58 Arch v2raya[28793]: [I] [io.go:425]  10.41.0.215:38262 accepted tcp:116.163.14.127:21154 [prox>
4月 16 22:07:58 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:52255 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:07:58 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:34733 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:07:58 Arch v2raya[28793]: [I] [io.go:425]  10.41.0.215:38264 accepted tcp:116.163.14.127:21154 [prox>
4月 16 22:07:58 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:37030 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:08:01 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:35746 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:08:01 Arch v2raya[28793]: [I] [io.go:425]  10.41.0.215:60638 accepted tcp:118.178.135.232:443 [direc>
4月 16 22:08:02 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:36233 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:08:02 Arch v2raya[28793]: [I] [io.go:425]  10.41.0.215:38266 accepted tcp:116.163.14.127:21154 [prox>
4月 16 22:08:02 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:51685 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:08:04 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:38649 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:08:04 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:33119 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:08:04 Arch v2raya[28793]: [I] [io.go:425]  10.41.0.215:38268 accepted tcp:116.163.14.127:21154 [prox>
4月 16 22:08:04 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:54677 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:08:07 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:32841 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:08:07 Arch v2raya[28793]: [I] [io.go:425]  10.41.0.215:38270 accepted tcp:116.163.14.127:21154 [prox>
4月 16 22:08:07 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:60345 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:08:08 Arch v2raya[28793]: [I] [io.go:425]  127.0.0.1:47853 accepted udp:2.0.1.7:53 [dns-out]
4月 16 22:08:08 Arch v2raya[28793]: [I] [io.go:425]  10.41.0.215:38272 accepted tcp:116.163.14.127:21154 [prox>`

**Comment by MarksonHon** [comment]
你第一张截图就告诉你了，你节点坏了
如果是自建节点，建议换 8443 端口跑 trojan
要是机场就换了吧
