### ISSUE TITLE
某些节点V2rayA无法使用，但其他V2ray相关软件可以。

### ISSUE THREAD

**Issue by ovmonk** [v2rayA/v2rayA#493]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
- Version: 1.5.6.2
2. 你通过什么方式安装v2rayA
- Scoop包管理器
3. 你所使用的操作系统
- Windows10 21H2

### 描述问题：

1. 如题。当使用V2rayA连接某些节点时，这些节点无法使用。但当我**将代理软件换成V2rayN时，这些节点却可以使用**。
2. 起初以为是V2ray内核的问题，但当手动更改环境变量，将内核切换成Xray时，这些节点仍然无法使用。
3. 出问题的节点集中在**vmess(ws+tls)** 类节点上。

### v2rayA运行日志（Optional）：
- Windows下不知如何抓取日志...

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

<img width="217" alt="v2rayn" src="https://user-images.githubusercontent.com/17329166/163725206-61ca8d6b-8826-40aa-b93c-8580d12053fa.png">
<img width="826" alt="v2raya" src="https://user-images.githubusercontent.com/17329166/163725209-89e5d680-6f0c-43bd-9643-7075c833e23b.png">
<img width="558" alt="设置截图" src="https://user-images.githubusercontent.com/17329166/163725216-e1eb2e66-9496-4fa4-88ba-f0c648da8615.png">

**Comment by sommio** [comment]
#423 #407

**Comment by ovmonk** [comment]
检查后发现AlterID果然是＞0，问题解决。
