### ISSUE TITLE
 解析Vmess链接时，无法正确解析sni参数至host

### ISSUE THREAD

**Issue by Chikage0o0** [v2rayA/v2rayA#496]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.6.2

3. 你通过什么方式安装v2rayA
scoop
4. 你所使用的操作系统
Windows10

### 描述问题

 解析Vmess链接时，无法正确解析sni参数至host

### 复现问题的步骤

导入该链接
vmess://eyJ2IjoiMiIsInBzIjoidGVzdCIsImFkZCI6Inh4eHh4IiwicG9ydCI6IjI4MjQzIiwiaWQiOiJiNTZkeHh4Ny04ZmQxLTQ5OGMtODUwZC1iZDc1NGEzMWI3MzIiLCJhaWQiOiIwIiwibmV0IjoiZ3JwYyIsInR5cGUiOiJub25lIiwiaG9zdCI6IiIsInBhdGgiOiJhcGkiLCJ0bHMiOiJ0bHMiLCJzbmkiOiJ4eHgueHh4In0=
```
{"v":"2","ps":"test","add":"xxxxx","port":"28243","id":"b56dxxx7-8fd1-498c-850d-bd754a31b732","aid":"0","net":"grpc","type":"none","host":"","path":"api","tls":"tls","sni":"xxx.xxx"}
```
### v2rayA/v2ray运行日志：
无报错

```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。
<!-- 如果条件允许请附图 -->

**Comment by MarksonHon** [comment]
@Chikage0o0 先删除 v2raya 这个包，然后换 v2raya-git 试试看

**Comment by Chikage0o0** [comment]
> @Chikage0o0 先删除 v2raya 这个包，然后换 v2raya-git 试试看

感觉不是版本问题，我直接源码编译出来也不行

**Comment by Chikage0o0** [comment]
待会我提交个pr吧
