### ISSUE TITLE
连续使用一周内存占用2GB

### ISSUE THREAD

**Issue by TinyRei** [v2rayA/v2rayA#500]
连续使用一周，内存占用2GB，且未释放

最近通过20172端口走代理流量很大（约500GB），内存占用2GB且不释放，需要重启
platform: unraid 6.9.2 docker

**Comment by MarksonHon** [comment]
超过三天未回复 先行关闭 有需要可以进群或者重开issue
Telegram 群组链接：<https://t.me/v2raya_zh>
