### ISSUE TITLE
添加自动开启代理选项

### ISSUE THREAD

**Issue by ASSANDHOLE** [v2rayA/v2rayA#505]
### 您想提出的功能特性是否和现有问题相关？
开机后代理没有自动启动，需要手动点开始，能否添加一个自动开启代理选项

### 功能特性内容
在设置里添加一个复选框以自动开启代理

**Comment by MarksonHon** [comment]
v2rayA会记住上一次退出时候的状态。如果你是在连接节点的情况下退出的，那么开机就会自动连接，反之则不会。
