### ISSUE TITLE
failed to start v2ray-core:

### ISSUE THREAD

**Issue by ArvinCJH** [v2rayA/v2rayA#506]
failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N V2RAY iptables v1.8.7 (legacy): can't initialize iptables table `nat': Permission denied (you must be root) Perhaps iptables or your kernel needs to be upgraded. : exit status 3

**Comment by walnut-mzy** [comment]
请问这个问题解决了吗？
