### ISSUE TITLE
检测到 geosite.dat, geoip.dat 文件或 v2ray-core 可能未正确安装，请检查

### ISSUE THREAD

**Issue by foxfire881** [v2rayA/v2rayA#510]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2raya_linux_arm64_1.5.7

2. 你通过什么方式安装v2rayA
直接执行v2raya_linux_arm64_1.5.7可执行文件

3. 你所使用的操作系统
树莓派debian/kali

### 描述问题
由于apt安装的最新版v2ray官方确定存在bug无法在debian上正常启动（golang语言版本问题）,因此下载了v2ray旧版二进制文件手动安装部署，部署后确认v2ray可以正常启动工作，只是安装路径没有装在/usr/bin、/usr/local/bin、/etc/v2ray这些路径下面。

然后启动v2rayA时报错：
启动时报core没有运行：
2022/05/01 16:56:40.302 [I] [main.go:28]  the core was not running the last time v2rayA exited
打开web console时提示：
“检测到 geosite.dat, geoip.dat 文件或 v2ray-core 可能未正确安装，请检查”

此时确认v2ray-core已经正常运行，geosite.dat, geoip.dat也都存在，但v2rayA仍然报错，猜测v2rayA可能是硬编码写死了检测规则强制core必须装在/usr/bin下面？可否通过config.json自定义配置core的路径？

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@foxfire881 https://v2raya.org/docs/manual/use-other-core/

**Comment by MarksonHon** [comment]
@foxfire881 要是 which v2ray 命令能找到核心，那就没事
要是找不到 那就得手动指定

**Comment by foxfire881** [comment]
> @foxfire881 https://v2raya.org/docs/manual/use-other-core/

请问要怎么指定命令行参数？文档给的例子是在service文件中增加下面这个环境变量

[Service]
Environment="V2RAYA_V2RAY_BIN=/usr/local/bin/xray"

但是我的bin和config.json等文件全都不在默认路径，还要配置一个V2RAYA_CONFIG变量，请问是怎么配置？
A：
[Service]
Environment="V2RAYA_V2RAY_BIN=/root/v2ray"
Environment="V2RAYA_CONFIG=/root/v2ray"

B：
[Service]
Environment="V2RAYA_V2RAY_BIN=/root/v2ray;V2RAYA_CONFIG=/root/v2ray"

应该是哪种写法？实测B方案无效，启动仍然报找不到core.

另外，我的geoip.dat、geosite.dat也不在默认路径下，这两个文件应该放在什么位置？

**Comment by MarksonHon** [comment]
@foxfire881 <http://www.jinbuguo.com/systemd/systemd.service.html>

**Comment by foxfire881** [comment]
> @foxfire881 http://www.jinbuguo.com/systemd/systemd.service.html

666, thanks very much

**Comment by mzz2017** [comment]
@Africanuncle 关于 v2ray 5.1.0 更新

目前 v2ray 5.1.0 已发布用户预览版，使用 fhs-install 新安装的 v2ray 会默认安装此版，目前发布的正式版 v2raya 1.5.9.1698.1 暂不支持 5.1.0 版的 v2ray-core。如需使用 v2raya， fhs-install 安装 v2ray 时需要指定 4.45.0 版的 v2ray 安装。

ref: https://github.com/v2fly/fhs-install-v2ray/issues/243

对于 Arch Linux 用户，v2ray 5.1.0 已经进入 community-testing 仓库，对于使用 testing 仓库的用户，可自行编译 v2raya 的 feat_v5 分支来适配新版的 v2ray。

ref: https://fars.ee/nCVO

**Comment by cxOrz** [comment]
Archlinux 现在给所有用户推 5.1.0 版本的v2ray了，更新完直接没网...

**Comment by exAClior** [comment]
@cxOrz  Try [downgrade] command on v2ray https://aur.archlinux.org/packages/downgrade

**Comment by cxOrz** [comment]
> @cxOrz Try [downgrade] command on v2ray https://aur.archlinux.org/packages/downgrade

改用 v2ray-git 了，已解决

**Comment by qian-jiahong** [comment]
已有解决办法：
https://github.com/v2rayA/v2rayA/issues/592

export V2RAYA_V2RAY_ASSETSDIR=/tmp/v2raya
export XDG_RUNTIME_DIR=/tmp
export V2RAYA_V2RAY_BIN=/opt/usr/v2ray/v2ray
export PATH=$PATH:/tmp/v2raya
./v2raya_linux_arm_2.0.1

**Comment by guoapeng** [comment]
我使用的是ubuntu 22.04.1
安装方式是下载v2raya deb包(版本2.2.4.3)进行安装, 安装完成, 访问v2ray web也遇到这样的错误提示.

问题排查:
使用命令查询安装了哪些包? 发现v2raya根本就没有带v2ray-core核心的任何文件, 因此会报错缺少geosite.dat, geoip.dat. 
其根本原因是却了整个v2ray核心. 

```bash
dpkg-query -L v2raya
```

找到了问题原因, 解决起来就比较容易了, 于是手动安装核心, 当然由于文档写得很混乱很差, 也没有那么容易.

于是去 https://github.com/v2fly/v2ray-core/releases 下载核心, 目前最新的版本是v5.11.0, 就使用它了.

```bash

# 下载核心
wget -o /tmp/v2ray-linux-64.zip https://github.com/v2fly/v2ray-core/releases/download/v5.11.0/v2ray-linux-64.zip
# 将其解压到
unzip /tmp/v2ray-linux-64.zip -d /usr/local/v2ray-core
```

修改配置让v2raya 使用v2ray-core

```bash

vi /etc/default/v2raya

# 添加配置
V2RAYA_V2RAY_BIN=/usr/local/v2ray-core/v2ray
V2RAYA_V2RAY_CONFDIR=/usr/local/v2ray-core

```

重启服务

```bash
systemctl restart v2raya
```
再次访问v2ray web ui, 错误消失.

**Comment by shizhier** [comment]
> 我也遇到类似的问题
> 
> ## 环境说明
> 我使用的是ubuntu 22.04.1 安装方式是下载v2raya deb包(版本2.2.4.3)进行安装, 安装完成, 访问v2ray web也遇到这样的错误提示.
> 
> ## 问题排查:
> 使用命令查询安装了哪些包? 发现v2raya根本就没有带v2ray-core核心的任何文件, 因此会报错缺少geosite.dat, geoip.dat. 其根本原因是却了整个v2ray核心.
> 
> ```shell
> dpkg-query -L v2raya
> ```
> 
> output
> 
> ```shell
> /etc
> /etc/default
> /etc/default/v2raya
> /usr
> /usr/bin
> /usr/bin/v2raya
> /usr/share
> /usr/share/icons
> /usr/share/icons/hicolor
> /usr/share/icons/hicolor/512x512
> /usr/share/icons/hicolor/512x512/apps
> /usr/share/icons/hicolor/512x512/apps/v2raya.png
> /usr/share/applications
> /usr/share/applications/v2raya.desktop
> /usr/share/doc
> /usr/share/doc/v2raya
> /usr/share/doc/v2raya/changelog.gz
> /usr/lib
> /usr/lib/systemd
> /usr/lib/systemd/system
> /usr/lib/systemd/system/v2raya.service
> /usr/lib/systemd/user
> /usr/lib/systemd/user/v2raya-lite.service
> ```
> 
> ## 解决方案
> 找到了问题原因, 解决起来就比较容易了, 于是手动安装核心, 当然由于文档写得很混乱很差, 很多连接失效, 也没有那么容易.
> 
> 于是去 https://github.com/v2fly/v2ray-core/releases 下载核心, 目前最新的版本是v5.11.0, 就使用它了.
> 
> ```shell
> # 下载核心
> wget -o /tmp/v2ray-linux-64.zip https://github.com/v2fly/v2ray-core/releases/download/v5.11.0/v2ray-linux-64.zip
> # 将其解压到
> unzip /tmp/v2ray-linux-64.zip -d /usr/local/v2ray-core
> ```
> 
> > 如何使用命令行下载很慢, 这里陷入一个矛盾, 但是需要自己想办法下载这个文件, 说不定在哪个犄角旮旯能找到文件.  由于众所周知的原因, 我只能帮助到这里了.
> 
> 修改配置让v2raya 使用v2ray-core
> 
> ```shell
> vi /etc/default/v2raya
> 
> # 添加配置
> V2RAYA_V2RAY_BIN=/usr/local/v2ray-core/v2ray
> V2RAYA_V2RAY_CONFDIR=/usr/local/v2ray-core
> ```
> 
> 重启服务
> 
> ```shell
> systemctl restart v2raya
> ```
> 
> ## 验证
> 再次访问v2ray web ui, 错误消失.

我也安装成功，界面显示正常。但是无法上到google。。。。

**Comment by GiveMeOneLastKiss** [comment]
一点补充事项：如果确认安装完v2ray但依然出现缺少

> 我也遇到类似的问题
> ## 环境说明
> 
> 我使用的是ubuntu 22.04.1 安装方式是下载v2raya deb包(版本2.2.4.3)进行安装, 安装完成, 访问v2ray web也遇到这样的错误提示.
> ## 问题排查:
> 
> 使用命令查询安装了哪些包? 发现v2raya根本就没有带v2ray-core核心的任何文件, 因此会报错缺少geosite.dat, geoip.dat. 其根本原因是却了整个v2ray核心.
> 
> ```shell
> dpkg-query -L v2raya
> ```
> 
> output
> 
> ```shell
> /etc
> /etc/default
> /etc/default/v2raya
> /usr
> /usr/bin
> /usr/bin/v2raya
> /usr/share
> /usr/share/icons
> /usr/share/icons/hicolor
> /usr/share/icons/hicolor/512x512
> /usr/share/icons/hicolor/512x512/apps
> /usr/share/icons/hicolor/512x512/apps/v2raya.png
> /usr/share/applications
> /usr/share/applications/v2raya.desktop
> /usr/share/doc
> /usr/share/doc/v2raya
> /usr/share/doc/v2raya/changelog.gz
> /usr/lib
> /usr/lib/systemd
> /usr/lib/systemd/system
> /usr/lib/systemd/system/v2raya.service
> /usr/lib/systemd/user
> /usr/lib/systemd/user/v2raya-lite.service
> ```
> 
> ## 解决方案
> 
> 找到了问题原因, 解决起来就比较容易了, 于是手动安装核心, 当然由于文档写得很混乱很差, 很多连接失效, 也没有那么容易.
> 
> 于是去 https://github.com/v2fly/v2ray-core/releases 下载核心, 目前最新的版本是v5.11.0, 就使用它了.
> 
> ```shell
> # 下载核心
> wget -o /tmp/v2ray-linux-64.zip https://github.com/v2fly/v2ray-core/releases/download/v5.11.0/v2ray-linux-64.zip
> # 将其解压到
> unzip /tmp/v2ray-linux-64.zip -d /usr/local/v2ray-core
> ```
> 
> > 如何使用命令行下载很慢, 这里陷入一个矛盾, 但是需要自己想办法下载这个文件, 说不定在哪个犄角旮旯能找到文件.  由于众所周知的原因, 我只能帮助到这里了.
> 
> 修改配置让v2raya 使用v2ray-core
> 
> ```shell
> vi /etc/default/v2raya
> 
> # 添加配置
> V2RAYA_V2RAY_BIN=/usr/local/v2ray-core/v2ray
> V2RAYA_V2RAY_CONFDIR=/usr/local/v2ray-core
> ```
> 
> 重启服务
> 
> ```shell
> systemctl restart v2raya
> ```
> 
> ## 验证
> 
> 再次访问v2ray web ui, 错误消失.

**一点补充事项：如果确认安装完v2ray但依然出现缺少文件，可以尝试重启设备**
