### ISSUE TITLE
各种提示“成功“、“success”、“”……但就是不正常，无法工作

### ISSUE THREAD

**Issue by foxfire881** [v2rayA/v2rayA#511]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2raya_linux_arm64_1.5.7

3. 你通过什么方式安装v2rayA
bin文件直接运行

5. 你所使用的操作系统
树莓派debian/kali

### 描述问题
按照手册文档配了三天，没有一次成功，实在受不了。

同一个节点（v2ray/ss/ssr/trojan..都试过了，alterid=0的也试过了）用其他客户端连接都可以正常访问，换了v2rayA在web console里面提示各种"运行成功"、“success”…… 但实际就是无法访问。

应用场景：把v2rayA部署在树莓派上做为Proxy提供给LAN内电脑访问。

配置和界面提示如下，各种“成功“、“已连接”……，20170的socks5端口也开了，但实际就是无法访问。

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.941 [I] [io.go:428]  10.0.0.3:52226 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.945 [I] [io.go:428]  10.0.0.3:52228 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.949 [I] [io.go:428]  10.0.0.3:52230 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.954 [I] [io.go:428]  10.0.0.3:52232 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.958 [I] [io.go:428]  10.0.0.3:52234 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.962 [I] [io.go:428]  10.0.0.3:52236 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.966 [I] [io.go:428]  10.0.0.3:52238 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.970 [I] [io.go:428]  10.0.0.3:52240 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.973 [I] [io.go:428]  10.0.0.3:52242 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.977 [I] [io.go:428]  10.0.0.3:52244 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.981 [I] [io.go:428]  10.0.0.3:52246 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.985 [I] [io.go:428]  10.0.0.3:52248 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.988 [I] [io.go:428]  10.0.0.3:52250 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.992 [I] [io.go:428]  10.0.0.3:52252 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:48 kali-rpi v2raya[67137]: 2022/05/02 23:14:48.996 [I] [io.go:428]  10.0.0.3:52254 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:49 kali-rpi v2raya[67137]: 2022/05/02 23:14:49.000 [I] [io.go:428]  [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:32345: accept4: too many open files
May 02 23:14:49 kali-rpi v2raya[67137]: 2022/05/02 23:14:49.000 [I] [io.go:428]  10.0.0.3:52256 accepted tcp:157.240.10.41:80 [direct]
May 02 23:14:49 kali-rpi v2raya[67137]: 2022/05/02 23:14:49.500 [I] [io.go:428]  [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:32345: accept4: too many open files
May 02 23:14:50 kali-rpi v2raya[67137]: 2022/05/02 23:14:50.000 [I] [io.go:428]  [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:32345: accept4: too many open files
May 02 23:14:58 kali-rpi v2raya[67137]: 2022/05/02 23:14:58.908 [I] [io.go:428]  tcp:10.0.0.42:12639 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 67
May 02 23:14:58 kali-rpi v2raya[67137]: 2022/05/02 23:14:58.908 [I] [io.go:428]  tcp:10.0.0.42:12640 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 67
May 02 23:15:00 kali-rpi v2raya[67137]: 2022/05/02 23:15:00.578 [I] [io.go:428]  tcp:10.0.0.42:12641 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 67
May 02 23:15:58 kali-rpi v2raya[67137]: 2022/05/02 23:15:58.923 [I] [io.go:428]  tcp:10.0.0.42:12645 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 67



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。
![1](https://user-images.githubusercontent.com/273961/166261770-246ebc6e-8ecd-4c51-ad2c-2c5fac47bc28.PNG)
![2](https://user-images.githubusercontent.com/273961/166261793-e74f1797-98c9-4332-993f-421b07d1d0ce.PNG)
![3](https://user-images.githubusercontent.com/273961/166261813-18044096-aa51-4bf0-9be4-da6a91ce2ddd.PNG)
![4](https://user-images.githubusercontent.com/273961/166261830-73c001f0-950a-48ea-83fb-686314bbb380.PNG)
![6](https://user-images.githubusercontent.com/273961/166262015-1f26bf71-1681-4c7f-b88b-e7f79dc401d8.PNG)
![7](https://user-images.githubusercontent.com/273961/166262043-3c99a8cf-4c13-4575-90e7-de3876ec330b.PNG)
![8](https://user-images.githubusercontent.com/273961/166262155-c34c1c49-4392-4c01-9774-06e6fe3cd84f.PNG)

**Comment by foxfire881** [comment]
#cat  /etc/v2raya/config.json



{
  "log":{
    "access":"",
    "error":"none",
    "loglevel":"info"
  },
  "inbounds":[
    {
      "port":20170,
      "protocol":"socks",
      "listen":"0.0.0.0",
      "sniffing":{
        "enabled":false,
        "destOverride":["http","tls"],
        "metadataOnly":false
      },
      "settings":{
        "auth":"noauth",
        "udp":true
      },
      "streamSettings":null,
      "tag":"socks"
    },
    {
      "port":20171,
      "protocol":"http",
      "listen":"0.0.0.0",
      "sniffing":{
        "enabled":false,
        "destOverride":["http","tls"],
        "metadataOnly":false
      },
      "streamSettings":null,
      "tag":"http"
    },
    {
      "port":20172,
      "protocol":"http",
      "listen":"0.0.0.0",
      "sniffing":{
        "enabled":false,
        "destOverride":["http","tls"],
        "metadataOnly":false
      },
      "streamSettings":null,
      "tag":"rule-http"
    },
    {
      "port":32345,
      "protocol":"dokodemo-door",
      "listen":"0.0.0.0",
      "sniffing":{
        "enabled":true,
        "destOverride":["http","tls"],
        "metadataOnly":false
      },
      "settings":{
        "network":"tcp,udp",
        "followRedirect":true
      },
      "streamSettings":{
        "sockopt":{
          "tproxy":"redirect"
        }
      },
      "tag":"transparent"
    },
    {
      "port":35279,
      "protocol":"dokodemo-door",
      "listen":"127.0.0.1",
      "sniffing":{
        "enabled":false,
        "metadataOnly":false
      },
      "settings":{
        "address":"127.0.0.1"
      },
      "streamSettings":null,
      "tag":"api-in"
    }
  ],
  "outbounds":[
    {
      "tag":"proxy",
      "protocol":"shadowsocks",
      "settings":{
        "servers":[
          {
            "address":"38.68.135.19",
            "method":"aes-256-gcm",
            "password":"g5MeD6Ft3CWlJId",
            "port":5003
          }
        ]
      },
      "streamSettings":{
        "sockopt":{
          "mark":128
        }
      }
    },
    {
      "tag":"direct",
      "protocol":"freedom",
      "settings":{
        "domainStrategy":"UseIP"
      },
      "streamSettings":{
        "sockopt":{
          "mark":128
        }
      }
    },
    {
      "tag":"block",
      "protocol":"blackhole",
      "settings":{

      }
    },
    {
      "tag":"dns-out",
      "protocol":"dns",
      "settings":{

      },
      "streamSettings":{
        "sockopt":{
          "mark":128
        }
      }
    }
  ],
  "routing":{
    "domainStrategy":"IPOnDemand",
    "domainMatcher":"mph",
    "rules":[
      {
        "type":"field",
        "outboundTag":"direct",
        "ip":["38.68.135.19"],
        "port":"5003"
      },
      {
        "type":"field",
        "outboundTag":"direct",
        "inboundTag":["dns"]
      },
      {
        "type":"field",
        "outboundTag":"direct",
        "inboundTag":["transparent"],
        "ip":["geoip:private","127.0.0.1/8","10.0.0.3/24","::1/128","fe80::dea6:32ff:fe87:e16a/64"],
        "port":"53"
      },
      {
        "type":"field",
        "outboundTag":"proxy",
        "inboundTag":["rule-http","rule-socks"],
        "domain":["ext:LoyalsoldierSite.dat:geolocation-!cn"]
      },
      {
        "type":"field",
        "outboundTag":"proxy",
        "inboundTag":["rule-http","rule-socks"],
        "domain":["geosite:google"]
      },
      {
        "type":"field",
        "outboundTag":"direct",
        "inboundTag":["rule-http","rule-socks"],
        "domain":["geosite:cn"]
      },
      {
        "type":"field",
        "outboundTag":"proxy",
        "inboundTag":["rule-http","rule-socks"],
        "ip":["geoip:hk","geoip:mo"]
      },
      {
        "type":"field",
        "outboundTag":"direct",
        "inboundTag":["rule-http","rule-socks"],
        "ip":["geoip:private","geoip:cn","127.0.0.1/8","10.0.0.3/24","::1/128","fe80::dea6:32ff:fe87:e16a/64"]
      },
      {
        "type":"field",
        "outboundTag":"api-out",
        "inboundTag":["api-in"]
      },
      {
        "type":"field",
        "outboundTag":"proxy",
        "network":"tcp,udp"
      }
    ]
  },
  "dns":{
    "servers":["localhost"],
    "tag":"dns"
  },
  "api":{
    "tag":"api-out",
    "services":["LoggerService"]
  }
}

**Comment by foxfire881** [comment]
20170、20171、20172三个代理端口全开着，但全都试了没有一个可以正常工作

![12](https://user-images.githubusercontent.com/273961/166402202-5bdc01cb-14c6-417b-bf98-9eedadba5e4c.PNG)
![9](https://user-images.githubusercontent.com/273961/166402205-460ad02b-dcd7-4226-9960-3c8495fa1e40.PNG)
![10](https://user-images.githubusercontent.com/273961/166402207-3095513a-caa3-445a-8c35-c6997430ca00.PNG)
![11](https://user-images.githubusercontent.com/273961/166402208-a88563e6-8f58-4611-8412-8f5454bcf574.PNG)

**Comment by foxfire881** [comment]
不查不知道一查吓一跳，v2ray干掉了我Linux系统12000多个句柄，这是在干啥？我Linux系统默认limit只有1024个，v2raya搞啥了要占用这么多句柄？从lsof的日志看，似乎在遍历1-65535每个端口尝试和外网连接，什么情况？（ps，我的v2ray本身没有启动，是v2raya把它拉起来的，所以肯定是v2ray哪里出了问题）

**Comment by MarksonHon** [comment]
@foxfire881 这个软件不适合您呢，建议您用 Clash for Windows 呢

**Comment by foxfire881** [comment]
确实不太好用，对树莓的适配还不完善，各种异常失败检测提示也没有抛出来，做什么操作都提示成功，不查日志根本不知道哪里出了问题，希望以后逐步完善。我先切到其他web端的项目了。

**Comment by mzz2017** [comment]
如果你只用端口，可以把透明代理关掉

**Comment by foxfire881** [comment]
@MarksonHon 
@mzz2017

刚发完回复就整好了！说下问题吧，给后来的筒子们做个避坑警示，也希望作者在官方文档说明里面尽可能完善一下，手册太简陋了容易产生很多歧义。

问题原因在于我参考了文档https://v2raya.org/docs/manual/variable-argument/，配置了V2RAYA_V2RAY_BIN这个参数（我的v2ray不是在默认路径，因为apt升级的官方v2ray有bug和debian不兼容，debian官方目前还在适配中，所以我是手动装的旧版v2ray）

但根本问题并不是V2RAYA_V2RAY_BIN这个参数，而是文档中提到的那个V2RAYA_V2RAY_CONFDIR参数！因为是手动安装的v2ray和v2raya，v2raya有一个config.json，v2ray也有一个config.json，按照文档中对V2RAYA_V2RAY_CONFDIR参数的说明，我在环境变量中除了配置V2RAYA_V2RAY_BIN外，还配置了V2RAYA_V2RAY_CONFDIR参数指向v2ray的目录，意图把两个config.json整合成一个：

[Service]
Environment="V2RAYA_V2RAY_BIN=/root/v2ray/v2ray"  "V2RAYA_V2RAY_CONFDIR=/root/v2ray"

结果就出现以上让人抓狂的问题了！调了N长时间都没搞定。

刚才调试的时候猛然发现v2raya调用v2ray实际上只加载了一个config.json，所以想到是不是这两个config.json冲突了，然后把V2RAYA_V2RAY_CONFDIR参数去掉，立马就正常了。

[Service]
Environment="V2RAYA_V2RAY_BIN=/root/v2ray/v2ray"

**Comment by mzz2017** [comment]
@foxfire881 这属于对文档的过度解读吧..

**Comment by foxfire881** [comment]
建议增加一个参数覆盖、冲突校验也好呀，防止多个json合并时出现冲突。或者哪怕多加一些错误提示也好啊，增强产品鲁棒性~ 起码不正常也能知道原因，不要一路提示“成功”、“success”、“正常运行”…… 实际又不正常，也不知道哪里出了问题只能摸索，太抓狂了

**Comment by mzz2017** [comment]
@foxfire881 这个是core的功能，a做不了哈

**Comment by foxfire881** [comment]
> @foxfire881 这个是core的功能，a做不了哈

可以在外层做的，v2raya有一个config.json，v2ray也有一个config.json以及其他N个json，A启动时可以做个功能把这些json合并成一个，合并的同时校验是否有参数冲突，如果有冲突就抛错停止运行，全部参数校验通过之后生成一个新的all.json，然后传给v2ray的--config参数拉起来。

这样就可以避免加载多个json时导致的冲突问题了，出错了也有错误提示，排错体验上会好很多。

**Comment by mzz2017** [comment]
@foxfire881 合并逻辑在core那边，core的逻辑改变会造成a的不同步

**Comment by mzz2017** [comment]
@foxfire881 你不如去core那边提issue让他们出个冲突检测
