### ISSUE TITLE
支持自动切换可用节点

### ISSUE THREAD

**Issue by lylunula** [v2rayA/v2rayA#514]
### 您想提出的功能特性是否和现有问题相关？

一次订阅有多个地址，自动切换可用节点；如果都不可用，则自动更新订阅。这样能确保更加无缝的代理体验。要不然当前状态，要不先手动测试一下节点是否失效，失效后再看订阅是否更新，完全就是人工重复劳动，希望能自动解决失效问题

### 功能特性内容

1. 每x分钟自动测试各个节点可用性及速度
2. 自动切换到可用性&&速度更快的节点
3. 如果可用性都为0，则自动更新订阅
4. 更新完订阅后，自动到第一步循环
5. 如果遇到n次连续遇到失效，则提醒用户

**Comment by MarksonHon** [comment]
@lylunula 建议你找你的机场定制一个软件
目前市面上没有任何一个软件支持你所说的功能

**Comment by lylunula** [comment]
Shadowrocket和clash都支持的...（比如：https://lancellc.gitbook.io/clash/clash-config-file/proxy-groups/auto）

> @lylunula 建议你找你的机场定制一个软件 目前市面上没有任何一个软件支持你所说的功能

**Comment by mzz2017** [comment]
@lylunula v2ray系的客户端偏向于可配置性，clash系客户端偏向于操作简单性，各有侧重。基于v2ray的客户端很难做到clash的这些面向机场用户的特性。
