### ISSUE TITLE
浏览器http协议地址文件下载慢

### ISSUE THREAD

**Issue by yanchenyuvip** [v2rayA/v2rayA#515]
![image](https://user-images.githubusercontent.com/44298325/166861216-00dd7fad-b61c-4731-a642-5fc7ce9848af.png)

### 版本、安装方式、系统

1. v2rayA 1.5.7

2. deb包

3. Ubuntu 22.04

### 描述问题：

网页正常，http文件下载慢，但https下载文件正常；

### v2rayA运行日志（Optional）：
![image](https://user-images.githubusercontent.com/44298325/166861351-4d40946b-7580-4914-a125-f0b1cd2c85fb.png)

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。
![image](https://user-images.githubusercontent.com/44298325/166861372-ce0c37be-7050-416b-abbf-78c4fe2a1925.png)

![image](https://user-images.githubusercontent.com/44298325/166861391-dc637f1f-4c36-4e85-829c-60d8f3e641e0.png)

**Comment by mzz2017** [comment]
请提供和其他软件对比以佐证是v2rayA的问题

**Comment by yanchenyuvip** [comment]
> 

同样的节点，在使用clash下载同样的文件，速度大约能达到宽带上限，我确认了此时clash自动选择的节点和v2raya下载的节点相同，但是速度只有如图所示。

**Comment by mzz2017** [comment]
是ssr吗

**Comment by yanchenyuvip** [comment]
> 是ssr吗

不，都是v2ray

**Comment by mzz2017** [comment]
@yanchenyuvip 那应该没有问题，你再确认一下

**Comment by yanchenyuvip** [comment]
> 



> @yanchenyuvip那应该没有问题，你再确认一下

不，我

> @yanchenyuvip那应该没有问题，你再确认一下

我再cenos7和ubuntu22.04分别复现了该问题，确实是http下载文件很慢！

**Comment by mzz2017** [comment]
@yanchenyuvip 你用clash测试是什么时候的事情

**Comment by yanchenyuvip** [comment]
> @yanchenyuvip你用冲突测试是什么时候的事情

都是11点50左右，同样的网络，同样的节点。

**Comment by yanchenyuvip** [comment]
复现很简单，没环境，我可以提供ubuntu，让你们用todesk远程，一试变知！提供个邮箱即可。

**Comment by mzz2017** [comment]
@yanchenyuvip mzz@tuta.io

**Comment by mzz2017** [comment]
@yanchenyuvip 稍等，我看到你这里使用了 gfwlist 的透明代理，你的这个地址可能没有被代理，你换用大陆白名单试一下

**Comment by yanchenyuvip** [comment]
> @yanchenyuvip 稍等，我看到你这里使用了 gfwlist 的透明代理，你的这个地址可能没有被代理，你换用大陆白名单试一下

我刚吃完饭试了下，确实如你所说，换了大陆白名单模式，http轻松过百兆下载速度，这个问题，我建议后期还是想个比较合理的解决方案吧。

**Comment by yanchenyuvip** [comment]
>该问题已经处理完成，因含个人信息，请尽快删除该issue！

**Comment by mzz2017** [comment]
@yanchenyuvip 没关系，我的邮箱是公开的
