### ISSUE TITLE
建议支持 Windows 托盘图标

### ISSUE THREAD

**Issue by neilbowman666** [v2rayA/v2rayA#516]
### 您想提出的功能特性是否和现有问题相关？
目前 Windows 运行 V2RayA 没有托盘图标，无法知晓是否是在后台运行，且没法找到除任务管理器外的安全退出方式。

### 功能特性内容
建议为 Windows 增加托盘图标功能。

**Comment by mzz2017** [comment]
@neilbowman666 服务是没有托盘的，服务自己也不能主动退出

**Comment by MarksonHon** [comment]
1. 如果你想完全控制 v2rayA 的运行，那么建议你[从 scoop 安装](https://github.com/v2rayA/v2raya-scoop)，而不是用安装包。
2. Windows 的后台服务不会拥有托盘图标，且默认服务不参与桌面交互。
