### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by liuye0331** [v2rayA/v2rayA#519]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
[A] [main.go:25]  network is connected
[A] [main.go:27]  V2Ray binary is
[A] [main.go:27]  V2Ray asset directory is /run/user/0/v2raya
[A] [main.go:27]  v2rayA working directory is /media/fa/boot3/v2raya-1.5.7-1.armv7/usr/bin
[A] [main.go:27]  v2rayA configuration directory is /etc/v2raya
[A] [main.go:27]  Golang: go1.18
[A] [main.go:27]  OS: linux
[A] [main.go:27]  Arch: arm
[A] [main.go:27]  Lite: false
[A] [main.go:27]  Version: 1.5.7
[A] [main.go:27]  Starting...
[I] [main.go:28]  the core was not running the last time v2rayA exited
[A] [index.go:117]  v2rayA is listening at http://127.0.0.1:2017
[A] [index.go:117]  v2rayA is listening at http://192.168.1.240:2017
[A] [index.go:117]  v2rayA is listening at http://192.168.100.1:2017
[A] [index.go:117]  v2rayA is listening at http://[::1]:2017
[A] [index.go:117]  v2rayA is listening at http://[fe80::e4d0:67ff:feb7:8992]:2017

2. What approach of installation do you install V2rayA?
with rpm

3. What is your operating system?
linux (not openwrt)

### Description

failed to resolve subscription address: Get "xxxxxxxxxxxxxxxxxxxxx": **x509: certificate has expired or is not yet valid: current time 2022-05-07T09:42:30+08:00 is after 2021-09-30T14:01:15Z**

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 failed to resolve subscription address: Get "xxxxxxxxxxxxxxxxxxxxx": **x509: certificate has expired or is not yet valid: current time 2022-05-07T09:42:30+08:00 is after 2021-09-30T14:01:15Z**
 # docker mode
 docker logs v2raya
 ```
```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by liuye0331** [comment]
Is there a approach to ignore certificate vertification?

**Comment by mzz2017** [comment]
@liuye0331 no option about that. sorry.

**Comment by MarksonHon** [comment]
You can visit [this site](https://www.google.com/search?q=certificate+has+expired+or+is+not+yet+valid) to get help.

**Comment by MarksonHon** [comment]
@MarksonHon Or you can join the group:

**Comment by MarksonHon** [comment]
@MarksonHon https://t.me/v2raya
