### ISSUE TITLE
请教关于客户端DNS设置问题

### ISSUE THREAD

**Issue by egg1234** [v2rayA/v2rayA#522]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.6.2

2. 你通过什么方式安装v2rayA
下载deb文件本地安装

4. 你所使用的操作系统
Debian 10

### 描述问题：

v2rayA的防止DNS污染设置为转发DNS请求，大陆白名单，redirect，假设v2rayA的地址是10.0.0.2

想请教的是：
局域网客户端的机器把网关设置为10.0.0.2，把DNS地址设置为10.0.0.2
与
局域网客户端的机器把网关设置为10.0.0.2，把DNS地址设置为8.8.8.8

上面这两种客户端的DNS设置方式对客户端的访问有什么不同的影响吗？

谢谢！

**Comment by Ling128** [comment]
同问

**Comment by mzz2017** [comment]
redirect并打开DNS转发时，会开一个53端口用于远端转发DNS。所有使用该53端口进行的DNS请求会在v2ray内部进行分流，国外域名将使用远端解析，国内域名使用国内公共DNS服务器解析。不使用该53端口的将不会通过v2ray。
目前tproxy并打开DNS转发时，不开放53端口，但会拦截所有DNS请求进入v2ray并分流，指不指定DNS服务器是一样的。
