### ISSUE TITLE
v2rayA无法自启，无法运行

### ISSUE THREAD

**Issue by zhangy104** [v2rayA/v2rayA#525]
版本、安装方式、系统
1. 你在使用什么版本的v2rayA 
    1.5.7
2. 你通过什么方式安装v2rayA
    https://v2raya.org/docs/prologue/installation/debian/
3. 你所使用的操作系统
    PVE下LXC容器 Ubuntu 21.10，无特权，嵌套

描述问题：
安装完成后，设置开机自启，reboot后无法启动，通过SSH手动输入v2raya后能够运行，ctrl+c后就停止运行，无法后端运行

 v2rayA运行日志（Optional）：
root@v2rayA:~# journalctl -u v2raya | tail -n 50
May 11 15:23:15 v2rayA v2raya[377]: runtime.newm1(0xc000056000)
May 11 15:23:15 v2rayA v2raya[377]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/proc.go:2147 +0xcf
May 11 15:23:15 v2rayA v2raya[377]: runtime.newm(0x43ec31?, 0x0, 0x184ff00?)
May 11 15:23:15 v2rayA v2raya[377]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/proc.go:2122 +0x12c
May 11 15:23:15 v2rayA v2raya[377]: runtime.main.func1()
May 11 15:23:15 v2rayA v2raya[377]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/proc.go:171 +0x29
May 11 15:23:15 v2rayA v2raya[377]: runtime.systemstack()
May 11 15:23:15 v2rayA v2raya[377]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/asm_amd64.s:469 +0x49
May 11 15:23:15 v2rayA v2raya[377]: goroutine 1 [running]:
May 11 15:23:15 v2rayA v2raya[377]: runtime.systemstack_switch()
May 11 15:23:15 v2rayA v2raya[377]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/asm_amd64.s:436 fp=0xc000052780 sp=0xc000052778 pc=0x461da0
May 11 15:23:15 v2rayA v2raya[377]: runtime.main()
May 11 15:23:15 v2rayA v2raya[377]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/proc.go:170 +0x6d fp=0xc0000527e0 sp=0xc000052780 pc=0x43656d
May 11 15:23:15 v2rayA v2raya[377]: runtime.goexit()
May 11 15:23:15 v2rayA v2raya[377]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000527e8 sp=0xc0000527e0 pc=0x463e81
May 11 15:23:15 v2rayA systemd[1]: v2raya.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 11 15:23:15 v2rayA systemd[1]: v2raya.service: Failed with result 'exit-code'.
May 11 15:23:15 v2rayA systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 4.
May 11 15:23:15 v2rayA systemd[1]: Stopped v2rayA Service.
May 11 15:23:15 v2rayA systemd[1]: Started v2rayA Service.
May 11 15:23:15 v2rayA v2raya[378]: runtime: failed to create new OS thread (have 2 already; errno=11)
May 11 15:23:15 v2rayA v2raya[378]: runtime: may need to increase max user processes (ulimit -u)
May 11 15:23:15 v2rayA v2raya[378]: fatal error: newosproc
May 11 15:23:15 v2rayA v2raya[378]: runtime stack:
May 11 15:23:15 v2rayA v2raya[378]: runtime.throw({0xe5768d?, 0x7fff9f9501a8?})
May 11 15:23:15 v2rayA v2raya[378]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/panic.go:992 +0x71
May 11 15:23:15 v2rayA v2raya[378]: runtime.newosproc(0xc000056000)
May 11 15:23:15 v2rayA v2raya[378]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/os_linux.go:182 +0x185
May 11 15:23:15 v2rayA v2raya[378]: runtime.newm1(0xc000056000)
May 11 15:23:15 v2rayA v2raya[378]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/proc.go:2147 +0xcf
May 11 15:23:15 v2rayA v2raya[378]: runtime.newm(0x43ec31?, 0x0, 0x184ff00?)
May 11 15:23:15 v2rayA v2raya[378]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/proc.go:2122 +0x12c
May 11 15:23:15 v2rayA v2raya[378]: runtime.main.func1()
May 11 15:23:15 v2rayA v2raya[378]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/proc.go:171 +0x29
May 11 15:23:15 v2rayA v2raya[378]: runtime.systemstack()
May 11 15:23:15 v2rayA v2raya[378]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/asm_amd64.s:469 +0x49
May 11 15:23:15 v2rayA v2raya[378]: goroutine 1 [running]:
May 11 15:23:15 v2rayA v2raya[378]: runtime.systemstack_switch()
May 11 15:23:15 v2rayA v2raya[378]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/asm_amd64.s:436 fp=0xc000052780 sp=0xc000052778 pc=0x461da0
May 11 15:23:15 v2rayA v2raya[378]: runtime.main()
May 11 15:23:15 v2rayA v2raya[378]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/proc.go:170 +0x6d fp=0xc0000527e0 sp=0xc000052780 pc=0x43656d
May 11 15:23:15 v2rayA v2raya[378]: runtime.goexit()
May 11 15:23:15 v2rayA v2raya[378]:         /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000527e8 sp=0xc0000527e0 pc=0x463e81
May 11 15:23:15 v2rayA systemd[1]: v2raya.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 11 15:23:15 v2rayA systemd[1]: v2raya.service: Failed with result 'exit-code'.
May 11 15:23:15 v2rayA systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 5.
May 11 15:23:15 v2rayA systemd[1]: Stopped v2rayA Service.
May 11 15:23:15 v2rayA systemd[1]: v2raya.service: Start request repeated too quickly.
May 11 15:23:15 v2rayA systemd[1]: v2raya.service: Failed with result 'exit-code'.
May 11 15:23:15 v2rayA systemd[1]: Failed to start v2rayA Service.

v2rayA设置以及相关截图
<img width="609" alt="image" src="https://user-images.githubusercontent.com/70047215/167889757-a6dcf446-8ed3-41e2-b0de-aa401a9d9ca4.png">

**Comment by zhangy104** [comment]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/70047215/167891355-59531d0c-1521-4120-b3a3-f1a58852f718.png">

**Comment by mzz2017** [comment]
@zhangy104 你调整过sysctl内核参数吗

**Comment by zhangy104** [comment]
@mzz2017 没有，新建虚拟机一样会出现类似问题，在debian11下也会复现。PVE主机是用过pvetools，其他就没动过

**Comment by MarksonHon** [comment]
@zhangy104

**Comment by MarksonHon** [comment]
我从 GitHub Release 直接安装 Debian 包没有问题，你要不也直接下载安装包安装看看？
![图片](https://user-images.githubusercontent.com/50002150/167964491-fdfe3561-c8cb-46dd-8f95-bd2e55d92521.png)

**Comment by zhangy104** [comment]
> 我从 GitHub Release 直接安装 Debian 包没有问题，你要不也直接下载安装包安装看看？
> ![图片](https://user-images.githubusercontent.com/50002150/167964491-fdfe3561-c8cb-46dd-8f95-bd2e55d92521.png)
> 

好的，我晚上回去试一试，谢谢

**Comment by zhangy104** [comment]
> 我从 GitHub Release 直接安装 Debian 包没有问题，你要不也直接下载安装包安装看看？
> ![图片](https://user-images.githubusercontent.com/50002150/167964491-fdfe3561-c8cb-46dd-8f95-bd2e55d92521.png)
> 

试了下，还是不行

**Comment by MarksonHon** [comment]
进群聊吧，issue区不适合讨论问题：
<https://t.me/v2raya_zh>
