### ISSUE TITLE
如何添加往gfwlist中添加自定义的ip地址段

### ISSUE THREAD

**Issue by iyzgit** [v2rayA/v2rayA#531]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.7
2. 你通过什么方式安装v2rayA
docker

3. 你所使用的操作系统
ubuntu

### 描述问题：

使用的是透明代理/gfwlist方式
v2raya运行没有任何问题
现在的问题是有些网站不在gfwlist的名单中，
请问有什么方法能添加一些IP地址段或者域名网址到gfwlist中？
或者有什么方法既使用gfwlist透明代理同时又能有一些自己定义的ip地址段也被透明代理？

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@iyzgit 使用RoutingA
