### ISSUE TITLE
请问我设置了代理后可以成功访问Google等外网，为什么不能ping通呢

### ISSUE THREAD

**Issue by XG520** [v2rayA/v2rayA#532]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.5.7

2. What approach of installation do you install V2rayA?
rpm 安装

3. What is your operating system?
CentOS Linux release 7.9.2009 (Core)

### Description

如题，我设置代理后可ssh国外服务器，可是不能使用scp和ping

```

**Comment by MarksonHon** [comment]
ICMP 信号不会被代理
