### ISSUE TITLE
请问：我使用scp和ansible传输大文件提示连接关闭

### ISSUE THREAD

**Issue by XG520** [v2rayA/v2rayA#534]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.7

2. 你通过什么方式安装v2rayA
rpm

3. 你所使用的操作系统
CentOS Linux release 7.9.2009 (Core)

### 描述问题：
如题：
我使用scp及ansible 传输200M的文件失败
传输1m左右的文件能成功。

我尝试使用ShadowsocksR测试订阅，能够传输成功。

请问是否是我的v2rayA设置不合理。
还是我没有成功配置代理。

我是在宿主机上安装的v2rayA及v2ray，通过写入一下环境变量到profile中配置宿主机代理：
export proxy=http://localhost:20172/
export http_proxy=http://localhost:20172/
export https_proxy=http://localhost:20172/
export ftp_proxy=ftp://localhost:20172

现在需要连接外网的是一个docker容器，
我在容器中执行scp命令传输200M的文件提示如下：
ad packet length 4290793138.
ssh_dispatch_run_fatal: Connection to xxx.xxx.xxx.xxx port 22: Connection corrupted
lost connection

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50

[root@localhost ~]#  journalctl -u v2raya | tail -n 50
-- Logs begin at 一 2022-04-11 10:31:30 CST, end at 六 2022-05-14 12:10:23 CST. --
5月 13 17:31:11 localhost.localdomain systemd[1]: Started v2rayA Service.


 
 ```
```shell
# 此处贴入运行日志
022/05/14 11:50:07.356 [I] [io.go:428] 127.0.0.1:41760 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:50:17.581 [I] [io.go:428] 127.0.0.1:52720 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:50:17.581 [I] [io.go:428] 127.0.0.1:33921 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:50:27.822 [I] [io.go:428] 127.0.0.1:59718 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:50:27.822 [I] [io.go:428] 127.0.0.1:44880 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:50:38.061 [I] [io.go:428] 127.0.0.1:36184 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:50:38.061 [I] [io.go:428] 127.0.0.1:42982 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:50:48.296 [I] [io.go:428] 127.0.0.1:39675 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:50:48.296 [I] [io.go:428] 127.0.0.1:57515 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:50:58.534 [I] [io.go:428] 127.0.0.1:49560 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:50:58.534 [I] [io.go:428] 127.0.0.1:58104 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:51:08.838 [I] [io.go:428] 127.0.0.1:49737 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:51:08.838 [I] [io.go:428] 127.0.0.1:37105 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:51:19.057 [I] [io.go:428] 127.0.0.1:55156 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:51:19.057 [I] [io.go:428] 127.0.0.1:52353 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:51:29.302 [I] [io.go:428] 127.0.0.1:51984 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:51:29.302 [I] [io.go:428] 127.0.0.1:49562 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:51:39.538 [I] [io.go:428] 127.0.0.1:38542 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:51:39.538 [I] [io.go:428] 127.0.0.1:42423 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:51:49.832 [I] [io.go:428] 127.0.0.1:47730 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:51:49.832 [I] [io.go:428] 127.0.0.1:39183 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:52:00.083 [I] [io.go:428] 127.0.0.1:41014 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:52:00.083 [I] [io.go:428] 127.0.0.1:53602 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:52:10.316 [I] [io.go:428] 127.0.0.1:60872 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:52:10.317 [I] [io.go:428] 127.0.0.1:39572 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:52:20.547 [I] [io.go:428] 127.0.0.1:49126 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:52:20.547 [I] [io.go:428] 127.0.0.1:40504 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:52:30.808 [I] [io.go:428] 127.0.0.1:41288 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:52:30.808 [I] [io.go:428] 127.0.0.1:60695 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:52:41.051 [I] [io.go:428] 127.0.0.1:52568 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:52:41.051 [I] [io.go:428] 127.0.0.1:44786 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:52:51.276 [I] [io.go:428] 127.0.0.1:60851 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:52:51.276 [I] [io.go:428] 127.0.0.1:40207 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:53:01.525 [I] [io.go:428] 127.0.0.1:46100 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 11:53:01.525 [I] [io.go:428] 127.0.0.1:44020 accepted udp:2.0.1.7:53 [dns-out]


```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![Dingtalk_20220514135213](https://user-images.githubusercontent.com/83686186/168412844-47d9034d-9cb4-47f7-b31e-41f29454a094.jpg)
![Dingtalk_20220514135225](https://user-images.githubusercontent.com/83686186/168412848-a5abfc71-7f7e-4e1c-88c6-fab64e4d9c89.jpg)
![Dingtalk_20220514135236](https://user-images.githubusercontent.com/83686186/168412852-f297d50e-5182-4762-8692-6cdcf6946a2e.jpg)

**Comment by XG520** [comment]
2022/05/14 13:53:01.721 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:02.722 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:03.722 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:03.814 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:04.723 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:04.815 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:05.723 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:05.816 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:06.723 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:06.817 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:07.725 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:07.818 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:07.979 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:08.725 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:08.790 [I] [io.go:428] 127.0.0.1:34539 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 13:53:08.790 [I] [io.go:428] 127.0.0.1:54281 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 13:53:08.819 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:08.980 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:09.726 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:09.819 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:09.981 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:10.727 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:10.820 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:10.982 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:11.728 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:11.821 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:11.983 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:12.532 [I] [process.go:67] low memory: 1622MiB, set V2RAY_CONF_GEOLOADER=memconservative
2022/05/14 13:53:12.545 [I] [io.go:428] V2Ray 4.45.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.1 linux/amd64)
2022/05/14 13:53:12.546 [I] [io.go:428] A unified platform for anti-censorship.
2022/05/14 13:53:12.550 [I] [io.go:428] [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/05/14 13:53:12.732 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:12.822 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:12.969 [I] [io.go:428] 127.0.0.1:41743 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 13:53:12.969 [I] [io.go:428] 127.0.0.1:44652 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 13:53:12.983 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded
2022/05/14 13:53:13.137 [I] [io.go:428] 127.0.0.1:56876 accepted tcp:127.0.0.1:0 [api-out]
2022/05/14 13:53:13.733 [I] [io.go:428] 127.0.0.1:57120 accepted tcp:127.0.0.1:0 [api-out]
2022/05/14 13:53:14.569 [I] [process.go:67] low memory: 1622MiB, set V2RAY_CONF_GEOLOADER=memconservative
2022/05/14 13:53:14.571 [W] [socks5.go:83] [socks5] failed to listen on 127.0.0.1:35638: listen tcp 127.0.0.1:35638: bind: address already in use
2022/05/14 13:53:14.587 [I] [io.go:428] V2Ray 4.45.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.1 linux/amd64)
2022/05/14 13:53:14.588 [I] [io.go:428] A unified platform for anti-censorship.
2022/05/14 13:53:14.588 [I] [io.go:428] [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/05/14 13:53:14.824 [W] [asm_amd64.s:1571] ObservatoryProducer: did not connect: context deadline exceeded

**Comment by XG520** [comment]
-- Logs begin at 一 2022-04-11 10:31:30 CST, end at 六 2022-05-14 14:02:36 CST. --
5月 13 17:31:11 localhost.localdomain systemd[1]: Started v2rayA Service.
5月 14 13:53:29 localhost.localdomain v2raya[3181]: panic: runtime error: invalid memory address or nil pointer dereference
5月 14 13:53:29 localhost.localdomain v2raya[3181]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xba5ee3]
5月 14 13:53:29 localhost.localdomain v2raya[3181]: goroutine 39927 [running]:
5月 14 13:53:29 localhost.localdomain v2raya[3181]: github.com/v2rayA/v2rayA/core/v2ray.NewProcess.func2()
5月 14 13:53:29 localhost.localdomain v2raya[3181]: /home/runner/work/v2rayA/v2rayA/service/core/v2ray/process.go:77 +0xa3
5月 14 13:53:29 localhost.localdomain v2raya[3181]: created by github.com/v2rayA/v2rayA/core/v2ray.NewProcess
5月 14 13:53:29 localhost.localdomain v2raya[3181]: /home/runner/work/v2rayA/v2rayA/service/core/v2ray/process.go:74 +0x43b
5月 14 13:53:29 localhost.localdomain systemd[1]: v2raya.service: main process exited, code=exited, status=2/INVALIDARGUMENT
5月 14 13:53:29 localhost.localdomain systemd[1]: Unit v2raya.service entered failed state.
5月 14 13:53:29 localhost.localdomain systemd[1]: v2raya.service failed.
5月 14 13:53:29 localhost.localdomain systemd[1]: v2raya.service holdoff time over, scheduling restart.
5月 14 13:53:29 localhost.localdomain systemd[1]: Stopped v2rayA Service.
5月 14 13:53:29 localhost.localdomain systemd[1]: Started v2rayA Service.

**Comment by XG520** [comment]
2022/05/14 14:05:29.549 [I] [io.go:428] A unified platform for anti-censorship.
2022/05/14 14:05:29.552 [I] [io.go:428] [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/05/14 14:05:29.944 [I] [io.go:428] 127.0.0.1:44934 accepted tcp:127.0.0.1:0 [api-out]
2022/05/14 14:05:30.163 [I] [io.go:428] 127.0.0.1:45178 accepted tcp:127.0.0.1:0 [api-out]
2022/05/14 14:05:40.573 [I] [io.go:428] 127.0.0.1:46306 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:05:40.573 [I] [io.go:428] 127.0.0.1:45948 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:05:51.983 [I] [io.go:428] 127.0.0.1:34524 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:05:51.983 [I] [io.go:428] 127.0.0.1:41426 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:06:03.758 [I] [io.go:428] 127.0.0.1:50893 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:06:03.758 [I] [io.go:428] 127.0.0.1:39184 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:06:14.002 [I] [io.go:428] 127.0.0.1:59885 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:06:14.002 [I] [io.go:428] 127.0.0.1:44287 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:06:24.304 [I] [io.go:428] 127.0.0.1:52492 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:06:24.304 [I] [io.go:428] 127.0.0.1:55701 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:06:33.272 [I] [io.go:428] 172.17.0.2:51082 accepted tcp:103.9.206.115:2012 [『🇭🇰 Hong Kong 01』]
2022/05/14 14:06:33.272 [I] [io.go:428] 127.0.0.1:45775 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:06:33.272 [I] [io.go:428] 127.0.0.1:52709 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:06:34.532 [I] [io.go:428] 127.0.0.1:60477 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:06:34.532 [I] [io.go:428] 127.0.0.1:39280 accepted udp:2.0.1.7:53 [dns-out]
2022/05/14 14:06:44.757 [I] [io.go:428] 127.0.0.1:58027 accepted udp:2.0.1.7:53 [dns-out]

**Comment by mzz2017** [comment]
你发的两段日志是同一次v2ray-core的启动吗

**Comment by XG520** [comment]
后面两段是同一次启动

**Comment by XG520** [comment]
![Dingtalk_20220514145844](https://user-images.githubusercontent.com/83686186/168414776-0e0db4f4-a344-4760-8b7b-50afb5fa25b2.jpg)
这两段是同一次启动

**Comment by XG520** [comment]
刚刚测试了13mb的文件，也失败了

**Comment by XG520** [comment]
现在好了，我设置为非分流模式的代理端口就好了
