### ISSUE TITLE
Support SOCKS as outbound server [支援SOCKS作為伺服器]

### ISSUE THREAD

**Issue by star-39** [v2rayA/v2rayA#535]
### Content of the feature

We currently have http/https as outbound. Paring with RoutingA, v2raya does a pretty good job routing traffics.

It would be nice to support SOCKS as a outbound server, which would probably have higher performance than http.

I have already got this feature working, PR should be submitted in days.

Thanks!

---------------------------------

目前V2RAYA支援http/https作為伺服器, 配合RoutingA可以做到很好的路由功能.

支援SOCKS作為伺服器或許可以提供更好的效能.

此功能我已做好, 測試完整後會submit PR.

謝謝!

![image](https://user-images.githubusercontent.com/75669297/168465529-1818d73c-9a53-4dea-a534-b566adbfead6.png)

![image](https://user-images.githubusercontent.com/75669297/168465549-5870990b-2217-4291-b9ab-71efef2222a9.png)

**Comment by mzz2017** [comment]
@star-39 welcome

**Comment by star-39** [comment]
Resolved by #537
