### ISSUE TITLE
关于模式的咨询

### ISSUE THREAD

**Issue by mingzaily** [v2rayA/v2rayA#536]
### Version, approach of installation, operating system

1. What version of v2rayA are you using? 1.5.7

2. What approach of installation do you install V2rayA? docker 使用的是macvlan网卡，非默认bridge

3. What is your operating system? naraid 

### Description
大佬们好，我想咨询下以下问题
1. `20171` 和 `20172` 有啥区别
前提：`透明代理/系统代理` 和 `规则端口的分流模式` 均选择 GFWList
现象：
- 当我使用20171端口代理时，测速网和国内外ip地址查询均显示代理的网址
![1652610792(1)](https://user-images.githubusercontent.com/44798713/168468414-cd0a518d-b18e-44ba-aed3-77183fa280f3.png)
- 当我使用20172端口代理时，国内外ip地址查询分别显示国内外地址
![1652610881(1)](https://user-images.githubusercontent.com/44798713/168468483-2ed28dec-019f-4ee9-a5de-4555b9c1cedd.png)

上述现象 `20171` 是否是叫做全局模式，如果是全局模式 ，我就不太能理解 `透明代理/系统代理` 这个选项配的意义是啥

2. `开启IP转发` 是啥功能
我能理解开启端口转发应该是旧版的局域网设备使用，但是 `开启IP转发` 确实不太懂

**Comment by mzz2017** [comment]
@mingzaily 并不是所有软件都支持设置端口，而透明代理是通用的

**Comment by mzz2017** [comment]
@mingzaily 不开启ip转发时作为网关不转发三层包，例如icmp，ping会不通

**Comment by mingzaily** [comment]
> @mingzaily 并不是所有软件都支持设置端口，而透明代理是通用的

意思是，不支持设置端口的设备或软件，直接填v2rayA所在的ip地址就可以了？这时候用的就是`透明代理/系统代理`配置的模式？

**Comment by mingzaily** [comment]
> @mingzaily 不开启ip转发时作为网关不转发三层包，例如icmp，ping会不通

请问v2rayA如何做网关使用，不都是用代理的方式吗？是我理解的静态IP+v2rayA吗？

**Comment by mzz2017** [comment]
@mingzaily 直接把网关设为 v2rayA 所在 ip 即可。但在 macvlan 情况下宿主机这样操作需要考虑一些问题。

**Comment by mingzaily** [comment]
> @mingzaily 直接把网关设为 v2rayA 所在 ip 即可。但在 macvlan 情况下宿主机这样操作需要考虑一些问题。

我已经在宿主机上也添加了macvlan网卡，宿主机和docker可以通讯了

> @mingzaily 并不是所有软件都支持设置端口，而透明代理是通用的

`20171端口`应用场景有哪些呀，不太懂，我目前都是系统设置代理或者用switchOmega设置浏览器代理，均可以设置端口

**Comment by mzz2017** [comment]
@mingzaily 给需要的人用的

**Comment by mingzaily** [comment]
> @mingzaily 给需要的人用的

额，好吧，一般人用20172应该就够了，谢谢

**Comment by mzz2017** [comment]
@mingzaily 是的
