### ISSUE TITLE
更新订阅，REMARKS中文日志报错

### ISSUE THREAD

**Issue by mingzaily** [v2rayA/v2rayA#538]
### Version, approach of installation, operating system

1. What version of v2rayA are you using? 1.5.7

2. What approach of installation do you install V2rayA? docker

3. What is your operating system? unraid

### Description
更新订阅的时候 备注带中文，日志会报错

![image](https://user-images.githubusercontent.com/44798713/168480552-7f949b3b-c08d-4344-b10d-30b4c85a32fe.png)

**Comment by mzz2017** [comment]
这是个warning，不会影响
