### ISSUE TITLE
希望可以根据端口实现不同的出站模式

### ISSUE THREAD

**Issue by mingzaily** [v2rayA/v2rayA#540]
1. 在右上角配了出站均衡，但配置了看日志好像走的都是proxy这个`outbound`，要怎么设置才能使用第二个`outbound`
2. 有些机场有游戏节点，希望可以增加 配置不同的端口配不同的`outbound`
比如说 

> 20171，20172 走默认proxy
> 20173 走游戏

![image](https://user-images.githubusercontent.com/44798713/168613515-81b8cde9-1dd7-4234-8fce-24e3e88c1f2b.png)

又或者已经有这个功能了，我不知道怎么设置，求指教

**Comment by mzz2017** [comment]
@mingzaily 参考 https://v2raya.org/docs/advanced-application/multiple-outbound-routing/#%E7%88%AC%E8%99%AB%E5%88%86%E6%B5%81
