### ISSUE TITLE
win下面成功切换了xray-core，但是依然无法使用XTLS的节点

### ISSUE THREAD

**Issue by Neomanbeta** [v2rayA/v2rayA#541]
### Version, approach of installation, operating system

v2rayA版本1.5.7
xray-core版本1.5.5
github下载的win安装包，安装后手动切换的xray-core，系统是win11

### 问题描述
xray-core的切换已经成功了，在日志里面也显示正常，但是依然无法正常使用，看记录里面显示的信息貌似是因为xtls-rprx-splice这个flow不被支持？这是v2raya造成的么？因为这个xtls-rprx-splice我用v2rayN客户端是可以正常在win下面使用的。

### Logs：
2022/05/17 01:02:00.100 [I] [io.go:428] Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 windows/amd64)
2022/05/17 01:02:00.100 [I] [io.go:428] A unified platform for anti-censorship.
2022/05/17 01:02:00.100 [I] [io.go:428] [Info] infra/conf/serial: Reading config: C:\Program Files\v2rayA/config.json
2022/05/17 01:02:00.150 [I] [io.go:428] Failed to start: main: failed to load config files: [C:\Program Files\v2rayA/config.json] > infra/conf: VLESS users: "xtls-rprx-splice" only support linux in this version
2022/05/17 01:02:00.160 [W] [asm_amd64.s:1571] v2ray-core: exit status 23
2022/05/17 01:02:02.088 [W] [context.go:165] PostConnection: failed to connect: unexpected exiting: check the log for more information
2022/05/17 01:02:02.088 [E] [connection.go:36] failed to connect: failed to connect: unexpected exiting: check the log for more information

**Comment by mzz2017** [comment]
不，这是v2rayN造成的。

**Comment by Neomanbeta** [comment]
那我在win下用v2raya的话，暂时还是没有办法用XTLS了？

**Comment by Neomanbeta** [comment]
好的，我试一下，我之前没在v2raya下面用xtls-rprx-direct的原因是这个如果用在v2rayN下会非常慢，必须改成splice才会有很快的速度，我不知道这个是不是v2rayN的问题。所以在v2raya里面我导入的时候就是xtls-rprx-splice。
