### ISSUE TITLE
请问怎么设置绕过大陆与局域网的规则

### ISSUE THREAD

**Issue by XG520** [v2rayA/v2rayA#543]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.5.7

2. What approach of installation do you install V2rayA?
rmp

3. What is your operating system?
CentOS Linux release 7.9.2009 (Core)

### Description

如题，请问各位怎么设置能绕过大陆域名与局域网

我访问国内网站，查看日志貌似都是走的代理

### Logs：
2022/05/17 00:05:59.413 [I] [io.go:428] tcp:192.168.0.223:49845 accepted tcp:array615.prod.do.dsp.mp.microsoft.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 00:05:59.414 [I] [io.go:428] 192.168.8.3:47735 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:05:59.414 [I] [io.go:428] 192.168.8.3:37273 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:06:03.052 [I] [io.go:428] 192.168.8.3:46701 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:06:03.052 [I] [io.go:428] 192.168.8.3:55394 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:06:13.187 [I] [io.go:428] 192.168.8.3:38035 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:06:13.188 [I] [io.go:428] 192.168.8.3:57487 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:06:23.341 [I] [io.go:428] 192.168.8.3:47379 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:06:23.341 [I] [io.go:428] 192.168.8.3:50009 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:06:33.496 [I] [io.go:428] 192.168.8.3:59019 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:06:33.496 [I] [io.go:428] 192.168.8.3:39770 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:06:43.637 [I] [io.go:428] 192.168.8.3:58677 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:06:43.637 [I] [io.go:428] 192.168.8.3:59309 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:06:54.259 [I] [io.go:428] 192.168.8.3:52666 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:06:54.259 [I] [io.go:428] 192.168.8.3:46539 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:07:04.973 [I] [io.go:428] 192.168.8.3:37149 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:07:04.973 [I] [io.go:428] 192.168.8.3:48873 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:07:15.529 [I] [io.go:428] 192.168.8.3:55034 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:07:15.530 [I] [io.go:428] 192.168.8.3:50974 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:07:26.084 [I] [io.go:428] 192.168.8.3:44625 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:07:26.084 [I] [io.go:428] 192.168.8.3:41561 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:07:36.915 [I] [io.go:428] 192.168.8.3:51879 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:07:36.915 [I] [io.go:428] 192.168.8.3:60616 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:07:47.339 [I] [io.go:428] 192.168.8.3:51486 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:07:47.339 [I] [io.go:428] 192.168.8.3:52632 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:07:57.713 [I] [io.go:428] 192.168.8.3:36192 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:07:57.713 [I] [io.go:428] 192.168.8.3:51777 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:08:08.306 [I] [io.go:428] 192.168.8.3:34173 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:08:08.306 [I] [io.go:428] 192.168.8.3:41670 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:08:18.863 [I] [io.go:428] 192.168.8.3:43876 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:08:18.863 [I] [io.go:428] 192.168.8.3:57020 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:08:31.274 [I] [io.go:428] 192.168.8.3:43878 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:08:31.274 [I] [io.go:428] 192.168.8.3:38940 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:08:41.848 [I] [io.go:428] 192.168.8.3:36496 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:08:41.848 [I] [io.go:428] 192.168.8.3:50656 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:08:52.068 [I] [io.go:428] 192.168.8.3:48005 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:08:52.068 [I] [io.go:428] 192.168.8.3:47010 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:09:02.277 [I] [io.go:428] 192.168.8.3:55157 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:09:02.277 [I] [io.go:428] 192.168.8.3:58394 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:09:12.479 [I] [io.go:428] 192.168.8.3:52344 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 00:09:12.479 [I] [io.go:428] 192.168.8.3:59871 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:08.675 [I] [io.go:428] 192.168.8.3:38051 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:08.675 [I] [io.go:428] 192.168.8.3:41403 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:08.676 [I] [io.go:428] 192.168.0.189:53224 accepted //8.142.9.165:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:08.676 [I] [io.go:428] 192.168.0.189:53225 accepted //8.142.11.190:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:08.677 [I] [io.go:428] 192.168.8.3:37823 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:08.677 [I] [io.go:428] 192.168.8.3:40610 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:08.709 [I] [io.go:428] 192.168.0.189:53227 accepted //mbd.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:08.709 [I] [io.go:428] 192.168.0.189:53228 accepted //mbdp01.bdstatic.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:08.709 [I] [io.go:428] 192.168.0.189:53226 accepted //mbd.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:08.710 [I] [io.go:428] 192.168.8.3:50372 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:08.710 [I] [io.go:428] 192.168.8.3:39410 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.072 [I] [io.go:428] 192.168.0.189:53229 accepted //pic.rmb.bdstatic.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.074 [I] [io.go:428] 192.168.8.3:59934 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.074 [I] [io.go:428] 192.168.8.3:54457 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.130 [I] [io.go:428] 192.168.0.189:53230 accepted //ug.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.132 [I] [io.go:428] 192.168.8.3:53833 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.132 [I] [io.go:428] 192.168.8.3:37989 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.195 [I] [io.go:428] 192.168.0.189:53231 accepted //b.bdstatic.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.196 [I] [io.go:428] 192.168.0.189:53232 accepted //ext.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.197 [I] [io.go:428] 192.168.8.3:36478 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.197 [I] [io.go:428] 192.168.8.3:50148 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.206 [I] [io.go:428] 192.168.0.189:53233 accepted //miao.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.207 [I] [io.go:428] 192.168.8.3:60170 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.207 [I] [io.go:428] 192.168.8.3:44746 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.221 [I] [io.go:428] 192.168.0.189:53234 accepted //mbd.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.221 [I] [io.go:428] 192.168.0.189:53235 accepted //ext.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.221 [I] [io.go:428] 192.168.0.189:53236 accepted //mbd.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.222 [I] [io.go:428] 192.168.8.3:43762 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.222 [I] [io.go:428] 192.168.8.3:50610 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.449 [I] [io.go:428] 192.168.0.189:53237 accepted //t12.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.451 [I] [io.go:428] 192.168.0.189:53238 accepted //t10.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.451 [I] [io.go:428] 192.168.0.189:53239 accepted //t11.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.453 [I] [io.go:428] 192.168.8.3:42817 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.453 [I] [io.go:428] 192.168.8.3:35274 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.454 [I] [io.go:428] 192.168.0.189:53240 accepted //t10.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.456 [I] [io.go:428] 192.168.0.189:53242 accepted //mbd.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.456 [I] [io.go:428] 192.168.0.189:53241 accepted //mbd.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.456 [I] [io.go:428] 192.168.8.3:51143 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.456 [I] [io.go:428] 192.168.8.3:39190 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.458 [I] [io.go:428] 192.168.8.3:34000 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.458 [I] [io.go:428] 192.168.8.3:53066 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.590 [I] [io.go:428] 192.168.0.189:53243 accepted //ug.baidu.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.592 [I] [io.go:428] 192.168.8.3:60320 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.592 [I] [io.go:428] 192.168.8.3:37430 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.971 [I] [io.go:428] 192.168.0.189:53244 accepted //himg.bdimg.com:443 [『🇭🇰 Hong Kong 02』]
2022/05/17 11:17:09.973 [I] [io.go:428] 192.168.8.3:59642 accepted udp:223.6.6.6:53 [dns-out]
2022/05/17 11:17:09.973 [I] [io.go:428] 192.168.8.3:41838 accepted udp:223.6.6.6:53 [dns-out]

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

![1](https://user-images.githubusercontent.com/83686186/168722087-9b57d90c-ce80-4ac7-ac67-d7b04381587c.jpg)
![2](https://user-images.githubusercontent.com/83686186/168722109-47acee77-ebb1-4ecf-9fcb-fbda10c49d41.jpg)

**Comment by mingzaily** [comment]
你是用网关还是代理的方法，
透明代理/系统代理那一栏配置的应该是用网关的方法
20171端口经过实践，应该是全局代理
20172端口才是配置的GFWList或者白名单

**Comment by XG520** [comment]
> 你是用网关还是代理的， 透明代理/系统代理那一栏的方法应该是网关使用方法20171的网关 代理 20172的GFW列表或者白名单配置

我使用的是20171的端口代理，之前我设置20172使用scp总是被服务器断开连接，使用20171可以通过设置
routingA来设置规则吗？

**Comment by XG520** [comment]
> 你是用网关还是代理的方法， 透明代理/系统代理那一栏配置的应该是用网关的方法 20171端口经过实践，应该是全局代理 20172端口才是配置的GFWList或者白名单

如果可以通过设置routeingA设置规则，请问该怎么设置？下面是我设置的routeingA, 可是baidu还是会走代理。 求指教

outbound: unblockneteasemusic = http(address:"127.0.0.1", port:"18080")

default: proxy

# The next line is for android devices, remove it if you don't use android because it may affects the song-listening record.
domain(regexp:clientlog\d*.music.163.com)->block
domain(domain:163.com,domain:netease.com) && source(172.16.0.0/12)->direct
domain(domain:163.com,domain:netease.com)->unblockneteasemusic

domain(geosite:geolocation-!cn)->proxy
domain(geosite:google-scholar)->proxy
domain(geosite:cn, geosite:category-scholar-!cn, geosite:category-scholar-cn)->direct
ip(geoip:hk,geoip:mo)->proxy
ip(geoip:private, geoip:cn)->direct


# 域名规则
domain(regexp: \.baidu.*\.com$) -> direct
domain(geosite:category-ads) -> block
domain(geosite:cn)->direct
domain(contains: baidu,contains: youku) -> direct

# 目的IP规则
ip(8.8.8.8) -> direct
ip(101.97.0.0/16) -> direct
ip(geoip:private) -> direct

# source IP rule
# 源IP规则
source(192.168.0.0/24) -> direct
source(192.168.0.0/16) -> direct
source(172.16.0.0/16) -> direct

**Comment by mingzaily** [comment]
应该可以吧？我没有配置过routingA，我发现20171上全局以后，一直用的都是20172，没出现断开连接过，你也可以试一下静态IP+配置v2rayA网关的方法

**Comment by XG520** [comment]
> ->proxy
> ip(geoip:private, geoip:cn)->direct

好的，感谢

**Comment by XG520** [comment]
> 应该可以吧？我没有配置过routingA，我发现20171上全局以后，一直用的都是20172，没出现断开连接过，你也可以试一下静态IP+配置v2rayA网关的方法

好的，我试试，感谢
