### ISSUE TITLE
GFWList获取失败，code: 429

### ISSUE THREAD

**Issue by XSdark** [v2rayA/v2rayA#544]
v2rayA 1.5.7

![Screenshot_20220518_105010](https://user-images.githubusercontent.com/78119366/168947761-c29a6b7e-24b7-4d4c-8a75-fc83403c3959.png)
![Screenshot_20220518_105042](https://user-images.githubusercontent.com/78119366/168947775-6e7671e7-7899-4375-9053-9937a6bb7f79.png)

**Comment by malikshi** [comment]
+1

**Comment by XSdark** [comment]
目前已恢复正常。
