### ISSUE TITLE
trojan+ws not working

### ISSUE THREAD

**Issue by lotusproxy** [v2rayA/v2rayA#548]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
```
1.5.7-stable/v2fly

server:Xray with trojan+ws
```
2. What approach of installation do you install V2rayA?
```
From github release, with v2fly core in the same directory
```
4. What is your operating system?
```
Manjaro Linux testing branch
```
### Description
```
When using trojan(ws), the websocket connection was force closed
```
### Steps to reproduce
```
1. Create a trojan profile with websocket obfs

2. choose a node and click on url test
```
```
more

cat /etc/v2raya/config.json -> and you will find out that there're no ws settings in it
``` 

### More&log

It seems strange that v2raya handle the websocket for v2core but it was closed 

```
[tcp] relay error: readfrom tcp 127.0.0.1:45829->127.0.0.1:34608: websocket: close 1000 (normal)
```

### Possible approach
```
Let v2core handle websocket traffic
```

**Comment by mzz2017** [comment]
@lotusproxy Can you look up error messages from the server side?

**Comment by lotusproxy** [comment]
Here it is
```
ip:0 rejected  proxy/trojan: not trojan protocol
proxy/trojan: firstLen = 4
app/proxyman/inbound: connection ends > proxy/trojan: invalid protocol or invalid user
```

**Comment by lotusproxy** [comment]
Have you tried to put caddy before the xray core?Btw which core, and which version are you using for v2raya?

**Comment by mzz2017** [comment]
I use v2ray-core v4.44.0 and v2rayA 1.5.7 on the client side. And the protocols are trojan+ws instead of trojan+ss+ws.

**Comment by mzz2017** [comment]
@lotusproxy Your configuration shows you are using trojan-cleartext + ws instead of trojan + tls + ws. v2rayA does not support this.
