### ISSUE TITLE
安装core失败

### ISSUE THREAD

**Issue by song-git** [v2rayA/v2rayA#551]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
官方 https://apt.v2raya.mzz.pub/ 中的包

2. 你通过什么方式安装v2rayA
v2rayA官网推荐的安装方式

3. 你所使用的操作系统
ubuntu20.04

### 描述问题：

在使用v2rayA提供的go.sh脚本安装v2ray core时，一直报 info: No new version. The current version of V2Ray is  .
查看了一下运行过程，好像是卡在获取版本信息那一步了， 脚本中提供的URL https://hubmirror.v2raya.org/api/v2fly/v2ray-core/releases/latest 应该是无效了。

### v2rayA运行日志（Optional）：

... (此处省略X行)
+ TMP_FILE=/tmp/tmp.oInoKEUAdz
+ curl -x '' -sS -H 'Accept: application/vnd.github.v3+json' -o /tmp/tmp.oInoKEUAdz https://hubmirror.v2raya.org/api/v2fly/v2ray-core/releases/latest
++ type -P curl
+ /usr/bin/curl -L -q --retry 5 --retry-delay 10 --retry-max-time 60 -x '' -sS -H 'Accept: application/vnd.github.v3+json' -o /tmp/tmp.oInoKEUAdz https://hubmirror.v2raya.org/api/v2fly/v2ray-core/releases/latest
++ sed 'y/,/\n/' /tmp/tmp.oInoKEUAdz
++ grep tag_name
++ awk -F '"' '{print $4}'
+ RELEASE_LATEST=
+ rm /tmp/tmp.oInoKEUAdz
+ RELEASE_VERSION=v
+ [[ v != '' ]]
+ RELEASE_VERSIONSION_NUMBER=
+ RELEASE_MAJOR_VERSION_NUMBER=
++ echo ''
++ awk -F . '{print $2}'
+ RELEASE_MINOR_VERSION_NUMBER=
+ RELEASE_MINIMUM_VERSION_NUMBER=
++ echo ''
++ sed 's/-.*//'
+ CURRENT_VERSIONSION_NUMBER=
+ CURRENT_MAJOR_VERSION_NUMBER=
++ echo ''
++ awk -F . '{print $2}'
+ CURRENT_MINOR_VERSION_NUMBER=
+ CURRENT_MINIMUM_VERSION_NUMBER=
+ [[ '' -gt '' ]]
+ [[ '' -eq '' ]]
+ [[ '' -gt '' ]]
+ [[ '' -eq '' ]]
+ [[ '' -gt '' ]]
+ return 1
+ NUMBER=1
+ [[ 1 -eq 0 ]]
+ [[ '' -eq 1 ]]
+ [[ 1 -eq 2 ]]
+ [[ 1 -eq 1 ]]
+ echo 'info: No new version. The current version of V2Ray is  .'
info: No new version. The current version of V2Ray is  .
+ exit 0

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya
 ```
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@song-git 已修复

**Comment by song-git** [comment]
> @song-git 已修复

试了一下，确实好了， 非常感谢。
