### ISSUE TITLE
add support shadowsocks-2022

### ISSUE THREAD

**Issue by malikshi** [v2rayA/v2rayA#554]
### Is the feature related with existing problem?

as title, current pre-release xray-core support shadowsocks 2022

### Content of the feature

 here the example 
 https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-2022

**Comment by MarksonHon** [comment]
v2rayA is just a GUI on top of v2ray core. If you want new features about a network protocol, you should go to v2fly/v2ray-core for help.

**Comment by sjtuross** [comment]
I use xray-core. If v2rayA GUI can get the method list updated, then issue resolved.

![image](https://user-images.githubusercontent.com/940110/197386829-6654e9c8-cd72-4391-9ad8-25e385463cff.png)

**Comment by SamLukeYes** [comment]
Shadowsocks 2022 client support is already in v2ray core. https://github.com/v2fly/v2ray-core/pull/2767
