### ISSUE TITLE
自动更新订阅后，自动连接服务器

### ISSUE THREAD

**Issue by libook** [v2rayA/v2rayA#555]
### 您想提出的功能特性是否和现有问题相关？

开启了定时更新订阅的功能后，每隔一段时间发现服务处于“就绪”也就是未连接服务器的状态，可能是在更新订阅之后，服务器列表发生了变化，而V2rayA未重新选择服务器连接。
不知我的猜测是否与V2rayA目前的设计一致。更新订阅，选择自动更新，预期一定是在更新后自动连接新的服务器，如果V2rayA自动离线需要手动连接服务器，那么“自动”更新订阅的意义可能不大了。

### 功能特性内容

如果V2rayA目前没有自动连接服务器的功能，请考虑是否添加相应功能，策略可以是先尝试自动连接相同序号位上的服务器，若相同序号位上没有服务器，就默认连接第一个。

比如我设定了连接订阅的服务器列表的第4个服务器，当自动更新订阅导致服务器列表变化后，V2rayA自动检查订阅服务器列表的第4号位置是否有服务器，有的话自动连接这个服务器，没有的话看第1号位置是否有服务器，有的话自动连接，没有的话保持未连接状态。

**Comment by darcyg** [comment]
我也需要这个功能。
能否选择仅锁定节点名？现在DNS污染很严重。最近连续1-2天，DNS就重新污染一次
现在的节点选择的逻辑，似乎是直接绑定的域名，所以域名和子域名一旦没用，更新订阅后。特别是订阅中节点的DNS变化之后。
原来所选的主机节点会放在列表最后。而新节点DNS不会被选择。导致服务不能用。
如果仅仅是锁定节点名，订阅后节点dns变化，节点名称不变，就不会有问题了。至少不会出现几天变一次的囧境

谢谢

**Comment by mzz2017** [comment]
@darcyg 这种需求和v系软件不太迎合，比方说在切换节点时会造成网络中断体验不佳，一般推荐使用clash系软件

**Comment by MarksonHon** [comment]
Clash 拥有更好的节点订阅兼容性，建议使用 Clash Meta 分支：
<https://docs.metacubex.one/>

**Comment by libook** [comment]
@mzz2017 或者更新订阅后保留正在连接的服务器，用户有需要可以手动切换到新的服务器。

**Comment by mzz2017** [comment]
@libook 目前行为就是保留

**Comment by jiqing112** [comment]
> @darcyg 这种需求和v系软件不太迎合，比方说在切换节点时会造成网络中断体验不佳，一般推荐使用clash系软件

不切换新的节点会一直断网。更新订阅后自动连接或许会无感知。
