### ISSUE TITLE
Installation failed on FreeBSD 13.1

### ISSUE THREAD

**Issue by chianjin** [v2rayA/v2rayA#556]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
installer_freebsd_amd64_1.5.7.txz

2. What approach of installation do you install V2rayA?
pkg install ./installer_freebsd_amd64_1.5.7.txz

3. What is your operating system?
FreeBSD xxx.xxx.net 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64

### Description
`pkg: Error parsing manifest: error while parsing <unknown>: line: 1, column: 1301 - 'empty keys are not allowed', character: '"'`
`pkg: /usr/home/chian/installer_freebsd_amd64_1.5.7.txz is not a valid package: Invalid manifest`

**Comment by MarksonHon** [comment]
Sorry, but the FreeBSD package for v2rayA is fake and we don't currently support FreeBSD

**Comment by glyh** [comment]
Please remove the package in case of further confusion.
