### ISSUE TITLE
启动v2rayA时遇到问题

### ISSUE THREAD

**Issue by DSLZL** [v2rayA/v2rayA#563]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
installer_debian_amd64_1.5.7.deb提供的版本
2. 你通过什么方式安装v2rayA
使用dpkg命令安装
3. 你所使用的操作系统
WSL2中的Ubuntu22.04 LTS

### 描述问题：

在根据 https://v2raya.org/docs/prologue/installation/debian/#启动-v2raya--设置-v2raya-自动启动 提供的教程
使用sudo systemctl start v2raya.service命令时
遇到System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Comment by mzz2017** [comment]
@DSLZL wsl2不支持systemctl，再开个终端使用 sudo v2raya 启动
