### ISSUE TITLE
无法在时间未同步的情况下启动VLESS协议服务器

### ISSUE THREAD

**Issue by shenzhui007** [v2rayA/v2rayA#564]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.7
2. 你通过什么方式安装v2rayA
apt
3. 你所使用的操作系统
Linux Debian

### 描述问题
一、Server 的协议（仅）配置了VLESS协议，
二、在时间未同步的情况下，客户端上无法启动v2ray core，但是VLESS 是个不依赖于系统时间的协议，时间不一致的情况下应该也能用的。
三、在时间同步后，由于v2ray-core未启动，需要手动重启v2raya服务才能连接

### 复现问题的步骤
配置VLESS服务器后，在客户端时间未同步的情况下，启动v2raya服务。

### v2rayA/v2ray运行日志：
2022/06/07 13:48:21.819  [A] [main.go:25]  waiting for the network connected
2022/06/07 13:48:28.050  [A] [main.go:25]  network is connected
2022/06/07 13:48:28.097  [A] [main.go:27]  V2Ray binary is /usr/local/bin/v2ray
2022/06/07 13:48:28.097  [A] [main.go:27]  V2Ray asset directory is /run/user/0/v2raya
2022/06/07 13:48:28.097  [A] [main.go:27]  v2rayA working directory is /
2022/06/07 13:48:28.097  [A] [main.go:27]  v2rayA configuration directory is /etc/v2raya
2022/06/07 13:48:28.097  [A] [main.go:27]  Golang: go1.18
2022/06/07 13:48:28.097  [A] [main.go:27]  OS: linux
2022/06/07 13:48:28.097  [A] [main.go:27]  Arch: amd64
2022/06/07 13:48:28.097  [A] [main.go:27]  Lite: false
2022/06/07 13:48:28.097  [A] [main.go:27]  Version: 1.5.7
2022/06/07 13:48:28.097  [A] [main.go:27]  Starting...
2022/06/07 13:48:28.355  [E] [main.go:28]  failed to start v2ray-core: Please sync datetime first. Your datetime is 2022/06/07 13:48, and the correct datetime is 2022/06/07 05:48
2022/06/07 13:48:28.361  [A] [index.go:117]  v2rayA is listening at http://127.0.0.1:2017
2022/06/07 13:48:28.361  [A] [index.go:117]  v2rayA is listening at http://192.168.0.112:2017
2022/06/07 13:48:28.361  [A] [index.go:117]  v2rayA is listening at http://172.17.0.1:2017
2022/06/07 13:48:28.361  [A] [index.go:117]  v2rayA is listening at http://[::1]:2017
2022/06/07 13:48:28.361  [A] [index.go:117]  v2rayA is listening at http://[fe80::e71f:c246:4aa1:9091]:2017
2022/06/07 05:51:40.495  [I] [io.go:428]  V2Ray 4.45.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.1 linux/amd64)
2022/06/07 05:51:40.495  [I] [io.go:428]  A unified platform for anti-censorship.
2022/06/07 05:51:40.496  [I] [io.go:428]  [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/06/07 05:51:42.301  [I] [io.go:428]  127.0.0.1:37770 accepted tcp:127.0.0.1:0 [api-out]

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@shenzhui007 https://github.com/v2rayA/v2rayA/actions/runs/2451556312
