### ISSUE TITLE
日志显示问题,windows 里面显示的是域名,Linux 显示的是ip

### ISSUE THREAD

**Issue by aeeq** [v2rayA/v2rayA#565]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.7

3. 你通过什么方式安装v2rayA
manjaro linux 原生
window  exe
4. 你所使用的操作系统
manjaro
window

### 描述问题：

日志显示问题,windows 里面显示的是域名,Linux 显示的是ip 
可不可以Linux 也显示域名
域名比较直观

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```
Linux 里面的
2022/06/07 00:00:00.457 [I] [io.go:428] 192.168.2.19:36094 accepted tcp:8.8.4.4:853 [direct]
2022/06/07 00:00:00.683 [I] [io.go:428] 192.168.2.19:36100 accepted tcp:8.8.4.4:853 [direct]
2022/06/07 00:00:00.685 [I] [io.go:428] 192.168.2.6:51924 accepted tcp:173.194.167.168:443 [『3.10』]
2022/06/07 00:00:00.923 [I] [io.go:428] 192.168.2.19:36104 accepted tcp:8.8.4.4:853 [direct]
2022/06/07 00:00:02.574 [I] [io.go:428] 192.168.2.19:36110 accepted tcp:8.8.4.4:853 [direct]
2022/06/07 00:00:02.658 [I] [io.go:428] 192.168.2.6:51925 accepted tcp:172.217.160.86:443 [『3.10』]
2022/06/07 00:00:02.794 [I] [io.go:428] 192.168.2.19:36114 accepted tcp:8.8.4.4:853 [direct]

```shell
window 里面的


2022/06/07 11:44:03.792 [I] [io.go:428] 127.0.0.1:23531 accepted //www.baidu.com:443 [direct]
2022/06/07 11:44:03.966 [I] [io.go:428] 127.0.0.1:23534 accepted //sp1.baidu.com:443 [direct]
2022/06/07 11:44:04.204 [I] [io.go:428] 127.0.0.1:23538 accepted //ug.baidu.com:443 [direct]
2022/06/07 11:44:04.320 [I] [io.go:428] 127.0.0.1:23540 accepted //ug.baidu.com:443 [direct]
2022/06/07 11:44:06.366 [I] [io.go:428] 127.0.0.1:23543 accepted //sp3.baidu.com:443 [direct]
2022/06/07 11:44:08.417 [I] [io.go:428] 127.0.0.1:23546 accepted //ss0.baidu.com:443 [direct]
2022/06/07 11:44:08.419 [I] [io.go:428] 127.0.0.1:23548 accepted //ss1.baidu.com:443 [direct]
2022/06/07 11:44:08.426 [I] [io.go:428] 127.0.0.1:23550 accepted //ss2.baidu.com:443 [direct]
2022/06/07 11:44:08.426 [I] [io.go:428] 127.0.0.1:23551 accepted //ss3.baidu.com:443 [direct]
2022/06/07 11:44:09.787 [I] [io.go:428] 127.0.0.1:23555 accepted //t7.baidu.com:443 [direct] 

```

### v2rayA设置以及相关截图
Linux 的设置
![图片](https://user-images.githubusercontent.com/8926331/172318815-632d2f70-387e-4a2d-b4a9-5f445d8eaddb.png)

windows的设置
![图片](https://user-images.githubusercontent.com/8926331/172318937-13f21dbf-aac9-4460-99b4-75339e98ce53.png)

**Comment by cubercsl** [comment]
linux 使用的是透明代理，并非设置系统代理为 http 代理，实现方式不同。透明代理无法显示域名。

**Comment by mzz2017** [comment]
@aeeq linux透明代理显示的是sniffing前的目标地址，属于网络层转发，windows系统代理走socks5和http，会描述域名

**Comment by aeeq** [comment]
好的
