### ISSUE TITLE
使用nginx+密码认证之后反代v2raya管理面板一直弹出输入用户名和密码

### ISSUE THREAD

**Issue by wutongskype** [v2rayA/v2rayA#567]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA  【1.5.7】

2. 你通过什么方式安装v2rayA 【手动下载deb安装】

3. 你所使用的操作系统【debian 11】

### 描述问题：

使用nginx加上账户密码认证之后反代v2raya那个管理面板，一直弹出输入用户名和密码。
![image](https://user-images.githubusercontent.com/40192806/172789654-e3d8725c-58c1-481f-ab94-43194af94711.png)
一直弹出这个输入用户名密码的页面。
nginx设置
![image](https://user-images.githubusercontent.com/40192806/172789806-e111d35d-4697-42a3-bf59-e44c8a6beb0d.png)

去掉密码认证后正常

翻了几十页iss没找到类似问题。。。

**Comment by MarksonHon** [comment]
看你在群里搞定了，我就先关掉了
