### ISSUE TITLE
vps Ubuntu已经同步了时间，六七十个节点只有一两个能用是为什么？

### ISSUE THREAD

**Issue by cascklhljhn** [v2rayA/v2rayA#568]
vps Ubuntu已经同步了时间，六七十个节点只有一两个能用是为什么，我几乎找不到能用的节点。请求各位大佬救命。
报错日志如下：
2022/06/13 12:22:53.989 [I] [io.go:428]  [Warning] [4145433786] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 36.134.168.174:30053: operation was canceled dial tcp: lookup node-1109.yh82l3dsytxzf8.xyz: operation was canceled] > common/retry: all retry attempts failed
2022/06/13 12:22:53.990 [I] [io.go:428]  [Warning] [1333798258] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 36.134.168.174:30060: operation was canceled dial tcp: lookup node-1112.yh82l3dsytxzf8.xyz: operation was canceled] > common/retry: all retry attempts failed
2022/06/13 12:22:53.990 [I] [io.go:428]  [Warning] [3378231050] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 36.137.226.151:30059: operation was canceled dial tcp: lookup node-1111.yh82l3dsytxzf8.xyz: operation was canceled] > common/retry: all retry attempts failed
2022/06/13 12:23:01.989 [I] [io.go:428]  [Warning] [4286771823] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 120.232.208.199:22004: operation was canceled dial tcp: lookup node-2104.yh82l3dsytxzf8.xyz: operation was canceled] > common/retry: all retry attempts failed
2022/06/13 12:23:01.989 [I] [io.go:428]  [Warning] [3731567306] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 36.137.226.151:22003: operation was canceled dial tcp: lookup node-2103.yh82l3dsytxzf8.xyz: operation was canceled] > common/retry: all retry attempts failed
2022/06/13 12:23:01.989 [I] [io.go:428]  [Warning] [3333626367] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 36.137.226.151:22002: operation was canceled dial tcp: lookup node-2102.yh82l3dsytxzf8.xyz: operation was canceled] > common/retry: all retry attempts failed
2022/06/13 12:23:01.989 [I] [io.go:428]  [Warning] [2458634577] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 36.134.168.174:22001: operation was canceled dial tcp: lookup node-2101.yh82l3dsytxzf8.xyz: operation was canceled] > common/retry: all retry attempts failed

**Comment by mzz2017** [comment]
@cascklhljhn 可能是服务器使用的vmess版本过老，使用老版本的v2raya例如1.5.5试试

**Comment by cascklhljhn** [comment]
一开始的是v2raya_linux_x86_1.5.7，换成了v2raya_linux_x86_1.5.5依然存在该问题，是否是v2ray服务不对？在Windows下的v2ray客户端都能使用这些节点。

**Comment by cascklhljhn** [comment]
这是我的系统版本：Linux racknerd-2d9d3a 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mzz2017** [comment]
@cascklhljhn windows能用是什么时候试的？

**Comment by cascklhljhn** [comment]
一直都能使用，用的V2rayN客户端，不是这个项目的软件。

**Comment by MarksonHon** [comment]
自己检查一下 AlterID 与 AEAD 加密的问题吧，有需要可以进群。
<https://t.me/v2raya_zh>
