### ISSUE TITLE
GFWList模式下无法使用telegram

### ISSUE THREAD

**Issue by fireflyoo** [v2rayA/v2rayA#569]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.7-1
2. 你通过什么方式安装v2rayA
opkg install v2raya
3. 你所使用的操作系统
openwrt 22.03.0-rc4

### 描述问题：

GFWList模式下telegram无法穿墙，而浏览器可正常穿墙。
大陆白名单模式下均正常。

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![图片](https://user-images.githubusercontent.com/3056566/173387078-3e5787e5-16ff-4bfd-b6e8-4d6edfba1280.png)

**Comment by FeyXieXzf** [comment]
telegram要穿墙必须在tg内的设置里自行启用代理，就算v2raya设置的是全局/系统代理也必须自行设置

**Comment by Gaojianli** [comment]
please read the doc plz
https://v2raya.org/docs/manual/routinga/

**Comment by fireflyoo** [comment]
@Gaojianli 谢谢，用了你提供的规则配置，现在已经可以正常连接了
