### ISSUE TITLE
windows can't import the share link of V2RayA in certain situations.

### ISSUE THREAD

**Issue by suhuaixing** [v2rayA/v2rayA#57]
### Version, approach of installation, operating system

1. What version of V2RayA are you using?
0.6.8.1
2. What approach of installation do you install V2rayA?
apt
3. What is your operating system and CPU architecture?
kubuntu
amd64
### Description

if the share link contain "/"
then windows client "ShadowsocksR" couldn't import such url
(loss all data after "/")
I've tested Linux(V2RayA), Android (ShadowsocksR).
I guess this is due to Windows client use a different base64 mechanism

I tried to share the url from Android (ShadowsocksR) with the same node setting. It doesn't produce a url with "/", so I can import this url on Windows.

### Steps to reproduce

I could't share my url since it includes some sensitive data. Could you find a url like this:

ssr://hfYWVzMTI4X21kNTpjaGFjaGEyMDp0bHMxLjJfdGlja2V0X2F1dGg6YldKc1lXNXJNWEJ2Y25RPS8******/****cmVtYXJrcz1XMFJkTFVoTExVaExWQzB3TVE9PSZwcm90b3BhcmFtPU16RTNOakU2YUhWaGFYaHBibWN4T1RrMU1UQXlOUT09Jm9iZnNwYXJhbT1ZWEJ3YkdSdWJHUXVZWEJ3YkdVdVkyOXQ=****

notices the "/"

Since base64 has many varieties, I think V2RayA adopts one which ShadowsocksR on Windows couldn't import. I know Windows is a garbage, this issue is really ackward. 

Thanks!

**Comment by mzz2017** [comment]
0.6.8.2已发布

**Comment by mzz2017** [comment]
I closed the issue due to no response for a long time. Feel free to reopen it if there is some progress. Thank you!
