### ISSUE TITLE
阿里云搭建v2raya提供公网连接，阿里云所连服务器ip被污染

### ISSUE THREAD

**Issue by imbennie** [v2rayA/v2rayA#572]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
Version: 1.5.8.1
V2Ray 4.45.2

> 2022/06/21 15:52:15.330 [A] [main.go:27]  V2Ray binary is /usr/bin/v2ray
2022/06/21 15:52:15.330 [A] [main.go:27]  V2Ray asset directory is /run/user/0/v2raya
2022/06/21 15:52:15.330 [A] [main.go:27]  v2rayA working directory is /root
2022/06/21 15:52:15.330 [A] [main.go:27]  v2rayA configuration directory is /etc/v2raya
2022/06/21 15:52:15.330 [A] [main.go:27]  Golang: go1.18.3
2022/06/21 15:52:15.330 [A] [main.go:27]  OS: linux
2022/06/21 15:52:15.330 [A] [main.go:27]  Arch: amd64
2022/06/21 15:52:15.330 [A] [main.go:27]  Lite: false
2022/06/21 15:52:15.330 [A] [main.go:27]  Version: 1.5.8.1
2022/06/21 15:52:15.330 [A] [main.go:27]  Starting...
2022/06/21 15:52:16.136 [I] [process.go:67]  low memory: 1178MiB, set V2RAY_CONF_GEOLOADER=memconservative
2022/06/21 15:52:16.144 [I] [io.go:428]  V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/amd64)

3. 你通过什么方式安装v2rayA
Docker

4. 你所使用的操作系统
Ubuntu 20.04.4 LTS

### 描述问题：
在VPS上通过docker部署，通过设置界面开启“开启端口分享“后。
我希望通过任意电脑能够连接到这个代理服务器。
实际情况上，请求能够到达v2raya，但是无法获得正常响应。

Chrome的显示为：

<img width="689" alt="image" src="https://user-images.githubusercontent.com/31159377/174851375-2a153d4f-e798-48f5-a55e-12dcb8ac5389.png">

排查：
1、端口监听

❯ lsof -i tcp:8889
COMMAND     PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
v2ray   3048755 root   11u  IPv6 11456272      0t0  TCP *:8889 (LISTEN)
❯
❯ lsof -i tcp:1089
COMMAND     PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
v2ray   3048755 root    9u  IPv6 11456270      0t0  TCP *:1089 (LISTEN)

2、nc
❯ nc -zv alivps 1089
Connection to alivps port 1089 [tcp/ff-annunc] succeeded!
❯

❯ nc -zv alivps 8889
Connection to alivps port 8889 [tcp/ddi-tcp-2] succeeded!

3、代理服务器本身问题已确定可以排除。

### v2rayA运行日志（Optional）：

日志显示说明请求已被v2raya接受。

```shell
2022/06/21 16:09:13.099 [I] [io.go:428]  114.*.*.*:32442 accepted //www.google.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:09:13.318 [I] [io.go:428]  114.*.*.*:32443 accepted //www.google.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:09:13.484 [I] [io.go:428]  114.*.*.*:32444 accepted //beacons.gcp.gvt2.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:09:34.464 [I] [io.go:428]  114.*.*.*:32577 accepted //www.google.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:10:00.150 [I] [io.go:428]  114.*.*.*:32669 accepted //optimizationguide-pa.googleapis.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:10:34.576 [I] [io.go:428]  114.*.*.*:32898 accepted //www.google.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:10:47.945 [W] [proxy.go:29]  [ssr] dial to sg1.xxxxxx.top:14198 error: dial tcp :0->127.0.0.1:14198: connect: connection refused
2022/06/21 16:10:57.954 [W] [proxy.go:29]  [ssr] dial to sg2.xxxxxx.top:14198 error: dial tcp :0->127.0.0.1:14198: connect: connection refused
2022/06/21 16:11:18.256 [W] [proxy.go:29]  [ssr] dial to sg3.xxxxxx.top:14198 error: dial tcp :0->127.0.0.1:14198: connect: connection refused
2022/06/21 16:11:39.049 [W] [proxy.go:29]  [ssr] dial to sg4.xxxxxx.top:14198 error: dial tcp :0->127.0.0.1:14198: connect: connection refused
2022/06/21 16:12:03.325 [W] [proxy.go:29]  [ssr] dial to sg5.xxxxxx.top:14198 error: dial tcp :0->127.0.0.1:14198: connect: connection refused
2022/06/21 16:12:23.676 [I] [io.go:428]  114.*.*.*:33306 accepted //clients4.google.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:12:23.815 [I] [io.go:428]  114.*.*.*:33307 accepted //clients4.google.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:12:24.073 [I] [io.go:428]  114.*.*.*:33311 accepted //beacons.gcp.gvt2.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:12:24.313 [I] [io.go:428]  114.*.*.*:33312 accepted //beacons.gcp.gvt2.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:12:24.328 [I] [io.go:428]  114.*.*.*:33313 accepted //beacons.gcp.gvt2.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:13:47.089 [I] [io.go:428]  114.*.*.*:33506 accepted //www.google.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:13:47.089 [I] [io.go:428]  114.*.*.*:33505 accepted //www.gstatic.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:13:47.232 [I] [io.go:428]  114.*.*.*:33507 accepted //beacons.gcp.gvt2.com:443 [『SG-Singapore3(1)』]
2022/06/21 16:13:47.232 [I] [io.go:428]  114.*.*.*:33508 accepted //beacons.gvt2.com:443 [『SG-Singapore3(1)』]
```

### v2rayA设置以及相关截图
<img width="644" alt="image" src="https://user-images.githubusercontent.com/31159377/174848058-7c0a785e-9d55-4604-9e97-76cfe0acd3c4.png">

**Comment by imbennie** [comment]
> @imbennie 你的意思是本机可以，其他机器不可以？

Sorry，我没有描述清楚。
问题是无法通过公网连接，程序是部署在VPS上的，有一个公网IP，我在本地电脑希望通过这个公网ip能够连接到这个代理。

**Comment by imbennie** [comment]
我用curl做了个测试。
cip.cc被配置为proxy时（domain(domain:cip.cc)->proxy），发现连接被拒绝。

观察发现其他需要被proxy的请求也会被拒绝。

```shell
❯ curl -x http://localhost:8889 cip.cc -v

*   Trying ::1:8889...
* TCP_NODELAY set
* Connected to localhost (::1) port 8889 (#0)
> GET http://cip.cc/ HTTP/1.1
> Host: cip.cc
> User-Agent: curl/7.68.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< Connection: close
* HTTP/1.1 proxy connection set close!
< Proxy-Connection: close
< Content-Length: 0
<
* Closing connection 0

```

v2raya日志
```
2022/06/21 16:43:41.212 [I] [io.go:428]  [::1]:35614 accepted http://cip.cc/ [『SG-Singapore』]
2022/06/21 16:43:41.214 [W] [proxy.go:29]  [ssr] dial to sg.***.top:14198 error: dial tcp :0->127.0.0.1:14198: connect: connection refused
```


cip.cc若路由为direct，则能正常得到响应。（domain(domain:cip.cc)->direct）
```shell
❯ curl -x http://localhost:8889 cip.cc -v
*   Trying ::1:8889...
* TCP_NODELAY set
* Connected to localhost (::1) port 8889 (#0)
> GET http://cip.cc/ HTTP/1.1
> Host: cip.cc
> User-Agent: curl/7.68.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Connection: close
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
< Date: Tue, 21 Jun 2022 16:47:27 GMT
< Server: openresty
< Vary: Accept-Encoding
< X-Cip-C: M
<
IP	: 8.22.*.*
地址	: 中国  中国

数据二	: 香港 | **

数据三	: 中国香港 | **

URL	: http://www.cip.cc/8.22.*.*
* Closing connection 0
```

**Comment by mzz2017** [comment]
@imbennie 你的日志表明 sg**top 可能存在 dns 污染

**Comment by mzz2017** [comment]
@imbennie 另外，是否能ping通你这个海外节点的ip？

**Comment by imbennie** [comment]
> @imbennie 另外，是否能ping通你这个海外节点的ip？

dns污染的情况应该不存在。
1. 我的vps在海外。
2. 代理服务器，我常年使用，并无异常情况。

可以ping通，both大陆网络和海外网络。

**Comment by imbennie** [comment]
> @imbennie 另外，是否能ping通你这个海外节点的ip？

确实是机器的问题，ping和的dig的结果都应答为127回环地址。

但是我用`dig sg4.***.top @1.1.1.1`，得到结果也是127，这里网络解析不太理解是什么样过程。

VPS是阿里云的，不确定是否做了操作。
由于网络方面的知识比较浅薄，我暂时还不能确定是哪里的问题。
大佬这边有没有建议指导下，我应该了解哪些知识以继续排查？

**Comment by mzz2017** [comment]
@imbennie 先确定是阿里云的污染还是解析确实是这个，在国外服务器dig一下看结果来验证。如果是阿里云的污染，换一个无污染的公共dns服务器或者使用dns over tls/https等技术规避污染，或者v2raya设置里dns防污染随便选一个之后特殊模式打开supervisor

**Comment by imbennie** [comment]
@mzz2017 
代理服务器的域名本身是不存在污染的，我在本地机器和另一台大陆的vps做了dig验证，都可以正常解析。因此可以确定问题出在这台机器的系统上或者阿里云的网络上，可能因为某些特殊设置导致。

我尝试过修改机器的dns解析配置为支持doh类的dns（1.1.1.1），解析结果显示是127地址。

同样的，如同上面的说明我直接用` dig sg4.***.top @1.1.1.1 `得到结果同样也是127 
这一点就很费解。

**Comment by MarksonHon** [comment]
长时间未回复，issue关闭。
有需要可以进群： 
<https://t.me/v2raya_zh>
