### ISSUE TITLE
群晖部署出现证书问题

### ISSUE THREAD

**Issue by HAVEANAMEISDIFFICULT** [v2rayA/v2rayA#573]
出现这个提示
failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": x509: certificate signed by unknown authority

**Comment by mzz2017** [comment]
@HAVEANAMEISDIFFICULT apt update && apt install ca-certificates

**Comment by mzz2017** [comment]
群晖的话对应是不是这个包我就不知道了

**Comment by HAVEANAMEISDIFFICULT** [comment]
群晖用不了apt怎么办

**Comment by HAVEANAMEISDIFFICULT** [comment]
我去注册一个ssl证书安装上有没有用啊

**Comment by HAVEANAMEISDIFFICULT** [comment]
解决了，这个挂载了/etc就会不正常，删掉就好了

**Comment by huanghe2015** [comment]
这条应该写在帮助文档里
