### ISSUE TITLE
sudo v2raya  的 web登陆密码  不能用在 v2raya  --lite , 为什么密码是不统一的？

### ISSUE THREAD

**Issue by rollto** [v2rayA/v2rayA#583]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?

2. What approach of installation do you install V2rayA?

3. What is your operating system?

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```
 You can also paste the log that comes from web administration page

```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by cubercsl** [comment]
普通用户运行的实例无法读取 root 运行的数据。这一点是符合预期的。

**Comment by rollto** [comment]
那我怎么重置普通用户的 密码呢？    v2raya --lite --reset-password    这个命令是不行的.

**Comment by mzz2017** [comment]
@rollto 这是个bug，我先记录一下。你可以通过删除 ~/.config/v2raya/bolt_v4.db 清除数据

**Comment by rollto** [comment]
当用 v2raya --lite 的时候， 设置的 第一个选项 透明代理系统 ,只能选关闭吧？

![透明代理系统代理设置](https://user-images.githubusercontent.com/45850782/176830941-6d07caac-77a8-4357-aaa3-354d17dc97b3.png)


![透明代理系统代理设置2](https://user-images.githubusercontent.com/45850782/176830955-ff497fb2-28f7-409b-b80b-0b06a1cf0cf1.png)

**Comment by cubercsl** [comment]
对于 windows 和 macos 来说，提供了自动配置系统代理的功能。对于 Linux 来说，不使用 root 运行就无法提供透明代理，同时 Linux 的桌面系统代理配置方式各不相同，无法提供统一的自动配置。

**Comment by ruitard** [comment]
重置密码是会设置默认密码吗，我将 `~/.config/v2raya` 删除后，网页界面还是登录界面，不是最开始的创建管理员账号界面。登录也一直是 `wrong username or password`

**Comment by MarksonHon** [comment]
@ruitard 如果以root运行，那么配置在/etc/v2raya
