### ISSUE TITLE
 geosite.dat, geoip.dat or v2ray-core may not be installed correctly

### ISSUE THREAD

**Issue by essoojay** [v2rayA/v2rayA#585]
Openwrt 21.02

V2raya: Git compiled (02/07/2022)

Geoip / Geosite error keep popping up and i couldnt fix, this .. it was easier to fix before now. I expected auto installation but that didnt happen,  Please where is the right path or if am using the wrong files.. please point to the right files.

Sorry if this has been answered before but couldnt find it on here..

Thanks

**Comment by mzz2017** [comment]
You should put your asset files to /usr/local/share/xray or /usr/local/share/v2ray which depends on your core.

**Comment by essoojay** [comment]
> 

I did placed the assets files in there, have /usr/share/v2ray or /usr/share/xray on my openwrt..  This did not solve it, still same error, had to practically disable v2ray (rename) to allow for xray to kick in as the core. There used to be a way to directly set the preferred core, but not anymore?? Am not an expert, i stand to be corrected. And i noticed, Tproxy mode for stopped working, could get only redirect mode.

Please point out what am doing wrong. thanks

**Comment by MarksonHon** [comment]
`which v2ray`
`which xray`
Then see what the output is

**Comment by hiradsajde** [comment]
i have same problem too, 
```
[root@fedora v2ray]# which xray
/usr/local/bin/xray
[root@fedora v2ray]# which v2ray
/usr/local/bin/v2ray
[root@fedora v2ray]# 

```

**Comment by hcym** [comment]
今天也是如此
