### ISSUE TITLE
uncheck option&works slow

### ISSUE THREAD

**Issue by NEO-Reverser** [v2rayA/v2rayA#590]
### Is the feature related with existing problem?

i have almost 2,300 servers that imported. and it works so slow in checking http or check/uncheck the servers
### Content of the feature

- [x] could you add a option that uncheck the checked servers? (It takes about 5 seconds for each server to uncheck)
- [ ] could you optimize speed?

![photo_2022-07-10_10-41-34](https://user-images.githubusercontent.com/33395636/178133636-25e4615e-5fdb-4f11-b5dd-188bb7f6683a.jpg)

**Comment by mzz2017** [comment]
@NEO-Reverser double click the checkbox to the left of title bar to unckeck all

**Comment by NEO-Reverser** [comment]
> @NEO-Reverser double click the checkbox to the left of title bar to unckeck all

I knew. For example, the fastest way is to refresh the page, but it is not good
The speed is really annoying

**Comment by mzz2017** [comment]
@NEO-Reverser Yes, we will consider it.
