### ISSUE TITLE
v1.5.8.1的两个问题，不知算不算bug?

### ISSUE THREAD

**Issue by egg1234** [v2rayA/v2rayA#591]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
v1.5.8.1

2. What approach of installation do you install V2rayA?
下载v4.44.0/v2ray-linux-64.zip及installer_debian_amd64_1.5.8.1.deb进行本地安装

3. What is your operating system?
ESXi上装ubuntu-22.04-live-server-amd64.iso版

### Description

问题一：
在本地另外一台linux服务器使用gost，pingtunnel监听socks5并转发到出口服务器，在firefox及chrome浏览器验证这两个socks5服务器正常工作并能访问https://api.ipify.org及https://clients3.google.com。
然后在v2raya的v1.5.8.1 web设置页面使用SOCKS5 as outbound server这个功能把上面两个socks5服务器设置好。
点画面右上角的设置，里面设置是：
防止DNS污染设置为转发DNS请求，透明代理/系统代理及端口规则的分流模式都是设置为大陆白名单，代理实现方式设置为tproxy（这些设置组合当连接到本地的vmess，ss，http代理服务器都工作得很正常）
选择两个socks5服务器其中之一，然后点画面左上角的启动，再ssh到v2raya本身这台ubuntu机器，打入下面的命令，回应都是curl: (6) Could not resolve host，等于是DNS解析不了
#curl https://api.ipify.org
curl: (6) Could not resolve host: api.ipify.org

#curl https://clients3.google.com
curl: (6) Could not resolve host: clients3.google.com

然后本地的客户端windows7，windows10把网关设置到这台v2raya的v1.5.8.1的IP地址，客户端DNS设置为1.1.1.1也不能联网，但同样这台v2raya的v1.5.8.1的机器改用本地的vmess，ss，http代理服务器都工作得很正常，v2raya本地curl也正常，客户端联网也正常，就是使用SOCKS5 as outbound server这个功能连接本地socks5服务器就不能正常工作

问题二：
v1.5.8.1运行一段时间后，可能是1天，可能是2－3天不定，会出现自己停止了代理的现象，就是进去web设置画面看到左上角的按钮变成就绪了，需要再手动点一下那个按钮启动代理，之前使用v1.5.6.2版及v1.5.7版都没有问题，同样是上面问题一的安装环境

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```

 You can also paste the log that comes from web administration page

```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by mzz2017** [comment]
@egg1234 一个可能性：你的pingtunnel监听的socks5可能不支持udp，v2ray默认认为socks5是支持的，导致把udp流量打上去就会出问题
停止运行问题：可能是core被杀了，看日志

**Comment by egg1234** [comment]
@mzz2017 谢谢你的回复！在你回复前我已经重新装了一台ubuntu-20.04.4-live-server-amd64.iso 服务器，同样是v4.44.0/v2ray-linux-64.zip及installer_debian_amd64_1.5.8.1.deb进行本地安装，v2raya的web页面配置里面的所有设置与上面的一样，
同样使用gost，pingtunnel监听socks5，甚至还使用了hysteria的socks5监听，都创建在v2raya进行测试，发现下面命令都是通的，而且windows7，10都能使用这个v2raya的网关连接上网，而且DNS也随便设都无所谓
#curl https://api.ipify.org
#curl https://clients3.google.com

而且日志也显示这些socks5都能连接到
#tail -n 50 /var/log/v2raya/v2raya.log

[I] [io.go:428]  127.0.0.1:35044 accepted tcp:127.0.0.1:0 [api-out]
[I] [io.go:428]  10.0.0.21:48870 accepted udp:10.0.0.1:53 [dns-out]
[I] [io.go:428]  10.0.0.21:56381 accepted udp:10.0.0.1:53 [dns-out]
[I] [io.go:428]  10.0.0.21:45416 accepted tcp:3.232.242.170:443 [proxy]
[I] [io.go:428]  10.0.0.21:38238 accepted udp:10.0.0.1:53 [dns-out]
[I] [io.go:428]  10.0.0.21:48641 accepted udp:10.0.0.1:53 [dns-out]
[I] [io.go:428]  10.0.0.21:46192 accepted udp:185.125.190.58:123 [proxy]
[I] [io.go:428]  10.0.0.21:52787 accepted udp:10.0.0.1:53 [dns-out]
[I] [io.go:428]  10.0.0.21:60109 accepted udp:10.0.0.1:53 [dns-out]
[I] [io.go:428]  10.0.0.21:35758 accepted tcp:52.20.78.240:443 [proxy]
[I] [io.go:428]  10.0.0.21:58820 accepted udp:10.0.0.1:53 [dns-out]
[I] [io.go:428]  10.0.0.21:36407 accepted udp:10.0.0.1:53 [dns-out]
[I] [io.go:428]  10.0.0.21:36135 accepted udp:10.0.0.1:53 [dns-out]
[I] [io.go:428]  10.0.0.21:35665 accepted udp:10.0.0.1:53 [dns-out]
[I] [io.go:428]  10.0.0.21:33622 accepted tcp:172.217.175.110:443 [proxy]

接下来观察一下ubuntu-20.04.4是否有不定时停止代理的问题，回头再看看是否ubuntu 22.04的问题

**Comment by darcyg** [comment]
我发现1.5.8.1的代理跑一天两天就不正常。代理服务访问不了，偶尔也出现过代理自动停止
我没看docker logs。但是进vm很慢，登录一看是交换分区满了。
vm是2核，2G内存，交换也是2G大小..

不知道是否有其他内存泄露。我也看两天

**Comment by darcyg** [comment]
开机跟了一下，几分钟内内存就吃光了，开机的时候内存也就190多MB使用，我就刷了几个页面。查看了一下日志
转头一看，4G内存就满了，开始写交换分区了。
日志里面如下，似乎是rpc调用出错，是否内存未释放？
================================
v2raya-web  | 2022/07/13 14:41:19.467 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:21.469 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:23.470 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:25.477 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:27.479 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:29.480 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:31.482 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:33.483 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:39.289 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:43.669 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:45.675 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:47.681 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:49.687 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:51.689 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:53.691 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:53.771 [I] [io.go:428]  tcp:221.222.61.59:43402 accepted tcp:www.google.com.hk:443 [『v2|新加坡04|MPTCP|★★★』]
v2raya-web  | 2022/07/13 14:41:55.692 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:57.692 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:41:59.694 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:42:01.699 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:42:05.906 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:42:05.914 [I] [io.go:428]  tcp:221.222.61.59:54834 accepted tcp:alive.github.com:443 [『v2|香港04|MPTCP|★★★』]
v2raya-web  | 2022/07/13 14:42:07.907 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:42:09.909 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:42:11.910 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:42:12.482 [I] [io.go:428]  tcp:221.222.61.59:54038 accepted tcp:www.google.com.hk:443 [『v2|香港04|MPTCP|★★★』]
v2raya-web  | 2022/07/13 14:42:12.483 [I] [io.go:428]  tcp:221.222.61.59:54836 accepted tcp:alive.github.com:443 [『v2|香港04|MPTCP|★★★』]
v2raya-web  | 2022/07/13 14:42:13.058 [I] [io.go:428]  tcp:221.222.61.59:43398 accepted tcp:www.google.com.hk:443 [『v2|新加坡04|MPTCP|★★★』]
v2raya-web  | 2022/07/13 14:42:15.338 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:42:17.344 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:42:19.346 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:42:21.347 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:42:23.350 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:42:25.353 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:42:27.354 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded
v2raya-web  | 2022/07/13 14:42:29.356 [W] [asm_amd64.s:1571]  ObservatoryProducer: rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Comment by darcyg** [comment]
我降级到1.5.7版本之后，也出现同样问题,初步判断是vless协议内存溢出，正在调回vmess协议测试。
之前v2rayA用了快1年（再之前是直接跑v2ray服务，自己用脚本抓订阅生成配置，我的配置也比较复杂）
最近1年是，改了v2rayA。但是我跑了3个v2rayA的docker。映射不同的inport端口。
最近才发现V2RayA可以通过routingA开多个inport。
所以重写了routingA，用端口分流
比如20170都是HK服务器代理，20180是新加坡代理..
然后订阅换了vless协议...
换了也就2-3周。因为最近上游服务商（速蛙）老被墙。
几乎2-3天就必须重启一下（有时是公司同事启动）。
直到我这两天ssh登vm。才发现开服务十几分钟内vm内存吃光了（目前VM是扩到4个G内存）。
我现在换了vmess在跑，已经半小时了，内存消耗只有202MB...继续观察

**Comment by egg1234** [comment]
经过这几天的验证，ubuntu-20.04.4-live-server-amd64.iso 服务器无论是使用v2fly/v2ray-core及XTLS/Xray-core，然后使用v2raya的v1.5.8.1都是比较稳定的，没有出现自己停止代理或解析不了域名的问题
由于之前把ubuntu-22.04-live-server-amd64.iso版服务器删除了重新安装，也同样验证了v2fly/v2ray-core及XTLS/Xray-core，然后使用v2raya的v1.5.8.1，虽然没有再出现自己停止代理或解析不了域名的问题，但会非常明显的感觉出使用ubuntu-22.04比使用ubuntu-20.04.4反应慢很多，就是v2raya本机curl或客户端浏览器访问网页的反应，而且两种版本系统都是同样使用本地局域网的http或socks5代理，这个应该不是cpu或内存问题，因为htop显示资源消耗非常少

**Comment by mzz2017** [comment]
@egg1234 保证设置一直，特别是dns防污染方面

**Comment by egg1234** [comment]
@mzz2017 所有这些安装的ubuntu-20.04.4-live-server-amd64.iso或ubuntu-22.04-live-server-amd64.iso版服务器都是一样的设置，防止DNS污染设置为转发DNS请求，透明代理/系统代理及端口规则的分流模式都是设置为大陆白名单，代理实现方式设置为tproxy，开启了IP转发

**Comment by mzz2017** [comment]
@egg1234 节点有差异吗

**Comment by mzz2017** [comment]
@egg1234 你dig一个未缓存的域名看看用时是多少

**Comment by egg1234** [comment]
@mzz2017 节点肯定是一样的，都是使用本地局域网的一个http代理outbound，之前验证阶段发现使用socks5代理outbound的各种访问反应效果不如http代理的outbound，这个包括ubuntu20或22都一样，当然这两个代理都是同一个出口节点的两个同时的本地监听

下面是两个ubuntu的dig国外网站结果，看起来ubuntu 22的dig延时比ubuntu 20要大
--------ubuntu 20
dig www.reuters.com

; <<>> DiG 9.16.1-Ubuntu <<>> www.reuters.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17350
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;www.reuters.com.		IN	A

;; ANSWER SECTION:
www.reuters.com.	600	IN	A	13.225.173.123
www.reuters.com.	600	IN	A	13.225.173.39
www.reuters.com.	600	IN	A	13.225.173.98
www.reuters.com.	600	IN	A	13.225.173.120

;; Query time: 609 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Jul 21 16:50:44 UTC 2022
;; MSG SIZE  rcvd: 108



---------ubuntu 22
dig www.reuters.com

; <<>> DiG 9.18.1-1ubuntu1.1-Ubuntu <<>> www.reuters.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23077
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;www.reuters.com.		IN	A

;; ANSWER SECTION:
www.reuters.com.	600	IN	A	13.225.173.123
www.reuters.com.	600	IN	A	13.225.173.39
www.reuters.com.	600	IN	A	13.225.173.98
www.reuters.com.	600	IN	A	13.225.173.120

;; Query time: 914 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Thu Jul 21 16:49:31 UTC 2022
;; MSG SIZE  rcvd: 108

另外dig国内网站有两个现象，如果这个网站是经常访问的网站，那么两种系统的dig延时都在几个ms，分别不很大
但当这个国内网站是不常访问的，那么这个延时就有分别了，举例ubuntu 20的dig延时在8ms的话，ubuntu 22的dig延时就需要16ms，基本都在1倍左右

暂时看起来这个问题应该是ubuntu 22.04引起的，就是ubuntu 22的首次DNS查询所需时间比较长
