### ISSUE TITLE
a Port for windows arm 32

### ISSUE THREAD

**Issue by hamed7ir** [v2rayA/v2rayA#593]
### Content of the feature

as we have surface 2 and rt and bunch of other tablet with windows arm32 i have request to port v2raya for windows arm32 actually rt 
we can install .exe apps with jailbreak in 8.1 or install them in windows 10 arm32.

**Comment by mzz2017** [comment]
@InvisibleRain Hi, could you please explore if this is possible?

**Comment by hamed7ir** [comment]
> @InvisibleRain Hi, could you please explore if this is possible?

![image](https://user-images.githubusercontent.com/30177186/179344359-b218a7b1-3c72-4ac0-ab4c-9b98caae1537.jpeg)

As you can see in my shot 
My surface 2 runnig windows 10 arm32
Run last version v2ray core for arm
Although v2ray core is a little buggy and crashs after browsing more btw it maybe be due to bad port or os malfunctioning or something else 
But i am going to test pervious v2ray core build maybe found more stable version...

**Comment by hamed7ir** [comment]
I randomly downloaded old v2ray 4.27.4 and it works fine
No crash after high proxy routing![image](https://user-images.githubusercontent.com/30177186/179345091-9c4ade77-27d6-470d-b5b2-3c2fb749603f.jpeg)

**Comment by InvisibleRain** [comment]
An installer for arm32 would be even more complicated than for arm64, since NSIS doesn't have any support for arm32

If you want to autostart the app, you could create a shortcut to v2raya.exe. Then edit it via right-click->Properties, so the shortcut contains all the required command-line flags. And finally, press Win+R, type shell:startup and press enter. Put your shortcut here and that should do the trick. Never tested, tbh

**Comment by MarksonHon** [comment]
<https://filetransfer.io/data-package/r3mNp9n1#link>

I have built a Windows armv7 version of v2rayA, you can have a try just like this command:

```ps1
C:\path\to\v2raya\v2raya-windows-arm-7.exe --v2ray-bin C:\path\to\v2ray\v2ray.exe
```

**Comment by hamed7ir** [comment]
[Logs.txt](https://github.com/v2rayA/v2rayA/files/9126834/Logs.txt)

first pf all thank you all for fast response and kindly help

this is the logs that saved . i used a .ink file to do commands and run v2raya in cmd just avoid crash and keep logs . i summaries the whole tests i done and logs i got. btw cmd is run as admin
as you see first it said use --lite command for non linux user i add that and run several time then think about path and run cmd in path to avoid missing geoip.dat . but nothing happend.

**Comment by MarksonHon** [comment]
> [Logs.txt](https://github.com/v2rayA/v2rayA/files/9126834/Logs.txt)
> 
> first pf all thank you all for fast response and kindly help
> 
> this is the logs that saved . i used a .ink file to do commands and run v2raya in cmd just avoid crash and keep logs . i summaries the whole tests i done and logs i got. btw cmd is run as admin as you see first it said use --lite command for non linux user i add that and run several time then think about path and run cmd in path to avoid missing geoip.dat . but nothing happend.

My mistake, on non-Linux platform we should use lite mode:

```
C:\path\to\v2raya\v2raya-windows-arm-7.exe --lite --v2ray-bin C:\path\to\v2ray\v2ray.exe
```

**Comment by hamed7ir** [comment]
> > [Logs.txt](https://github.com/v2rayA/v2rayA/files/9126834/Logs.txt)
> > first pf all thank you all for fast response and kindly help
> > this is the logs that saved . i used a .ink file to do commands and run v2raya in cmd just avoid crash and keep logs . i summaries the whole tests i done and logs i got. btw cmd is run as admin as you see first it said use --lite command for non linux user i add that and run several time then think about path and run cmd in path to avoid missing geoip.dat . but nothing happend.
> 
> My mistake, on non-Linux platform we should use lite mode:
> 
> ```
> C:\path\to\v2raya\v2raya-windows-arm-7.exe --lite --v2ray-bin C:\path\to\v2ray\v2ray.exe
> ```
np i add that to ink file and run that in cmd then the error said missing geoip.dat and tried to download

**Comment by MarksonHon** [comment]
@hamed7ir C:\path\to\v2raya\v2raya-windows-arm-7.exe --lite --v2ray-bin C:\path\to\v2ray\v2ray.exe --v2ray-assetdir C:\path\to\v2ray\

Or you can wait the download to finish

**Comment by hamed7ir** [comment]
> @hamed7ir C:\path\to\v2raya\v2raya-windows-arm-7.exe --lite --v2ray-bin C:\path\to\v2ray\v2ray.exe --v2ray-assetdir C:\path\to\v2ray\
> 
> Or you can wait the download to finish

Fixing that by take all files to the path that wanted to download and save there
![image](https://user-images.githubusercontent.com/30177186/179379657-d494860b-b031-4c23-a0b4-9e91a9617839.jpeg)

As you can see your port now run but there is no routing proxy 
I must test it a little more

**Comment by MarksonHon** [comment]
@hamed7ir you use a wrong v2ray binary path, it must be a exe file which is a Windows program

**Comment by hamed7ir** [comment]
> @hamed7ir you use a wrong v2ray binary path, it must be a exe file which is a Windows program

![image](https://user-images.githubusercontent.com/30177186/179379802-7c7974e3-214e-4ab8-8f5f-a8b5c18853ab.jpeg)

Yes fixed
 then crashed

**Comment by MarksonHon** [comment]
And then, use a PowerShell script is recommended rather than a lnk file:

```ps1
$V2RAYA_V2RAY_ASSETSDIR="C:\path-to-two-dat-files"
$V2RAYA_V2RAY_BIN="C:\path-to-v2ray.exe"
$V2RAYA_LOG_FILE="${env:temp}\v2raya.log"
C:\path-to-v2raya.exe --lite
```

**Comment by hamed7ir** [comment]
> > > @hamed7ir you use a wrong v2ray binary path, it must be a exe file which is a Windows program
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/30177186/179379802-7c7974e3-214e-4ab8-8f5f-a8b5c18853ab.jpeg)
> 
> > 
> 
> > Yes fixed then crashed
> 
> 
> 
> Still wrong v2ray

![image](https://user-images.githubusercontent.com/30177186/179380006-5c01c70e-9120-40f3-8dfd-5ca12ed8eb4e.jpeg)

**Comment by hamed7ir** [comment]
This time didn't crash but no more log ...nothing
![image](https://user-images.githubusercontent.com/30177186/179380063-3fe62d2d-f680-4f50-8b4e-a5d8886c9e56.jpeg)

**Comment by MarksonHon** [comment]
@hamed7ir http://localhost:2017

try to open it

**Comment by hamed7ir** [comment]
> @hamed7ir http://localhost:2017
> 
> try to open it

![image](https://user-images.githubusercontent.com/30177186/179380183-3b9ad159-a7d0-4c34-8fa0-cd1b702bee76.jpeg)

Empty

**Comment by MarksonHon** [comment]
[Uploading v2raya-windows-armv7.zip…]()

Try to use this one instead

**Comment by MarksonHon** [comment]
[v2raya-windows-armv7.zip](https://github.com/v2rayA/v2rayA/files/9126908/v2raya-windows-armv7.zip)

Try to use this one

**Comment by mzz2017** [comment]
I notice that the static gzip library v2rayA using may have some wrong.
However, it is hard to debug for the win arm32 because I have no device.

**Comment by MarksonHon** [comment]
Long time for no reply, this issue closed.
Join the group if you need:
 
<https://t.me/v2raya>
