### ISSUE TITLE
启动代理报错

### ISSUE THREAD

**Issue by Noi-q** [v2rayA/v2rayA#594]
报错内容：failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: iptables -w 2 -t nat -A V2RAY -m mark --mark 0x80/0x80 -j RETURN Warning: Extension mark revision 0 not supported, missing kernel module? iptables: No chain/target/match by that name. : exit status 1

我更改了设置，无论怎样改，都是这个报错，我确保我安装了v2ray内核,并且版本为4.45.2
请求官方帮忙解决

**Comment by MarksonHon** [comment]
进群：
<https://t.me/v2raya_zh>

**Comment by mzz2017** [comment]
@Noi-q 重启电脑

**Comment by Noi-q** [comment]
> @Noi-q 重启电脑

??? 我都发出来了，还不知道重启?

**Comment by MarksonHon** [comment]
@Noi-q 那你参照官方文档补全内核模块吧

**Comment by mzz2017** [comment]
@Noi-q 你提供的信息只有两种可能，一个是你更新了内核，需要重启系统。另一个可能是你没有安装 iptables 内核模块。大多数情况是第一种情况，因为我觉得这个提示“missing kernel module?”一般人都会知道第二种情况的意思。

**Comment by haol666** [comment]
ubuntu18.04.6 iptables is already the newest version (1.6.1-2ubuntu2.1).
