### ISSUE TITLE
可以支持wireGuard？？

### ISSUE THREAD

**Issue by Potterli20** [v2rayA/v2rayA#595]
### 功能特性内容

wireGuard也是可以的

**Comment by mzz2017** [comment]
@Potterli20 目前 core 还不支持，但 v2rayA 的下一步计划是支持用户插件

**Comment by egg1234** [comment]
@Potterli20 由于https://github.com/SagerNet/v2ray-core使用v2fly的安装脚本(https://github.com/v2fly/fhs-install-v2ray/blob/master/install-release.sh)本地安装后缺少(/usr/local/bin/v2ctl)文件，所以安装完成后进入v2raya的web配置界面，v2raya马上报告v2ray-core未正确安装，即使我们强行配置outbound，点击http测试也马上报告unexpected exiting
所以现在使用SagerNet/v2ray-core也是不现实的，需要v2raya本身增加代码检测SagerNet/v2ray-core才行
当然如果后面v2raya支持了SagerNet/v2ray-core，就等于多支持了wireGuard及ssh的outbound协议，因为这个是SagerNet/v2ray-core比v2fly/v2ray-core及XTLS/Xray-core多支持outbound协议

**Comment by MarksonHon** [comment]
> @Potterli20 由于https://github.com/SagerNet/v2ray-core 使用v2fly的安装脚本(https://github.com/v2fly/fhs-install-v2ray/blob/master/install-release.sh) 本地安装后缺少(/usr/local/bin/v2ctl)文件，所以安装完成后进入v2raya的web配置界面，v2raya马上报告v2ray-core未正确安装，即使我们强行配置outbound，点击http测试也马上报告unexpected exiting 所以现在使用SagerNet/v2ray-core也是不现实的，需要v2raya本身增加代码检测SagerNet/v2ray-core才行 当然如果后面v2raya支持了SagerNet/v2ray-core，就等于多支持了wireGuard及ssh的outbound协议，因为这个是SagerNet/v2ray-core比v2fly/v2ray-core及XTLS/Xray-core多支持outbound协议

其实呢，v2rayA 有个 feat_v5 分支，可以用 v5 的 v2ray。不过 SagerNet 独有的功能目前没支持而已

**Comment by aeeq** [comment]
配合 wireproxy 和 v2raya socks5 可以曲线救国
