### ISSUE TITLE
无法在 RT-AX88U 上运行

### ISSUE THREAD

**Issue by jdxj** [v2rayA/v2rayA#598]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

    - v2raya_linux_arm64_1.5.8.1

2. 你通过什么方式安装v2rayA

    - 二进制

3. 你所使用的操作系统

    - aarch64 ASUSWRT-Merlin

### 描述问题：

无法运行

```
$ ./v2raya
madvise: function not implemented
```

搜索了下报错是有关 boltdb 的

**Comment by MarksonHon** [comment]
有需要可以进群：
<https://t.me/v2raya_zh>
