### ISSUE TITLE
链接报错

### ISSUE THREAD

**Issue by kmy-4Q** [v2rayA/v2rayA#600]
### 版本、安装方式、系统
failed to start v2ray-core: not support "tproxy" mode of transparent proxy: ExecCommands: iptables -w 2 -t mangle -N TP_OUT sh: 1: iptables: not found : exit status 127

1. 你在使用什么版本的v2rayA
v2rayA服务端正在运行，Version: 1.5.8.1

2. 你通过什么方式安装v2rayA
deb
3. 你所使用的操作系统
openkykin

### 描述问题

failed to start v2ray-core: not support "tproxy" mode of transparent proxy: ExecCommands: iptables -w 2 -t mangle -N TP_OUT sh: 1: iptables: not found : exit status 127
### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```
 或者粘贴来自 Web 页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
@kmy-4Q which iptables
运行这个命令，然后给下结果出来

**Comment by MarksonHon** [comment]
我试了下这个系统，发现iptables啥的都是没有的，要是用apt安装还会提示依赖冲突，所以你还是换个系统开透明代理吧。
有需要可以进群：
<https://t.me/v2raya_zh>
