### ISSUE TITLE
无法正确导入订阅

### ISSUE THREAD

**Issue by ngdngdc** [v2rayA/v2rayA#612]
### Version, approach of installation, operating system

1. 1.5.9.1698.1-1

2. repo/archlinuxcn

3. 5.18.14-1-Manjaro-Cinnamon

### Description

[此问题](https://github.com/v2rayA/v2rayA/issues/611)未得到有效解决，本人第一次导入的就是[https://github.com/v2rayA/v2rayA/issues/611#issuecomment-1205199477](https://github.com/v2rayA/v2rayA/issues/611#issuecomment-1205199477)中引用的链接但v2raya没有从此链接中导入任何节点,本人已确认在多次重装系统和软件后此问题仍然存在且绝对不是因为本人使用了错误的订阅链接导致的，[这个链接](https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0804.txt)在2dust开发的[v2rayN](https://github.com/2dust/v2rayN)和[v2rayNG](https://github.com/2dust/v2rayNG)都可以正常使用，但在v2raya中不可用。还请开发者不要过于随意的关闭issue。

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```

 You can also paste the log that comes from web administration page

```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by mzz2017** [comment]
感谢你的 issue，问题已成功复现，我向之前的行为道歉。该文件采用了不寻常的带 BOM 的 UTF-8 编码，导致了 base64 解码失败，尽管这并不是标准行为，但我将对其进行适配。

**Comment by mzz2017** [comment]
已修复，现在你可以使用 aur 中的 v2raya-git 来使用最新版本。
