### ISSUE TITLE
RoutingA模式下开机无法直接启用软件提供的LoyalsoldierSite.dat文件导致无法上网

### ISSUE THREAD

**Issue by Blank-Cao** [v2rayA/v2rayA#613]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.9.1698.1（v2raya --version）
2. 你通过什么方式安装v2rayA
pacman 添加 archlinuxcn 源
3. 你所使用的操作系统
Arch Linux

### 描述问题
软件分流使用 RoutingA 模式并用 systemd 设置系统服务，重启，v2raya 罢工，无法上网。
后查看日志发现 v2raya 无法在 /run/user/0/v2raya 文件夹下找到 LoyalsoldierSite.dat 文件，导致无法解析 RoutingA 规则。

### 复现问题的步骤
用 systemd 将 v2raya 设置为系统服务。
软件透明代理设置为与规则端口所选模式一致。
规则端口分流模式设置为 RoutingA，并配置如下一行：
domain(ext:"LoyalsoldierSite.dat:gfw", ext:"LoyalsoldierSite.dat:greatfire")->proxy
之后重启系统。

### v2rayA/v2ray运行日志：
2022/08/06 08:01:57.977 [I] [io.go:429] V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/amd64)
2022/08/06 08:01:57.978 [I] [io.go:429] A unified platform for anti-censorship.
2022/08/06 08:01:57.978 [I] [io.go:429] [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/08/06 08:01:58.058 [I] [io.go:429] main: failed to read config files: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: ext:LoyalsoldierSite.dat:gfw > infra/conf/rule: failed to load external geosite: gfw from LoyalsoldierSite.dat > infra/conf/geodata/standard: failed to open file: LoyalsoldierSite.dat > open /run/user/0/v2raya/LoyalsoldierSite.dat: no such file or directory
2022/08/06 08:01:58.285 [W] [processManager.go:75] only listen at 127.2.0.17: dns port 53 is occupied by systemd-resolve(375)
2022/08/06 08:01:58.286 [W] [asm_amd64.s:1594] v2ray-core: exit status 23
2022/08/06 08:01:58.487 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information

（复制自web界面）

### v2rayA设置以及相关截图
以下复制自 /etc/v2raya/config.conf：（本人 Arch 没有安装截屏软件，只得用这种方式提供配置，十分抱歉）
{"log":{"access":"","error":"none","loglevel":"info"},"inbounds":[{"port":20170,"protocol":"socks","listen":"127.0.0.1","sniffing":{"enabled":false,"destOverride":["http","tls"],"metadataOnly":false},"settings":{"auth":"noauth","udp":true},"streamSettings":null,"tag":"socks_ipv4"},{"port":20171,"protocol":"http","listen":"127.0.0.1","sniffing":{"enabled":false,"destOverride":["http","tls"],"metadataOnly":false},"streamSettings":null,"tag":"http_ipv4"},{"port":20172,"protocol":"http","listen":"127.0.0.1","sniffing":{"enabled":false,"destOverride":["http","tls"],"metadataOnly":false},"streamSettings":null,"tag":"rule-http_ipv4"},{"port":32345,"protocol":"dokodemo-door","listen":"0.0.0.0","sniffing":{"enabled":true,"destOverride":["http","tls"],"metadataOnly":false},"settings":{"network":"tcp,udp","followRedirect":true},"streamSettings":{"sockopt":{"tproxy":"redirect"}},"tag":"transparent"},{"port":53,"protocol":"dokodemo-door","listen":"127.2.0.17","sniffing":{"enabled":false,"metadataOnly":false},"settings":{"network":"udp","address":"2.0.1.7","port":53},"streamSettings":null,"tag":"dns-in"},{"port":35059,"protocol":"dokodemo-door","listen":"127.0.0.1","sniffing":{"enabled":false,"metadataOnly":false},"settings":{"address":"127.0.0.1"},"streamSettings":null,"tag":"api-in_ipv4"},{"port":20170,"protocol":"socks","listen":"::1","sniffing":{"enabled":false,"destOverride":["http","tls"],"metadataOnly":false},"settings":{"auth":"noauth","udp":true},"streamSettings":null,"tag":"socks_ipv6"},{"port":20171,"protocol":"http","listen":"::1","sniffing":{"enabled":false,"destOverride":["http","tls"],"metadataOnly":false},"streamSettings":null,"tag":"http_ipv6"},{"port":20172,"protocol":"http","listen":"::1","sniffing{"log":{"access":"","error":"none","loglevel":"info"},"inbounds":[{"port":20170,"protocol":"socks","listen":"127.0.0.1","sniffing":{"enabled":false,"destOverride":["http","tls"],"metadataOnly":false},"settings":{"auth":"noauth","udp":true},"streamSettings":null,"tag":"socks_ipv4"},{"port":20171,"protocol":"http","listen":"127.0.0.1","sniffing":{"enabled":false,"destOverride":["http","tls"],"metadataOnly":false},"streamSettings":null,"tag":"http_ipv4"},{"port":20172,"protocol":"http","listen":"127.0.0.1","sniffing":{"enabled":false,"destOverride":["http","tls"],"metadataOnly":false},"streamSettings":null,"tag":"rule-http_ipv4"},{"port":32345,"protocol":"dokodemo-door","listen":"0.0.0.0","sniffing":{"enabled":true,"destOverride":["http","tls"],"metadataOnly":false},"settings":{"network":"tcp,udp","followRedirect":true},"streamSettings":{"sockopt":{"tproxy":"redirect"}},"tag":"transparent"},{"port":53,"protocol":"dokodemo-door","listen":"127.2.0.17","sniffing":{"enabled":false,"metadataOnly":false},"settings":{"network":"udp","address":"2.0.1.7","port":53},"streamSettings":null,"tag":"dns-in"},{"port":35059,"protocol":"dokodemo-door","listen":"127.0.0.1","sniffing":{"enabled":false,"metadataOnly":false},"settings":{"address":"127.0.0.1"},"streamSettings":null,"tag":"api-in_ipv4"},{"port":20170,"protocol":"socks","listen":"::1","sniffing":{"enabled":false,"destOverride":["http","tls"],"metadataOnly":false},"settings":{"auth":"noauth","udp":true},"streamSettings":null,"tag":"socks_ipv6"},{"port":20171,"protocol":"http","listen":"::1","sniffing":{"enabled":false,"destOverride":["http","tls"],"metadataOnly":false},"streamSettings":null,"tag":"http_ipv6"},{"port":20172,"protocol":"http","listen":"::1","sniffing":{"enabled":false,"destOverride":["http","tls"],"metadataOnly":false},"streamSettings":null,"tag":"rule-http_ipv6"},{"port":35059,"protocol":"dokodemo-door","listen":"::1","sniffing":{"enabled":false,"metadataOnly":false},"settings":{"address":"127.0.0.1"},"streamSettings":null,"tag":"api-in_ipv6"}],"outbounds":[{"tag":"proxy","protocol":"vmess","settings":{"vnext":[{"address":"193.9.44.100","port":41265,"users":[{"id":"13bc7f0e-5562-4856-aef3-45d44b4346aa","security":"auto"}]}]},"streamSettings":{"network":"tcp","sockopt":{"mark":128}}},{"tag":"direct","protocol":"freedom","settings":{"domainStrategy":"UseIP"},"streamSettings":{"sockopt":{"mark":128}}},{"tag":"block","protocol":"blackhole","settings":{}},{"tag":"dns-out","protocol":"dns","settings":{"port":53,"address":"119.29.29.29","network":"udp"},"streamSettings":{"sockopt":{"mark":128}}}],"routing":{"domainStrategy":"IPOnDemand","domainMatcher":"mph","rules":[{"type":"field","outboundTag":"direct","ip":["193.9.44.100"],"port":"41265"},{"type":"field","outboundTag":"direct","inboundTag":["dns"],"ip":["223.6.6.6"],"port":"53"},{"type":"field","outboundTag":"direct","inboundTag":["dns"],"ip":["119.29.29.29"],"port":"53"},{"type":"field","outboundTag":"direct","inboundTag":["dns"]},{"type":"field","outboundTag":"dns-out","inboundTag":["dns-in"],"port":"53"},{"type":"field","outboundTag":"direct","inboundTag":["transparent"],"ip":["geoip:private","127.0.0.1/8","192.168.31.86/24","::1/128","fe80::3af3:abff:feec:a0a5/64"],"port":"53"},{"type":"field","outboundTag":"direct","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"],"domain":["domain:push-apple.com.akadns.net","domain:push.apple.com"]},{"type":"field","outboundTag":"proxy","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"],"domain":["domain:hubmirror.v2raya.org"]},{"type":"field","outboundTag":"proxy","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"],"domain":["ext:LoyalsoldierSite.dat:gfw","ext:LoyalsoldierSite.dat:greatfire"]},{"type":"field","outboundTag":"proxy","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"],"domain":["domain:raw.githubusercontent.com"]},{"type":"field","outboundTag":"proxy","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"],"domain":["domain:emacs-china.org"]},{"type":"field","outboundTag":"proxy","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"],"ip":["91.105.192.0/23","91.108.4.0/22","91.108.8.0/21","91.108.16.0/21","91.108.56.0/22","95.161.64.0/20","149.154.160.0/20","185.76.151.0/24","2001:67c:4e8::/48","2001:b28:f23c::/47","2001:b28:f23f::/48","2a0a:f280:203::/48"]},{"type":"field","outboundTag":"direct","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"]},{"type":"field","outboundTag":"api-out","inboundTag":["api-in_ipv4","api-in_ipv6"]},{"type":"field","outboundTag":"proxy","network":"tcp,udp"}]},"dns":{"hosts":{"courier.push.apple.com":["1-courier.push.apple.com"]},"servers":[{"address":"223.6.6.6","port":53},{"address":"119.29.29.29","port":53}],"tag":"dns"},"api":{"tag":"api-out","services":["LoggerService"]}}":{"enabled":false,"destOverride":["http","tls"],"metadataOnly":false},"streamSettings":null,"tag":"rule-http_ipv6"},{"port":35059,"protocol":"dokodemo-door","listen":"::1","sniffing":{"enabled":false,"metadataOnly":false},"settings":{"address":"127.0.0.1"},"streamSettings":null,"tag":"api-in_ipv6"}],"outbounds":[{"tag":"proxy","protocol":"vmess","settings":{"vnext":[{"address":"193.9.44.100","port":41265,"users":[{"id":"13bc7f0e-5562-4856-aef3-45d44b4346aa","security":"auto"}]}]},"streamSettings":{"network":"tcp","sockopt":{"mark":128}}},{"tag":"direct","protocol":"freedom","settings":{"domainStrategy":"UseIP"},"streamSettings":{"sockopt":{"mark":128}}},{"tag":"block","protocol":"blackhole","settings":{}},{"tag":"dns-out","protocol":"dns","settings":{"port":53,"address":"119.29.29.29","network":"udp"},"streamSettings":{"sockopt":{"mark":128}}}],"routing":{"domainStrategy":"IPOnDemand","domainMatcher":"mph","rules":[{"type":"field","outboundTag":"direct","ip":["193.9.44.100"],"port":"41265"},{"type":"field","outboundTag":"direct","inboundTag":["dns"],"ip":["223.6.6.6"],"port":"53"},{"type":"field","outboundTag":"direct","inboundTag":["dns"],"ip":["119.29.29.29"],"port":"53"},{"type":"field","outboundTag":"direct","inboundTag":["dns"]},{"type":"field","outboundTag":"dns-out","inboundTag":["dns-in"],"port":"53"},{"type":"field","outboundTag":"direct","inboundTag":["transparent"],"ip":["geoip:private","127.0.0.1/8","192.168.31.86/24","::1/128","fe80::3af3:abff:feec:a0a5/64"],"port":"53"},{"type":"field","outboundTag":"direct","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"],"domain":["domain:push-apple.com.akadns.net","domain:push.apple.com"]},{"type":"field","outboundTag":"proxy","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"],"domain":["domain:hubmirror.v2raya.org"]},{"type":"field","outboundTag":"proxy","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"],"domain":["ext:LoyalsoldierSite.dat:gfw","ext:LoyalsoldierSite.dat:greatfire"]},{"type":"field","outboundTag":"proxy","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"],"domain":["domain:raw.githubusercontent.com"]},{"type":"field","outboundTag":"proxy","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"],"domain":["domain:emacs-china.org"]},{"type":"field","outboundTag":"proxy","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"],"ip":["91.105.192.0/23","91.108.4.0/22","91.108.8.0/21","91.108.16.0/21","91.108.56.0/22","95.161.64.0/20","149.154.160.0/20","185.76.151.0/24","2001:67c:4e8::/48","2001:b28:f23c::/47","2001:b28:f23f::/48","2a0a:f280:203::/48"]},{"type":"field","outboundTag":"direct","inboundTag":["rule-http_ipv4","rule-socks","transparent","rule-http_ipv6"]},{"type":"field","outboundTag":"api-out","inboundTag":["api-in_ipv4","api-in_ipv6"]},{"type":"field","outboundTag":"proxy","network":"tcp,udp"}]},"dns":{"hosts":{"courier.push.apple.com":["1-courier.push.apple.com"]},"servers":[{"address":"223.6.6.6","port":53},{"address":"119.29.29.29","port":53}],"tag":"dns"},"api":{"tag":"api-out","services":["LoggerService"]}}

**Comment by Blank-Cao** [comment]
顺带一提，大部分情况下点击web界面的“就绪”即可正常解析RoutingA规则，但有时会提示 failed to get latest version of GFWList

**Comment by mzz2017** [comment]
@Blank-Cao 软件没有提供这个文件，你需要在设置里点右上角的更新下载这个文件

**Comment by Blank-Cao** [comment]
> @Blank-Cao 软件没有提供这个文件，你需要在设置里点右上角的更新下载这个文件

我当时已经更新了这个文件，但还是会出现这个情况
刚刚重启的时候我还注意到这个文件要在开机后好一会儿才会创建链接文件

**Comment by mzz2017** [comment]
那么下载后还存在问题吗

**Comment by Blank-Cao** [comment]
> 那么下载后还存在问题吗

当时是直接下载都下不下来的
整个电脑没有网络

**Comment by mzz2017** [comment]
@Blank-Cao 好吧，关掉代理再下载一下？下载成功后问题解决了吗

**Comment by Blank-Cao** [comment]
> @Blank-Cao 好吧，关掉代理再下载一下？下载成功后问题解决了吗

嗯……后面我发现其实不需要下载，只要在web界面点击一下设置，软件就会自己在 /run/user/0/v2raya 下创建 LoyalsoldierSite.dat 的软链接。后面再点“就绪”就能正常使用
我看过软件的部分源代码。我初步估计是在一开始启动软件的时候忘了写建立 LoyalsoldierSite.dat 软链接的代码（或者间接调用到相关函数），但在后面点击设置的时候由于需要检查本地文件的版本从而创设了软链接，反而让RoutingA能够读取到文件从而正确解析
（为什么我怀疑是软链接的问题，因为我曾经删过 /run/user/0/v2raya 下的 LoyalsoldierSite.dat，结果问题复现了）

**Comment by mzz2017** [comment]
@Blank-Cao 已复现问题

**Comment by mzz2017** [comment]
已修复，你可以通过 aur v2raya-git 使用最新版本，archlinux v2raya-git 有一定延迟。
