### ISSUE TITLE
导入vless+mkcp节点链接时，相应的seed没有配置。

### ISSUE THREAD

**Issue by okwellok** [v2rayA/v2rayA#616]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.9.1698.1
2. 你通过什么方式安装v2rayA
pacman
3. 你所使用的操作系统
archlinux

### 描述问题

导入vless+mkcp节点链接时，相应的seed没有配置到，手动加入seed后正常。
其他客户端v2rayng和v2rayn导入后正常使用。所以是v2raya的导入有问题？还是就是这样设计的呢？
### 复现问题的步骤

比如vless+mkcp+wechat-video+seed: hTfjidas 的节点链接，导入后seed是空的
手动加入seed后正常。

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![图片](https://user-images.githubusercontent.com/83217712/183350692-5f5517f6-af03-4df8-942b-2dda7baf9519.png)

![图片](https://user-images.githubusercontent.com/83217712/183350239-bff9d0aa-6bee-454a-bc93-765382ba97fd.png)

**Comment by mzz2017** [comment]
@okwellok vless链接长什么样

**Comment by okwellok** [comment]
@mzz2017 vless://c15ca22d-1303-4542-a21d-84e7f19099h6@666.222.333.217:49823?headerType=wechat-video&security=none&seed=hTBeGHjb&type=kcp#666.222.333.217:49823

**Comment by okwellok** [comment]
@mzz2017 这个是服务器上面生成的：vless://c15ca22d-1303-4542-a21d-84e7f19099e5@666.888.777.217:88888?encryption=none&type=kcp&headerType=wechat-video&seed=hTBeGHck#666.888.777.217%3A88888
我改了服务器地址、端口和seed

**Comment by okwellok** [comment]
抱歉，第二个可能被我改坏了。第一个链接是导入之后修改再导出的，重新导入可以复现问题。

**Comment by mzz2017** [comment]
@okwellok 已修

**Comment by okwellok** [comment]
@mzz2017 谢谢大佬
