### ISSUE TITLE
提议一个新功能

### ISSUE THREAD

**Issue by bilibiliwangzheruoyun** [v2rayA/v2rayA#618]
### 您想提出的功能特性是否和现有问题相关？

有个问题，测速后不能排序，超时的节点不能取消，节点不能转换，节点协议不能分类，还有运行速度真的很慢。

### 功能特性内容

作者自己想吧。

**Comment by MarksonHon** [comment]
尊敬的用户您好，很抱歉为您带来了不便，对于您的一切需求，我方将认真考虑，仔细研究，然后不允实现。谢谢您的留言，再见。
