### ISSUE TITLE
除了v2ray 都不支持配置 Network 

### ISSUE THREAD

**Issue by wode2016501** [v2rayA/v2rayA#628]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
git
2. 你通过什么方式安装v2rayA
git
3. 你所使用的操作系统
linux

### 描述问题

除了vm[le]ss都不支持配置 Network[tcp/mkcp]配置

### 复现问题的步骤

服务器配置http+kcp v2raya不支持这样的配置

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```
 或者粘贴来自 Web 页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by TATTXT** [comment]
network选项里选mkcp
