### ISSUE TITLE
Docker 运行V2rayA 时，总是自动恢复config.json和v2raya.json文件

### ISSUE THREAD

**Issue by AnlakHui** [v2rayA/v2rayA#63]
将/etc/v2ray目录挂载到物理卷后，每次修改完这两个文件，加入一些自定义配置后，重启V2rayA后，这两个配置文件都被恢复为默认配置了，有办法设置成重启不自动恢复配置文件吗

**Comment by mzz2017** [comment]
你是想只将v2raya作为透明代理的用途吗




mzz2017
m@mzz.pub




------------------ 原始邮件 ------------------
发件人: AnlakHui <notifications@github.com&gt;
发送时间: 2020年3月31日 00:02
收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[mzz2017/V2RayA] Docker 运行V2rayA 时，总是自动恢复config.json和v2raya.json文件 (#63)





 
将/etc/v2ray目录挂载到物理卷后，每次修改完这两个文件，加入一些自定义配置后，重启V2rayA后，这两个配置文件都被恢复为默认配置了，有办法设置成重启不自动恢复配置文件吗

**Comment by AnlakHui** [comment]
对的，我是把这个v2rayA部署在nas上面，通过端口转发映射出去，这样在外面手机就可以通过socks代理访问，然后有时又需要访问nas所在局域网内的另一台设备，就需要将内网192.168的请求发到v2ray客户端，然后转发给那台内网设备。用centos部署测试了socks加验证，将192.168.0.0/16走direct可以实现，但是换了docker版本，将/etc/v2ray目录挂载到实体机，修改好config.json配置后，重启docker会马上被覆盖成初始配置，有办法让他不要自动覆盖吗

**Comment by mzz2017** [comment]
如果只涉及路由或outbound的修改，可以使用routingA




mzz2017
m@mzz.pub




------------------ 原始邮件 ------------------
发件人: AnlakHui <notifications@github.com&gt;
发送时间: 2020年3月31日 20:24
收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt;
抄送: mzz <m@mzz.pub&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[mzz2017/V2RayA] Docker 运行V2rayA 时，总是自动恢复config.json和v2raya.json文件 (#63)





 
对的，我是把这个v2rayA部署在nas上面，通过端口转发映射出去，这样在外面手机就可以通过socks代理访问，然后有时又需要访问nas所在局域网内的另一台设备，就需要将内网192.168的请求发到v2ray客户端，然后转发给那台内网设备。用centos部署测试了socks加验证，将192.168.0.0/16走direct可以实现，但是换了docker版本，将/etc/v2ray目录挂载到实体机，修改好config.json配置后，重启docker会马上被覆盖成初始配置，有办法让他不要自动覆盖吗

**Comment by AnlakHui** [comment]
对的，我是把这个v2rayA部署在nas上面，通过端口转发映射出去，这样在外面手机就可以通过socks代理访问，然后有时又需要访问nas所在局域网内的另一台设备，就需要将内网192.168的请求发到v2ray客户端，然后转发给那台内网设备。用centos部署测试了socks加验证，将192.168.0.0/16走direct可以实现，但是换了docker版本，将/etc/v2ray目录挂载到实体机，修改好config.json配置后，重启docker会马上被覆盖成初始配置，有办法让他不要自动覆盖吗

**Comment by mzz2017** [comment]
你好。

迟来的解决方案：
```
$ v2raya --help
Usage of v2raya:
  -a, --address string         Listening address (default "0.0.0.0:2017")
  -c, --config string          v2rayA configure directory (default "/etc/v2raya")
      --v2ray-bin string       Executable v2ray binary path. Auto-detect if put it empty.
      --v2ray-confdir string   Additional v2ray config directory, files in it will be combined with config generated by v2rayA
      --webdir string          v2rayA web files directory (default "/etc/v2raya/web")
  -m, --mode string            (deprecated) Options: systemctl, service, universal. Auto-detect if not set
  -s, --pluginlistenport int   Plugin outbound port (default 32346)
      --passcheckroot          Skip privilege checking. Use it only when you cannot start v2raya but confirm you have root
                               privilege
      --reset-password         
      --version                
  -h, --help                   print this help menu
```

你现在可以通过 `--v2ray-confdir` 增加自定义配置。
