### ISSUE TITLE
无法访问 v2raya

### ISSUE THREAD

**Issue by hausen1012** [v2rayA/v2rayA#630]
v2raya安装在没有图形界面的linux机器上。在其他机器无法通过 ip:2017访问

**Comment by mzz2017** [comment]
@hausen1012 确保防火墙没有拦截对应端口，这不是 v2raya 的问题

**Comment by hausen1012** [comment]
请问这是默认所有ip都可以访问到web页面的吗？

**Comment by mzz2017** [comment]
@hausen1012 是的，2017 是监听在所有 ip 的

**Comment by hausen1012** [comment]
谢谢哈

**Comment by hausen1012** [comment]
![image](https://user-images.githubusercontent.com/50026605/185845754-9f5ce323-0199-4dbb-807c-d4eadc4e24d6.png)
![image](https://user-images.githubusercontent.com/50026605/185845768-62af9559-cac4-44a5-a0d8-d1d4396e3e99.png)
不知道这是什么原因

**Comment by mzz2017** [comment]
@hausen1012 先看能不能ping通，再到那边看 iptables-save 是不是默认 reject 了，看有没有 systemctl status firewalld 和 ufw

**Comment by hausen1012** [comment]
谢谢，是我的问题。不好意思了哈
