### ISSUE TITLE
启用透明代理/系统代理 报错

### ISSUE THREAD

**Issue by Mrzqd** [v2rayA/v2rayA#633]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.9.1698.1
2. 你通过什么方式安装v2rayA
rpm -i
3. 你所使用的操作系统
centos 8 Stream 

### 描述问题：

启用透明代理/系统代理报错
failed to start v2ray-core: not support "tproxy" mode of transparent proxy: ExecCommands: iptables -w 2 -t mangle -A TP_OUT -m mark --mark 0x80/0x80 -j RETURN iptables v1.8.4 (nf_tables): Couldn't load match `mark':No such file or directory Try `iptables -h' or 'iptables --help' for more information. : exit status 2

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志

2022/08/24 22:57:16.218  [E] [connection.go:88]  failed to start v2ray-core: not support "tproxy" mode of transparent proxy: ExecCommands: iptables -w 2 -t mangle -A TP_OUT -m mark --mark 0x80/0x80 -j RETURN iptables v1.8.4 (nf_tables): Couldn't load match `mark':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
: exit status 2


```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![image](https://user-images.githubusercontent.com/104408988/186452368-f5dc8cf4-465d-4bbb-b314-cacd0526f5e9.png)
![image](https://user-images.githubusercontent.com/104408988/186452439-f057d818-23da-4480-ac2d-634e60dbb654.png)

**Comment by TATTXT** [comment]
看起来是 centos8 使用的 nftables 的问题，换 iptables 或者换 Debian 试试
https://forums.centos.org/viewtopic.php?t=75661
