### ISSUE TITLE
macOS 版 v2rayA 突然连续弹窗请求一堆隐私权限

### ISSUE THREAD

**Issue by ACTCD** [v2rayA/v2rayA#636]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA：Version: 1.5.9.1698.1-homebrew

2. 你通过什么方式安装v2rayA：homebrew

3. 你所使用的操作系统：macOS

### v2rayA运行日志（Optional）：
无相关内容日志

### v2rayA设置以及相关截图
homebrew 自带 service 以 `--lite` 模式运行。
运行了有一段时间了，今天突然连续弹出一堆要求访问目录以及通讯录、日历、提醒事项、照片在内的多项权限的弹窗请求。
有十个左右连续弹窗没有截图，直接全部拒绝了，附图为部分系统隐私设置中的记录。

![图片](https://user-images.githubusercontent.com/101378590/187128183-6f588e87-31a0-4db4-8c2f-b7937c942aec.png)
![图片](https://user-images.githubusercontent.com/101378590/187128190-a7d6bd5c-6001-436d-b365-d9bfdb97a57a.png)
![图片](https://user-images.githubusercontent.com/101378590/187128199-719ac34b-e082-4513-a038-d78c62f19155.png)

**Comment by cubercsl** [comment]
[77F571C007D039AD9E00766906707C933D78577BA625648EF2A229A72A77C399
](https://github.com/v2rayA/homebrew-v2raya/releases/download/1.5.9.1698.1/v2raya-aarch64-macos-sha256.txt)

**Comment by mzz2017** [comment]
@ACTCD 看起来是对的，但弹窗的 v2raya 确实是 /opt/homebrew/Cellar/v2raya/1.5.9.1698.1/bin/v2raya 吗

**Comment by mzz2017** [comment]
@ACTCD 这就很奇怪了。。v2raya 理论上不会请求这些隐私，建议权限全关掉

**Comment by MarksonHon** [comment]
@ACTCD brew services 的本质是调用 macOS 的 launchctl 管理服务，你可能需要检查一下服务文件是否有被改动，其位置位于 ~/Library/LaunchAgents （我记得不清楚，可能有错误，以 v2raya.org 上手动安装的 wiki 为准），正常的服务文件只会制定三个变量环境，且无需往用户私人目录下写文件。

**Comment by MarksonHon** [comment]
那就只能当做是macOS抽风了，安全起见，重装一次v2rayA吧，记得先禁掉服务

**Comment by MarksonHon** [comment]
长时间无回复，有需要可以加群：
<https://t.me/v2raya_zh>
