### ISSUE TITLE
v2raya and xray XTLS configuration issue

### ISSUE THREAD

**Issue by iopq** [v2rayA/v2rayA#637]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

build from github this year

3. 你通过什么方式安装v2rayA

built from source

5. 你所使用的操作系统

NixOS

### 描述问题：

I use Xray and v2rayA together because I want to use transparent proxy. But when I use XTLS I get an error message:

https://github.com/XTLS/Xray-core/issues/877

every time I set it up, on different computers the UDP part doesn't work right and gives bad MAC error

```
2022/08/29 20:12:20 [Info] [266897868] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to transfer response payload > remote error: tls: bad record MAC
2022/08/29 20:12:20 [Info] [266897868] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
```

somehow the XTLS implementation is not working when I set up v2rayA to use tproxy (or redirect, for that matter)

**Comment by mzz2017** [comment]
@iopq We cannot judge if it is a problem from v2rayA. Can you see "xray" in your log?

**Comment by iopq** [comment]
I changed the logging to turn on xray logs, this is the only way to see this error

I get the error from xray, but the issue is from interaction of v2raya and xray XTLS in UDP packets, I just don't know what

https://github.com/XTLS/Xray-core/discussions/237

**Comment by iopq** [comment]
How does v2raya actually force the proxy on? It's proxying my game in Wine, but my $http_proxy is not set

I can't troubleshoot if I don't figure this out

**Comment by mzz2017** [comment]
> How does v2raya actually force the proxy on? It's proxying my game in Wine, but my $http_proxy is not set
> 
> 
> 
> I can't troubleshoot if I don't figure this out

Transparent proxy in Settings means global proxy.

**Comment by iopq** [comment]
It seems this is not supported, it's an xray issue
