### ISSUE TITLE
The log log is emptied regularly

### ISSUE THREAD

**Issue by liang-hiwin** [v2rayA/v2rayA#639]
The log log is emptied regularly, and you can also view the log by opening and closing the log

**Comment by mzz2017** [comment]
@liang-hiwin Excuse me, can you elaborate?

**Comment by liang-hiwin** [comment]
> 

v2raya.2022-09-02.001.log     Can log files like these (/var/log/v2raya/) be set to be automatically deleted every few days

**Comment by mzz2017** [comment]
@liang-hiwin It already is.

**Comment by liang-hiwin** [comment]
> @liang-hiwin It already is.

The default is how many days?

**Comment by MarksonHon** [comment]
@liang-hiwin 3
