### ISSUE TITLE
经常出现“企业微信”无法发送图片或发送图片超慢

### ISSUE THREAD

**Issue by lhm518** [v2rayA/v2rayA#641]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2rayA服务端正在运行，Version: 1.5.9.1698.1

2. 你通过什么方式安装v2rayA
docker
3. 你所使用的操作系统
centos7.9

### 描述问题：

使用中经常出现“企业微信”无法发送图片或发送图片超慢

### v2rayA运行日志（Optional）：

 # docker mode
 docker logs v2raya
使用这命令后日志超多，有一个多月的量。请问怎么设定它的天数或清空？

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
设置

GFWList
最新:
[2022-08-30](https://github.com/v2rayA/dist-v2ray-rules-dat/releases)
本地:
2022-08-30
透明代理/系统代理 

启用: 分流规则与规则端口所选模式一致
透明代理/系统代理实现方式 

redirect
规则端口的分流模式 

大陆白名单模式
防止DNS污染 

关闭
特殊模式 

关闭
TCPFastOpen 

保持系统默认
多路复用 

关闭
自动更新订阅

关闭
解析订阅链接/更新时优先使用

跟随透明代理/系统代理

**Comment by mzz2017** [comment]
@lhm518 你可以搜 docker 清理日志的方法，另外你使用大陆白名单，域名走代理了吧，改gfwlist

**Comment by lhm518** [comment]
> @lhm518你可以搜索 docker 代理日志的方法，另外你使用大陆域名，走域名吧，改 gfwlist

感谢大神，真的非常好用。
