### ISSUE TITLE
无法正常使用，20170端口未监听

### ISSUE THREAD

**Issue by xiaopangzia** [v2rayA/v2rayA#646]
ubuntu 22.04.1
v2raya 1.5.8
刚启动时正常监听20170端口，我启动telegram（配置proxy sock5 20170）后
端口就不监听了![Uploading t{a8af27b} (a7ec155f-a7eb-4f3f-995f-7c3d1ac71b8a id=0x7f0a0196 tag=CreateIssueFragment) …]()

**Comment by mzz2017** [comment]
日志怎么说？

**Comment by xiaopangzia** [comment]
> 日志怎么说？

![mmexport1662649651236.jpg](https://user-images.githubusercontent.com/29044591/189158364-3c6cb615-a539-4b54-b0e1-bfcb04a0f1c7.jpg)

**Comment by mzz2017** [comment]
@xiaopangzia 你 v2ray 版本是多少

**Comment by xiaopangzia** [comment]
版本1.5.9.1698.1

**Comment by mzz2017** [comment]
@xiaopangzia v2ray-core

**Comment by xiaopangzia** [comment]
> @xiaopangzia 你 v2ray 版本是多少

4.34.0 20220118-150717
原来用你们脚本安装v2ray，一直报v2ray未启动1 然后就apt install v2ray就可以了

**Comment by mzz2017** [comment]
@xiaopangzia 版本过低，不支持的，使用 4.40 以上的版本

**Comment by xiaopangzia** [comment]
> @xiaopangzia 版本过低，不支持的，使用 4.40 以上的版本

好的 谢谢了

**Comment by mzz2017** [comment]
@xiaopangzia 已更新镜像脚本，请重新安装获得 v4.45.2

**Comment by xiaopangzia** [comment]
> @xiaopangzia 已更新镜像脚本，请重新安装获得 v4.45.2

好的
