### ISSUE TITLE
无法获取最新版本的 GFWList

### ISSUE THREAD

**Issue by Lolicon-A** [v2rayA/v2rayA#648]
进入设置就提示这个：
failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on [::1]:53: read udp [::1]:34743->[::1]:53: read: connection refused

**Comment by Venus-WXP** [comment]
我遇到同样的问题：
[version.go:65] failed to get latest version of GFWList: Get "https://api.github.com/repos/v2rayA/dist-v2ray-rules-dat/tags": read tcp 192.168.3.89:58685->20.205.243.168:443: read: connection reset by peer

**Comment by Venus-WXP** [comment]
下面是我的设置：

<img width="680" alt="image" src="https://user-images.githubusercontent.com/18739624/192841154-26fcd5d7-b52e-4c7d-9ca8-13f3f0877acd.png">

<img width="744" alt="image" src="https://user-images.githubusercontent.com/18739624/192840994-53946df2-e01d-4f26-a9d1-0fb3c93d4f2d.png">

**Comment by Venus-WXP** [comment]
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/18739624/192842177-5ca3bcfa-0ca9-4c5b-acab-2d2adbabc3dc.png">

**Comment by xuelingkang** [comment]
我也遇到这个问题，解决了吗

**Comment by MarksonHon** [comment]
建议先用其它方式启动代理再来更新gfwlist，因为镜像站点有可能被GFW干扰了。
