### ISSUE TITLE
通过 --v2ray-assetsdir ./v2ray-core 命令行参数指定 geoip 和 geosite 文件的目录位置不生效

### ISSUE THREAD

**Issue by CeresCa** [v2rayA/v2rayA#649]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2raya_linux_arm_1.5.9.1698.1

2. 你通过什么方式安装v2rayA
直接下载文件 [v2raya_linux_arm_1.5.9.1698.1](https://github.com/v2rayA/v2rayA/releases/download/v1.5.9.1698.1/v2raya_linux_arm_1.5.9.1698.1)

3. 你所使用的操作系统
路由器系统，Linux on ARM (Fresh Tomato on ARMv7 Processor rev 0 (v7l))

### 描述问题

通过 --v2ray-assetsdir ./v2ray-core 命令行参数指定 geoip 和 geosite 文件的目录位置不生效，
日志输出： ` [main.go:27]  V2Ray asset directory is /run/user/0/v2raya` 。
路由器上这个目录无法创建，因为是只读文件系统，只能挂载 U盘 到 /opt 下。
```shell
# mkdir /run
mkdir: can't create directory '/run': Read-only file system
```

### 复现问题的步骤

通过 `--v2ray-assetsdir ./v2ray-core` 指定 geoip 和 geosite 文件的目录位置不生效，始终使用 `/run/user/0/v2raya` 路径 ,
查看代码得知，非 Windows 系统，assetdir 始终使用 `filepath.Join(xdg.RuntimeDir, "v2raya")` 拼接的目录位置，而不是命令行参数指定目录。
https://github.com/v2rayA/v2rayA/blob/96c8ffd2d96be3d8f3e42666bf5ad732e2fdefa7/service/core/v2ray/process.go#L236
https://github.com/v2rayA/v2rayA/blob/96c8ffd2d96be3d8f3e42666bf5ad732e2fdefa7/service/core/v2ray/asset/asset.go#L24

### v2rayA/v2ray运行日志：

```shell
/opt# v2raya  --v2ray-bin ./v2ray-core/v2ray  --v2ray-assetsdir ./v2ray-core -c ./v2raya/
2022/09/09 15:53:46.732 [A] [main.go:27]  V2Ray binary is ./v2ray-core/v2ray
2022/09/09 15:53:46.732 [A] [main.go:27]  V2Ray asset directory is /run/user/0/v2raya
2022/09/09 15:53:46.732 [A] [main.go:27]  v2rayA working directory is /opt
2022/09/09 15:53:46.732 [A] [main.go:27]  v2rayA configuration directory is v2raya/v2raya
2022/09/09 15:53:46.732 [A] [main.go:27]  Golang: go1.18.4
2022/09/09 15:53:46.732 [A] [main.go:27]  OS: linux
2022/09/09 15:53:46.732 [A] [main.go:27]  Arch: arm
2022/09/09 15:53:46.732 [A] [main.go:27]  Lite: false
2022/09/09 15:53:46.733 [A] [main.go:27]  Version: 1.5.9.1698.1
2022/09/09 15:53:46.733 [A] [main.go:27]  Starting...
2022/09/09 15:53:46.733 [I] [main.go:28]  the core was not running the last time v2rayA exited
2022/09/09 15:53:46.798 [A] [index.go:117]  v2rayA is listening at http://127.0.0.1:2017
2022/09/09 15:53:46.798 [A] [index.go:117]  v2rayA is listening at http://192.168.0.2:2017

```

### v2rayA设置以及相关截图
![chrome_74Lnl2ARYP](https://user-images.githubusercontent.com/5327960/189394462-210b256c-c6d0-43cc-ab7b-345ee037dc16.png)
![MobaXterm_5j6rB5l4LW](https://user-images.githubusercontent.com/5327960/189394522-1cda94a3-8a75-4dd4-b985-61cc036b3916.png)

**Comment by mzz2017** [comment]
@CeresCa 应该是显示有误，试试看是否已经生效

**Comment by mzz2017** [comment]
@mzz2017 我看到了，确实需要修一下

**Comment by mzz2017** [comment]
@CeresCa 已修，thanks。在使用新版本前，你可通过环境变量 V2RAY_LOCATION_ASSET 覆写
