### ISSUE TITLE
v2ray 5.1.0 命令行参数不兼容

### ISSUE THREAD

**Issue by zhanghua000** [v2rayA/v2rayA#652]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.9.1698.1
2. 你通过什么方式安装v2rayA
AUR 构建安装 `v2raya` 软件包
3. 你所使用的操作系统
Arch Linux ARM

### 描述问题

若 v2ray 使用 5.1.0 版本，则 v2raya 无法正常启动 v2ray

### 复现问题的步骤

- 确保 v2ray 为 [5.1.0](https://github.com/v2fly/v2ray-core/releases/tag/v5.1.0) 版本
- 正常启动 v2raya

### v2rayA/v2ray运行日志：

```text
2022/09/13 18:31:30.201  [A] [main.go:27]  V2Ray binary is /usr/bin/v2ray
2022/09/13 18:31:30.201  [A] [main.go:27]  V2Ray asset directory is /run/user/0/v2raya
2022/09/13 18:31:30.201  [A] [main.go:27]  v2rayA working directory is /
2022/09/13 18:31:30.201  [A] [main.go:27]  v2rayA configuration directory is /etc/v2raya
2022/09/13 18:31:30.201  [A] [main.go:27]  Golang: go1.19
2022/09/13 18:31:30.201  [A] [main.go:27]  OS: linux
2022/09/13 18:31:30.201  [A] [main.go:27]  Arch: arm64
2022/09/13 18:31:30.201  [A] [main.go:27]  Lite: false
2022/09/13 18:31:30.201  [A] [main.go:27]  Version: 1.5.9.1698.1
2022/09/13 18:31:30.201  [A] [main.go:27]  Starting...
2022/09/13 18:31:32.056  [I] [io.go:429]  flag provided but not defined: -config
2022/09/13 18:31:32.056  [I] [io.go:429]  Usage of /usr/bin/v2ray:
2022/09/13 18:31:32.852  [W] [asm_arm64.s:1165]  v2ray-core: exit status 2
2022/09/13 18:31:32.854  [E] [main.go:28]  failed to start v2ray-core: unexpected exiting: check the log for more information
```

### v2rayA设置以及相关截图
无

Arch Linux 的 `community/v2ray` 还是在版本 4.45.2 估计也是因为这个原因，在 Arch Linux ARM 中使用 `downgrade` 降级 `community/v2ray` 软件包回 4.45.2 版本可恢复正常。

**Comment by MarksonHon** [comment]
@zhanghua000 你可以自行编译feat_v5分支来使用第五代V2Ray

**Comment by cubercsl** [comment]
You can use AUR package `v2raya-git` to build `feat_v5` branch.

**Comment by zhanghua000** [comment]
v2ray 5.1.0 已经进入Arch Linux 的 community 仓库，请考虑给 v2raya 软件包发布一次更新以让未使用 v2raya-git 的用户可以正常运行。

**Comment by ilolipopi** [comment]
v2rayA启动v2ray时用的是`v2ray --config=/etc/v2raya/config.json`，但现在的v2ray版本需要`v2ray run --config=/etc/v2raya/config.json`。我的临时解决方案：
```
mv /bin/v2ray /bin/v2rayr
echo -e '#!/bin/bash\nv2rayr run $@' > /bin/v2ray
chmod +x /bin/v2ray
```
