### ISSUE TITLE
https://apt.v2raya.org 404

### ISSUE THREAD

**Issue by w3ntao** [v2rayA/v2rayA#659]
https://apt.v2raya.org 无法访问，导致apt无法更新v2raya

**Comment by cubercsl** [comment]
please give your error log.

**Comment by yohole** [comment]
> 找到问题了：旧的公钥过期，导致apt无法更新。添加新的公钥后软件正常更新。

我也出现了同样的问题，请问这个如何更新新的公钥呢？ @w3ntao

**Comment by w3ntao** [comment]
> > 找到问题了：旧的公钥过期，导致apt无法更新。添加新的公钥后软件正常更新。
> 
> 我也出现了同样的问题，请问这个如何更新新的公钥呢？ @w3ntao

重新运行一遍安装命令
