### ISSUE TITLE
任务栏图标+自动登录+切换并显示当前节点

### ISSUE THREAD

**Issue by Firestar-Reimu** [v2rayA/v2rayA#661]
1. 虽然没有GUI，但是否可以考虑增加一个任务栏图标，显示当前v2raya是否在运行&连接的是哪个节点
2. 能否增加一个自动登录按钮，不用每次登录都输入账号密码（大部分电脑都是单用户的）
3. 如何切换并显示当前节点？
![Screenshot_20220926_142542](https://user-images.githubusercontent.com/65082432/192207322-ad0a340c-8ca7-4dd5-9ed3-7a745326e50c.png)
如果说蓝色是当前使用的节点，为什么Google还会显示这个
![Screenshot_20220926_142753](https://user-images.githubusercontent.com/65082432/192207648-055998de-fda3-48aa-a948-67f7cb480dfa.png)
还有就是系统重启之后（开机自动启动的）v2rayA会用最近一次连接的节点嘛？

**Comment by cubercsl** [comment]
1. 任务栏图标：https://github.com/YidaozhanYa/v2rayATray
2. 登录操作是浏览器 cookies 。
3. 你的如果错了，你选三个节点就知道黄色的才是当前使用的。

**Comment by mzz2017** [comment]
@Firestar-Reimu 另外节点切换时不会中断当前长连接，建议重启浏览器检查切换成功，或者使用 curl ip.sb

**Comment by mzz2017** [comment]
@Firestar-Reimu 理论上重启后才会清除登陆状态

**Comment by Firestar-Reimu** [comment]
谢谢！

> 登录操作是浏览器 cookies 

我的浏览器配置了退出时不删除cookies，这适用于几乎任何网站（github bilibili archlinuxbbs stackoverflow等），关闭浏览器后都不需要手动登录，但只有v2rayA在关闭浏览器后需要手动登录

**Comment by mzz2017** [comment]
@Firestar-Reimu 检查是否删除了 localStorage

**Comment by Firestar-Reimu** [comment]
浏览器 firefox 105.0.1

存储：登录后看了一下，只有本地存储有数据，cookie、会话存储等其它存储没有

**Comment by mzz2017** [comment]
理论上localStorage本地存储不应该被清除，请检查你的浏览器插件

**Comment by Firestar-Reimu** [comment]
好的，我看看是不是我的ublock origin有问题
