### ISSUE TITLE
windows安装包的编码问题

### ISSUE THREAD

**Issue by Firestar-Reimu** [v2rayA/v2rayA#663]
我的windows开启了UTF8（不是GBK）编码

安装包看上去就是这样的

![image](https://user-images.githubusercontent.com/65082432/192515969-b5078b81-9ad1-4378-856a-20de2acb8b2f.png)

或许可以考虑一下开启[unicode support](https://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System#Unicode_support)，点阵字体也很难看？

**Comment by MarksonHon** [comment]
@Firestar-Reimu 其实有试过打包成msi，无奈本人水准太低，做不成。理论上做成msi就能把arm64的安装包也给做出来。

**Comment by Firestar-Reimu** [comment]
可以看看inno setup，也是开源的

https://github.com/jrsoftware/issrc

**Comment by MarksonHon** [comment]
> 可以看看inno setup，也是开源的
> 
> https://github.com/jrsoftware/issrc

已经添加了 inno 的安装包，但是目前只有英文

**Comment by MarksonHon** [comment]
暂时先关闭，有需要可以进群
