### ISSUE TITLE
Failed to start v2raya.service: Unit v2raya.service not found.

### ISSUE THREAD

**Issue by ZZP-DMU** [v2rayA/v2rayA#667]
1.我使用的是文档里debian/ubuntu里的方法，安装的是最新v2raya

2.我把apt install .deb包的方法，dpkg -i .deb包的方法以及sudo apt install v2raya都尝试了一遍

3. 我使用的是deepin v20.7

### 描述问题：

安装过程还是比较顺利的，就是使用apt install时，提示了秘钥无效的问题，所以我使用了apt-key add  ****这个命令，并且可以安装了。但是我发现无论使用何种安装方法，都无法开启v2raya的服务。并且我在/etc/systemd/system目录下找不到v2raya.service这个文件。也不知道是哪里出问题了。但是我可以使用v2raya --lite开启应用。

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![Uploading 截图_选择区域_20221001130313.png…]()

**Comment by mzz2017** [comment]
@ZZP-DMU 应该是在 /usr/lib/systemd/system

**Comment by MarksonHon** [comment]
非软件本身的故障，有需要可以加群：
<https://t.me/v2raya_zh>
