### ISSUE TITLE
Brew Formula

### ISSUE THREAD

**Issue by MohamadKh75** [v2rayA/v2rayA#670]
### Is the feature related with existing problem?

No (Maybe?)

### Content of the feature

Hey
Thanks for your great tool!
Can we have a brew formula for this awesome package so I can install it with `brew install v2raya`?
I searched in https://v2raya.org/en/docs/prologue/installation/ but couldn't find a macOS way
I'm already using this with binaries but if we can have a brew way, updates would be much simpler!

Thanks

**Comment by MohamadKh75** [comment]
English translations are not ready yet [here](https://v2raya.org/docs/prologue/installation/macos/)

```bash
brew tap v2raya/v2raya
brew install v2raya
```

**Comment by MarksonHon** [comment]
macOS English docs added
