### ISSUE TITLE
与最新版本的v2ray-core不兼容

### ISSUE THREAD

**Issue by shenyaojin** [v2rayA/v2rayA#671]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.9.1698.1
2. 你通过什么方式安装v2rayA
AUR社区打包的v2rayA
3. 你所使用的操作系统
Manjaro Linux x86_64

### 描述问题

与最新的v2ray-core(ver. 5.1.0)不兼容，导致无法正确识别v2ray core的版本。
如果把v2ray-core回滚到4.xx版本则能完好地运行。

### 复现问题的步骤

升级v2ray-core到最新版本。

### v2rayA/v2ray运行日志：

N/A

**Comment by MarksonHon** [comment]
<https://t.me/v2raya_zh/87943>

**Comment by Firestar-Reimu** [comment]
切换到v2raya-git AUR软件包

想知道什么时候v2raya AUR软件包适配v2ray 5
