### ISSUE TITLE
v2rayA服务启动后与KVM冲突，导致KVM无法正常连接英特网

### ISSUE THREAD

**Issue by RuiBaiXYZ** [v2rayA/v2rayA#672]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
$ v2raya --version
1.5.9.1698.1

2. 你通过什么方式安装v2rayA
dnf localinstall ./v2raya_redhat_x64_1.5.9.1698.1.rpm

3. 你所使用的操作系统
$ cat /etc/rocky-release
Rocky Linux release 9.0 (Blue Onyx)
$ uname -r
5.14.0-70.26.1.el9_0.x86_64

### 描述问题
安装KVM
qemu-kvm.x86_64     6.2.0-11.el9_0.5
libvirt-daemon-driver-qemu.x86_64      8.0.0-8.1.el9

当v2rayA启动后，KVM 虚拟机无法访问英特网，具体表现为：
ping www.baidu.com 正常
curl www.baidu.com 超时，无反应；

当v2rayA停止后，KVM 虚拟机可以正常访问英特网，具体表现为：
ping www.baidu.com 正常
curl www.baidu.com 正常；

当启动KVM 虚拟机后，KVM虚拟机可以正常访问英特网，此时再启动v2rayA，v2rayA无法连接VPN。

考虑点：
是否存在v2raya与KVM的配置上存在端口冲突，或者服务冲突，或者是路由冲突等，可能会导致两者无法同时启动，需要各位的帮忙。
多谢～

### v2rayA/v2ray运行日志：

# tail -n 50 /var/log/v2raya/v2raya.log
2022/10/06 23:33:45.762  [I] [io.go:428]  192.168.2.101:36380 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:33:47.778  [I] [io.go:428]  192.168.2.101:56296 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:33:48.126  [I] [io.go:428]  192.168.2.101:56306 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:33:50.430  [I] [io.go:428]  192.168.2.101:56318 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:33:50.677  [I] [io.go:428]  192.168.2.101:56324 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:33:52.987  [I] [io.go:428]  192.168.2.101:56330 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:33:53.235  [I] [io.go:428]  192.168.2.101:56340 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:33:55.450  [I] [io.go:428]  192.168.2.101:56356 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:33:55.698  [I] [io.go:428]  192.168.2.101:56362 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:33:57.419  [I] [io.go:428]  192.168.2.101:50788 accepted udp:17.253.84.253:123 [direct]
2022/10/06 23:33:58.005  [I] [io.go:428]  192.168.2.101:40094 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:33:58.256  [I] [io.go:428]  192.168.2.101:40102 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:33:59.915  [I] [io.go:428]  192.168.2.101:38252 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:33:59.915  [I] [io.go:428]  192.168.2.101:49430 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:00.566  [I] [io.go:428]  192.168.2.101:40106 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:00.819  [I] [io.go:428]  192.168.2.101:40120 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:01.373  [I] [io.go:428]  192.168.2.101:58201 accepted udp:162.159.200.1:123 [direct]
2022/10/06 23:34:01.744  [I] [io.go:428]  192.168.2.101:33495 accepted udp:223.255.185.2:123 [direct]
2022/10/06 23:34:03.051  [I] [io.go:428]  192.168.2.101:40122 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:03.375  [I] [io.go:428]  192.168.2.101:40124 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:04.323  [I] [io.go:428]  192.168.2.101:34334 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:04.335  [I] [io.go:428]  192.168.2.101:37948 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:04.335  [I] [io.go:428]  192.168.2.101:40403 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:04.336  [I] [io.go:428]  192.168.2.101:60795 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:04.336  [I] [io.go:428]  192.168.2.101:39586 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:04.345  [I] [io.go:428]  192.168.2.101:50609 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:05.694  [I] [io.go:428]  192.168.2.101:40134 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:05.936  [I] [io.go:428]  192.168.2.101:40150 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:08.373  [I] [io.go:428]  192.168.2.101:49954 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:08.596  [I] [io.go:428]  192.168.2.101:49962 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:10.909  [I] [io.go:428]  192.168.2.101:49976 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:11.168  [I] [io.go:428]  192.168.2.101:49994 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:13.477  [I] [io.go:428]  192.168.2.101:50008 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:13.718  [I] [io.go:428]  192.168.2.101:50022 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:16.107  [I] [io.go:428]  192.168.2.101:50032 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:16.380  [I] [io.go:428]  192.168.2.101:50034 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:18.691  [I] [io.go:428]  192.168.2.101:57742 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:18.947  [I] [io.go:428]  192.168.2.101:57752 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:21.199  [I] [io.go:428]  192.168.2.101:57762 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:21.499  [I] [io.go:428]  192.168.2.101:57766 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:22.863  [I] [io.go:428]  192.168.2.101:45445 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:22.876  [I] [io.go:428]  192.168.2.101:44684 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:22.877  [I] [io.go:428]  192.168.2.101:47239 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:22.877  [I] [io.go:428]  192.168.2.101:40252 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:22.878  [I] [io.go:428]  192.168.2.101:42660 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:22.887  [I] [io.go:428]  192.168.2.101:60235 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:22.888  [I] [io.go:428]  192.168.2.101:44856 accepted udp:192.168.2.1:53 [dns-out]
2022/10/06 23:34:23.820  [I] [io.go:428]  192.168.2.101:57776 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:24.065  [I] [io.go:428]  192.168.2.101:57784 accepted tcp:18.233.72.79:443 [direct]
2022/10/06 23:34:26.959  [I] [io.go:428]  192.168.2.101:41231 accepted udp:162.159.200.123:123 [direct]

**Comment by Delayless** [comment]
请问下你是怎么解决的，我看了其他issue修改routingA也没用
