### ISSUE TITLE
v2raya和v2raya-git有什么区别？

### ISSUE THREAD

**Issue by epubreader** [v2rayA/v2rayA#673]
最近更新发现v2raya用不了， 发现要降级v2ray包，
v2raya和v2raya-git有什么区别？ 为什么有二个包？

**Comment by Lew1s777** [comment]
git仓库是从github的master分支构建的 你可以认为```v2ray-git```更**新**
因为v2ray-core的大版本更新 老的v2raya无法兼容新的v2ray-core 因此```v2raya```会需要降级v2ray包
当然 你也可以通过改用```v2raya-git```然后使用最新版的v2ray-core

**Comment by MarksonHon** [comment]
<https://t.me/v2raya_zh/87943>
