### ISSUE TITLE
支持导入 clash 配置文件吗？

### ISSUE THREAD

**Issue by yangyuw** [v2rayA/v2rayA#677]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.6.9.8
2. 你通过什么方式安装v2rayA
docker
3. 你所使用的操作系统
群辉7.0

### 描述问题：

请问支持导入 YAML 格式的 clash 配置文件吗，阅读了文档发现好像只支持订阅和ssr链接？

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
不支持
