### ISSUE TITLE
关闭代理时自动关闭系统代理(透明代理)

### ISSUE THREAD

**Issue by qwq0** [v2rayA/v2rayA#679]
### 功能特性内容

通过左上角的关闭代理关闭v2ray后并没有改变设置中的系统代理
需要手动关闭设置中的系统代理

**Comment by mzz2017** [comment]
@qwq0 你是windows还是macos，你确定这影响了什么吗？表现在哪里

**Comment by qwq0** [comment]
@mzz2017 我是windows系统 复现问题的概率非常低 但有时会在关闭代理后访问网页显示代理服务器错误 系统代理开关没有正常关闭 在我重启电脑后无法复现此问题 问题的截图康起来像酱紫
![image](https://user-images.githubusercontent.com/82009862/195016888-43fc83e6-4cba-47a9-acb2-e67ce35decf6.png)

**Comment by qwq0** [comment]
我在另外一台电脑上安装也不会发生这个问题 应该事偶然问题

**Comment by qwq0** [comment]
话说有打算添加windows上弹出申请通过防火墙窗口的功能嘛? 好像目前只能关掉防火墙才能从其他设备连接 在“允许应用通过防火墙”里勾选这个还是不能用
![image](https://user-images.githubusercontent.com/82009862/195029775-8e998a7b-d7f6-4636-957a-4b66252b6ac3.png)
必须要关掉防火墙

**Comment by qwq0** [comment]
@mzz2017 找到原因了 这可能是一个bug 在关闭左上角代理开关后进行延迟测试会使系统代理开关打开 此时访问网页会显示代理服务器出现问题
