### ISSUE TITLE
v2raya找不到v2ray-core核心

### ISSUE THREAD

**Issue by Wings-Fantasy** [v2rayA/v2rayA#687]
### 版本、安装方式、系统
OS: Arch
AUR安装的v2raya Version: 1.5.9.1698.1
包管理器安装的v2ray 5.1.0-2

### 描述问题
某一次更新系统后v2raya报错：检测到v2ray-core可能未正确安装，请检查

### v2rayA/v2ray运行日志：

<details> <summary>展开/收起</summary>

<div class="highlight highlight-source-shell notranslate position-relative overflow-auto" dir="auto"><pre><span class="pl-c"><span class="pl-c">#</span> sudo tail -n 50 /var/log/v2raya/v2raya.log</span>

2022/10/23 05:42:00.938  [A] [main.go:27]  V2Ray binary is /usr/bin/v2ray
2022/10/23 05:42:00.941  [A] [main.go:27]  V2Ray asset directory is /run/user/0/v2raya
2022/10/23 05:42:00.941  [A] [main.go:27]  v2rayA working directory is /
2022/10/23 05:42:00.941  [A] [main.go:27]  v2rayA configuration directory is /etc/v2raya
2022/10/23 05:42:00.941  [A] [main.go:27]  Golang: go1.19.2
2022/10/23 05:42:00.941  [A] [main.go:27]  OS: linux
2022/10/23 05:42:00.941  [A] [main.go:27]  Arch: amd64
2022/10/23 05:42:00.941  [A] [main.go:27]  Lite: <span class="pl-c1">false</span>
2022/10/23 05:42:00.941  [A] [main.go:27]  Version: 1.5.9.1698.1
2022/10/23 05:42:00.941  [A] [main.go:27]  Starting...
2022/10/23 05:42:01.035  [E] [main.go:28]  failed to start v2ray-core: failed to get the version of v2ray-core
2022/10/23 05:42:01.056  [A] [index.go:117]  v2rayA is listening at http://127.0.0.1:2017
2022/10/23 05:42:01.056  [A] [index.go:117]  v2rayA is listening at http://192.168.10.100:2017
2022/10/23 05:42:01.056  [A] [index.go:117]  v2rayA is listening at http://[::1]:2017
2022/10/23 05:42:01.056  [A] [index.go:117]  v2rayA is listening at http://[fe80::a10b:2457:4014:6f6b]:2017
2022/10/23 05:42:02.733  [I] [asm_amd64.s:1594]  [AutoUpdate] Subscriptions: Complete updating subscription -- ID: 0，Address: https://sub2.wwwowo.com/modules/servers/V2raySocks/osubscribe.php<span class="pl-k">?</span>sid=1884<span class="pl-k">&amp;</span>token=bl
2022/10/23 05:42:02.918  [I] [asm_amd64.s:1594]  [AutoUpdate] Subscriptions: Complete updating subscription -- ID: 1，Address: https://feiniaoyun.xyz/api/v1/client/subscribe<span class="pl-k">?</span>token=b3ffc3dcaf977fdd9692db9c6d88dd0e
2022/10/22 22:36:00.391  [E] [connection.go:88]  failed to start v2ray-core: failed to get the version of v2ray-core
2022/10/22 22:46:28.720  [A] [main.go:27]  V2Ray binary is /usr/bin/v2ray
2022/10/22 22:46:28.720  [A] [main.go:27]  V2Ray asset directory is /run/user/0/v2raya
2022/10/22 22:46:28.720  [A] [main.go:27]  v2rayA working directory is /
2022/10/22 22:46:28.720  [A] [main.go:27]  v2rayA configuration directory is /etc/v2raya
2022/10/22 22:46:28.720  [A] [main.go:27]  Golang: go1.19.2
2022/10/22 22:46:28.720  [A] [main.go:27]  OS: linux
2022/10/22 22:46:28.720  [A] [main.go:27]  Arch: amd64
2022/10/22 22:46:28.720  [A] [main.go:27]  Lite: <span class="pl-c1">false</span>
2022/10/22 22:46:28.720  [A] [main.go:27]  Version: 1.5.9.1698.1
2022/10/22 22:46:28.720  [A] [main.go:27]  Starting...
2022/10/22 22:46:28.816  [E] [main.go:28]  failed to start v2ray-core: failed to get the version of v2ray-core
2022/10/22 22:46:28.826  [A] [index.go:117]  v2rayA is listening at http://127.0.0.1:2017
2022/10/22 22:46:28.826  [A] [index.go:117]  v2rayA is listening at http://192.168.10.100:2017
2022/10/22 22:46:28.826  [A] [index.go:117]  v2rayA is listening at http://[::1]:2017
2022/10/22 22:46:28.826  [A] [index.go:117]  v2rayA is listening at http://[fd00:6868:6868::44b]:2017
2022/10/22 22:46:28.826  [A] [index.go:117]  v2rayA is listening at http://[fd00:6868:6868:0:ecc2:58fc:1b79:ad82]:2017
2022/10/22 22:46:28.826  [A] [index.go:117]  v2rayA is listening at http://[fe80::a10b:2457:4014:6f6b]:2017
2022/10/22 22:46:30.703  [I] [asm_amd64.s:1594]  [AutoUpdate] Subscriptions: Complete updating subscription -- ID: 0，Address: https://sub2.wwwowo.com/modules/servers/V2raySocks/osubscribe.php<span class="pl-k">?</span>sid=1884<span class="pl-k">&amp;</span>token=bl
2022/10/22 22:46:31.358  [I] [asm_amd64.s:1594]  [AutoUpdate] Subscriptions: Complete updating subscription -- ID: 1，Address: https://feiniaoyun.xyz/api/v1/client/subscribe<span class="pl-k">?</span>token=b3ffc3dcaf977fdd9692db9c6d88dd0e</pre></div>

</details>

**Comment by MarksonHon** [comment]
@Wings-Fantasy <https://t.me/v2raya_zh/87943>

**Comment by mzz2017** [comment]
@Wings-Fantasy 降级v2ray到4.45.2或者使用v2raya-git

**Comment by wineee** [comment]
v2raya-git 下一个 tag 大概什么时候打
