### ISSUE TITLE
[mac]  更新mac 13后无法使用系统代理

### ISSUE THREAD

**Issue by icepie** [v2rayA/v2rayA#690]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

> 1.5.9.1698.1-homebrew

2. 你通过什么方式安装v2rayA

> brew

3. 你所使用的操作系统

> mac os 13

### 描述问题

无法启用系统代理

### 日志

```bash
failed to start v2ray-core: not support "system proxy" mode of transparent proxy: ExecCommands: /usr/sbin/networksetup -setwebproxystate "USB 10/100/1000 LAN" on ** Error: Command requires admin privileges. : exit status 14

```

**Comment by MarksonHon** [comment]
@icepie 我黑苹果下复现失败了，内置的WiFi与板载网卡都能设置上代理

**Comment by icepie** [comment]
翻阅了相关 issue ...

暂时把原因归为 ota 的 bug 吧, 估计抹盘重装了系统就好了


### 临时解决方法

```bash
sudo visudo
```

编辑一下

```
# root and users in group wheel can run anything on any machine as any user
root            ALL = (ALL) ALL
%admin          ALL = (ALL) ALL
<你的用户名> ALL=(ALL) NOPASSWD: /usr/sbin/networksetup
```

然后再重新编译 v2raya

修改 `service/core/iptables/systemProxy_macos.go`

在 networksetup 相关代码前都加上 sudo

编译好后 替换掉二进制文件

```bash
cp v2raya $(which v2raya)
```

再重启 service

```
brew services restart v2raya/v2raya/v2raya
```

### 最后

这应该算是苹果系统的 bug

但是我有个想法可以解决一下这个问题

当遇到 `Error: Command requires admin privileges.` 的时候

可以把设置代理的命令用 `osascript` 包装一下

例如:


```bash
osascript -e 'do shell script "networksetup -setdnsservers Wi-Fi 127.0.0.1" with administrator privileges'
```

这样就会出现一个对话框 提权...

![截屏2022-10-27 12 56 08](https://user-images.githubusercontent.com/28620142/198195491-36da4217-318d-478d-9489-5f8329014724.png)

**Comment by MarksonHon** [comment]
检查一下你的用户是否还留在admin组

**Comment by icepie** [comment]
@MarksonHon 

```
$ groups                                       
staff access_bpf everyone localaccounts _appserverusr admin _appserveradm _lpadmin com.apple.sharepoint.group.1 _appstore _lpoperator _developer _analyticsusers com.apple.access_ftp com.apple.access_screensharing com.apple.access_ssh com.apple.access_remote_ae com.apple.sharepoint.group.2
```

**Comment by MarksonHon** [comment]
有需要就进群聊，这里先关闭：
https://t.me/v2raya_zh
