### ISSUE TITLE
macOS Ventura 13.0 - Apple translation is unavailable

### ISSUE THREAD

**Issue by Misakaou** [v2rayA/v2rayA#692]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

1.5.9.1698.1

2. 你通过什么方式安装v2rayA

手动安装

3. 你所使用的操作系统

macOS Ventura 13.0

### 描述问题：

开启v2rayA代理后Mac自带的翻译失效，显示“翻译” 目前不可用

#### 1. 参考文章

- [macOS Ventura beta 6 Safari 浏览器自带翻译异常 - Github](https://github.com/yichengchen/clashX/discussions/964)
- [macOS Ventura 开启 Surge iOS 后，文本翻译出现问题 - v2ex](https://www.v2ex.com/t/859652)

#### 2. 试图修改v2rayA设置

- 配置界面如下图所示

<img width="626" alt="Screenshot 2022-10-30 at 15 11 04" src="https://user-images.githubusercontent.com/40706446/198866801-f1dd4dbf-b712-460d-beaf-a2012bdbee0f.png">

- 以下是我编辑的Routing规则

```text
# 大陆白名单模式
default: proxy
domain(geosite:geolocation-!cn)->proxy
domain(geosite:cn)->direct
ip(geoip:private, geoip:cn)->direct

# apple service
domain(domain: apple.com)->direct
domain(domain: sequoia.apple.com)->direct
domain(domain: seed-sequoia.siri.apple.com)->direct
```

> ##  但是它并不起作用

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

1. 翻译失败截图

<img width="362" alt="Screenshot 2022-10-30 at 15 07 33" src="https://user-images.githubusercontent.com/40706446/198866693-16bfedca-742e-42e4-baf8-3c6aee7dccb4.png">

**Comment by MarksonHon** [comment]
建议直接：
`domain(geosite:apple) -> direct`

**Comment by Misakaou** [comment]
> 建议直接：
> `domain(geosite:apple) -> direct`

感谢您的帮助，但是依旧不可用，这是我修改后的Routing规则：

```text
# 大陆白名单模式
default: proxy
domain(geosite:geolocation-!cn)->proxy
domain(geosite:cn)->direct
ip(geoip:private, geoip:cn)->direct

# apple service
domain(geosite:apple) -> direct
```

> 在[macOS Ventura beta 6 Safari 浏览器自带翻译异常](https://github.com/yichengchen/clashX/discussions/964)中[@FFFergie](https://github.com/FFFergie)也提到了
> > 这个情况的特殊之处在于只要开启了“设置为系统代理”就会出现，出站模式选成直连也不行。

**Comment by MarksonHon** [comment]
@Misakaou 我自己测试了下，的确是一开系统代理就烂掉，这个估计要苹果的阿三师傅们才能修好

**Comment by Misakaou** [comment]
> @Misakaou 我自己测试了下，的确是一开系统代理就烂掉，这个估计要苹果的阿三师傅们才能修好

好的，感谢回复🙏

看到隔壁ClashX似乎有忽略代理的配置，v2rayA不知道能不能添加诶。也许得看内核支持情况？

主要是Safari不能单独设定代理，还不想换Firefox chrome，寄。

**Comment by mzz2017** [comment]
@Misakaou clashX是tun模式。qv2ray和v2rayA是设置系统代理，所以不能忽略代理

**Comment by Misakaou** [comment]
> @Misakaou clashX是tun模式。qv2ray和v2rayA是设置系统代理，所以不能忽略代理

明白了，非常感谢

**Comment by Misakaou** [comment]
macOS 13.0.1 (22A400) 更新解决了这个问题。

**Comment by love4taylor** [comment]
> @Misakaou clashX是tun模式。qv2ray和v2rayA是设置系统代理，所以不能忽略代理

1. ClashX 是 System Proxy，ClashX Pro 才支持 TUN
2. TUN 反倒没有这个问题，因为并没有设置 System Proxy
3. 正因为 v2rayA 是 System Proxy 才可以忽略代理 `networksetup -setproxybypassdomains`

> macOS 13.0.1 (22A400) 更新解决了这个问题。

macOS 13.2 表示 并没有修复

**Comment by chenzhwsysu57** [comment]
> 

请问现在的最新版本解决了问题了吗？我是shadowrocket软件，同样设置了绕过代理也不行

**Comment by Misakaou** [comment]
@love4taylor @chenzhwsysu57 我这边目前是全局代理，CN白名单分流，但是并没有这个问题了，可能存在个体差异。
