### ISSUE TITLE
v2ray升级5.0后无法使用

### ISSUE THREAD

**Issue by roderickbao** [v2rayA/v2rayA#697]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v1.6.9.8
2. 你通过什么方式安装v2rayA
直接下载文件到/usr/local/bin
3. 你所使用的操作系统
Alpine

### 描述问题
原先正常使用，升级v2ray至V2Ray 5.1.0 (v2ray) 1667325841 (go1.19.3 linux/amd64)后，V2rayA无法正常启用，
提示failed to start v2ray-core: failed to get the version of v2ray-core

### 复现问题的步骤
v2ray退回V2Ray 4.45.0 (v2ray) 1665181922 (go1.18.7 linux/amd64)后正常使用。

### v2rayA/v2ray运行日志：

2022/11/07 03:15:06.244 [A] [main.go:27] V2Ray binary is /usr/bin/v2ray
2022/11/07 03:15:06.246 [A] [main.go:27] V2Ray asset directory is /run/user/0/v2raya
2022/11/07 03:15:06.246 [A] [main.go:27] v2rayA working directory is /
2022/11/07 03:15:06.246 [A] [main.go:27] v2rayA configuration directory is /usr/local/etc/v2raya
2022/11/07 03:15:06.246 [A] [main.go:27] Golang: go1.18.4
2022/11/07 03:15:06.246 [A] [main.go:27] OS: linux
2022/11/07 03:15:06.246 [A] [main.go:27] Arch: amd64
2022/11/07 03:15:06.246 [A] [main.go:27] Lite: false
2022/11/07 03:15:06.246 [A] [main.go:27] Version: 1.5.9.1698.1
2022/11/07 03:15:06.246 [A] [main.go:27] Starting...
2022/11/07 03:15:06.249 [I] [main.go:28] the core was not running the last time v2rayA exited
2022/11/07 03:15:06.288 [A] [index.go:117] v2rayA is listening at http://127.0.0.1:2017
2022/11/07 03:15:06.288 [A] [index.go:117] v2rayA is listening at http://192.168.2.89:2017
2022/11/07 03:15:06.288 [A] [index.go:117] v2rayA is listening at http://[::1]:2017
2022/11/07 03:15:06.288 [A] [index.go:117] v2rayA is listening at http://[240e:.....]:2017
2022/11/07 03:15:06.288 [A] [index.go:117] v2rayA is listening at http://[fe80::820:97ff:fef7:365a]:2017
2022/11/07 03:15:28.120 [E] [connection.go:88] failed to start v2ray-core: failed to get the version of v2ray-core

```

**Comment by smzlivee** [comment]
我也出现同样的问题 v2ray5.10 版本 v2raya 1.5.9.1698.1 版本，会一直提示failed to get the version of v2ray-core

**Comment by MarksonHon** [comment]
@smzlivee 目前只有两种方案：
1. 使用不稳定版本的v2rayA，可以从[这里](https://github.com/v2rayA/v2rayA/actions/runs/3404750263)下载后手动替换掉。
2. 降级v2ray到四代，或者使用[Xray](https://github.com/XTLS/alpinelinux-install-xray)。
