### ISSUE TITLE
Is there a problem with the documentation? Different menus have the same unrelated content on the menu theme

### ISSUE THREAD

**Issue by dong-lufei** [v2rayA/v2rayA#698]
https://v2raya.org/docs/manual/import/
https://v2raya.org/docs/manual/transparent-proxy/

The above two document menu pages have the following irrelevant content：

[Requirements](https://v2raya.org/docs/manual/import/#requirements)
[Start a new Doks project](https://v2raya.org/docs/manual/import/#start-a-new-doks-project)
[Create a new site](https://v2raya.org/docs/manual/import/#create-a-new-site)
[Change directories](https://v2raya.org/docs/manual/import/#change-directories)
[Install dependencies](https://v2raya.org/docs/manual/import/#install-dependencies)
[Start development server](https://v2raya.org/docs/manual/import/#start-development-server)
[Other commands](https://v2raya.org/docs/manual/import/#other-commands)

**Comment by git136975643** [comment]
https://v2raya.org/docs/manual/ There are many such problems under this big menu

**Comment by MarksonHon** [comment]
Wiki should be writen by everyone, or it will be the default sample
