### ISSUE TITLE
v2ray exited with code -2

### ISSUE THREAD

**Issue by Sharelter** [v2rayA/v2rayA#703]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
1.5.9.1698.1

2. What approach of installation do you install V2rayA?
Download the newest release package
3. What is your operating system?
ArchLinux

### Description

I installed v2raya and v2raya followed by the V2raya-wiki
I installed the v2ray package from the official repo and v2raya-bin from AUR via yay.
The version of v2ray in the offical repo is 5.1.0-2
With this install, v2ray could not work at all.
When I click start , it shows 'v2ray exited with code 2'

I tried an older version of v2ray which is : https://archlinuxstudio.github.io/ArchLinuxTutorial/res/v2ray-4.44.0-1-x86_64.pkg.tar.zst Its version is 4.44.0

And v2raya works just fine!

### Steps to reproduce

Freshly install an archlinux system
install v2ray via 'pacman -S v2ray'
install v2raya via yay or the newest release package
Get some node and try to connect

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```

 You can also paste the log that comes from web administration page

```shell
# Paste running logs here

2022/11/11 18:26:22.285  [I] [io.go:428]  [Warning] [4186400480] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws:/***************:24710/):  > dial tcp ********** operation was canceled transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://************:24710/):  > dial tcp: operation was canceled] > common/retry: all retry attempts failed
2022/11/11 18:34:46.543  [I] [io.go:428]  flag provided but not defined: -config
2022/11/11 18:34:46.544  [I] [io.go:428]  Usage of /usr/bin/v2ray:
2022/11/11 18:34:46.545  [W] [asm_amd64.s:1571]  v2ray-core: exit status 2
2022/11/11 18:34:46.742  [E] [latency.go:66]  unexpected exiting: check the log for more information


```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

Just use the default config.

**Comment by Sharelter** [comment]
I temporarily ignored the upgrade of 'v2ray' package in pacman to get v2raya work temporarily.

**Comment by MarksonHon** [comment]
use `v2raya-git` instead of `v2raya`

**Comment by MarksonHon** [comment]
> @MarksonHon Hi.
> I have the same issue. I installed the `v2raya` following this link(s): https://v2raya.org/en/docs/prologue/installation/debian/
> 
> > V2Ray installation: https://github.com/v2fly/fhs-install-v2ray
> > Xray installation: [https://github.com/XTLS/Xray-insta](https://github.com/XTLS/Xray-install)
> 
> I downloaded and installed the `.deb` file. I see the same error as OP in the log:
> `flag provided but not defined: -config`
> What should I do? will installing through the mirror script solve this problem?

https://t.me/v2raya/1159
