### ISSUE TITLE
Add run scripts for other init scheme such as runit, s6 and dinit

### ISSUE THREAD

**Issue by yuandi42** [v2rayA/v2rayA#705]
### Is the feature related with existing problem?

Though systemd is de facto the standard init and service management scheme in Linux world. There are still distros using other init scheme ([runit](http://smarden.org/runit/index.html) in my case). But in the repo I can only find the service file for systemd. 

### Content of the feature

Since this project has no dependency related to systemd (or does it?), I do hope service file/ run scripts for other init scheme can be added.

**Comment by cubercsl** [comment]
@yuandi42 Our developers are not very familiar with other init systems, so we can not ship the scripts for other init. As far as I know, there are downstream distributions (such as gentoo, openwrt, ...) that write scripts for their init systems. If you are packaging for a  distribution with other init system and  want ship a service file, please feel free to submit a PR and add the scripts in install/universal directory.
