### ISSUE TITLE
docker 容器与主机时间（时区）不一致

### ISSUE THREAD

**Issue by Kicey** [v2rayA/v2rayA#706]
在 ubuntu 系统下，1.5.9 以 docker 方式运行的容器存在主机时间和容器时间不一致的情况，这会导致某些代理无法使用，解决这个问题也很简单，将主机的 /etc/localtime 拷贝到容器中即可。

**Comment by lhm518** [comment]
-e TZ=Asia/Shanghai
这样不行？

**Comment by Kicey** [comment]
> -e TZ=Asia/Shanghai 这样不行？

可以，这需要在容器启动时使用，在启动后可以通过复制时间文件到容器进行同步（linux，其他系统 echo 'Asia/Shanghai' >/etc/timezone‘ 类似的方式设置），更好的办法是在 Dockerfile 中设置时区。

**Comment by lhm518** [comment]
> 

--restart=always
我是再加这个

**Comment by AlleNPooh** [comment]
加了时区好像在日志里显示的时间还是不对啊。请问大家怎么解决的

**Comment by MarksonHon** [comment]
@AlleNPooh 映射 /etc/localetime

**Comment by AlleNPooh** [comment]
> /etc/localetime

我的底层系统是unraid，没有找到这个文件啊

**Comment by yuzhen1024** [comment]
> @AlleNPooh 映射 /etc/localetime

尝试过，没用。

**Comment by AlleNPooh** [comment]
有没有人解决了？

**Comment by MarksonHon** [comment]
TZ变量可以在2.2.4.5版本的Docker映像中使用了
