### ISSUE TITLE
connected but no IP change

### ISSUE THREAD

**Issue by Faarhad** [v2rayA/v2rayA#712]
1. What version of v2rayA are you using?
the latest
2. What approach of installation do you install V2rayA?
Vmess/ws
3. What is your operating system?
ubuntu 20

### Description
my service is running and it's connected to my server but my IP didn't change,
thanks for everyone's reply in advance.

**Comment by gitmoh2** [comment]
Did you figure this one out?

**Comment by MarksonHon** [comment]
https://t.me/v2raya

Join group and get help
