### ISSUE TITLE
出现异常上下行流量

### ISSUE THREAD

**Issue by dfmjndm** [v2rayA/v2rayA#713]
docker版本的v2raya，没有开启透明代理，出现非我操作的上下行流量
起因是宝塔看流量监控时发现有4M/4M的上行/下行流量，经过端口排查确定为v2raya的流量，但此时我没有任何进程在调用代理端口
这个情况出现十几分钟后机器负载跑到100%，然后死机，重启后过十几分钟再次出现这一情况
我不清楚是不是我的端口被别人使用了，http代理端口也没有帐号密码，感觉很不安全

**Comment by dfmjndm** [comment]
目前暂时关闭了外部访问

**Comment by lovefan-fan** [comment]
查到原因了吗，我也遇到了这样的情况

**Comment by dfmjndm** [comment]
就是被打了，端口特征明显，很多人扫

lovefan-fan ***@***.***> 于2024年4月2日周二 10:48写道：
