### ISSUE TITLE
反向代理支持

### ISSUE THREAD

**Issue by SuperCase135** [v2rayA/v2rayA#719]
希望增加对v2ray反向代理功能的支持，使外网可以通过VPS连接进局域网：

增加对reverse(bridges)字段和相关outbounds/routing rules的配置支持。

不确定在使用core-hook自定义v2ray-core配置时是否可添加或操作上述设置字段，并能与其他已有的inbounds/outbounds/routing rules完美共存。

![block_of_reverse-vmess cd11ba0c](https://user-images.githubusercontent.com/118732621/203472402-fafc7df2-941b-4ec0-b2d9-deb9bf66a945.png)

**Comment by mzz2017** [comment]
@SuperCase135 v2rayA的初衷是客户端，我们不会做大而全的core的所有功能，你可以考虑用core-hook自定义完成你的需求
