### ISSUE TITLE
hyper-v接管2017端口导致启动失败

### ISSUE THREAD

**Issue by bxz2311196368** [v2rayA/v2rayA#722]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
windows_x64_1.5.9.1698.1
2. 你通过什么方式安装v2rayA
手动
3. 你所使用的操作系统
Win11

### 描述问题：

hyper-v接管2017端口导致启动失败

一种解决方式：
[https://stackoverflow.com/a/54727281](https://stackoverflow.com/a/54727281)

希望能增加检测到hyper-v后切换成较大的端口号（目前测试是大约5000以上的端口可用），或者在文档中增加对hyper-v的提示。

**Comment by MarksonHon** [comment]
前者不会实现 后者暂时没人写 有兴趣可以PR
