### ISSUE TITLE
Mixed Port

### ISSUE THREAD

**Issue by fakhamatia** [v2rayA/v2rayA#726]
Please add mixed port for http and socks. Like Clash

**Comment by MarksonHon** [comment]
Please go to V2Ray to submit your needs, we are just a user front end.

**Comment by MarksonHon** [comment]
Please go to V2Ray to submit your needs, we are just a user front end.

**Comment by fakhamatia** [comment]
[https://github.com/v2fly/v2ray-core/discussions/2184#discussion-4611450](https://github.com/v2fly/v2ray-core/discussions/2184#discussion-4611450)
