### ISSUE TITLE
每天都要重新选择一下节点，否则就无法上网

### ISSUE THREAD

**Issue by 344108150** [v2rayA/v2rayA#728]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
   1.5.5
2. 你通过什么方式安装v2rayA
docker
3. 你所使用的操作系统
centos 7.5

### 描述问题

  每天都要重新选择一下节点，否则就无法上网

### 复现问题的步骤

不用复现 每天都这样

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```
 或者粘贴来自 Web 页面的日志
日志都是正常的
```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
没有日志，不好判断，有需要还是进群吧。
https://t.me/v2raya_zh/
