### ISSUE TITLE
"Invalid trojan format input" -> caused because I created users:passwords with trojan-panel

### ISSUE THREAD

**Issue by theguytestingstuff123** [v2rayA/v2rayA#73]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
Latest - Just updated.
2. What approach of installation do you install V2rayA?
command line
3. What is your operating system and CPU architecture?
Ubuntu ADM

### Description

I recently added Trojan-panel to my server which creates users through passwords
i.e 

trojan://user:password@host.com:443

When I try to add this server to v2raya, it tells me that it's not possible because the format is not okay

### Steps to reproduce

add trojan-panel to your server -> https://github.com/trojan-gfw/trojan-panel
Try to add this as a server to trojan -> trojan://user:password@host.com:443
### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 100
 
 # docker mode
 docker logs v2raya_backend
 ```
```shell
# Paste running logs here



```

**Comment by rmmendez** [comment]
I forgot to link: https://github.com/trojan-gfw/trojan-panel

**Comment by mzz2017** [comment]
I am not a trojan user actually so I don't know all popular formats.

Now v2rayA just support one format like `trojan://password@host:port#remarks`

Is the field `user` necessary? Or it can be omitted?

**Comment by mzz2017** [comment]
A temporary solution is that you can click `Create` and fill the form to add.

**Comment by theguytestingstuff123** [comment]
@mzz2017 

Yep. I tried manually but had got the same error. I really love V2Raya.
I cannot obmit the "user" field since there is a database that checks to make sure that the username matches the password given.

I also tried creating an empty user name "" but no luck.

Any chance that Trojan could accept the 
trojan://user:password@host:port#remarks

?

It is coming straight out of the Trojan repository so I imagine that it will only become more popular as more people start using the trojan-panel

**Comment by mzz2017** [comment]
I'll look into it in the few days.

**Comment by theguytestingstuff123** [comment]
@mzz2017 

So I figured out that since I left a default username on the database - "trojan" then I can still add
trojan://password@host:port#remarks

and I can still access the server.

It would be nice if I could do user though for my friends.

**Comment by mzz2017** [comment]
Yes, I'll look about the user field in latest trojan protocol standard.

**Comment by mzz2017** [comment]
Hello, it seems that client does not need to send `username` to server and the unique password can be mapped to this user.

https://github.com/trojan-gfw/trojan/blob/3d608e868c1d4fe5b07266d4b8bc5bfd01e9291d/src/core/authenticator.cpp#L49

**Comment by mzz2017** [comment]
I closed the issue due to no response for a long time. Feel free to reopen it if there is some progress. Thank you!
