### ISSUE TITLE
不走代理的地址要怎么写到v2rayA中？

### ISSUE THREAD

**Issue by lhm518** [v2rayA/v2rayA#732]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
mzz2017 / v2rayA
2. 你通过什么方式安装v2rayA
docker
3. 你所使用的操作系统
centos7.9 2009

### 描述问题：

做的内网代理，有些网站我不想它走代理，例如https://p4psearch.1688.com/ 、183.47.99.22,14.116.241.17
我要怎么操作把这些我不想走代理或一定要走代理的写到v2rayA中？？
### v2rayA运行日志（Optional）：
无
 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by huangz986** [comment]
改入站不好弄，可使用RoutingA分流走direct。
另外，一般浏览器代理设置也可以添加例外规则。

**Comment by lhm518** [comment]
> 改入站不好弄，可使用RoutingA分流走direct。另外 ，一般浏览器代理设置也可以添加实例外部规则。

因为是docker，用的是哪个文件呢？

**Comment by lhm518** [comment]
> 改入站不好弄，可使用RoutingA分流走direct。 另外，一般浏览器代理设置也可以添加例外规则。

找到了，我好好研究

**Comment by dreamfrog7** [comment]
> > 改入站不好弄，可使用RoutingA分流走direct。 另外，一般浏览器代理设置也可以添加例外规则。
> 
> 找到了，我好好研究

能否告诉下如何让部分网站不走代理吗？？

**Comment by huangz986** [comment]
> > > 改入站不好弄，可使用RoutingA分流走direct。 另外，一般浏览器代理设置也可以添加例外规则。
> > 
> > 
> > 找到了，我好好研究
> 
> 能否告诉下如何让部分网站不走代理吗？？

V2rayA的web ui ->设置 ->规则端口的分流模式，选择"RoutingA"，右边就会出现"配置“按钮，点进去有模板，也可以查看帮助文档。然后查看设置界面的"地址与端口“，代理走带分流规则的端口就可以了。

**Comment by dreamfrog7** [comment]
> > > > 改入站不好弄，可使用RoutingA分流走direct。 另外，一般浏览器代理设置也可以添加例外规则。
> > > 
> > > 
> > > 找到了，我好好研究
> > 
> > 
> > 能否告诉下如何让部分网站不走代理吗？？
> 
> V2rayA的web ui ->设置 ->规则端口的分流模式，选择"RoutingA"，右边就会出现"配置“按钮，点进去有模板，也可以查看帮助文档。然后查看设置界面的"地址与端口“，代理走带分流规则的端口就可以了。

好的，非常感谢您的回复，祝工作愉快
