### ISSUE TITLE
系统重启后第一次重启报错：open /run/user/0/v2raya/LoyalsoldierSite.dat: no such file or directory

### ISSUE THREAD

**Issue by yylzcom** [v2rayA/v2rayA#740]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
v2rayA服务端正在运行，Version: 1.5.9.1698.1

2. What approach of installation do you install V2rayA?
dpkg -i installer_debian_amd64_1.5.9.1698.1.deb

4. What is your operating system?
Ubuntu 22.04.1 LTS 

### Description

重启后第一次连接， 会出现下列错误
infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: ext:LoyalsoldierSite.dat:gfw > infra/conf/rule: failed to load external geosite: gfw from LoyalsoldierSite.dat > infra/conf/geodata/standard: failed to open file: LoyalsoldierSite.dat > 

### Steps to reproduce

1. 安装
2. 设置 - 启用:分流规则与规则端口所选模式一致 - "规则端口的分流模式"选RoutingA - 点击“配置”
3. 添加规则： domain(ext:"LoyalsoldierSite.dat:gfw", ext:"LoyalsoldierSite.dat:greatfire")->proxy
4.  去掉这条规则后可以启动，再把这规则添加回去一切正常
 
### Logs：
2022/12/10 08:18:42.797 [A] [main.go:27] V2Ray binary is /usr/local/bin/v2ray
2022/12/10 08:18:42.798 [A] [main.go:27] V2Ray asset directory is /run/user/0/v2raya
2022/12/10 08:18:42.798 [A] [main.go:27] v2rayA working directory is /
2022/12/10 08:18:42.798 [A] [main.go:27] v2rayA configuration directory is /etc/v2raya
2022/12/10 08:18:42.798 [A] [main.go:27] Golang: go1.18.4
2022/12/10 08:18:42.798 [A] [main.go:27] OS: linux
2022/12/10 08:18:42.798 [A] [main.go:27] Arch: amd64
2022/12/10 08:18:42.798 [A] [main.go:27] Lite: false
2022/12/10 08:18:42.798 [A] [main.go:27] Version: 1.5.9.1698.1
2022/12/10 08:18:42.798 [A] [main.go:27] Starting...
2022/12/10 08:18:42.928 [I] [io.go:428] V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/amd64)
2022/12/10 08:18:42.928 [I] [io.go:428] A unified platform for anti-censorship.
2022/12/10 08:18:42.930 [I] [io.go:428] [Info] main/jsonem: Reading config: /etc/v2raya/config.json
2022/12/10 08:18:43.055 [I] [io.go:428] main: failed to read config files: [/etc/v2raya/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: ext:LoyalsoldierSite.dat:gfw > infra/conf/rule: failed to load external geosite: gfw from LoyalsoldierSite.dat > infra/conf/geodata/standard: failed to open file: LoyalsoldierSite.dat > open /run/user/0/v2raya/LoyalsoldierSite.dat: no such file or directory
2022/12/10 08:18:43.212 [W] [asm_amd64.s:1571] v2ray-core: exit status 23

 You can also paste the log that comes from web administration page

### v2rayA setting and related screenshot
![image](https://user-images.githubusercontent.com/5056797/206820123-74ac771b-e06b-4199-b84c-2f97f85ec9db.png)
![image](https://user-images.githubusercontent.com/5056797/206820138-b195a3ec-38a8-43f8-897b-600847bdb93c.png)

**Comment by MarksonHon** [comment]
你需要先更新gfwlist

**Comment by mzz2017** [comment]
@yylzcom 设置面板右上角“更新”

**Comment by yylzcom** [comment]
@mzz2017 
**目前我遇到的窘境**
- 每次开机都因为gfw列表无法更新和下载，导致启动失败；但是此时系统代理又已经生效，导致所有网站都无法打开
- 需要手动切换成“绕过大陆模式”才能启动，更新GFW列，表然后再修改回我所需的模式，


**能否设计成**
1. GFW列表这种需要更新的，可以设置一个备用目录，使用之前已经下载/缓存的文件，**确保能正常启动**
2. 启动之后，再对需要更新的文件进行更新替换

**Comment by yylzcom** [comment]
如果有朋友可能会遇到的
1. 更新到2.0.1版本之后问题解决
2. 手动下载 LoyalsoldierSite.dat 放到 /usr/local/share/v2ray/ 目录下
