### ISSUE TITLE
没有“局域网共享”选项

### ISSUE THREAD

**Issue by adsian** [v2rayA/v2rayA#741]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.0-homebrew

3. 你通过什么方式安装v2rayA
homebrew

5. 你所使用的操作系统
maos

### 描述问题：

![image](https://user-images.githubusercontent.com/34738478/206866523-a1a72be7-6765-4383-aa88-87e76a3bd376.png)

如果是需要为局域网中的其他机器提供代理，请在设置中打开“局域网共享”，并检查防火墙开放情况。

![image](https://user-images.githubusercontent.com/34738478/206866665-e4bd1ca1-3a79-455f-93e9-4a8b3d9c48e0.png)

实际设置没有"局域网共享"选项,  这是什么原因?

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@adsian 这个选项已经分割成两个选项了，大概就在那个位置

**Comment by MarksonHon** [comment]
截图没更新而已，端口分享开起来就行。

**Comment by naokicc** [comment]
> @adsian 这个选项已经分割成两个选项了，大概就在那个位置

大佬我想咨询下“开启端口共享”图标为黄色还是白色时是开启了共享的啊🤣

**Comment by adsian** [comment]
黄色开启共享

**Comment by eonun** [comment]
这个坑着实没想到，找半天怎么改成局域网共享， 看到字了没想到去点一下以为已经有了，然后去找配置文件看怎么改成0.0.0.0的，没想到页面设置上就点一下的事
