### ISSUE TITLE
1.5版本apt升级2.0版本之后，未自动更新v2ray-core，导致程序无法运行

### ISSUE THREAD

**Issue by shenzhui007** [v2rayA/v2rayA#742]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.0
2. 你通过什么方式安装v2rayA
apt
3. 你所使用的操作系统
Debian

### 描述问题：

如题，通过apt升级2.0版本之后，未自动更新v2ray-core到v5版本，导致程序无法运行。
我也不知道这算不算问题，因为之前是用脚本安装的，没有手动更新过core。
也许在首页标注下更新v2版本前要手动更新core？或者优化下升级方式。

**Comment by shenzhui007** [comment]
本问题可随时关闭，就当给大家提个醒吧。

**Comment by Seele0oO** [comment]
在ArchLinux系统上，v2ray版本为5.1.0-2,
升级v2raya之后也无法正常运行。

**Comment by mzz2017** [comment]
@Seele0oO 什么是无法正常运行，systemctl restart v2raya 了吗

**Comment by Seele0oO** [comment]
> @Seele0oO 什么是无法正常运行，systemctl restart v2raya 了吗

运行后没问题了。
订阅链接被清空，重新加入后恢复网络连接。

**Comment by gbsadmin** [comment]
别忘了重启 systemctl restart v2raya

**Comment by 1996wu** [comment]
同样manjaro系统上，升级v2raya到2.0.0-1后，无法正常使用，提示"检测到v2ray-core的版本并非v5,请使用v5版本或将v2rayA 降级至v1.5"。v2ray版本为5.1.0-2，重启v2raya服务后也没办法正使用。

**Comment by vincentyzhj** [comment]
我是通过docker升级的，运行后不能正常使用，又降级回去

**Comment by mzz2017** [comment]
@vincentyzhj 抱歉，我无法复现你的问题

**Comment by W-weiluo** [comment]
alpine里 升级2.0 init.d文件里v2raya的系统文件需要加指定内核命令command_args=" --v2ray-bin=/usr/local/bin/v2ray"

**Comment by gdoudeng** [comment]
我也遇到这问题了。。。。

**Comment by gdoudeng** [comment]
我是mac的 旧的启动文件还在 没改 导致重启电脑后有问题
![image](https://user-images.githubusercontent.com/34932391/207752193-ecc3e7a3-2b84-41e3-979c-d9deda8b85e1.png)

**Comment by gdoudeng** [comment]
![image](https://user-images.githubusercontent.com/34932391/207752443-1518bf49-09ec-45bb-8c1f-8605ba0b6ba8.png)
删掉旧的重启解决问题

**Comment by Gr-1m** [comment]
哪位老哥解决这个问题了吗，或者说降级怎么降，求教学

**Comment by Gr-1m** [comment]
> 哪位老哥解决这个问题了吗，或者说降级怎么降，求教学

debian-amd64的系统

**Comment by kicurry** [comment]
ArchLinux系统，碰到该报错的可以先检查下环境变量中是否存在多个v2ray不知道什么软件在/usr/local/bin下安装了一个4.44.0版本的v2ray，v2raya首先匹配到它导致报上述错误，将其改为pacman安装的v2ray可解决问题

**Comment by MarksonHon** [comment]
> ![image](https://user-images.githubusercontent.com/34932391/207752443-1518bf49-09ec-45bb-8c1f-8605ba0b6ba8.png) 删掉旧的重启解决问题

你这是手动写过服务文件，homebrew生成的文件不长这样，都是homebrew开头的

**Comment by shenzhui007** [comment]
> > 哪位老哥解决这个问题了吗，或者说降级怎么降，求教学
> 
> debian-amd64的系统

去v2fly的项目底下，下载最新的v2ray-core，然后替换掉自己电脑上/usr/local/bin下的v2ray执行文件即可。

**Comment by Gr-1m** [comment]
> > 哪位老哥解决这个问题了吗，或者说降级怎么降，求教学
> 
> debian-amd64的系统

感谢，已经解决，十分感谢

**Comment by x1982** [comment]
docker pull mzz2017/v2raya 后，没有任何改观，还是“v2rayA服务端正在运行，Version: 1.5.5. 检测到新版本: 2.0.1”，如何升级
