### ISSUE TITLE
xray support dropped?

### ISSUE THREAD

**Issue by donnyxray** [v2rayA/v2rayA#743]
Please re-consider support for xray. Its new XTLS Vision is proving to be much better at avoiding blocking in China than anything v2fly can offer. 

Xray is also easier to install on platforms like OpenWRT, due to them providing official packages where v2fly does not.

**Comment by Ling128** [comment]
Agreed.

**Comment by 1715173329** [comment]
I have added v2fly package to official openwrt already, it's available on 22.03+

If you wanna use it with xray-core, just keep at master branch.

**Comment by iopq** [comment]
I need xray support for UDP forwarding

**Comment by brucejuz** [comment]
please don't drop the support to xray, thanks!

**Comment by brucejuz** [comment]
I have to downgrade to the 1.5 version in order to use xray

**Comment by kmy-4Q** [comment]
> 我必须降级到 1.5 版本才能使用 xray

不支持xray确实理解不了出于什么原因。

**Comment by MarksonHon** [comment]
v2ray 第五代的配置格式有变更，所以不太可能同时支持 Xray 与 v2ray 了，如果有人有兴趣，那么可以将 Master 分支复刻出去继续维护，甚至可以专门搭配 Xray 使用。
The configuration format of the fifth generation of v2ray has changed, so it is unlikely to support Xray and v2ray at the same time. If anyone is interested, you can fork the Master branch and continue to maintain it, even use it specifically with Xray.

**Comment by iopq** [comment]
> v2ray 第五代的配置格式有变更，所以不太可能同时支持 Xray 与 v2ray 了，如果有人有兴趣，那么可以将 Master 分支复刻出去继续维护，甚至可以专门搭配 Xray 使用。 The configuration format of the fifth generation of v2ray has changed, so it is unlikely to support Xray and v2ray at the same time. If anyone is interested, you can fork the Master branch and continue to maintain it, even use it specifically with Xray.

someone already did it

https://github.com/xbclub/xraya
