### ISSUE TITLE
Downloading missing geoip.dat and geosite.dat!!!

### ISSUE THREAD

**Issue by shuoros** [v2rayA/v2rayA#744]
### Version, approach of installation, operating system

1. What version of v2rayA are you using? 2.0.0

2. What approach of installation do you install V2rayA? sudo snap install v2raya

3. What is your operating system? Ubuntu 22.04.1 LTS

### Description
Showing this message on: http://localhost:2017/
```
Downloading missing geoip.dat and geosite.dat; refresh the page later.
正在下载缺失的 geoip.dat 和 geosite.dat，请稍后刷新页面。
```

### Logs：

-- No entries --

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by madjxatw** [comment]
Confirmed on Fedora 37 with 2.0.1 release.  Except for geoip.dat and geosite.dat, I got a message stating like "[latency.go:66] not found".

**Comment by Shahin-rmz** [comment]
Same problem here.
what should I download?
thanks

**Comment by lNATl** [comment]
> Same problem here. what should I download? thanks

`curl -Ls https://install.direct/go.sh | bash`     
ERROR: This script has been DISCARDED, please switch to fhs-install-v2ray project.
HOW TO USE: https://github.com/v2fly/fhs-install-v2ray
TO MIGRATE: https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this

### Install and update V2Ray 
`bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)`

### Install the latest release of geoip.dat and geosite.dat 
`bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-dat-release.sh)`

**Comment by amanjuman** [comment]
For OpenWRT use
wget -O /usr/share/v2ray/geoip.dat https://github.com/v2fly/geoip/releases/latest/download/geoip.dat
wget -O /usr/share/v2ray/geosite.dat https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat

**Comment by Valkierja** [comment]
FYI maybe in latest version you need download into  /usr/share/xray

**Comment by MichaelUray** [comment]
> FYI maybe in latest version you need download into /usr/share/xray

This is correct, for OpenWrt 23.05.0 you have to run

```
wget -O /usr/share/xray/geoip.dat https://github.com/v2fly/geoip/releases/latest/download/geoip.dat
wget -O /usr/share/xray/geosite.dat https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
```

**Comment by q2333gh** [comment]
> For OpenWRT use wget -O /usr/share/v2ray/geoip.dat https://github.com/v2fly/geoip/releases/latest/download/geoip.dat wget -O /usr/share/v2ray/geosite.dat https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat

我把这个手动下载复制进去了.给了777权限并重启openwrt.还是提示missing

**Comment by XuecWu** [comment]
好不容易弄到这里，又不行了，我真是醉了
