### ISSUE TITLE
怎么设置可以让docker指定的bridge容器走代理，其他全部直连

### ISSUE THREAD

**Issue by aefa6** [v2rayA/v2rayA#745]
怎么设置可以让docker指定的bridge容器走代理，其他全部直连。（或者所有host容器走直连也可）。
现在的问题是有一个bridge的容器我需要走代理，有一个host容器需要走直连，其他我都无所谓。请教下怎么设定才可以，谢谢！
version2.00

**Comment by aefa6** [comment]
重提了

**Comment by dian-yu-luo** [comment]
在哪呢,没找着啊
