### ISSUE TITLE
能否添加一个切换全局代理的快捷按钮

### ISSUE THREAD

**Issue by junknet** [v2rayA/v2rayA#75]
因经常切换全局代理，有点麻烦....
希望大佬能在Web面板某处弄一个快捷的切换按钮 ～～

**Comment by mzz2017** [comment]
可以是可以……问题是设计上需要一个调整

你是什么原因需要频繁切换呢，路由规则可以帮助你吗

**Comment by mzz2017** [comment]
如果需要，可以新增一个bash脚本迅速对v2raya后端进行调整

只需以下两步：
1. 修改/etc/v2ray/v2raya.json透明代理相关内容
2. systemctl restart v2raya

docker模式操作类似
