### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by a578044594** [v2rayA/v2rayA#752]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.1
2. 你通过什么方式安装v2rayA
arch yay
3. 你所使用的操作系统
linux

### 描述问题：

go: downloading github.com/klauspost/cpuid v1.2.3
/home/deck/go/pkg/mod/go4.org/netipx@v0.0.0-20220812043211-3cc044ffd68d/ipset.go:9:2: package net/netip is not in GOROOT (/usr/lib/go/src/net/netip)
==> ERROR: A failure occurred in build().
    Aborting...

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
不会编译就装 v2raya-bin
