### ISSUE TITLE
openwrt 透明代理 tproxy 方式 lan 口下不生效

### ISSUE THREAD

**Issue by aeeq** [v2rayA/v2rayA#754]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.9.1698.1
2. 你通过什么方式安装v2rayA
opkg
3. 你所使用的操作系统
openwrt

### 描述问题：

openwrt 透明代理 tproxy 方式 lan 口下不生效,路由器本机可以

本机有log 产生，lan口下不产生

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![图片](https://user-images.githubusercontent.com/8926331/208050050-733f73dc-64c7-490e-99d2-c8067ffbff5a.png)

**Comment by MarksonHon** [comment]
进群聊：
<https://t.me/v2raya_zh>
