### ISSUE TITLE
能不能出一个不依赖v2ray/xray安装脚本的版本？

### ISSUE THREAD

**Issue by odup** [v2rayA/v2rayA#755]
### 您想提出的功能特性是否和现有问题相关？

否

### 功能特性内容

我真的很崩溃，对于网络不是太好的国内网络，xray的官方安装脚本死活安装不上，用你们的镜像脚本也不行，因为脚本里面也请求了github，我还没富强呢，先让访问一个国外网站，肯定会有影响，太不友好了。
能不能做一个，只需要把v2ray/xray的核心压缩包下载下来，然后解压到指定地方，v2rayA就能识别使用的版本？跪求。

**Comment by odup** [comment]
对于v2rayA我不用担心，只需要把https://github.com/v2rayA/v2rayA/releases包下载下载安装就行了。
卡就卡在核心这里，我相信这不是一个人的需求。

**Comment by MarksonHon** [comment]
看不懂你的逻辑
如果是想手动安装核心
那你把二进制放 /usr/local/bin 就是了

**Comment by odup** [comment]
> 

这个是我手动安装参考的教程：https://www.rultr.com/tutorials/vps/5587.html
你这个做法，我试过了不行，v2rayA并不能识别。
我的意思是用脚本因为网络问题安装不上核心，那么能不能出个手动安装的教程或者版本。
就像我要用v2rayA富强，还没有安装成功使用呢，却先让访问一个需要富强才能流畅访问的网站，没有鸡怎么有的蛋呢。

**Comment by Zx1999** [comment]
> > 
> 
> 这个是我手动安装参考的教程：https://www.rultr.com/tutorials/vps/5587.html 你这个做法，我试过了不行，v2rayA并不能识别。 我的意思是用脚本因为网络问题安装不上核心，那么能不能出个手动安装的教程或者版本。 就像我要用v2rayA富强，还没有安装成功使用呢，却先让访问一个需要富强才能流畅访问的网站，没有鸡怎么有的蛋呢。

请问后来有解决吗？

**Comment by mzz2017** [comment]
@Zx1999 没规定必须用脚本装，只要你能装上就行
