### ISSUE TITLE
差不多每个24小时 就会自动停止，要重新手动启动才行

### ISSUE THREAD

**Issue by 344108150** [v2rayA/v2rayA#759]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
2.0.0
2. What approach of installation do you install V2rayA?
docker
3. What is your operating system?
centos 7.5

### Description

差不多每个24小时 就会自动停止，要重新手动启动才行，请问这是什么原因啊 ？
### Steps to reproduce

<img width="1802" alt="image" src="https://user-images.githubusercontent.com/90685197/208800596-cfe632cc-31d1-484a-9ffa-8d02b92dbde4.png">

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```

 You can also paste the log that comes from web administration page

```shell
# Paste running logs here
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/90685197/208800370-57b1556b-6d4a-4400-becd-45d9da76d100.png">



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by 344108150** [comment]
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/90685197/208811657-7c153dcc-81c8-4f82-8164-6b23b1ebfa87.png">

**Comment by mzz2017** [comment]
@344108150 看起来是 oom 了，内存占用过大被 kill 了

**Comment by 344108150** [comment]
> 

估计是的 之前不知道 看了别人的 issues  再看我的内存 也在乎乎的长  我再观察观察 估计是这个原因

**Comment by Xinyu-Wu-0000** [comment]
https://unix.stackexchange.com/questions/449210/systemd-memory-limit-not-working-example

在 `/etc/systemd/system/v2raya.service` 中设置一个内存上限，达到上限后重启服务

**Comment by MarksonHon** [comment]
https://t.me/v2raya_zh
进群聊
