### ISSUE TITLE
求出一个手动安装核心并能识别的教程

### ISSUE THREAD

**Issue by odup** [v2rayA/v2rayA#762]
### 您想提出的功能特性是否和现有问题相关？

这个是我手动安装参考的教程：https://www.rultr.com/tutorials/vps/5587.html
这个做法，我试过了不行，v2rayA并不能识别。
用脚本会因为网络问题安装不上核心，那么能不能出个手动安装的教程或者版本。
就像我要用v2rayA富强，还没有安装成功使用呢，却先让访问一个需要富强才能流畅访问的网站github，没有鸡怎么有的蛋呢。

### 功能特性内容

出一个教用户怎么手动安装v2ray或xray会被识别的教程。

**Comment by MarksonHon** [comment]
下载核心，解压，把v2ray放在/usr/local/bin/即可。

**Comment by mzz2017** [comment]
2.0已经移除了xray支持，请使用v2ray，或降级v2rayA到1.5.1698.1
