### ISSUE TITLE
这个MarksonHon，你TM会不会啊，光会关闭Issues

### ISSUE THREAD

**Issue by odup** [v2rayA/v2rayA#763]
### 您想提出的功能特性是否和现有问题相关？

只会一句话：下载核心，解压，把v2ray放在/usr/local/bin/即可。
你TM试过没有啊，v2rayA并不能识别，会报提示。关闭Issues怪积极。
好好看了吗，发的链接 https://www.rultr.com/tutorials/vps/5587.html 不比你一句话安装的仔细啊。
跟个机器人一样，也不求你能解决啥东西了。

### 功能特性内容

解决 @MarksonHon 这个B，不实践瞎TM关闭Issues

**Comment by MarksonHon** [comment]
你想想，一百点多个issue我不关，偏偏就关你的，你不想想你自己是不是有什么大问题么？😆
还解决我，有本事你报警去，看下警察是来找我还是先罚款你个想翻墙的
