### ISSUE TITLE
Proxy 10.0.0.0/8

### ISSUE THREAD

**Issue by ehsanm6830** [v2rayA/v2rayA#764]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
Version: 2.0.1
2. What approach of installation do you install V2rayA?
Install from apt-source or AUR
3. What is your operating system?
Ubuntu 20.04

### Description

I want to proxy 10.0.0.0/8 but not working!
v2raya proxy for exmaple 111.0.0.0/8 range without any problem but v2raya not proxy 10.0.0.0/8 !

blew exmaple of RoutingA:
```
default: direct
ip(geoip:cn)->proxy
ip(111.0.0.0/8)->proxy
ip(10.0.0.0/8)->proxy
```

**Comment by MarksonHon** [comment]
This is expected behavior, because this IP range belongs to reserved private addresses, so it is not proxied by default.

**Comment by ehsanm6830** [comment]
i write RoutingA rules but not routing 10.0.0.0/8.
i need to proxy this private range to my proxy.what shoud i do?

**Comment by MarksonHon** [comment]
If you want to proxy, you need to use a transparent hook to delete the corresponding firewall rules. For details, please refer to the document:

https://v2raya.org/docs/manual/hook/

You can join https://t.me/v2raya , this issue closed.
