### ISSUE TITLE
rootless on mac 也可以支持切换系统代理

### ISSUE THREAD

**Issue by dusmart** [v2rayA/v2rayA#766]
### 功能特性内容
目前 2.0.1 版本暂时不支持在 Mac 中设置透明代理，但是有一些可以妥协的解决方案。

比如 V2rayX 的[方案](https://github.com/Cenmrev/V2RayX/blob/3551c3eb49/v2rayx_sysconf/main.m)，通过移植该脚本过来，将相关脚本的权限提升为root并添加标志位+s来解决运行时的权限问题，仅需在[安装时](https://github.com/Cenmrev/V2RayX/blob/3551c3eb49/V2RayX/install_helper.sh)使用一次root权限即可。

**Comment by MarksonHon** [comment]
v2rayA调用系统自带的`networksetup`来设置系统代理，本身是不需要root权限的，但是需要v2rayA本身以当前用户权限运行。

**Comment by dusmart** [comment]
> v2rayA调用系统自带的`networksetup`来设置系统代理，本身是不需要root权限的，但是需要v2rayA本身以当前用户权限运行。

我在 mac 上试了试 `networksetup -setwebproxy "Wi-Fi" 127.0.0.1 8003`
它提示 ** Error: Command requires admin privileges.

看起来还是需要一定的 root 权限的，而 V2rayX 通过设置二进制文件的特殊权限位 +s，可以向用户只在安装时索取一次 root 权限，而后的每一次切换都无需 root 权限。

**Comment by MarksonHon** [comment]
@dusmart 运行`groups`命令看下你的用户组，我这边是这样的：

staff everyone localaccounts _appserverusr admin _appserveradm _lpadmin _appstore _lpoperator _developer _analyticsusers com.apple.access_ftp com.apple.access_screensharing com.apple.access_ssh com.apple.access_remote_ae com.apple.sharepoint.group.1

**Comment by dusmart** [comment]
那看起来好像只有我有这个问题。
我自己创建了一个 root 用户，把自己的用户单独出来撤销了 root 权限。

staff everyone localaccounts com.apple.access_ssh com.apple.sharepoint.group.1 com.apple.sharepoint.group.3 _lpoperator com.apple.sharepoint.group.4 com.apple.sharepoint.group.2
