### ISSUE TITLE
Docker Portainer Install login issues

### ISSUE THREAD

**Issue by mookrhodan** [v2rayA/v2rayA#767]
I managed to properly install v2raya v 2.0.1 on docker portainer on Rpi (all latest versions) - initially everything worked but then i misplaced pw for login.... 

Followed instructions from quick install to use sudo v2raya --reset-password, failed with error v2raya not found.

Then i run "docker logs v2raya" with the result that none of the directories listed in logs actually exist on my Rpi
V2ray binary is /usr/bin/v2ray - doesnt exist
V2Ray assets /run/user/0/v2raya - doesnt exist

Removed v2raya from portainer and re-installed, still old password that I didnt save....

Why are there directories in log that dont exist and how to I reset my login password?

Cheers

**Comment by mzz2017** [comment]
@mookrhodan Firstly, stop the container: docker stop <container name>. Secondly, run another container to modify the password: docker run -it --volumes-from <container name we just stopped> mzz2017/v2raya --reset-password
