### ISSUE TITLE
docker用最新镜像安装的，可是每次登录都提示用的1.5.5，最新版为2.0.1

### ISSUE THREAD

**Issue by Mrvivi** [v2rayA/v2rayA#768]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
 我用1.5.5版本

2. 你通过什么方式安装v2rayA
 docker 安装的

docker用最新镜像安装的，可是每次登录都提示用的1.5.5，最新版为2.0.1
重新安装也是这样的，不知道怎么样才能更新成功

<img width="440" alt="Snipaste_2022-12-29_16-02-31" src="https://user-images.githubusercontent.com/49402255/209979595-4734a3cb-f4db-4e70-9611-0912ecccd578.png">

**Comment by dreamfrog7** [comment]
我也有这个提示，大佬你能分享给局域网的设备使用代理吗？

**Comment by Mrvivi** [comment]
我只需要安装v2到这个linux机器里面 ,局域网的设备使用v2不需要这么麻烦啊 ,都有各自的客户端吧 ！

**Comment by MarksonHon** [comment]
贴出你的安装命令

**Comment by Mrvivi** [comment]
# run v2raya
docker run -d \
  --restart=always \
  --privileged \
  --network=host \
  --name v2raya \
  -e V2RAYA_ADDRESS=0.0.0.0:2017 \
  -v /lib/modules:/lib/modules:ro \
  -v /etc/resolv.conf:/etc/resolv.conf \
  -v /etc/v2raya:/etc/v2raya \
  mzz2017/v2raya
