### ISSUE TITLE
如何查看域名命中的分流规则？

### ISSUE THREAD

**Issue by HaoTian22** [v2rayA/v2rayA#769]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.1
2. 你通过什么方式安装v2rayA
AUR
3. 你所使用的操作系统
Archlinux

### 描述问题：

如何查看域名命中了哪个RouteA的规则？看log都是只显示IP地址，很难反推出域名
而RouteA基本上都是写的域名规则，很少写IP规则
如果看到哪个网站没命中正确的话就可以及时修改RouteA，避免走错分流
（比如微软有的域名是国内快，有的是国外快，我看到域名走了代理还是直连，我就知道我需要在RouteA加一个规则了）

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![image](https://user-images.githubusercontent.com/48882584/210030424-b3fc2ef0-e799-4276-a3c2-801835f8e1a5.png)

**Comment by mzz2017** [comment]
@HaoTian22 透明代理不显示域名，你可以借助浏览器插件，如switchyOmega，通过http/socks5端口，这样log就会记录域名了

**Comment by HaoTian22** [comment]
好的，谢谢
