### ISSUE TITLE
通过docker方式部署了v2raya，请问可以更新版本吗？如何在线更新呢？

### ISSUE THREAD

**Issue by dreamfrog7** [v2rayA/v2rayA#772]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.1
2. 你通过什么方式安装v2rayA
docker
3. 你所使用的操作系统
群晖nas

### 描述问题：

在本地docker部署了v2raya后，通过浏览器127.0.0.1:2017访问后总提示新版本2.0，想问问可以更新吗？如何更新？

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by dreamfrog7** [comment]
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -c --run-once 容器名？

**Comment by MarksonHon** [comment]
@dreamfrog7 建议谷歌“如何更新Docker中的镜像”
Or Google "how to pull a new version image in Docker"

**Comment by MarksonHon** [comment]
实在不行建议你进群求助：https://t.me/v2raya_zh
