### ISSUE TITLE
v2raya 开启了端口分享，局域网内的手机，设置了代理还是无法连接

### ISSUE THREAD

**Issue by dreamfrog7** [v2rayA/v2rayA#774]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.1
2. 你通过什么方式安装v2rayA
docker
3. 你所使用的操作系统
群晖nas
### 描述问题：
v2raya 开启了端口分享，默认端口20170 （192.168.68.16）  同一局域网内的手机手动设置代理 192.168.68.16 端口 20170 和20171都尝试了，还是无法通过代理上网。。。

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
进群：<https://t.me/v2raya_zh>
