### ISSUE TITLE
每次自动开机启动就会提示failed to start v2ray-core: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature

### ISSUE THREAD

**Issue by cogitate3** [v2rayA/v2rayA#778]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
v2.0.1

2. What approach of installation do you install V2rayA?
winget

3. What is your operating system?
win10

### Description

开机自启后，手动点击启动，就提示：
failed to start v2ray-core: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```
 You can also paste the log that comes from web administration page

```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by MarksonHon** [comment]
可能需要刷新一下浏览器
