### ISSUE TITLE
support for more protocols (Vmess, Vless, etc) in routingA inbound rules 

### ISSUE THREAD

**Issue by Ali-Flt** [v2rayA/v2rayA#780]
### Content of the feature

Right now routingA supports only socks and http as inbounds. Could it be possible for inbounds to also support other protocols such as Vmess?

**Comment by MarksonHon** [comment]
We are NOT a server web UI but a **client**, I don't think VMess and VLESS are needed in routingA inbound.

**Comment by Ali-Flt** [comment]
I understand but since v2rayA is by far the neatest v2ray implementation I found (both UI and document wise) and if I understood correctly the same v2ray core could be used for both server and client side It's a shame not to have both server and client side support.
Thanks anyway

**Comment by mzz2017** [comment]
However, v2rayA is not designed as a server.  If you need additional configuration items, you can modify config.json through core hook. [See more (Chinese)](https://v2raya.org/docs/advanced-application/custom-extra-config/)
