### ISSUE TITLE
管理界面支持 TLS 访问

### ISSUE THREAD

**Issue by hhyhhy** [v2rayA/v2rayA#782]
### 您想提出的功能特性是否和现有问题相关？
查看文档，似乎只能通过代理的方式让 v2raya 的管理界面支持 TLS
[将 v2rayA 部署于前缀路径中](https://v2raya.org/docs/advanced-application/nginx-prefix-deploy/)

### 功能特性内容
v2raya 直接支持 TLS 相关配置，不需要配置代理。

**Comment by hhyhhy** [comment]
另外希望有一个纯净的登录界面，在登录之前隐藏所有的关键词。

**Comment by MarksonHon** [comment]
v2rayA绝大多数时候运行于没有公网环境下的计算机、网关或开发板中，这个功能不会支持，如果想要反向代理方便一点，你可以考虑搭配Caddy。
