### ISSUE TITLE
在登录之前隐藏所有的关键词

### ISSUE THREAD

**Issue by hhyhhy** [v2rayA/v2rayA#783]
### 您想提出的功能特性是否和现有问题相关？
现在的登录界面很漂亮，但是界面上有一些关键词容易触发主动探测。

### 功能特性内容
提供一个纯净的登录界面，在登录之前完全不返回特定的关键词。

**Comment by huanghaoyuanhhy** [comment]
需要监听0.0.0.0 ，场景是：多地多个管理员可以访问，所以 IP 白名单也有难度。

我考虑的办法是，走一层代理再走到 127.0.0.1，可以隐藏起来。

**Comment by hhyhhy** [comment]
场景是：多地多个管理员可以访问，所以导致需要监听 0.0.0.0 ，另外配置 IP 白名单也不太可能。

目前想到一个比较麻烦的办法是，先过一层代理做完验证再走到 v2raya，可以隐藏起来，但配起来和使用起来都比较麻烦。

**Comment by cubercsl** [comment]
@hhyhhy 考虑
nginx basic auth
cloudflare zerotrust

**Comment by MarksonHon** [comment]
那你装个Caddy代理下2017端口吧，顺便还可以加一把账号密码验证。
相关功能v2rayA不会实现，因为我们只是一个简约的客户端
