### ISSUE TITLE
webUI中部分元素无法显示

### ISSUE THREAD

**Issue by Wings-Fantasy** [v2rayA/v2rayA#784]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
Version: 2.0.1
2. 你通过什么方式安装v2rayA
AUR里的`v2raya-bin`
3. 你所使用的操作系统
Arch Linux

### 描述问题

webUI中部分元素无法显示，在旧版本中显示正常

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

https://i.328888.xyz/2023/01/06/kih4z.png
https://i.328888.xyz/2023/01/06/kVCaN.png

**Comment by MarksonHon** [comment]
你截图没上来

**Comment by Wings-Fantasy** [comment]
啊，我好像没说，我用的就是`v2raya-bin`这个包

**Comment by MarksonHon** [comment]
有些蜜汁，有需要就进群吧：
<https://t.me/v2raya_zh>
