### ISSUE TITLE
检测到 geosite.dat, geoip.dat 文件或 v2ray-core 可能未正确安装，请检查

### ISSUE THREAD

**Issue by durongze** [v2rayA/v2rayA#786]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

2. 你通过什么方式安装v2rayA

3. 你所使用的操作系统

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
未提供任何日志与信息，此issue关闭，有需要可以加群。
telegram搜索 @v2raya_zh

**Comment by durongze** [comment]
> 未提供任何日志与信息，此issue关闭，有需要可以加群。 telegram搜索 @v2raya_zh

那个问题我知道了，选择选项不是通过页面中每项前的checkbox，而是通过后的选择按钮选择选项。
