### ISSUE TITLE
程序菜单中应让用户选择是否使用特权运行v2rayA

### ISSUE THREAD

**Issue by jjjttwkr123** [v2rayA/v2rayA#790]
### Is the feature related with existing problem?

点击v2rayA.desktop无法启动v2rayA

### Content of the feature

两个.desktop文件，分别为sudo v2raya(特权)和 v2raya --lite(非特权)

**Comment by cubercsl** [comment]
`v2rayA.desktop` 只从浏览器打开对应地址，不负责启动服务。
