### ISSUE TITLE
适配cns代理

### ISSUE THREAD

**Issue by Jacobabc123** [v2rayA/v2rayA#793]
### 您想提出的功能特性是否和现有问题相关？

希望适配cns代理，它是一种很强大的代理

**Comment by MarksonHon** [comment]
CNS是个什么工具？

**Comment by Jacobabc123** [comment]
https://github.com/mmmdbybyd/CNS

https://github.com/mmmdbybyd/CLNC

请大佬查看

> CNS是个什么工具？

**Comment by cubercsl** [comment]
Due to open source license issues, at least one AGPL compliant client implementation is required, but the one you provided seems to contain only precompiled binaries.
