### ISSUE TITLE
检测到 v2ray-core 的版本并非 v5，请使用 v5 版本或将 v2rayA 降级至 v1.5

### ISSUE THREAD

**Issue by chatage** [v2rayA/v2rayA#794]
### 版本、安装方式、系统

1. v2rayA2.01

2. apt install v2raya

3. armbian x86 bullseye

检测到 v2ray-core 的版本并非 v5，请使用 v5 版本或将 v2rayA 降级至 v1.5

默认安装的v2ray core是稳定版4.3

需要安装v2ray core的新版本 5.0.1

使用以下方法更新v2ray core

#下载此指令码
curl -O https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
#执行
bash install-release.sh
#运行 V2ray
systemctl start v2ray
#置开机自启动 V2Ray
systemctl enable v2ray
#检查一下 V2ray 运行状态
systemctl status v2ray

**Comment by MarksonHon** [comment]
你试试不就知道了
