### ISSUE TITLE
请问 RoutingA 设置是否有保存到单独的文件中？

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [v2rayA/v2rayA#795]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

2. 你通过什么方式安装v2rayA

3. 你所使用的操作系统

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
你的issue不符合我们的模板规范，现在关闭。
有需要直接问的可以进群：
<https://t.me/v2raya_zh>
