### ISSUE TITLE
请问 RoutingA 设置是否有保存到单独的文件中？

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [v2rayA/v2rayA#796]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.1

2. 你通过什么方式安装v2rayA
deb包二进制安装

3. 你所使用的操作系统
ubuntu 22.04

### 描述问题：

请问 RoutingA 设置是否有保存到单独的文件中？ 如果没有能够新增此功能，将 RoutingA 保存在特定文件中，启动时从中加载设置。

**Comment by mzz2017** [comment]
@Xinyu-Wu-0000 小问题建议进群 https://t.me/v2raya_zh
