### ISSUE TITLE
Support SSH tunnel as a new connection

### ISSUE THREAD

**Issue by erfansahaf** [v2rayA/v2rayA#798]
### Is the feature related with existing problem?
No, it isn't.

### Content of the feature

I want to use the v2raya UI to set up an SSH tunnel (by a password or a private key). `v2raya` should keep an eye on this ssh tunnel and restart it when it gets interrupted. The UI must add the ability to define a new SSH proxy just like it supports SSR, for example.

**Comment by MarksonHon** [comment]
@erfansahaf Talk is cheap, show us your code
