### ISSUE TITLE
重启debian11后 透明代理的 开启ip转发 未生效

### ISSUE THREAD

**Issue by 757321061** [v2rayA/v2rayA#802]
### 版本、安装方式、系统
Debian11-PC
1. 你在使用什么版本的v2rayA
2.0.1
3. 你通过什么方式安装v2rayA
apt install v2raya
4. 你所使用的操作系统
 Debian11

### 描述问题

重启debian11后 透明代理的 开启ip转发 未生效，导致他作为网关别的设备无法ping别的网址。例如ping baidu.com
必须要去v2raya的后台 点开设置 点击 保存并应用 后马上就可以ping通baidu.com
### 复现问题的步骤

只要重启就必须去v2raya点开设置 点击保存并应用 后可恢复

希望修复这个问题让v2raya的debian系统重启后不用去v2raya去设置并保存开启ip转发

![111111](https://user-images.githubusercontent.com/49135603/213383867-a1c7380f-d5d4-42cd-b3fc-a2c8a816f003.png)

**Comment by 757321061** [comment]
https://user-images.githubusercontent.com/49135603/213386680-453aa02b-b537-4a44-b76c-52e056abbd11.mp4

**Comment by mzz2017** [comment]
@757321061 写 /etc/sysctl.conf:
net.ipv4.ip_forward = 1

**Comment by 757321061** [comment]
ok 解决了
