### ISSUE TITLE
导入订阅地址时出现错误“failed to resolve subscription address: Get "https://raw.githubusercontent.com/xxxxxx": dial tcp 0.0.0.0:443: connect: connection refused”

### ISSUE THREAD

**Issue by 38423258** [v2rayA/v2rayA#803]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

     Version: 1.5.7

2. 你通过什么方式安装v2rayA
    github下载deb包
 
3. 你所使用的操作系统
    ubuntu22.04

### 描述问题：
   v2ray-core版本是4.34
    
    导入订阅地址为"https://raw.githubusercontent.com/xxxx"时，出现
    “failed to resolve subscription address: Get "https://raw.githubusercontent.com/xxxxxx": dial tcp 0.0.0.0:443: connect: connection refused””

### v2rayA运行日志（Optional）：

2023/01/20 19:55:13.454 [A] [main.go:27] v2rayA working directory is /
2023/01/20 19:55:13.454 [A] [main.go:27] v2rayA configuration directory is /etc/v2raya
2023/01/20 19:55:13.454 [A] [main.go:27] Golang: go1.18
2023/01/20 19:55:13.454 [A] [main.go:27] OS: linux
2023/01/20 19:55:13.454 [A] [main.go:27] Arch: amd64
2023/01/20 19:55:13.454 [A] [main.go:27] Lite: false
2023/01/20 19:55:13.454 [A] [main.go:27] Version: 1.5.7
2023/01/20 19:55:13.454 [A] [main.go:27] Starting...
2023/01/20 19:55:13.454 [I] [main.go:28] the core was not running the last time v2rayA exited
2023/01/20 19:55:13.461 [A] [index.go:117] v2rayA is listening at http://127.0.0.1:2017
2023/01/20 19:55:13.461 [A] [index.go:117] v2rayA is listening at http://192.168.123.37:2017
2023/01/20 19:55:13.461 [A] [index.go:117] v2rayA is listening at http://[::1]:2017
2023/01/20 19:55:13.462 [A] [index.go:117] v2rayA is listening at http://[fe80::fafe:8957:3f79:e3a5]:2017
2023/01/20 19:55:28.709 [E] [connection.go:88] failed to start v2ray-core: failed: no server is selected. please select at least one server
2023/01/20 19:55:35.212 [E] [connection.go:88] failed to start v2ray-core: failed: no server is selected. please select at least one server
2023/01/20 19:55:44.621 [E] [connection.go:88] failed to start v2ray-core: failed: no server is selected. please select at least one server
2023/01/20 20:00:04.364 [E] [import.go:22] failed to resolve subscription address: Get "https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2": dial tcp 0.0.0.0:443: connect: connection refused

```

### v2rayA设置以及相关截图
![Screenshot from 2023-01-20 21-46-19](https://user-images.githubusercontent.com/30613114/213714640-4088fc08-1c41-49ae-8f75-6aa0df61f2dc.png)
![Screenshot from 2023-01-20 21-46-28](https://user-images.githubusercontent.com/30613114/213714660-c506b2e7-f229-4eae-88d4-ff8a5f72c2af.png)
![Screenshot from 2023-01-20 21-34-32](https://user-images.githubusercontent.com/30613114/213714672-5c88f807-67b9-426d-9383-2c6285dd7bcb.png)

**Comment by MarksonHon** [comment]
你的运营商或GFW污染了GitHub的一些地址，此问题与本软件无关。
