### ISSUE TITLE
issue with v2rayA as home network gateway: No ping but internet access is fine

### ISSUE THREAD

**Issue by Ali-Flt** [v2rayA/v2rayA#806]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
2.0.1
2. What approach of installation do you install V2rayA?
from Archlinux AUR repository
3. What is your operating system?
Archlinux

### Description

I'm using v2rayA as the gateway for my home network traffic. I did this by setting the IP address of my home server (192.168.1.115) as the default gateway in the router settings. I think I don't have any dns issue because on the clients websites open and domains resolve without any issue but I can't ping anything (8.8.8.8, google.com, any other website or ip) on the clients whereas I can ping everything on the server that is running v2rayA. 

What could possibly cause me not to be able to ping anywhere? Does v2rayA not support ICMP packets in transparent proxy mode?

![image](https://user-images.githubusercontent.com/60854595/213944515-12e25e4e-0e1e-432f-b305-ca420830200e.png)
![image](https://user-images.githubusercontent.com/60854595/213944530-836852f5-448e-4afa-aaeb-4ed7c6e3c94c.png)
![image](https://user-images.githubusercontent.com/60854595/213944537-8046e7f6-08fd-4cee-9e80-5a7a7a48b7c5.png)

**Comment by MarksonHon** [comment]
You should set allow ICMP redirect by editing sysctl configuration.
https://man.archlinux.org/man/icmp.7.en
v2rayA will not proxy any ICMP packets because it cannot be proxied by any socks-liked proxy tool.

**Comment by Ali-Flt** [comment]
```
net.ipv4.conf.all.accept_redirects = 1
net.ipv4.conf.default.accept_redirects = 1
net.ipv4.conf.all.secure_redirects = 1
net.ipv4.conf.default.secure_redirects = 1
net.ipv6.conf.all.accept_redirects = 1
net.ipv6.conf.default.accept_redirects = 1
``` 
Added these lines to sysctl config. Didn't work

**Comment by Ali-Flt** [comment]
It was cause of the iptables FORWARD Policy being DROP
```
$ iptables -A FORWARD -i enp0s25 -o enp0s25 -j ACCEPT
```
this did the trick
