### ISSUE TITLE
根据官网帮助文档 配置出错 xray 无法使用，并且报错。目前无力解决

### ISSUE THREAD

**Issue by bitxx** [v2rayA/v2rayA#807]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
apt install v2raya 安装的版本 2.0.1
2. 你通过什么方式安装v2rayA
apt install v2raya
3. 你所使用的操作系统
debian 11.6

### 描述问题

根据官网文档 安装了xray 然后无法使用。
https://v2raya.org/docs/manual/use-other-core/
https://v2raya.org/docs/manual/variable-argument/#systemd-%E7%AE%A1%E7%90%86%E7%9A%84-v2raya

![1](https://user-images.githubusercontent.com/45416520/215055188-aa552856-0b3a-4ac8-885b-7aa8f0e53933.jpg)

![2](https://user-images.githubusercontent.com/45416520/215055189-276457af-6092-48db-b0dc-2edb5ff1f176.jpg)
![3](https://user-images.githubusercontent.com/45416520/215055193-430e4967-e616-4489-9c68-c99765d7aeeb.jpg)

### v2rayA/v2ray运行日志：
2023/01/27 03:20:28.010 [E] [connection.go:88] failed to start v2ray-core: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:20:49.515 [E] [version.go:36] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 192.168.134.2:53: read udp 192.168.134.128:45726->192.168.134.2:53: i/o timeout
2023/01/27 03:21:32.377 [W] [context.go:165] PostConnection: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:21:32.377 [E] [connection.go:36] failed to connect: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:22:02.777 [E] [outbound.go:86] outbound "proxy" cannot be deleted
2023/01/27 03:22:05.661 [E] [connection.go:88] failed to start v2ray-core: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:22:12.908 [E] [connection.go:88] failed to start v2ray-core: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:22:13.372 [E] [connection.go:88] failed to start v2ray-core: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:22:13.541 [E] [connection.go:88] failed to start v2ray-core: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:22:13.701 [E] [connection.go:88] failed to start v2ray-core: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:22:14.547 [W] [context.go:165] PostConnection: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:22:14.548 [E] [connection.go:36] failed to connect: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:22:16.726 [W] [context.go:165] PostConnection: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:22:16.726 [E] [connection.go:36] failed to connect: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:22:18.819 [W] [context.go:165] PostConnection: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:22:18.819 [E] [connection.go:36] failed to connect: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:22:33.515 [E] [version.go:36] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 192.168.134.2:53: read udp 192.168.134.128:40479->192.168.134.2:53: i/o timeout
2023/01/27 03:22:56.787 [W] [context.go:165] PostConnection: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:22:56.787 [E] [connection.go:36] failed to connect: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:23:29.904 [E] [setting.go:51] cannot find GFWList files. update GFWList and try again
2023/01/27 03:23:35.731 [W] [context.go:165] PostConnection: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:23:35.731 [E] [connection.go:36] failed to connect: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 03:24:03.445 [E] [version.go:36] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 192.168.134.2:53: read udp 192.168.134.128:34482->192.168.134.2:53: i/o timeout
2023/01/27 03:24:43.475 [E] [gfwlist.go:12] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 192.168.134.2:53: read udp 192.168.134.128:38744->192.168.134.2:53: i/o timeout
2023/01/27 03:25:23.511 [E] [gfwlist.go:12] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 192.168.134.2:53: read udp 192.168.134.128:39548->192.168.134.2:53: i/o timeout
2023/01/27 03:26:03.542 [E] [gfwlist.go:12] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 192.168.134.2:53: read udp 192.168.134.128:38887->192.168.134.2:53: i/o timeout
2023/01/27 03:26:43.573 [E] [version.go:36] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 192.168.134.2:53: read udp 192.168.134.128:57780->192.168.134.2:53: i/o timeout
2023/01/27 03:27:23.609 [E] [gfwlist.go:12] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 192.168.134.2:53: read udp 192.168.134.128:36116->192.168.134.2:53: i/o timeout
2023/01/27 03:28:03.645 [E] [gfwlist.go:12] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 192.168.134.2:53: read udp 192.168.134.128:45069->192.168.134.2:53: i/o timeout
2023/01/27 03:28:43.672 [E] [gfwlist.go:12] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 192.168.134.2:53: read udp 192.168.134.128:60010->192.168.134.2:53: i/o timeout
2023/01/27 03:29:23.702 [E] [gfwlist.go:12] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 192.168.134.2:53: read udp 192.168.134.128:55256->192.168.134.2:53: i/o timeout
2023/01/27 03:30:03.737 [E] [gfwlist.go:12] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 192.168.134.2:53: read udp 192.168.134.128:38148->192.168.134.2:53: i/o timeout
2023/01/27 03:30:43.764 [E] [version.go:36] failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 192.168.134.2:53: read udp 192.168.134.128:58303->192.168.134.2:53: i/o timeout
2023/01/27 03:32:31.633 [E] [connection.go:88] failed to start v2ray-core: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 04:39:15.246 [W] [context.go:165] PostConnection: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature
2023/01/27 04:39:15.246 [E] [connection.go:36] failed to connect: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```
 或者粘贴来自 Web 页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by King-Of-Knights** [comment]
日志里面已经很清楚了啊：
`failed to connect: failed to connect: current version of v2rayA only support v2ray-core v5: v2fly/v2ray-core only feature`
最新版本的v2rayA不支持Xray了
