### ISSUE TITLE
希望增加免密码功能

### ISSUE THREAD

**Issue by XueqiangDong** [v2rayA/v2rayA#810]
### 您想提出的功能特性是否和现有问题相关？

每次都需要密码，不方便

### 功能特性内容

希望增加一个免密码功能，比如 sudo v2raya --disable-password 之类的
大部分时间都是本地使用，没必要密码的，连 linux/windows 这样的操作系统都可以自动登录和免密码 sudo，使用免密码的人当然知道自己在干什么，没有必要像个家长管理小孩子一样去想当然认为"你需要个登录密码，这是为了你的安全着想"，让使用者自己决定用不用密码，多个选择，多份自由

**Comment by XueqiangDong** [comment]
非常喜换v2rayA的设计思想，一个文件(/usr/bin/v2raya)，一个服务(v2raya.service)，简洁，要是/usr/bin/v2raya把v2ray core 集成进来就更完美了

**Comment by mzz2017** [comment]
@XueqiangDong v2raya --help

**Comment by mzz2017** [comment]
@XueqiangDong 免密码不安全
