### ISSUE TITLE
win10开启代理无法访问google

### ISSUE THREAD

**Issue by Faker0715** [v2rayA/v2rayA#811]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.1
3. 你通过什么方式安装v2rayA
installer_install_inno.exe 安装包
4. 你所使用的操作系统
win10

### 描述问题：

部分电脑上启动v2rayA之后，访问google不会产生日志，而且上不去google
![image](https://user-images.githubusercontent.com/36560441/216136801-e8d9e3c2-3160-4de4-8bcd-ef27fc0326a0.png)
![image](https://user-images.githubusercontent.com/36560441/216136850-7328decc-5fb0-40ce-98e3-b5bbb15b39d1.png)
![image](https://user-images.githubusercontent.com/36560441/216136927-f4646c96-24e5-460d-a4d4-bbe559bfcb9b.png)

### v2rayA运行日志（Optional）：

![image](https://user-images.githubusercontent.com/36560441/216137730-f814775e-8768-46dd-afd1-4a1754180f8b.png)

**Comment by Faker0715** [comment]
![image](https://user-images.githubusercontent.com/36560441/216138268-d1551fc2-f2c4-4c8c-b323-19ddd409bae4.png)
正常的电脑访问google会出现日志 也能上去

**Comment by MarksonHon** [comment]
过于玄学，建议进群：
<https://t.me/v2raya_zh>
