### ISSUE TITLE
关于“直连IP” 选项的添加

### ISSUE THREAD

**Issue by Tom-Plants** [v2rayA/v2rayA#814]
### 功能特性内容

假设一个情况，本机与目标服务器建立的链接使用三方进程，而v2rayA的outbound连接着三方进程。

此三方进程对目标服务器建立的链接会被v2rayA的全局代理给拦截，从而产生无限环回的问题。

可以通过改v2ray配置解决，也可以通过其他方法解决，但是为了方便起见，是否可以在一个地方添加一个“直连IP”，防止三方进程与目标服务器建立的链接再被v2rayA拦截。

**Comment by MarksonHon** [comment]
https://v2raya.org/docs/manual/routinga/
