### ISSUE TITLE
failed to get latest version of GFWList

### ISSUE THREAD

**Issue by love4taylor** [v2rayA/v2rayA#815]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
2.0.1
2. What approach of installation do you install V2rayA?
homebrew
3. What is your operating system?
macOS 13.2

### Description
failed to get latest version of GFWList

### Steps to reproduce
Just open v2rayA setting

### Logs：

 ```
2023/02/06 20:22:04.346 [E] [version.go:36] failed to get latest version of GFWList: fail in getting commit date of latest tag: parsing time "" as "200601021504": cannot parse "" as "2006"
2023/02/06 20:22:09.477 [E] [gfwlist.go:12] failed to get latest version of GFWList: fail in getting commit date of latest tag: parsing time "" as "200601021504": cannot parse "" as "2006"
 ```

### v2rayA setting and related screenshot
<img width="1361" alt="SCR-20230206-seg" src="https://user-images.githubusercontent.com/6081912/216971157-3bdae020-13f3-402c-8fb1-f284ce27da96.png">

**Comment by MarksonHon** [comment]
Maybe a network issue, join group if you need.
https://t.me/v2raya_zh
