### ISSUE TITLE
无root运行

### ISSUE THREAD

**Issue by guohoo** [v2rayA/v2rayA#818]
版本：1.5.8.1
系统：Debian
问题描述：如题，不用root无法使用透明代理，只剩下system proxy可以选，但是system proxy又提示不支持当前操作系统。那请问无root要怎么用呢😂？

**Comment by MarksonHon** [comment]
1、手动给桌面配置系统代理
2、配置代理环境变量
3、单独给应用设置代理
这些内容很容易搜索到
