### ISSUE TITLE
如何修改后端 （20170）的默认监听地址，从localhost修改至172以及192开头的地址？

### ISSUE THREAD

**Issue by chenying99** [v2rayA/v2rayA#819]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
 latest(二月份最新的latest版)

3. 你通过什么方式安装v2rayA
  docker
4. 你所使用的操作系统
cent7

### 描述问题：

默认的socks5监听地址是127.0.0.1:20170，开启端口分享后，监听地址变成0.0.0.0:20170，这样公网ip也可以连接到socks5代理

如果要限制20170端口暴露在外网ip，同时能够接收来自192开头的地址以及172.21.0开头的地址连接，该怎么设置呢？谢谢

**Comment by mzz2017** [comment]
@chenying99 sudo systemctl edit --full v2raya.service

**Comment by mzz2017** [comment]
@chenying99 配一下防火墙就行了

**Comment by chenying99** [comment]
> @chenying99 配一下防火墙就行了

在防火前限制在外网暴露20170端口？

**Comment by chenying99** [comment]
貌似有几个端口要限制  20170 20171 20172等

**Comment by mzz2017** [comment]
@chenying99 防火墙ban掉端口连入就行了

**Comment by chenying99** [comment]
更准确一点的描述是，指定v2raya监听的地址，监听127.0.0.1:20170，限制得太严了
开启端口分享后，监听0.0.0.0:20170，放得开宽了

-----------------------------------------------------------------------------------------------------------------------
我想设置的是，监听本机ip地址，包括127.0.0.1 ，局域网分配的地址192.168， 以及docker分配的地址172.21

但不监听公网ip地址

**Comment by cubercsl** [comment]
@chenying99 提供给你两个方案：
1. 监听 0.0.0.0，在防火墙上添加规则，拒绝不在指定源地址范围的到这些端口的包
2. 不使用这个端口共享功能，在 routingA 中添加自定义入站

**Comment by MarksonHon** [comment]
https://v2raya.org/docs/manual/variable-argument/
