### ISSUE TITLE
无法获取GFWList

### ISSUE THREAD

**Issue by CrazyChildren** [v2rayA/v2rayA#82]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
Version 0.7.1
2. 你通过什么方式安装v2rayA
sudo apt-get install
3. 你所使用的操作系统、CPU架构
ubuntu 16.04 
intel core i5 8th generation-> amd64

### 描述问题

一直在设置中配置了端口分流模式为GWFList，最近出现了无法连接代理的问题，会提示是配置文件错误或端口被占用，经过测试，端口是没问题的，查看日志是由于无法解析GFWLIST文件，应该是目标网站变更了。
日志：
6月 10 19:37:37 chen v2ray[14933]: V2Ray 4.23.4 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/amd64)
6月 10 19:37:37 chen v2ray[14933]: A unified platform for anti-censorship.
6月 10 19:37:37 chen v2ray[14933]: main: failed to read config files: [/etc/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl:
6月 10 19:37:37 chen v2ray[14933]: v2ctl> Read config:  /etc/v2ray/config.json
**6月 10 19:37:37 chen v2ray[14933]: v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to parse domain rule: ext:LoyalsoldierSite.dat:geolocation-!cn > v2ray.com/core/infra/conf: failed to load external sites: geolocation-!cn from LoyalsoldierSite.dat > proto: router.GeoSite: illegal tag 0 (wire type 0) > exit status 255**

**Comment by CrazyChildren** [comment]
只要改变分流模式为其他的就可以正常使用。

**Comment by mzz2017** [comment]
我这里正常，gfwlist先点一下更新看一下

**Comment by CrazyChildren** [comment]
gfwlist已经是最新的了，刚才再试了一下，还是一样的错误

**Comment by dragonandy** [comment]
I got some issue about **LoyalsoldierSite.dat**

> gfwlist.go:144: open /usr/share/v2ray/LoyalsoldierSite.dat: no such file or directory
> [Warning] open /usr/share/v2ray/LoyalsoldierSite.dat: no such file or directory

#93 related and more [info](https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this)

command `sudo mkdir /usr/share/v2ray` may works

**suggestion:** 
make use of `/usr/local/share/v2ray` or make a sepreate `v2raya` folder for v2raya settings 

**more steps:**
update  `v2rayA/install/go.sh`  and consider update to the packages.

**Comment by mzz2017** [comment]
@dragonandy 

Thanks for the feedback.

Unpublished related commit can be found here https://github.com/v2rayA/v2rayA/commit/5f9fcbbb0148173ad1a3a711eccca4b7590a9948

It added support for inspecting /usr/local/share and /usr/share according to the source code of v2ray-core.


If you think it doesn't make sense, feel free to report it.
