### ISSUE TITLE
如果替换 V2raya binary 为 Xray, 提示: The version of v2ray-core is not v5. Use v5 or downgrade v2rayA to v1.5

### ISSUE THREAD

**Issue by zw963** [v2rayA/v2rayA#821]
当然，这可能并不算是 issue, 但是值得一提的是，我一直是 V2rayA 的用户，而且很长时间，我都是先使用官方的 docker image 启动一个容器，然后再手动替换 v2ray 命令行为 xray, 并且使用的相当好，但是自从升级到版本 2, V2rayA 限制了我的使用。

请问，有没有解决办法？ （当然，我最希望的是，官方可以直接支持通过界面来配置使用 xray).

**Comment by mzz2017** [comment]
@zw963 v1 的最后一个版本很稳定，可以暂时先用着。目前等 xray 重新支持新配置后 v2rayA 会进行跟进，据不可靠消息说 rprx 准备推进新配置的兼容

**Comment by zw963** [comment]
好，理解了，早就听说 V2ray 在版本 5 之后，会极大的精简配置，不过后来我切换到 XTLS 了，也不再关注了，如果 Xray 也采用新配置，那真需要再学习一下，谢谢。

**Comment by mzz2017** [comment]
@zw963 并不，这个新配置很复杂。。

**Comment by mzz2017** [comment]
@zw963 可以期待我们的新项目 v2rayA/dae，这是我们自己写的 core，之后会写 ui
