### ISSUE TITLE
支持socks5的账号密码功能

### ISSUE THREAD

**Issue by steinvenic** [v2rayA/v2rayA#822]
### 您想提出的功能特性是否和现有问题相关？

v2rayA部署在公网上，现在使用的一个大端口号，但也难免会被扫出来，希望增加账号密码的功能，以增加其安全性

**Comment by mzz2017** [comment]
@steinvenic https://v2raya.org/docs/advanced-application/intranet-transmission/

**Comment by steinvenic** [comment]
> 
多谢，刚在文档中 没看到...
