### ISSUE TITLE
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.20 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.20 set. Notably, if go1.20 adds a moving garbage collector, this program is unsafe to use.  goroutine 1 [running]: go4.org/unsafe/assume-no-moving-gc.init.0()         /home/keeyu/go/pkg/mod/go4.org/unsafe/assume-no-moving-gc@v0.0.0-20220617031537-928513b29760/untested.go:25 +0x178

### ISSUE THREAD

**Issue by keeYuc** [v2rayA/v2rayA#823]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2raya-2.0.1-1
2. 你通过什么方式安装v2rayA
yay
3. 你所使用的操作系统
manjaro/arm64
### 描述问题

无法启动
运行直接报错
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.20 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.20 set. Notably, if go1.20 adds a moving garbage collector, this program is unsafe to use.  goroutine 1 [running]: go4.org/unsafe/assume-no-moving-gc.init.0()         /home/keeyu/go/pkg/mod/go4.org/unsafe/assume-no-moving-gc@v0.0.0-20220617031537-928513b29760/untested.go:25 +0x178
### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```
 或者粘贴来自 Web 页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@keeYuc master 已修，用 v2raya-git 或者 v2raya-bin

**Comment by keeYuc** [comment]
> @keeYuc 主分支已修，用 v2raya-git 或者 v2raya-bin

1

**Comment by Hoohan** [comment]
> @keeYuc 主分支已修，用 v2raya-git 或者 v2raya-bin

你好，我今天使用AUR库安装也出现了完全一样的问题，现在正在安装v2raya-git。请问正式版何时可以修复？
