### ISSUE TITLE
如何进行端口转发

### ISSUE THREAD

**Issue by lxzcl** [v2rayA/v2rayA#828]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.1
2. 你通过什么方式安装v2rayA
docker
3. 你所使用的操作系统
Ubuntu 20.04 LTS aarch64

### 描述问题：
问题如题如何进行端口转发

**Comment by mzz2017** [comment]
@lxzcl 请详细描述你所说的端口转发

**Comment by lxzcl** [comment]
例如我在公网上有一个80网页或者其他服务，我想在本地挂一个节点，这节点没有任何代理的作用他只是把公网的端口通过节点转发到本地机器的某个端口，这样我就可以在局域网通过局域网IP访问
功能类似于
![image](https://user-images.githubusercontent.com/41499707/221341598-f276623c-692b-410d-bd24-dee937f0adf8.png)

**Comment by mzz2017** [comment]
@lxzcl 目前不支持这个操作

**Comment by mzz2017** [comment]
@lxzcl 你可以选择使用 ssh -L 远程转发，或者 zerotier， vscode 等工具实现你的功能

**Comment by lxzcl** [comment]
好吧，期待有一天可以支持，因为我寻找了很久类似便捷的工具，很可惜他们都不在linux上支持

**Comment by MarksonHon** [comment]
Use shadowsocks-libev's `ss-tunnel` instead, v2rayA is just a cilent for V2Ray.
https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-tunnel.asciidoc
