### ISSUE TITLE
启动失败，报[E] [once.go:74]  bbolt.Open: invalid argument

### ISSUE THREAD

**Issue by cgangit** [v2rayA/v2rayA#829]
### 版本、安装方式、系统
1. 你在使用什么版本的v2rayA
1.5.9.1698.1-2
2. 你通过什么方式安装v2rayA
opkg
3. 你所使用的操作系统
openwrt 22
4. 设备
新路由3 Newifi D2

### 描述问题：
服务启动失败，管理界面无法打开。
根据日志感觉是打开数据库文件失败，但/etc/v2raya/目录下存在一个.db文件。

### v2rayA运行日志：
2023/02/27 08:07:42.265  [E] [once.go:74]  bbolt.Open: invalid argument

**Comment by mzz2017** [comment]
@cgangit 删除 /etc/v2raya 下面的 db 文件看看

**Comment by mzz2017** [comment]
很有可能

**Comment by cgangit** [comment]
@mzz2017 把v2raya和xray分别压缩到7M左右后，运行依旧报相同错误。

**Comment by mzz2017** [comment]
看看uname -a

**Comment by cgangit** [comment]
@mzz2017 Linux OpenWrt 5.10.161 #0 SMP Tue Jan 3 00:24:21 2023 mips GNU/Linux

**Comment by mzz2017** [comment]
@cgangit 可能是数据库对mips支持问题

**Comment by cgangit** [comment]
感谢回复，我再想想其他方案

**Comment by jamesqhnu** [comment]
我现在也是这个问题，请问你是怎么解决的

**Comment by cgangit** [comment]
没有解决，后边我用nas跑虚拟机当旁路由。

jamesqhnu ***@***.***> 于2023年5月21日周日 11:23写道：

**Comment by agha57** [comment]
Dear friends,

I have a problem with a fresh install of “v2raya+xray-core”.  V2raya is not starting and v2raya log shows a few lines, repeating the following error message:
   2023/09/26 18:52:55.134  [E] [once.go:74]  bbolt.Open: invalid argument

Here is my Setup:
Router: Asus RT-N16
Device Flash/RAM: 32/128 MB
OpenWRT 22.03.5, r20134-5f15225c1e
BusyBox v1.35.0 (2023-04-27 20:28:15 UTC)
V2raya installation exactly as per instructions in https://github.com/v2raya/v2raya-openwrt
opkg list-installed *ray*   ==>
   luci-app-v2raya - 10
   v2raya - 2.2.4-1
   xray-core - 1.8.4-1
Remaining free space after above “v2raya+xray-core” installation (but not running):
   Free Space Falsh/RAM: 1.2/66 MiB 

I saw this page using google translate and it did not solve my problem.

Could anybody help, please?
Thanks.

**Comment by geeklin** [comment]
bbolt 对overlayfs 支持有问题，我尝试把配置文件目录改到/tmp/v2rarya目录后可以正常运行。
