### ISSUE TITLE
需要添加环境变量ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.20后才能正常启动

### ISSUE THREAD

**Issue by neovali** [v2rayA/v2rayA#834]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2.0.1

2. 你通过什么方式安装v2rayA
通过copr自编译

3. 你所使用的操作系统
Fedora 38

### 描述问题：
copr编译v2raya用的是https://github.com/v2rayA/v2raya-copr 的.spec文件。
copr编译v2ray-core用的是https://github.com/sixg0000d-copr/v2ray-core 的.spec文件

在启动时提示下方内容，然后通过添加环境变量`ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.20`后正常启动。

```
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.20 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.20 set. Notably, if go1.20 adds a moving garbage collector, this program is unsafe to use.

goroutine 1 [running]:
go4.org/unsafe/assume-no-moving-gc.init.0()
        /builddir/go/pkg/mod/go4.org/unsafe/assume-no-moving-gc@v0.0.0-20220617031537-928513b29760/untested.go:25 +0x1ba
```

**Comment by cubercsl** [comment]
已在主分支上修复。2.0.1 的代码发布时应使用 go 1.19 编译，如需使用 go1.20 编译，则需要 cherry-pick 一下 https://github.com/v2rayA/v2rayA/commit/312f470a405475e6bbd89ccd1d27e840e6417b9b
。
