### ISSUE TITLE
查看日志，显示空白（前段时间还正常显示日志记录）

### ISSUE THREAD

**Issue by chenying99** [v2rayA/v2rayA#835]
版本、安装方式、系统
你在使用什么版本的v2rayA
 v2.0.1 (latest)

你通过什么方式安装v2rayA
docker

你所使用的操作系统
cent7

描述问题：
今天打开网页界面，右上角，查看日志，显示空白（前段时间还正常显示，有日志记录）

docker-compose配置
v2raya:
    image: mzz2017/v2raya
    ports:
      - 2017:2017
      - 20170-20172:20170-20172
    hostname: v2raya
    restart: always
    environment:      
      - V2RAYA_LOG_FILE=/tmp/v2raya.log
    volumes:
      - /etc/v2raya:/etc/v2raya

**Comment by mzz2017** [comment]
@chenying99 是不是磁盘满了

**Comment by chenying99** [comment]
不是呀，我刚查看剩余空间，还有40多G，我刚停止 删除容器，重新docker-compose up，又可以看到日志了
