### ISSUE TITLE
Ubuntu22.10安装v2raya，提示无异常，但无法上网

### ISSUE THREAD

**Issue by renxi-jack** [v2rayA/v2rayA#836]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?

2. What approach of installation do you install V2rayA?

3. What is your operating system?

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```

 You can also paste the log that comes from web administration page

```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by ASh-en** [comment]
设置中透明代理/系统代理该选项是否为关闭状态，可选择启用试试
