### ISSUE TITLE
failed to start v2ray-core: unsupported alterID > 0:

### ISSUE THREAD

**Issue by jiangbinzhe** [v2rayA/v2rayA#838]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.1
2. 你通过什么方式安装v2rayA
sudo apt install v2raya
3. 你所使用的操作系统
ubuntu 22.04.2LTS

### 描述问题

选择节点，点击“就绪”之后报
failed to start v2ray-core: unsupported alterID > 0:
节点内AlterID设置为1
### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```
 或者粘贴来自 Web 页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by salary300w** [comment]
好像只能降级到1.5

**Comment by HadesYOUNG** [comment]
关了干啥，咋解决呢

**Comment by mzz2017** [comment]
@HadesYOUNG alterID > 0 已经被新版本弃用，修改你的服务器配置，或者降级 v2rayA 到 1.5.9

**Comment by HadesYOUNG** [comment]
请问如何降级呢
&nbsp;


杨智慧
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月12日(星期天) 晚上9:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [v2rayA/v2rayA] failed to start v2ray-core: unsupported alterID &gt; 0: (Issue #838)





 
@HadesYOUNG alterID &gt; 0 已经被新版本弃用，修改你的服务器配置，或者降级 v2rayA 到 1.5.9

**Comment by mzz2017** [comment]
@HadesYOUNG 去 releases 里找个 1.5.9 版本的下载下来替换掉 which v2raya
