### ISSUE TITLE
查看日志，只能看到今天3.9号8点后的日志，之前的都看不到了，是不是正常情况？

### ISSUE THREAD

**Issue by chenying99** [v2rayA/v2rayA#839]
版本、安装方式、系统
你在使用什么版本的v2rayA
v2.0.1 (latest)

你通过什么方式安装v2rayA
docker

你所使用的操作系统
cent7

描述问题：
刚才查看日志，只能看到今天3.9号8点后的日志，前些天的都看不到了，是正常的吗？还是容器自动重启了导致的？

docker-compose配置
v2raya:
image: mzz2017/v2raya
ports:
- 2017:2017
- 20170-20172:20170-20172
hostname: v2raya
restart: always
environment:
- V2RAYA_LOG_FILE=/tmp/v2raya.log
volumes:
- /etc/v2raya:/etc/v2raya

**Comment by mzz2017** [comment]
@chenying99 /tmp会重启清空

**Comment by chenying99** [comment]
那是容器自动重启了吧

**Comment by mzz2017** [comment]
@chenying99 你不是把宿主的/tmp挂上去了？你宿主重启了啊

**Comment by chenying99** [comment]
宿主机没重启呀，上面的compose配置，volume，没有映射容器的/temp目录到宿主机

**Comment by mzz2017** [comment]
@chenying99 哦哦看见了，对的，就是容器重启了就没了

**Comment by mzz2017** [comment]
@chenying99 我不清楚容器是不是会自动重启，你可以看docker ps，应该会显示启动时间

**Comment by chenying99** [comment]
好的 我看看

**Comment by chenying99** [comment]
我查了一下，没有重启呀
CONTAINER ID   IMAGE                     COMMAND                  CREATED        STATUS 
698e9e3f17f7   mzz2017/v2raya            "v2raya"                 27 hours ago   Up 27 hours

**Comment by mzz2017** [comment]
@chenying99 不清楚了哇，你看看/tmp目录下面是不是被清了

**Comment by chenying99** [comment]
我进容器 查查

**Comment by chenying99** [comment]
sudo docker exec -it imagematting_v2raya /bin/bash

这个进不了，还有其它方法进入容器么？

**Comment by mzz2017** [comment]
@chenying99 用 /bin/sh

**Comment by chenying99** [comment]
/tmp # ls -lh
total 280K   
-r--r-----    1 root     root        3.7K Mar  8 07:57 v2raya.2023-03-08.001.log
-r--r-----    1 root     root      260.1K Mar  9 07:52 v2raya.2023-03-09.001.log
-rw-rw----    1 root     root        6.4K Mar  9 08:59 v2raya.log

可能是日志按日期滚动的，前端界面只显示最近的日志吧

**Comment by chenying99** [comment]
日期中又按文件大小 分割吧

**Comment by mzz2017** [comment]
@chenying99 哦哦对，前端只显示最新的那个日志文件

**Comment by chenying99** [comment]
我前几天 突然看不到日志了，不清楚是不是这个原因

**Comment by mzz2017** [comment]
@chenying99 新日志也看不到了吗

**Comment by chenying99** [comment]
我当时打开几次看不到日志，有可能几分钟内没有请求代理，没有产生新日志

**Comment by mzz2017** [comment]
@chenying99 有可能的
