### ISSUE TITLE
the core was not running the last time v2rayA exited, 是不是有问题?

### ISSUE THREAD

**Issue by csfreebird** [v2rayA/v2rayA#840]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
v2.0.1

3. What approach of installation do you install V2rayA?
手动安装deb文件

5. What is your operating system?
ubuntu 22.04

### Logs：

2023/03/07 11:39:00.717  [A] [main.go:26]  Starting...
2023/03/07 11:39:00.717  [I] [main.go:27]  the core was not running the last time v2rayA exited
2023/03/07 11:39:00.734  [A] [index.go:116]  v2rayA is listening at http://127.0.0.1:2017

```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.
<!-- Paste screenshot if possible -->

**Comment by MarksonHon** [comment]
建议使用翻译软件翻译一下即可，还有核心别忘了装了，有需要可以阅读 https://v2raya.org

**Comment by mzz2017** [comment]
@csfreebird 没什么问题

**Comment by tableking** [comment]
遇到同样问题，windows 11 pro ,  v2raya v2.0.5
2023/04/13 18:58:08.086 [A] [main.go:26]  V2Ray binary is D:\ProgramFiles\openss\xray.exe
2023/04/13 18:58:08.092 [A] [main.go:26]  V2Ray asset directory is config2
2023/04/13 18:58:08.092 [A] [main.go:26]  v2rayA working directory is D:\ProgramFiles\openss
2023/04/13 18:58:08.092 [A] [main.go:26]  v2rayA configuration directory is config2
2023/04/13 18:58:08.093 [A] [main.go:26]  Golang: go1.20.3
2023/04/13 18:58:08.093 [A] [main.go:26]  OS: windows
2023/04/13 18:58:08.093 [A] [main.go:26]  Arch: amd64
2023/04/13 18:58:08.093 [A] [main.go:26]  Lite: true
2023/04/13 18:58:08.093 [A] [main.go:26]  Version: 2.0.5
2023/04/13 18:58:08.094 [A] [main.go:26]  Starting...
2023/04/13 18:58:08.094 [I] [main.go:27]  the core was not running the last time v2rayA exited
2023/04/13 18:58:08.101 [A] [index.go:116]  v2rayA is listening at http://[fe8::4ad:e53:6c68:e2be]:2017

**Comment by tableking** [comment]
旧版本没有这个问题一样的配置
2023/04/13 18:58:08.086 [A] [main.go:26]  V2Ray binary is D:\ProgramFiles\openss\xray.exe
2023/04/13 18:58:08.092 [A] [main.go:26]  V2Ray asset directory is config2
2023/04/13 18:58:08.092 [A] [main.go:26]  v2rayA working directory is D:\ProgramFiles\openss
2023/04/13 18:58:08.092 [A] [main.go:26]  v2rayA configuration directory is config2
2023/04/13 18:58:08.093 [A] [main.go:26]  Golang: go1.20.3
2023/04/13 18:58:08.093 [A] [main.go:26]  OS: windows
2023/04/13 18:58:08.093 [A] [main.go:26]  Arch: amd64
2023/04/13 18:58:08.093 [A] [main.go:26]  Lite: true
2023/04/13 18:58:08.093 [A] [main.go:26]  Version: 2.0.5
2023/04/13 18:58:08.094 [A] [main.go:26]  Starting...
2023/04/13 18:58:08.094 [I] [main.go:27]  the core was not running the last time v2rayA exited
2023/04/13 18:58:08.101 [A] [index.go:116]  v2rayA is listening at http://[f80::46a:e52:6c:e2be]:2017
