### ISSUE TITLE
配置routingA direct连接国内站，SSL握手时间非常长

### ISSUE THREAD

**Issue by Liu-Steve** [v2rayA/v2rayA#842]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.1
2. 你通过什么方式安装v2rayA
通过github下载installer_debian_amd64_2.0.1.deb包，并使用apt安装
3. 你所使用的操作系统
Ubuntu 22.04.1
linux内核版本5.19.0-37-generic
Chrome版本 111.0.5563.64（正式版本）（64 位）
Firefox版本: 110.0.1 (64 位)

### 描述问题：

问题：配置routingA direct连接国内站，SSL握手时间非常长
一次握手长达16s，对于zhihu这种先建立页面连接再建立图床连接的网站，需要更长时长才可以正常访问，难以忍受
更长的连接时间也经常导致页面加载失败，特别是css文件

目前我已完成v2aryA的配置，可以正常且迅速地访问Google等GFW外网站，具体配置可以看下面
现在的问题是当访问zhihu.com，qq.mail.com等国内网站时会有一个非常长的SSL握手时长，可以通过F12观察到
我已为这些网站在v2rayA的routingA中配置到direct方向出站，并且可以在日志中观察到他们确实走的direct

目前的临时解决方案：
在chrome浏览器中安装SwitchyOmega插件，提前将zhihu等网站分流走直连

### v2rayA运行日志（Optional）：

关闭SwitchyOmega插件分流zhihu与zhimg功能，访问zhihu.com时v2rayA日志

注：http://91.108.56.107:80/api 是telegram的ip,请无视它

 ```bash
$ sudo tail -n 50 /var/log/v2raya/v2raya.log

2023/03/11 11:57:52.000  [I] [io.go:429]  127.0.0.1:44762 accepted //encrypted-tbn0.gstatic.com:443 [『Hong Kong』]
2023/03/11 11:57:52.302  [I] [io.go:429]  127.0.0.1:44778 accepted //encrypted-tbn0.gstatic.com:443 [『Hong Kong』]
2023/03/11 11:57:52.302  [I] [io.go:429]  127.0.0.1:44790 accepted //encrypted-tbn0.gstatic.com:443 [『Hong Kong』]
2023/03/11 11:57:55.259  [I] [io.go:429]  127.0.0.1:44794 accepted //ogs.google.com:443 [『Hong Kong』]
2023/03/11 11:57:55.802  [I] [io.go:429]  127.0.0.1:44808 accepted //www.gstatic.com:443 [『Hong Kong』]
2023/03/11 11:57:55.802  [I] [io.go:429]  127.0.0.1:44818 accepted //ssl.gstatic.com:443 [『Hong Kong』]
2023/03/11 11:58:00.570  [I] [io.go:429]  127.0.0.1:37312 accepted //www.zhihu.com:443 [direct]
2023/03/11 11:58:00.570  [I] [io.go:429]  127.0.0.1:37328 accepted //static.zhihu.com:443 [direct]
2023/03/11 11:58:01.700  [I] [io.go:429]  127.0.0.1:37334 accepted http://91.108.56.107:80/api [『Hong Kong』]
2023/03/11 11:58:03.203  [I] [io.go:429]  127.0.0.1:37336 accepted http://91.108.56.107:80/api [『Hong Kong』]
2023/03/11 11:58:10.057  [I] [io.go:429]  127.0.0.1:37348 accepted http://91.108.56.107:80/api [『Hong Kong』]
2023/03/11 11:58:10.313  [I] [io.go:429]  127.0.0.1:58936 accepted //mtalk.google.com:5228 [『Hong Kong』]
2023/03/11 11:58:14.869  [I] [io.go:429]  127.0.0.1:58946 accepted http://91.108.56.107:80/api [『Hong Kong CMI』]
2023/03/11 11:58:18.340  [I] [io.go:429]  127.0.0.1:58960 accepted //static.zhihu.com:443 [direct]
2023/03/11 11:58:18.734  [I] [io.go:429]  127.0.0.1:58972 accepted //static.zhihu.com:443 [direct]
2023/03/11 11:58:18.839  [I] [io.go:429]  127.0.0.1:58980 accepted //hm.baidu.com:443 [direct]
2023/03/11 11:58:18.887  [I] [io.go:429]  127.0.0.1:58992 accepted //static.zhihu.com:443 [direct]
2023/03/11 11:58:19.560  [I] [io.go:429]  127.0.0.1:58998 accepted //sugar.zhihu.com:443 [direct]
2023/03/11 11:58:19.560  [I] [io.go:429]  127.0.0.1:59004 accepted //sugar.zhihu.com:443 [direct]
2023/03/11 11:58:19.560  [I] [io.go:429]  127.0.0.1:59014 accepted //sugar.zhihu.com:443 [direct]
2023/03/11 11:58:19.566  [I] [io.go:429]  127.0.0.1:59030 accepted //content-autofill.googleapis.com:443 [『Hong Kong CMI』]
2023/03/11 11:58:19.566  [I] [io.go:429]  127.0.0.1:59034 accepted //sugar.zhihu.com:443 [direct]
2023/03/11 11:58:19.577  [I] [io.go:429]  127.0.0.1:59046 accepted //picx.zhimg.com:443 [direct]
2023/03/11 11:58:19.581  [I] [io.go:429]  127.0.0.1:59062 accepted //pic4.zhimg.com:443 [direct]
2023/03/11 11:58:19.631  [I] [io.go:429]  127.0.0.1:59074 accepted http://91.108.56.107:80/api [『Hong Kong CMI』]
2023/03/11 11:58:19.883  [I] [io.go:429]  127.0.0.1:59088 accepted //pic4.zhimg.com:443 [direct]
2023/03/11 11:58:20.007  [I] [io.go:429]  127.0.0.1:59096 accepted //mqtt-web.zhihu.com:443 [direct]
2023/03/11 11:58:20.246  [I] [io.go:429]  127.0.0.1:45910 accepted //picx.zhimg.com:443 [direct]
2023/03/11 11:58:20.246  [I] [io.go:429]  127.0.0.1:45918 accepted //picx.zhimg.com:443 [direct]
2023/03/11 11:58:20.247  [I] [io.go:429]  127.0.0.1:45924 accepted //pic1.zhimg.com:443 [direct]
2023/03/11 11:58:20.248  [I] [io.go:429]  127.0.0.1:45926 accepted //picx.zhimg.com:443 [direct]
2023/03/11 11:58:20.248  [I] [io.go:429]  127.0.0.1:45932 accepted //pica.zhimg.com:443 [direct]
2023/03/11 11:58:20.248  [I] [io.go:429]  127.0.0.1:45944 accepted //picx.zhimg.com:443 [direct]
2023/03/11 11:58:20.259  [I] [io.go:429]  127.0.0.1:45960 accepted //picx.zhimg.com:443 [direct]
2023/03/11 11:58:20.345  [I] [io.go:429]  127.0.0.1:45966 accepted //zhihu-web-analytics.zhihu.com:443 [direct]
2023/03/11 11:58:20.349  [I] [io.go:429]  127.0.0.1:45968 accepted //118.89.204.198:443 [direct]
2023/03/11 11:58:20.371  [I] [io.go:429]  127.0.0.1:45978 accepted //datahub.zhihu.com:443 [direct]
2023/03/11 11:58:20.550  [I] [io.go:429]  127.0.0.1:45988 accepted //pica.zhimg.com:443 [direct]
2023/03/11 11:58:20.588  [I] [io.go:429]  127.0.0.1:45992 accepted //sugar.zhihu.com:443 [direct]
2023/03/11 11:58:36.349  [I] [io.go:429]  127.0.0.1:36394 accepted //apm.zhihu.com:443 [direct]
 ```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

#### v2rayA配置
![image](https://user-images.githubusercontent.com/73787075/224464363-6443cab7-d85e-4299-aa5a-2f9ce8551e1f.png)
![image](https://user-images.githubusercontent.com/73787075/224464375-b39038cd-6068-473c-8e24-8561de147158.png)
![image](https://user-images.githubusercontent.com/73787075/224465275-c2b4bf47-c8e2-48c5-9fde-c28d20b649e8.png)
使用系统代理而没有使用透明代理，是因为会影响YesPlayMusic

#### chrome配置
![image](https://user-images.githubusercontent.com/73787075/224465312-db79359e-5667-4767-9b8b-5e72784b611a.png)

#### Firefox配置
![image](https://user-images.githubusercontent.com/73787075/224465359-a26935be-3b23-4542-bec4-c9cb7bca63e3.png)

#### Ubuntu系统代理配置
![image](https://user-images.githubusercontent.com/73787075/224465376-7a651c46-ee68-4caa-bae8-45b41c4870d0.png)

chrome通过SwitchyOmega插件在分流基础上使用系统代理，Firefox直接配置系统代理

#### routingA配置
![image](https://user-images.githubusercontent.com/73787075/224464389-a683d228-bed9-4e77-8484-ccbb8f503401.png)

#### DNS配置
![image](https://user-images.githubusercontent.com/73787075/224464405-d6e95d59-1c32-4f51-b68e-694a3d0ba170.png)

#### 节点配置
![image](https://user-images.githubusercontent.com/73787075/224464461-d551606a-87f6-4ec0-bed5-0fa8510c5dde.png)
三个节点使用相同配置，自建v2ray节点，使用certbot申请证书，协议vless，应该与本题无关

#### F12截图
关闭SwitchyOmega插件分流zhihu与zhimg功能，与zhihu.com 建立连接时
![image](https://user-images.githubusercontent.com/73787075/224464226-d70f0108-64ec-4243-bcc4-54d7eb2ab232.png)
![image](https://user-images.githubusercontent.com/73787075/224464248-470c19e5-818a-498a-8877-0d4dbdfa166b.png)
分别与 www.zhihu.com 和 pic4.zhimg.com 建立SSL连接

不只Chrome，Firefox也有类似问题
![image](https://user-images.githubusercontent.com/73787075/224465116-c64cf8b0-19f3-4846-89bb-f1897026a1c2.png)

作为对比
附上与 google.com SSL握手F12截图
![image](https://user-images.githubusercontent.com/73787075/224464598-2c66f423-f182-496b-a711-5996d5bf2ec0.png)

附上使用SwitchyOmega分流zhihu的F12截图
![image](https://user-images.githubusercontent.com/73787075/224465144-54b22bdf-59dc-4a50-a11f-4adf702bb152.png)

如果需要任何其他的日志或信息，我会尽力提供

**Comment by mzz2017** [comment]
因为日志显示知乎上直连，这种情况一般来说，这可能是因为对知乎的dns查询进行了转发，从而拿到了国外cdn的地址，而直连国外cdn是比较慢的。你可以通过dig知乎域名来看看拿到ip是不是国内ip来验证。

**Comment by Liu-Steve** [comment]
感谢大佬回答，我在这里尝试了在本地和香港的VPS上执行 dig @1.1.1.1 zhihu.com，查到的都是同一个ip地址103.41.167.234，根据ip138是中国河北石家庄的ip地址，命令如下：
本地：
```bash
$ dig @1.1.1.1 zhihu.com

; <<>> DiG 9.18.1-1ubuntu1.3-Ubuntu <<>> @1.1.1.1 zhihu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21299
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;zhihu.com.			IN	A

;; ANSWER SECTION:
zhihu.com.		29	IN	A	103.41.167.234

;; Query time: 60 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Sat Mar 11 13:21:16 CST 2023
;; MSG SIZE  rcvd: 54
```
香港某VPS：
```bash
$ dig @1.1.1.1 zhihu.com

; <<>> DiG 9.18.12 <<>> @1.1.1.1 zhihu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9215
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;zhihu.com.			IN	A

;; ANSWER SECTION:
zhihu.com.		61	IN	A	103.41.167.234

;; Query time: 0 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Sat Mar 11 13:17:33 CST 2023
;; MSG SIZE  rcvd: 54
```

ip138截图：
![image](https://user-images.githubusercontent.com/73787075/224466609-da5de86a-fb89-4ede-a492-f4354081f26d.png)

**Comment by Liu-Steve** [comment]
另外我也在另外一个香港VPS节点，一个大阪VPS节点，一个美国新泽西节点用dig对1.1.1.1进行了测试，结果都是相同的，都是103.41.167.234这个ip地址，可能zhihu.com并没有海外CDN节点

**Comment by mzz2017** [comment]
那如果日志走的是直连的话，不应该会很慢

**Comment by mzz2017** [comment]
关掉v2raya就能好吗

**Comment by Liu-Steve** [comment]
> 

正确的，关掉v2raya以及系统代理就可以正常访问

**Comment by MarksonHon** [comment]
如果填写了http代理，那么https代理也要设置成一样的，否则https流量不走代理，然后一旦一些流量从你VPS访问，一些流量直连访问，那很可能出问题。

**Comment by Liu-Steve** [comment]
另外，如果使用不分流的http端口，完全使用代理连接知乎反而不会有很长的SSL握手时间

**Comment by Liu-Steve** [comment]
@MarksonHon 非常感谢，我现在在ubuntu的系统代理给https设置了与http相同的代理，问题解决了
