### ISSUE TITLE
v2rayA 重设密码很久没有结果

### ISSUE THREAD

**Issue by xflcx1991** [v2rayA/v2rayA#846]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.1
2. 你通过什么方式安装v2rayA
软件源方式
3. 你所使用的操作系统
Ubuntu 18.04

### 描述问题：
我忘记了我的web密码，看到
https://github.com/v2rayA/v2rayA/issues/143
这里说 https://github.com/v2rayA/v2rayA/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98 讲了方法，可是没有回应啊，说关闭另外的v2ray实例，我是通过 systemctl start 方式启动，我没有其他实例啊
![image](https://user-images.githubusercontent.com/3775351/224700083-2e45b1ae-7d12-46a2-bf68-2c0839e55c43.png)

这是日志
![image](https://user-images.githubusercontent.com/3775351/224700484-ab12d51f-6bce-4448-b314-e8f6aa5d40b6.png)

**Comment by mzz2017** [comment]
@xflcx1991 关掉那个systemd的实例

**Comment by xflcx1991** [comment]
> @xflcx1991 关掉那个systemd的实例

解决了，原来就是要关掉
