### ISSUE TITLE
v2rayA自动断开连接

### ISSUE THREAD

**Issue by BlademasterQAQ** [v2rayA/v2rayA#847]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.1
2. 你通过什么方式安装v2rayA
apt
3. 你所使用的操作系统
Ubuntu

### v2rayA运行日志（Optional）：

未记录到问题出现时的日志

![image](https://user-images.githubusercontent.com/36795725/224928193-5cfdb68c-009d-4b6c-9332-d6e70a368286.png)

之前用旧版v2rayA的时候没有遇到这样的问题，新版中左上角加入了一个按钮，需要选中节点并且点击此按钮使其处于“正在运行”的状态下才能工作。
遇到的问题是，**在正常使用大约1天后，“正在运行”会被切换为“断开”，而节点的选择是正常的**，主机自身应该也没有问题，并且此问题已多次出现（是否至少有一种治标不治本的简单方法，通过API每分钟检测运行状态，若断卡则自动重连，API请求）。

p.s. tg群的验证是不是有点太难了，答了两次都不对

**Comment by mzz2017** [comment]
@BlademasterQAQ 有一说一我也觉得难。你可以看看日志，是不是 out of memory 被 kill 了

**Comment by BlademasterQAQ** [comment]
> @BlademasterQAQ 有一说一我也觉得难。你可以看看日志，是不是 out of memory 被 kill 了

意思是可能 v2ray 被 kill 了，而 v2rayA 的web UI还是正常工作的？由于是阿里云服务器，也不排除是阿里云在搞鬼。。。

**Comment by BlademasterQAQ** [comment]
> @BlademasterQAQ 对，有可能 v2ray 被 kill 了。一般情况下是因为内存泄露，建议切回旧版本观察是否问题消失以排除服务商的问题。

tail -n 50 /var/log/v2raya/v2raya.log
看到  `[W] [asm_amd64.s:1594]  v2ray-core: signal: killed`
只能切换旧版本试试吗？

**Comment by mzz2017** [comment]
@BlademasterQAQ 现在可以升级到 2.0.4，然后使用 xray 看看问题会不会解决

**Comment by BlademasterQAQ** [comment]
> @BlademasterQAQ 现在可以升级到 2.0.4，然后使用 xray 看看问题会不会解决

感谢，刚刚检查了下确实是内存爆了，我尝试下增加 swap 看看。
我认为程序可能存在一个问题，就是程序崩溃后不会自动重连，需要手动重连，不知道新版是否做了改进？
我也不是很懂本项目，说的不对见笑了。
