### ISSUE TITLE
failed to start v2ray-core: unsupported alterID > 0: check the log for more information

### ISSUE THREAD

**Issue by ranbi666** [v2rayA/v2rayA#849]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v2rayA --version:2.0.1
v2rayCore --version:v4.31.0
2. 你通过什么方式安装v2rayA
通过软件源安装
3. 你所使用的操作系统
Linux nfore 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
### 描述问题：

点击Start后弹出：failed to start v2ray-core: unsupported alterID > 0: check the log for more information

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log：
2023/03/17 00:40:48.640  [A] [index.go:116]  v2rayA is listening at http://[fe80::1a05:2bcd:c878:79ab]:2017
2023/03/17 00:40:55.900  [E] [account.go:79]  length of password should be between 6 and 32
2023/03/17 00:44:18.821  [W] [context.go:165]  PostConnection: failed to connect: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:44:18.821  [E] [connection.go:36]  failed to connect: failed to connect: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:44:23.731  [W] [context.go:165]  PostConnection: failed to connect: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:44:23.731  [E] [connection.go:36]  failed to connect: failed to connect: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:44:41.588  [W] [context.go:165]  PostConnection: failed to connect: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:44:41.588  [E] [connection.go:36]  failed to connect: failed to connect: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:46:16.658  [E] [connection.go:88]  failed to start v2ray-core: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:49:34.152  [E] [connection.go:88]  failed to start v2ray-core: failed: no server is selected. please select at least one server
2023/03/17 00:49:41.716  [E] [connection.go:88]  failed to start v2ray-core: failed: no server is selected. please select at least one server
2023/03/17 00:50:07.238  [E] [v2rayTmpl.go:1275]  We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:50:07.238  [E] [connection.go:88]  failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 00:51:10.735  [E] [v2rayTmpl.go:1275]  We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:51:10.735  [E] [connection.go:88]  failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 00:53:25.712  [A] [main.go:26]  V2Ray binary is /usr/local/bin/v2ray
2023/03/17 00:53:25.713  [A] [main.go:26]  V2Ray asset directory is /run/user/0/v2raya
2023/03/17 00:53:25.713  [A] [main.go:26]  v2rayA working directory is /
2023/03/17 00:53:25.713  [A] [main.go:26]  v2rayA configuration directory is /etc/v2raya
2023/03/17 00:53:25.713  [A] [main.go:26]  Golang: go1.19.3
2023/03/17 00:53:25.713  [A] [main.go:26]  OS: linux
2023/03/17 00:53:25.713  [A] [main.go:26]  Arch: amd64
2023/03/17 00:53:25.713  [A] [main.go:26]  Lite: false
2023/03/17 00:53:25.713  [A] [main.go:26]  Version: 2.0.1
2023/03/17 00:53:25.713  [A] [main.go:26]  Starting...
2023/03/17 00:53:25.713  [I] [main.go:27]  the core was not running the last time v2rayA exited
2023/03/17 00:53:25.729  [A] [index.go:116]  v2rayA is listening at http://127.0.0.1:2017
2023/03/17 00:53:25.729  [A] [index.go:116]  v2rayA is listening at http://192.168.56.130:2017
2023/03/17 00:53:25.729  [A] [index.go:116]  v2rayA is listening at http://[::1]:2017
2023/03/17 00:53:25.729  [A] [index.go:116]  v2rayA is listening at http://[fe80::1a05:2bcd:c878:79ab]:2017
2023/03/17 00:55:24.396  [E] [v2rayTmpl.go:1275]  We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:55:24.396  [E] [connection.go:88]  failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 00:55:44.078  [E] [v2rayTmpl.go:1275]  We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:55:44.078  [E] [connection.go:88]  failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 00:56:23.374  [E] [v2rayTmpl.go:1275]  We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:56:23.374  [E] [connection.go:88]  failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 00:59:52.749  [E] [v2rayTmpl.go:1275]  We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:59:52.749  [E] [connection.go:88]  failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 00:59:58.934  [E] [v2rayTmpl.go:1275]  We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:59:58.934  [E] [connection.go:88]  failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 01:00:46.523  [E] [v2rayTmpl.go:1275]  We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 01:00:46.523  [E] [connection.go:88]  failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 01:00:48.539  [E] [v2rayTmpl.go:1275]  We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 01:00:48.539  [E] [connection.go:88]  failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 01:02:45.181  [E] [v2rayTmpl.go:1275]  We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 01:02:45.181  [E] [connection.go:88]  failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 01:02:56.874  [E] [v2rayTmpl.go:1275]  We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 01:02:56.874  [E] [connection.go:88]  failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 01:05:17.080  [E] [v2rayTmpl.go:1275]  We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 01:05:17.080  [E] [connection.go:88]  failed to start v2ray-core: unsupported alterID > 0: check the log for more information

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志：
2023/03/17 00:40:48.634 [I] [pre.go:159] init DB
2023/03/17 00:40:48.637 [A] [main.go:26] V2Ray binary is
2023/03/17 00:40:48.637 [A] [main.go:26] V2Ray asset directory is /run/user/0/v2raya
2023/03/17 00:40:48.637 [A] [main.go:26] v2rayA working directory is /
2023/03/17 00:40:48.637 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2023/03/17 00:40:48.637 [A] [main.go:26] Golang: go1.19.3
2023/03/17 00:40:48.637 [A] [main.go:26] OS: linux
2023/03/17 00:40:48.637 [A] [main.go:26] Arch: amd64
2023/03/17 00:40:48.637 [A] [main.go:26] Lite: false
2023/03/17 00:40:48.637 [A] [main.go:26] Version: 2.0.1
2023/03/17 00:40:48.637 [A] [main.go:26] Starting...
2023/03/17 00:40:48.637 [I] [main.go:27] the core was not running the last time v2rayA exited
2023/03/17 00:40:48.640 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2023/03/17 00:40:48.640 [A] [index.go:116] v2rayA is listening at http://192.168.56.130:2017
2023/03/17 00:40:48.640 [A] [index.go:116] v2rayA is listening at http://[::1]:2017
2023/03/17 00:40:48.640 [A] [index.go:116] v2rayA is listening at http://[fe80::1a05:2bcd:c878:79ab]:2017
2023/03/17 00:40:55.900 [E] [account.go:79] length of password should be between 6 and 32
2023/03/17 00:44:18.821 [W] [context.go:165] PostConnection: failed to connect: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:44:18.821 [E] [connection.go:36] failed to connect: failed to connect: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:44:23.731 [W] [context.go:165] PostConnection: failed to connect: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:44:23.731 [E] [connection.go:36] failed to connect: failed to connect: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:44:41.588 [W] [context.go:165] PostConnection: failed to connect: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:44:41.588 [E] [connection.go:36] failed to connect: failed to connect: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:46:16.658 [E] [connection.go:88] failed to start v2ray-core: geoip.dat or geosite.dat file does not exists. Try updating GFWList please
2023/03/17 00:49:34.152 [E] [connection.go:88] failed to start v2ray-core: failed: no server is selected. please select at least one server
2023/03/17 00:49:41.716 [E] [connection.go:88] failed to start v2ray-core: failed: no server is selected. please select at least one server
2023/03/17 00:50:07.238 [E] [v2rayTmpl.go:1275] We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:50:07.238 [E] [connection.go:88] failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 00:51:10.735 [E] [v2rayTmpl.go:1275] We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:51:10.735 [E] [connection.go:88] failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 00:53:25.712 [A] [main.go:26] V2Ray binary is /usr/local/bin/v2ray
2023/03/17 00:53:25.713 [A] [main.go:26] V2Ray asset directory is /run/user/0/v2raya
2023/03/17 00:53:25.713 [A] [main.go:26] v2rayA working directory is /
2023/03/17 00:53:25.713 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2023/03/17 00:53:25.713 [A] [main.go:26] Golang: go1.19.3
2023/03/17 00:53:25.713 [A] [main.go:26] OS: linux
2023/03/17 00:53:25.713 [A] [main.go:26] Arch: amd64
2023/03/17 00:53:25.713 [A] [main.go:26] Lite: false
2023/03/17 00:53:25.713 [A] [main.go:26] Version: 2.0.1
2023/03/17 00:53:25.713 [A] [main.go:26] Starting...
2023/03/17 00:53:25.713 [I] [main.go:27] the core was not running the last time v2rayA exited
2023/03/17 00:53:25.729 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2023/03/17 00:53:25.729 [A] [index.go:116] v2rayA is listening at http://192.168.56.130:2017
2023/03/17 00:53:25.729 [A] [index.go:116] v2rayA is listening at http://[::1]:2017
2023/03/17 00:53:25.729 [A] [index.go:116] v2rayA is listening at http://[fe80::1a05:2bcd:c878:79ab]:2017
2023/03/17 00:55:24.396 [E] [v2rayTmpl.go:1275] We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:55:24.396 [E] [connection.go:88] failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 00:55:44.078 [E] [v2rayTmpl.go:1275] We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:55:44.078 [E] [connection.go:88] failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 00:56:23.374 [E] [v2rayTmpl.go:1275] We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:56:23.374 [E] [connection.go:88] failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 00:59:52.749 [E] [v2rayTmpl.go:1275] We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:59:52.749 [E] [connection.go:88] failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 00:59:58.934 [E] [v2rayTmpl.go:1275] We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 00:59:58.934 [E] [connection.go:88] failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 01:00:46.523 [E] [v2rayTmpl.go:1275] We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 01:00:46.523 [E] [connection.go:88] failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 01:00:48.539 [E] [v2rayTmpl.go:1275] We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 01:00:48.539 [E] [connection.go:88] failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 01:02:45.181 [E] [v2rayTmpl.go:1275] We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 01:02:45.181 [E] [connection.go:88] failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 01:02:56.874 [E] [v2rayTmpl.go:1275] We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 01:02:56.874 [E] [connection.go:88] failed to start v2ray-core: unsupported alterID > 0: check the log for more information
2023/03/17 01:05:17.080 [E] [v2rayTmpl.go:1275] We do not support alterID > 0 since v1.5.6 due to security; please contact your server provider or downgrade v2rayA to v1.5.5
2023/03/17 01:05:17.080 [E] [connection.go:88] failed to start v2ray-core: unsupported alterID > 0: check the log for more information

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by tsieyy** [comment]
有同样的问题

**Comment by ranbi666** [comment]
> 2.0.4版本已经处理了这个问题，然后就是，你核心太老了，用v2fly的脚装一个吧

更新后的确好用了，谢谢。
