### ISSUE TITLE
Web 中倒序显示 log（最新的在最前）

### ISSUE THREAD

**Issue by heimoshuiyu** [v2rayA/v2rayA#853]
### 功能特性内容

应该没人想看几天前的log

**Comment by Leathong** [comment]
建议打开自动滚动到最下面，倒序显示也不好。
另外问一下，默认的 log 路径在哪里，太多了想删掉

**Comment by mzz2017** [comment]
@Leathong /var/log/v2raya/

**Comment by Leathong** [comment]
@mzz2017 我从源代码上找到的也是这个路径，但是我电脑上没有这个文件，我是 Mac

**Comment by mzz2017** [comment]
@Leathong mac在 /tmp/v2raya.log

**Comment by Leathong** [comment]
@mzz2017 找到了，感谢感谢

**Comment by heimoshuiyu** [comment]
> 建议打开自动滚动到最下面，倒序显示也不好。 另外问一下，默认的 log 路径在哪里，太多了想删掉

请问一下，可能我没有注意到，自动滚动模式在哪里呢？谢谢。

**Comment by mzz2017** [comment]
@heimoshuiyu 好像还不支持吧

**Comment by heimoshuiyu** [comment]
@mzz2017 如果倒序显示不好，希望能有自动滚动功能并默认为打开状态🙏
