### ISSUE TITLE
config.json 中的 AlterID 未能正确生成

### ISSUE THREAD

**Issue by bluaze** [v2rayA/v2rayA#854]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
    2.0.2
2. 你通过什么方式安装v2rayA
    apt
3. 你所使用的操作系统
    ubuntu 20.04

### 描述问题

v2raya 2.0.2 移除了 AlterID=0 的限制，在 Web 界面上能正常添加 AlterID>0 的节点，但若使用相应节点，在生成的 config.json 中相应节点信息漏了 AlterID，导致相应节点虽能添加，但实际不能使用

**Comment by mzz2017** [comment]
@bluaze 好的，感谢报告，稍后会修复

**Comment by mzz2017** [comment]
https://github.com/v2rayA/v2rayA/releases/tag/v2.0.4 应该修复了

**Comment by bluaze** [comment]
升了2.0.4，好了
