### ISSUE TITLE
更新2.0.4后报错，failed to start v2ray-core: cannot connect to multiple servers: v2fly/v2ray-core only feature

### ISSUE THREAD

**Issue by yuanwb1984** [v2rayA/v2rayA#860]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.4
2. 你通过什么方式安装v2rayA
apt
3. 你所使用的操作系统
armbian

### 描述问题

更新2.0.4后报错，failed to start v2ray-core: cannot connect to multiple servers: v2fly/v2ray-core only feature

### v2rayA/v2ray运行日志：
2023/03/21 11:28:44.757  [A] [main.go:26]  V2Ray binary is /usr/local/bin/xray
2023/03/21 11:28:44.758  [A] [main.go:26]  V2Ray asset directory is /run/user/0/v2raya
2023/03/21 11:28:44.758  [A] [main.go:26]  v2rayA working directory is /
2023/03/21 11:28:44.759  [A] [main.go:26]  v2rayA configuration directory is /etc/v2raya
2023/03/21 11:28:44.759  [A] [main.go:26]  Golang: go1.20.2
2023/03/21 11:28:44.759  [A] [main.go:26]  OS: linux
2023/03/21 11:28:44.759  [A] [main.go:26]  Arch: arm64
2023/03/21 11:28:44.759  [A] [main.go:26]  Lite: false
2023/03/21 11:28:44.759  [A] [main.go:26]  Version: 2.0.4
2023/03/21 11:28:44.759  [A] [main.go:26]  Starting...
2023/03/21 11:28:44.768  [I] [main.go:27]  the core was not running the last time v2rayA exited
2023/03/21 11:28:44.825  [A] [index.go:116]  v2rayA is listening at http://127.0.0.1:2017
2023/03/21 11:28:44.826  [A] [index.go:116]  v2rayA is listening at http://192.168.32.99:2017
2023/03/21 11:28:44.826  [A] [index.go:116]  v2rayA is listening at http://192.168.192.184:2017
2023/03/21 11:28:44.826  [A] [index.go:116]  v2rayA is listening at http://[::1]:2017
2023/03/21 11:28:44.826  [A] [index.go:116]  v2rayA is listening at http://[2409:8a00:6c4b:5db0:3b51:f8b5:540:337]:2017
2023/03/21 11:28:44.826  [A] [index.go:116]  v2rayA is listening at http://[fe80::2058:f762:b7ff:2ec3]:2017
2023/03/21 11:28:44.826  [A] [index.go:116]  v2rayA is listening at http://[fe80::586a:6ff:fec4:52f8]:2017
2023/03/21 11:28:55.270  [E] [connection.go:88]  failed to start v2ray-core: cannot connect to multiple servers: v2fly/v2ray-core only feature

```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。
<!-- 如果条件允许请附图 -->

**Comment by mzz2017** [comment]
@yuanwb1984 xray只能连接一个节点，或者你可以卸载xray

**Comment by yuanwb1984** [comment]
只选择一个节点后正常启动；
感谢支持xray，目前导入的reality或者vision还不能使用；
有没啥办法设置用v2ray么；

**Comment by mzz2017** [comment]
@yuanwb1984 现在只能卸载 xray，或者指定 --v2ray-bin 参数或者 V2RAYA_V2RAY_BIN 环境变量。你可以看看 /etc/default/v2raya 里面能不能写

**Comment by gbsadmin** [comment]
2.0.4 在etc/default/v2raya 里面能改其他核心，不知道V2RAYA_V2RAY_BIN 环境变量咋改

**Comment by ksong008** [comment]
> @yuanwb1984 xray只能连接一个节点，或者你可以卸载xray
这个问题是这样的，原来的版本更换节点直接点新的节点就会断开老的节点连接上新的节点，现在的2.04并不会，需要先停止v2，然后断开老节点，再连接新节点才可以。

**Comment by sjtuross** [comment]
> > @yuanwb1984 xray只能连接一个节点，或者你可以卸载xray
> > 这个问题是这样的，原来的版本如果更换节点，直接点新的节点就会断开老的节点并连接上新的节点，现在的2.04并不会，需要先停止v2，然后断开老节点，再连接新节点才可以。

同样遇到这个UI交互的问题，换一个节点有点繁琐

**Comment by mzz2017** [comment]
> > > @yuanwb1984 xray只能连接一个节点，或者你可以卸载xray
> > > 这个问题是这样的，原来的版本如果更换节点，直接点新的节点就会断开老的节点并连接上新的节点，现在的2.04并不会，需要先停止v2，然后断开老节点，再连接新节点才可以。
> 
> 同样遇到这个UI交互的问题，换一个节点有点繁琐

嗯嗯是的，这个下个版本会修的。

**Comment by ksong008** [comment]
> > > > @yuanwb1984 xray只能连接一个节点，或者你可以卸载xray
> > > > 这个问题是这样的，原来的版本如果更换节点，直接点新的节点就会断开老的节点并连接上新的节点，现在的2.04并不会，需要先停止v2，然后断开老节点，再连接新节点才可以。
> > 
> > 
> > 同样遇到这个UI交互的问题，换一个节点有点繁琐
> 
> 嗯嗯是的，这个下个版本会修的。

辛苦您了
