### ISSUE TITLE
更新到最新的v2ray-core后多路复用失效

### ISSUE THREAD

**Issue by stark-eth** [v2rayA/v2rayA#862]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?

2. What approach of installation do you install V2rayA?

3. What is your operating system?

### Description

更新到最新的v2ray-core后多路复用失效
[W] [context.go:165] PostConnection: failed to connect: cannot connect to multiple servers: v2fly/v2ray-core only feature
2023/03/22 17:27:10.710 [E] [connection.go:36] failed to connect: failed to connect: cannot connect to multiple servers: v2fly/v2ray-core only feature
2023/03/22 17:27:11.064 [W] [asm_amd64.s:1598] ObservatoryProducer: did not connect: context deadline exceeded

### Steps to reproduce

开启多路服用后无法选择多个节点

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```

 You can also paste the log that comes from web administration page

```shell
# Paste running logs here



```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by mzz2017** [comment]
@stark-eth 卸载xray可解

**Comment by stark-eth** [comment]
@mzz2017  Thanks！
