### ISSUE TITLE
Docker用不了机场链接，导入链接后，选择后点击就绪，报错

### ISSUE THREAD

**Issue by lgtice** [v2rayA/v2rayA#867]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.4
3. 你通过什么方式安装v2rayA
docker
4. 你所使用的操作系统
Ubuntu

### 描述问题

机场链接，导入链接后，选择后点击就绪，报错

### v2rayA/v2ray运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```
 或者粘贴来自 Web 页面的日志

```shell
# 此处贴入运行日志
root@ubuntu201:~# docker logs v2raya1
2023/03/24 03:40:53.540 [I] [pre.go:160]  init DB
2023/03/24 03:40:53.556 [A] [main.go:26]  V2Ray binary is /usr/bin/v2ray
2023/03/24 03:40:53.556 [A] [main.go:26]  V2Ray asset directory is /run/user/0/v2raya
2023/03/24 03:40:53.556 [A] [main.go:26]  v2rayA working directory is /root
2023/03/24 03:40:53.556 [A] [main.go:26]  v2rayA configuration directory is /etc/v2raya
2023/03/24 03:40:53.556 [A] [main.go:26]  Golang: go1.20.2
2023/03/24 03:40:53.556 [A] [main.go:26]  OS: linux
2023/03/24 03:40:53.556 [A] [main.go:26]  Arch: amd64
2023/03/24 03:40:53.556 [A] [main.go:26]  Lite: false
2023/03/24 03:40:53.556 [A] [main.go:26]  Version: 2.0.4
2023/03/24 03:40:53.556 [A] [main.go:26]  Starting...
2023/03/24 03:40:53.556 [I] [main.go:27]  the core was not running the last time v2rayA exited
2023/03/24 03:40:53.563 [A] [index.go:116]  v2rayA is listening at http://127.0.0.1:2017
2023/03/24 03:40:53.563 [A] [index.go:116]  v2rayA is listening at http://172.17.0.2:2017
2023/03/24 04:00:54.995 [I] [io.go:429]  V2Ray 5.2.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.4 linux/amd64)
2023/03/24 04:00:54.995 [I] [io.go:429]  A unified platform for anti-censorship.
2023/03/24 04:00:55.687 [I] [io.go:429]  127.0.0.1:34150 accepted tcp:127.0.0.1:0 [api-out]
2023/03/24 04:00:55.983 [I] [io.go:429]  127.0.0.1:34166 accepted tcp:127.0.0.1:0 [api-out]
2023/03/24 04:01:06.226 [I] [io.go:429]  V2Ray 5.2.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.4 linux/amd64)
2023/03/24 04:01:06.226 [I] [io.go:429]  A unified platform for anti-censorship.
2023/03/24 04:01:06.279 [W] [transparent.go:52]  writeTransparentProxyRules: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:01:06.327 [E] [setting.go:51]  invalid config: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:01:07.214 [W] [asm_amd64.s:1598]  ObservatoryProducer: did not connect: context deadline exceeded
2023/03/24 04:01:19.187 [W] [setting.go:49]  UpdateSetting: WriteIpForward: open /proc/sys/net/ipv4/ip_forward: read-only file system
2023/03/24 04:01:24.073 [W] [connection.go:86]  Connect: WriteIpForward: open /proc/sys/net/ipv4/ip_forward: read-only file system
2023/03/24 04:01:24.118 [I] [io.go:429]  V2Ray 5.2.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.4 linux/amd64)
2023/03/24 04:01:24.118 [I] [io.go:429]  A unified platform for anti-censorship.
2023/03/24 04:01:24.160 [W] [transparent.go:52]  writeTransparentProxyRules: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:01:24.208 [E] [connection.go:88]  failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:10:39.963 [W] [connection.go:86]  Connect: WriteIpForward: open /proc/sys/net/ipv4/ip_forward: read-only file system
2023/03/24 04:10:40.009 [I] [io.go:429]  V2Ray 5.2.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.4 linux/amd64)
2023/03/24 04:10:40.009 [I] [io.go:429]  A unified platform for anti-censorship.
2023/03/24 04:10:40.060 [W] [transparent.go:52]  writeTransparentProxyRules: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:10:40.112 [E] [connection.go:88]  failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:10:59.159 [W] [connection.go:86]  Connect: WriteIpForward: open /proc/sys/net/ipv4/ip_forward: read-only file system
2023/03/24 04:10:59.201 [I] [io.go:429]  V2Ray 5.2.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.4 linux/amd64)
2023/03/24 04:10:59.201 [I] [io.go:429]  A unified platform for anti-censorship.
2023/03/24 04:10:59.247 [W] [transparent.go:52]  writeTransparentProxyRules: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:10:59.302 [E] [connection.go:88]  failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
root@ubuntu201:~# 



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![image](https://user-images.githubusercontent.com/79943077/227429902-da78d300-d549-44ff-a413-c1810bca5ebf.png)

**Comment by lgtice** [comment]
root@ubuntu201:~# docker logs v2raya1
2023/03/24 03:40:53.540 [I] [pre.go:160]  init DB
2023/03/24 03:40:53.556 [A] [main.go:26]  V2Ray binary is /usr/bin/v2ray
2023/03/24 03:40:53.556 [A] [main.go:26]  V2Ray asset directory is /run/user/0/v2raya
2023/03/24 03:40:53.556 [A] [main.go:26]  v2rayA working directory is /root
2023/03/24 03:40:53.556 [A] [main.go:26]  v2rayA configuration directory is /etc/v2raya
2023/03/24 03:40:53.556 [A] [main.go:26]  Golang: go1.20.2
2023/03/24 03:40:53.556 [A] [main.go:26]  OS: linux
2023/03/24 03:40:53.556 [A] [main.go:26]  Arch: amd64
2023/03/24 03:40:53.556 [A] [main.go:26]  Lite: false
2023/03/24 03:40:53.556 [A] [main.go:26]  Version: 2.0.4
2023/03/24 03:40:53.556 [A] [main.go:26]  Starting...
2023/03/24 03:40:53.556 [I] [main.go:27]  the core was not running the last time v2rayA exited
2023/03/24 03:40:53.563 [A] [index.go:116]  v2rayA is listening at http://127.0.0.1:2017
2023/03/24 03:40:53.563 [A] [index.go:116]  v2rayA is listening at http://172.17.0.2:2017
2023/03/24 04:00:54.995 [I] [io.go:429]  V2Ray 5.2.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.4 linux/amd64)
2023/03/24 04:00:54.995 [I] [io.go:429]  A unified platform for anti-censorship.
2023/03/24 04:00:55.687 [I] [io.go:429]  127.0.0.1:34150 accepted tcp:127.0.0.1:0 [api-out]
2023/03/24 04:00:55.983 [I] [io.go:429]  127.0.0.1:34166 accepted tcp:127.0.0.1:0 [api-out]
2023/03/24 04:01:06.226 [I] [io.go:429]  V2Ray 5.2.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.4 linux/amd64)
2023/03/24 04:01:06.226 [I] [io.go:429]  A unified platform for anti-censorship.
2023/03/24 04:01:06.279 [W] [transparent.go:52]  writeTransparentProxyRules: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:01:06.327 [E] [setting.go:51]  invalid config: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:01:07.214 [W] [asm_amd64.s:1598]  ObservatoryProducer: did not connect: context deadline exceeded
2023/03/24 04:01:19.187 [W] [setting.go:49]  UpdateSetting: WriteIpForward: open /proc/sys/net/ipv4/ip_forward: read-only file system
2023/03/24 04:01:24.073 [W] [connection.go:86]  Connect: WriteIpForward: open /proc/sys/net/ipv4/ip_forward: read-only file system
2023/03/24 04:01:24.118 [I] [io.go:429]  V2Ray 5.2.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.4 linux/amd64)
2023/03/24 04:01:24.118 [I] [io.go:429]  A unified platform for anti-censorship.
2023/03/24 04:01:24.160 [W] [transparent.go:52]  writeTransparentProxyRules: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:01:24.208 [E] [connection.go:88]  failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:10:39.963 [W] [connection.go:86]  Connect: WriteIpForward: open /proc/sys/net/ipv4/ip_forward: read-only file system
2023/03/24 04:10:40.009 [I] [io.go:429]  V2Ray 5.2.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.4 linux/amd64)
2023/03/24 04:10:40.009 [I] [io.go:429]  A unified platform for anti-censorship.
2023/03/24 04:10:40.060 [W] [transparent.go:52]  writeTransparentProxyRules: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:10:40.112 [E] [connection.go:88]  failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:10:59.159 [W] [connection.go:86]  Connect: WriteIpForward: open /proc/sys/net/ipv4/ip_forward: read-only file system
2023/03/24 04:10:59.201 [I] [io.go:429]  V2Ray 5.2.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.4 linux/amd64)
2023/03/24 04:10:59.201 [I] [io.go:429]  A unified platform for anti-censorship.
2023/03/24 04:10:59.247 [W] [transparent.go:52]  writeTransparentProxyRules: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
2023/03/24 04:10:59.302 [E] [connection.go:88]  failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
: exit status 3
root@ubuntu201:~#

**Comment by MarksonHon** [comment]
建议 `sudo snap install v2raya`
虽然可能不清真
但一定管用

**Comment by Voidmort** [comment]
sudo docker run -d \
  --restart=always \
  --privileged \
  --network=host \
  --name v2raya \
  -p 2017:2017 \
  -e V2RAYA_LOG_FILE=/tmp/v2raya.log \
  -v /lib/modules:/lib/modules:ro \
  -v /etc/resolv.conf:/etc/resolv.conf \
  -v /etc/v2raya:/etc/v2raya \
  mzz2017/v2raya --transparent-hook /etc/v2raya/tproxy-hook.sh
