### ISSUE TITLE
使用brew services start v2raya/v2raya/v2raya 提示没有安装v2ray

### ISSUE THREAD

**Issue by afayge** [v2rayA/v2rayA#868]
2.0.4 版本 MacOS13.2.1

使用 brew 安装以后提示 没有安装v2ray
查看log
[A] [main.go:26]  V2Ray binary is 
后面为空白，但是使用
V2RAYA_LOG_FILE="/tmp/v2raya.log" XDG_DATA_DIRS="/opt/homebrew/share:" /opt/homebrew/opt/v2raya/bin/v2raya --lite
可以正常使用程序
在homebrew.mxcl.v2raya.plist 添加
<key>V2RAYA_V2RAY_BIN</key>
<string>/opt/homebrew/bin/v2ray</string>
可以正常运行

**Comment by MarksonHon** [comment]
`brew update; brew reinstall v2raya`
现在应该好了
