### ISSUE TITLE
How can I reset the username and password!

### ISSUE THREAD

**Issue by huangjinghuangjing** [v2rayA/v2rayA#869]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
2.0.4
2. What approach of installation do you install V2rayA?
installed v2raya via brew
3. What is your operating system?
macOS 13.2.1

### Description
I have forgotten my username and password, and command "sudo v2raya --reset_password" doesn't work. I excuted this command and restarted v2raya via "brew services restart v2raya". But it still presented wrong username or password.

**Comment by mzz2017** [comment]
@huangjinghuangjing 应该不用sudo，加--lite参数，然后用-c指定配置文件目录，具体目录在哪里可以看看服务里怎么写的

**Comment by MarksonHon** [comment]
brew services stop v2raya
v2raya --reset-password
brew services start v2raya

**Comment by MarksonHon** [comment]
Add reset password notice if you are using `v2raya` or `v2raya-unstable` while you are installing,
see more in https://github.com/v2rayA/homebrew-v2raya
