### ISSUE TITLE
群晖docker运行不能透明代理

### ISSUE THREAD

**Issue by Eureka321** [v2rayA/v2rayA#87]
报错信息类似：
github.com/mzz2017/v2rayA/common/cmds: iptables-legacy -t mangle -A PREROUTING -m socket --transparent -j SSTP_ONCE iptables v1.8.3 (legacy): Couldn't load match `socket':No such file or directory
transparent.go:43: github.com/mzz2017/v2rayA/common/cmds: iptables-legacy -t nat -A V2RAY -m mark --mark 0xff -j RETURN iptables v1.8.3 (legacy): Couldn't load match `mark':No such file or directory
transparent.go:26: github.com/mzz2017/v2rayA/core/v2ray: [WARNING] DropSpoofing can't be enable > github.com/mzz2017/v2rayA/common/cmds: BADIP="127.0.0.1 0.0.0.0";for IP in $BADIP ;do hexip=$(printf '%02X ' ${IP//./ }; echo) ;iptables-legacy -A DROP_SPOOFING -p udp --sport 53 -m string --algo bm --hex-string "|0004$hexip|" --from 60 --to 180 -j DROP ;done iptables v1.8.3 (legacy): Couldn't load match `string':No such file or directory
该如何排查？

**Comment by mzz2017** [comment]
已了解问题，请换用0.7.0.5版本，后面我会进行修复

**Comment by Eureka321** [comment]
感谢回复，重新安装了0.7.0.5版本，启动时出现类似错误，供参考。
transparent.go:35: v2rayA/common/cmds: iptables-legacy -t nat -A V2RAY -m mark --mark 0xff -j RETURN iptables v1.8.3 (legacy): Couldn't load match `mark':No such file or directory

**Comment by Eureka321** [comment]
0.7.0.5版本，连接机场时提示：
fail in connecting > v2rayA/core/v2ray: v2rayA/core/v2ray: not support transparent proxy: > v2rayA/common/cmds: iptables-legacy -t nat -A V2RAY -m mark --mark 0xff -j RETURN iptables v1.8.3 (legacy): Couldn't load match `mark':No such file or directory Try `iptables -h' or 'iptables --help' for more information. > exit status 2

**Comment by mzz2017** [comment]
你的群晖iptables重装一下

**Comment by Eureka321** [comment]
> 你的群晖iptables重装一下

感谢回复！尴尬的是，我研究了一下，但并不知道应该如何重装iptables，于是我重启了nas，重装了v2raya0.7.0.5，第一次能够连接节点，但是第二次连接，以及打开全局透明代理时仍会报错。
参考信息：
[Warning] v2rayA/core/v2ray: v2rayA/core/v2ray: not support transparent proxy:  > v2rayA/common/cmds: iptables-legacy -t nat -A V2RAY -m mark --mark 0xff -j RETURN iptables v1.8.3 (legacy): Couldn't load match `mark':No such file or directory
[Warning] fail in connecting > v2rayA/core/v2ray: v2rayA/core/v2ray: not support transparent proxy:  > v2rayA/common/cmds: iptables-legacy -t nat -A V2RAY -m mark --mark 0xff -j RETURN iptables v1.8.3 (legacy): Couldn't load match `mark':No such file or directory

期待更新！

**Comment by Eureka321** [comment]
补充说明，其实就是在打开了“全局透明代理之后出错”，不打开该功能则正常可用。

**Comment by mzz2017** [comment]
出现这个报错就不是v2raya的问题了，你的iptables模块不全，需要安装。
