### ISSUE TITLE
检测到 geosite.dat, geoip.dat 文件或 v2ray-core 可能未正确安装，请检查

### ISSUE THREAD

**Issue by disini** [v2rayA/v2rayA#870]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
     2.0.4

3. 你通过什么方式安装v2rayA
   dpkg -i installer_debian_amd64_2.0.4.deb

5. 你所使用的操作系统
ubuntu 22.04

### 描述问题：

安装完之后运行程序，自动打开了http://127.0.0.1:2017/这个地址
然后我选择批量导入，把一堆vmess地址导了进来，然后点击第一行后面的“选择，修改，分享”里的选择按钮，点完就弹出了这个报错
有时候是中文，有时候是英文：

检测到 geosite.dat, geoip.dat 文件或 v2ray-core 可能未正确安装，请检查
failed to connect: failed to connect: geoip.dat or geosite.dat file does not exists

求大佬指点迷津？是我哪里操作的不对吗？

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

![图片](https://user-images.githubusercontent.com/5233769/227616192-ff10dd32-34af-4dbb-8e6d-032e568fb844.png)

**Comment by MarksonHon** [comment]
https://v2raya.org
去照着文档装个核心

**Comment by lxin98** [comment]
我也有遇到，不知道怎么解决

**Comment by disini** [comment]
> 

就是按照这个文档来的，试了好几次都不行欸？

**Comment by disini** [comment]
> 

兄弟你解决了吗？

**Comment by lxin98** [comment]
解决了

**Comment by lxin98** [comment]
手动把核心降级到 4.45就可以

**Comment by disini** [comment]
> https://v2raya.org 去照着文档装个核心

非常感谢，可以了！

**Comment by disini** [comment]
> 手动把核心降级到 4.45就可以

哦噢，我前两天试了下用最新版核心也可以了！

**Comment by disini** [comment]
> 手动把核心降级到 4.45就可以

@lxin98 

请问如何手动降低核心版本呢？这个核心的路径是在哪个文件里配置的呢？多谢！

**Comment by guoapeng** [comment]
我也遇到类似的问题

## 环境说明

我使用的是ubuntu 22.04.1
安装方式是下载v2raya deb包(版本2.2.4.3)进行安装, 安装完成, 访问v2ray web也遇到这样的错误提示.

## 问题排查:

使用命令查询安装了哪些包? 发现v2raya根本就没有带v2ray-core核心的任何文件, 因此会报错缺少geosite.dat, geoip.dat. 
其根本原因是却了整个v2ray核心.  

```bash
dpkg-query -L v2raya
```

output

```bash
/etc
/etc/default
/etc/default/v2raya
/usr
/usr/bin
/usr/bin/v2raya
/usr/share
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/512x512
/usr/share/icons/hicolor/512x512/apps
/usr/share/icons/hicolor/512x512/apps/v2raya.png
/usr/share/applications
/usr/share/applications/v2raya.desktop
/usr/share/doc
/usr/share/doc/v2raya
/usr/share/doc/v2raya/changelog.gz
/usr/lib
/usr/lib/systemd
/usr/lib/systemd/system
/usr/lib/systemd/system/v2raya.service
/usr/lib/systemd/user
/usr/lib/systemd/user/v2raya-lite.service
```

## 解决方案
找到了问题原因, 解决起来就比较容易了, 于是手动安装核心v2ray或者xray, 这里以v2ray为例. 当然由于文档写得很混乱很差, 很多连接失效, 也没有那么容易.

于是去 https://github.com/v2fly/v2ray-core/releases 下载核心, 目前最新的版本是v5.11.0, 就使用它了.

```bash

# 下载核心
wget -o /tmp/v2ray-linux-64.zip https://github.com/v2fly/v2ray-core/releases/download/v5.11.0/v2ray-linux-64.zip
# 将其解压到
unzip /tmp/v2ray-linux-64.zip -d /usr/local/v2ray-core
```
> 如何使用命令行下载很慢, 这里陷入一个矛盾, 但是需要自己想办法下载这个文件, 说不定在哪个犄角旮旯能找到文件.  由于众所周知的原因, 我只能帮助到这里了. 

修改配置让v2raya 使用v2ray-core

```bash

vi /etc/default/v2raya

# 添加配置
V2RAYA_V2RAY_BIN=/usr/local/v2ray-core/v2ray
V2RAYA_V2RAY_CONFDIR=/usr/local/v2ray-core

```

重启服务

```bash
systemctl restart v2raya
```
## 验证

再次访问v2ray web ui, 错误消失.

**Comment by disini** [comment]
非常感谢！ @guoapeng

**Comment by szliugx** [comment]
处理完 v2ray-core 后要等一会儿，提示要下载缺失的数据，我挂着睡觉了，起床后再打开就可以了
