### ISSUE TITLE
Docker V2raya on MacOS : ObservatoryProducer: did not connect: context deadline exceeded

### ISSUE THREAD

**Issue by superben** [v2rayA/v2rayA#873]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
V2.0.4

2. 你通过什么方式安装v2rayA
Dcoker

5. 你所使用的操作系统
MacOS 13.2.1 

### 描述问题：

选择某节点后，log出现：
 [W] [asm_arm64.s:1172]  ObservatoryProducer: did not connect: context deadline exceeded

### v2rayA运行日志（Optional）：

 ```bash
 # docker mode
docker run -d \
  -p 2017:2017 \
  -p 20170-20172:20170-20172 \
  --restart=always \
  --name v2raya \
  -e V2RAYA_LOG_FILE=/etc/v2raya/v2raya.log \
  -v /Users/xxxxxxxxxxxxx/Applications/v2raya:/etc/v2raya \
  mzz2017/v2raya


cd  /Users/xxxxxxxxxxxxx/Applications/v2raya/
tail -f  v2raya.log
 ```
2023/03/26 20:38:14.862  [I] [io.go:429]  V2Ray 5.2.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.4 linux/arm64)
2023/03/26 20:38:14.862  [I] [io.go:429]  A unified platform for anti-censorship.
2023/03/26 20:38:15.352  [I] [io.go:429]  127.0.0.1:35364 accepted tcp:127.0.0.1:0 [api-out]
2023/03/26 20:38:15.840  [W] [asm_arm64.s:1172]  ObservatoryProducer: did not connect: context deadline exceeded
2023/03/26 20:38:15.844  [I] [io.go:429]  127.0.0.1:35372 accepted tcp:127.0.0.1:0 [api-out]

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
macOS 下建议用 brew 去装，而不要用 Docker
https://v2raya.org/docs/prologue/installation/macos/

**Comment by superben** [comment]
感谢建议。的确，用brew安装是好用的，但是中间费了些周折。最后，通过指定V2RAYA_V2RAY_BIN解决了。没解决前，就尝试下用docker方式部署，结果还是没成功，提这个issue就是想深入了解下项目，请大神提示下，看看怎么解决掉。

**Comment by superben** [comment]
另外，建议MacOS用 brew 去装，而不用 Docker，理由是什么呢？非常感谢回复，绝没有冒犯的意思。

**Comment by mzz2017** [comment]
主要是docker版本很久没有维护了，因为大家都在用brew安装。如果你调好了docker怎么弄，欢迎帮忙更新文档！

**Comment by MarksonHon** [comment]
V2RAYA_V2RAY_BIN 现在应该不需要了，brew的服务文件目前添加了brew自身的path，可以检测到brew装好的xray或v2ray

**Comment by palemoons** [comment]
这个报错不仅在docker里会出现，使用brew安装并运行也会出现一样的log

**Comment by mzz2017** [comment]
@hv0912 日志里是怎么说呢

**Comment by MarksonHon** [comment]
2.0.5 应该没问题了，有问题就再新开吧
