### ISSUE TITLE
Failed to execute command "xdg-open "http://127.0.0.1:2017"".

### ISSUE THREAD

**Issue by xLordHerox** [v2rayA/v2rayA#874]
Hi guys. 

I have a problem when I want to open v2rayA on my Ubuntu server.
Please help me, guys.

![v2rayA](https://user-images.githubusercontent.com/69323214/227781502-d337ff31-eb51-4531-94c9-cfdc944d4e71.png)

**Comment by mzz2017** [comment]
@xLordHerox apt-get install xdg-utils

**Comment by xLordHerox** [comment]
> @xLordHerox apt-get install xdg-utils

Thanks. works.
