### ISSUE TITLE
无法访问v2raya.org

### ISSUE THREAD

**Issue by Caesar6666666** [v2rayA/v2rayA#875]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
Version: 2.0.4

2. 你通过什么方式安装v2rayA
docker

3. 你所使用的操作系统
fedora 37

### 描述问题：

无论使用什么配置都无法访问v2rayA.org，其他国内外网站都正常。
手机使用同样节点的clash无问题

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

v2raya 的dns查询
![image](https://user-images.githubusercontent.com/53715073/227786183-5e086abe-5847-4708-9ce2-1262c57d8640.png)

### 现在使用routingA 配置
default: proxy

domain(domain:mail.qq.com)->direct
domain(domain:v2raya.org)->proxy
domain(geosite:google-scholar)->proxy
domain(geosite:category-scholar-!cn, geosite:category-scholar-cn)->direct
domain(geosite:geolocation-!cn, geosite:google)->proxy
domain(geosite:cn)->direct
ip(geoip:hk,geoip:mo)->proxy
ip(geoip:private, geoip:cn)->direct

### v2raya配置
![image](https://user-images.githubusercontent.com/53715073/227786647-0f92644c-7e3e-4a53-998d-ad944015ef96.png)

**Comment by Caesar6666666** [comment]
今天又变成了https://v2raya.org/和 https://v2raya.org/docs/prologue/introduction/ 这个两个页面可以访问，其他页面无法访问。太奇怪了。

**Comment by sgao318** [comment]
从昨天开始就访问不到v2raya.org了，被黑了吗？
