### ISSUE TITLE
日志里有大量websocket报错,是为啥

### ISSUE THREAD

**Issue by TcDhlPro** [v2rayA/v2rayA#879]
2023/03/31 01:41:21.349 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:41:25.352 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:41:29.349 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:41:33.366 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:41:37.356 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:41:41.376 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:41:45.378 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:41:49.392 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:41:53.431 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:41:57.505 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:42:01.610 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:42:05.885 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:42:10.045 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:42:15.013 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:42:24.175 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:42:29.566 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:42:38.239 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:42:44.311 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:42:51.932 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:43:00.781 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:43:05.702 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2023/03/31 01:43:12.373 [E] [message.go:22] websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

**Comment by MarksonHon** [comment]
反向代理控制页面是需要 upgrade websocket 的

**Comment by TcDhlPro** [comment]
就是反向代理127.0.0.1:2017的v2rayA页面, 需要nginx里配置好upgrade websocket?

**Comment by TcDhlPro** [comment]
> @TcDhlPro https://v2raya.org/docs/advanced-application/nginx-prefix-deploy/ 这里有个示例
谢谢, 直接解决问题!
http {
  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }
  server {
    listen 8080;
    server_name example.com;
    location ^~ /v2raya {
      proxy_redirect off;
      proxy_set_header Accept-Encoding "";
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      rewrite ^/v2raya$ / break;
      rewrite ^/v2raya/(.*)$ /$1 break;
      sub_filter '\"static/' '\"/v2raya/static/';
      sub_filter '\"/api' '\"/v2raya/api';
      sub_filter_once off;
      sub_filter_types application/javascript;
      proxy_pass http://127.0.0.1:2017;
    }
  }
}

**Comment by Fengikjing** [comment]
我现在也是这个报错，我用的nginx的可视化面板进行操作的  现在不知道怎么改上面的代码进行替换
![image](https://github.com/v2rayA/v2rayA/assets/81843759/7516f02d-5ee2-486c-b189-75f8e9478a1d)

**Comment by Fengikjing** [comment]
我用的还是泛域名，不是网址/v2ray的方式，是v2ray.xxx.com:443这样子   然后用上面这个改  改不出来。。。

**Comment by Fengikjing** [comment]
@TcDhlPro 能帮忙看看吗

**Comment by TcDhlPro** [comment]
> @TcDhlPro 能帮忙看看吗

我已经不用这个了, 因为解决完一个问题, 又会有新的问题出来, 难绷....
