### ISSUE TITLE
socks代理时不会分流？

### ISSUE THREAD

**Issue by Eureka321** [v2rayA/v2rayA#88]
是否可以设置？还是设计如此？

**Comment by mzz2017** [comment]
设计如此。高级配置可以使用routingA开个socks端口inbound，并手动设计路由规则，该端口则可以分流

**Comment by mzz2017** [comment]
类似的高级功能实现可以通过[RoutingA](https://github.com/mzz2017/v2rayA/wiki/RoutingA)实现，下面是你提到的功能的routingA写法：
```python
# 下一行定义socks5出站协议，无用户密码的socks5协议则去除下面的user和pass
inbound: socksin = socks(address:"0.0.0.0", port:"1080", user: "my-username", pass: "my-password")
default: proxy
# 下面两行定义大陆域名和IP直连，以及内网直连
domain(geosite:cn)->direct
ip(geoip:private, geoip:cn)->direct
```

**Comment by Eureka321** [comment]
十分感谢您的回复！我之前用原版v2ray运行于docker实现了http和socks双协议监听的代理，但是您的版本可以更方便的管理节点，非常感谢！但是经过一段时间的使用，设置代理（无论http或者socks）对于一些系统（如Android TV）或者软件（如Sonarr）存在一些或多或少的内网或者外网访问问题，是我无力解决的，只能想办法Work around。所以还是十分期待您的新版本透明代理的在synology docker上的完美运行！感恩！

**Comment by mzz2017** [comment]
对于iptables模块支持不全的系统，将来只能考虑使用tun设备的透明代理实现来进行透明代理的支持，这在计划中是较为延后的，如果可能，建议尝试修复iptables的问题。

**Comment by FredyVia** [comment]
> 类似的高级功能实现可以通过[RoutingA](https://github.com/mzz2017/v2rayA/wiki/RoutingA)实现，下面是你提到的功能的RoutingA写法：
> 
> ```python
> # 下一行定义socks5入站协议，无用户密码的socks5协议则去除下面的user和pass
> inbound: socksin = socks(address:"0.0.0.0", port:"1080", user: "my-username", pass: "my-password")
> default: proxy
> # 下面两行定义大陆域名和IP直连，以及内网直连
> domain(geosite:cn)->direct
> ip(geoip:private, geoip:cn)->direct
> ```

非常抱歉打扰您，我看了你的routingA的项目，但是不知道怎么通过routingA解析这些，以及解析完之后应该怎么做，我在routingA里面没看到相关的介绍，我没接触过go语言，这是我通过命令行在routingA的项目克隆文件夹下:
修改`parser_test.go`里面的program赋值后执行的
`go test -v parser_test.go  parser.go routingA.go rules.go semantics.go symbol.go syntaxTree.go table.go` 
但是得到输出:
```
fredyvia@littlebee:~/routingA$ go test -v parser_test.go  parser.go routingA.go rules.go semantics.go symbol.go syntaxTree.go table.go 
=== RUN   TestParse
--- PASS: TestParse (0.00s)
    parser_test.go:26: default proxy
    parser_test.go:22: [{domain [] map[geosite:[cn]]}] direct
    parser_test.go:22: [{ip [] map[geoip:[private cn]]}] direct
PASS
ok      command-line-arguments  0.006s
```
我这样做对吗，得到这些输出之后又该怎么做呢?非常感谢!

**Comment by mzz2017** [comment]
@FredyVia 
![image](https://user-images.githubusercontent.com/30586220/109923419-baf12980-7cf9-11eb-960c-b12d080d0e41.png)
