### ISSUE TITLE
MacbookPro: no proxy IP address was seen to the outside world

### ISSUE THREAD

**Issue by niugeba** [v2rayA/v2rayA#883]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
2.0.4
2. What approach of installation do you install V2rayA?
Brew
3. What is your operating system?
Monterey 12.6 and 12.6.4, on two MacbookPro 

### Description

I had 2.0.1 installed on one macbookPro, but it was never worked. I thought it was related to bug #849 and used another APP "v2rayU" for VPN. Today I  just used brew to update  v2raya to 2.0.4. I could confirm #849 indeed fixed the "alterID >0" error. However,  I am still not able to VPN out after running command "v2raya --light". There is no error message from the console, and I could pick a VPN server from web client at 127.0.0.1:2017. I could select a known good VPN address, and  start it and see the state becomes running. However, i am still not be able to VPN out. Then I found out that my ip address from website ipaddress.my was always my public IP address, regardless which VPN server i was trying to connect. This seems to be odd, as if i am using "v2rayU" with the same VPN server, i could see my VPN ip address on ipaddress.my website. 
It's the same issue on another Macbookpro running Montenery 12.6 with fresh installed 2.04 using brew.

So it seems that even though everything seems to be normal, no VPN IP address was actually assigned. What am I missing?

### Steps to reproduce

- brew tap v2raya/v2raya
- brew install v2raya/v2raya/v2raya
- issue v2raya --light in terminal
- go to 127.0.0.1:2017, pick a VPN server that was known to be good with other app like v2rayU, start it, and the state becomes "running"
- go to ipaddress.my, and see the IP reported. In my case, it is still my public IP
- Pick another VPN server, still only see public IP. 

### Logs：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log
 
 # docker mode
 docker logs v2raya
 ```

 You can also paste the log that comes from web administration page

```shell
# Paste running logs here
v2raya --light
2023/04/02 00:29:56.828 [A] [main.go:26]  V2Ray binary is /usr/local/bin/v2ray
2023/04/02 00:29:56.828 [A] [main.go:26]  V2Ray asset directory is /Users/niugeba/Library/Application Support/v2raya
2023/04/02 00:29:56.828 [A] [main.go:26]  v2rayA working directory is /Users/niugeba/.V2rayU
2023/04/02 00:29:56.828 [A] [main.go:26]  v2rayA configuration directory is /Users/niugeba/Library/Application Support/v2raya
2023/04/02 00:29:56.828 [A] [main.go:26]  Golang: go1.20.2
2023/04/02 00:29:56.828 [A] [main.go:26]  OS: darwin
2023/04/02 00:29:56.828 [A] [main.go:26]  Arch: amd64
2023/04/02 00:29:56.828 [A] [main.go:26]  Lite: true
2023/04/02 00:29:56.828 [A] [main.go:26]  Version: v2.0.4-brew
2023/04/02 00:29:56.828 [A] [main.go:26]  Starting...
2023/04/02 00:29:57.208 [I] [io.go:429]  V2Ray 5.3.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.5 darwin/amd64)
2023/04/02 00:29:57.208 [I] [io.go:429]  A unified platform for anti-censorship.
2023/04/02 00:29:58.288 [I] [io.go:429]  127.0.0.1:55108 accepted tcp:127.0.0.1:0 [api-out]
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://127.0.0.1:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[::1]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::1]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::93:21fc:1e15:73cf]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://172.20.3.159:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::4079:42ff:fee3:c3cf]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::4079:42ff:fee3:c3cf]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::fca8:51ff:f00c:1c67]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::4d52:77a9:2d91:4927]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::ce81:b1c:bd2c:69e]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::63db:1196:e022:fec6]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::cfae:1cd5:f159:6fbb]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::db83:13b2:d0ac:4b25]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::9175:f745:ffc5:7901]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::655a:ec10:e3de:cb2e]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::91e6:91b7:f66d:fa61]:2017
2023/04/02 00:29:58.313 [A] [index.go:116]  v2rayA is listening at http://[fe80::1823:7f74:fde:cf60]:2017

---------- After I have configured a new VPN server---------------------
2023/04/02 00:31:11.483 [I] [io.go:429]  V2Ray 5.3.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.5 darwin/amd64)
2023/04/02 00:31:11.484 [I] [io.go:429]  A unified platform for anti-censorship.
2023/04/02 00:31:12.485 [I] [io.go:429]  127.0.0.1:55141 accepted tcp:127.0.0.1:0 [api-out]


```

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.

**Comment by MarksonHon** [comment]
Tools based on v2ray can never be a VPN software, they may just use tun/tap to hijack all traffic to a socks port(tun2socks), and all of then will NOT forward ICMP at all.
v2rayA don't have tun2socks support, if you want to proxy your traffic, just enable system proxy.

**Comment by niugeba** [comment]
Sorry that the word "VPN" is misleading in my previous description. Rather what I meant was v2ray servers or VPSs for outbound traffic. So are you telling me that for v2rayA support, there is no new IP address seen on the local macbookpro, yet it will have a new IP address seen by the outside if other APP like Shadowrocket or v2rayU is used? As i mentioned, if I use v2rayU, the outside will see a new IP address for my mac, yet if I use v2rayA, the outside still sees my own public IP. If it is normal behavior for the IP part, what more information do you need to debug?

**Comment by niugeba** [comment]
Thinking more,  the new IP address should be the VPS proxy seen by outside world. So in theory, I should expect the outside world to see the VPS proxy IP for v2rayA as well if all outbound traffic goes to the proxy first as it's configure. In that case, what went wrong here in my setup? thanks

**Comment by niugeba** [comment]
I think your suggestion of turn on the system proxy in the settings of v2rayA client page works for me. I don't know why it is off in the first place for mac users. Anyways, thanks for your suggestions.
