### ISSUE TITLE
修改网页端用户界面

### ISSUE THREAD

**Issue by huge-pancake** [v2rayA/v2rayA#885]
### 您想提出的功能特性是否和现有问题相关？
否

### 功能特性内容
用 [Vuetify](https://vuetifyjs.com/) 组件库重构网页端用户界面

**Comment by MarksonHon** [comment]
Great job! so could please tell us where is your code?😀

**Comment by huge-pancake** [comment]
What a friendly guy...

**Comment by huge-pancake** [comment]
It's just an idea so far, I'll contribute if you guys like it

**Comment by cubercsl** [comment]
@huge-pancake PR is always welcomed~

**Comment by huge-pancake** [comment]
I will try when I have time
