### ISSUE TITLE
openwrt中v2raya_2.0.4-1_x86_64包无法使用

### ISSUE THREAD

**Issue by ylu19870105** [v2rayA/v2rayA#888]
openwrt版本为
openwrt-21.02.5-x86-64-generic-ext4-combined-efi
openwrt为旁路由方式部署因此只配置了一个lan IP地址
v2rays版本为
v2raya - 2.0.4-1 - v2rayA is a V2Ray Linux client supporting global transparent proxy, compatible with SS, SSR, Trojan(trojan-go), PingTunnel protocols.
我通过
opkg update
opkg intstall v2raya
安装包没有提示安装失败信息。v2raya也正常加入了openwrt的startup启动项之中。
但是访问2017端口失败。感像是gui服务没有正常启动。重启也是一样

**Comment by shynome** [comment]
同样的问题, 这些依赖有一些需要升级但依赖声明用的还是老的导致的, 手动更新下面这些依赖就可以了. 
```
opkg update
opkg install \
    ca-bundle \
    ip-full \
    iptables-mod-conntrack-extra \
    iptables-mod-extra \
    iptables-mod-filter \
    iptables-mod-tproxy \
    kmod-ipt-nat6
```

**Comment by MarksonHon** [comment]
进群聊吧：https://t.me/v2raya_zh
