### ISSUE TITLE
官方文档的"误导性"建议

### ISSUE THREAD

**Issue by luciddream-tsin** [v2rayA/v2rayA#893]
### 您想提出的功能特性是否和现有问题相关？

在官方文档的安装教程里，如果网站页面是英文版本，win系统的指令是:

```cpp
winget install --id v2raya.win
```

如果是中文版，安装指令是:
```cpp
winget install --id v2rayA.v2rayA
```
关键的问题是，如果一个位于中国的新手，不小心打开了英文界面，
执行了对应的安装命令，他将一直卡在哪里，不知所措。。。

### 功能特性内容

如果能在官网添加一个提示，将会消除这种误会。

**Comment by MarksonHon** [comment]
啊 忘了翻译了 不过以前这个安装ID是存在的 后来被微软那边的人给我手动合并到v2rayA.v2rayA了，有兴趣可以来文档首页提交翻译，有翻译平台可用

**Comment by MarksonHon** [comment]
Fixed
