### ISSUE TITLE
failed to start v2ray-core: core version too low: the version 4.34.0 is lower than 5.0.0

### ISSUE THREAD

**Issue by redscience** [v2rayA/v2rayA#902]
failed to start v2ray-core: core version too low: the version 4.34.0 is lower than 5.0.0

How to resolve this error message?

**Comment by redscience** [comment]
The version of v2ray-core is not v5. Use v5 or downgrade v2rayA to v1.5

**Comment by redscience** [comment]
I did this installation method:
https://v2raya.org/en/docs/prologue/installation/debian/

Install v2rayA
Method 1: Install through the software source
Add public key
wget -qO - https://apt.v2raya.org/key/public-key.asc | sudo tee /etc/apt/trusted.gpg.d/v2raya.asc
Add V2RayA software source
echo "deb https://apt.v2raya.org/ v2raya main" | sudo tee /etc/apt/sources.list.d/v2raya.list
sudo apt update
Install V2RayA
sudo apt install v2raya

**Comment by MarksonHon** [comment]
Use script to install v2ray core at first.
https://v2raya.org/en/docs/prologue/installation/debian/#mirror-script-provided-by-v2raya-recommended
