### ISSUE TITLE
希望以命令行的方式配置v2raya,但是查看官方文档好像没有发现可以命令行的方式配置v2raya

### ISSUE THREAD

**Issue by 5huanghuai** [v2rayA/v2rayA#903]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
V2Ray 5.3.0
2. 你通过什么方式安装v2rayA
软件源
3. 你所使用的操作系统
ubuntu

### 描述问题：

如何以命令行的方式配置v2raya,但是查看官方文档好像没有发现可以命令行的方式配置v2raya

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by mzz2017** [comment]
@5huanghuai pr welcome

**Comment by 5huanghuai** [comment]
> @5huanghuai pr welcome

对不起，我好像没明白什么意思。我刚才搜索了"pr welcome ",好像是使用拉取请求来配置v2raya吗？

**Comment by mzz2017** [comment]
@5huanghuai 欢迎来提交你的代码

**Comment by MarksonHon** [comment]
Ubuntu 用户可以打开终端，然后：
`sudo snap install v2raya`
纯命令行 非常简单

**Comment by be-engineer** [comment]
他的意思应该是说可以通过命令行来改变v2raya的各种参数。我其实也有这个想法，因为在使用过程中发现v2raya运行一段时间后代理就会失效（不知为什么），但是重新关闭再启动又正常，所以想通过脚本来监控v2ray，如果代理失败，就关闭代理再重启一次，但是没看到命令行有该功能
