### ISSUE TITLE
不能代理ipv6 

### ISSUE THREAD

**Issue by qian9008** [v2rayA/v2rayA#906]
虽然v4代理了 可以翻墙，但是泄露了 客户机的真实v6地址。

**Comment by qian9008** [comment]
> 你是docker？

openwrt

**Comment by mzz2017** [comment]
@qian9008 你可以在openwrt config那里把ipv6支持给设on看看

**Comment by mzz2017** [comment]
@qian9008 是在v2raya有个config文件来着

**Comment by ogios** [comment]
请问您是如何解决的

**Comment by ogios** [comment]
好了，在/etc/v2raya/config.json里把inbounds跟ipv4相关的监听复制粘贴一份改为ipv6的之后重启服务就可以了

**Comment by chouhai110** [comment]
请求时如何解决的，可是提供下配置相关配置信息吗 @ogios

**Comment by ogios** [comment]
@chouhai110 现在不用这么干，运行的时候参数加上`--ipv6-support`就好
下面这个是`/usr/share/applications/v2raya.desktop`的服务，改`Exec`就行
```
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=v2rayA
Categories=Network;
Keywords=Internet;VPN;Proxy;v2ray;v2raya
# Exec=xdg-open "http://127.0.0.1:2017"
Exec=/bin/v2raya --ipv6-support
Icon=/usr/share/icons/hicolor/512x512/apps/v2raya.png
```
