### ISSUE TITLE
请问是否支持 xtls-rprx-vision 下的reality ?

### ISSUE THREAD

**Issue by lionkingc** [v2rayA/v2rayA#910]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.5
2. 你通过什么方式安装v2rayA
手工安装ipk
3. 你所使用的操作系统
openwrt

### 描述问题：

你好,请问是否支持 xtls-rprx-vision 下的reality ?
后台看XRAY已升级到1.8.0-1 , 
V2RAYA 的UI里点新增, 选VLESS, 但没有地方填对应的选项

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by lionkingc** [comment]
我看别人DOCKER安装的, UI里有FLOW选项, 我用OPENWRT安装的最新的版本, UI里没有这个选项.

<img width="400" alt="222" src="https://user-images.githubusercontent.com/23330617/231348555-ddb410a3-ed36-4f81-a234-982fe81a3247.png">


![lala im_2021-04-16_15-40-30](https://user-images.githubusercontent.com/23330617/231348299-eaaba532-207d-4c02-a2a9-dff1b679dc0b.png)

**Comment by heycharliek** [comment]
I have the same question!

**Comment by cYobject** [comment]
这个flow的功能选项 ，好像是存在于docker的镜像中，[installer_debian_amd64_2.0.5.deb]中同样没有(https://github.com/v2rayA/v2rayA/releases/download/v2.0.5/installer_debian_amd64_2.0.5.deb)

**Comment by xxSaeidxx** [comment]
Does V2rayA support Reality protocol? @mzz2017

**Comment by Cuans** [comment]
XRay支持的情况下，使用v2rayA正常配置vless(tcp+tls) 只是没有flow 选项xtls-rprx-vision，可以先不用管。
如何运行下面的脚本强制将配置文件中加上"flow":"xtls-rprx-vision"

运行下面脚本后，在v2rayA中点击左上角启动，启动完成后停止下面的脚本即可加上对xtls-rprx-vision的支持了。
#!/bin/bash
while true
do  
    sed -i 's/ption":"none"}/ption":"none","flow":"xtls-rprx-vision"}/'  /etc/v2raya/config.json
done

**Comment by JAM2199562** [comment]
> XRay支持的情况下，临时解决办法可以使用v2rayA正常配置vless(tcp+tls) 只是没有flow 选项xtls-rprx-vision，可以先不用管。 然后运行下面的脚本强制将配置文件中加上"flow":"xtls-rprx-vision"
> 
> 运行下面脚本后，在v2rayA中点击左上角启动，启动完成后停止下面的脚本即可加上对xtls-rprx-vision的支持了。（必须在运行脚本的情况，点击代理启动）（该方法是一次性的） #!/bin/bash while true do sed -i 's/ption":"none"}/ption":"none","flow":"xtls-rprx-vision"}/' /etc/v2raya/config.json done

非常好用，感谢了，有需要的可以再加一句
> sed -i 's/listen":"127.0.0.1/listen":"0.0.0.0/' /etc/v2raya/config.json

**Comment by iwoow** [comment]
哈哈哈哈哈哈哈哈哈哈哈哈哈，死循环果然万能。

**Comment by iwoow** [comment]
现有的开发者们应该确实是没时间也没意愿搞这个免费又麻烦的东西了，很多代码段都能明显感觉到他们：“能写死的尽量写死，尽量避免增加UI、尽量避免去实现一切可有可无的判断逻辑”，一句话，能不写尽量不写，能不改尽量不动。

**Comment by mczy** [comment]
> 

没有publickey shortid servername也可以吗

**Comment by raijintt** [comment]
windows下要怎么弄呢？似乎选不了xtls

**Comment by ztatw** [comment]
this branch `feat_v5` is supported xray, if you use xray as the app kernel, it supports xtls, you can check with the front-end source code

but I find something wrong with the current commit, I need some code change to use xtls+rprx+vision:

the latest xray requires xtls+rprx+vision and `security: tls` and `tlsSetting`, but the current version will use `security:xtls` and `xtlsSetting`, which is depreated by xray now, so I need following changes

```diff
diff --git a/service/core/serverObj/v2ray.go b/service/core/serverObj/v2ray.go
index b36a865..1a694b0 100644
--- a/service/core/serverObj/v2ray.go
+++ b/service/core/serverObj/v2ray.go
@@ -350,7 +350,7 @@ func (v *V2Ray) Configuration(info PriorInfo) (c Configuration, err error) {
 		default:
 			return Configuration{}, fmt.Errorf("unexpected transport type: %v", v.Net)
 		}
-		if strings.ToLower(v.TLS) == "tls" {
+		if strings.ToLower(v.TLS) == "tls" || strings.ToLower(v.TLS) == "xtls" {
 			core.StreamSettings.Security = "tls"
 			core.StreamSettings.TLSSettings = &coreObj.TLSSettings{}
 			if v.AllowInsecure {
@@ -370,6 +370,14 @@ func (v *V2Ray) Configuration(info PriorInfo) (c Configuration, err error) {
 				}
 				core.StreamSettings.TLSSettings.Alpn = alpn
 			}
+			// Flow
+			if v.Flow == "" {
+				v.Flow = "none"
+			}
+			vnext := core.Settings.Vnext.([]coreObj.Vnext)
+			vnext[0].Users[0].Flow = v.Flow
+			core.Settings.Vnext = vnext
+
 		} else if strings.ToLower(v.TLS) == "xtls" {
 			core.StreamSettings.Security = "xtls"
 			core.StreamSettings.XTLSSettings = &coreObj.TLSSettings{}
```

sorry for my dirty code change, I'm a very new Goer, so I have to do that

after the code change, rebuild v2raya with `./build.sh`

**Comment by mzz2017** [comment]
@ztatw Thanks for your code. I'll look into it.

**Comment by MarksonHon** [comment]
已支持

**Comment by libli** [comment]
用的docker版本，导入的vless+reality，无法使用。看docker使用的是v2ray-core，不是xray-core。
