### ISSUE TITLE
failed to create server > app/router: unexpect ip length: 0

### ISSUE THREAD

**Issue by szeller1111** [v2rayA/v2rayA#913]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
2.0.5 Openwrt Version 

2. What approach of installation do you install V2rayA?
opkg install v2raya
opkg install xray-core
opkg install luci-app-v2raya luci-i18n-v2raya-zh-cn

3. What is your operating system?
ImmortalWrt 21.02.5 X86/64 - Kernel 5.4.236 （On ESXi 6.7 u3）

### Description
配置好服务器、RouteA规则、出站规则后，点击“启动”按钮。系统提示“failed to start v2ray-core: unexpected exiting: check the log for more information”

### Steps to reproduce
如上

### Logs：
2023/04/14 06:49:57.600 [I] [io.go:429] Xray 1.8.0 (Xray, Penetrates Everything.) OpenWrt (go1.19.8 linux/amd64)
2023/04/14 06:49:57.600 [I] [io.go:429] A unified platform for anti-censorship.
2023/04/14 06:49:57.600 [I] [io.go:429] [Info] infra/conf/serial: Reading config: /etc/v2raya/config.json
2023/04/14 06:49:57.704 [I] [io.go:429] Failed to start: main: failed to create server > app/router: unexpect ip length: 0
2023/04/14 06:49:57.710 [W] [asm_amd64.s:1594] v2ray-core: exit status 23
2023/04/14 06:49:57.710 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information

### v2rayA setting and related screenshot
Paste your v2rayA setting and problem related screenshot.
<img width="619" alt="image" src="https://user-images.githubusercontent.com/36726401/231968603-1c0cbe66-d3ee-417f-bcc9-65a72e33f388.png">
服务器为HTTPS（Naiveproxy）协议，在其他v2raya平台运行正常

**Comment by MarksonHon** [comment]
RoutingA里面写了什么

**Comment by szeller1111** [comment]
> RoutingA里面写了什么

搞定了。RoutingA里有一行 ip(ext:"LoyalsoldierSite.dat:telegram")->proxy 注释掉就好了。估计是这个dat文件里没有telegram对应的ip字段

**Comment by MarksonHon** [comment]
https://v2raya.org/docs/manual/routinga/#%E5%B8%B8%E8%A7%81%E7%94%A8%E6%B3%95

**Comment by MarksonHon** [comment]
自动更新目前都没有；不过如果前者如果是通过软件包管理器安装的，那就可以通过软件包管理器更新，Arch Linux 下就是这样，后者目前大部分系统都没打包到，只有我们自建的 Windows 版本的 scoop 仓库能更新。
