### ISSUE TITLE
v2rayA的1.5.9.1698.1版本使用vmess(ws+tls)协议时，支持自定义pac吗？

### ISSUE THREAD

**Issue by 643104191** [v2rayA/v2rayA#915]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
1.5.9.1698.1
2. 你通过什么方式安装v2rayA
手动安装
3. 你所使用的操作系统
OpenWrt 22.03.3 r20028-43d71ad93e

### 描述问题：

v2rayA的1.5.9.1698.1版本使用vmess(ws+tls)协议时，支持自定义pac吗？
如果不支持，可以修改本地gfw文件来自定义pac吗？
如果可以，更新到本地gfw文件路径是啥？
修改完本地gfw文件后，是否需要重启openwrt？
---------------
如果不支持修改本地gfw文件来自定义pac，有其他办法吗？
---------------
如果1.x版本的v2rayA实在没办法实现自定义pac，2.x版本的v2rayA可以在使用vmess(ws+tls)协议时，支持自定义pac吗？

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。
![image](https://user-images.githubusercontent.com/27074730/232177384-3c7d39df-5043-49cd-8f6a-149b8c196498.png)

**Comment by huanghe2015** [comment]
软件本身如果用过[v2rayN](https://github.com/2dust/v2rayN)或者[v2rayNG](https://github.com/2dust/v2rayNG)这些就很好理解了，如果要做定制就要看v2ray的文档了。
PAC是一个单独的HTTP流量分配的脚本，可以以静态文件部署。可以使用[gfwlist2pac](https://github.com/petronny/gfwlist2pac)或者参阅[MDN](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file)自己实现。

**Comment by 643104191** [comment]
> 软件本身如果用过[v2rayN](https://github.com/2dust/v2rayN)或者[v2rayNG](https://github.com/2dust/v2rayNG)这些就很好理解了，如果要做定制就要看v2ray的文档了。 PAC是一个单独的HTTP流量分配的脚本，可以以静态文件部署。可以使用[gfwlist2pac](https://github.com/petronny/gfwlist2pac)或者参阅[MDN](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file)自己实现。

自己实现?那算了,操作不来
