### ISSUE TITLE
无法修改透明代理端口52345

### ISSUE THREAD

**Issue by aries1998** [v2rayA/v2rayA#921]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.5
2. 你通过什么方式安装v2rayA
docker
3. 你所使用的操作系统
ubuntu 22

### 描述问题：

无法修改透明代理端口52345 ， 具体重现步骤
1 v2raya的web界面停止v2ray客户端
2 停止v2raya   docker stop v2raya
3 修改/etc/v2raya/config.json中的透明代理端口为8080
4 启动v2raya , 配置文件端口为8080
5 web界面启动v2ray客户端, 配置文件端口又变回52345

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 sudo tail -n 50 /var/log/v2raya/v2raya.log

 # docker mode
 docker logs v2raya
 ```

 或者粘贴来自 Web 管理页面的日志

```shell
# 此处贴入运行日志



```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
预期行为，透明代理端口写死了是这个

**Comment by aries1998** [comment]
> 预期行为，透明代理端口写死了是这个

那就没法了
