### ISSUE TITLE
添加了一个server，选中并点击"启动"时提示 没有选中server。

### ISSUE THREAD

**Issue by honeway** [v2rayA/v2rayA#929]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA: docker latest

2. 你通过什么方式安装v2rayA: docker

3. 你所使用的操作系统
 fedora38

### 描述问题：

![image](https://user-images.githubusercontent.com/6339134/235562576-5bb2fe51-b151-4cb8-92f8-b91531c45ab0.png)

### v2rayA运行日志（Optional）：

 # docker mode
 docker logs v2raya
 ```
❯ docker logs v2raya
Quitting...
Quitting...

```

 或者粘贴来自 Web 管理页面的日志

```shell
2023/05/02 01:52:13.727 [E] [connection.go:88] failed to start v2ray-core: failed: no server is selected. please select at least one server


```

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。

**Comment by MarksonHon** [comment]
右边的选择按钮操作下

**Comment by honeway** [comment]
> 右边的选择按钮操作下

谢谢，解决了问题。 错误理解了 选中，以为前面的勾上就是选中了。
