### ISSUE TITLE
V2rayA 如何修改默認後臺管理端口2017

### ISSUE THREAD

**Issue by boss731** [v2rayA/v2rayA#932]
### 您想提出的功能特性是否和现有问题相关？

無法修改v2rayA默認2017管理端口

### 功能特性内容

V2rayA 如何修改默認後臺管理端口2017為其他任意端口，如果再可以改管理界面的背景會更好。謝謝

**Comment by huanghe2015** [comment]
修改端口：
“设置”→“地址与端口”

**Comment by mzz2017** [comment]
debian等发行版在/etc/default/v2raya改环境变量

**Comment by boss731** [comment]
> debian等發行版在/etc/default/v2raya改環境變量

謝謝  debian下已經找到0.0.0.0:2017   問題解決
