### ISSUE TITLE
v2rayA代理不成功

### ISSUE THREAD

**Issue by NUAAwanghe** [v2rayA/v2rayA#943]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.4
2. 你通过什么方式安装v2rayA
提供的脚本
3. 你所使用的操作系统
centos7和ubuntu20.04

### 描述问题：

我用azure搭建的vps，在windows下的v2rayN访问chatgpt、google没有问题
但是我在linux下搭建的v2raya，用export http_proxy方式或者v2raya的透明代理方式都不能正常工作
其中v2raya的透明代理，系统代理方式一直提示 系统不支持，请问是跟系统有关系吗？

**Comment by MarksonHon** [comment]
系统代理目前不支持Linux
