### ISSUE TITLE
http: server gave HTTP response to HTTPS client 

### ISSUE THREAD

**Issue by sss20081** [v2rayA/v2rayA#949]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.5-1
2. 你通过什么方式安装v2rayA
https://aur.archlinux.org/packages/v2raya
3. 你所使用的操作系统
Arch

### 描述问题：
Trojan节点http测试显示http: server gave HTTP response to HTTPS client ,连接节点无法使用。安卓端的v2rayNG可以正常使用。
![swappy-20230515-121403](https://github.com/v2rayA/v2rayA/assets/62577592/5e4cd5ba-3cbf-4800-b4b0-8f407f40c2c8)
![swappy-20230515-121440](https://github.com/v2rayA/v2rayA/assets/62577592/f7041f6e-707f-4881-b56e-822197d203d2)

### v2rayA运行日志（Optional）：
 sudo tail -n 50 /var/log/v2raya/v2raya.log 下图
![swappy-20230515-122215](https://github.com/v2rayA/v2rayA/assets/62577592/ccadf077-1549-4e22-9eef-66b53b67cd38)

### v2rayA设置以及相关截图
贴入v2rayA设置，以及问题相关的截图。
![swappy-20230515-121513](https://github.com/v2rayA/v2rayA/assets/62577592/14f91008-d173-46e4-a130-a976620ab017)

**Comment by lry127** [comment]
I ran into the same problem today, which was led  by the wrong Trojan password given. So check again if your subscription is still valid (e.g have the correct password, no bandwidth limit was excessed). You can use [orignal Trojan tool](https://github.com/trojan-gfw/trojan) to test your configuration.

**Comment by sss20081** [comment]
> I ran into the same problem today, which was led by the wrong Trojan password given. So check again if your subscription is valid (e.g have the correct password, no bandwidth limit was excessed). You can use the [orignal Trojan tool](https://github.com/trojan-gfw/trojan) to test your configuration.

Thanks for your reply, I'll try it if I have time.
Now I will close this issue
