### ISSUE TITLE
failed to get latest version of GFWList tags

### ISSUE THREAD

**Issue by YuanjianZhang** [v2rayA/v2rayA#963]
error info :
>fail in getting commit date of latest tag: parsing time "2023-06-01-03-24" as "200601021504": cannot parse "-06-01-03-24" as "01"

code link:
>https://github.com/v2rayA/v2rayA/blob/9b21697e08e676f360fa00429fe5370031fc10ce/service/core/v2ray/asset/dat/gfwlist.go#L44

maybe it can be fixed by this code:
```Go
 t, err := time.Parse("2006-01-02-15-04", tag) 
```

**Comment by CroMarmot** [comment]
LGTM

**Comment by CroMarmot** [comment]
https://github.com/v2rayA/dist-v2ray-rules-dat/issues/5
