### ISSUE TITLE
能用但是Failed to start v2raya.service: Unit v2raya.service not found.

### ISSUE THREAD

**Issue by xunx911** [v2rayA/v2rayA#981]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA：2.0.5

2. 你通过什么方式安装v2rayA：snap

3. 你所使用的操作系统：ubuntu22.04LTS

### 描述问题：
运行sudo systemctl start v2raya.service会报错
Failed to start v2raya.service: Unit v2raya.service not found.

先安装完snap商店中的v2raya后需要配置core等。
使用文档中的curl -Ls https://mirrors.v2raya.org/go.sh | sudo bash命令时报错(error: Failed to get release list, GitHub API response code:)，不用官方镜像也报错。打开.sh文件查看core的download link我这边点开是404不知道有没有关系。
最后是直接去下载了Zotero-6.0.26_linux-x86_64.tar.bz2并解压缩，然后打开v2raya就可以正常使用了。
但是运行sudo systemctl start v2raya.service会报错
Failed to start v2raya.service: Unit v2raya.service not found.

**Comment by MarksonHon** [comment]
用 snap 装了，服务会自动启动

**Comment by MarksonHon** [comment]
https://snapcraft.io/docs/service-management

**Comment by xunx911** [comment]
感谢
