### ISSUE TITLE
docker-v2raya host模式部署网关模式，服务器的网页无法访问

### ISSUE THREAD

**Issue by bluestar800** [v2rayA/v2rayA#982]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
V2.0.5

2. 你通过什么方式安装v2rayA
 docker host模式

3. 你所使用的操作系统
debian

### 描述问题：
代理：与规则端口所选模式一致
代理方式：redirect
分流模式：routingA

docker的宿主机的IP作为局域网的网关使用****.1。代理及直连均正常。

但是在另外一台设备上windows server系统，安装了jellyfin，局域网使用正常。路由器已经做了相应的jellyfin端口映射
1、**如果网关设置为v2raya的宿主机IP****.1，则只能内网访问，外网无法访问。**
2、如果网关设置为路由器的IP****.254，则内外网均能访问，

### v2rayA运行日志（Optional）：
无任何错误、报警

### v2rayA设置以及相关截图
![image](https://github.com/v2rayA/v2rayA/assets/30996974/f6503b12-64fe-484b-a0ee-fa012bac153e)

**Comment by dw763j** [comment]
> 使用钩子解决了
@bluestar800 可以请问下如何解决的吗，我也遇到了上级局域网下的服务无法访问的情况。

**Comment by bluestar800** [comment]
> > 使用钩子解决了
> > @bluestar800 可以请问下如何解决的吗，我也遇到了上级局域网下的服务无法访问的情况。

我现在用的是tproxy的代理模式，同时使用钩子，解决docker的防火墙问题，同时使用钩子将jellyfin的特定端口的流量不经过代理。这就解决了udp的问题，还有docker 的问题，以及特定端口代理的问题。具体的可以看下官网关于钩子的，bt下载，docker容器代理，然后只要针对钩子文件，进行整合和修改就可以了。相对来说很简单

**Comment by dw763j** [comment]
> > > 使用钩子解决了
> > > @bluestar800 可以请问下如何解决的吗，我也遇到了上级局域网下的服务无法访问的情况。
> 
> 我现在用的是tproxy的代理模式，同时使用钩子，解决docker的防火墙问题，同时使用钩子将jellyfin的特定端口的流量不经过代理。这就解决了udp的问题，还有docker 的问题，以及特定端口代理的问题。具体的可以看下官网关于钩子的，bt下载，docker容器代理，然后只要针对钩子文件，进行整合和修改就可以了。相对来说很简单

感谢回复，我检查后发现我的环境问题是由防火墙导致，添加路由input和forward后成功解决 #1219 #195 .
