### ISSUE TITLE
routeros container里运行v2raya的问题

### ISSUE THREAD

**Issue by csy59** [v2rayA/v2rayA#985]
我在routeros的容器里运行v2raya的docker版本，在web界面导入节点，选择节点点击启动的时候提示failed to start v2ray-core: ExecCommands: iptables -w 2 -N DROP_SPOOFING iptables v1.6.0: can'tinitialize iptables table `filter': Module is版本错误 可能 iptables 或您的内核需要升级。: exit status 3
这个错误是什么引起的，应该怎么解决啊

**Comment by JKSTAFF** [comment]
存在相同问题，使用的镜像是mzz2017/v2raya:latest

**Comment by crimsonqh** [comment]
存在相同问题，使用的镜像是mzz2017/v2raya:latest
环境是ikuai物理机使用docker

**Comment by bi4nbn** [comment]
目前是无解

**Comment by bi4nbn** [comment]
套个ubuntu在container里试试
