### ISSUE TITLE
【建议】如果加个按键，自动下载升级/选择 v2fly core 就好了

### ISSUE THREAD

**Issue by zz5678** [v2rayA/v2rayA#99]
目前貌似没有，还得升级 docker image ，这就引入了不少问题，比如，是不是要先备份现在的 服务器/订阅 数据神马的
最近 v2fly 内核更的好快啊，呵呵

**Comment by mzz2017** [comment]
如果你使用wiki中的挂载方式启动，就不需要备份和恢复

**Comment by zz5678** [comment]
就是不知道版本之间切换，是否数据格式/网页接口不一样什么的，比如，刚问了 v2raya.json 都变成 0.dat 了，哈哈，世界变化快，v2raya 也快。看着现在 0.7.12 还在用，已经到 1.0.1 版本了

**Comment by mzz2017** [comment]
使用wiki方式启动会自动迁移的

**Comment by zz5678** [comment]
> 如果你使用wiki中的挂载方式启动，就不需要备份和恢复

挂载？？？这么耳熟的字眼。。。。好像是几个版本之前就被你废掉的数据盘吧？
结果我去搜了一下，本项目下就没提过几次  :dizzy_face: :dizzy_face: :dizzy_face: 
![image](https://user-images.githubusercontent.com/67672527/94469483-c5fad780-01f8-11eb-9da8-946906a65cf7.png)

**Comment by mzz2017** [comment]
> > 如果你使用wiki中的挂载方式启动，就不需要备份和恢复
> 
> 
> 
> 挂载？？？这么耳熟的字眼。。。。好像是几个版本之前就被你废掉的数据盘吧？
> 
> 结果我去搜了一下，本项目下就没提过几次  :dizzy_face: :dizzy_face: :dizzy_face: 
> 
> ![image](https://user-images.githubusercontent.com/67672527/94469483-c5fad780-01f8-11eb-9da8-946906a65cf7.png)
> 
> 

多看看wiki，啥都有

https://github.com/mzz2017/v2raya/wiki

**Comment by zz5678** [comment]
在 胆战心惊 下，首先 从 docker 备份出 0.dat 后，升级到了最新版 …… wiki 并不是啥都有，庆幸的是 0.dat 最近的格式没有变啊，庆幸没有经历 v2raya.json 被放弃的大版本更迭时代啊 
:stuck_out_tongue_closed_eyes:
